### ISSUE TITLE
Worldborder

### ISSUE THREAD

**Issue by agoniaprivat** [GeyserMC/Geyser#2320] opened 2021-06-24 00:45 UTC
### What feature do you want to see added?

Make so geyser players can see a visible worldborder. 

### Are there any alternatives?

Could be an option to turn on. Could be any particle effect showing up instead, since Bedrock has not implemented javas worldborder system.

**Comment by Camotoy** [comment] 2021-06-24 00:48
Duplicate of #447. Thank you anyway!

**Closed** 2021-06-24 01:56 UTC
Labels: Feature Request
