### ISSUE TITLE
Server cant send data to bedrock client after random amount of time. "An exception occurred in RakNet >>> Operation not permitted" (Solved)

### ISSUE THREAD

**Issue by xManInWhitex** [GeyserMC/Geyser#1275] opened 2020-09-10 18:27 UTC
**Describe the bug**
My Bedrock-Clients seems to lose the connection to the Server Network but without disconnecting. I can move and commands will be redirected to the spigot server but every clickable block will not work (buttons, pressure plates, ...) and I'll get no feedback from the server. If I want to execute /spawn for example, the console of the Server says PlayerXY executed /spawn and teleports the client to the spawn location but on the side of the bedrock client the player will not be ported. If the Bedrock-Client does reconnect, the player stands on the position where the player should be.

The Inventory button on the screen of the bedrock client also won't work in this state.
I have not found defined way to break the connection. Sometimes it works for some commands sometimes it won't work directly after connecting.

If I'm using Geyser-Bungee no error messages appearing. When I'm using Geyser-Standalone I get some error messages.

`io.netty.channel.unix.Errors$NativeIoException: sendToAddress(..) failed: Operation not permitted`

**To Reproduce**
I have not found defined way to break the connection. Sometimes it works for some commands sometimes it won't work directly after connecting.

**Expected behavior**
Bedrock clients should keep connection

**Server Version**
I'm using BungeeCord#1533 with three PaperSpigot#187 Servers. (1.16.2)

**Geyser Version**
GeyserStandalone#379 and GeyserBungee#379

**Minecraft: Bedrock Edition Version**
I've tested with bedrock on Windows 10 (RTX Beta) and Android (1.16.40.02).

**Additional Context**
Full Geyser-Log: https://hasteb.in/efilowun
Geyser Dump: https://dump.geysermc.org/OSk9rrYpJFRmploYAAEg4BGgs5uTwLEU

**Comment by DoctorMacc** [comment] 2020-09-10 18:28
#1274 should likely properly disconnect the client and prevent the non-interactable world from occuring. Once that is merged this issue will have to be updated.

**Comment by xManInWhitex** [comment] 2020-09-10 18:32
But the player still be online on the java server but on another location as the bedrock client, so there is no disconnection signal from spigot or am I wrong?

**Comment by DoctorMacc** [comment] 2020-09-10 18:33
Hmm, perhaps not.

Can you also attach your BungeeCord + Spigot plugins list, and mention any notables within those lists?

**Comment by xManInWhitex** [comment] 2020-09-10 18:58
### Spigot Plugins of all Servers:
- AdvancedBan
- AreaShop
- AsyncWorldEdit
- Bank
- BestTools
- BungeeServerSigns
- **BungeeTabListPlus**
- ChatColor
- ChestCommands
- ChestShop
- ChestSort
- Citizens
- ClearLag
- CombatLogX
- CommandNPC
- Commandspy
- Core
- CoreProtect
- DisableJoinMessage
- Dynmap
- EditableSign
- EntityTrackerFixer
- **Essentials**
- EssentialsChat
- **EssentialsSpawn**
- Essentials_WarpGUI
- FreeBungeeChat
- HolographicDisplays
- HungerGames
- IPortal
- Jobs
- LWC
- Lands
- Microblocks
- MobArena
- **Multiverse-Core**
- **Multiverse-Inventories**
- **Multiverse-Portals**
- OpenInv
- PermissionsEx
- PlaceholderAPI
- Plot2Dynmap
- PlotSquared
- **ProtocolLib**
- QuickBoard
- React
- RemoteToolkitPlugin
- ScoreboardStats
- ServerSelectorX
- ServerSigns
- ServerTutorialPlus
- SignColours
- SimpleBroadcast
- StopCountdown
- TNTRun_reloaded
- TheNewEconomy
- UltimateTimber
- Vault
- VoteSend
- Votifier
- VotingPlugin
- WanderingNPC
- WelcomeBookRecoded
- WorldBorder
- WorldEdit
- WorldGuard

### Bungee Plugins:
- AdvancedBan 2.2.1
- BungeeKick
- BungeeMotd
- BungeePexBridge
- **BungeeTabListPlus 3.4.0**
- BungeeWhiteList
- FreeBungeeChat 2.4
- Mc Global Bell 1.8.3
- **protocolize-plugin**

I have **marked** plugins that I think may cause errors.

**Comment by toinouH** [comment] 2020-09-10 19:40
Could you please reproduce it without plugins ? 😀

**Comment by xManInWhitex** [comment] 2020-09-10 19:51
I'll test it.. Can you tell me what the error message "operation not permitted" means?

**Comment by DoctorMacc** [comment] 2020-09-10 19:51
I would assume it means something network-related.

**Comment by xManInWhitex** [comment] 2020-09-10 20:31
Okay, tested without any plugins and without bungee between.
Same error.

**Comment by DoctorMacc** [comment] 2020-09-10 20:32
The standalone spam or the teleport thing?

**Comment by xManInWhitex** [comment] 2020-09-10 20:33
Standalone spam.
The spam only occurs if the teleport thing is happening.
Its one and the same thing.

**Comment by xManInWhitex** [comment] 2020-09-10 20:35
I've also tested local on my PC and it worked.
Only on the server in the server center it won't work. It's an Ubuntu machine.

**Comment by xManInWhitex** [comment] 2020-09-10 20:47
I've noticed on my Windows PC that geyser inserted a rule into the firewall.
I don't know if it was able to do this on the Linux machine.
What rule has to be added?

**Comment by xManInWhitex** [comment] 2020-09-10 23:47
It seems to work with Spigot 1.16.3. I have to wait for paper 1.16.3 to be released, to test if paper is the problem.
If it works with paper 1.16.3 paper 1.16.2 was the problem.

**Comment by xManInWhitex** [comment] 2020-09-11 08:13
Bingo! Spigot-1.16.3 worked.. Paper-1.16.3 not.. Ideas?

**Comment by bundabrg** [comment] 2020-09-11 08:43
TIL that you can mark comments as outdated.

**Comment by xManInWhitex** [comment] 2020-09-11 09:23
> TIL that you can mark comments as outdated.

Jeah but it wont be shown as outdated on the mobile app of github.

**Comment by xManInWhitex** [comment] 2020-09-11 11:05
I just got noticed, that the error spam begins with the following error message.
(I don't know if the spam always starts with this message)

`2020-09-11 13:02:33.660 [Network Listener - #1] D - [0;37mCould not find packet for EntityFallPacket[0m
2020-09-11 13:02:35.379 [Network Listener - #1] E - An exception occurred in RakNet`

Is this helpful?

**Comment by soshimee** [comment] 2020-09-11 15:20
Similar issue here, but Bedrock players can move again if they die (probably using /suicide because they can’t move). It happens for me when they touch end rods.

**Comment by DoctorMacc** [comment] 2020-09-11 15:22
The EntityFallPacket can be successfully ignored.

Does the Operation Not Permitted happen on Spigot?

**Comment by xManInWhitex** [comment] 2020-09-11 15:27
I've tested it again. And it happens also for spigot now. 
So paper is not the problem..

**Comment by xManInWhitex** [comment] 2020-09-11 15:43
I can pm you FTP and console login data if you want to test it on my server?

**Comment by xManInWhitex** [comment] 2020-09-12 09:12
I opened a ticket with the serverhoster so that he can see if something is blocked in his network structure. Which ports must be open for Geyser to work?

**Comment by toinouH** [comment] 2020-09-12 09:26
The most time UDP 19132 BUT depending of your host provider it could be the same as your java port but UDP. Like your tcp is 25565 you have to open UDP 25565. Note you can join the discord for more help in #support

**Comment by DoctorMacc** [comment] 2020-09-12 13:57
If you're connected to the server, then there are no problems with the ports per se. That doesn't mean something else is acting up.

**Comment by xManInWhitex** [comment] 2020-09-12 14:42
My hoster told me that he couldn't find anything that was blocked and the ports are open. He also said that he couldn't help me any more and that I should talk to geyser's creators to find a solution. It can only be because of Geyser on my server, because if I start Geyser locally and link to the Java servers on the host, everything works. Thus, the bungee and paper servers cannot be the problem. But why it doesn't work directly on the Ubuntu machine? And why always after a random time, completely regardless of what the player does. It would be so nice to use Geyser. :( Is "raknet" of you or is it a standalone library?

**Comment by xManInWhitex** [comment] 2020-09-13 17:38
Can't I somehow see which network address Geyser wants to send data to when the error message comes?

**Comment by xManInWhitex** [comment] 2020-09-13 20:28
Seems like I solved the problem. I lowered the MTU to 700 and set the scoreboard timer to 5.

Now it seems to be working. I'll test again tomorrow and then close the ticket if it works.

**Comment by DoctorMacc** [comment] 2020-09-13 20:29
Interesting. It's probably one of those things as opposed to both.

**Comment by xManInWhitex** [comment] 2020-09-14 08:31
It's working! Thanks!

**Closed** 2020-09-14 08:31 UTC

**Comment by xManInWhitex** [comment] 2020-09-14 08:33
Can you mark my comment as solution? If someone else has the same problem.

**Comment by DoctorMacc** [comment] 2020-09-14 13:24
Don't think that's an option in GitHub.
