### ISSUE TITLE
Right clicking armor in your hand does not swap it with the currently equipped armor

### ISSUE THREAD

**Issue by abcdefghijklmnopqr88** [GeyserMC/Geyser#2262] opened 2021-06-07 17:23 UTC
### Describe the bug

Right clicking the armor you have in your hand does not swap it with the currently equipped armor.

### To Reproduce

1. Equip a chestplate.
2. Get a chestplate of a different material.
3. Hold it in your hand and right click.

### Expected behaviour

The chestplate in your armor slot and your hand should swap.

### Server Version and Plugins

This server is running Purpur version git-Purpur-1161 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

No plugins

### Geyser Dump

https://dump.geysermc.org/dbQIWFb333eT1jua1C8FOzCCRwBU1M7m

### Geyser Version

1.2.1-SNAPSHOT (git-master-aaa100b)

### Minecraft: Bedrock Edition Version

1.16.221

**Comment by Camotoy** [comment] 2021-06-07 17:25
I'm marking this as a feature request because this is intended behavior. Java Edition does not allow you to quick-equip if you already have something equipped in that armor slot. However, a plugin could be used to fix this.

**Comment by Tydium** [comment] 2021-07-10 00:54
This can now be done with the latest build of purpur^

It only now has the problem of a double animation. Im sure Gibbon already knows that tho. Right buddy :) [we know each other]

**Comment by YHDiamond** [comment] 2021-07-19 11:58
The ability to do this isn't possible in vanilla java and could be considered hacking in some pvp encounters, I personally don't think this belongs in geyser. Any opinions?

**Comment by Tydium** [comment] 2021-07-19 15:40
Nessesarily, your correct however for a server like mine that actually brought it back via the server side. Everyone who now uses Purpur has this option in the config. I would atleast like for geyser to check if its enabled in the config then disable its own check to stop the double animation that plays.

**Comment by Chew** [comment] 2021-07-19 16:02
In theory, to maintain equilibrium (and to avoid another dependency) you'd want this to be a config option.

**Comment by Tydium** [comment] 2021-07-21 01:07
I believe Camo said something about that in the [funky monkey] Chat about adding some type of check.

**Comment by Camotoy** [comment] 2021-07-21 01:16
It's definitely possible, though I don't know if we will. It's definitely low priority either way.

**Comment by gibbon27** [comment] 2021-07-22 01:03
hi

**Comment by RednedEpic** [comment] 2022-04-23 17:22
This has been implemented as part of https://github.com/GeyserMC/Geyser/commit/e92633d65771bac061cadc22c95e114122af87e4.

**Closed by RednedEpic** 2022-04-23 17:22 UTC
Labels: Feature Request, Priority: Low
