### ISSUE TITLE
ClientboundTeleportEntityPacket is spamming the server console

### ISSUE THREAD

**Issue by lodzen** [GeyserMC/Geyser#5167] opened 2024-11-27 11:35 UTC
### What feature do you want to see added?

I can see thousands of messages for ClientboundTeleportEntityPacket because the loggin level is INFO in the referenced code.

### Are there any alternatives?

Can you update the level to SEVERE or DEBUG to decrease the messages?

**Comment by onebeastchris** [comment] 2024-11-27 11:37
Duplicate of https://github.com/GeyserMC/Geyser/issues/5141 - it's a small debug message left over from the 1.21.3 update. We're currently working on properly implementing it properly; but if that takes much longer we'll remove the message entirely sooner

**Closed by onebeastchris** 2024-11-27 11:37 UTC
Labels: Feature Request
