### ISSUE TITLE
Bug with water buckets on mobile devices

### ISSUE THREAD

**Issue by Osicool** [GeyserMC/Geyser#952] opened 2020-07-14 14:46 UTC
**Describe the bug**
On mobile devices connected through a geyser proxy, when you want to get water in your bucket, you usually would tap the water to get it. On the mobile device it appears as if you have the bucket of water on hand but for others you do not. If you go to place down the water it will place for a split second and then go as you haven't actually picked up the bucket of water. What you need to do to actually get the water bucket is hold down and go to break the block below (against the expected method of tapping to get water). Then to place the water, you also have to hold down. It basically is the opposite of how its meant to be. This is only on mobile as when I checked, Minecraft Bedrock Windows 10 Edition has the expected behaviour.

**To Reproduce**

<!---  1. Join on a bedrock edition mobile client (I'm using an iPad) through the geyser proxy
<!---  2. Get an empty bucket and find some water.
<!---  3. Just tap on the water and as you can see you have the water (but thats only client side)
<!---  4. Tap on the ground somewhere else, you will place down the water but then it will go as you don't actually have the water.
<!--- 5. For you to actually get this water you need to hold down and the block below will start breaking, then you will get the water.
<!--- 6. Then hold down on the ground to place the bucket of water and it will be placed.

**Expected behavior**
On mobile, the expected behaviour is that you tap to collect and place down water instead of holding down to collect and place water

**Screenshots / Videos**
Java Edition perspective - https://streamable.com/0o5afq
Mobile Bedrock Edition perspective - https://streamable.com/i0tplg

**Server Version**
Running Paper version git-Paper-79 (MC: 1.16.1)

**Geyser Version**
Geyser version 1.0.0 (git-1.16-pr-83ae319)

**Minecraft: Bedrock Edition Version**
1.16.1

**Additional Context**
Not that I know of.

**Comment by rtm516** [comment] 2020-07-14 14:47
Duplicate of https://github.com/GeyserMC/Geyser/issues/321 and we have a WIP PR https://github.com/GeyserMC/Geyser/pull/767

**Closed by rtm516** 2020-07-14 14:47 UTC

**Comment by DoctorMacc** [comment] 2020-07-14 14:48
Thank you for reporting regardless!
