### ISSUE TITLE
Client Time out

### ISSUE THREAD

**Issue by LynkZero** [GeyserMC/Geyser#4247] opened 2023-10-26 01:28 UTC
### Describe the bug

Hello! I recently updated to a new version of Geyser today and all of my bedrock mobile players have been having their games crash after trying to join my server, Im not sure if its their Minecraft's, or geyser, but i have a feeling it may be geyser.

### To Reproduce

1: load server with Viaversion, Veinminer, Marriage Master, Single Player Sleep, Tree Feller, World Edit, and World Guard and an old version of Geyser/Floodgate
2: Delete the old version of Geyser/Floodgate
3: Install New version
4: Config new version, then restart server
5: join server on bedrock

### Expected behaviour

Game will crash, either with a Client timeout message or a normal Disconnect, on  players side, either a normal disconnect, or a full game crash

### Server Version and Plugins

Server Version is 1.20 Spigot, and the Plugins are listed above

### Geyser Dump

https://dump.geysermc.org/ilbbGBHZaRA30BrKyBYJynsTcbpgp0Nm

### Geyser Version

Geyser build 2.2.0 Spigot

### Additional Context

like I said, Im not sure if this is a bedrock problem or a geyser problem, and my hosting provider is serverminer. my players that disconnect are specifically running tablets, Nintendo Switches, and Phones, but computer bedrock players seem to be able to connect

**Comment by nasiridrishi** [comment] 2023-10-26 02:03
Have this issue as well

**Comment by Konicai** [comment] 2023-10-26 02:16
Duplicate of #4240

**Closed by Konicai** 2023-10-26 02:17 UTC
