### ISSUE TITLE
Bedrock Edition players receive a customized command list

### ISSUE THREAD

**Issue by DJelly4K** [GeyserMC/Geyser#2513] opened 2021-09-04 18:41 UTC
### What feature do you want to see added?

Bedrock Edition players can receive a customized command list, some commands will be hidden, and the command list can be configured to display

### Are there any alternatives?

None.
Maybe...

**Comment by Konicai** [comment] 2021-09-04 18:52
This is a duplicate of https://github.com/GeyserMC/Geyser/issues/2389

**Closed by Konicai** 2021-09-04 18:52 UTC
Labels: Feature Request
