### ISSUE TITLE
upnp support

### ISSUE THREAD

**Issue by LegacyGamerHD** [GeyserMC/Geyser#908] opened 2020-07-06 15:24 UTC
**upnp** 

it makes it more easy for users that host on there pc for sesion for friends also most people dont know what portfording is and its most its anbled on the rouder or it quick toggle

**Alternatives?**
opning a port my self

**Comment by DoctorMacc** [comment] 2020-07-06 15:25
I don't think uPnP works this way, but I'm not a networking expert. Seems like it's only for the local network.

**Comment by LegacyGamerHD** [comment] 2020-07-06 15:26
well its Universal Plug and Play pmmp hase it even nukkit it think

**Comment by DoctorMacc** [comment] 2020-07-06 15:28
If you could provide a source for how this works for them, that would be extensively helpful.

**Comment by LegacyGamerHD** [comment] 2020-07-06 15:29
https://en.wikipedia.org/wiki/Universal_Plug_and_Play#:~:text=UPnP%20assumes%20the%20network%20runs,actions%2C%20data%20transfer%20and%20eventing.&text=UPnP%20devices%20are%20%22plug%20and,working%20configurations%20with%20other%20devices.

**Comment by DoctorMacc** [comment] 2020-07-06 15:31
I’m reading that all happens on the *same* network.

**Comment by LegacyGamerHD** [comment] 2020-07-06 15:32
well i can conect to outside team viewer , pasec uses it

**Comment by LegacyGamerHD** [comment] 2020-07-06 15:34
https://github.com/pmmp/PocketMine-MP/blob/stable/src/pocketmine/network/upnp/UPnP.php

**Comment by rtm516** [comment] 2021-06-05 01:12
https://github.com/CloudburstMC/UPnP

**Comment by RednedEpic** [comment] 2022-01-22 01:42
Thanks for the suggestion, however this is a bit out of scope for Geyser and the behavior may not work as intended on non-standalone platforms. Plus, it would be a bit odd for the Bedrock server to "portforward itself", while the Java server remains inaccessible without manual portforwarding. Definitely a good idea as an extension though which it very likely will become, but thanks for opening this suggestion anyway!

**Closed by RednedEpic** 2022-01-22 01:42 UTC
Labels: Feature Request
