### ISSUE TITLE
Random Chunks Not Loading For Bedrock Players.

### ISSUE THREAD

**Issue by planefr** [GeyserMC/Geyser#3499] opened 2023-01-10 07:38 UTC
### Describe the bug

I am running a Geyser Spigot server (1.19.3) with floodgate and Bedrock players have a problem where some chunks just will not load and it requires a relog to fix however other chunks end up not loading, thus requiring relogs quite often.   This seems to happen on every render distance setting.  I have changed the server side render distance (Currently set at 5 was set to the default before which I believe is 10.) and that has not changed anything either.  Tried multiple server optimization tips.  This happens for me as well when I try to play on bedrock on PC so I don't think its a network or Xbox problem. 

My server console would keep spitting this out at me when I would enter the unloaded chunk.
[error.txt](https://github.com/GeyserMC/Geyser/files/10380091/error.txt)

### To Reproduce

1. Start Server
2. Join On Bedrock
3. Walk around for about 30 seconds and you'll probably encounter one.

### Expected behaviour

chunks to load properly.

### Screenshots / Videos

![mc chunk error](https://user-images.githubusercontent.com/122346005/211488565-3966dd8c-7163-41a6-b3d3-3419b8050ad7.png)

### Server Version and Plugins

This bug happens with no plugins installed other than Geyser and floodgate.

### Geyser Dump

https://dump.geysermc.org/a9vhnUeCxoaHQbdIb2yZY2dxKuOEADRa

### Geyser Version

2.10-SNAPSHOT Build#1270

### Minecraft: Bedrock Edition Device/Version

Bedrock Edition (PC,XBOX)

### Additional Context

Any help would be very much appreciated!  this is my first time running a minecraft server so I was expecting some issues but I cant find anyone else with the same issue as me.

**Comment by Kas-tle** [comment] 2023-01-10 08:05
Duplicate of https://github.com/GeyserMC/Geyser/issues/3490

Should be fixed by https://github.com/GeyserMC/Geyser/pull/3498

You can resolve this by either:
- Switching to [Paper](https://papermc.io) 
- Trying the build in my recent PR (download the correct [build artifact](https://github.com/GeyserMC/Geyser/actions/runs/3880706785) for your platform and unzip for the jar)

**Closed** 2023-01-10 16:49 UTC
