### ISSUE TITLE
Issue with controlling striders 

### ISSUE THREAD

**Issue by datrandomduggy** [GeyserMC/Geyser#2066] opened 2021-03-23 05:52 UTC
### Describe the bug

Using a warped fungus on a stick I am not able to make a strider move but am able to ride the skidder just not control it

### To Reproduce

1. place a saddle on strider mob
2. ride the strider 
3. attempt to use warped fungus on a stick to control the movement of the strider
4. strider stays in one place and never moves

### Expected behaviour

being able to use a warped fungus on a stick to control a strider when riding on it

### Screenshots / Videos

video of the bug https://www.youtube.com/watch?v=BJg1Jn4g9cQ

### Server Version and Plugins

This server is running CraftBukkit version 3019-Spigot-bff5261-ee5006d (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Plugins:
1. Geyser
2. Floodgate

DataPacks(if they matter)
1. Vannila Tweaks armour statues v2.8.1
2. Vannila Tweaks double shulker shells v1.3.0
3. Vannila Tweaks durability ping v1.1.0
4. Vannila Tweaks more mob heads v2.8.2
5. Vannila Tweaks multiplayer sleep v2.5.2
6. Vannila Tweaks player head drops v1.1.0
7. Vannila Tweaks unlock all recipes v2.0.1
8. Vannila Tweaks villager work station highlights v1.1.0
9. Vannila Tweaks xp management v1.1.0

### Geyser Dump

https://dump.geysermc.org/NLjnJiOHHgJiaRrF9a9gyC9vCmltQmWx

### Geyser Version

1.2.0-SNAPSHOT (git-temp-fix-eeb729f) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.210)

### Minecraft: Bedrock Edition Version

1.16.210

**Comment by Camotoy** [comment] 2021-03-23 14:24
This is a duplicate of #638. Regardless, thank you for reporting!

**Closed by Camotoy** 2021-03-23 14:24 UTC
