### ISSUE TITLE
&k Broken on consoles

### ISSUE THREAD

**Issue by spookymgmt** [GeyserMC/Geyser#4425] opened 2024-02-08 01:46 UTC
### Describe the bug

The &k which obfuscates text, just shows as a "." on console edition now.

### To Reproduce

Go latest, type &k:hi, it resolves to just . on console

### Expected behaviour

Should show the magical formatting like usual.

### Server Version and Plugins

Spigot version 1.20.1

### Geyser Dump

https://dump.geysermc.org/CbaLJBPAWKns1PjympMJqK9c932X52Ye

### Geyser Version

Run 426 https://github.com/GeyserMC/Geyser/actions/runs/7816162067

### Minecraft: Bedrock Edition Device/Version

Latest ps5

**Comment by onebeastchris** [comment] 2024-02-08 09:40
Could you test on a Bedrock singleplayer world whether `§kHi` works?
This sounds like a potential Bedrock bug to me

For all symbols, see here:
https://minecraft.fandom.com/wiki/Formatting_codes

**Comment by Kas-tle** [comment] 2024-03-17 04:45
This is likely not an issue with consoles and is instead how MC intends to display when unicode font is forced by unicode characters on the sign. This is considered intended behavior and is clientside, so closing.
See https://bugs.mojang.com/browse/MCPE-164625.

**Closed by Kas-tle** 2024-03-17 04:45 UTC
Labels: Waiting On Response
