### ISSUE TITLE
Remove java account sign in or make ip remember

### ISSUE THREAD

**Issue by KOT4N** [GeyserMC/Geyser#2559] opened 2021-10-01 15:54 UTC
### What feature do you want to see added?

Hello, my server without online mode and when people come in, you need to constantly enter Java data. Okay if your password s1s1s1s etc, but if you have pass from generator is very hard.

Can you add ip remember or skip auth?

**Comment by Chew** [comment] 2021-10-01 17:33
Duplicate of #1977 

See Redned's message here: https://github.com/GeyserMC/Geyser/issues/1977#issuecomment-886088987

The "Skip Auth" you're looking for would be [Floodgate](https://githuh.com/GeyserMC/Floodgate).

**Closed by Chew** 2021-10-01 17:33 UTC
Labels: Feature Request

**Comment by Camotoy** [comment] 2021-10-01 17:35
Clarification on Redned's comment: storing any sort of authentication data is very insecure. We would need to cache data in some way that it is still readable by the Geyser instance. And that's storing authentication tokens (or, worse, usernames/passwords) on some remote server that the owner of that account cannot control.
