### ISSUE TITLE
Can't swim through 1 block gaps 

### ISSUE THREAD

**Issue by ZeroX4212** [GeyserMC/Geyser#1855] opened 2021-01-20 14:48 UTC
**Describe the bug**

When I try to swim through 1 block gaps, it doesn't let me go through

**To Reproduce**

1. Go in water
2. Sprint in water to swim
3. Try to go through a 1 block gap

**Expected behavior**

Being able to go through 1 block gaps

**Screenshots / Videos**

https://youtu.be/8h2sdcGMNKk

**Geyser Dump**

https://dump.geysermc.org/eq4dBndN1p32Zphwqc5tKoCWVdbV56pg

**Minecraft: Bedrock Edition Version**

1.16.201, 1.16.200, 1.16.100

**Comment by rtm516** [comment] 2021-01-20 15:19
Thanks for the report but this is a duplicate of https://github.com/GeyserMC/Geyser/issues/1724
Please also try out this PR https://github.com/GeyserMC/Geyser/pull/1814

**Closed by rtm516** 2021-01-20 15:19 UTC
