### ISSUE TITLE
Bedrock players can not use a book and quill.

### ISSUE THREAD

**Issue by CrystalVortex** [GeyserMC/Geyser#3453] opened 2022-12-12 16:57 UTC
### Describe the bug

Bedrock players can not use a book and quill, when the click on a signed book on a lectern it doesn't do anything.

### To Reproduce

get a lectern.
get a book and write some text then sign and close it.
place the book on the lectern.
log in on bedrock edition and try to open the book and quill.

### Expected behaviour

The book and quill opens on bedrock edition.

### Server Version and Plugins

 git-Paper-173 (MC: 1.19.2)
Plugins (23): CasinoPlugin, ChestShop, CommandBlocker, CoreProtect, DiscordSRV, EasyWhitelist*, Essentials, floodgate, Geyser-Spigot, GeyserHacks, GriefPrevention, HolographicDisplays, ItemSlotMachine, LiveKit, LuckPerms, OnePlayerSleep*, OpenInv, ProtocolLib, SkinsRestorer, Vault, WorldEdit, WorldGuard, YamipaPlugin

### Geyser Dump

https://dump.geysermc.org/CQnyRckAXf9247PlalFnX7PqjkLFa6mX

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-3d66d27) (Java: 1.19.1 - 1.19.2, Bedrock: 1.19.20 - 1.19.50)

### Minecraft: Bedrock Edition Device/Version

Windows, IOS, Android (1.19.50)

**Comment by neco222** [comment] 2022-12-28 10:19
I can't open the book I put on the lectern
I can't see my inventory after clicking.
If you open the chest and then open your inventory again, it will return to its original state.

**Comment by onebeastchris** [comment] 2023-04-20 22:40
Does this issue still occur on the latest version of Geyser?

**Comment by neco222** [comment] 2023-04-20 23:43
Correction Confirmed

**Comment by onebeastchris** [comment] 2023-04-21 00:14
that is weird.. for me, the following happens:
- editing a book and quill & signing it works, when the book is held
- when the signed book is placed down, it can be opened fine

the only thing that does not work atm (latest version of Geyser) would be to edit an empty book and quill while it is on a lectern

**Comment by onebeastchris** [comment] 2024-03-09 12:54
Going to close this due to no further response - both writing books and opening them on lecterns works fine currently.

**Closed by onebeastchris** 2024-03-09 12:55 UTC
Labels: Confirmed Bug
