### ISSUE TITLE
Not seeing other players on maps.

### ISSUE THREAD

**Issue by BrianTheBrain11** [GeyserMC/Geyser#3829] opened 2023-06-08 05:51 UTC
### Describe the bug

I do not see my friend in the map. I made sure to craft the map with a compass. My friend cannot see me on the same/different map either. Tried restarting our games, and the server.

### To Reproduce

1. Compile spigot from the 1.20 BuildTools.jar.
2. Add the latest 1.20 Geyser for spigot, and the latest floodgate for spigot.
3. Craft a map with one compass and 8 paper.

### Expected behaviour

I expect to see my friend playing in java on the map, but I do not. My friend cannot see me in Bedrock on the map either.

### Server Version and Plugins

Geyser 1.20
Floodgate latest

### Geyser Version

1.20

### Minecraft: Bedrock Edition Device/Version

Minecraft for Windows

**Comment by hw2007** [comment] 2023-06-08 15:59
This might be as intended, because on java you can't see other players on maps, so they might have intentionally disabled this to make it fair. Not sure though

**Comment by BrianTheBrain11** [comment] 2023-06-09 05:01
It is not a standard map, but a "locator" map crafted with a compass. https://minecraft-archive.fandom.com/wiki/Locator_Map

**Comment by onebeastchris** [comment] 2023-06-11 01:59
Duplicate of https://github.com/GeyserMC/Geyser/issues/3525

**Closed by onebeastchris** 2023-06-11 01:59 UTC
