### ISSUE TITLE
Geyser Fabric - Server Crash on startup

### ISSUE THREAD

**Issue by TwoPointInfinity** [GeyserMC/Geyser#3439] opened 2022-12-07 23:13 UTC
### Describe the bug

with geyser, or both geyser and floodgate my server crashes when starting. Not sure if this is a mod conflict or an issue with geyser fabric but i cannot get it to work. 

### To Reproduce

use geyser fabric
use other mods
crash maybe?

### Expected behaviour

doesnt crash on statup

### Screenshots / Videos

https://pastebin.com/7EAfbmQh

### Server Version and Plugins

Minecraft 1.19.2 with Fabric Loader 0.14.10
	- adventure-platform-fabric 5.4.0-SNAPSHOT via floodgate
	- antixray 1.2.6
	- autoconfig1u 3.4.0 via disfabric
	- autowhitelist 1.1.2-compat-mcdiscordchat.2.1.0
	- banhammer 0.5.4+1.19.2
	- better-recipes 1.3.0
	- bluemap 3.6
	- carpet 1.4.84
	- chunky 1.3.38
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 8.2.88
	- cloud 1.8.0-SNAPSHOT via tabtps-fabric
	- cloud_commandframework_cloud-brigadier_ 1.8.0-SNAPSHOT via cloud
	- cloud_commandframework_cloud-core_ 1.8.0-SNAPSHOT via cloud
	- cloud_commandframework_cloud-minecraft-extras 1.8.0-SNAPSHOT via tabtps-fabric
	- cloud_commandframework_cloud-services_ 1.8.0-SNAPSHOT via cloud
	- club_minnced_discord-webhooks 0.8.0 via banhammer
	- clumps 9.0.0+11
	- collective-fabric 5.22
	- com_electronwill_night-config_core 3.6.5 via no-shield-delay
	- com_electronwill_night-config_toml 3.6.5 via no-shield-delay
	- com_fasterxml_jackson_core_jackson-annotations 2.13.2 via autowhitelist
	- com_fasterxml_jackson_core_jackson-core 2.13.2 via autowhitelist
	- com_fasterxml_jackson_core_jackson-databind 2.13.2.2 via autowhitelist
	- com_google_code_findbugs_jsr305 3.0.2 via disfabric
	- com_konghq_unirest-java_standalone 3.13.4 via disfabric
	- com_moandjiezana_toml_toml4j 0.7.2 via antixray
	- com_neovisionaries_nv-websocket-client 2.14 via autowhitelist
	- com_squareup_okhttp3_okhttp 4.9.3 via autowhitelist
	- com_squareup_okio_okio 2.8.0 via autowhitelist
	- com_typesafe_config 1.4.2 via tabtps-fabric
	- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
	- disfabric 1.3.11
	- doubledoors-fabric 3.8
	- editsign 2.6.0
	- fabric-api 0.66.0+1.19.2
	- fabric-api-base 0.4.12+93d8cb8290 via fabric-api
	- fabric-api-lookup-api-v1 1.6.10+93d8cb8290 via fabric-api
	- fabric-biome-api-v1 9.0.18+c6af733c90 via fabric-api
	- fabric-block-api-v1 1.0.0+12bfe4ea90 via fabric-api
	- fabric-command-api-v1 1.2.12+f71b366f90 via fabric-api
	- fabric-command-api-v2 2.1.8+93d8cb8290 via fabric-api
	- fabric-commands-v0 0.2.29+df3654b390 via fabric-api
	- fabric-containers-v0 0.1.35+df3654b390 via fabric-api
	- fabric-content-registries-v0 3.4.1+6064db2a90 via fabric-api
	- fabric-convention-tags-v1 1.1.2+93d8cb8290 via fabric-api
	- fabric-crash-report-info-v1 0.2.6+aeb40ebe90 via fabric-api
	- fabric-data-generation-api-v1 5.2.3+b598f4ac90 via fabric-api
	- fabric-dimensions-v1 2.1.32+0dd10df690 via fabric-api
	- fabric-entity-events-v1 1.5.0+a1d87cb890 via fabric-api
	- fabric-events-interaction-v0 0.4.29+c6af733c90 via fabric-api
	- fabric-events-lifecycle-v0 0.2.29+df3654b390 via fabric-api
	- fabric-game-rule-api-v1 1.0.22+c6af733c90 via fabric-api
	- fabric-item-api-v1 1.5.8+93d8cb8290 via fabric-api
	- fabric-item-groups-v0 0.3.33+70efcffe90 via fabric-api
	- fabric-language-kotlin 1.8.7+kotlin.1.7.22
	- fabric-lifecycle-events-v1 2.2.0+33ffe9ec90 via fabric-api
	- fabric-loot-api-v2 1.1.7+83a8659290 via fabric-api
	- fabric-loot-tables-v1 1.1.10+9e7660c690 via fabric-api
	- fabric-message-api-v1 5.0.4+93d8cb8290 via fabric-api
	- fabric-mining-level-api-v1 2.1.18+33fbc73890 via fabric-api
	- fabric-networking-api-v1 1.2.5+c6af733c90 via fabric-api
	- fabric-networking-v0 0.3.22+df3654b390 via fabric-api
	- fabric-object-builder-api-v1 4.1.0+06e0e25190 via fabric-api
	- fabric-particles-v1 1.0.11+79adfe0a90 via fabric-api
	- fabric-permissions-api-v0 0.2-SNAPSHOT via geyser-fabric
	- fabric-registry-sync-v0 0.9.26+c6af733c90 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.16+12bfe4ea90 via fabric-api
	- fabric-rendering-fluids-v1 3.0.8+c6af733c90 via fabric-api
	- fabric-resource-conditions-api-v1 2.1.0+aae9039d90 via fabric-api
	- fabric-resource-loader-v0 0.7.3+3e1ba48e90 via fabric-api
	- fabric-screen-handler-api-v1 1.3.1+1cc24b1b90 via fabric-api
	- fabric-transfer-api-v1 2.1.1+93d8cb8290 via fabric-api
	- fabric-transitive-access-wideners-v1 1.3.1+42d99c3290 via fabric-api
	- fabricloader 0.14.10
	- fabsit 1.5.3+1.19
	- ferritecore 5.0.3
	- fiber 0.23.0-2 via collective-fabric
	- floodgate 2.2.0-SNAPSHOT
	- geyser-fabric 2.1.0-SNAPSHOT
	- hologram-api 0.2.2+1.19 via holograms
	- holograms 1.4.0+1.19.2
	- horsestonks 1.0.1
	- invview 1.4.9-1.19+
	- io_leangen_geantyref_geantyref 1.3.13 via cloud
	- itemflexer 1.3.0
	- java 19
	- krypton 0.2.1
	- leaf-decay 1.5.0-1.19.2
	- ledger 1.2.5
	- luckperms 5.4.46
	- microconfig 2.2.1 via itemflexer
	- midnightlib 0.5.2 via repurposed_structures
	- minecraft 1.19.2
	- monsters_in_the_closet 1.0.3+1.19
	- mysql_mysql-connector-java 8.0.29 via banhammer
	- net_dv8tion_jda 5.0.0-alpha.22 via autowhitelist
	- net_kyori_adventure-api 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-key 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-platform-api 4.1.0 via adventure-platform-fabric
	- net_kyori_adventure-serializer-configurate4 4.11.0 via tabtps-fabric
	- net_kyori_adventure-text-feature-pagination 4.0.0-SNAPSHOT via tabtps-fabric
	- net_kyori_adventure-text-logger-slf4j 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-text-minimessage 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-text-serializer-gson 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-text-serializer-legacy 4.11.0 via tabtps-fabric
	- net_kyori_adventure-text-serializer-plain 4.11.0 via adventure-platform-fabric
	- net_kyori_examination-api 1.3.0 via adventure-platform-fabric
	- net_kyori_examination-string 1.3.0 via adventure-platform-fabric
	- net_sf_trove4j_trove4j 3.0.3 via autowhitelist
	- no-shield-delay 1.0.0
	- nochatreports 1.19.2-v1.13.12
	- org_apache_commons_commons-collections4 4.4 via autowhitelist
	- org_jetbrains_annotations 22.0.0 via banhammer
	- org_jetbrains_kotlin_kotlin-reflect 1.7.22 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.22 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.22 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.22 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.5 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1 via fabric-language-kotlin
	- org_json_json 20210307 via banhammer
	- org_slf4j_slf4j-api 1.7.32 via banhammer
	- org_spongepowered_configurate-core 4.1.2 via tabtps-fabric
	- org_spongepowered_configurate-hocon 4.1.2 via tabtps-fabric
	- org_xerial_sqlite-jdbc 3.36.0.3 via banhammer
	- org_yaml_snakeyaml 1.31 via viafabric
	- packet_tweaker 0.3.0+1.18.2 via server_translations_api
	- phosphor 0.8.1
	- placeholder-api 2.0.0-beta.7+1.19 via holograms
	- plan 5.5 build 2100
	- repurposed_structures 6.1.2+1.19
	- semblance 1.1.3
	- server-hats 0.11
	- server_translations_api 1.4.14+1.19-rc2 via ledger
	- serverstop 0.1.1
	- sgui 1.1.3+1.19.1 via banhammer
	- tabtps-fabric 1.3.15
	- terralith 2.3
	- vanish 1.4.3
	- viafabric 0.4.9+19-main
	- viafabric-mc119 0.4.9+19-main via viafabric
	- viaversion 4.4.3-SNAPSHOT via viafabric
	- voicechat 1.19.2-2.3.15

### Geyser Dump

server could not load to dump geyser

### Geyser Version

update #1248

### Minecraft: Bedrock Edition Device/Version

1.19.2

### Additional Context

im sorry if this was resolved somewhere else, i did look and i could not find it. I also could not figure the crash report or what the issue could be. Does geyser have any known compatibility issues with any of my installed mods?

**Comment by Camotoy** [comment] 2022-12-07 23:21
Looks like this is a duplicate of https://github.com/GeyserMC/Geyser/issues/3423. Thanks.

**Closed by Camotoy** 2022-12-07 23:21 UTC
