### ISSUE TITLE
Anvils not working on 1.20 Geyser Spigot

### ISSUE THREAD

**Issue by Bayanicool** [GeyserMC/Geyser#3899] opened 2023-06-20 03:27 UTC
### Describe the bug

You cannot add enchants in an anvil or rename a nametag

### To Reproduce

Try renaming a nametag or using the anvil for any uses.

### Expected behaviour

It would work.

### Screenshots / Videos

https://i.imgur.com/DNYcnrS.png

### Server Version and Plugins

1.20 
https://i.imgur.com/E83RyM2.png

### Geyser Dump

https://dump.geysermc.org/KAdP2J5AKkITII2jNrT7ylGo6KZgjZ0B

### Geyser Version

6-18-2023 GEYSER NEWEST

### Minecraft: Bedrock Edition Device/Version

NEWEST 6-18-2023

### Additional Context

THIS HAS BEEN HAPPENING SINCE 1.20

**Comment by Konicai** [comment] 2023-06-20 03:56
Duplicate of #3866

**Closed by Konicai** 2023-06-20 03:56 UTC
