### ISSUE TITLE
Hotbar out of sync

### ISSUE THREAD

**Issue by valaphee** [GeyserMC/Geyser#4968] opened 2024-08-15 08:48 UTC
### Describe the bug

When items are moved in the hotbar, it doesn't immediately update.

### To Reproduce

1. Open the inventory
2. Move items in/out of the hotbar

### Expected behaviour

Hotbar should be kept in sync

### Screenshots / Videos

https://www.youtube.com/watch?v=v6YRW6oXVMU

### Geyser Version

0bc39d5

**Comment by onebeastchris** [comment] 2024-08-15 09:51
Update Geyser. This has been resolved in https://github.com/GeyserMC/Geyser/commit/4f7e9fca9cea213d5968401fdfc60a2495d6bec9. For the future, please provide a Geyser dump too!

**Closed by onebeastchris** 2024-08-15 09:51 UTC

**Comment by onebeastchris** [comment] 2024-08-15 18:21
This issue is a duplicate of https://github.com/GeyserMC/Geyser/issues/4966
