### ISSUE TITLE
Scaffolding can't work correctly

### ISSUE THREAD

**Issue by youwen233** [GeyserMC/Geyser#1050] opened 2020-07-29 06:48 UTC
**Describe the bug**

Scaffolding can't work correctly, when I was trying to climb up, it felt just like I was jumping on the normal block.
When I was trying to go down, it felt just like I was holding Shift on the stone, and I couldn't get down.

**To Reproduce**

1.Join the server
2.Place some scaffolding
3.climb on them

**Expected behavior**

Scaffolding's can work just like on Java Edition

**Screenshots / Videos**

https://dl.alidingtalk.fun/GD/Temp/Minecraft%202020-07-29%2014-34-20.mp4?preview

**Server Version**

This server is running Paper version git-Paper-123 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Geyser Version**

This server is running Geyser version 1.0.0 (git-master-fe75320) (Java: 1.16.1, Bedrock: 1.16.0)

**Minecraft: Bedrock Edition Version**

0.16.0

**Additional Context**

https://dump.geysermc.org/RwvMlRtTjnHVSSPaKhFcn1Dg0r4U19OZ

**Comment by rtm516** [comment] 2020-07-29 09:49
Duplicate of https://github.com/GeyserMC/Geyser/issues/617

**Closed by rtm516** 2020-07-29 09:49 UTC
