### ISSUE TITLE
Error encoding packet TABLE_USE

### ISSUE THREAD

**Issue by BackSam6348** [GeyserMC/Geyser#3980] opened 2023-07-14 10:45 UTC
### Describe the bug

Error encoding packet LevelSoundEvent2Packet(sound=TABLE_USE, position=(7700.5, 127.5, 1743.5), extraData=-1, identifier=:, babySound=false, relativeVolumeDisabled=false)
org.cloudburstmc.protocol.bedrock.codec.PacketSerializeException: Error whilst serializing LevelSoundEvent2Packet(sound=TABLE_USE, position=(7700.5, 127.5, 1743.5), extraData=-1, identifier=:, babySound=false, relativeVolumeDisabled=false)
        at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryEncode(BedrockCodec.java:80) ~[server.jar:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.encode(BedrockPacketCodec.java:39) ~[server.jar:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.encode(BedrockPacketCodec.java:19) ~[server.jar:?]
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[server.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[server.jar:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[server.jar:?]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[server.jar:?]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[server.jar:?]
        at org.cloudburstmc.protocol.bedrock.BedrockPeer.onTick(BedrockPeer.java:91) ~[server.jar:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [server.jar:?]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:159) [server.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [server.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [server.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [server.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) [server.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [server.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [server.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [server.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: No id found for TABLE_USE
        at org.cloudburstmc.protocol.common.util.Preconditions.checkArgument(Preconditions.java:207) ~[server.jar:?]
        at org.cloudburstmc.protocol.common.util.TypeMap.getId(TypeMap.java:39) ~[server.jar:?]
        at org.cloudburstmc.protocol.bedrock.codec.v332.serializer.LevelSoundEventSerializer_v332.serialize(LevelSoundEventSerializer_v332.java:18) ~[server.jar:?]
        at org.cloudburstmc.protocol.bedrock.codec.v332.serializer.LevelSoundEventSerializer_v332.serialize(LevelSoundEventSerializer_v332.java:12) ~[server.jar:?]
        at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryEncode(BedrockCodec.java:78) ~[server.jar:?]
        ... 23 more

### To Reproduce

Using enchant Table

### Expected behaviour

Error after using enchantment table

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/47339652/ad25c0f9-2483-4cb1-86ba-691f687dcff1)

### Server Version and Plugins

Paper version git-Paper-72 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: a3c760e)

[19:43:58 INFO]: Server Plugins (33):
[19:43:58 INFO]: Bukkit Plugins:
[19:43:58 INFO]:  - AntiCheatAddition, BlockLocker, Chunky, CrazyEnvoys, dynmap, Essentials, EssentialsChat, EssentialsDiscord, EssentialsDiscordLink, floodgate
[19:43:58 INFO]:  Floodgate-Skript, FreedomChat, HeadDrop, LuckPerms, *MaxBans, OldCombatMechanics, OpenInv, *ProtocolChanger, ProtocolLib, *RealTimeWeather
[19:43:58 INFO]:  Skript, *skUtilities, TabTPS, Themis, TradeSystem, Vault, ViaBackwards, ViaVersion, voicechat, VotifierPlus
[19:43:58 INFO]:  VotingPlugin, WorldBorder, WorldEdit

### Geyser Dump

https://dump.geysermc.org/yiKuwgAOOruprIauaTYPAO3wKsS3ubU6

### Geyser Version

2.1.2-SNAPSHOT (git-master-c1d8009)

### Minecraft: Bedrock Edition Device/Version

1.20.10

**Comment by onebeastchris** [comment] 2023-07-14 10:46
Duplicate of https://github.com/GeyserMC/Geyser/issues/3969, thanks anyways

**Closed** 2023-07-14 10:46 UTC
Labels: Duplicate
