### ISSUE TITLE
build limit fix on bedrock

### ISSUE THREAD

**Issue by Elyas2024** [GeyserMC/Geyser#4878] opened 2024-07-19 17:42 UTC
### What feature do you want to see added?

on java, you can increase the worlds build limit and it would work perfectly and it's serverside only. if I do that and add geyser to the server, it just doesnt load those blocks. and if I use floodgate to build up higher than 319 blocks up, then join on bedrock on my java account. it. just  breaks. it makes me fall half a block them teleport back up

### Are there any alternatives?

I tried hydrolic, no fix.

**Comment by onebeastchris** [comment] 2024-07-19 17:44
https://github.com/GeyserMC/Geyser/issues/4837 - duplicate of this issue - unfortunately, this is a can't fix

**Closed by onebeastchris** 2024-07-19 17:44 UTC
Labels: Feature Request
