### ISSUE TITLE
Some information of geyser is not displayed correctly in the game

### ISSUE THREAD

**Issue by fang2006-0643** [GeyserMC/Geyser#2600] opened 2021-10-30 14:08 UTC
### Describe the bug

My English is not good. The following words are translated by translator.
When the player enters the game, all game prompts are not displayed as normal text.
For example, "XXX players join the game" is displayed as "multiplayer. Player. Joined"
When players join the game, the server will also prompt: illegal local download and load request: zh_ cn
I don't know how to solve it.QAQ

### To Reproduce

1,Use Geyser[Independent Edition]
2,Open JE Minecraft Server 1.17.1 paper-spigot
3,Open Win10 BE Minecraft(1.17.41) and join this server

### Expected behaviour

I just hope it can display the game prompt normally, such as XXX player join the game

### Screenshots / Videos

![2021-10-30](https://user-images.githubusercontent.com/73422207/139536221-1f9914ca-2c17-4056-93e7-d2391d5784e8.png)

### Geyser Dump

https://dump.geysermc.org/bZLdOgqSLQzRrsNhD7K7AdD4YmUTFkhw

### Geyser Version

1.4.3-SNAPSHOT (git-master-1316f6e)

### Minecraft: Bedrock Edition Version

1.17.41（win10 BE）

**Comment by Camotoy** [comment] 2021-10-30 14:26
Are you able to post the `latest.log` file from the `logs` folder?

**Comment by fang2006-0643** [comment] 2021-10-30 14:30
> 您能否从文件夹中发布文件？`latest.log``logs`
[2021-10-30-1.log.gz](https://github.com/GeyserMC/Geyser/files/7446777/2021-10-30-1.log.gz)
[latest.log](https://github.com/GeyserMC/Geyser/files/7446778/latest.log)

Sure, but there may be something in the document in Chinese

**Comment by zhenchao** [comment] 2022-01-25 17:22
I set the JVM property `-Dfile.encoding=UTF-8` which fixed the problem.  This seems to only appear in non-Unicode environments

**Comment by zhenchao** [comment] 2022-01-25 17:25
I set the JVM property `-Dfile.encoding=UTF-8` which fixed the problem.  
This only seems to be present in non-Unicode environments.  
And also when the BE client is set to English, the problem doesn't appear

**Comment by Camotoy** [comment] 2022-01-25 18:27
Is there a way we can easily replicate it? Maybe a JVM property that makes it occur?

**Comment by srlss123** [comment] 2022-02-09 00:27
We must fix is bug ....

**Comment by Camotoy** [comment] 2022-02-09 00:32
I did try to reproduce this on Linux to no avail. It may be a Windows bug. Are you able to apply Zhenchao's workaround?

**Comment by srlss123** [comment] 2022-02-09 00:38
I cloud not set -Dfile.encoding=UTF-8 or -Dfile.encoding=GBK to fix it . This maybe a windows bug.
I use windows to start server.

**Comment by srlss123** [comment] 2022-02-13 03:29
This bug is fix in new version
On windows

**Comment by RednedEpic** [comment] 2022-04-23 17:59
Was mentioned that this is fixed in newer versions. Closing.

**Closed by RednedEpic** 2022-04-23 17:59 UTC
