### ISSUE TITLE
Signs have a different max length

### ISSUE THREAD

**Issue by chelminski** [GeyserMC/Geyser#4130] opened 2023-09-18 21:18 UTC
### Describe the bug

I know custom heads don't work on bedrock in inventory. I saw it in the "limitations" tab. What happened to the signs, can it be repaired somehow? Is there any chance of adding support for custom heads placed?

### To Reproduce

1. Place a sign and fill it with text.
2. Place custom heads

### Expected behaviour

Correct display of plates and heads

### Screenshots / Videos

JAVA:
![image](https://github.com/GeyserMC/Geyser/assets/62246121/92f8cbb9-0d92-4b21-a1c4-83065e738721)

BEDROCK:
![image](https://github.com/GeyserMC/Geyser/assets/62246121/448495f4-292a-4e6a-9baf-71ef5b358cc8)

### Server Version and Plugins

CraftBukkit version 3870-Spigot-d2eba2c-78796c9 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT

### Geyser Version

On proxy - bungeecord fork - Geyser 2.2.0-SNAPSHOT (git-master-69f89ed) (Java: 1.20, Bedrock: 1.20.0/1.20.1 - 1.20.30)

**Comment by onebeastchris** [comment] 2023-09-20 16:32
We have a workaround you could use for this that makes individual heads into custom blocks, thereby showing their texture.
See https://wiki.geysermc.org/geyser/custom-skulls/#custom-skullsyml for how to use it

**Comment by onebeastchris** [comment] 2023-09-20 16:32
Leaving open for the sign issue, although unsure if we're able to fix this.

**Comment by Konicai** [comment] 2023-09-29 21:34
This is nearly intended behaviour, at least currently.

If the text is some sort of readable text, it might be preferable to wrap the text, as you can see in these images.
Otherwise, if it's just bordering, it would be better to truncate it.

There's no way of knowing which case it is. And implementing a config option would really suck.

**Comment by onebeastchris** [comment] 2024-06-05 22:42
Closing this issue in favor of it being documented on our current limitations page: https://wiki.geysermc.org/geyser/current-limitations/

**Closed by onebeastchris** 2024-06-05 22:42 UTC
Labels: Confirmed Bug, Can't Fix
