### ISSUE TITLE
Geyser Standalone has some kind of leak pegging all CPU threads to 100% over time.

### ISSUE THREAD

**Issue by RetroPronghorn** [GeyserMC/Geyser#930] opened 2020-07-10 18:42 UTC
**Describe the bug**
Geyser Standalone has some kind of leak pegging all CPU threads to 100% over time.

**To Reproduce**
1. Run the latest Geyser Standalone build from Master 
2. Allow time with a few players joining and disconnecting.
3. Monitor CPU usage for runaway process.

**Server Version**
Spigot 1.16

**Geyser Version**
origin/master as commit 40032987faf3d87785f31b232f4e0e797328613b

**Minecraft: Bedrock Edition Version**
1.16.1

**Additional Context**

![Screenshot_20200710-144014_Termius](https://user-images.githubusercontent.com/1770198/87187657-87214980-c2bb-11ea-8b13-5e019f286ed9.jpg)

As shown after about 12 hours Geyser pegs the CPU to maximum across all 12 threads. This was tested on the standalone version and the issue seems to have been introduced in the 1.16pr branch merge.

**Comment by DoctorMacc** [comment] 2020-07-10 18:44
Please follow the issue template (though I understand this is not an issue that's not a result of gameplay). Specifically, what build you are on now.

**Comment by RetroPronghorn** [comment] 2020-07-10 19:12
My mistake, issue updated.

**Comment by DoctorMacc** [comment] 2020-07-10 19:15
Thank you.

I notice you're using Bedrock version 1.16.2 (a beta) - could you confirm if the issue happens without the beta?

**Comment by RetroPronghorn** [comment] 2020-07-10 19:29
That again is my mistake, it's 1.16.1 (latest pub release.)

**Comment by DoctorMacc** [comment] 2020-07-15 15:15
I assume this is still happening? Are you on our Discord server?

**Comment by RetroPronghorn** [comment] 2020-07-15 20:57
@DoctorMacc It is, and I am, I currently have the issue happening right now if you'd like to tag up on Discord.

**Comment by DoctorMacc** [comment] 2020-07-15 20:58
Head on over to our Development channel. I don't know any profilers off the top of my head but maybe something there will be able to help.

**Comment by DoctorMacc** [comment] 2020-08-07 01:30
Is this still occurring on the latest builds? I've encountered someone who's reported this issue again but this time on the BungeeCord version. If so: could you now provide a dump with `/geyser dump` ?

**Comment by RetroPronghorn** [comment] 2020-08-12 19:49
I have not been having the issue recently on the latest version. @DoctorMacc

**Comment by DoctorMacc** [comment] 2020-08-12 19:49
Huh. Thanks for the update!

**Comment by RetroPronghorn** [comment] 2020-08-13 17:54
@DoctorMacc the issue came back again, here is the dump: https://dump.geysermc.org/veNGWHnbrPj3kCkL2phuxZMq4KjwVaXt

**Comment by DoctorMacc** [comment] 2020-08-13 17:55
Oof, but thanks!

**Comment by DoctorMacc** [comment] 2020-08-13 17:56
Hmm, not seeing anything obviously out of the blue - Java version looks fine, Linux isn't anything special, no ping passthroughs enabled.

**Comment by Heath123** [comment] 2020-08-13 18:26
@RetroPronghorn Can you still reproduce it? Are you on a VPS? Can I try getting you to set up a profiler please so we can see what's causing it?

**Comment by Heath123** [comment] 2020-08-13 18:48
Also, are you on the Discord?

**Comment by DoctorMacc** [comment] 2020-08-13 18:50
Yes they are.

**Comment by RetroPronghorn** [comment] 2020-08-13 21:28
@Heath123 I can join back in, I left about 30 discords yesterday it was getting too much :P Send me a FR at RetroPronghorn#0001 if you can. I am on a dedicated threadripper server but I can still setup a profiler if you have one that works from the CLI. But I would prefer not to install something like VisualVM so I don't have to install x11 or anything

**Comment by Heath123** [comment] 2020-08-13 21:29
> @Heath123 I can join back in, I left about 30 discords yesterday it was getting too much :P Send me a FR at RetroPronghorn#0001 if you can. I am on a dedicated threadripper server but I can still setup a profiler if you have one that works from the CLI. But I would prefer not to install something like VisualVM so I don't have to install x11 or anything

![image](https://user-images.githubusercontent.com/13787163/90189012-5d74aa00-ddb4-11ea-88a9-a35eb4ff6b1d.png)
(I'm circuit10#0158)
I think VisualVM can connect remotely to a headless server though

**Comment by RetroPronghorn** [comment] 2020-08-14 03:36
I added you

**Comment by Shanwer** [comment] 2020-08-15 03:48
![image](https://user-images.githubusercontent.com/16631550/90304386-c27dec00-dee9-11ea-99cf-aff4ac5b4662.png)
I also have this problem using the latest Geyser.There was an error which repeated in console  before cpu usage reached 100% an hour ago.

**Comment by PQguanfang** [comment] 2020-08-20 02:35
The same station. I have tried Geyser-Standalone, Geyser-Spigot and Geyser-BungleCord, unfortunately, all of them have this problem.

Today, my Geyser server bump again, and only receive this error this time:
![8C4698FF-284C-47F8-A67A-46631A92FC6F](https://user-images.githubusercontent.com/35395058/90710255-9343f200-e2d0-11ea-86c9-94e058c13105.jpeg)

**Comment by DoctorMacc** [comment] 2020-08-20 02:39
We need the full error - the screenshot you send isn't helpful.

**Comment by RetroPronghorn** [comment] 2020-08-20 22:48
For some additional info, at least in my case, there is spam when using debugging mode about teams. 

[22:47:10 DEBUG] Team packet Team:15 UPDATE null
[22:47:10 DEBUG] Team packet Team:15 UPDATE null
[22:47:10 DEBUG] Team packet Team:14 UPDATE null
[22:47:10 DEBUG] Team packet Team:14 UPDATE null
[22:47:10 DEBUG] Team packet Team:13 UPDATE null
[22:47:10 DEBUG] Team packet Team:13 UPDATE null
[22:47:10 DEBUG] Team packet Team:12 UPDATE null
[22:47:10 DEBUG] Team packet Team:12 UPDATE null
[22:47:10 DEBUG] Team packet Team:11 UPDATE null
[22:47:10 DEBUG] Team packet Team:11 UPDATE null
[22:47:10 DEBUG] Team packet Team:10 UPDATE null
[22:47:10 DEBUG] Team packet Team:10 UPDATE null
[22:47:10 DEBUG] Team packet Team:9 UPDATE null
[22:47:10 DEBUG] Team packet Team:9 UPDATE null
[22:47:10 DEBUG] Team packet Team:8 UPDATE null
[22:47:10 DEBUG] Team packet Team:8 UPDATE null
[22:47:10 DEBUG] Team packet Team:7 UPDATE null
[22:47:10 DEBUG] Team packet Team:7 UPDATE null
[22:47:10 DEBUG] Team packet Team:6 UPDATE null
[22:47:10 DEBUG] Team packet Team:6 UPDATE null
[22:47:10 DEBUG] Team packet Team:5 UPDATE null
[22:47:10 DEBUG] Team packet Team:5 UPDATE null
[22:47:10 DEBUG] Team packet Team:4 UPDATE null
[22:47:10 DEBUG] Team packet Team:4 UPDATE null
[22:47:10 DEBUG] Team packet Team:3 UPDATE null
[22:47:10 DEBUG] Team packet Team:3 UPDATE null
[22:47:10 DEBUG] Team packet Team:2 UPDATE null
[22:47:10 DEBUG] Team packet Team:2 UPDATE null
[22:47:10 DEBUG] Team packet Team:15 UPDATE null
[22:47:10 DEBUG] Team packet Team:15 UPDATE null
[22:47:10 DEBUG] Team packet Team:14 UPDATE null
[22:47:10 DEBUG] Team packet Team:14 UPDATE null
[22:47:10 DEBUG] Team packet Team:13 UPDATE null
[22:47:10 DEBUG] Team packet Team:13 UPDATE null
[22:47:10 DEBUG] Team packet Team:12 UPDATE null
[22:47:10 DEBUG] Team packet Team:12 UPDATE null
[22:47:10 DEBUG] Team packet Team:11 UPDATE null
[22:47:10 DEBUG] Team packet Team:11 UPDATE null
[22:47:10 DEBUG] Team packet Team:10 UPDATE null
[22:47:10 DEBUG] Team packet Team:10 UPDATE null
[22:47:10 DEBUG] Team packet Team:9 UPDATE null
[22:47:10 DEBUG] Team packet Team:9 UPDATE null
[22:47:10 DEBUG] Team packet Team:8 UPDATE null
[22:47:10 DEBUG] Team packet Team:8 UPDATE null
[22:47:10 DEBUG] Team packet Team:7 UPDATE null
[22:47:10 DEBUG] Team packet Team:7 UPDATE null
[22:47:10 DEBUG] Team packet Team:6 UPDATE null
[22:47:10 DEBUG] Team packet Team:6 UPDATE null
[22:47:10 DEBUG] Team packet Team:5 UPDATE null
[22:47:10 DEBUG] Team packet Team:5 UPDATE null
[22:47:10 DEBUG] Team packet Team:4 UPDATE null

You can see how frequently this is coming through by the timestamps.  Still bringing the entire box to a crawl then it happens.

**Comment by DoctorMacc** [comment] 2020-08-20 22:50
Yup, it's probably what #1166 aims to fix. Want to try out that PR and see if it helps?

**Comment by DoctorMacc** [comment] 2020-08-28 15:52
Judging from the debug logs, I'm going to make a strong assumption that this is now fixed in the latest Geyser build with #1166.

**Closed by DoctorMacc** 2020-08-28 15:52 UTC
Labels: Assistance Required, More Info Needed

**Comment by RetroPronghorn** [comment] 2020-09-13 19:57
Just a heads up, this is not fixed in the latest version. Still happening every other day

**Comment by RednedEpic** [comment] 2020-09-13 19:58
> Just a heads up, this is not fixed in the latest version. Still happening every other day

Can we get a profiler report? Not a whole lot that we're able to do without one unfortunately.

**Comment by RetroPronghorn** [comment] 2020-09-13 19:58
Could you let me know what flags to use to start the jar with some kind of profiler like JMX?

**Comment by RednedEpic** [comment] 2020-09-13 20:01
> Could you let me know what flags to use to start the jar with some kind of profiler like JMX?

The flags you use to start up the Geyser jar normally should work fine. I would recommend using VisualVM as your profiler.

**Comment by RetroPronghorn** [comment] 2020-09-13 20:26
@RednedEpic I can't use VisualVM is the issue, it's on a box without a GUI but I thought there might be a way to start a profiler and bind VIsualVM to the remote addr:port. One thing I can say is that it seems to be the same issue with team packets. It spams at an unreadable rate `Team packet Team:3 UPDATE null`. It's doing it immediately when people connect. Is there a way I can just remove teams from Geyser they seem to be what's causing the issue. 

[https://i.imgur.com/fcn0PXw.png](https://i.imgur.com/fcn0PXw.png)

https://i.imgur.com/fcn0PXw.png

**Comment by RednedEpic** [comment] 2020-09-13 20:27
> @RednedEpic I can't use VisualVM is the issue, it's on a box without a GUI but I thought there might be a way to start a profiler and bind VIsualVM to the remote addr:port. One thing I can say is that it seems to be the same issue with team packets. It spams at an unreadable rate `Team packet Team:3 UPDATE null`. It's doing it immediately when people connect. Is there a way I can just remove teams from Geyser they seem to be what's causing the issue.
> 
> https://i.imgur.com/fcn0PXw.png
> 
> https://i.imgur.com/fcn0PXw.png

At the moment no, but the team spam is definitely something we're looking in to. Can you try disabling debug mode to see if that helps at all?

**Comment by RetroPronghorn** [comment] 2020-09-13 20:55
I disabled debug mode which stops the spam, but the 1600% CPU usage still happens behind the scenes.

**Comment by DoctorMacc** [comment] 2020-09-13 20:57
You can try bumping the `scoreboard-packet-threshold` in the Geyser config (add the option if it isn't there) to something greater than 20.

**Comment by Tim203** [comment] 2020-09-13 21:26
Lower then 20 ^

**Comment by MrPowerGamerBR** [comment] 2020-10-27 00:10
This issue is still happening in the latest Geyser version.

![https://cdn.discordapp.com/attachments/613168464634576897/770438213215059978/unknown.png](https://cdn.discordapp.com/attachments/613168464634576897/770438213215059978/unknown.png)

**Comment by Comstepr** [comment] 2020-10-27 00:36
@MrPowerGamerBR At the moment, I can suggest that you try the following:
- Use the command `taskset --cpu-cores <cpu numbers> java -Xmx1G -jar Geyser.jar`
For example `taskset --cpu-cores 11 java -Xmx1G -jar Geyser.jar`

**Comment by MrPowerGamerBR** [comment] 2020-11-01 13:19
Profiled the process, here's the results:

![javaw_fenWdgI7ar](https://user-images.githubusercontent.com/9496359/97804001-c2110980-1c2b-11eb-9463-9d4b31f351d6.png)
![javaw_ktMR4H6Cej](https://user-images.githubusercontent.com/9496359/97804003-c2a9a000-1c2b-11eb-8bfe-eabfb45c3194.png)

**Comment by Tim203** [comment] 2020-11-01 14:35
Thanks, I see quite a few things that we can optimise to get better performance in those specific areas.

**Comment by Tim203** [comment] 2020-11-05 21:46
#1481 was made to improve performance of tile/block entities and it got merged a few minutes ago.
Can you check that out to see if performance got improved for you?

**Comment by MrPowerGamerBR** [comment] 2021-02-22 12:16
@Tim203 sorry for the very very very late reply, but sadly this is still happening, I will try getting some CPU profiles again to help debugging this issue.

By the way: I think this is happening because *something* is stuck in a loop and the loop never exits, because this only happens *sometimes* and doesn't seem to matter how many players are logged in.

**Comment by Tim203** [comment] 2021-02-22 15:31
No problem, thanks
