### ISSUE TITLE
World border works only for java 

### ISSUE THREAD

**Issue by chelminski** [GeyserMC/Geyser#1677] opened 2020-12-14 17:09 UTC
**Error description:**
Bedrock players can bypass the restriction and build at the world border.

- [Video of Bedrock view](https://youtu.be/ENXysc_B7t0)

- [Video of Java view](https://youtu.be/X3Jql76Tq2c)

**Comment by Camotoy** [comment] 2020-12-14 17:13
Duplicate of #447. In the future, please follow the issue template. Thank you!

**Closed by Camotoy** 2020-12-14 17:13 UTC
