### ISSUE TITLE
players cannot see each other

### ISSUE THREAD

**Issue by JesusMtzMC** [GeyserMC/Geyser#3272] opened 2022-09-06 23:46 UTC
### Describe the bug

the players cannot see each other, as if they were not on the server but nevertheless they are 

### To Reproduce

¿?

### Expected behaviour

It may be some incompatibility with a plugin since that is what has happened in several cases

### Screenshots / Videos

![Screenshot_20220906-152846](https://user-images.githubusercontent.com/109834273/188758599-9e490765-ffbf-4366-89fb-96b660c7d366.png)
![IMG-20220906-WA0017](https://user-images.githubusercontent.com/109834273/188758612-4eed30d9-ff97-48a2-abc8-a7f08b1c3ed8.jpg)
![Screenshot_20220906-153056~5](https://user-images.githubusercontent.com/109834273/188758742-b5cb5ac0-5b34-4ebb-befe-1da592d89685.jpg)

### Server Version and Plugins

Versión 
git-Purpur-1774 (MC: 1.19.2)

List Plugins
(23): ChatManager, Citizens, ConditionalEvents, DecentHolograms, DeluxeHub, Essentials, ExcellentCrates, FastAsyncWorldEdit (WorldEdit), floodgate, Geyser-Spigot, LuckPerms, Multiverse-Core, MyCommand, NexEngine, PlaceholderAPI, SCore, spark, StaffPlusPlus, SternalBoard, TAB, Vault, VoidGen, WorldGuard

### Geyser Dump

https://dump.geysermc.org/L1R6cy6GOjvOG3YdrHrQIXr8cAbnL6O2

### Geyser Version

git-Purpur-1774 (MC: 1.19.2)

### Minecraft: Bedrock Edition Device/Version

1.19.2

**Comment by JesusMtzMC** [comment] 2022-09-06 23:52
Help

**Comment by onebeastchris** [comment] 2022-09-06 23:56
As said in the discord - and as you've said too - it's likely an incompatibly with another plugin. 

Please follow the steps below to find out the plugin that may be interfering - if you can reproduce this without any other errors present, send a new dump

If you have a possible plugin interfering with Geyser or Floodgate, follow these steps to find the culprit plugin:
- Temporarily remove/move half of your plugins from your server's plugins folder.
- *If the problem persists*, remove another half.
- *If the problem goes away*, swap that half of your plugins with the other half.
- Keep repeating this pattern, this time with the half that exhibits the problem, until you find your problematic plugin.

It's a cumbersome process, but unfortunately, we can't do it for you since there could be external factors too. 
I'd recommend to make a backup of the plugin folder beforehand aswell.

**Comment by JesusMtzMC** [comment] 2022-09-07 02:15
and when finding the guilty plugin what can be done? since if it is one that I need I will not be able to eliminate it

**Comment by Kas-tle** [comment] 2022-09-07 03:23
Then we will be able to reproduce the issue and see if it can be fixed by Geyser. But for that to happen we need to identify what plugin is causing the issue and how to reproduce said issue.

**Comment by Konicai** [comment] 2022-10-18 00:59
Have you determined a plugin conflict?

**Comment by Jens-Co** [comment] 2023-04-25 00:23
Closing due to no response. If you still have this issue please provide us with the asked info and let me know and I'll reopen this. Thanks!

**Closed by Jens-Co** 2023-04-25 00:23 UTC
Labels: Waiting On Response

**Comment by BrianTheBrain11** [comment] 2023-06-08 04:54
Same issue. Clean Mc server. Latest 1.20 version of minecraft that released today. Today's geyser-spigot download. 1.20 spigot self compiled. The latest version of floodgate.
