### ISSUE TITLE
Boats Disappearing on Place

### ISSUE THREAD

**Issue by nicholasveronico** [GeyserMC/Geyser#2834] opened 2022-02-12 15:41 UTC
### Describe the bug

When placing a boat in a one-block deep pool of water, the boat seems to not place but also disappears from the player's inventory. Upon clicking another item into the place of the boat in the player's inventory, it reappears. 

### To Reproduce

1. Go to a one-block deep area of a water source.
2. Place a boat on the block of the one-block deep source.
3. Click another item into the place of the boat in the inventory.

### Expected behaviour

The boat is supposed to place without any issues of ghost blocks. I have attached a video below showing the problem.

### Screenshots / Videos

https://imgur.com/a/DBXxeg5

### Server Version and Plugins

Proxy: Flamecord v0.7.0
Backend: git-Purpur-1551 (MC: 1.18.1) 

Another testing environment where this occurs:
-  Proxy: Waterfall build 478
- Backend: Paper 1.18.1 build 194
- Plugins: Nothing but floodgate-spigot

### Geyser Dump

https://dump.geysermc.org/cVXszRHOJHK9gQWOHlz5rnpo08CvSUoO

### Geyser Version

Geyser version 2.0.1-SNAPSHOT (git-master-44af9da) (Java: 1.18 - 1.18.1, Bedrock: 1.17.40 - 1.18.10)

### Minecraft: Bedrock Edition Version

1.18.10

**Comment by Camotoy** [comment] 2022-02-12 15:42
Looks like this is a duplicate of #1247, so I will close to keep tidiness. Thank you anyway!

**Closed by Camotoy** 2022-02-12 15:42 UTC
