### ISSUE TITLE
Signs aren't sent to the server

### ISSUE THREAD

**Issue by RealBitslayn** [GeyserMC/Geyser#2014] opened 2021-03-08 16:09 UTC
### Describe the bug

Signs placed by bedrock players aren't sent to the server. Restarting the world or reloading signs through a plugin clears the sign.

### To Reproduce

1. Write text in a sign.
2. Reload server or modify sign using a plugin.
3. Sign data will be blank as if not written on.

### Expected behaviour

The signs written on Bedrock should be sent to the server.

### Server Version and Plugins

This server is running Paper version git-Paper-441 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Plugins (18): DiscordSRV, dynmap*, DynmapBannerMarkers, Essentials, floodgate-bukkit, Geyser-Spigot, GeyserSkinManager, GeyserUpdater, Graves, LuckPerms, NoBoom, SignShop, SilkSpawners, StatsSB, SuperChairs, TimeIsMoney*, Vault, WorldBorder

### Geyser Dump

https://dump.geysermc.org/sKsZTlSlJZVk7kqhEIIwPuVrWcwNG01t

### Geyser Version

Geyser version 1.2.0-SNAPSHOT (git-server-inventory-814fa95)

### Minecraft: Bedrock Edition Version

1.16.201

### Additional Context

I recently found the bug relating to plugins using the SignShop plugin while attempting to link a sign with a chest.

**Comment by Camotoy** [comment] 2021-03-08 16:10
This is likely a duplicate of #1063. Thank you for reporting anyway!

**Closed by Camotoy** 2021-03-08 16:10 UTC
