### ISSUE TITLE
Parrot sound error

### ISSUE THREAD

**Issue by koloksk** [GeyserMC/Geyser#516] opened 2020-05-08 22:32 UTC
**Describe the bug**
When the parrot makes a sound, it disconnects from the server.

**Screenshots / Videos**
https://imgur.com/a/kYIG1Du
https://www.youtube.com/watch?v=q3uzPImx8nQ

**Server Version**
- Waterfall git:Waterfall-Bootstrap:1.15-SNAPSHOT:e0795ab:341 (Geyser)
- Paper-1602 (MC: 1.12.2)

**Geyser Version**
Geyser version 1.0-SNAPSHOT (git-master-e58ffdd)

**Minecraft: Bedrock Edition Version**
1.14.60

**Comment by DoctorMacc** [comment] 2020-05-08 22:34
One of the mimicked noises, or a standard parrot noise?

**Comment by koloksk** [comment] 2020-05-08 22:49
> One of the mimicked noises, or a standard parrot noise?

standard parrot noise

**Comment by DoctorMacc** [comment] 2020-05-10 17:42
I was unable to confirm this on Spigot 1.12.2 as well as Paper 1.15.2. Can you redownload Geyser? If the error still persists: what type of Geyser are you using? (Standalone, Bukkit. etc)

**Comment by koloksk** [comment] 2020-05-12 20:13
https://www.youtube.com/watch?v=q3uzPImx8nQ
I will try to download the latest version of geyser again.

**Comment by koloksk** [comment] 2020-05-13 08:28
I installed the latest version of Geyser and the error is gone :)

**Comment by koloksk** [comment] 2020-05-13 08:28
However, no :(

**Comment by DoctorMacc** [comment] 2020-05-13 14:05
Are you using any plugins?

**Comment by rtm516** [comment] 2020-05-14 23:25
Can we get a server IP where this occurs?

**Comment by CuteTadpole** [comment] 2020-05-22 15:35
So, I'm going to add some information for this issue.
When the parrot makes a **pant** sound, player disconnects from the server. 

**Steps to reproduce**
1. Spawn the parrot and the wolf next to each other (in Java Minecraft): 
![image](https://user-images.githubusercontent.com/61086561/82683513-d226c500-9c59-11ea-9153-5db5692f64b9.png)
2. Wait a little bit
3. Then get this error: 
![image](https://user-images.githubusercontent.com/61086561/82683724-292c9a00-9c5a-11ea-86c3-f6f77279be59.png)
(The contributor's error and my error are the same)

**Server version**
![image](https://user-images.githubusercontent.com/61086561/82683989-93453f00-9c5a-11ea-9ead-cdd441a9ea4f.png)

**Geyser version**
Geyser Bungee build 171

**Minecraft: Bedrock Edition Version**
1.14.60

And I don't really know about plugins on the server I'm testing because of restrictions :(

**Comment by CuteTadpole** [comment] 2020-05-22 16:16
I've just tested this bug on clear Paper 1.12.2 build 1618 using Geyser Bukkit build 173 and bug partially happens - I don't hear a pant sound, but I don't get this error and therefore don't get kicked from the server. Maybe I need to update Geyser Bungee on the server I'm testing?

**Comment by CuteTadpole** [comment] 2020-05-22 16:54
![ozrjFySsCKQ](https://user-images.githubusercontent.com/61086561/82690996-dc4ec080-9c65-11ea-9f82-aad2a27b423f.jpg)
So I've got necessary permissions to use /pl command. It is a list of plugins on the server.

**Comment by DoctorMacc** [comment] 2020-05-23 04:25
Our upstream Java protocol library, MCProtocolLib, pushed a fix recently that should fix this problem. When the next Geyser build releases, please re-test this.

**Comment by CuteTadpole** [comment] 2020-05-23 19:53
I've tested this bug on PR #623 and this bug disappeared 
👍

**Closed** 2020-05-23 20:56 UTC
Labels: Unconfirmed Bug, Upstream
