### ISSUE TITLE
Crafting Bug

### ISSUE THREAD

**Issue by Cryptics1999** [GeyserMC/Geyser#1472] opened 2020-10-29 16:05 UTC
**Describe the bug**
When a bedrock player tries to craft in 1.8, its not allowing the player to craft. Im also using Paper Spigot

Use latest 1.8 paper jar
Use bedrock client
Try to Craft
Nothing possibal to craft

**Expected behavior**

Bedrock Players are not able to craft

Latest Paper Spigot 1.8 jar

Geyser Version: 1.1.0

Bedrock Version: 1.16.50 on Minecraft PE

https://dump.geysermc.org/eLSLKaUUmKbTYiWFwrUAPiYuMhijgbWo

**Comment by DoctorMacc** [comment] 2020-10-29 16:07
This is a duplicate of #511. Regardless, thank you for reporting!

**Closed** 2020-10-29 16:08 UTC
