### ISSUE TITLE
Naming in anvil broken

### ISSUE THREAD

**Issue by Topnitel** [GeyserMC/Geyser#1720] opened 2020-12-21 16:31 UTC
**Describe the bug**
Naming using an anvil is broken, the red cross doesn't disappear on the arrow and I can't take the output item
This happens as well if you're merging something and at the same time naming it (e.g. adding a book to your sword and also renaming it), it will give you the output but unnamed

**To Reproduce**
1. Get an anvil
2. Name something, or merge something with it and rename it
3. It never gets named

**Expected behavior**
It allows you to take the named output item

**Screenshots / Videos**
Cannot record any videos

**Server Version**
This server is running Paper version git-Paper-338 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Geyser Version**
This server is running Geyser version 1.2.0-SNAPSHOT (git-master-c921500) (Java: 1.16.4, Bedrock: 1.16.100/1.16.101 - 1.16.200.5)

**Minecraft: Bedrock Edition Version**
Both 1.16.200 (PC) and 1.16.201 (iPhone)

**Additional Context**
https://dump.geysermc.org/0JMv0JfSSt4mTFKfjuDkEZ65ZkdYmZBR

**Comment by Camotoy** [comment] 2020-12-21 16:32
Duplicate of #1658. Thank you regardless for reporting!

**Closed by Camotoy** 2020-12-21 16:32 UTC
