### ISSUE TITLE
io.netty.handler.codec.DecoderException with a Forge server

### ISSUE THREAD

**Issue by Leeo97one** [GeyserMC/Geyser#251] opened 2020-03-28 11:11 UTC
**Describe the bug**
I can't join a Forge server running without any mod:
```
Leeo97one has disconnected from remote java server on address 127.0.0.1 because of io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.command.CommandParser.
```

**To Reproduce**
1. Run a Forge server without any mod
2. Connect via Geyser
3. See error

**Expected behavior**
Successful connection.

**Screenshots**
![Screenshot_20200328-120519](https://user-images.githubusercontent.com/1344241/77821706-99042580-70ec-11ea-91c3-a1d04633aecc.jpg)

**Server version**
forge-1.15.2-31.1.0-universal

**Geyser version**
Revision: 03e11df58beafbc91b414f8e50a020a76e8e2e7c

**Bedrock version**
1.14.30

**Additional context**
No mods.

**Comment by ldare373** [comment] 2020-03-28 12:07
My understanding is that geyser will not work with forge.

**Comment by RealTriassic** [comment] 2020-03-28 12:25
Geyser Proxy doesn't work with Modded Forge Servers, or basically any Forge.

**Comment by Leeo97one** [comment] 2020-03-28 12:27
OK and no support is planned? At least for server which doesn't require any client-side mod.

**Comment by RealTriassic** [comment] 2020-03-28 12:30
> OK and no support is planned? At least for server which doesn't require any client-side mod.

Most likely no.

**Comment by Heath123** [comment] 2020-03-28 13:08
Geyser should probably work in the same way as a vanilla client- can a vanilla client join the server?

**Comment by Leeo97one** [comment] 2020-03-28 13:24
> Geyser should probably work in the same way as a vanilla client- can a vanilla client join the server?

Yes of course.

**Comment by ldare373** [comment] 2020-03-28 13:26
Wait what

**Comment by LogicismDev** [comment] 2020-03-28 13:46
You will not be able to join a forge server basically since Geyser doesn't support custom blocks and GUIs. So basically if a vanilla client can't join, it'll make sense why a bedrock user can't join through Geyser.

**Comment by Leeo97one** [comment] 2020-03-28 13:49
A vanilla client can join a Forge server with server-side only mods. Easy to test if you want.

**Comment by RednedEpic** [comment] 2020-03-28 17:46
Ideally, Geyser should be able to join Forge and Fabric servers that don't require the client to have any mods without any problems. Likely what is happening is the Forge server is sending a packet that Geyser does not recognize, thus causing them to be kicked. On a normal Notchian client, the packet is ignored.

**Comment by Loganh4005** [comment] 2020-03-31 15:42
I also remember something like this error when trying to get bungeecord working with forge before I went to spigot + vanilla

**Comment by DoctorMacc** [comment] 2020-04-15 15:53
I'll keep this open, but it appears the problem is in MCProtocolLib and not us. I'll be filing a bug report shortly.

**Comment by DoctorMacc** [comment] 2020-04-15 22:08
This should be fixed next build, when the MCProtocolLib changes can register.

**Comment by DoctorMacc** [comment] 2020-04-17 17:50
This should be now be fixed.

**Closed by DoctorMacc** 2020-04-17 17:50 UTC
Labels: Confirmed Bug, Priority: Medium, Work in Progress
