### ISSUE TITLE
mobs dont show there item in hand

### ISSUE THREAD

**Issue by LegacyGamerHD** [GeyserMC/Geyser#114] opened 2019-12-19 08:20 UTC
latest geyser 

latest bedrock ( 1.14 )

zombies shoelld hold a item if picked up

**Comment by RednedEpic** [comment] 2019-12-19 13:55
Duplicate of #106

**Closed by RednedEpic** 2019-12-19 13:55 UTC
Labels: Duplicate

**Comment by LegacyGamerHD** [comment] 2019-12-19 17:06
i swear i dident see that my bad

**Comment by Seamusmario** [comment] 2019-12-20 03:04
;)
