### ISSUE TITLE
 The provided value for the 'code' parameter is not valid. And you need a java edition account

### ISSUE THREAD

**Issue by Kimmigbpz** [GeyserMC/Geyser#3179] opened 2022-07-27 20:06 UTC
### Describe the bug

i used gerser.jar the server is fabric and mc1.18.1 when i login my server it always has error like  The provided value for the 'code' parameter is not valid. And you need a java edition account

### To Reproduce

just i login the server

### Expected behaviour

.

### Screenshots / Videos

[03:29:25 INFO] /39.144.37.205:17768 Try connecting!
[03:29:26 INFO] The player established the connection with the username of GBPZkimmi (use the Microsoft Login)
[03:29:48 INFO] Bedrock Edition IP is: /39.144.37.205 for The provided value for the 'code' parameter is not valid. Disconnect
[03:30:28 INFO] /39.144.37.205:17768 Try connecting!
[03:30:29 INFO] The player established the connection with the username of GBPZkimmi （uses browser and i brouth a javaedition account）
[03:32:08 INFO] Players with Bedrock Edition IP: /39.144.37.205 are disconnected due to the need for a paid Java account on this server

### Server Version and Plugins

Fabric mc-1.18.1 no any block mod just 

### Geyser Dump

https://dump.geysermc.org/NrPs6siPctfbNKb3QBSNyNS8BnBHYQt0

### Geyser Version

2.0.5-SNAPSHOT (git-master-f4a5ccb)

### Minecraft: Bedrock Edition Device/Version

10549241

**Comment by Camotoy** [comment] 2022-07-27 20:09
Try logging in with the web browser instead.

**Comment by Camotoy** [comment] 2022-07-27 20:09
Or use Floodgate.

**Comment by Kimmigbpz** [comment] 2022-07-28 02:03
Yes，i've tried logging in with the web browser instead.
but it‘s not work，it tell me I need a java edition a account
And my server is online I don‘t know why
I really need help


从 Windows 版邮件发送

发件人: Camotoy
发送时间: 2022年7月28日 4:10
收件人: GeyserMC/Geyser
抄送: Kimmi; Author
主题: Re: [GeyserMC/Geyser] The provided value for the 'code' parameter isnot valid. And you need a java edition account (Issue #3179)

Try logging in with the web browser instead.

**Comment by Konicai** [comment] 2022-07-28 17:38
What is your java edition username?

**Comment by Kimmigbpz** [comment] 2022-08-02 01:40
the server java edition is 1.18.1

**Comment by Kimmigbpz** [comment] 2022-08-02 01:40
the server java edition is MCDR Fabric 1.18.1

**Comment by Erkam246** [comment] 2022-08-11 13:11
I think Microsoft changed the login flow

**Comment by Erkam246** [comment] 2022-08-11 15:12
U sure about that? Cuz i tried to implement it myself and also tried McAuthLib with Username and Password auth but there was no redirect to get the access_token from the url like it should be. Also descriped here https://mojang-api-docs.netlify.app/authentication/msa.html

or i missed something idk maybe you can take a deeper look after it

**Comment by onebeastchris** [comment] 2023-06-11 00:56
Since the issue is getting axed soon enough - closing this.

**Closed by onebeastchris** 2023-06-11 00:56 UTC
