### ISSUE TITLE
Inventory Freeze when Rapidly Opening/Closing on Latest Version of GeyserMC

### ISSUE THREAD

**Issue by DimaSergeew** [GeyserMC/Geyser#4517] opened 2024-03-23 18:16 UTC
### Describe the bug

Players have been experiencing a significant issue where if they rapidly press the button to open their inventory, it completely freezes and becomes unresponsive. This issue extends to all inventory-related interactions including chests, furnaces, and crafting tables. Once this bug is triggered, players are unable to open their inventory or interact with any item storage blocks. The only workaround currently available is to disconnect and reconnect to the server. This problem has been reported on the latest version of GeyserMC.

### To Reproduce

Connect to the server using the latest version of GeyserMC.
Rapidly press the button to open and close the inventory multiple times.
Notice that after a few rapid interactions, the inventory completely freezes.
Attempt to interact with chests, furnaces, or crafting tables, and observe that these interactions are also frozen and unresponsive.

### Expected behaviour

Players should be able to rapidly open and close their inventory without causing it to freeze or become unresponsive. Additionally, interacting with chests, furnaces, and crafting tables should always be possible regardless of how often the inventory is accessed.

### Screenshots / Videos

https://github.com/GeyserMC/Geyser/assets/75163645/642ce4c4-4a28-4d43-8a4f-45a8098864c6

### Server Version and Plugins

purpur 1.20.4 lastet

### Geyser Dump

https://dump.geysermc.org/Xs9Gj33YCqPfqUu49eR4R5x9zXgpoasN

### Geyser Version

2.2.2-SNAPSHOT (git-master-c64e8af)

### Additional Context

This issue has been consistently reproducible under the conditions mentioned above and has been verified on multiple occasions by different players on the server. It significantly affects gameplay, as players are unable to access their items or manage their inventory effectively once the bug occurs. A server reconnect is required each time to resolve the issue temporarily, but it can recur if the inventory is rapidly accessed again.

**Comment by onebeastchris** [comment] 2024-03-23 22:02
Does this issue also occur with this build?
https://github.com/GeyserMC/Geyser/actions/runs/8296491137

**Comment by DimaSergeew** [comment] 2024-03-24 08:25
> Does this issue also occur with this build? https://github.com/GeyserMC/Geyser/actions/runs/8296491137


In the latest version of Geyser, I was receiving numerous complaints about this issue. In this version, as demonstrated, there have been significantly fewer complaints, but some still exist and the bug remains unresolved.

**Comment by Hahaa13** [comment] 2024-03-24 08:56
Double click and error
And chest,inventory,... cannot open

**Comment by Folas1337** [comment] 2024-03-25 11:52
I've also had two users report the same issue with the inventory freezing or in other words being unable to open inventories.

One user has given me some more details:
- He first opened the inventory manually then closed it manually
- The game seems to have force-opened the inventory for him again as if it hadn't understood that it was closed
- He then closes it again and afterwards this bug happens

He is then unable to open his own inventory or any containers but he can apparently open shulker boxes which then look as if they were opened but he can still move freely.

*More info might be added as we investigate but that's all I have for now.*

**Comment by Trihienkun** [comment] 2024-03-26 03:09
Is there any way to fix this error?

**Comment by R00tB33rMan** [comment] 2024-03-26 12:43
I can reproduce this issue. Occurs with a large sum of my users. The evidence provided in the initial report explicitly represents what I've been facing.

**Comment by qrvgqwe** [comment] 2024-03-26 16:42
here's the problem https://github.com/GeyserMC/Geyser/commit/112f4ddb8d8ef6d2518f6adde57300f31c6c5be1

**Comment by onebeastchris** [comment] 2024-03-26 23:04
Able to replicate. Unfortunately i don't have enough time at the moment to try and resolve the root cause (where Geyser doesn't seem to react fast enough to inventories being opened/closed). I've made a PR that reverts the commit linked here - thanks for the research btw, appreciate it.

**Comment by DimaSergeew** [comment] 2024-03-27 09:17
> Able to replicate. Unfortunately i don't have enough time at the moment to try and resolve the root cause (where Geyser doesn't seem to react fast enough to inventories being opened/closed). I've made a PR that reverts the commit linked here - thanks for the research btw, appreciate it.

+ I noticed another 1 problem, I use the plugin TrydeSystem, and when a player cancels a transaction screen hip player becomes black, and he needs to restart the game, I noticed that such a problem is not in GeyserMC in ptacha where added 1.20.60

**Comment by DimaSergeew** [comment] 2024-03-27 09:19
> Able to replicate. Unfortunately i don't have enough time at the moment to try and resolve the root cause (where Geyser doesn't seem to react fast enough to inventories being opened/closed). I've made a PR that reverts the commit linked here - thanks for the research btw, appreciate it.

I can spend a couple of days of my time and check all patches after 1.20.60 and find the one that broke the inventory system

**Comment by onebeastchris** [comment] 2024-03-27 10:14
Besides this commit, no other major changes have been done that would impact the inventory system. 
If you want to troubleshoot and find the root cause - feel free to. As for the trading issue, create a new issue with reproduction steps

**Closed** 2024-04-15 15:33 UTC
Labels: Confirmed Bug
