### ISSUE TITLE
Downstream packet error! Packet "ClientboundLoginDisconnectPacket" not fully read.

### ISSUE THREAD

**Issue by xx445469** [GeyserMC/Geyser#4265] opened 2023-11-01 16:06 UTC
### Describe the bug

when I use PE login 

[15:54:37 INFO]: [.boomtnt1055] disconnected with: Exception Connecting: DecoderException : java.lang.UnsupportedOperationException: Packet must implement read method @ io.netty.handler.codec.MessageToMessageDecoder:98
[15:54:37 INFO] [floodgate]: Floodgate player logged in as .boomtnt1055 disconnected
[15:54:37 INFO]: [/xx.xxx.xx.xx:0|.boomtnt1055] -> UpstreamBridge has disconnected
[15:54:37 WARN] [Geyser-BungeeCord]: Downstream packet error! Packet "ClientboundLoginDisconnectPacket" not fully read.
[15:54:37 INFO]: [.boomtnt1055|/xx.xxx.xx.xx:0] <-> ServerConnector [lobby] has disconnected

### To Reproduce

It also show the error connection close in PE client
and the cell phone has the same error

### Expected behaviour

when I use windows PE V1.20.40 login server I will show the error
and the cell phone has the same error

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/109457281/5d3d8182-da72-42ef-9e8b-6655b0f153e4)
![image](https://github.com/GeyserMC/Geyser/assets/109457281/c411de50-66ca-4830-9b34-b683b15c76bf)

### Server Version and Plugins

server version : waterfall-1.20-549
Geyser version 2.2.0-SNAPSHOT (git-master-8d2ebcf) (Java: 1.20.2, Bedrock: 1.20.0/1.20.1 - 1.20.40)
floodgate version You're currently on 2.2.2-SNAPSHOT (b85-71acc6c) (branch: master)

### Geyser Dump

https://dump.geysermc.org/sxni3BYvSYSSHNlhGdxMBYVS8dY8OOtx

### Geyser Version

2.2.0-SNAPSHOT (git-master-8d2ebcf)

### Minecraft: Bedrock Edition Device/Version

windows PE V1.20.40

### Additional Context

my plugins

BungeeGuard
BungeeServerManager-1.5.2
FallBackServer-3.2.0-Beta1
floodgate-bungee
Geyser-BungeeCord
GeyserSkinManager-BungeeCord
lobbysystem-2.4-SNAPSHOT
LuckPerms-Bungee-5.4.102
minimotd-bukkit-bungeecord-2.0.13
SkinsRestorer
VentureChat-3.6.0
ViaBackwards-4.8.1
ViaVersion-4.8.1.jar

**Comment by onebeastchris** [comment] 2023-11-01 16:21
Please try the download founder under `Checks` from this PR:
https://github.com/GeyserMC/Geyser/pull/4264

**Comment by onebeastchris** [comment] 2023-11-03 10:36
Closing - this is a duplicate of https://github.com/GeyserMC/Geyser/issues/4049.

**Comment by onebeastchris** [comment] 2023-11-03 11:27
What error do you get now? Still the same `ClientboundLoginDisconnectPacket no fully read` error, or the `Packet must implement read method` one?

**Comment by onebeastchris** [comment] 2023-11-03 11:29
Send a log, a yes doesnt answer that question

**Comment by onebeastchris** [comment] 2023-11-03 11:31
Could be. Afaik the first error you're getting, the "Packet must implement read method" one, would imply some plugin sending invalid packets - please try reproducing the issue with no plugins besides Geyser/Floodgate.

**Comment by onebeastchris** [comment] 2023-11-03 11:32
Are you able to connect normally with a 1.20.2 Java client?

**Comment by onebeastchris** [comment] 2023-11-03 11:43
That would imply a plugin issue then - Geyser also emulates a 1.20.2 Java client.
What you should do:
- Update/install ViaVersion on the backend servers if they are not on 1.20.2
- update plugins on the proxy to versions that work with 1.20.2 - or remove them if they dont support it
- try with less plugins.

Going to close this though - if Java 1.20.2 doesn't work, Geyser wont be able to aswell.

**Closed by onebeastchris** 2023-11-03 11:43 UTC
Labels: Possible Duplicate
