### ISSUE TITLE
geyser player Hud's disapear after Teleporting

### ISSUE THREAD

**Issue by shawn695** [GeyserMC/Geyser#4552] opened 2024-04-07 03:14 UTC
### Describe the bug

when a geyser playe TP's they hud disapears (hotbar, health, armour everything)

### To Reproduce

teleport in world 

### Expected behaviour

for players huds to not disapear

### Screenshots / Videos

![IMG_0134](https://github.com/GeyserMC/Geyser/assets/92684055/f7a916fa-a379-4e40-8812-b3812e1b25d0)

### Server Version and Plugins

Current: git-Purpur-2166 (MC: 1.20.4)*

### Geyser Dump

https://dump.geysermc.org/g7EO6ugKQJJUhaYXVvlMsgJg9SOa0o84

### Geyser Version

487

### Minecraft: Bedrock Edition Device/Version

all bedrock clients

**Comment by lucasfrederico** [comment] 2024-04-10 00:15
This is happening to me too

**Comment by prxgma** [comment] 2024-04-12 09:58
Yep, happening to me too.

**Comment by lucasfrederico** [comment] 2024-04-12 20:09
Any ETA to solve it?

**Comment by lucasfrederico** [comment] 2024-04-22 14:32
@onebeastchris

**Comment by lucasfrederico** [comment] 2024-04-26 01:03
ETA?

**Comment by 1470429149** [comment] 2024-05-17 12:40
me too

**Comment by onebeastchris** [comment] 2024-05-17 12:44
Unable to reproduce. Please provide further reproduction steps - does this occur with the `/tp` command? Or only with a specific plugin? Or specific distances?

**Comment by onebeastchris** [comment] 2024-06-18 15:17
Closing due to no further response. If this bug still occurs, please provide updated replication steps here, and we'll attempt to reproduce it.

**Closed by onebeastchris** 2024-06-18 15:17 UTC
Labels: Unconfirmed Bug/Not Currently Replicable, Waiting On Response

**Comment by WaffleBits** [comment] 2024-07-14 02:08
hello this is happening to me is there a solution somewhere else or just not enough info ?

**Comment by onebeastchris** [comment] 2024-07-14 08:35
@WaffleBits This was closed due to incomplete reproduction steps/us being not able to replicate the issue. If you can replicate it, let us know how, and we'll try and resolve it.
