### ISSUE TITLE
World haven't been loaded full on bedrock edition

### ISSUE THREAD

**Issue by Shadodd** [GeyserMC/Geyser#4853] opened 2024-07-13 02:24 UTC
### Describe the bug

A player playing with the bedrock edition sometimes does not load the world, and there is simply emptiness instead of the world, such as a legal Xray, how can this be fixed? I tried to break the block, but it didn't help

### To Reproduce

1. Download my version of geyser
2. Set up it config
3. Play on bedrock

### Expected behaviour

Its just not loading a part of world

### Screenshots / Videos

![Screenshot_20240713-091550](https://github.com/user-attachments/assets/dea50c91-2f1b-427c-b6b9-60702c1d81e3)

### Server Version and Plugins

1.17.1 paper
Plugins (52): AdvancedEnchantments, AntiRelog, AuthMe, BanItem, BetterCommandSpy, BetterTalismans, BlockedCmds*, ChatEx, ChestCommands*, Citizens, Clans, CoreProtect, CrazyAuctions, DecentHolograms, DeluxeMenus, DiscordSRV, DonateCase, EliteRTP, EnotGranter*, Essentials, EssentialsSpawn, ExecutableItems, FastAsyncWorldEdit (WorldEdit), Geyser-Spigot, HeadDatabase, HealthBar*, HideStream*, LiteBans, LuckPerms, Matrix, MobsManager, MyCommand, MyPads, NBTAPI, NoLagg*, Pholo*, PlaceholderAPI, PlayerKits, PlayerManagementPlugin, PlayerPoints, ProtocolLib, sBroadcast*, SCore, SkinsRestorer, TAB, Vault, ViaBackwards, ViaVersion, voicechat, WGExtender, WorldGuard, YouTube*

### Geyser Dump

https://dump.geysermc.org/3PYJrYhqcRedYZq8rvA2zFDK3hLLLXY1

### Geyser Version

#599, paperSpigot

### Minecraft: Bedrock Edition Device/Version

1.21.2

**Comment by onebeastchris** [comment] 2024-07-13 17:29
Thanks for reporting the bug here. Unfortunately, it is a duplicate of https://github.com/GeyserMC/Geyser/issues/3809 - hence ill close this report. Thanks anyways!

**Closed by onebeastchris** 2024-07-13 17:29 UTC
