### ISSUE TITLE
Exception in Raknet, Causing lag on the server for bedrock players. 

### ISSUE THREAD

**Issue by Hades5514** [GeyserMC/Geyser#1595] opened 2020-11-26 07:25 UTC
**Describe the bug**
Whenever anyone plays on Bedrock, its very laggy, and the console is constantly spewing out errors pertaining to Raknet and java exceptions. 

**To Reproduce**
I'm unsure how to reproduce this error. I have tried deleting and re-installing, resetting the configs, and making sure my server is completely up to date. but despite all this, the errors return. 

**Expected behaviour**
This error shouldn't appear. 

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/67989452/100320037-895d1980-2fb8-11eb-8bc2-94fe42a20b7e.png)

**Server Version**
Paper version git-Paper-294 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Geyser Version**
This server is running Geyser version 1.2.0-SNAPSHOT (git-master-894275b) (Java: 1.16.4, Bedrock: 1.16.100.60 - 1.16.200.56)

**Minecraft: Bedrock Edition Version**
1.16.100

**Additional Context**
https://dump.geysermc.org/SN2SklN4uEDjBnmcqSxLmWWfkK0jCaGe

**Comment by toinouH** [comment] 2020-11-26 08:30
Could you try without plugin except Geyser and Floodgate please ?

**Comment by Hades5514** [comment] 2020-11-26 09:00
> Could you try without plugin except Geyser and Floodgate please ?

I did this, same errors, same lag.. I should also note that as per an earlier solution, I took my MTU to 700 and the scoreboard packet thresh hold to 5, but this did not work either, and so I've reverted them back to normal. 

https://dump.geysermc.org/i3jFdZsrca7aVkSD0p6Z5cMo9Z9rH7W6

**Comment by SupremeMortal** [comment] 2020-11-26 10:51
Do you have a firewall that could be blocking the connection? Maybe an iptables rule.

**Comment by Hades5514** [comment] 2020-11-27 00:36
> Do you have a firewall that could be blocking the connection? Maybe an iptables rule.

Nope, I checked this and there is no firewall blocking it

**Comment by vijaypondini** [comment] 2021-01-08 09:57
> **Describe the bug**
> Whenever anyone plays on Bedrock, its very laggy, and the console is constantly spewing out errors pertaining to Raknet and java exceptions. 
> 
> **To Reproduce**
> I'm unsure how to reproduce this error. I have tried deleting and re-installing, resetting the configs, and making sure my server is completely up to date. but despite all this, the errors return. 
> 
> **Expected behaviour**
> This error shouldn't appear. 
> 
> **Screenshots / Videos**
> ![image](https://user-images.githubusercontent.com/67989452/100320037-895d1980-2fb8-11eb-8bc2-94fe42a20b7e.png)
> 
> **Server Version**
> Paper version git-Paper-294 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
> 
> **Geyser Version**
> This server is running Geyser version 1.2.0-SNAPSHOT (git-master-894275b) (Java: 1.16.4, Bedrock: 1.16.100.60 - 1.16.200.56)
> 
> **Minecraft: Bedrock Edition Version**
> 1.16.100
> 
> **Additional Context**
> https://dump.geysermc.org/SN2SklN4uEDjBnmcqSxLmWWfkK0jCaGe
> 

Hello I can see you are using ggservers. And the issue is with them, not Geyser.

I am personally angry for you, because I contacted ggservers regarding this issue. I opened a ticket, wrote paragraphs on this error becuase I had this error for months, spamming my console for days on end. Screenshots, dumps and a lot of huff and puff later, their response - contact the authors of the plugin.

Regardless of what you do, you can't fix this raknet error because I tried for way too long, and gg servers won't fix it. It's only a problem with their hosting. 

Switch hosters. GGServers are not that reliable given my experience with the same issue you had

Regards

**Comment by rubenvde** [comment] 2021-01-10 13:35
Got the same issue as described. I'm using Spigot 1.16.4 and currently the latest Geyser build [574](https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/574/).

**Comment by Camotoy** [comment] 2021-01-10 16:21
Can you try this PR: https://github.com/GeyserMC/Geyser/pull/1775? 

To download a pull request (or a "PR") you need to:
1. Make sure you are signed in with a GitHub account
2. Click on the pull request link
3. Follow the guide on this picture: https://i.ibb.co/tCcB1Qp/PR1.png

**Comment by rubenvde** [comment] 2021-01-11 13:43
@Camotoy yes this seems to have fixed the issue! :)

**Comment by Camotoy** [comment] 2021-02-18 02:15
#1775 should have fixed this issue. If not, I will reopen it!

**Closed by Camotoy** 2021-02-18 02:15 UTC
