### ISSUE TITLE
ViaVersion Broken PIPE

### ISSUE THREAD

**Issue by zRedblood** [GeyserMC/Geyser#577] opened 2020-05-16 19:30 UTC
There are a problem when BedRock player try to join on a 1.14 server that allow 1.15.2 players to join thanks ViaVersion plugin, this cause crash of Geyser Proxy/Plugin.

Fix this and add a blacklist servers for bungee to deny player join in certain servers.

Error: https://pastebin.com/raw/SQpRYbrt

**Comment by DoctorMacc** [comment] 2020-05-16 19:32
Please follow the issue template.

**Comment by RednedEpic** [comment] 2020-05-16 19:39
Duplicate of #384, and disable ping passthrough for the time being to fix this.

**Closed by RednedEpic** 2020-05-16 19:39 UTC
