### ISSUE TITLE
Read timeout for every single bedrock player after Geyser and Floodgate update

### ISSUE THREAD

**Issue by RealKomander** [GeyserMC/Geyser#4254] opened 2023-10-29 18:37 UTC
### Describe the bug

Bedrock players are disconnected due to timeout

I'm using last versions of GeyserMC + floodgate velocity-3.2.0-SNAPSHOT-290, I will send any additional information if required

```
[21:20:50 INFO]: [connected player] .RealKomander (/IP) has disconnected: An internal error occurred in your connection.
[21:20:50 INFO] [floodgate]: Player RealKomander using Floodgate disconnected
[21:20:50 ERROR]: [connected player] .RealKomander (/IP): read timed out
[21:20:50 INFO] [geyser]: RealKomander disconnected from Java server for a reason An internal error occurred in your connection.
[21:20:50 INFO]: [server connection] .RealKomander -> lobby has disconnected
```

Several errors were written in russian, I translated them

Mu backend server is fabric 1.20.1 and I can't update it to 1.20.2, latest geyser and floodgate don't work on it

### To Reproduce

Download latest geyser and floodgate for velocity

### Expected behaviour

Time out error for all bedrock players

### Server Version and Plugins

velocity-3.2.0-SNAPSHOT-290 + a network of paper 1.20-1.20.1 and fabric 1.20-1.20.1 servers

### Geyser Dump

https://dump.geysermc.org/q85qM3OuOfkNCRsMXrSrxwjPKX46QLDK

### Geyser Version

build #340

### Minecraft: Bedrock Edition Device/Version

1.20.30, 1.20.40

**Comment by onebeastchris** [comment] 2023-10-30 07:32
Likely duplicate of https://github.com/GeyserMC/Geyser/issues/4236.

Additionally:
- Check if 1.20.2 Java clients can join.
- You will need to install ViaVersion, ideally on the 1.20.1 server, if that is not an option, you will need to install it on the proxy.
- See if removing auth plugins helps - offline mode is *not* supported.

**Closed by onebeastchris** 2023-10-30 07:32 UTC

**Comment by RealKomander** [comment] 2023-10-30 11:14
- 1.20.2 players can join
- viaversion, as well as viabackwards are installed
- this sucks
I guess the only thing I can hope for is that it magically fixes by itself...
