### ISSUE TITLE
Skins locked to 8x8 resolution and does not update automatically

### ISSUE THREAD

**Issue by nixybuilder** [GeyserMC/Geyser#4475] opened 2024-03-03 21:55 UTC
### Describe the bug

Im trying to use 16x16 skin or higher resolution skin on bedrock and it shows as 8x8 on bedrock
The skins doesnt change when i update it, i need to restart server

### To Reproduce

1. When i try to use higher resolution skin, it doesnt update my skin.
2. I need to restart server for it to update my skin.
3. After server restart i find out it shows as 8x8 skin and not the 16x16.

### Expected behaviour

Should update and work with higher resolution skins and load skins automatically after player switches skin

### Screenshots / Videos

![Snímka obrazovky 2024-03-03 223915](https://github.com/GeyserMC/Geyser/assets/145860929/a9b155e5-2a8c-4e7a-af77-e951fd02d81b)
![Snímka obrazovky 2024-03-03 223922](https://github.com/GeyserMC/Geyser/assets/145860929/9617a192-4742-43d9-b4e2-17c63e058592)

### Server Version and Plugins

[22:48:39 INFO]: This server is running Paper version git-Paper-443 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 60218cd)

[22:49:21 INFO]:  - Commanditem, CrossplatForms, DecentHolograms, Essentials, EssentialsChat, EssentialsDiscord, EssentialsProtect, EssentialsSpawn, ExcellentCrates, floodgate, Geyser-Spigot, GSit, LuckPerms, Multiverse-Core, NexEngine, ProtocolLib, SimplePets, VeinMiner, WorldEdit

### Geyser Dump

https://dump.geysermc.org/6A5LDRPuUmuF6vRU2yAedxmrlXKJxHMH

### Geyser Version

2.2.2-SNAPSHOT (git-master-5d95bf6)

### Minecraft: Bedrock Edition Device/Version

1.20.60, WIndows PC and also 1.20.62 iPhone

**Comment by rtm516** [comment] 2024-03-07 17:13
Skin change will never work while you're connected to the server. The bedrock client only sends the skin data on connection and not at any other time.

**Comment by Kas-tle** [comment] 2024-03-17 03:59
Given RTM's statement this seems to be intended behavior based on our current caching policy I'll close this.

**Closed by Kas-tle** 2024-03-17 03:59 UTC
