### ISSUE TITLE
No Armorstands and no Skins withs newest Version

### ISSUE THREAD

**Issue by zikdriver** [GeyserMC/Geyser#1869] opened 2021-01-26 19:09 UTC
**Describe the bug**

I cant see nothing Armorstands (with Skull and Armor) on my JavaServer with Win10 or PocketEdition 

**To Reproduce**

**Expected behavior**

**Screenshots / Videos**

Smartphone (Bug): https://i.imgur.com/Ovb5XfD.png

PC Javaversion(Thats right): https://i.imgur.com/cfPJIuK.png
 

**Server Version and Plugins**
WaterFall 1.16-393 (Proxyversion)
Paper1.8 Spigot
Own Plugins, (Lobbysystem), ViaVersion 3.2.1, CloudNet V2.1.17 

**Geyser Dump**

https://dump.geysermc.org/tDTvaH5OpPykXHlH8fbZ9o7m3cx70Beb

**Minecraft: Bedrock Edition Version**

Newest Smartphoneversion: 1.16.201

**Additional Context**

/

**Comment by Camotoy** [comment] 2021-01-26 19:56
This is a duplicate of #1251, so I am closing. Thank you anyway for the report!

**Closed by Camotoy** 2021-01-26 19:56 UTC
