### ISSUE TITLE
Inventory clearing and crafting issues in Bedrock

### ISSUE THREAD

**Issue by vijaypondini** [GeyserMC/Geyser#1245] opened 2020-09-03 05:09 UTC
**Describe the bug**
Attempting to craft sticks in MCPE, causes the players inventory to completely clear, ( probably follows the sticks not stacking properly in inventory issue while crafting ). There is a small chance while crafting furnaces in MCPE and windows 10 too, that the inventory gets cleared again. Using recipe book in MCPE also causes inventory to vanish from time to time.
Attempting to exit the crafting interface in bedrock with items still in the slots possibly causes the inventory to clear as well

**To Reproduce**
1. Just attempt to craft sticks in MCPE, or craft any tools using the recipe book in it. 

**Expected behavior**
Inventory gets cleared, a yellow colour appears on the item count

**Screenshots / Videos**

https://drive.google.com/file/d/1F8Sa6rabHeY2_zxzQJ-zafe9tACcunyA/view?usp=drivesdk - 1st video showing the attempt to craft an iron chestplate and items clearing when he exits the interface.
https://drive.google.com/file/d/1eoChSkCTWJBazi5ZYkwuynU7-7Nwe2Gh/view?usp=sharing - 2nd video showing an attempt to craft sticks and the inventory clears

**Server Version**
Paper version git-Paper-135 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Geyser Version**
Geyser version 1.1.0 (git-master-2f9ff0c) (Java: 1.16.2, Bedrock: 1.16.0 - 1.16.100)

**Minecraft: Bedrock Edition Version**
Minecraft 1.16.2 Bedrock ( Latest )

**Additional Context**
I know this issue might have already been reported, but i'd like to report it again, so that you know this issue is kinda high priority ( though i'm not the one to keep asking for fixes asap lol ). Hope to see this fixed soon though. :)

**Comment by DoctorMacc** [comment] 2020-09-03 14:47
1: Does relogging make the items appear again?
2: Please provide a Geyser dump.

I do not believe this has been reported - #1032 is *related* but seems to not be caused by crafting.

**Comment by vijaypondini** [comment] 2020-09-04 02:46
Hey, i'd like to close the issue with a little misconception on my end. 
[ERROR] Could not pass event InventoryClickEvent to PerWorldChatPlus v5.1.1
[ERROR] Could not pass event InventoryClickEvent to PerWorldChatPlus v5.1.1
[ERROR] Could not pass event CraftItemEvent to PerWorldChatPlus v5.1.1
[ERROR] Could not pass event InventoryClickEvent to PerWorldChatPlus v5.1.1
[ERROR] Could not pass event CraftItemEvent to PerWorldChatPlus v5.1.1
[ERROR] Could not pass event InventoryClickEvent to PerWorldChatPlus v5.1.1
[ERROR] Could not pass event CraftItemEvent to PerWorldChatPlus v5.1.1
[ERROR] Could not pass event InventoryClickEvent to PerWorldChatPlus v5.1.1
[ERROR] Could not pass event CraftItemEvent to PerWorldChatPlus v5.1.1
[ERROR] Could not pass event InventoryClickEvent to PerWorldChatPlus v5.1.1
[ERROR] Could not pass event CraftItemEvent to PerWorldChatPlus v5.1.1
[ERROR] Could not pass event InventoryClickEvent to PerWorldChatPlus v5.1.1
[ERROR] Could not pass event CraftItemEvent to PerWorldChatPlus v5.1.1
[ERROR] Could not pass event InventoryClickEvent to PerWorldChatPlus v5.1.1
This plugin is clearly interfering during a crafting event on minecraft pocket edition ( probably because of it not supporting the bridge b/w the versions ) and causes the inventory to clear since it doesn't know what to do. I am extremely sorry for wasting ur guys' time with the bug i kept rambling on about it..

**Comment by DoctorMacc** [comment] 2020-09-04 02:48
I'm glad you found the issue! I'll be closing this issue for now since a solution was found - if there's something we need to do on our end to fix those issues (I don't think we need to but I could be wrong) let us know.

**Closed by DoctorMacc** 2020-09-04 02:48 UTC
Labels: More Info Needed, Unconfirmed Bug
