### ISSUE TITLE
Donkey's inventory not being displayed when right-clicking

### ISSUE THREAD

**Issue by 1MagicSweet** [GeyserMC/Geyser#916] opened 2020-07-07 19:52 UTC
**Describe the bug**
Title is pretty much describe the full situation

**To Reproduce**
1. Join a server
2. Try to open donkey's inventory with shift+right click on it or sit on and press an "open inventory" button.

**Expected behavior**
Donkey's inventory gui opens when shift+click and same for click when sitting ()

**Screenshots / Videos**
Singleplayer:
![Annotation 2020-07-07 224659](https://user-images.githubusercontent.com/49122140/86835001-3388e300-c0a4-11ea-9729-b06910c52163.png)
![Annotation 2020-07-07 224758](https://user-images.githubusercontent.com/49122140/86835002-34ba1000-c0a4-11ea-8a08-13ebde35cb46.png)

Java server:
![Annotation 2020-07-07 224919](https://user-images.githubusercontent.com/49122140/86835032-3d124b00-c0a4-11ea-9c87-441a22bfcba9.png)

**Server Version**
1.16.1, vanilla

**Geyser Version**
git-feature/1.16-5f6566a

**Minecraft: Bedrock Edition Version**
1.16.1

**Additional Context**
When you try to open donkey's inventory when sitting on it player's inventory opens

**Comment by DoctorMacc** [comment] 2020-07-07 20:32
Duplicate of #639. Thank you for reporting anyway!

**Closed by DoctorMacc** 2020-07-07 20:32 UTC
