### ISSUE TITLE
Can’t see chat messages on Bedrock 1.19

### ISSUE THREAD

**Issue by OpenSourcery4321** [GeyserMC/Geyser#3154] opened 2022-07-20 03:19 UTC
### Describe the bug

Hi, I was wondering if I could troubleshoot here:

I am experiencing an issue wherein I can’t see any chat messages or announcements (someone died or joined the server) from other players, even while the chat is open. 

I can still send commands, but this appears to be only a problem for me as one of the Bedrock players on the server.

My theory is the reason either might be 1.19 or GeyserMC.

My Specs:
- OS: iPadOS
- iOS Version: 15 
- Server Hosting: Aternos
- Geyser and Server Version: 1.19
- Minecraft Launcher Version and Edition: 1.19 & Bedrock

### To Reproduce

1. Create an Aternos Java Edition Server with the following plugins (All Latest Versions)
A. Chunky 
B. SkinsRestorer
C. GeyserMC
D. HuskHomes
E. SleepFixer
F. LightPerms

2. Open the server with an iPad iOS version 15 with Bedrock edition. 

3. See if the chat works with other players.

### Expected behaviour

When joining the server, I am still able to run commands, but I am unable to see any kind of messages from any other players. 

Whether it’s them chatting or server announcements such as a death message if they get killed by any mob.

### Geyser Version

1.19

### Minecraft: Bedrock Edition Device/Version

1.19, iPadOS

**Comment by Camotoy** [comment] 2022-07-20 18:13
Try without LightPerms? This sounds like something permissions-wise is getting in the way.

**Comment by Jens-Co** [comment] 2022-07-24 20:13
Any info on this issue? :)

**Comment by TraceLosu** [comment] 2022-08-07 18:34
Same issue on my server. I run GeyserMC on the proxy while floodgate on the backend servers. One of my backend server's chats is working fine, however. But, after moving all plugins from the server with working chat to the server with broken chat, the issue persists.

It seems like every time a chat message is recieved/sent, this error occurs:
`[11:30:14 WARN] [geyser]: Downstream packet error! invalid click action:  
[11:30:14 ERROR]: com.google.gson.JsonParseException: invalid click action:  
[11:30:14 ERROR]:       at net.kyori.adventure.text.serializer.gson.IndexedSerializer.read(IndexedSerializer.java:58)
[11:30:14 ERROR]:       at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
[11:30:14 ERROR]:       at com.google.gson.Gson.fromJson(Gson.java:991)
[11:30:14 ERROR]:       at net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:124)
[11:30:14 ERROR]:       at net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:49)
[11:30:14 ERROR]:       at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
[11:30:14 ERROR]:       at com.google.gson.Gson.fromJson(Gson.java:991)
[11:30:14 ERROR]:       at com.google.gson.Gson.fromJson(Gson.java:1062)
[11:30:14 ERROR]:       at com.google.gson.Gson.fromJson(Gson.java:1034)
[11:30:14 ERROR]:       at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:214)
[11:30:14 ERROR]:       at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:56)
[11:30:14 ERROR]:       at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
[11:30:14 ERROR]:       at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
[11:30:14 ERROR]:       at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
[11:30:14 ERROR]:       at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
[11:30:14 ERROR]:       at com.google.gson.Gson.fromJson(Gson.java:991)
[11:30:14 ERROR]:       at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:173)
[11:30:14 ERROR]:       at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:95)
[11:30:14 ERROR]:       at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:56)
[11:30:14 ERROR]:       at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
[11:30:14 ERROR]:       at com.google.gson.Gson.fromJson(Gson.java:991)
[11:30:14 ERROR]:       at com.google.gson.Gson.fromJson(Gson.java:956)
[11:30:14 ERROR]:       at com.google.gson.Gson.fromJson(Gson.java:905)
[11:30:14 ERROR]:       at com.google.gson.Gson.fromJson(Gson.java:876)
[11:30:14 ERROR]:       at org.geysermc.geyser.text.GsonComponentSerializerWrapper.deserialize(GsonComponentSerializerWrapper.java:66)
[11:30:14 ERROR]:       at org.geysermc.geyser.text.GsonComponentSerializerWrapper.deserialize(GsonComponentSerializerWrapper.java:40)
[11:30:14 ERROR]:       at com.github.steveice10.mc.protocol.codec.MinecraftCodecHelper.readComponent(MinecraftCodecHelper.java:271)
[11:30:14 ERROR]:       at com.github.steveice10.mc.protocol.packet.ingame.clientbound.ClientboundSystemChatPacket.<init>(ClientboundSystemChatPacket.java:23)
[11:30:14 ERROR]:       at com.github.steveice10.mc.protocol.codec.MinecraftPacketSerializer.deserialize(MinecraftPacketSerializer.java:21)
[11:30:14 ERROR]:       at com.github.steveice10.mc.protocol.codec.MinecraftPacketSerializer.deserialize(MinecraftPacketSerializer.java:10)
[11:30:14 ERROR]:       at com.github.steveice10.packetlib.codec.PacketDefinition.newInstance(PacketDefinition.java:54)
[11:30:14 ERROR]:       at com.github.steveice10.packetlib.packet.PacketProtocol.createClientboundPacket(PacketProtocol.java:159)
[11:30:14 ERROR]:       at com.github.steveice10.mc.protocol.MinecraftProtocol.createClientboundPacket(MinecraftProtocol.java:187)
[11:30:14 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpPacketCodec.decode(TcpPacketCodec.java:62)
[11:30:14 ERROR]:       at io.netty.handler.codec.ByteToMessageCodec$1.decode(ByteToMessageCodec.java:42)
[11:30:14 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
[11:30:14 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
[11:30:14 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
[11:30:14 ERROR]:       at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[11:30:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:30:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:30:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[11:30:14 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[11:30:14 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
[11:30:14 ERROR]:       at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[11:30:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:30:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:30:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[11:30:14 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[11:30:14 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
[11:30:14 ERROR]:       at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[11:30:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:30:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:30:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[11:30:14 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[11:30:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:30:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:30:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[11:30:14 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[11:30:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[11:30:14 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[11:30:14 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[11:30:14 ERROR]:       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[11:30:14 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
[11:30:14 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
[11:30:14 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[11:30:14 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[11:30:14 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[11:30:14 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by Camotoy** [comment] 2022-08-07 18:35
I don't think there's anything we can do about that - that's a bug we fixed in Adventure, but it hasn't been pulled into a release yet, so Velocity is still bugged. You can change back to standalone for now, or I believe VentureChat is the offending plugin here.

**Comment by TraceLosu** [comment] 2022-08-07 18:43
> I don't think there's anything we can do about that - that's a bug we fixed in Adventure, but it hasn't been pulled into a release yet, so Velocity is still bugged. You can change back to standalone for now, or I believe VentureChat is the offending plugin here.

I see. I doubt it's VentureChat, though, as it works fine for one of the backend servers I mentioned.

**Comment by TraceLosu** [comment] 2022-08-17 10:33
> > I don't think there's anything we can do about that - that's a bug we fixed in Adventure, but it hasn't been pulled into a release yet, so Velocity is still bugged. You can change back to standalone for now, or I believe VentureChat is the offending plugin here.
> 
> I see. I doubt it's VentureChat, though, as it works fine for one of the backend servers I mentioned.

Haha, I was wrong. It was VentureChat. I forgot to check if the config files were exactly the same. And there was a difference. Updating VentureChat to 1.19 resulted in the config's `jsonformatting` section (the part that handled hover and click actions) to change.

The error was, literally, an invalid click action caused by misconfiguration. 😅

**Comment by Jens-Co** [comment] 2022-10-13 19:16
Ill close this issue since its patched.

**Closed by Jens-Co** 2022-10-13 19:16 UTC
Labels: Waiting On Response
