### ISSUE TITLE
setGliding packet/method for CraftBukkit/Paper doesnt work properly for bedrock players

### ISSUE THREAD

**Issue by Dueris** [GeyserMC/Geyser#4109] opened 2023-09-07 23:53 UTC
### Describe the bug

Upon running the method setGliding on the Player interface for a normal Java player, it sets the player gliding like it would if they had an elytra for abt 1 tick. When put in a runnable it makes it execute continuously creating an infinite elytra flight effect. However, upon running this on a Bedrock/Geyser player, it wouldn't execute correctly, making the method do absolutely nothing, unless they have an elytra already equipped to the Bedrock player.

### To Reproduce

Create a new BukkitRunnable with a task timer of 1 ticks with no delay, inside it get the current online players(or specify it with Bukkit.getPlayer("name")), and set the player gliding by using <player instance>.setGliding(true);

Place that in your onEnable method and join on java, you should be in a gliding state as if you had activated your elytra. Join on bedrock and it does nothing until you have an elytra equipped.

### Expected behaviour

Set the Bedrock player to a gliding state

### Server Version and Plugins

Geyser, Spark, GenesisMC, WorldEdit

Paper latest build, 1.20.1

### Geyser Dump

Not able to atm, not at computer

### Geyser Version

Latest

### Minecraft: Bedrock Edition Device/Version

Latest bedrock, windows 10 edition

**Comment by Konicai** [comment] 2023-09-08 00:00
Duplicate of #3255

**Closed by Konicai** 2023-09-08 00:00 UTC
