### ISSUE TITLE
Server Players Random Timeout 

### ISSUE THREAD

**Issue by WinterMiller** [GeyserMC/Geyser#4672] opened 2024-05-18 18:33 UTC
### Describe the bug

The bug will randomly time out / disconnect all players connected to a proxy, this bug happens in velocity & bungee cord. 

### To Reproduce

Have a velocity server 1.20.4 
Have geyser velocity 
Have via version in the backend servers(unknown if related)
Have 2 or more geyser player or java players 

### Expected behaviour

It will time out all the players connect to the proxy, including java players. 

### Screenshots / Videos

Not mine but my feed looked just like this 
![IMG_20240515_170644](https://github.com/GeyserMC/Geyser/assets/140283559/23c5a6a3-2072-4dc9-82a3-7237842c401d)

### Server Version and Plugins

Proxy
Velocity (1.20.4) (build 389) (3.3.0-Snapshot)
——-
Plugins
Geyser Velocity 
Floodgate velocity 
———
====+
———-
Backend servers
Paper (1.20.4-R0.1-SNAPSHOT) (git:7ac24a1) ver/1.20.4 
——-
Plugins 
- floodgate
- Executable Items
- Citizens
- Decent holograms
- Essentials
- Fawe
- Placeholder api
- Worldguard
- Auraskills 
- AdvancedEnchants 
- Battlepass
- BetterRtp
- Betterteams 
- Chunky
- Commandpanels
- Coreprotect
- Corssplatforms
- Dilyrewards
- Greif prevention
- Playershopplus
- PvpManger
- SimpleScore
- SimpleSounds
- Spark
- SpawnerMeta
- VariableChest
- ViaVersion
- VillagerOverhual 
- YamipaPlugin

### Geyser Dump

https://dump.geysermc.org/Vq2mYcLk6nUc1VFYzkf6rWCXmhgak6xh

### Geyser Version

Build 533 geyser velocity 

### Minecraft: Bedrock Edition Device/Version

Laptop, xbox, phone

### Additional Context

Sometimes its 20 mins sometimes it takes 3 hours.

**Comment by onebeastchris** [comment] 2024-05-18 23:21
Closing as this is likely a duplicate of https://github.com/GeyserMC/Geyser/issues/4620. Unfortunately, this is one of those issues that are near impossible to debug - since this could be related to networking on the players side, or the hosts side, or some fault in the plugin.
 
If you're able to provide more details about when/how this occurs, please do so on the linked issue.

**Closed by onebeastchris** 2024-05-18 23:21 UTC
Labels: Unconfirmed Bug/Not Currently Replicable
