### ISSUE TITLE
Inventory & Master, Bedrock client crashes with floodgate

### ISSUE THREAD

**Issue by applebee1558** [GeyserMC/Geyser#208] opened 2020-03-14 01:04 UTC
Reproduce:
Install Floodgate plugin on bungeecord
Start the latest master/inventory proxy with floodgate
Join the server

Fix:
Turn bungeecord to offline mode and remove floodgate plugin
(this removes the purpose of floodgate though)

**Comment by LogicismDev** [comment] 2020-03-14 01:05
Yes this is a known issue, we are currently fixing this.

**Comment by RednedEpic** [comment] 2020-03-14 15:33
Duplicate of #206.

**Closed by RednedEpic** 2020-03-14 15:33 UTC
Labels: Duplicate, Invalid
