### ISSUE TITLE
Bedrock Players occasionally losing their prefix. 

### ISSUE THREAD

**Issue by Kazii78** [GeyserMC/Geyser#5087] opened 2024-10-19 18:32 UTC
### Describe the bug

I'm using Paper 1.21.1 using GeyserMC and Floodgate. Occasionally, bedrock players would not receive their prefix before their username and I'm guessing the server treats it as a new player. The player loses all their items, gets teleported to spawn, etc.. Basically a reset. This is only temporary tho. If they re-log, they likely get their prefix back and get all their progress back. But I have this issue where someone has done quite lots of progress on their account without the prefix. They are unable to get their stuff. 

This has happend to other bedrock players too.

### To Reproduce

I don't know how to reproduce it. Hope for the server to screw up, I guess?

![grafik](https://github.com/user-attachments/assets/edb6f918-015f-4705-85c4-3e5ba6b7d5af)

Possible steps, haven't tried.

### Expected behaviour

Bedrock players should always have their prefix.

### Screenshots / Videos

![grafik](https://github.com/user-attachments/assets/4684df4e-d000-4e52-9fde-26e13d00aac7)
![grafik](https://github.com/user-attachments/assets/af2aeb64-5cd0-4e89-a774-376bda77b68e)

"naif820" is a bedrock player.
Right now, they've only been getting the period.

### Server Version and Plugins

/version -> "This server is running Paper version 1.21.1-DEV-master@755a775 (2024-10-18T04:27:17Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)"

Plugins:
- Chunky (Chunky-1.4.10.jar)
- Discord-Linker (Discord-Linker-3.5.1.jar)
- Floodgate (floodgate-spigot.jar)
- GeyserMC (Geyser-Spigot.jar)
- LetUrMemoryRest (LetUrMemoryRest-3.2.jar)
- LibreLogin (LibreLogin.jar)
- LowTPSRestart (LowTPSRestart.jar)
- ProtocolLib (ProtocolLib.jar)
- SkinsRestorer (SkinsRestorer.jar)
- TabListPing (TabListPing-1.06.jar)
- TabTPS (tabtps-spigot-1.3.25.jar)

### Geyser Version

2.4.3-b689 (git-master-d64c0b3)

### Minecraft: Bedrock Edition Device/Version

1.21.31

### Additional Context

We are playing with cracked player support.

**Comment by onebeastchris** [comment] 2024-10-19 21:18
This issue is a duplicate of https://github.com/GeyserMC/Geyser/issues/5086 - and the reason you're not seeing that disconnection screen but are being connected without the prefix is because you're running in offline mode. We do not support offline mode. 
As a workaround, don't enable offline mode.

**Closed by onebeastchris** 2024-10-19 21:18 UTC
