### ISSUE TITLE
Worldborder bug

### ISSUE THREAD

**Issue by SoenkeK** [GeyserMC/Geyser#2087] opened 2021-03-29 22:17 UTC
### Describe the bug

As bedrock Player You cant see the Worldborder and you can go trough it. 

### To Reproduce

1. go to the Worldborder or set the World border to you
2. You cant see it and you can go trough the Worldborder

### Expected behaviour

You cant go trough the Worldborder

### Geyser Dump

https://dump.geysermc.org/BffefPpswYNTIanhhvvToJ37nHzSt5YQ

### Geyser Version

 1.3.0-SNAPSHOT (git-floodgate-2.0-677a8d6) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.210)

### Minecraft: Bedrock Edition Version

1.16.210

**Comment by Camotoy** [comment] 2021-03-29 22:18
Duplicate of #447. Thank you for reporting anyway!

**Closed by Camotoy** 2021-03-29 22:18 UTC
