### ISSUE TITLE
Item frames do not show up on bedrock clients if there is another block in the same space.

### ISSUE THREAD

**Issue by hw2007** [GeyserMC/Geyser#3747] opened 2023-05-05 18:30 UTC
### Describe the bug

On java edition, you can use item frames in combination with other blocks or other item frames. For example, a button and an item frame can be on the same tile, and multiple item frames can also be in the same tile together. On bedrock, only one of the item frames will render if there are multiple on the same spot, and if there is an item frame + a block, either only the block or only the frame will render.

This issue makes some build tricks such as anvils in frames combined with torches or infinity rooms look bad on bedrock.

### To Reproduce

1. On a java client, place down a button.
2. Place an item frame on the same spot as the button, notice how you can see both the frame and button
3. Go on a bedrock client, and look at the same spot. Either only the button or only the frame will be visible.

### Expected behaviour

Bedrock players should see it exactly as java players see it.

### Server Version and Plugins

Paper version git-Paper-466 (MC: 1.19.4)
Plugins: floodgate, Geyser-Spigot, GeyserHacks, MinecraftDiscordWebhook, ViaBackwards, ViaVersion, voicechat

### Geyser Dump

https://dump.geysermc.org/s8PB0j8GCi4JT7RZEapTCM83LSHCTQXR

### Geyser Version

2.1.0-SNAPSHOT (git-master-8a25afb)

### Minecraft: Bedrock Edition Device/Version

It happens on all versions and devices

**Comment by onebeastchris** [comment] 2023-05-05 18:34
Duplicate of https://github.com/GeyserMC/Geyser/issues/1491 - this issue is caused by Bedrock edition seeing item frames as blocks, and as two blocks (unlike block + entity) cannot collide on bedrock, you only see the one

**Comment by onebeastchris** [comment] 2023-05-21 10:03
Closing, as it's effectively a duplicate of #1491

**Closed** 2023-05-21 10:04 UTC
Labels: Duplicate, Confirmed Bug
