### ISSUE TITLE
Real IP address without floodgate

### ISSUE THREAD

**Issue by chelminski** [GeyserMC/Geyser#1594] opened 2020-11-25 12:17 UTC
Hello! Please add an IP redirection option so that the Spigot server sees the real address of the player.I am using bungee and currently when someone connects via Geyser, Spigot sees IP as 172.15 .... This is very problematic when I need to verify the player's account in order to recover the password, and when I need to block the address due to multi-accounts. Also, I can't check if a player is using multiple accounts because I can only see 172.15 ... Thank you in advance.

I apologize if something is not clearly written. English is not my primary language.

**Comment by ad1tya2** [comment] 2020-11-25 14:09
Why dont you want to use floodgate ? https://cdn.discordapp.com/emojis/779230462295146507.gif

**Comment by chelminski** [comment] 2020-11-25 21:34
> Why dont you want to use floodgate ? @chelminski

Players lose all progress in the game and do not need this type of authentication.

**Comment by Chew** [comment] 2020-11-25 23:16
They can always link their accounts to their java accounts...

**Comment by chelminski** [comment] 2020-11-25 23:18
> They can always link their accounts to their java accounts...

Players can only join from bedrock. There are no Java accounts.

**Comment by DoctorMacc** [comment] 2020-11-25 23:21
It is a problem because we have to modify the server in order to display the real IP address. Geyser has thus far been successful in not needing to modify the server - Floodgate does that for us.

**Comment by chelminski** [comment] 2020-11-25 23:49
> It is a problem because we have to modify the server in order to display the real IP address. Geyser has thus far been successful in not needing to modify the server - Floodgate does that for us.

Is there a solution to this problem? To add real IP address display without any extras? Is it possible to extract the code from the floodgate responsible for this process and create a small bungee plugin? The mentioned function is very important to me. I understand that this may be a problem for you, I am asking for help. I can wait.

**Comment by awgybop1** [comment] 2020-11-30 04:12
The way Geyser works is by creating a translation proxy that the players connect through. Because of this, the IP address of the player will always be the IP of the proxy (the server Geyser is running on). Floodgate fixes this problem by providing an authentication layer, and when it verifies a player it tricks the server into thinking the player is using a specific username and connecting from a specific IP address (similar to Bungeecord). The authentication layer can be a problem because if you're using shared hosting and you login to your account from Geyser, Mojang can potentially take it as a security threat and lock your account which is not fun - this is why it is recommended to use floodgate and simply link your Java accounts. Geyser can also be run by itself on a standalone server, where this direct server modification would not work - which is why Floodgate exists only as a plugin.

To answer your question:
Yes, there is a solution and it CAN be done, but just use Geyser and Floodgate together, because the chances of this being implemented into Geyser itself are very slim.

If I am understanding correctly you are running a Java server but only allowing Bedrock players to connect?
Is your server cracked? Because otherwise I don't see how you are doing this without Java accounts.
And you say players lose their data, why is this? Are their UUIDs changing?

**Comment by lukeeey** [comment] 2020-11-30 04:21
@awgybop1 If the java server is cracked while only allowing bedrock players then there’s not really a problem as the verification only works for java players.

**Comment by chelminski** [comment] 2020-11-30 07:09
> The way Geyser works is by creating a translation proxy that the players connect through. Because of this, the IP address of the player will always be the IP of the proxy (the server Geyser is running on). Floodgate fixes this problem by providing an authentication layer, and when it verifies a player it tricks the server into thinking the player is using a specific username and connecting from a specific IP address (similar to Bungeecord). The authentication layer can be a problem because if you're using shared hosting and you login to your account from Geyser, Mojang can potentially take it as a security threat and lock your account which is not fun - this is why it is recommended to use floodgate and simply link your Java accounts. Geyser can also be run by itself on a standalone server, where this direct server modification would not work - which is why Floodgate exists only as a plugin.
> 
> To answer your question:
> Yes, there is a solution and it CAN be done, but just use Geyser and Floodgate together, because the chances of this being implemented into Geyser itself are very slim.
> 
> If I am understanding correctly you are running a Java server but only allowing Bedrock players to connect?
> Is your server cracked? Because otherwise I don't see how you are doing this without Java accounts.
> And you say players lose their data, why is this? Are their UUIDs changing?

Yes, after installing floodgate, bedrock players start connecting via the uuid generated By floodgate. The new UUID is a new account.

**Comment by Chew** [comment] 2020-11-30 16:11
Yes, if Bedrock/Floodgate players connect, they can link their Java account, so when they join on bedrock, they will join as their Java account. If they don't have a Java account, they will fallback to the Floodgate account.

**Comment by chelminski** [comment] 2020-12-01 12:17
> Yes, if Bedrock/Floodgate players connect, they can link their Java account, so when they join on bedrock, they will join as their Java account. If they don't have a Java account, they will fallback to the Floodgate account.

I followed your advice and created a discord vote. 764 people voted that they want one account for multiple platforms, and 14 people want separate accounts or linked accounts.So I stick to my opinion.

**Comment by EasyClifton** [comment] 2020-12-01 13:19
Well, you are free to implement this in your own version of Geyser or wherever you want. Geyser and Floodgate are open-source for that matter.

**Comment by chelminski** [comment] 2020-12-03 21:08
> Well, you are free to implement this in your own version of Geyser or wherever you want. Geyser and Floodgate are open-source for that matter.

I am not a programmer. If I were, I wouldn't be asking the creators for help.

**Comment by EasyClifton** [comment] 2020-12-03 21:25
> > Well, you are free to implement this in your own version of Geyser or wherever you want. Geyser and Floodgate are open-source for that matter.
> 
> I am not a programmer. If I were, I wouldn't be asking the creators for help.

Well, they already told you they won't.

**Comment by chelminski** [comment] 2020-12-03 21:31
> > > Well, you are free to implement this in your own version of Geyser or wherever you want. Geyser and Floodgate are open-source for that matter.
> > 
> > 
> > I am not a programmer. If I were, I wouldn't be asking the creators for help.
> 
> Well, they already told you they won't.

I don't understand the problem. Like anyone, I can request a feature. You don't have to be mean to me.

**Comment by Talie5in** [comment] 2020-12-04 00:32
@chelminski You've asked for a "Real IP" and "Not needing Java accounts" - Floodgate covers this aspect.
If the issue is due to the new UUID you can always be a server admin, let them log in once with Floodgate, log out, then you move their playerdata to the new UUID.

As per Geyser Floodgate wiki "Floodgate is a hybrid mode plugin which allows for **Minecraft: Bedrock Accounts** to join **Minecraft: Java Edition servers without needing a Minecraft: Java Edition account.** This is something you install in addition to Geyser."

> 
> I followed your advice and created a discord vote. 764 people voted that they want one account for multiple platforms, and 14 people want separate accounts or linked accounts. 

Once again, if they want 1 account for multiple platforms (Java + Bedrock) then this would be achieved using Floodgate to link the accounts, this sounds like Floodgate is the option your "Discord Vote" is asking for.

**Comment by DoctorMacc** [comment] 2020-12-04 00:41
I'm closing this as the discussion has taken its course. Floodgate works effectively for 99% of server owners, and the use-case described here appears to be very specific. Real IP addresses may come to Geyser in the future, but this is very low priority.

**Closed by DoctorMacc** 2020-12-04 00:41 UTC
