### ISSUE TITLE
Banner Pattern not showing up for Bedrock

### ISSUE THREAD

**Issue by SamGamerYT** [GeyserMC/Geyser#3378] opened 2022-11-01 16:09 UTC
### Describe the bug

Weird issue with Bedrock again, Previously which was confirmed and fixed by Camotoy in the past, Players can't view all of the banners again in Loom.

Will provide picture of the banner that's viewable in java but not bedrock.

https://gyazo.com/c229bd4d1e5b28b6fe9369eb957c8038

### To Reproduce

Grab the following items
/give <Name> WHITE_BANNER 1
/give <Name> BLACK_DYE 1

/loom (if you have essential or place a loom down)

### Expected behaviour

It should show the pattern in the image but it doesn't

### Screenshots / Videos

Repost: https://gyazo.com/c229bd4d1e5b28b6fe9369eb957c8038

### Server Version and Plugins

Purpur-1835 1.19.2
Latest Geyser as of the Reporting Time.

### Geyser Version

#1225 Master

### Minecraft: Bedrock Edition Device/Version

HM Latest Mobile Version, Xbox and Playstation.

**Comment by onebeastchris** [comment] 2022-11-01 16:10
please attach a Geyser dump, just to have a full overview

**Comment by Camotoy** [comment] 2022-11-01 16:35
I don't think there's anything we can do about it without a hack.

**Comment by SamGamerYT** [comment] 2022-11-01 17:19
I'm so lost on that comment @Camotoy 

https://dump.geysermc.org/yHFF8iFksjYQMwpGACG6Dn1TFCZ9nFgl

**Comment by onebeastchris** [comment] 2023-11-03 11:08
Duplicate of https://github.com/GeyserMC/Geyser/issues/3183 - can't fix since we can't add patterns to the loom.

**Closed by onebeastchris** 2023-11-03 11:08 UTC
Labels: Can't Fix
