### ISSUE TITLE
Command completion crashes the client

### ISSUE THREAD

**Issue by ClayCoffee** [GeyserMC/Geyser#1530] opened 2020-11-12 14:51 UTC
**Describe the bug**

When I join in a server with LOTS of commands, the command completion crashes the client.(make it not response)

**To Reproduce**

1. Join in a server with LOTS of commands
2. type "/" in the chatting area
3. the client crashes

**Expected behavior**

The command will auto complete correctly.

**Screenshots / Videos**

**Server Version**

This server is running Paper version git-Paper-264 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Geyser Version**

1.1.0 (git-master-ea52107) (Java: 1.16.4, Bedrock: 1.16.0 - 1.16.20)

**Minecraft: Bedrock Edition Version**

**Additional Context**

https://dump.geysermc.org/ylzwYOBukkGr3lVmyPedG1MJKrqUjhDf

**Comment by rtm516** [comment] 2020-11-12 15:01
Thanks for the report but this is a duplicate of #870

> This is a known issue with the client, please set `command-suggestions` to `false` in the config.

**Closed by rtm516** 2020-11-12 15:01 UTC
