### ISSUE TITLE
Add support with Aikar Commands Framework

### ISSUE THREAD

**Issue by xtomyserrax** [GeyserMC/Geyser#2670] opened 2021-12-04 16:50 UTC
### What feature do you want to see added?

Hey, how are you? Ive noticed that many servers are using Geyser and are loving how it works.

Many server owners asked me if I could add support for Bedrock players but sadly its out of my reach because Im using ACF to handle commands (a framework made by the author of Paper which makes a lot of stuff easier such as registering commands, editing them, disabling them, tab completion, etc.).

Is it possible that you could add support for this framework? Many plugins are using ACF right now and maybe in a better future more authors will turn to this as it has a lot of advantages.

Basicly the issue is that when the command is sent, ACF says player is not online.

https://github.com/aikar/commands

Dont know if its possible to add support for this but its worth the try I guess.

Thank you!

### Are there any alternatives?

None

**Comment by Camotoy** [comment] 2021-12-04 17:00
`Basicly the issue is that when the command is sent, ACF says player is not online.`

This sounds like a Floodgate issue - are you in a position to try with just Geyser?

**Comment by xtomyserrax** [comment] 2021-12-04 18:54
Yeah the guy told me he is using Geyser and Floodgate. He told me he was going to try with Geyser only. Ill let you know, thanks!

**Comment by Konicai** [comment] 2021-12-07 01:03
Likely an issue in ACF with 
https://github.com/aikar/commands/blob/master/core/src/main/java/co/aikar/commands/ACFPatterns.java#L47
and/or
https://github.com/aikar/commands/blob/master/bukkit/src/main/java/co/aikar/commands/ACFBukkitUtil.java#L265-L299

treating the floodgate prefix as invalid

**Comment by Camotoy** [comment] 2022-02-24 19:19
I'm closing this as there's likely nothing we can do about this, as Konica pointed out. Thanks anyway.

**Closed by Camotoy** 2022-02-24 19:19 UTC
Labels: Feature Request
