### ISSUE TITLE
Haven't received PlayerListEntry packet

### ISSUE THREAD

**Issue by Eisenbahn** [GeyserMC/Geyser#3442] opened 2022-12-08 22:40 UTC
### Describe the bug

Hi!
So, I've just updated to Geyser (Build #1250 (8 de dez de 2022 03:55:00)) and it started not showing some MythicMobs entities (Plugin MythicMobs), specially the ones that use the Libdisguise to set custom Skins. This happens ONLY TO BEDROCK. Java is fine.

So ive tried to update Viaversion and ViaBackwards and Libdisguise, but no success.
I'm using Geyser Standalone and PaperSpigot 1.12.2

-Citizens works fine with custom skins.

Not sure about the error below, but i noticed this too. Which is new.
```
[18:07:36 WARN] Downstream packet error! String is longer than maximum allowed length
[18:07:36 ERROR] Haven't received PlayerListEntry packet before spawning player! We ignore the player b283c25f-074e-4539-8c15-f623ff443764
[18:07:36 WARN] Downstream packet error! String is longer than maximum allowed length
[18:07:36 ERROR] Haven't received PlayerListEntry packet before spawning player! We ignore the player a1efd173-d3f4-4cba-9a15-ff996dea131a
[18:07:36 WARN] Downstream packet error! String is longer than maximum allowed length
[18:07:36 ERROR] Haven't received PlayerListEntry packet before spawning player! We ignore the player da7629bf-382f-46e5-81cd-ef37a7a4cc54
[18:09:01 WARN] Downstream packet error! String is longer than maximum allowed length
[18:09:01 ERROR] Haven't received PlayerListEntry packet before spawning player! We ignore the player 70a02b9d-8cd1-4869-b793-f538da919b1f
[18:09:07 WARN] Downstream packet error! String is longer than maximum allowed length
[18:09:07 ERROR] Haven't received PlayerListEntry packet before spawning player! We ignore the player 01bbd13c-10e6-467a-b8be-d2b3e5c521dd
```

### To Reproduce

Mythicmobs MythicMobs-4.13.0.jar
ViaVersion 4.5.1
ViaBackwards 4.5.0
LibsDisguises-10.0.31-Free

### Expected behaviour

--

### Server Version and Plugins

--

### Geyser Dump

https://dump.geysermc.org/716ku3AFzSQ5IhIUH2FlQL7Al1XURtvr

### Geyser Version

git-master-57e3437)

### Minecraft: Bedrock Edition Device/Version

1.19.41

**Comment by onebeastchris** [comment] 2024-06-11 06:43
Does this issue still occur? If it does, please enable the debug-mode setting in Geysers configuration file, restart, and send a new log.

**Comment by onebeastchris** [comment] 2024-06-11 06:51
Okay, going to close this issue then as I'm unable to reproduce this issue.

**Closed** 2024-06-11 06:51 UTC
Labels: Unconfirmed Bug/Not Currently Replicable, Waiting On Response
