### ISSUE TITLE
A few days after the ban, "That player does not exist".

### ISSUE THREAD

**Issue by siyukatu** [GeyserMC/Geyser#4400] opened 2024-01-19 01:42 UTC
### Describe the bug

It has been several days since the bedrock player was banned.
When I run "pardon <name>" I get "That player does not exist".
This is the same result for "pardon <UUID>" or "whitelist add <name>".

Also, the geysermc plugin is not installed on the origin server, since it is running through Waterfall as a proxy server.
The pardon command was executed on the origin server.

### To Reproduce

1. BAN Bedrock player
2. Wait a few days
3. Trying to unban bedrock player (ERROR!)

### Expected behaviour

Successful pardon command.
"Unbanned <NAME>"

### Geyser Version

2.2.0-SNAPSHOT (git-master-95d6535) at waterfall proxy

**Comment by onebeastchris** [comment] 2024-03-02 17:27
Duplicate of https://github.com/GeyserMC/Floodgate/issues/399 - currently, you'd have to manually modify the banned player list json file.

**Closed by onebeastchris** 2024-03-02 17:27 UTC
