### ISSUE TITLE
PS5 Player can't strip logs

### ISSUE THREAD

**Issue by ZedaMC** [GeyserMC/Geyser#4869] opened 2024-07-17 10:34 UTC
### Describe the bug

PS5 Player's can't strip logs.
This only happens to PS5 players.

### To Reproduce

1. Get an axe
2. Try to strip some logs

### Expected behaviour

Logs turn into stripped logs

### Server Version and Plugins

This server is running Paper version 1.21-27-master@76c2f16 (2024-06-22T18:19:36Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are 54 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.20.6-115-9d6f2cc (MC: 1.20.6)

### Geyser Version

This server is running Geyser version 2.4.0-b609 (git-master-669a76c) (Java: 1.21, Bedrock: 1.20.80/1.20.81 - 1.21.2/1.21.3)

### Minecraft: Bedrock Edition Device/Version

PS5 latest version

**Comment by onebeastchris** [comment] 2024-07-17 20:57
Try updating Geyser, and paper - if that doesnt fix it, please send a geyser dump (run `geyser dump` in the server console, and send the link you get here)

**Comment by MrZomka** [comment] 2024-07-17 23:45
Just tried it on my iPad with a Switch Pro Controller. Couldn't reproduce the issue. I assume it's PS4/PS5 specific.

**Comment by Camotoy** [comment] 2024-07-18 02:43
Is the player also holding a shield?

**Comment by onebeastchris** [comment] 2024-09-02 14:19
Closing this due to no further response. Possible duplicate of https://github.com/GeyserMC/Geyser/issues/4871

**Closed** 2024-09-02 14:19 UTC
Labels: Unconfirmed Bug/Not Currently Replicable
