### ISSUE TITLE
unable to craft in bedrock client

### ISSUE THREAD

**Issue by BlackKnight683** [GeyserMC/Geyser#1406] opened 2020-10-15 04:55 UTC
**Describe the bug**
 Unable To Craft Anything Anywhere

**To Reproduce**

 A Minecraft Java Edition offline 1.8.8 server from a bedrock client
 A Crafting Table Or Use Inventory Crafting
 Any Item
 Nothing Pops Up To Be Able To Craft

**Expected behavior**
 Should be able to craft items

**Screenshots / Videos**
 
![Screenshot_2020-10-15-10-16-04-816_com mojang minecraftpe](https://user-images.githubusercontent.com/69863661/96078507-21eb7e80-0ed0-11eb-9e82-08a392b15c88.jpg)
![Screenshot_2020-10-15-10-16-33-854_com mojang minecraftpe](https://user-images.githubusercontent.com/69863661/96078512-244dd880-0ed0-11eb-88bd-acbeb130f1c4.jpg)
![Screenshot_2020-10-15-10-16-49-173_com mojang minecraftpe](https://user-images.githubusercontent.com/69863661/96078513-24e66f00-0ed0-11eb-965a-8a69cce5331c.jpg)

**Server Version**
 1.8.8

**Geyser Version**
 [Thu, 15. Oct 2020 04:53:52 GMT INFO] This server is running Geyser version 1.1.0 (git-master-2ca2436) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.20)
[Thu, 15. Oct 2020 04:53:52 GMT INFO] Checking version, please wait...
[Thu, 15. Oct 2020 04:53:52 GMT INFO] No updates available.

**Minecraft: Bedrock Edition Version**
 1.16.2

**Additional Context**
 https://dump.geysermc.org/VPO7RDcMhfI1l9i0VEY9InljlSxMQjyh

**Comment by RednedEpic** [comment] 2020-10-15 04:56
Duplicate of #511. This is because you are running an outdated server version. Please consider updating to 1.12 or higher for the time being if you would like to craft.

**Closed by RednedEpic** 2020-10-15 04:56 UTC

**Comment by MrZomka** [comment] 2020-10-15 17:03
Also, GeyserMC team doesn’t not condone piracy, so no support until you would switch ‘online-mode’ to true :/
