### ISSUE TITLE
If a server has a plugin that kicks players without the server resource pack, it's not possible to join via Geyser Standalone

### ISSUE THREAD

**Issue by Hedwig7s** [GeyserMC/Geyser#3836] opened 2023-06-08 20:44 UTC
### Describe the bug

The title explains it all really there's plugin that kick players without the server's resource pack and geyser gets kicked by it

### To Reproduce

1. Go on any server with a plugin that kicks players without the pack (like ForcePack)
2. Join via Geyser Standalone
3. Wait a few seconds

### Expected behaviour

Geyser should fake the resource pack loaded packet to bypass this

### Screenshots / Videos

Kick message from a server:
<img width="420" alt="image" src="https://github.com/GeyserMC/Geyser/assets/51961150/64e45eb7-bdf6-4dc7-8c5d-37a062d54d83">

### Server Version and Plugins

<img width="314" alt="image" src="https://github.com/GeyserMC/Geyser/assets/51961150/cb332156-8763-4a8c-85c1-dcba984a0efe">

### Geyser Version

Build #170

### Minecraft: Bedrock Edition Device/Version

v1.19.83 Windows & Android

### Additional Context

This only happens on servers with a plugin like ForcePack

**Comment by Camotoy** [comment] 2023-06-09 03:44
> Geyser should fake the resource pack loaded packet to bypass this

This is generally not an approach we want to take... we don't want to lie that the packet has been loaded. The exception of course would be if you own the server and have already translated the resource pack for Bedrock players, but at that point you can probably exempt them as well.

**Comment by Hedwig7s** [comment] 2023-06-09 07:36
> This is generally not an approach we want to take... we don't want to lie that the packet has been loaded. The exception of course would be if you own the server and have already translated the resource pack for Bedrock players, but at that point you can probably exempt them as well.

Well unless you can translate the resource packs in the near future that's the only way to bypass it really

**Comment by onebeastchris** [comment] 2023-06-10 23:23
Duplicate of https://github.com/GeyserMC/Geyser/issues/1796 - closing this in favor of the older issue.

**Closed by onebeastchris** 2023-06-10 23:23 UTC
