### ISSUE TITLE
Downstream packet error!

### ISSUE THREAD

**Issue by Ibotmealot** [GeyserMC/Geyser#3608] opened 2023-03-14 23:35 UTC
### Describe the bug

[19:32:00 WARN]: [Geyser-Spigot] Downstream packet error! null
[19:32:00 WARN]: [Geyser-Spigot] Downstream packet error! null
[19:32:00 WARN]: [Geyser-Spigot] Downstream packet error! null
[19:32:00 WARN]: [Geyser-Spigot] Downstream packet error! null
[19:32:00 WARN]: [Geyser-Spigot] Downstream packet error! null
[19:32:00 WARN]: [Geyser-Spigot] Downstream packet error! null

Just sends in the console and spams it a bunch

### To Reproduce

Literally nothing, it just shows up...

### Expected behaviour

For it to not spam said error? 

### Server Version and Plugins

This server is running Paper version git-Paper-386 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 4da844f)

Plugins (52): BetterRTP, BuycraftX, ChatManager, ChatReaction, Chunky, ChunkyBorder, ConsoleSpamFix, CoreProtect, DailyRewardsPlus, DeluxeMenus, DeluxeWithdraw, DeluxeWithdrawEXPAddon, DeluxeWithdrawVaultAddon, DiscordSRV, EconomyShopGUI, Essentials, EssentialsSpawn, floodgate, FreedomChat, Geyser-Spigot, GriefPrevention, GSit, HarvestEXP, Infiniteannouncements, InventoryRollbackPlus, KauriVPN, LibertyBans, LPC, LuckPerms, MiniMOTD, NoMobGriefing, OpenInv, PlaceholderAPI, Plan, PlayerWarps, PreventStabby, ProtocolLib, QuickShop, SimplePets, spark, squaremap, squaremap-griefprevention, squaremap-vanish, SuperVanish, TAB, TradeSystem, UltimateAutoRestart, Vault, ViaBackwards, ViaVersion, Vulcan, zAuctionHouseV3

### Geyser Dump

https://dump.geysermc.org/AnyAsWRIzIjT7a5POjZ9J0kDJeHT20MZ

### Geyser Version

 2.1.0-SNAPSHOT

**Comment by 0swin** [comment] 2023-03-14 23:38
I have this same error.  
My server is running Fabric 1.19.3 and latest Geyser version, while my client runs bedrock 1.19.70.  
The client is stuck on "Locating World" while I have the same console spam as OP, that also makes the server TPS drops and the server laggy for all players.
Here is also my dump :  

https://dump.geysermc.org/Qu2tE9bBvEC09AzJZ5Xwwofuk9kfjZGE

**Comment by Ibotmealot** [comment] 2023-03-15 18:50
![image](https://user-images.githubusercontent.com/42391199/225412909-48a0f62b-16e4-4148-9112-88108000fc17.png)
There's nothing in startup though
![image](https://user-images.githubusercontent.com/42391199/225413150-6b29859c-2b41-45e0-85cc-23f9d6f80808.png)
![image](https://user-images.githubusercontent.com/42391199/225413174-36dbf942-708e-4d5c-ab94-757cce2b0180.png)
![image](https://user-images.githubusercontent.com/42391199/225413209-242ab454-1fbd-469a-b3aa-fc2fb32ad5bd.png)

**Comment by DarkChromaMC** [comment] 2023-03-17 06:14
We're getting this error too x2

**Comment by Ibotmealot** [comment] 2023-03-17 17:18
![image](https://user-images.githubusercontent.com/42391199/225974267-20eb8945-2057-4aca-9abf-2c0e01e1e1b0.png)
@Camotoy any ideas? I provided the logs above

**Comment by Ibotmealot** [comment] 2023-03-18 02:49
![image](https://user-images.githubusercontent.com/42391199/226080453-323facbb-7201-40a3-9f8d-0d39cf0dd517.png)
spam goes on

**Comment by M8torr** [comment] 2023-03-18 04:51
Experiencing the same issue with Geyser-Standalone (#26) with Fabric 1.19.3 and using ViaFabric 0.4.9+24-main and ViaBackwards 4.5.1

https://dump.geysermc.org/sg3m84fCkp2ciridQPjJI1LlHQYci2hq

**Comment by Camotoy** [comment] 2023-03-19 23:36
Can y’all try updating and see if the issue is resolved?

**Comment by Camotoy** [comment] 2023-04-03 01:20
Closing since there's been no new reports. Thanks!

**Closed by Camotoy** 2023-04-03 01:20 UTC
