### ISSUE TITLE
Console getting spammed by a warning message.

### ISSUE THREAD

**Issue by ZeTioZ** [GeyserMC/Geyser#1269] opened 2020-09-09 23:43 UTC
**Describe the bug**
Hi, I have installed Geyser and it seems that when a player connected through it, the console is spammed by this warning message...
(it does spam it until the player don't disconnect from the server.

**To Reproduce**
1. Connect to the server.
2. The console get spammed.

**Expected behavior**
Not to be spammed.

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/12181249/92665302-7c5c5280-f306-11ea-8d8f-c60c28f2ac1c.png)

**Server Version**
1.16.1

**Geyser Version**
Geyser version 1.1.0 (git-master-d47360d) (Java: 1.16.2, Bedrock: 1.16.0 - 1.16.100)

**Minecraft: Bedrock Edition Version**
beta 1.16.30.52

**Comment by BenjiButton** [comment] 2020-09-10 09:23
This is caused by a bug in TitleManager 2.3.1, please use version 2.3.0 which does not have this bug

**Comment by Comstepr** [comment] 2020-09-15 13:28
@ZeTioZ Your bug report is **incomplete.**

Missing:
- /geyser dump
- /version

You are using an outdated Geyser version as well. Try updating Geyser.

**Comment by Chew** [comment] 2021-04-05 23:48
The author hasn't responded to the mini-triage(?) above, and a fix has been provided as well. If you happen to run into this issue again (with the suggested fix), please open a new issue and we'll be happy to handle it there. Thank you for your contributions!

**Closed by Chew** 2021-04-05 23:48 UTC
