### ISSUE TITLE
Bedrock client crashes when logging into server

### ISSUE THREAD

**Issue by Dhenier** [GeyserMC/Geyser#2296] opened 2021-06-18 04:00 UTC
### Describe the bug

Bedrock player joins Spigot server with whitelist turned off.
Only plugins: Geyser-Spigot build 723, floodgate-spigot build 11.
No one else is on the server. 
(I have tested this using a localhost and on the remote host. Same results.)

Server console shows that the player connected and the IP address they connected from.
The Bedrock client shows loading resources and then crashes.
After awhile the console shows player disconnected TIMED OUT.

### To Reproduce

1) Login to Windows 10 MC
2) Click on Join Server
3) Window shows Generating World and then Loading Resources
4) Crash

### Expected behaviour

Load into the world without the client crashing.

### Screenshots / Videos

![Bedrock Crash - Event Viewer Log](https://user-images.githubusercontent.com/5112730/122503721-f7a21180-cfc6-11eb-9e0f-909aa71d8ecc.png)
![Bedrock-LocalHost Loading Resources](https://user-images.githubusercontent.com/5112730/122503736-fd97f280-cfc6-11eb-96b6-3e23876af7a6.png)
![Bedrock-LocalHost Port](https://user-images.githubusercontent.com/5112730/122503747-025ca680-cfc7-11eb-87dc-880498e45cbb.png)
![Bedrock-Crom Online](https://user-images.githubusercontent.com/5112730/122503754-04bf0080-cfc7-11eb-86ba-6e0b68375286.png)
![Bedrock-LocalHost Online](https://user-images.githubusercontent.com/5112730/122503763-0688c400-cfc7-11eb-9333-32ccd750a6ed.png)
[Event Viewer - Data Output for Crash.txt](https://github.com/GeyserMC/Geyser/files/6674479/Event.Viewer.-.Data.Output.for.Crash.txt)

### Geyser Dump

https://dump.geysermc.org/FsJvfvmvdVk9wrUabR9OVZkwUpimWQPR

### Geyser Version

Build 723 Dated June 16, 2021 

### Minecraft: Bedrock Edition Version

Microsoft.MinecraftUWP_1.17.2.0_x64__8wekyb3d8bbwe

### Additional Context

I have also tried with the 19132 port but Bedrock could never locate the server at that port. 

Config files are below:
[Geyser-config.txt](https://github.com/GeyserMC/Geyser/files/6674488/Geyser-config.txt)
[floodgate-config.txt](https://github.com/GeyserMC/Geyser/files/6674489/floodgate-config.txt)

**Comment by Camotoy** [comment] 2021-06-18 15:36
Adding unconfirmed bug since I've been joining Spigot 1.17 fine with Bedrock.

**Comment by Dhenier** [comment] 2021-06-19 21:01
I believe this is a Microsoft bug. We have people now on the server who are on java, android tablet, and windows 10 bedrock. So you can close this. Don't think it is a geyser bug. Ty for looking at it.

**Comment by robotjohn** [comment] 2021-06-20 18:02
I was having the same issue and in my case i fixed it by removing all placed Java 1.17 candles from the world

**Comment by Camotoy** [comment] 2021-06-20 18:06
Noted. I will close this since the original user has resolved their issue.

**Closed by Camotoy** 2021-06-20 18:06 UTC
Labels: Unconfirmed Bug
