### ISSUE TITLE
Update on issue #4224

### ISSUE THREAD

**Issue by shawn695** [GeyserMC/Geyser#4226] opened 2023-10-18 16:21 UTC
### Describe the bug

the bug still persists even with making the disconect message as short as possible

```18.10 15:39:23 [Server] INFO [Geyser-BungeeCord]: Player connected with username silentbutginger
18.10 15:39:23 [Server] INFO [Geyser-BungeeCord]: silentbutginger (logged in as: silentbutginger) has connected to the Java server
18.10 15:39:23 [Server] INFO [floodgate]: Floodgate player logged in as .silentbutginger joined (UUID: 00000000-0000-0000-0009-000009bc2d96)
18.10 15:39:23 [Server] INFO [.silentbutginger] disconnected with: Kicked whilst connecting to Main: YOU MUST LINK YOUR DISCORD ACCOUNT TO PLAY!!.
18.10 15:39:23 [Server] INFO Find The discord channel thats says {Link Code Here}
18.10 15:39:23 [Server] INFO And only enter this 4 digit code >> 0757 <<
18.10 15:39:23 [Server] INFO [floodgate]: Floodgate player logged in as .silentbutginger disconnected
18.10 15:39:23 [Server] WARN [Geyser-BungeeCord]: Downstream packet error! Packet "ClientboundLoginDisconnectPacket" not fully read.
18.10 15:39:23 [Server] INFO [Geyser-BungeeCord]: silentbutginger has disconnected from the Java server because of Connection closed.
18.10 15:39:23 [Server] INFO [/90.210.88.42:0|.silentbutginger] -> UpstreamBridge has disconnected```

### To Reproduce

use Discord Srv whitlist system 

### Expected behaviour

4 digit code to appear on client side screen to whitelist them self

### Screenshots / Videos

_No response_

### Server Version and Plugins

_No response_

### Geyser Dump

https://dump.geysermc.org/DWl7PdhRpvKnZWrw28TG4q8deuCd1awX

### Geyser Version

#333

### Minecraft: Bedrock Edition Device/Version

all bedrock devices

### Additional Context

this only happens for "NewCommers" joining.
this whitlist system has worked for over a year on my server(s) running geyser

**Comment by onebeastchris** [comment] 2023-11-01 13:29
Duplicate of https://github.com/GeyserMC/Geyser/issues/4049 - for the future, please just reply to the previous post instead of creating a new issue.

**Closed by onebeastchris** 2023-11-01 13:29 UTC
