### ISSUE TITLE
Allow sign-in without xbox

### ISSUE THREAD

**Issue by OurLobanov** [GeyserMC/Geyser#4685] opened 2024-05-22 15:22 UTC
### Describe the bug

Many players play without xbox, why not add the ability to enter the geyser without xbox
You can enter without Xbox by removing the server and then going to the Friends tab, where it will hang for a few seconds
There are also hacked versions of Minecraft that allow you to enter without removing the server, simply by clicking on the server
Why not add the option for admins to choose whether they want to admit such players?

### To Reproduce

..

### Expected behaviour

..

### Screenshots / Videos

https://youtu.be/GbdlgxCEN7g

### Geyser Version

2.3.1-SNAPSHOT git-master-a780eea

**Comment by onebeastchris** [comment] 2024-05-22 15:23
https://github.com/GeyserMC/Geyser/issues/1721 duplicate of e.g. this issue - we will not be adding this to Geyser.

**Closed by onebeastchris** 2024-05-22 15:23 UTC
