### ISSUE TITLE
when crafting minecart furnaces (funri?) on bedrock it crafts a minecart hopper instead

### ISSUE THREAD

**Issue by hurricaneJoef** [GeyserMC/Geyser#1603] opened 2020-11-28 17:24 UTC
**Describe the bug**

funance to hoppers using minecarts like the infinite soul soil campfire glitch
**To Reproduce**

go on ios and craft a minecart furnace and you will get a minecart hopper
**Expected behavior**

i expect to get a minecart furnace
**Screenshots / Videos**

https://cdn.discordapp.com/attachments/767805522912870454/782269409510686720/image0.png

**Server Version**

1.16.4 fabric 
**Geyser Version**

geyser fabric version 1.2.0-snapshot
(git master a70d3e2)
**Minecraft: Bedrock Edition Version**

ios 1.16.101
**Additional Context**

we are running carpet mod and lithium with a couple other small mods like carpet extra and right click farming and a discord integration mod too 
![image](https://user-images.githubusercontent.com/33767776/100521831-17c9ca80-3174-11eb-9bb3-99055319edf8.png)

**Comment by DoctorMacc** [comment] 2020-11-28 17:27
Essentially a duplicate of #1279, so I'm closing this to tidy up. The issue lies in that there is no furnace minecart in Bedrock. However, the item should place as a furnace minecart. Thank you for reporting anyway!

**Closed by DoctorMacc** 2020-11-28 17:27 UTC
