### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by DarkChromaMC** [GeyserMC/Geyser#3720] opened 2023-04-29 06:59 UTC
### Describe the bug

An exception was encountered during the deserialization of an InventoryTransactionPacket on our geysermc server (Velocity proxy) using the CloudburstMC protocol library. The root cause of the error is a `java.io.UTFDataFormatException` with the message `malformed input around byte 0`. This exception is thrown when the input data cannot be properly decoded as a valid UTF-8 string. The issue seems to be related to reading the item user data.

Console error spam:
[06:51:02 WARN] [io.netty.channel.DefaultChannelPipeline]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: org.cloudburstmc.protocol.bedrock.codec.PacketSerializeException: Error whilst deserializing InventoryTransactionPacket(legacyRequestId=0, legacySlots=[], actions=[], transactionType=ITEM_USE_ON_ENTITY, actionType=1, runtimeEntityId=3426, blockPosition=null, blockFace=0, hotbarSlot=2, itemInHand=null, playerPosition=null, clickPosition=null, headPosition=null, usingNetIds=false, blockDefinition=null)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at org.cloudburstmc.netty.channel.raknet.RakChannelPipeline.lambda$onUnhandledInboundMessage$0(RakChannelPipeline.java:60) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.cloudburstmc.protocol.bedrock.codec.PacketSerializeException: Error whilst deserializing InventoryTransactionPacket(legacyRequestId=0, legacySlots=[], actions=[], transactionType=ITEM_USE_ON_ENTITY, actionType=1, runtimeEntityId=3426, blockPosition=null, blockFace=0, hotbarSlot=2, itemInHand=null, playerPosition=null, clickPosition=null, headPosition=null, usingNetIds=false, blockDefinition=null)
        at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryDecode(BedrockCodec.java:59) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.decode(BedrockPacketCodec.java:57) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.decode(BedrockPacketCodec.java:19) ~[?:?]
        at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        ... 35 more
Caused by: java.lang.IllegalStateException: Unable to read item user data
        at org.cloudburstmc.protocol.bedrock.codec.v431.BedrockCodecHelper_v431.readItem(BedrockCodecHelper_v431.java:148) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.v291.serializer.InventoryTransactionSerializer_v291.readItemUseOnEntity(InventoryTransactionSerializer_v291.java:61) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.v407.serializer.InventoryTransactionSerializer_v407.deserialize(InventoryTransactionSerializer_v407.java:70) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.v407.serializer.InventoryTransactionSerializer_v407.deserialize(InventoryTransactionSerializer_v407.java:13) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryDecode(BedrockCodec.java:57) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.decode(BedrockPacketCodec.java:57) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.decode(BedrockPacketCodec.java:19) ~[?:?]
        at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        ... 35 more
Caused by: java.io.UTFDataFormatException: malformed input around byte 0
        at java.io.DataInputStream.readUTF(DataInputStream.java:661) ~[?:?]
        at io.netty.buffer.ByteBufInputStream.readUTF(ByteBufInputStream.java:301) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at org.cloudburstmc.nbt.NBTInputStream.deserialize(NBTInputStream.java:95) ~[?:?]
        at org.cloudburstmc.nbt.NBTInputStream.deserialize(NBTInputStream.java:107) ~[?:?]
        at org.cloudburstmc.nbt.NBTInputStream.deserialize(NBTInputStream.java:107) ~[?:?]
        at org.cloudburstmc.nbt.NBTInputStream.readTag(NBTInputStream.java:41) ~[?:?]
        at org.cloudburstmc.nbt.NBTInputStream.readTag(NBTInputStream.java:30) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.v431.BedrockCodecHelper_v431.readItem(BedrockCodecHelper_v431.java:132) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.v291.serializer.InventoryTransactionSerializer_v291.readItemUseOnEntity(InventoryTransactionSerializer_v291.java:61) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.v407.serializer.InventoryTransactionSerializer_v407.deserialize(InventoryTransactionSerializer_v407.java:70) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.v407.serializer.InventoryTransactionSerializer_v407.deserialize(InventoryTransactionSerializer_v407.java:13) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryDecode(BedrockCodec.java:57) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.decode(BedrockPacketCodec.java:57) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.decode(BedrockPacketCodec.java:19) ~[?:?]
        at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[velocity.jar:3.2.0-SNAPSHOT (git-dc7efd93-b237)]
        ... 35 more

### To Reproduce

Use the latest 1.19.8 release for GeyserMC velocity.
Connect to the server as a Bedrock player
Perform an action that triggers the generation of an InventoryTransactionPacket (e.g., using an item on an entity).

### Expected behaviour

The server should be able to deserialize the InventoryTransactionPacket without any issues, and the corresponding actions should be properly executed. Resulting in no console spam.

### Geyser Dump

https://dump.geysermc.org/VADhH0QD8QGQQXIB0cU8wtwktdVRs9rF

### Geyser Version

2.1.0-SNAPSHOT (git-master-c8afd34) (Java: 1.19.4, Bedrock: 1.19.40/1.19.41 - 1.19.80)

**Comment by frogglen** [comment] 2023-05-01 01:39
This is a likely duplicate of the https://github.com/GeyserMC/Geyser/issues/3710 issue

**Comment by Konicai** [comment] 2023-05-02 02:19
Should be fixed - please update

**Closed by Konicai** 2023-05-02 02:19 UTC
