### ISSUE TITLE
bedrock players unable to control camel entity

### ISSUE THREAD

**Issue by bajamaster13** [GeyserMC/Geyser#3957] opened 2023-07-09 21:29 UTC
### Describe the bug

during gameplay with both bedrock and java players on, bedrock players are unable to control the forward/ reverse movement of camels. Attempted a re-log and a server reset with no changes. 
![plugin list](https://github.com/GeyserMC/Geyser/assets/139079168/98d5aedd-64f7-4d1e-ba8e-6a0df292e8b8)
attached is a plugin list

### To Reproduce

1. get on server via bedrock
2. mount camel with saddle 
3. attempt to move.

### Expected behaviour

should be able to use the camel as expected.

### Geyser Dump

https://dump.geysermc.org/OkLBNqpKcBd3bITsfxDl3BUK2oQaOt89

### Geyser Version

Build #1447

### Minecraft: Bedrock Edition Device/Version

most recent update for the xbox version

**Comment by onebeastchris** [comment] 2023-07-09 21:30
Duplicate of https://github.com/GeyserMC/Geyser/issues/3860 - thanks for reporting anyways :)

**Closed** 2023-07-09 21:31 UTC
Labels: Duplicate
