### ISSUE TITLE
Fabric 1.17 Geyser and Floodgate

### ISSUE THREAD

**Issue by DistanceMC** [GeyserMC/Geyser#2292] opened 2021-06-17 03:42 UTC
### Describe the bug

When I try to run the Fabric versions of GeyserMC and floodgate together I get the error [Log](https://pastebin.com/GjNYefzs). Have I done something wrong? 

I have included the full log file.
[latest.log](https://github.com/GeyserMC/Geyser/files/6667201/latest.log)

### To Reproduce

1. Create a fresh 1.17 Fabric server
2. Install Geyser [Link I used](https://ci.opencollab.dev/job/GeyserMC/job/Geyser-Fabric/job/java-1.17/)
3. Run the server to generate configs
4. Install FloodGate [Link I used](https://ci.opencollab.dev/job/GeyserMC/job/Floodgate-Fabric/job/master/)
5. Run the server
6. Receive Error

### Expected behaviour

I expected the server to run with both mods installed

### Screenshots / Videos

Mods Folder
![image](https://user-images.githubusercontent.com/70821369/122327577-17203800-cefc-11eb-9bb5-d38d14a57b97.png)
Server Folder
![image](https://user-images.githubusercontent.com/70821369/122327605-21423680-cefc-11eb-8f38-a5e3a130ee08.png)

### Server Version and Plugins

FabricMC 1.17

### Geyser Dump

https://dump.geysermc.org/IoZbxERL8Ymn4RgHtRRJHPvlmI4ttbNQ

### Geyser Version

Geyser-Fabric-1.4.0-SNAPSHOT

**Comment by Konicai** [comment] 2021-06-17 03:53
Duplicate of https://github.com/GeyserMC/Floodgate-Fabric/issues/7#issuecomment-817022484

**Comment by DistanceMC** [comment] 2021-06-17 03:59
Thank you

**Closed** 2021-06-17 13:15 UTC
