### ISSUE TITLE
/gamemode spectator

### ISSUE THREAD

**Issue by whes1015** [GeyserMC/Geyser#2687] opened 2021-12-08 08:49 UTC
### Describe the bug

In /gamemode spectator mode,There is a high probability that the UI buttons that control the up and down will flash quickly, and the player's up and down activities will be uncontrollable

### To Reproduce

1. Switch to /gamemode spectator

### Expected behaviour

Should be normal like create mod

### Geyser Version

All Versions

### Minecraft: Bedrock Edition Version

All Versions

**Comment by rtm516** [comment] 2021-12-08 08:51
Thanks for the report but this is a duplicate of https://github.com/GeyserMC/Geyser/issues/1334

**Closed by rtm516** 2021-12-08 08:51 UTC
