### ISSUE TITLE
When riding a mob I can't walk on it

### ISSUE THREAD

**Issue by thiagogebrimm** [GeyserMC/Geyser#4004] opened 2023-07-20 16:49 UTC
### Describe the bug

when riding on mobs that are moved when I have a carrot or fungus in my hand, they don't move

### To Reproduce

1- Place the sadle on the mob
2- Ride it
3- Try to walk

### Expected behaviour

He obey and walk normally

### Screenshots / Videos

https://streamable.com/0qlj5p

### Server Version and Plugins

Current: git-Purpur-2015 (MC: 1.20.1)

### Geyser Version

2.1.2-SNAPSHOT (git-master-ea2bac4)

**Comment by Konicai** [comment] 2023-07-20 18:02
Duplicate of #638

**Closed by Konicai** 2023-07-20 18:02 UTC
