### ISSUE TITLE
Bedrock Users Loose Acces to Inventory

### ISSUE THREAD

**Issue by XttinaGarnet** [GeyserMC/Geyser#2916] opened 2022-04-03 09:36 UTC
### Describe the bug

Bedrock users lose access to their inventory after about a half-hour. If they log out and log back in everything goes blue. I am using apex hosting and I checked in with them and they think it is a geyser error. A similar problem happened a few months ago and installing an earlier version fixed the problem. However, that version isn't working with the current version of Minecraft. I have the most recent version of geyser, floodgate, and via version. I also have world guard, world edit,  and core protect.

### To Reproduce

1. Log onto an apex creative mode server from a bedrock device. 
2. Wait a half hour to 45 min
3. Try to access the inventory

### Expected behaviour

Inventory opens and users can search to new items.

### Server Version and Plugins

Spigot 1.18.2
Floodgate (most recent)
Geyser (most recent)
World Guard
World Edit
Core Protect
Via Version (most recent)

### Geyser Dump

https://dump.geysermc.org/s56bwyr255sLzhTU8V86DRXHJ7AFKmLY

### Geyser Version

2.0.2-SNAPSHOT (git-master-0067ba5)

### Minecraft: Bedrock Edition Version

1.18.2

**Comment by AnhNguyenlost13** [comment] 2022-04-06 08:37
Duplicate of #2861, maybe?

**Comment by Batman2741** [comment] 2022-05-13 18:01
I have the same issue when interacting with something at max height

**Comment by onebeastchris** [comment] 2023-04-26 00:27
This is a likely duplicate of the #2861 issue; try the fix there.
But due to a lack of response, this should be closed

**Closed** 2023-04-30 22:53 UTC
