### ISSUE TITLE
Kick only on one Bungee Sub Server

### ISSUE THREAD

**Issue by Leonlp9** [GeyserMC/Geyser#3543] opened 2023-02-09 21:09 UTC
### Describe the bug

https://cdn.discordapp.com/attachments/613170125696270357/1073343213059964928/20230209_214045.mp4

I programmed a feature that called Booster and since that it is like that in the video. I try to figure out what that is, but there is no console error. 

### To Reproduce

The only thing i had in onJoin addet is that: @EventHandler
    public void onJoin(PlayerJoinEvent e){
        if (e.getPlayer().hasPermission("citybuild.fly.bypass")){
            if (!e.getPlayer().isFlying()) {
                e.getPlayer().setAllowFlight(true);
                e.getPlayer().setFlying(true);
            }
        }else{
            if (e.getPlayer().isFlying()) {
                e.getPlayer().setFlying(false);
                e.getPlayer().setAllowFlight(false);
            }
        }
    }
    but without its also didnt work for me :/

### Expected behaviour

No timeout on citybuild server. on all other its work

### Screenshots / Videos

https://cdn.discordapp.com/attachments/613170125696270357/1073343213059964928/20230209_214045.mp4
or test it by your self on greenynet.de

### Server Version and Plugins

https://cdn.discordapp.com/attachments/1053346659486146720/1073349044828655676/image.png

### Geyser Dump

https://dump.geysermc.org/wCILSzwU6LmGuLfgHlqLP2qugNxK37VS

### Geyser Version

2.1.0-SNAPSHOT 3d97188

### Minecraft: Bedrock Edition Device/Version

1.19.60 for everyone on the server

**Comment by onebeastchris** [comment] 2023-02-09 21:12
anything in the logs of either of the servers when they're kicked?

**Comment by Leonlp9** [comment] 2023-02-10 18:24
Only lost connection

**Comment by Leonlp9** [comment] 2023-02-10 19:34
I removed my Plugin, it's works. But that is not the way to go.
That I removed every getServer().getPluginManager().registerEvents
Because I think there was something in onJoin, but still not working?

**Comment by onebeastchris** [comment] 2023-02-11 02:12
https://github.com/GeyserMC/Geyser/issues/2914
Could be this issue

**Comment by Leonlp9** [comment] 2023-02-11 12:18
I don't know how to properly describe it.  For some reason with me the bedrock players get kicked right after joining.  what should not be.  You can move for a short time but don't get it loading and repeating what you're doing after rejoining.  From the Java point of view, they go up and down again after 1s.  The funny thing is when the Bedrock player gets the rank Supporter from me, everything works, even if I delete my plugin.  But if I remove everything from the main in onEnable in my plugin, ie no events etc., then it still doesn't work.

**Comment by Leonlp9** [comment] 2023-02-11 12:19
and if i delete the event i send before it is also didnt work

**Comment by Leonlp9** [comment] 2023-02-15 14:46
bump

**Comment by onebeastchris** [comment] 2023-06-11 00:26
Closing as duplicate of https://github.com/GeyserMC/Geyser/issues/2914

**Closed by onebeastchris** 2023-06-11 00:26 UTC
