### ISSUE TITLE
Boat 

### ISSUE THREAD

**Issue by adalmo** [GeyserMC/Geyser#2908] opened 2022-03-30 12:53 UTC
### Describe the bug

when i tried to place the boat it got dissapear and it bring back to on my inventory

### To Reproduce

1. Try to place boat on water or somewhere
2. It got disappeared
3. whit for it or try to craft something with craftingtable
4. the boat bring back to the item on inventory

### Expected behaviour

1. Try to place boat on water or somewhere
2. It got disappeared
3. whit for it or try to craft something with craftingtable
4. the boat bring back to the item on inventory

### Geyser Version

Build #1068 Geyser.spigot.jar

### Minecraft: Bedrock Edition Version

1.18.12

**Comment by Konicai** [comment] 2022-03-30 22:05
Duplicate of https://github.com/GeyserMC/Geyser/issues/1247

**Closed by Konicai** 2022-03-30 22:05 UTC
