### ISSUE TITLE
Players in Bedrock Edition cannot use buckets, buckets, and magma buckets

### ISSUE THREAD

**Issue by JulStar2003** [GeyserMC/Geyser#978] opened 2020-07-19 18:06 UTC
Players in Bedrock Edition cannot use buckets, buckets, and magma buckets，Please fix it

**Comment by DoctorMacc** [comment] 2020-07-19 18:09
Hello! Next time please fill out the issue template, and ensure there isn't a duplicate issue. Since this is a duplicate of #321, I'm closing it.

**Closed by DoctorMacc** 2020-07-19 18:09 UTC
