### ISSUE TITLE
Geyser causes a dead lock

### ISSUE THREAD

**Issue by Legit4K** [GeyserMC/Geyser#2116] opened 2021-04-09 11:52 UTC
### Describe the bug

Geyser-Spigot causes a server dead lock and prevents the server from shutting down therefore interrupting automated restarts. 

### To Reproduce

Leave the server running for a few hours with both Java and Bedrock Players online and then execute /stop or have a Plugin such as [ServerRestart](https://www.spigotmc.org/resources/serverrestart-1-13-1-16.57570/) and configure it to run /stop when it's time to restart.

### Expected behaviour

Geyser should shutdown safely and allow the server to proceed and shutdown everything else.

### Screenshots / Videos
![Screenshot_20210409_160109](https://user-images.githubusercontent.com/44619264/114176061-1e532480-9954-11eb-8791-fb55b0655fff.jpg)

### Server Version and Plugins

This server is running Paper version git-
Paper-584 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Plugins (35): AuthMe, ChatControl, Chunkmaster, CommandTimer*, DeathCoordinates, DiscordSRV, eBackup, floodgate, Geyser-Spigot, GeyserSkinManager, GMusic, IllegalStack, LagAssist, LuckPerms, Noteblockapi, PacketListenerApi*, PlaceholderAPI, Plan, PluginConstructorAPI, PluginManager*, ProtocolLib, purecore, RandomSpawnPlus, ServerlistMOTD*, ServerRestart, SkinsRestorer, spark, Sudo*, Suicide*, Themis, Vault, ViaBackwards, ViaVersion, VillagerLobotomizatorNator, WorldBorder

### Geyser Dump

https://dump.geysermc.org/crayIo439yrT2Q20iUbr5rgHGZDTFlYm

### Geyser Version

 Geyser version 1.2 .1-SNAPSHOT (git-master-e549792) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.220)

### Minecraft: Bedrock Edition Version

1.16.220

### Additional Context

I'm able to reproduce this consistently with the steps provided, I used the Paper Server Software and the ServerRestart Plugin mentioned in the bug report description.

**Comment by Legit4K** [comment] 2021-04-12 09:45
I might have just narrowed down the cause of the issue, the dead lock happens when there is at least 1 Bedrock Player online and a shutdown is initiated with either `stop` or `geyser shutdown` command. So this leads me to believe its related to something near here: https://github.com/GeyserMC/Geyser/blob/fb18a6493a0f5935176b85611081374503e1b825/connector/src/main/java/org/geysermc/connector/GeyserConnector.java#L324

**Comment by Legit4K** [comment] 2021-04-15 20:27
Can anyone try reproducing this or am I going insane 😂

**Comment by ExusiaiMoe** [comment] 2021-04-18 03:25
try this geyser, I added a stacktrace on error, post the log here if you can reproduce it with this jar
[Geyser-Spigot.zip](https://github.com/GeyserMC/Geyser/files/6330442/Geyser-Spigot.zip)

**Comment by Squeej** [comment] 2021-04-20 12:19
I've been having the same exact problem ever since I installed geyser/floodgate on my bungee network. The servers will work great for a while but after about 24-48 hours cpu usage goes through the roof and the servers inevitably crash. I just removed geyser/floodgate this morning to test and confirm that this is what's happening. I'll post here if memory stops leaking as a result

**Comment by DevCarnage** [comment] 2021-04-25 04:41
@Legit4K May i ask what JVM  arguments you use? How much RAM do you have in total and how much of it is used by the SERVER
  i had an issue where the server would "crash" and be in a deadlock ever since i updated to the 1.16.220 update. Then was given this error occasionally when the deadlock happen (note the deadlock happen like 10-15 hours of restarting which was similar to this)

> Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached
which was fixed by having some "RAM" that wasnt being used by minecraft cuz apparently geyser tries to use RAM outside MC which caused the crash. IDK if that will fix the issue (sorry if this wasted your time).

**Comment by Legit4K** [comment] 2021-04-25 11:52
@DevCarnage sure,
I use the following JVM Arguments which follows aikar's optimization guide
```
java -Xmx12G -Xms12G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar paper.jar
```
I have 128G RAM in total and 12G is dedicated to the server as shown in the JVM arguments and I should note that this has been happening for months now but recently it had became more frequent.

I've already setup a work-around to prevent it from happening but it'd be ideal if we can all find the source cause of this issue because it may prevent larger networks from using Geyser for longer periods of time.

**Comment by DevCarnage** [comment] 2021-04-26 03:02
hmm alright Well i recommend trying out the stacktrace jar that Moe gave and try to replicate the issue. It could also be something to do with your plugins if this issue has been occurring for a while, maybe remove the useless one and see if any plugins are causing the issue.

**Comment by Camotoy** [comment] 2021-04-26 04:00
I would not recommend downloading random jarfiles from untrusted sources. That being said, feel free to publish the source of the jar and I can help guide through testing that.

**Comment by ExusiaiMoe** [comment] 2021-04-26 11:18
> I would not recommend downloading random jarfiles from untrusted sources. That being said, feel free to publish the source of the jar and I can help guide through testing that.

I just changed the throw quiet exception part so that it print out stacktrace, just
`System.out.println(e)`
If you don't trust it just build it yourself :-)😀

**Comment by DevCarnage** [comment] 2021-04-26 16:06
> I would not recommend downloading random jarfiles from untrusted sources. That being said, feel free to publish the source of the jar and I can help guide through testing that.

A bad move on my fault ^^ in all fairness i'd usually run a virus scan, open it up in JD-GUI/ and compare it to the current version of the plugin before even using it which i have done.  From what i seen the plugin given above is a bit outdated  but actually does what is promised. If you want to be safe you could compile it yourself with the code edited.

**Comment by Legit4K** [comment] 2021-05-09 17:34
I would love to test it but I don't want to put my production server through that because it would cause rollbacks since the dead lock would prevent server from closing which means it wouldn't save world data. I did initially have a test server but after the hardware upgrade, I no longer have it tho I'll probably set another one up in the future.

Anyways, if anyone wants to help test this issue then just follow my basic setup of a Paper 1.16 Server and Geyser Spigot (No Proxy setup & latest builds of Paper + Geyser), the issue happens when there's a bedrock player online during server shutdown. For the purpose of testing, I recommend that there be a _a few_ bedrock players online, not just one. You should watch the console log when you initiate a shutdown via `/stop` or `/geyser shutdown`

**Comment by RednedEpic** [comment] 2021-07-22 03:45
Is this still an issue? Some people reporting that Geyser has deadlocked for them in the past mentioned it is no longer a problem, and some have been able to scale up to 500+ players without (to our knowledge) any sudden crash or deadlock.

**Comment by Legit4K** [comment] 2021-07-24 15:30
The inconsistency between the results makes it hard to track the origin of the issue, I haven't experienced it for a while now but that may be because of my temporary workaround where I make sure the auto restart system kicks every player before stopping the server.

**Comment by DevCarnage** [comment] 2021-07-24 20:46
Haven't had any issues when this first happened

**Comment by Firav** [comment] 2021-07-28 23:46
I've been starting to encounter this issue also. Seems to happen when theres only 1 bedrock player connected to the proxy. I'll start keeping a closer eye on this and recording my findings here.

**Comment by Firav** [comment] 2021-08-01 06:16
Little update on this. Seems to only happen when I use the Minecraft `stop` command. If I shut down the plugin beforehand via its own commands, it doesnt create the deadlock.

**Closed** 2022-04-21 18:44 UTC
Labels: Unconfirmed Bug/Not Currently Replicable, Waiting On Response
