### ISSUE TITLE
Trapdoors hitbox is not the same as rendered when use event is cancelled

### ISSUE THREAD

**Issue by BlueBurgersTDD** [GeyserMC/Geyser#857] opened 2020-06-29 16:47 UTC
**Describe the bug**
The rendered position is different from the hitbox when the event is cancelled

**To Reproduce**
1. Get World Guard
2. Set up a region where you can't use trapdoors
3. Try to use it

**Expected behavior**
The hitbox should be the same as rendered

**Screenshots / Videos**
https://medal.tv/clips/27482076/d1337iPOaEQJ

**Server Version**
Paper version git-Paper-350 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Geyser Version**
Latest Velocity version, 1.16 branch

**Minecraft: Bedrock Edition Version**
1.16.0

**Additional Context**
Running WorldGuard 7.0.2

**Comment by endevrr** [comment] 2020-06-29 20:08
This is not a worldguard issue but an issue with non full blocks updating, I will make an issue so we can close all these issues

**Comment by endevrr** [comment] 2020-06-29 20:16
Duplicate of #865

**Closed** 2020-06-29 20:16 UTC
