### ISSUE TITLE
Geyser - Bungeecord (Extention) Motd bug

### ISSUE THREAD

**Issue by LemonCraft-11** [GeyserMC/Geyser#3201] opened 2022-08-03 22:24 UTC
### Describe the bug

i change motd in config.yml but motd in minecraft don't change

### To Reproduce

1.Goto ' Change motd'
2.See 'Error'

### Expected behaviour

Fix it

### Screenshots / Videos

https://cdn.discordapp.com/attachments/613168464634576897/1004513739611054150/unknown.png

### Server Version and Plugins

PurpurMC ( 1.19.10 )

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-local/dev-684b9c2)

### Minecraft: Bedrock Edition Device/Version

1.19.10

**Comment by Camotoy** [comment] 2022-08-03 22:33
Please provide a Geyser dump.

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by DJelly4K** [comment] 2022-08-05 06:18
> Please provide a Geyser dump.
> 
> Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

this problem is also on other platforms

**Comment by Legendans** [comment] 2022-08-12 03:12
> Hello, I also have this problem
geyser is Branch feature/extensions
run /geyser dump But there was an error

[11:03:06 INFO]: Winspuer976 issued server command: /geyser dump
[11:03:06 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'geyser' in plugin Geyser-Spigot v2.1.0-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2262) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2073) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2054) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1286) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: inStream parameter is null
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at java.util.Properties.load(Properties.java:407) ~[?:?]
        at org.geysermc.geyser.dump.DumpInfo.<init>(DumpInfo.java:94) ~[Geyser-Spigot (1).jar:?]
        at org.geysermc.geyser.command.defaults.DumpCommand.execute(DumpCommand.java:93) ~[Geyser-Spigot (1).jar:?]
        at org.geysermc.geyser.platform.spigot.command.GeyserSpigotCommandExecutor.onCommand(GeyserSpigotCommandExecutor.java:67) ~[Geyser-Spigot (1).jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-411]
        ... 21 more

**Comment by Legendans** [comment] 2022-08-12 03:15
> Please provide a Geyser dump.
> 
> Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

Hello, I also have this problem
Server Version and Plugins
Paper 1.17 geyser is Branch feature/extensions
run /geyser dump But there was an error

[11:03:06 INFO]: Winspuer976 issued server command: /geyser dump
[11:03:06 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'geyser' in plugin Geyser-Spigot v2.1.0-SNAPSHOT
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Paper-411]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-411]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Paper-411]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2262) ~[app:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2073) ~[app:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2054) ~[app:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[app:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-411]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-411]
at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-411]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-411]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-411]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[patched_1.17.1.jar:git-Paper-411]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1286) ~[patched_1.17.1.jar:git-Paper-411]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: inStream parameter is null
at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
at java.util.Properties.load(Properties.java:407) ~[?:?]
at org.geysermc.geyser.dump.DumpInfo.(DumpInfo.java:94) ~[Geyser-Spigot (1).jar:?]
at org.geysermc.geyser.command.defaults.DumpCommand.execute(DumpCommand.java:93) ~[Geyser-Spigot (1).jar:?]
at org.geysermc.geyser.platform.spigot.command.GeyserSpigotCommandExecutor.onCommand(GeyserSpigotCommandExecutor.java:67) ~[Geyser-Spigot (1).jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-411]
... 21 more

**Comment by Konicai** [comment] 2022-08-12 03:16
Join our Discord if you have issues preparing a dump

And please don't paste large errors into github comments, especially twice

**Comment by Legendans** [comment] 2022-08-12 03:18
> Join our Discord if you have issues preparing a dump
> 
> And please don't paste large errors into github comments, especially twice

I'm sorry, I don't know the rules too well, I'll give you trouble

**Comment by Camotoy** [comment] 2022-08-29 00:42
This should be fixed in the next commit.

**Closed by Camotoy** 2022-08-29 00:42 UTC
Labels: Waiting On Response
