### ISSUE TITLE
The bungeecord plugin of geyser is consuming so MUCH RAM

### ISSUE THREAD

**Issue by JavyMC123** [GeyserMC/Geyser#790] opened 2020-06-19 23:14 UTC
**Describe the bug**
The bungeecord dont past the 24 hours on because the ram. I have the same bungee with less ram and the same plugins (2GB) and have 34 days online without issues. THe other bungee with geyser and floodgate, use 5GB and dont past 24 hours ON. What is happening?

**Server Version**
Waterfall latest version

**Geyser Version**
Geyser latest version
Floodgate latest version

**Minecraft: Bedrock Edition Version**
Latest version

**Comment by Heath123** [comment] 2020-06-19 23:16
This is probably a memory leak. Are you on the Discord server?

**Comment by JavyMC123** [comment] 2020-06-19 23:17
No, what is the discord? Pls

**Comment by rtm516** [comment] 2020-06-19 23:18
http://discord.geysermc.org/

**Comment by rtm516** [comment] 2020-06-19 23:20
Closing this in favour of https://github.com/GeyserMC/Geyser/issues/592

**Closed by rtm516** 2020-06-19 23:20 UTC

**Comment by AnonAlpha** [comment] 2020-06-20 03:30
This isn't caused by Geyser, I have no problem using Geyser on Bungeecord

**Comment by DoctorMacc** [comment] 2020-06-20 03:31
Do you use ping passthrough?

**Comment by AnonAlpha** [comment] 2020-06-20 07:44
> Do you use ping passthrough?

I do
