### ISSUE TITLE
Could not translate packet ClientboundContainerSetContentPacket

### ISSUE THREAD

**Issue by LucidAPs** [GeyserMC/Geyser#3197] opened 2022-08-02 13:59 UTC
### Describe the bug

Console error https://nekobin.com/gugacaqixu

### To Reproduce

No idea.

### Expected behaviour

No error?

### Server Version and Plugins

waterfall-1.19-500

### Geyser Version

[#1162 (Aug 1, 2022, 7:45:19 PM)](https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/1162/changes)

**Comment by Jens-Co** [comment] 2022-08-02 14:11
Duplicate of https://github.com/GeyserMC/Geyser/issues/3115

**Closed by Jens-Co** 2022-08-02 14:11 UTC
