### ISSUE TITLE
Unable To Craft

### ISSUE THREAD

**Issue by BlackKnight683** [GeyserMC/Geyser#1407] opened 2020-10-15 05:02 UTC
**Describe the bug**
 Unable to craft any itme in any sort of inventory

**To Reproduce**

 go to the server, and try to craft any sort of item either in the crafting bench OR in the player crafting slota

**Expected behavior**
 Able to craft that item

**Screenshots / Videos**

![Screenshot_2020-10-15-10-16-49-173_com mojang minecraftpe](https://user-images.githubusercontent.com/69863661/96079043-6fb4b680-0ed1-11eb-8ad2-c36cc311f85d.jpg)
![Screenshot_2020-10-15-10-16-33-854_com mojang minecraftpe](https://user-images.githubusercontent.com/69863661/96079045-72171080-0ed1-11eb-8db2-10f06e8fefcb.jpg)1.8.8
![Screenshot_2020-10-15-10-16-04-816_com mojang minecraftpe](https://user-images.githubusercontent.com/69863661/96079048-72afa700-0ed1-11eb-94fc-c3070efad092.jpg)

**Server Version**
 1.8.8

**Geyser Version**
 v1.1.0 latest build of 15 october [Geyser-Spigot]

**Minecraft: Bedrock Edition Version**
 1.16.2/1.16.3

**Additional Context**
 
https://dump.geysermc.org/m8GikdWxQ89BqViCkRW2TjXPk9dtEVsu

**Comment by RednedEpic** [comment] 2020-10-15 05:02
Again, duplicate of #511. Please do not open up a new issue as there is already one open for this.

**Closed by RednedEpic** 2020-10-15 05:02 UTC
