### ISSUE TITLE
Groups of Bedrock Players get disconnected

### ISSUE THREAD

**Issue by mrunningmasterc** [GeyserMC/Geyser#4116] opened 2023-09-10 20:34 UTC
### Describe the bug

Groups of bedrock players will get disconnected quite often. Bedrock players often lose connection quite a bit.

### To Reproduce

Join server on bedrock
Play for a little bit 
Randomly disconnects player or groups of players

### Expected behaviour

When joining on bedrock you will get disconnected with a bunch of other players on bedrock.

### Screenshots / Videos

<img width="378" alt="Screenshot 2023-09-10 at 4 30 31 PM" src="https://github.com/GeyserMC/Geyser/assets/63335629/3cb0a174-a6fe-4eda-a3e7-1186b4356414">

### Server Version and Plugins

FlameCord 1.6.4 by LinsaFTW & Sammwy

### Geyser Dump

https://dump.geysermc.org/VzgVFG19KtWfzVoa3hgzhRhfJv0vyDZh

### Geyser Version

 Geyser version 2.2.0-SNAPSHOT (git-master-c67d50c)

### Minecraft: Bedrock Edition Device/Version

1.20.15

**Comment by mrunningmasterc** [comment] 2023-09-10 20:35
<img width="297" alt="Screenshot 2023-09-10 at 4 34 44 PM" src="https://github.com/GeyserMC/Geyser/assets/63335629/baaa56c7-ab3d-42c3-aa43-56051b998843">


here's a photo of a singular bedrock player.

This never happens with any of my java players.

**Comment by mrunningmasterc** [comment] 2023-09-13 23:46
<img width="489" alt="Screenshot 2023-09-13 at 7 46 10 PM" src="https://github.com/GeyserMC/Geyser/assets/63335629/025a81c9-fd7b-44f1-9f3f-671e37f0c077">
some more occurrences

**Comment by rtm516** [comment] 2023-09-14 07:51
Please provide a full server/proxy log file

**Comment by mrunningmasterc** [comment] 2023-09-17 01:31
[2023-09-16-1.log](https://github.com/GeyserMC/Geyser/files/12641847/2023-09-16-1.log)
[latest.log](https://github.com/GeyserMC/Geyser/files/12641848/latest.log)


Here's some log files from flamecord on which it happens.

**Comment by mrunningmasterc** [comment] 2023-09-17 01:44
[latest.log](https://github.com/GeyserMC/Geyser/files/12641859/latest.log)

Here's another one where a group of bedrock users disconnect

**Comment by Jens-Co** [comment] 2023-09-17 07:23
Can you please try with Waterfall instead of flamecord? It's quite possible that flamecord itself is causing this issue.

**Comment by mrunningmasterc** [comment] 2023-09-17 15:45
Waterfall is closing up shop. They are going remove it soon. Any other proxy suggestions, besides velocity, that work best with geyser? Bungeecord is to unsecure to use.

**Comment by muazhari** [comment] 2023-09-17 22:35
same here, my bedrock players often got disconnected with high ping/lagging in before.

**Comment by mrunningmasterc** [comment] 2023-09-19 02:07
I’ve tested it on bungeecord, still getting a bunch of group disconnects. Trying out velocity now and it seems to have the same issue.

**Comment by PedroMPagani** [comment] 2023-09-19 14:14
@mrunningmasterc what's your frequency in which you're getting this, is this very often?

**Comment by mrunningmasterc** [comment] 2023-09-19 14:16
> @mrunningmasterc what's your frequency in which you're getting this, is this very often?

Its been pretty frequent

**Comment by PedroMPagani** [comment] 2023-09-19 14:21
That disconnect happens out of nowhere?

**Comment by PedroMPagani** [comment] 2023-09-19 14:23
One question, does it let them join back, or do you need to restart it all the time?
1. Are you running standalone?

**Comment by mrunningmasterc** [comment] 2023-09-19 14:23
yea I have no idea why. I made sure every setting in geyser and proxy was correct. I tried multiple proxies and they all do the same thing. It lets them join back, just after a bit they get timed out

> That disconnect happens out of nowhere?

**Comment by PedroMPagani** [comment] 2023-09-19 14:28
I'd like to add a few debugs, are you able to run this custom jar so we can see why? I am from DonutSMP.net, we are also experiencing this but in our side it completely doesn't let people to connect back again

**Comment by mrunningmasterc** [comment] 2023-09-19 14:32
> I'd like to add a few debugs, are you able to run this custom jar so we can see why? I am from DonutSMP.net, we are also experiencing this but in our side it completely doesn't let people to connect back again

Yea I can, I'm currently running velocity so it would need to support that.

**Comment by mrunningmasterc** [comment] 2023-09-19 14:32
I wonder if its a mojang thing

**Comment by PedroMPagani** [comment] 2023-09-19 14:35
Standalone supports velocity by default, i don't think its a mojang thing, because I experienced 400 player drop all at once and then no one able to connect, this is not a DDOS though, geyser was fine just on a state where it wouldnt accept more connections, same issue as yours, the diff is yours is accepting after some time, I havent really tried to let it online when this happened, auto kill and restart, I'll modify a jar with a lot of debugs and i'll send

**Comment by mrunningmasterc** [comment] 2023-09-19 14:38
> Standalone supports velocity by default, i don't think its a mojang thing, because I experienced 400 player drop all at once and then no one able to connect, this is not a DDOS though, geyser was fine just on a state where it wouldnt accept more connections, same issue as yours, the diff is yours is accepting after some time, I havent really tried to let it online when this happened, auto kill and restart, I'll modify a jar with a lot of debugs and i'll send

I don't use the stand alone version. I use the velocity version they put out for the proxy. None of my paper servers run geyser plugin just the proxy runs the geyser jar

**Comment by mrunningmasterc** [comment] 2023-09-24 21:58
Alright I switched to Standalone then everything was doing great and fine everyone lasted for a while and then BAM. Everyone gets disconnected and no one is able to join again and I had to restart it.

> Standalone supports velocity by default, i don't think its a mojang thing, because I experienced 400 player drop all at once and then no one able to connect, this is not a DDOS though, geyser was fine just on a state where it wouldnt accept more connections, same issue as yours, the diff is yours is accepting after some time, I havent really tried to let it online when this happened, auto kill and restart, I'll modify a jar with a lot of debugs and i'll send

**Comment by PedroMPagani** [comment] 2023-09-24 23:05
@mrunningmasterc share your startup flags, your docker memory allocated to it, what port you're running it on, and also a geyser dump for it, this is the same behavior so..

**Comment by mrunningmasterc** [comment] 2023-09-24 23:35
@PedroMPagani 

I’ll send it here soon but it’s weird cause I started using it Friday night and it was fine Saturday all day then around 6pm Sunday (Today) it randomly starts doing that where it disconnects everyone and they are unable to join and have to restart.

**Comment by mrunningmasterc** [comment] 2023-09-25 01:56
@PedroMPagani 

Also, memory was at 50% when the disconnects happened so there was plenty of memory. Cause of that wouldn't have been memory 

Port is 19132 and gets connected to a flamecord proxy. I have the floodgate key from the proxy also in the standalone geyser server

Kept the startup flags simple

<img width="642" alt="Screenshot 2023-09-24 at 9 54 15 PM" src="https://github.com/GeyserMC/Geyser/assets/63335629/405f30c2-ec84-4322-94de-03f95fc2039e">


https://dump.geysermc.org/PvZLxBs6rMUASI9UQT9d9S6VYWsewBog

**Comment by linsaftw** [comment] 2023-09-25 22:50
Can someone confirm if this is an issue related to FlameCord or just a general proxy issue?

**Comment by PedroMPagani** [comment] 2023-09-25 23:58
I got this with velocity.

**Comment by Minionguyjpro** [comment] 2023-11-19 15:30
> Can someone confirm if this is an issue related to FlameCord or just a general proxy issue?

Same issue has been reproduced for me on a regular Purpur server. It used to work fine at first and now it lets bedrock players join but they just get kicked after like 30 seconds in of the server.

**Comment by onebeastchris** [comment] 2023-12-07 07:51
https://github.com/GeyserMC/Geyser/pull/4329
Does the build from this PR improve connection stability/resolve the player kicking issue?

**Comment by onebeastchris** [comment] 2024-02-02 15:29
Should be resolved by https://github.com/GeyserMC/Geyser/commit/226a4bb15118b00eb15832b1d3ffa1a970d8c7df.
The amount of listen threads can be increased further if need be using the `-DGeyser.ListenCount` system property - by default, the listen thread count is set to two (previously, one). For servers with a lot of Bedrock players playing via Geyser, this can be increased manually

**Closed by onebeastchris** 2024-02-02 15:29 UTC
Labels: Unconfirmed Bug/Not Currently Replicable
