### ISSUE TITLE
Bedrock players not always able to see Java players

### ISSUE THREAD

**Issue by Phr3d13** [GeyserMC/Geyser#1468] opened 2020-10-29 02:28 UTC
**Describe the bug**
Bedrock players become "out of sync" with Java players and need to re-log to be able to see Java players.

**To Reproduce**
1. Setup Geyser (Spigot plugin version)
2. Connect Java and Bedrock players
3. Wait {duration} time
4. Java players become invisible to Bedrock players

**Expected behavior**
Players of both platforms to always be able to see each other

**Screenshots / Videos**

**Server Version**
This server is running CraftBukkit version git-Spigot-57bbdd8-dea4138 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Geyser Version**
This server is running Geyser version 1.1.0 (git-master-62d984d) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.20)

**Minecraft: Bedrock Edition Version**
1.16.40

**Additional Context**
https://dump.geysermc.org/viBMgXPNMP91CyGUOfxiCA1lbgDjxVe8

**Comment by Kooldude183** [comment] 2020-10-29 21:01
I notice this happen when/after they ride in Minecarts

**Comment by Phr3d13** [comment] 2020-10-29 21:08
Ok, I think we're on to something... We're on a very watery map. We use boats a lot. Might be linked to riding in/on things.

**Comment by strubbe06** [comment] 2020-10-29 22:18
This happens to me sometimes when a player is out of my render distance and is teleported to me, or sometimes when they respawn they become invisible.

**Comment by DoctorMacc** [comment] 2020-10-30 02:42
@Kooldude183 @strubbe06 can I get Geyser dumps from both of you?

I played around with SkinsRestorer and Paper/Spigot 1.16.3 with no issues. Tried entering/exiting a minecart, teleporting, and riding into the chunk with a minecart.

**Comment by Kooldude183** [comment] 2020-10-30 03:19
> @Kooldude183 @strubbe06 can I get Geyser dumps from both of you?
> 
> I played around with SkinsRestorer and Paper/Spigot 1.16.3 with no issues. Tried entering/exiting a minecart, teleporting, and riding into the chunk with a minecart.

https://dump.geysermc.org/NBRW0RZvpCsCrotKlbOKpI90bYx3eTNg

**Comment by DoctorMacc** [comment] 2020-10-30 03:21
Can I get a list of the plugins on the server, and `/version`'s output? (if you have access) The plugin dump takes care of that usually.

**Comment by Kooldude183** [comment] 2020-10-30 03:23
> Can I get a list of the plugins on the server, and `/version`'s output? (if you have access) The plugin dump takes care of that usually.

Plugins (49): ActionHealth*, AdvancedBan*, AntiVPN, AutoBroadcast, AutomaticInventory, BedrockPlayerManager, ChestSort, CommandAliases, ConsoleSpamFix, CoreProtect, DiscordSRV, DynamicShop, dynmap*, Essentials, EssentialsChat, EternalLight, floodgate-bukkit, Graves, GriefPrevention, HolographicDisplays, JDynmapGriefPrevention*, LuckPerms, Md5Lukas-Commons, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, NametagEdit*, Plan, ProtocolLib, PunishGUI*, QuickShop, ServerListPlus*, SignBoard, SilkSpawners, SkinsRestorer, spark, SpigotPing, TabuuCore, TradeSystem, UltimateAutoRestart, UltimateTimber, Vault, ViaVersion, ViewDistanceTweaks, Waypoints, Wild, WitherAC, WorldBorder, XP-Transfer*

This server is running Tuinity version git-Tuinity-"5df4a4f" (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Comment by strubbe06** [comment] 2020-10-30 03:55
> @Kooldude183 @strubbe06 can I get Geyser dumps from both of you?
> 
> I played around with SkinsRestorer and Paper/Spigot 1.16.3 with no issues. Tried entering/exiting a minecart, teleporting, and riding into the chunk with a minecart.

https://dump.geysermc.org/u0RDlrvMSJ9FS60PdFUVjR9lR07AmM5A

**Comment by DoctorMacc** [comment] 2020-10-30 04:00
The main linking point between you all is Paper and SkinsRestorer and Floodgate - I'll try again with Floodgate tomorrow.

**Comment by Phr3d13** [comment] 2020-10-30 09:17
But I'm not on paper, I'm on spigot...

**Comment by DoctorMacc** [comment] 2020-10-30 14:37
I tested on Spigot as well.

**Comment by Phr3d13** [comment] 2020-10-31 00:11
Also, I'm not using floodgate.

**Comment by Phr3d13** [comment] 2020-10-31 00:12
Also found this when testing and trying to force the issue:
[20:07:30] [Thread-67/WARN]: [Geyser-Spigot] Could not translate packet ServerSpawnPlayerPacket
java.lang.NullPointerException: null
        at org.geysermc.connector.entity.PlayerEntity.spawnEntity(PlayerEntity.java:110) ~[Geyser-Spigot.jar:?]
        at org.geysermc.connector.entity.PlayerEntity.sendPlayer(PlayerEntity.java:127) ~[Geyser-Spigot.jar:?]
        at org.geysermc.connector.network.translators.java.entity.spawn.JavaSpawnPlayerTranslator.translate(JavaSpawnPlayerTranslator.java:58) ~[Geyser-Spigot.jar:?]
        at org.geysermc.connector.network.translators.java.entity.spawn.JavaSpawnPlayerTranslator.translate(JavaSpawnPlayerTranslator.java:38) ~[Geyser-Spigot.jar:?]
        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:93) [Geyser-Spigot.jar:?]
        at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:514) [Geyser-Spigot.jar:?]
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) [Geyser-Spigot.jar:?]
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) [Geyser-Spigot.jar:?]
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) [Geyser-Spigot.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
[20:07:30] [Thread-67/WARN]: java.lang.NullPointerException
[20:07:30] [Thread-67/WARN]:    at org.geysermc.connector.entity.PlayerEntity.spawnEntity(PlayerEntity.java:110)
[20:07:30] [Thread-67/WARN]:    at org.geysermc.connector.entity.PlayerEntity.sendPlayer(PlayerEntity.java:127)
[20:07:30] [Thread-67/WARN]:    at org.geysermc.connector.network.translators.java.entity.spawn.JavaSpawnPlayerTranslator.translate(JavaSpawnPlayerTranslator.java:58)
[20:07:30] [Thread-67/WARN]:    at org.geysermc.connector.network.translators.java.entity.spawn.JavaSpawnPlayerTranslator.translate(JavaSpawnPlayerTranslator.java:38)
[20:07:30] [Thread-67/WARN]:    at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:93)
[20:07:30] [Thread-67/WARN]:    at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:514)
[20:07:30] [Thread-67/WARN]:    at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
[20:07:30] [Thread-67/WARN]:    at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
[20:07:30] [Thread-67/WARN]:    at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324)
[20:07:30] [Thread-67/WARN]:    at java.lang.Thread.run(Unknown Source)

**Comment by DoctorMacc** [comment] 2020-10-31 00:15
That error links your problem to boats for sure then. If you figure out a concrete way to replicate it, please inform me!!!

**Comment by Phr3d13** [comment] 2020-10-31 00:45
I'm trying to force it to happen with boats, getting in a boat, going long distances, hopping out, switching boats, going back to the bedrock player, and the bedrock player can still see the java player... and no errors in the log... But if a java player dies, I get an error similar to the one posted above, and the bedrock player can no longer see the java player.

**Comment by DoctorMacc** [comment] 2020-10-31 00:46
Is the Java player in render distance or no?

**Comment by Phr3d13** [comment] 2020-10-31 00:46
I don't know if it's specifically tied to player death, but player death is one way to force it to trigger the issue

**Comment by Phr3d13** [comment] 2020-10-31 00:47
Yes, no more than 20 blocks away, pretty much line of sight.

**Comment by Phr3d13** [comment] 2020-10-31 00:48
I don't know if it was exactly within view though, because I can only see/control one client at a time.

**Comment by DoctorMacc** [comment] 2020-10-31 00:48
I can work with that.

**Comment by DoctorMacc** [comment] 2020-10-31 00:56
Still unable to replicate. :/

**Comment by DoctorMacc** [comment] 2020-10-31 00:56
Might have to do with AuthMe? I absolutely don't condone piracy, but a bug is a bug that could surface elsewhere.

**Comment by Phr3d13** [comment] 2020-10-31 00:57
Hmmmmm... I tried to do the same thing again now, to show a friend, and it didn't error out. I'm going through the exact steps I went through last time I got the error message... It might have to do with one of the players having been outside render distance at some point, but maybe not currently.

**Comment by Phr3d13** [comment] 2020-10-31 01:03
Yes, I was able to make force error conditions... Both players could see each other... I moved the Java player 700 blocks west, I drowned the java player, and respawned him, the error happened in the console, and the bedrock player can no longer see the java player (until bedrock player re-log). If you want, I can remove authme to see if the error still happens

**Comment by DoctorMacc** [comment] 2020-10-31 01:04
Did you teleport the player 700 blocks or was that through flying/moving?

**Comment by Phr3d13** [comment] 2020-10-31 01:05
I rowed him in a boat

**Comment by DoctorMacc** [comment] 2020-10-31 01:05
Will try tonight.

**Comment by DoctorMacc** [comment] 2020-10-31 04:18
@Phr3d13 no luck. :/ Rowed out, drowned myself, and I still show up. I'm still testing on standalone, though, so tomorrow I will try with Geyser-Spigot.

**Comment by soshimee** [comment] 2020-10-31 11:35
Happens for me on teleports on long distances.

**Comment by Jacky10X** [comment] 2020-10-31 13:00
It also happens to me. It seems there is a chance to happen when the player dead and respawns. But I don't know is it related to distance or not.

**Comment by DoctorMacc** [comment] 2020-10-31 18:55
I'm unable to confirm even with Geyser-Spigot. There must be something else going on. @Jacky10X @soshimee can you guys provide Geyser dumps? Have you modified spigot.yml/paper.yml etc.?

**Comment by DoctorMacc** [comment] 2020-10-31 18:55
Also for anyone affected: please try removing SkinsRestorer temporarily and see if the issue is resolved.

**Comment by kingflashroseG** [comment] 2020-10-31 20:30
Can Confirm that even with skin restorer removed it still happens for me its whenever the players use any mode of transport in the game such as minecarts and horses (Probably should have commented on this post a lot sooner)

**Comment by DoctorMacc** [comment] 2020-10-31 23:46
@kingflashroseG can you provide a Geyser dump and elaborate on how to possibly replicate this?

**Comment by soshimee** [comment] 2020-11-01 06:46
I have modified spigot.yml but none related to it.
[Here is the dump.](https://dump.geysermc.org/gjtxWJT2VJA6pinz8aGQP0hK5z7JXmvL)

**Comment by soshimee** [comment] 2020-11-01 06:48
It happens for me on long distance teleports and world moves.
But the bedrock player can see the name tags for some reason.

**Comment by Phr3d13** [comment] 2020-11-01 20:21
Hopped Java player into a boat, rowed far away, teleported back to Bedrock player.
[15:20:23] [Server thread/INFO]: Plugins (5): dynmap, Geyser-Spigot, SinglePlayerSleep, DiscordSRV, GriefPrevention

https://dump.geysermc.org/TSTObDPn7K6POxblhkJBEW6DyydVwDrR

[15:18:27] [Server thread/INFO]: [phr3dx13: Teleported phr3dx13 to Phr3d13]
[15:18:28] [Thread-38/WARN]: [Geyser-Spigot] Could not translate packet ServerSpawnPlayerPacket
java.lang.NullPointerException: null
        at org.geysermc.connector.entity.PlayerEntity.spawnEntity(PlayerEntity.java:110) ~[Geyser-Spigot%20(1).jar:?]
        at org.geysermc.connector.entity.PlayerEntity.sendPlayer(PlayerEntity.java:127) ~[Geyser-Spigot%20(1).jar:?]
        at org.geysermc.connector.network.translators.java.entity.spawn.JavaSpawnPlayerTranslator.translate(JavaSpawnPlayerTranslator.java:58) ~[Geyser-Spigot%20(1).jar:?]
        at org.geysermc.connector.network.translators.java.entity.spawn.JavaSpawnPlayerTranslator.translate(JavaSpawnPlayerTranslator.java:38) ~[Geyser-Spigot%20(1).jar:?]
        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:93) [Geyser-Spigot%20(1).jar:?]
        at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:514) [Geyser-Spigot%20(1).jar:?]
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) [Geyser-Spigot%20(1).jar:?]
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) [Geyser-Spigot%20(1).jar:?]
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) [Geyser-Spigot%20(1).jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
[15:18:28] [Thread-38/WARN]: java.lang.NullPointerException
[15:18:28] [Thread-38/WARN]:    at org.geysermc.connector.entity.PlayerEntity.spawnEntity(PlayerEntity.java:110)
[15:18:28] [Thread-38/WARN]:    at org.geysermc.connector.entity.PlayerEntity.sendPlayer(PlayerEntity.java:127)
[15:18:28] [Thread-38/WARN]:    at org.geysermc.connector.network.translators.java.entity.spawn.JavaSpawnPlayerTranslator.translate(JavaSpawnPlayerTranslator.java:58)
[15:18:28] [Thread-38/WARN]:    at org.geysermc.connector.network.translators.java.entity.spawn.JavaSpawnPlayerTranslator.translate(JavaSpawnPlayerTranslator.java:38)
[15:18:28] [Thread-38/WARN]:    at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:93)
[15:18:28] [Thread-38/WARN]:    at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:514)
[15:18:28] [Thread-38/WARN]:    at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
[15:18:28] [Thread-38/WARN]:    at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
[15:18:28] [Thread-38/WARN]:    at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324)
[15:18:28] [Thread-38/WARN]:    at java.lang.Thread.run(Unknown Source)

**Comment by DoctorMacc** [comment] 2020-11-02 04:06
I rowed myself (as a Java player) 800 blocks, got out, collected the boat, and then teleported myself back to the Java player. No issues.

**Comment by soshimee** [comment] 2020-11-02 06:10
Don't know, maybe ping issue or something? I use hosting.

**Comment by Phr3d13** [comment] 2020-11-02 06:12
Mine's not a ping issue... I'm testing locally. Either same machine, or a machine in my local network.

**Comment by Phr3d13** [comment] 2020-11-02 06:12
> I rowed myself (as a Java player) 800 blocks, got out, collected the boat, and then teleported myself back to the Java player. No issues.

Are you still testing standalone, or testing with spigot?

**Comment by RednedEpic** [comment] 2020-12-12 08:17
Is this still an issue?

**Comment by Phr3d13** [comment] 2020-12-12 11:32
The method I used to use to trigger this issue no longer trigger the same errors/problems. So, it may have been fixed.

**Comment by soshimee** [comment] 2020-12-12 12:08
I don't see it anymore also, but might be just because I don't test on
Bedrock much now.

>

**Comment by Mike-Parker** [comment] 2021-01-25 17:18
My daughter still believes this to be an issue (Bedrock players not being able to see Java players). I believe the Bedrock player becomes unable to see a Java player when a third Java player dies.

The following is from a server session today:

[16:33:59] [Thread-2926/WARN]: [Geyser-Spigot] Could not translate packet ServerSpawnPlayerPacket
java.lang.NullPointerException: null
        at org.geysermc.connector.entity.player.PlayerEntity.spawnEntity(PlayerEntity.java:106) ~[Geyser-Spigot.jar:?]
        at org.geysermc.connector.entity.player.PlayerEntity.sendPlayer(PlayerEntity.java:123) ~[Geyser-Spigot.jar:?]
        at org.geysermc.connector.network.translators.java.entity.spawn.JavaSpawnPlayerTranslator.translate(JavaSpawnPlayerTranslator.java:64) ~[Geyser-Spigot.jar:?]
        at org.geysermc.connector.network.translators.java.entity.spawn.JavaSpawnPlayerTranslator.translate(JavaSpawnPlayerTranslator.java:38) ~[Geyser-Spigot.jar:?]
        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:93) [Geyser-Spigot.jar:?]
        at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:564) [Geyser-Spigot.jar:?]
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) [Geyser-Spigot.jar:?]
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) [Geyser-Spigot.jar:?]
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) [Geyser-Spigot.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
[16:33:59] [Thread-2926/WARN]: java.lang.NullPointerException
[16:33:59] [Thread-2926/WARN]:  at org.geysermc.connector.entity.player.PlayerEntity.spawnEntity(PlayerEntity.java:106)
[16:33:59] [Thread-2926/WARN]:  at org.geysermc.connector.entity.player.PlayerEntity.sendPlayer(PlayerEntity.java:123)
[16:33:59] [Thread-2926/WARN]:  at org.geysermc.connector.network.translators.java.entity.spawn.JavaSpawnPlayerTranslator.translate(JavaSpawnPlayerTranslator.java:64)
[16:33:59] [Thread-2926/WARN]:  at org.geysermc.connector.network.translators.java.entity.spawn.JavaSpawnPlayerTranslator.translate(JavaSpawnPlayerTranslator.java:38)
[16:33:59] [Thread-2926/WARN]:  at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:93)
[16:33:59] [Thread-2926/WARN]:  at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:564)
[16:33:59] [Thread-2926/WARN]:  at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
[16:33:59] [Thread-2926/WARN]:  at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
[16:33:59] [Thread-2926/WARN]:  at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324)
[16:33:59] [Thread-2926/WARN]:  at java.lang.Thread.run(Thread.java:748)

**Comment by Camotoy** [comment] 2021-01-25 17:20
@Mike-Parker please try https://github.com/GeyserMC/Geyser/pull/1706 and see if the issue resolves. If so, we will merge that into the master branch.

> To download a pull request (or a "PR") you need to:
> 1. Make sure you are signed in with a GitHub account
> 2. Follow the pull request link above
> 3. Follow the guide on this picture: https://images-ext-2.discordapp.net/external/GTXJkSGA22bfKu6zbE4IOCFeJ6GVN_O2RtGXx3mOcLM/https/i.ibb.co/tCcB1Qp/PR1.png?width=340&height=300

**Comment by Mike-Parker** [comment] 2021-01-25 17:38
We'll give it a try and let you know how we get on. Thanks

**Comment by Mike-Parker** [comment] 2021-01-28 17:48
After a couple of days of testing, we've seen no reoccurrence of the issue so it looks like #1706 has fixed the problem. My daughter (playing on Bedrock edition) reported that MC was a bit laggier than usual (jerkier than usual screen updates) but this may have been due to other factors on the Bedrock client (low battery, other apps running etc.)

**Comment by Camotoy** [comment] 2021-01-28 18:19
That has been merged into the main branch, so you are safe to use that.

I'm going to assume this error has been fixed. Let me know if the lagginess continues.

**Closed by Camotoy** 2021-01-28 18:19 UTC
Labels: Unconfirmed Bug
