### ISSUE TITLE
Higher movement speed then in java version

### ISSUE THREAD

**Issue by piotr5ase** [GeyserMC/Geyser#1100] opened 2020-08-08 13:08 UTC
This can lead to ban. 
https://hypixel.net/threads/i-got-banned-for-30-days-and-didnt-do-anything-wrong-but-i-cant-make-an-appeal.3215944/

**Comment by rtm516** [comment] 2020-08-08 13:09
> This can lead to ban.
> https://hypixel.net/threads/i-got-banned-for-30-days-and-didnt-do-anything-wrong-but-i-cant-make-an-appeal.3215944/

Please follow the issue template.

**Comment by DoctorMacc** [comment] 2020-08-08 18:25
Is movement speed an assumption or do you have proof that it is specifically the speed? We are aware of Bedrock triggering anticheat but nothing relating to movement *speed*.

**Comment by Heath123** [comment] 2020-08-08 18:27
> Is movement speed an assumption or do you have proof that it is specifically the speed? We are aware of Bedrock triggering anticheat but nothing relating to movement _speed_.

Exactly, I'm working on fixing the movement issues but I didn't think speed was a problem.

**Comment by Daenningas** [comment] 2020-08-10 15:13
Hi. I believe I have this issue on my server as well. Java players movement is fine, Bedrock players appear to be continually sprinting.
I just rolled back form build 319 to 309 thinking that was when the issue was introduced (I just updated last night), however the issue is still there on 309.

Since this is marked as need more information, what can I provide?

**Comment by DoctorMacc** [comment] 2020-08-10 15:13
Could you elaborate on "continually sprinting"? When does this occur?

**Comment by Daenningas** [comment] 2020-08-10 15:30
I just logged into my server using a Bedrock account (EnchantedSword.net -- Not advertising, just so you can see the issue in action) -- I move in any direction and am moving at a high rate of speed.
Even when crouching I am moving faster than normal.
Using CTRL to run is almost indistinguishable from walking.

**Comment by 4daze** [comment] 2020-08-17 02:38
I can confirm that bedrock players climb ladders faster than java player

**Comment by myk3sr** [comment] 2020-08-25 17:37
I can also confirm this, if you download any anticheat antihacks antigrief plugin, when configured properly for java clients you will get mass amounts of errors on bedrock clients.

Most errors are while interacting with ladders, stairs, water surface, doorways.  Walking on top of wither skulls placed on ground causes errors too.

Jumping while running triggers fly (invalidy Y axis) movements.

This is tragic cause my server has had hack problems in the past and I cant use anticheat antihack plugins cause speed errors.

I can also confirm the values are different for each console client.  Xbox, PS4, and Switch values are all different, windows 10 edition also, mobile users both Android and iOS, ALL VALUES ARE INCONSISTENT.

This bug is essential to getting anti hack features working on java + bedrock please fix !!!!

**Comment by RednedEpic** [comment] 2020-12-12 06:18
Any confirmation on whether this still exists after movement fixes?

**Comment by Chew** [comment] 2021-04-05 23:34
There have not been any confirmations, so going to assume this is good to go. Thank you everyone for your contributions!

**Closed by Chew** 2021-04-05 23:34 UTC
Labels: More Info Needed
