### ISSUE TITLE
Issue joining Velocity Proxy

### ISSUE THREAD

**Issue by LadyHaley** [GeyserMC/Geyser#5048] opened 2024-09-19 13:23 UTC
### Describe the bug

I cant even join my proxy on bedrock, it gives the error linked at the bottom of this ticket, it has happened to two different people on windows 10 and another one on switch, same error. Tried on multiple versions of bedrock, paper builds, and geyser/floodgate builds. I have tried on a proxy hosted in the US and a proxy hosted locally in australia, both with different hardware configurations and different server panel platforms with the same results each time. I have also changed what servers it tried to join the client to when joining through the proxy.
If geyser is out of date it will show the out of date msg instead, it also does show ping and motd in the bedrock client.

### To Reproduce

attempt to join server
doesnt succeed

### Expected behaviour

joining the server succeeds

### Server Version and Plugins

velocity-3.3.0-SNAPSHOT-436
Tried from a US based proxy joining a 1.20.4 paper build #497 server
and from an AUS based proxy joining a 1.21.1 paper build #56 server

1.20.4 server is running AdvancedServerList, FairyChat, HuskHomes AdvancedMobArena, BattleArena, BimmCore, Citizens, CitizensCMD, CMI, CMILib, CoreProtect, DecentHolograms, DeluxeMentions DiscordSRV, FastAsyncWorldEdit, floodgate, GolfParty, HideAndSeek, LibsDisguises, LuckPerms, Magic, MapModCompanion, McInfected MineChess, MiniBoardGames, MinigameMaker, Multiverse-Core, MythicCrucible, MythicMobs, nightcore, Paintball, Pazaak, PlaceholderAPI PlayerParticles, PlugManX, ProNouns, ProtocolLib, RocketJoin, SafeNBT, Sentinel, ServerSigns, SpleefX, SurvivalGames Vault, ViaBackwards, ViaVersion, Vivecraft-Spigot-Extensions, VoidGen, VotingPlugin, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags, XConomy

1.21.1 server is running AdvancedBan, AdvancedServerList, ajLeaderboards, ArmorStandAdjustor, ArmorTrimEdit, BannerMaker, BansWebhook, BlockLocker, BreweryX, Citizens, ClearLag, CMI, CMILib, CoreProtect, Cosmin, CreeperRecover, CustomCrafting, CustomCrops, DecentHolograms, DeluxeMentions, DiscordSRV, DropEdit2, DtlPlayershops, dtlTraders, DualHorse, DurabilityAlertReloaded, Dwellin, EnchantGui, EntityTraveller, ExcellentCrates, ExcellentEnchants, ExtractableEnchantments, FairyChat, FastAsyncWorldEdit, floodgate, FlowerMeal, Gender, GSit, Harbor, HeadDatabase, HuskHomes, IllegalStack, ImageFrame, InteractionVisualizer, InvisibleItemFrames, Jobs, LibsDisguises, Lootin, LuckPerms, Magic, MapModCompanion, MarriageMaster, mcMMO, McmmoGuiV2, Multiverse-Core, MyPet, MythicCrucible, MythicMobs, MythicMobsExtension, nightcore, Oraxen, OreAnnouncer, packetevents, PeacefulPlayerRepacified, PhantomSpawnControl, PlaceholderAPI, PlayerParticles, PlugManX, ProtocolLib, PyroFishingPro, PyroLib, PyroMining, RealScoreboard, RocketJoin, Sentinel, ServerSigns, SpawnerMeta, Spicord, StripArmour, SwimmingHorses, TogglePvp, Vault, ViaBackwards, ViaVersion, Vivecraft-Spigot-Extensions, VotingPlugin, WanderingTrades, WolfyUtilities, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags, XConomy

### Geyser Dump

https://dump.geysermc.org/ckQEUTP3SOyQwqbdUqm26VlTUx2KLoh0

### Geyser Version

Geyser version 2.4.3-b678 (git-master-2ef6172) (Java: 1.21, Bedrock: 1.20.80/1.20.81 - 1.21.30)

### Minecraft: Bedrock Edition Device/Version

1.21.30 Windows 10 and Nintendo Switch

### Additional Context

Speciffic error on join https://hastebin.com/share/raliniyavu.php

**Comment by onebeastchris** [comment] 2024-09-19 14:43
"Channel Closed" means that something went wrong while connecting to the Java server. This could be caused by a different proxy plugin, or the backend server. If you need help troubleshooting the issue, please join our discord server: https://discord.gg/geysermc

I'll close this post since we don't provide support via GitHub issues

**Closed by onebeastchris** 2024-09-19 14:43 UTC
