### ISSUE TITLE
disable bedrock speed bridge

### ISSUE THREAD

**Issue by shinnag0103** [GeyserMC/Geyser#2208] opened 2021-05-13 15:30 UTC
### What feature do you want to see added?

Bedrock speed bridge should be disabled.
because it is unfair in pvp.

### Are there any alternatives?

nothing

**Comment by Camotoy** [comment] 2021-05-13 15:31
Duplicate of #2061. Thank you for reporting anyway!

**Comment by shinnag0103** [comment] 2021-05-13 15:32
sorry

**Closed by Camotoy** 2021-05-13 15:31 UTC
Labels: Feature Request
