### ISSUE TITLE
[1.16] There is an error in the display of enchanted equipment.

### ISSUE THREAD

**Issue by HeyDon-Lee** [GeyserMC/Geyser#828] opened 2020-06-28 12:40 UTC
**Describe the bug**
Enchanted equipment can not be seen Chestplates, Leggings, Boots, part of the enchanted equipment display error.

**Screenshots / Videos**
Java:
![image](https://user-images.githubusercontent.com/16282726/86030420-0b2b3400-ba67-11ea-9489-fb8ba9d5c2a0.png)
Bedrock:
![image](https://user-images.githubusercontent.com/16282726/86030431-0e262480-ba67-11ea-83b8-d77b5948d8ea.png)

**Server Version**
1.16.1 / Paper-21

**Geyser Version**
1.16

**Minecraft: Bedrock Edition Version**
1.16.1

**Comment by Heath123** [comment] 2020-06-28 13:34
Please give more information...

**Comment by Savagetechguy** [comment] 2020-06-28 15:29
I experienced this too. When wearing a full set of armor the player will only have a helmet on

**Comment by HeyDon-Lee** [comment] 2020-06-29 16:19
I found the problem. The problem is the enchanted equipment.
@Heath123 @Savagetechguy

**Comment by RednedEpic** [comment] 2020-07-04 17:43
Can you please provide more information about this problem? What enchants are not working, is it just the equipment that is unable to show enchantments... etc.?

**Comment by RednedEpic** [comment] 2020-07-12 01:01
Shortly after this report there were fixes upstream that should resolve the problem you were encountering. Closing for now as I am unable to reproduce, but please let us know here if you still have the problem on the latest build.

**Comment by rtm516** [comment] 2020-07-12 11:32
I just checked this and it is still an issue when pulling an item out of the creative inventory, in this case, an enchanted book. The enchantment is lost. See https://github.com/GeyserMC/Geyser/pull/920/files#diff-781ea13cab34d3922b6ddce4de83c882R50-R60

**Comment by Chew** [comment] 2021-04-05 23:37
This appears to have been fixed as of now. If you happen to run into this, please let us know. Thank you everyone for your contributions!

**Closed by Chew** 2021-04-05 23:37 UTC
Labels: More Info Needed, Unconfirmed Bug
