### ISSUE TITLE
Boat Bug

### ISSUE THREAD

**Issue by Craftifyeu** [GeyserMC/Geyser#2693] opened 2021-12-09 10:17 UTC
### Describe the bug

Hi, we have such a minor problem on the server that if the mobile player creates a boat and then puts it down, everything is fine so far, but as he gets out of the boat, the boat disappears. The Java player still sees the boat.
[After disconnection and reconnection, the boat is visible again.]

### To Reproduce

1. Place boat
2. Get on the boat
3. Get off the boat

### Expected behaviour

Well, I expected the boat to stay where the player parked.

### Server Version and Plugins

Server: git-Paper-59 (MC: 1.18)
Plugins: AntiAFK*, AuthMe, BPS-Free, ClearConsole*, ConsoleSpamFix, CoreProtect, DiSky, DriveBackupV2, dynmap, Ersatz*, floodgate, Geyser-Spigot, Harbor, InventoryRollbackPlus, LuckPerms, PlaceholderAPI, PlugMan, ProtocolLib, Reqn*, RuntimeSkriptAddonPatcher, SharpSK*, SkBee, skDragon, Skellett, SkinsRestorer, SkQuery, skRayFall, Skript, skript-reflect, skript-yaml, SkriptJSON*, SkStuff*, SkUniversal, skUtilities*, TAB, Themis, WolvSK, WorldBorder

### Geyser Version

2.0.0-SNAPSHOT (git-master-8c7a3d1)

### Minecraft: Bedrock Edition Version

1.18.0

**Comment by Camotoy** [comment] 2021-12-09 13:34
Sounds like a duplicate of #2605. Thank you for reporting anyway!

**Closed by Camotoy** 2021-12-09 13:34 UTC
