### ISSUE TITLE
New geyser update (1.19.80) ruined proxy protocol IP's

### ISSUE THREAD

**Issue by liquidman228** [GeyserMC/Geyser#3706] opened 2023-04-27 15:22 UTC
### Describe the bug

I use UDP proxy protocol on my bungeecord and with new version all bedrock players are getting not their real IP, with ruins alot of things on my server, because my server says that ALL bedrock players are playing with the same IP

When i switched back to previous version, everything works just fine

### To Reproduce

1. Install the latest version of Geyser (1.19.80)
2. Use proxy protocol on your bungeecord
3. Log in and check your IP - it will be not real IP

### Expected behaviour

Users have their real IP's, as on the old version

### Geyser Version

https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/1352/

**Comment by onebeastchris** [comment] 2023-04-27 15:24
Duplicate of https://github.com/GeyserMC/Geyser/issues/3703.

**Closed** 2023-04-27 15:45 UTC
Labels: Duplicate
