### ISSUE TITLE
A parrot's pant sound causes error and kick from server

### ISSUE THREAD

**Issue by CuteTadpole** [GeyserMC/Geyser#618] opened 2020-05-22 15:16 UTC
**Describe the bug**
Sometimes parrots can pant when the wolf is near, and this pant sound causes error and kick.

**To Reproduce**
1. Spawn the parrot and the wolf next to each other (in Java Minecraft):
![image](https://user-images.githubusercontent.com/61086561/82682044-4d3aac00-9c57-11ea-8d8c-2c5ecd88c5f8.png)
2. Wait a little bit
3. See this error:
![image](https://user-images.githubusercontent.com/61086561/82682142-71968880-9c57-11ea-9647-2df363c787de.png)

**Expected behavior**
Correct sound playing

**Screenshots / Videos**
See screenshots above

**Server Version**
![image](https://user-images.githubusercontent.com/61086561/82682387-deaa1e00-9c57-11ea-9827-9cf8d343ed4a.png)

**Geyser Version**
Geyser Bungee build 171

**Minecraft: Bedrock Edition Version**
1.14.60

**Comment by DoctorMacc** [comment] 2020-05-22 15:18
This is a duplicate of #516 - I'm going to close this. You did a wonderful job providing information; could you copy it all over there, as well as specify if you're using any plugins?

**Closed by DoctorMacc** 2020-05-22 15:18 UTC
