### ISSUE TITLE
Text above the hotbar sometimes shows json data

### ISSUE THREAD

**Issue by GhostCoder256** [GeyserMC/Geyser#241] opened 2020-03-24 20:21 UTC
**Describe the bug**
When seeing something that changes the text above the hotbar on Bedrock, it will sometimes show json data instead of the intended information.

**To Reproduce**
There are multiple ways to see it, but the way I found it is to
1. Open a Java server with [this](https://www.dropbox.com/s/v38dypro425odbl/MGS_2.0_resources.zip?dl=0) datapack
2. Go on with a bedrock client through Geyser
3. Use the command `/function mgs:guns/mac10/give/gun` to get a gun (it will look like a fishing rod without the resource pack)
4. See the splurge of json data above the hotbar

**Expected behavior**
The text above the hotbar should show the ammo left like it does in Java edition

**Screenshots**
Java Screenshot: https://www.dropbox.com/s/rp07taadj5yijy0/2020-03-24%20%281%29.png?dl=0
Bedrock Screenshot: https://www.dropbox.com/s/42kzuydrmmvl4fq/2020-03-24%20%282%29.png?dl=0

**Server version**
git-Paper-105 (MC: 1.15.2)

**Geyser version**
latest

**Bedrock version**
v1.14.30

**Additional context**
I know this isn't strictly related to Geyser, but since there's eventually going to be another plugin or datapack wanting to edit the text above the hotbar, I figured I would share it here.

**Comment by RednedEpic** [comment] 2020-05-05 05:14
Datapack link is invalid. There have been some changes in this area, and so far we've not received a report similar to this. Closing for the time being, however if you're still able to reproduce, let us know here and please include an updated link to where we can download the datapack.

**Comment by DoctorMacc** [comment] 2020-05-05 14:05
Just confirmed this with the Coordinates HUD pack here: https://vanillatweaks.net/picker/datapacks/

**Comment by DoctorMacc** [comment] 2020-08-27 19:33
This is now fixed, likely because of #1161.

**Closed by DoctorMacc** 2020-08-27 19:33 UTC
Labels: Confirmed Bug, Priority: Low
