### ISSUE TITLE
Bedrock users can crouch under slabs

### ISSUE THREAD

**Issue by S0M0G** [GeyserMC/Geyser#1819] opened 2021-01-08 15:52 UTC
The Bedrock user cant crouch under slabs while Java players can. I have an XP farm which the bedrock user cant collect XP by going under the slab so my friend on Bedrock has to get it from the sides while on Java I can.

**Comment by Camotoy** [comment] 2021-01-08 15:55
In the future, please follow the issue template.

This is a duplicate of #1456. Thank you for reporting anyway!

**Closed by Camotoy** 2021-01-08 15:55 UTC
