### ISSUE TITLE
Hide hud if use chest-menu (❗ have fix)

### ISSUE THREAD

**Issue by towuk118** [GeyserMC/Geyser#621] opened 2020-05-22 21:15 UTC
**To Reproduce**
see video
dont have steps

**Expected behavior**
not have

**Screenshots / Videos**
### just check video: https://youtu.be/Kj3A69KJThw
 timecode 1:16 - see bug
 timecode 0:10 - see logs console and other

> I can provide this server-files for testing by you!

**Server Version**
CraftBukkit version git-Spigot-b32c8f8-4d3bf20 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT) and other spigot 1.15+ version without viaversion!!!

**Geyser Version**
latest now

**Minecraft: Bedrock Edition Version**
latest stable 1.14.60

**Comment by rtm516** [comment] 2020-05-22 21:20
Likely duplicate of #205 and fixed by https://github.com/GeyserMC/Geyser/pull/602 Please can you test that PR

**Comment by towuk118** [comment] 2020-05-22 21:27
> Likely duplicate of #205 and fixed by #602 Please can you test that PR

how build geyser bukkit this RP?

**Comment by towuk118** [comment] 2020-05-22 21:36
> Likely duplicate of #205 and fixed by #602 Please can you test that PR

i build this repository from you #602 tag (https://github.com/AJ-Ferguson/Geyser/tree/inventory-fixes)
will test...
![image](https://user-images.githubusercontent.com/28830162/82711180-4af34480-9c8d-11ea-86f5-8534db092760.png)

**Comment by towuk118** [comment] 2020-05-22 21:43
not work...
dont work standalone and bukkit
![image](https://user-images.githubusercontent.com/28830162/82711549-5d21b280-9c8e-11ea-9960-e9e8d685ea4c.png)

**Comment by towuk118** [comment] 2020-05-22 21:48
![image](https://user-images.githubusercontent.com/28830162/82711770-08cb0280-9c8f-11ea-814c-5c582273064a.png)
oh nice... i wil test... :)

**Comment by towuk118** [comment] 2020-05-22 22:18
hm.... worked! fix worked !!!!!
https://github.com/AJ-Ferguson/Geyser/tree/inventory-fixes

**Closed** 2020-06-02 16:48 UTC
Labels: Confirmed Bug, Priority: Medium
