### ISSUE TITLE
Geyser Console Debugging Says Inmapped Items

### ISSUE THREAD

**Issue by NatickYT** [GeyserMC/Geyser#2928] opened 2022-04-13 13:52 UTC
### Describe the bug

When Having The Debugger Enabled Geyser States About Translations Needing To Be Added

### To Reproduce

1. Download The Latest Geyser Version (2.0.2-Snapshot) Onto A Paper Server
2. Enable Debugging
3. Read Console As It Boots

### Expected behaviour

Not To Need Any More Items Or Blocks Translating

### Screenshots / Videos

![20220413_144534](https://user-images.githubusercontent.com/99545540/163195606-74220a93-f785-4789-9b45-aa9304b84c45.jpg)
![20220413_144550](https://user-images.githubusercontent.com/99545540/163195618-5c09c247-e6ea-4154-b039-02a8fc9292cf.jpg)
![20220413_144607](https://user-images.githubusercontent.com/99545540/163195623-d768eca9-b330-4544-bca2-88819eeee5ee.jpg)
![20220413_144626](https://user-images.githubusercontent.com/99545540/163195628-b93d2e7f-a0d8-4849-8253-85db13fa1ff9.jpg)

### Server Version and Plugins

Server Turned Off Before I Could Fill This Out

### Geyser Dump

Server Turned Off Before I Could Fill This Out

### Geyser Version

2.0.2-Snapshot (Server Turned Off Before I Could Fill This Out)

**Comment by rtm516** [comment] 2022-04-13 13:56
First is from https://github.com/GeyserMC/Geyser/blob/1d3eebc678be9a17fb71141bdacd933c13477f0c/core/src/main/java/org/geysermc/geyser/registry/populator/ItemRegistryPopulator.java#L397-L399
Second is from https://github.com/GeyserMC/Geyser/blob/1d3eebc678be9a17fb71141bdacd933c13477f0c/core/src/main/java/org/geysermc/geyser/registry/type/ItemMappings.java#L153

**Comment by Camotoy** [comment] 2022-04-13 22:05
The first is not an error whatsoever. It indicates that the item NAME needs translated since it doesn't exist in Bedrock.

**Comment by onebeastchris** [comment] 2023-06-06 00:24
Closing this, as it is intended behavior - items that arent mapped either dont exist in all supported versions, and are yet to be mapped, or have to be mapped another way to work around some items not existing on bedrock.

**Closed by onebeastchris** 2023-06-06 00:24 UTC
Labels: Work in Progress
