### ISSUE TITLE
/help [topic] command does not work for bedrock players

### ISSUE THREAD

**Issue by 420noscope-exe** [GeyserMC/Geyser#4478] opened 2024-03-05 18:47 UTC
### Describe the bug

I added an alias for the /help command.  The alias executes `/help Rules` and maps that to `/rules`.   Trying to use `/help` for any topic other than `?` and `help` does not work (this includes help for plugins).  Doing this returns a syntax error, and the use of `/help` by a bedrock player is not logged to console.  It would appear that this command is not even being sent to the server for a response. This works fine on java, but not on bedrock.  I disabled command suggestions as it was causing crashes, and essentially broke all commands for bedrock players as the game would crash the second they typed `/`, 100% of the time.  All other commands work as expected except for `/help` now.  Using an alias for `/tellraw`  is not a solution, as I would have to give every player permission to use `/tellraw`.  Using `/help` only provides info for the `/help` command and nothing else.  Please see second screenshot.

### To Reproduce

1. Connect to geyser enabled java server on bedrock client
2. execute alias `/rules` or `/help Rules`/`/help [topic]`

### Expected behaviour

The specified topic should be visible in chat to the player that executed the command.

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/25134554/e62f6609-b197-418b-bdfe-925fb35a9a16)

![image](https://github.com/GeyserMC/Geyser/assets/25134554/bd4ca7fa-8d2d-4662-a077-90c3a0687b2e)

### Server Version and Plugins

This server is running CraftBukkit version 4045-Spigot-c198da2-38fd4bd (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT)

Plugins (8): dynmap, eggThrow420, OpenInv, floodgate, personal420, caseyGun420, TeleCraft, Geyser-Spigot

### Geyser Version

Geyser version 2.2.2-SNAPSHOT (git-master-6a51d82) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.60/1.20.61)

### Minecraft: Bedrock Edition Device/Version

1.20.62 Windows 10

**Comment by onebeastchris** [comment] 2024-03-05 18:49
Unfortunately, this a Bedrock client side limitation - these are hard-coded to show the available commands :/

Duplicate of https://github.com/GeyserMC/Geyser/issues/2573 - thanks anyways for reporting.

**Closed by onebeastchris** 2024-03-05 18:49 UTC

**Comment by 420noscope-exe** [comment] 2024-03-05 19:03
I propose a new command be added `/helpB` or something similar be added that executes the java `/help` command and sends this to the server if the `/help` is hardcoded into the bedrock client.

**Comment by onebeastchris** [comment] 2024-03-05 19:16
That seems like a bad solution, considering that it could clash with a Java command that has that name. For the meantime, I'd recommend telling Bedrock players to use the non-aliased command. Alternatively, you could try and limit command crashing by reducing the amount of suggestions sent with the HideCommands Geyser extension :)

**Comment by 420noscope-exe** [comment] 2024-03-05 19:27
Thats the thing, the non aliased command `/help Rules` does not work either.  The normal `/help command` can only take 2 types of parameters [int: page] and [command: CommandName].  Spigot and most other flavors of minecraft server have a third override for this, [topic: TopicName].  This solution would not clash with a java command of that name, as there is no built in command `/helpB`.  Plus, it could literally be named anything other than that.

Running `/execute as @p run help` on a bedrock client gives me the java output of the command from the server, instead of the bedrock output.  If  `/execute` worked with external plugin commands, this would work.  I believe 100% that an additional command can be added for bedrock players to send `/help` to the server and get the full output.

**Comment by 420noscope-exe** [comment] 2024-03-05 21:27
My implementation of this works.  I added `/helpBedrock` as a command.  This returns the Server override for `/help` instead of the default version of this command in Bedrock and Java. 

![image](https://github.com/GeyserMC/Geyser/assets/25134554/0e6daac6-72fc-4f97-b6aa-212a01b01a05)

```
package bedrockhelpgeyser.noscope420;

import org.bukkit.Bukkit;
import org.bukkit.Server;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

public class HelpBedrock implements CommandExecutor{

	public boolean onCommand(CommandSender sender, Command cmd, String commandLabel, String[] args)
	{
		if (sender instanceof Player) {
            Player player = (Player) sender;
        }
		
		Bukkit.getServer().dispatchCommand(sender,"/help");
		 
		return true;
	}
	
}
```

This fixes the problem.
