### ISSUE TITLE
Sweeping Edge books cant be used to enchant swords in anvil

### ISSUE THREAD

**Issue by ajaxnotmeta** [GeyserMC/Geyser#4337] opened 2023-12-13 19:45 UTC
### Describe the bug

Sweeping Edge books cant be used to enchant swords in anvil despite you can get one in enchantment table and cant be workarounded with renaming the swords

### To Reproduce

1.put swords on anvil
2.put sweeping edge book on its 2nd slot
3.the arrow were crossed

### Expected behaviour

putting swords and sweeping edge books will result the sword having its enchantment in the anvil

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/135541817/23aa6290-7484-4688-8ca4-6f9c243faa5a)

### Server Version and Plugins

Geyser For Fabric or Geyser Mod for Fabric

### Geyser Version

2.2.0-SNAPSHOT (git-master-3971650) (Java: 1.20.2, Bedrock: 1.20.0/1.20.1 - 1.20.50)

**Comment by onebeastchris** [comment] 2023-12-13 20:42
Closing as duplicate of https://github.com/GeyserMC/Geyser/issues/3121 - unfortunately, there's nothing we can do about that. Bedrock simply refuses to accept custom enchantments (or those that it doesn't recognize).
Thanks anyways for reporting

**Closed by onebeastchris** 2023-12-13 20:42 UTC
