### ISSUE TITLE
Signed Books and Lecterns with Books Issues

### ISSUE THREAD

**Issue by Spectr3D** [GeyserMC/Geyser#1285] opened 2020-09-13 01:13 UTC
**Describe the bug**
Signed Books when made on bedrock just have their text inside the book converted to null.
When any Book & Quill or a Signed Book is put into a lectern, Bedrock Edition is unable to break the Lectern. 

**To Reproduce**
1. Open a Book & Quill on Bedrock and attempt to sign the book.
2. When signed, all text is made null.

**Server Version**
CraftBukkit version git-Spigot-b5a13e6-0d8350a (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Geyser Version**
Geyser version 1.1.0 (git-master-46c3484) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.100)

**Minecraft: Bedrock Edition Version**
1.16.40

**Additional Context**
The Author and Title are fine when signed, just the text inside the book is converted to null. Java Books have no issues being read on Bedrock

**Comment by DoctorMacc** [comment] 2020-09-13 01:14
This is a duplicate of #1088. Thank you for reporting anyway!

**Closed by DoctorMacc** 2020-09-13 01:14 UTC
