### ISSUE TITLE
Item Displays

### ISSUE THREAD

**Issue by Tobias123567** [GeyserMC/Geyser#4073] opened 2023-08-23 11:25 UTC
### What feature do you want to see added?

Translate item displays to items, so that bedrock users can also see them

### Are there any alternatives?

no

**Comment by onebeastchris** [comment] 2023-08-23 11:32
Duplicate of https://github.com/GeyserMC/Geyser/issues/3810, closing.
They'll probably take a while to be implemented/worked around, since they don't exist on Bedrock edition natively

**Closed** 2023-08-23 11:32 UTC
Labels: Duplicate
