### ISSUE TITLE
Bedrock players Invisible after Death

### ISSUE THREAD

**Issue by mrunningmasterc** [GeyserMC/Geyser#3908] opened 2023-06-23 23:30 UTC
### Describe the bug

When players are pvping, and a bedrock players get killed and they respawn at pvp area they are invisible. It seems to only happen when bedrock players are killed.

### To Reproduce

fight a bedrock account and kill them. 
Sometimes it makes them invisible sometimes it doesn't
Happens randomly but gets pretty annyoing in serious pvp fights.

### Expected behaviour

When fighting a bedrock player, it should turn them invisible after you kill them.

### Server Version and Plugins

git-Purpur-1985 (MC: 1.19.4)

### Geyser Dump

https://dump.geysermc.org/V89IlUvkMxwpc4e2A9DnPFlbalWzsSi0

### Geyser Version

 2.1.1-SNAPSHOT (git-master-50d7f56) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.0)

### Minecraft: Bedrock Edition Device/Version

1.20.1

**Comment by frogglen** [comment] 2023-06-24 02:16
same problem

**Comment by mrunningmasterc** [comment] 2023-06-27 13:26
![invis glitch](https://github.com/GeyserMC/Geyser/assets/63335629/ed387e3b-ba64-4361-aad1-07ad10e4304f)
![invis](https://github.com/GeyserMC/Geyser/assets/63335629/8bd30657-de12-4e1e-92a0-95e79e8d9638)
Here are some screen shots of players this happens to when they die

**Comment by mrunningmasterc** [comment] 2023-06-29 03:11
I’ve even removed every single plug-in made it vanilla in 1.20.1. I have the latest version of geysermc. I’m still getting issues.

**Comment by mrunningmasterc** [comment] 2023-06-29 03:26
As you can see in the video. I have two bedrock accounts. They both died. They respawn. I look over at .Kirizuto and walk over to look down at where the zombies are. I dropped .kirizuto down and start walking around but the account recording doesn't seem .kirizuto it just see the zombies and spiders walking around. then you see the kill message in the chat. When .kirizuto respawns you see where he get respawned but then when he moves he's invisible.
https://github.com/GeyserMC/Geyser/assets/63335629/22901a53-69f2-41bd-8100-84da3557c16a

**Comment by Konicai** [comment] 2023-06-29 03:38
> I’ve even removed every single plug-in made it vanilla in 1.20.1. I have the latest version of geysermc. I’m still getting issues.
this occurs without any plugins/datapacks?

**Comment by mrunningmasterc** [comment] 2023-06-29 05:27
> > I’ve even removed every single plug-in made it vanilla in 1.20.1. I have the latest version of geysermc. I’m still getting issues.
> 
> this occurs without any plugins/datapacks?

Yes. I have no plugins/datapacks running. Its just latest version of paper on 1.20.1.

**Comment by mrunningmasterc** [comment] 2023-06-29 05:41
Only affects bedrock players
Using geysermc on proxy


Geyser version 2.1.1-SNAPSHOT (git-master-4077514) 
git-Paper-56 (MC: 1.20.1)


<img width="324" alt="Screen Shot 2023-06-29 at 1 30 27 AM" src="https://github.com/GeyserMC/Geyser/assets/63335629/f69c755e-3008-4312-b3af-08bc0038fe8f">

**Comment by SrCookie450** [comment] 2023-07-02 17:43
It's happening here too... using paper 1.16.5, 1.20.1 bedrock

https://github.com/GeyserMC/Geyser/assets/119267439/d575601e-532e-4d96-8bc1-728b48638726

**Comment by Redned235** [comment] 2023-07-02 17:47
This is a regression from 1.20. More details on what causes this issue can be found here: https://github.com/pmmp/PocketMine-MP/issues/5822

We may look in to what caused this, but unfortunately will require a far less-than-ideal fix that will likely cause regressions in other places. However, this seems to be fixed in 1.20.10, and once the update is out, the issue should be resolved from the Geyser side too.

**Comment by SrCookie450** [comment] 2023-07-02 21:01
> This is a regression from 1.20. More details on what causes this issue can be found here: [pmmp/PocketMine-MP#5822](https://github.com/pmmp/PocketMine-MP/issues/5822)
> 
> We may look in to what caused this, but unfortunately will require a far less-than-ideal fix that will likely cause regressions in other places. However, this seems to be fixed in 1.20.10, and once the update is out, the issue should be resolved from the Geyser side too.

sorry if i'm being dumb, but "1.20.10" is 1.20.0.10... some users may get this issue on 1.20.1

**Comment by Konicai** [comment] 2023-07-02 21:05
1.20.10 is in preview/beta right now (1.20.0.10 doesn't exist)

**Comment by SrCookie450** [comment] 2023-07-02 21:09
> 1.20.10 is in preview/beta right now (1.20.0.10 doesn't exist)

thanks for telling me

**Comment by onebeastchris** [comment] 2023-07-14 12:42
1.20.10/1.20.11 is out and fixes this issue; please update Geyser/Bedrock clients & this issue should be resolved.

**Closed** 2023-07-14 12:43 UTC
