### ISSUE TITLE
Forced Zoom Issue when using Multiverse-Core TP  Commands and MV Portals

### ISSUE THREAD

**Issue by TMFuzz** [GeyserMC/Geyser#4022] opened 2023-07-31 02:51 UTC
### Describe the bug

For some reason when any mv commands are used to teleporting portals and tpa tphere bedrock players are in a forced zoom perspective and the only way to fix it is by leaving and relogging.

### To Reproduce

go through mv portal
use tpa or tphere commands
tp bedrock player to anyworld other than spawn

### Expected behaviour

bedrock player should not be zoomed in.

### Screenshots / Videos

https://www.twitch.tv/videos/1886173828

### Server Version and Plugins

[01:30:11] [Server thread/INFO]: This server is running CraftBukkit version 3837-Spigot-3374045-7cf863d (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)
[01:30:11] [Server thread/INFO]: Checking version, please wait...
[01:30:11] [Thread-86/INFO]: You are 6 version(s) behind

### Geyser Dump

https://dump.geysermc.org/MTbgYZ6d7FSA7VHcFJDT5hUDsRrrRRnP

### Geyser Version

[Server thread/INFO]: This server is running Geyser version 2.1.2-SNAPSHOT (git-master-19914a5) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.10)

### Minecraft: Bedrock Edition Device/Version

1.20.1 Android and 1.20.1 minecraft for windows bedrock

### Additional Context

This only happens when i use mv tp commands mv portals if i use my java player go through the mv portal no issues and use mc tp command it works just find nether portals just fine. Only get the forced zoom when using mv tp options. Only way the stop the zoom in is rejoin the game.

**Comment by gre3x** [comment] 2023-08-02 06:23
Looks like duplicate of #3896. There was a PR (#3978), but it was closed by @patyhank due to not being needed? 

I am also still getting this issue in latest version

**Comment by jandie1505** [comment] 2023-08-02 11:39
I'm also getting this issue. I'm using the latest version of geyser on a 1.20.1 paper server.
I'm running a BungeeCord network. On a server switch, this bug does not occur, but when teleporting from one world to another (multiverse or not), the bug occurs.
The bug is also available in 2 different variants. On some clients, there is this fov bug, on some other clients, there is no fov bug, but the world around the player is not loading until the player reconnects.
If I can provide more information about this, tell me which information you want.

**Comment by TMFuzz** [comment] 2023-08-03 15:02
After further inspection, I was able to determine that being in spectator mode and then teleporting to a different dimension is the issue. For some reason, when I'm in any other mode, it doesn't have the FOV issue..

**Comment by patyhank** [comment] 2023-08-03 15:07
Revert https://github.com/GeyserMC/Geyser/pull/3770
This is no longer needed this commit

**Comment by patyhank** [comment] 2023-08-04 05:20
A temporary solution:
Turn this option off
![image](https://github.com/GeyserMC/Geyser/assets/41978811/731e71bd-4f36-47cc-944d-3dc1a0253093)

**Comment by onebeastchris** [comment] 2023-09-05 12:20
Feel free to test #4093 whether it fixes this issue, it should resolve this

**Closed** 2023-09-06 22:13 UTC
