### ISSUE TITLE
Furnaces don't work

### ISSUE THREAD

**Issue by redness360** [GeyserMC/Geyser#801] opened 2020-06-22 13:39 UTC
**Describe the bug**
Opening a Furnace (any type of furnace, smoker, or blast furnace) does nothing on Bedrock.

**To Reproduce**

1. Click on furnace

**Expected behavior**
Furnace GUI opens.

**Screenshots / Videos**

**Server Version**
1.15.2 Paper

**Geyser Version**
#244 Bukkit Plugin with Floodgate 

**Minecraft: Bedrock Edition Version**
1.14.6

**Additional Context**
Tried uninstalling Modern LWC plugin (lock containers), didn't fix. Other plugins installed are LuckPerms, Harbor (sleep enhanment), ClearLag, DiscordSRV (Minecraft server log in discord server), vault, and vaultchatformater.

**Comment by RednedEpic** [comment] 2020-06-22 13:39
Furnaces work fine. Please fill out the issue template with more information if you're running into issues.

**Comment by redness360** [comment] 2020-06-22 13:41
Sorry, I forgot to remove the tags on the words. Fixed now!

**Comment by DoctorMacc** [comment] 2020-06-22 13:42
Do chests and other inventories work?

**Comment by redness360** [comment] 2020-06-22 13:42
Yes

**Comment by DoctorMacc** [comment] 2020-06-22 13:43
Any errors on console? Does it happen on a clean server with no plugins?

**Comment by redness360** [comment] 2020-06-22 13:48
This is the console error, haven't tested a clean server yet but I will try to asap: 
[09:46:34 WARN]: [Geyser-Bukkit] Could not translate packet ServerOpenWindowPacket
java.lang.NullPointerException: null
	at org.geysermc.connector.utils.LocaleUtils.getLocaleString(LocaleUtils.java:251) ~[?:?]
	at org.geysermc.connector.network.translators.inventory.holder.BlockInventoryHolder.prepareInventory(BlockInventoryHolder.java:64) ~[?:?]
	at org.geysermc.connector.network.translators.inventory.BlockInventoryTranslator.prepareInventory(BlockInventoryTranslator.java:51) ~[?:?]
	at org.geysermc.connector.utils.InventoryUtils.openInventory(InventoryUtils.java:56) ~[?:?]
	at org.geysermc.connector.network.translators.java.window.JavaOpenWindowTranslator.translate(JavaOpenWindowTranslator.java:84) ~[?:?]
	at org.geysermc.connector.network.translators.java.window.JavaOpenWindowTranslator.translate(JavaOpenWindowTranslator.java:41) ~[?:?]
	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:93) ~[?:?]
	at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:400) ~[?:?]
	at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) ~[?:?]
	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) ~[?:?]
	at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[09:46:34 WARN]: java.lang.NullPointerException
[09:46:34 WARN]: 	at org.geysermc.connector.utils.LocaleUtils.getLocaleString(LocaleUtils.java:251)
[09:46:34 WARN]: 	at org.geysermc.connector.network.translators.inventory.holder.BlockInventoryHolder.prepareInventory(BlockInventoryHolder.java:64)
[09:46:34 WARN]: 	at org.geysermc.connector.network.translators.inventory.BlockInventoryTranslator.prepareInventory(BlockInventoryTranslator.java:51)
[09:46:34 WARN]: 	at org.geysermc.connector.utils.InventoryUtils.openInventory(InventoryUtils.java:56)
[09:46:34 WARN]: 	at org.geysermc.connector.network.translators.java.window.JavaOpenWindowTranslator.translate(JavaOpenWindowTranslator.java:84)
[09:46:34 WARN]: 	at org.geysermc.connector.network.translators.java.window.JavaOpenWindowTranslator.translate(JavaOpenWindowTranslator.java:41)
[09:46:34 WARN]: 	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:93)
[09:46:34 WARN]: 	at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:400)
[09:46:34 WARN]: 	at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
[09:46:34 WARN]: 	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
[09:46:34 WARN]: 	at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324)
[09:46:34 WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by DoctorMacc** [comment] 2020-06-22 13:55
Looks like this is the same core error as #776 so I'm closing it to keep things clean. It's odd though that chests work and furnaces don't - maybe a corrupt `en_us.json`?

**Comment by redness360** [comment] 2020-06-22 13:56
Removing the plugins does not fix

**Closed by DoctorMacc** 2020-06-22 13:55 UTC
Labels: Unconfirmed Bug

**Comment by redness360** [comment] 2020-06-22 14:05
Also, single chests don't work, but double chests do, I think it's the same issue as you merged it with

**Comment by redness360** [comment] 2020-06-22 14:17
Geyser says locale file not found when starting, I'm a noob so can anyone tell me how I download it?

**Comment by DoctorMacc** [comment] 2020-06-22 14:19
Well, that's the bug - it should download, and as far as I'm aware in these cases it does but Geyser doesn't pick up on that.

**Comment by redness360** [comment] 2020-06-22 14:20
Any way to download manually, already tried deleting geysers files and restarting.

**Comment by DoctorMacc** [comment] 2020-06-22 14:22
For now, use this version: https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/241/
I've been unable to replicate this bug myself so I have no idea what the problem is.
