### ISSUE TITLE
A part of EliteMob and MMOitems is unable

### ISSUE THREAD

**Issue by sai03925** [GeyserMC/Geyser#3729] opened 2023-05-01 02:00 UTC
### Describe the bug

sword , axe, bow, fiahong rods and other items are unable. Also we can't uae the skills which the items have. And we can't open shulker box. probably the issues only switch.

### To Reproduce

1.grab the item
2.use the item like sword to enemys
3.try to use the skill like heal

### Expected behaviour

you must be not able to attack the enemy and can't use the skill

### Server Version and Plugins

EliteMob and MMO.the newest version.

### Geyser Version

the newest version

### Minecraft: Bedrock Edition Device/Version

nintendoswitch the newest version

**Comment by frogglen** [comment] 2023-05-01 02:03
This is a likely duplicate of the https://github.com/GeyserMC/Geyser/issues/3710 issue

**Comment by onebeastchris** [comment] 2023-05-01 14:21
Hey! Could you try the latest Geyser build and see if the error persists?
Thanks!

**Comment by sai03925** [comment] 2023-05-02 00:37
I have been testing the latest version now, everything seems to work fine. thank you

**Comment by Konicai** [comment] 2023-05-02 02:09
Duplicate and fixed

**Closed by Konicai** 2023-05-02 02:09 UTC
