### ISSUE TITLE
Blocks change to Item Frames with Datapack Utilities datapack

### ISSUE THREAD

**Issue by ToastyDark** [GeyserMC/Geyser#1491] opened 2020-11-03 19:12 UTC
**Describe the bug**
When furnaces, smokers, or campfires come into view on all Bedrock versions,, they change into item frames; I guess symbolizing theirs a translation bug? 

**To Reproduce**

Walked out of view of furnaces, smokers, or campfires and walking back into view seems to cause this bug.

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/31451604/98029944-44d9c600-1dde-11eb-822c-4ac9a3cc8a7e.png)

**Server Version**
Paper-209 (MC: 1.16.3)

**Geyser Version**
 1.1.0 (git-master-ea52107)

**Minecraft: Bedrock Edition Version**
1.16.40

**Additional Context**

**Comment by DoctorMacc** [comment] 2020-11-03 19:13
Please provide a Geyser dump.

Are there item frames on those blocks?

**Comment by MatthewPenguin** [comment] 2020-11-03 19:15
Here we go. https://dump.geysermc.org/VsRWZqszT9pKzH2LFrc6sU1IONny4Jbm

And no, there are no item frames on any of the blocks

**Comment by DoctorMacc** [comment] 2020-11-03 19:18
It wouldn't be a translation error occurring here; it would be that an item frame is spawning and overriding the existing block (as they are blocks on Bedrock). I assume this a plugin issue; therefore, if you have time, try this:

- Temporarily remove/move half of your plugins from your server's plugins folder, except Geyser/Floodgate.
- If the problem persists, remove another half.
- If the problem goes away, swap that half of your plugins with the other half.
- Keep repeating this pattern, this time with the half that exhibits the problem, until you find your problematic plugin.

**Comment by MatthewPenguin** [comment] 2020-11-03 19:57
Literally removed every plugin bug Geyser and floodgate and this bug still happens

**Comment by DoctorMacc** [comment] 2020-11-03 19:57
Can you send the world file here, if you're OK with it?

**Comment by MatthewPenguin** [comment] 2020-11-03 20:04
The world is 520mb, might take a bit to upload

**Comment by MatthewPenguin** [comment] 2020-11-03 20:14
https://www.dropbox.com/s/0axqgo6wmhw4853/world.zip?dl=0

**Comment by DoctorMacc** [comment] 2020-11-04 16:39
OK, so it's probably not a plugin issue but a datapack issue.

**Comment by DoctorMacc** [comment] 2020-11-04 17:09
The datapack with the issue is `datapackutilities-v2-2-1c.zip`. I'll investigate further.

**Comment by MatthewPenguin** [comment] 2020-11-05 03:46
yeah I figured after you said it could be datapack, datapack utilities does something specific with those blocks

**Comment by ZeBarba** [comment] 2021-04-03 20:34
I have the exactly same issue as @MatthewPenguin and I also use Datapack Utilities in my World (in fact, it works as a library of Cave Biomes data pack). I already realise that this is the problem, but I want to know if you guys found a way around to keep Datapack Utilities and solve this item frame situation.

**Comment by Kas-tle** [comment] 2024-03-17 05:39
This issue can no longer be reproduced since the attached data pack download link no longer exists. Please provide a datapack that can reproduce the issue and I will reopen. I also think this is still likely a duplicate of https://github.com/GeyserMC/Geyser/issues/1938 and the data pack may just be doing some item frame spawning for some reason.

**Closed by Kas-tle** 2024-03-17 05:39 UTC
Labels: Confirmed Bug, Missing Client Feature
