### ISSUE TITLE
Inventory Bug for Bedrock Users. 

### ISSUE THREAD

**Issue by JoshuaPHYT** [GeyserMC/Geyser#2228] opened 2021-05-26 14:47 UTC
### Describe the bug

Well the Inventory on Java is really different on Bedrock since Java using Mouse and Keyboard..

But yeah. if you are moving a item on your inventory or on crafting table, anvil, and more handeling Inventory thing..

Here is the video to understand more 

### To Reproduce

on my video 

### Expected behaviour

Hopefully there is possible to bring Inventory of Bedrock to Java Server using Geyser. since its really hard to move items. 

### Screenshots / Videos

https://user-images.githubusercontent.com/69298936/119680775-10aa1d80-be74-11eb-8ff2-3f1188d42557.mp4

https://user-images.githubusercontent.com/69298936/119680793-143da480-be74-11eb-81ef-19ce221effc3.mp4

https://user-images.githubusercontent.com/69298936/119680820-19025880-be74-11eb-8131-34a502c31b87.mp4

### Server Version and Plugins

i try to use all Version.. Spigot, Paper, purpur and other java software. I dont have any plugins. 

### Geyser Dump

https://dump.geysermc.org/kvRjpJxEJ6ROXIgxDstxjzx6JGAMG7tg

### Geyser Version

"1.3.0-SNAPSHOT (git-floodgate-2.0-5c76bd8)", 

### Minecraft: Bedrock Edition Version

1.16.221

**Comment by Konicai** [comment] 2021-05-26 15:13
1. "Latest" isn't a version
2. Please run `geyser dump` in console and provide the link it gives you here

**Comment by JoshuaPHYT** [comment] 2021-05-26 15:20
Edited. Thanks!

**Comment by zOIDAdaJulian** [comment] 2021-06-15 16:42
Hey, I can confirm that problem too from my side.
I also noticed, that since the update on the 1.17(Client) some Items are other than on java.
For example ther nether_brick item looks like this on java: https://gyazo.com/239cc9d363a6d9cab7871def84d95b15
But it looks like this on PE: https://gyazo.com/3ddfdf93be86feee333f0da6d989d231
We also have problems with crafting, like in this video: https://imgur.com/a/f2viEhk
Maybe this helps to fix the problem ^^

**Comment by Camotoy** [comment] 2021-06-15 17:03
The nether brick issue should be fixed in the next build.

**Comment by Jens-Co** [comment] 2021-07-21 06:12
Hello there, does this issue still persist on the latest geyser version ? Otherwise I'll test this one myself.

**Comment by Konicai** [comment] 2021-11-27 23:48
Closing this as we haven't had any response

**Closed by Konicai** 2021-11-27 23:48 UTC
