### ISSUE TITLE
Geyser casuing server crash after adding mods

### ISSUE THREAD

**Issue by ExpertNugget** [GeyserMC/Geyser#4511] opened 2024-03-20 18:41 UTC
### Describe the bug

not entirely sure why, but now geyser causes a crash on startup, might be from via version possibly

### To Reproduce

launch with my mod list

### Expected behaviour

it to launch and not crash heh

### Screenshots / Videos

[latest.log](https://github.com/GeyserMC/Geyser/files/14671100/latest.log)

### Server Version and Plugins

- [Styled Player List](https://modrinth.com/mod/DQIfKUHf) [3.3.0+1.20.3]
- [YUNG's Better Ocean Monuments](https://modrinth.com/mod/3dT9sgt4) [1.20.4-Fabric-3.4.1]
- [Terralith](https://modrinth.com/mod/8oi3bsk5) [2.4.11]
- [YUNG's Better Nether Fortresses](https://modrinth.com/mod/Z2mXHnxP) [1.20.4-Fabric-2.4.2]
- [Trinkets](https://modrinth.com/mod/G8hlgtEk) [3.8.0+polymerport.2]
- [Styled Chat](https://modrinth.com/mod/doqSKB0e) [2.4.0+1.20.3]
- [PolyFactory](https://modrinth.com/mod/MikpSrAF) [0.3.4+1.20.4]
- [YUNG's Better Witch Huts](https://modrinth.com/mod/t5FRdP87) [1.20.4-Fabric-3.4.1]
- [Fabric Language Kotlin](https://modrinth.com/mod/Ha28R6CL) [1.10.19+kotlin.1.9.23]
- [KleeSlabs](https://modrinth.com/mod/7uh75ruZ) [16.0.1]
- [Starlight](https://modrinth.com/mod/H8CaAYZC) [1.1.3+fabric.f5dcd1a]
- [Simple Voice Chat](https://modrinth.com/mod/9eGKb6K1) [1.20.4-2.5.9]
- [More Tools (Polymer)](https://modrinth.com/mod/S6P4vaGq) [1.0.0]
- [YUNG's Better Dungeons](https://modrinth.com/mod/o1C1Dkj5) [1.20.4-Fabric-4.4.1]
- [Polymer](https://modrinth.com/mod/xGdtZczs) [0.7.6+1.20.4]
- [Voice Chat Interaction](https://modrinth.com/mod/qsSP2ZZ0) [1.20.4-1.0.6]
- [Illager Expansion Recrafted](https://modrinth.com/mod/zkp424MG) [1.1.0]
- [YUNG's Better Jungle Temples](https://modrinth.com/mod/z9Ve58Ih) [1.20.4-Fabric-2.4.1]
- [Get It Together, Drops!](https://modrinth.com/mod/T0OUgf8P) [fabric-1.20-1.3.1]
- [JamLib](https://modrinth.com/mod/IYY9Siz8) [1.0.6+1.20.4]
- [Polysit](https://modrinth.com/mod/G9eJHDO2) [0.5.3+mc.1.20.1]
- [Right Click Harvest](https://modrinth.com/mod/Cnejf5xM) [4.1.4+1.20.4]
- [Styled Sidebars](https://modrinth.com/mod/3iuae0OP) [1.3.0+1.20.3]
- [Concurrent Chunk Management Engine](https://modrinth.com/mod/VSNURh3q) [0.2.0+alpha.11.58]
- [Simple Discord Link](https://modrinth.com/mod/Sh0YauEf) [3.0.1]
- [Collective](https://modrinth.com/mod/e0M1UDsY) [7.40]
- [spark](https://modrinth.com/mod/l6YH9Als) [1.10.58]
- [Floodgate-Fabric](https://modrinth.com/mod/bWrNNfkb) [2.2.0-SNAPSHOT]
- [Balm](https://modrinth.com/mod/MBAkmtvl) [9.0.6]
- [CraterLib](https://modrinth.com/mod/Nn8Wasaq) [1.1.0]
- [Improved Signs](https://modrinth.com/mod/tEcCNQe7) [1.3.3]
- [YUNG's Extras](https://modrinth.com/mod/ZYgyPyfq) [1.20.4-Fabric-4.4.0]
- [BlueMap](https://modrinth.com/mod/swbUV1cr) [3.20]
- [Bigger Better End Cities](https://modrinth.com/mod/A1ySbDYD) [1.20.4-1.0.4]
- [ViaBackwards](https://modrinth.com/mod/NpvuJQoq) [4.9.3-SNAPSHOT]
- [ViaVersion](https://modrinth.com/mod/P1OZGk5p) [4.9.4-SNAPSHOT]
- [Geyser-Fabric](https://modrinth.com/mod/wKkoqHrH) [2.2.2-SNAPSHOT]
- [Fabric API](https://modrinth.com/mod/P7dR8mSH) [0.96.11+1.20.4]
- [Universal Graves](https://modrinth.com/mod/yn9u3ypm) [3.2.1+1.20.3]
- [ViaFabric](https://modrinth.com/mod/YlKdE5VK) [0.4.13+64-main]
- [PolyDecorations](https://modrinth.com/mod/5710VC7f) [0.2.2+1.20.4]
- [Sensible Sleepiness](https://modrinth.com/mod/R0CH8YWl) [0.0.1-1.20+]
- [True Ending: Ender Dragon Overhaul](https://modrinth.com/mod/MCnBYP0b) [1-v1.1.0c]
- [Cloth Config v13](https://modrinth.com/mod/9s6osm5g) [13.0.121]
- [ChoiceTheorem's Overhauled Village](https://modrinth.com/mod/fgmhI8kH) [3.4.2]
- [YUNG's Better Mineshafts](https://modrinth.com/mod/HjmxVlSr) [1.20.4-Fabric-4.4.1]
- [Tree Harvester](https://modrinth.com/mod/abooMhox) [8.7]
- [Lithostitched](https://modrinth.com/mod/XaDC71GB) [1.1.5]
- [YUNG's API](https://modrinth.com/mod/Ua7DFN59) [1.20.4-Fabric-4.4.2]
- [FastBack](https://modrinth.com/mod/ZHKrK8Rp) [0.17.0+1.20.4-fabric]
- [ViaRewind](https://modrinth.com/mod/TbHIxhx5) [3.0.7-SNAPSHOT]
- [YUNG's Better End Island](https://modrinth.com/mod/2BwBOmBQ) [1.20.4-Fabric-2.4.1]
- [Very Many Players](https://modrinth.com/mod/wnEe9KBa) [0.2.0+beta.7.138]
- [YUNG's Better Strongholds](https://modrinth.com/mod/kidLKymU) [1.20.4-Fabric-4.4.1]
- [Get Off My Lawn ReServed](https://modrinth.com/mod/j5niDupl) [`1.11.0`+1.20.3-rc1]
- [Polydex](https://modrinth.com/mod/m5NB7FJE) [1.0.1+1.20.4]
- [YUNG's Better Desert Temples](https://modrinth.com/mod/XNlO7sBv) [1.20.4-Fabric-3.4.1]
- [Architectury](https://modrinth.com/mod/lhGA9TYQ) [11.1.17]
- [Lithium](https://modrinth.com/mod/gvQqBUqZ) [0.12.1]
- [View Distance Fix](https://modrinth.com/mod/nxrXbh5K) [1.20.4-1.0.2]
- [Monsters in the Closet](https://modrinth.com/mod/GMA8jFBD) [1.0.3+1.20]

### Geyser Dump

N/A

### Geyser Version

2.2.2-SNAPSHOT

**Comment by onebeastchris** [comment] 2024-03-20 19:17
Seems like this is caused by us including yaml 1.33, which is the version used by `com_fasterxml_jackson_dataformat_jackson-dataformat-yaml 2.14.0`. ViaFabric is including a newer yaml version (2.2), which is likely what's causing the issue here - marking as confirmed bug.
For now, you can use an older version of Geyser which you can download under the `artifacts` tab here: https://github.com/GeyserMC/Geyser/pull/4495/checks

**Comment by onebeastchris** [comment] 2024-03-20 21:03
Could you test the linked PR and see if that resolves the issue?
You can download it from the `Checks` tab.

**Comment by ExpertNugget** [comment] 2024-03-21 07:12
Yup looks like this checks version fixed the issue

**Closed** 2024-03-21 18:05 UTC
Labels: Confirmed Bug
