### ISSUE TITLE
shift crafting kicks you for send too many packets

### ISSUE THREAD

**Issue by pranshuthegamer** [GeyserMC/Geyser#1953] opened 2021-02-19 04:50 UTC
**Describe the bug**

when you craft while pressing shift many times, the server kicks you for sending too many packets

**To Reproduce**

1.get something like bamboo or wood planks
2.try crafting sticks as fast as possible
3.see the kick message

**Expected behavior**

i expected the server to not kick me because java players dont get kicked

**Screenshots / Videos**

**Server Version and Plugins**

1.16.5 papermc

Harbor- sleep enhance plugin

**Geyser Dump**

im not a server admin

**Minecraft: Bedrock Edition Version**

1.16.200

**Comment by Camotoy** [comment] 2021-02-19 04:52
This is a duplicate of #1176. Regardless, thank you for reporting!

**Closed by Camotoy** 2021-02-19 04:52 UTC
