### ISSUE TITLE
Not able to use bukkit in mobile phone

### ISSUE THREAD

**Issue by Yuudachi-Kai2** [GeyserMC/Geyser#435] opened 2020-04-27 08:02 UTC
**Describe the bug**
when I try to use bukkit to place water or lava via mobile phone (my client version is 1.14.60)
in creative, the water will be placed and disappear instantly
in creativemode, the bukkit also become empty. 

**To Reproduce**
1. Use a mobile phone to connect the server
2. Take a water or lava bukkit 
3. Place it
4. And you will see it

**Expected behavior**
the water or lava be placed normally

**Server Version**
Paper version git-Paper-214 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Geyser Version**
Geyser-Bukkit version 1.0-SNAPSHOT

**Minecraft: Bedrock Edition Version**
1.14.60

**Additional Context**
if I try to connnect the server via windows 10 edition (download from microsoft store), the bukkit works normally.
this problem also be reported by some players of my server.

**Comment by RednedEpic** [comment] 2020-04-27 20:30
Duplicate of #321.

**Closed by RednedEpic** 2020-04-27 20:30 UTC
Labels: Duplicate
