### ISSUE TITLE
Players kicked from server when trying to join

### ISSUE THREAD

**Issue by Jim-m-y** [GeyserMC/Geyser#4934] opened 2024-08-05 04:29 UTC
### Describe the bug

basically every 2 out of 5 players who join get this kick message when trying to join "Tried joining as a java player. Is floodgate configured correctly?" 
Logs: https://mclo.gs/p9gKlYA

### To Reproduce

Log out and log in to the geyser server several times, (I think the kick message is much more likely to appear if you have a slightly slower connection than normal)

### Expected behaviour

kick error not coming out

### Screenshots / Videos

the kick message is shown in the logs

### Server Version and Plugins

This server is running Folia version 1.20.6-5-master@d797082 (2024-06-19T22:19:29Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)

CommandWhitelist, CoreProtect, DiscordSRV, EpicHomes, floodgate, Geyser-Spigot, LibertyBans, LuckPerms, PlaceholderAPI, PlayerKits2, ProtectionStones, SkinsRestorer, *Spawn, TAB, Tebex, TPA, ViaBackwards, ViaVersion, WorldEdit, WorldGuard

### Geyser Dump

https://dump.geysermc.org/LnzYYkvgXcOcpTcSPFkEzqwmeYMDuZnb

### Geyser Version

Geyser versión 2.4.1-b633 (git-master-3d7e62a)

### Minecraft: Bedrock Edition Device/Version

All versión, all device

**Comment by onebeastchris** [comment] 2024-08-06 11:58
Duplicate of https://github.com/GeyserMC/Geyser/issues/4403

**Closed** 2024-08-06 11:59 UTC
Labels: Duplicate
