### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by Iness92i** [GeyserMC/Geyser#4795] opened 2024-06-23 15:15 UTC
### Describe the bug

1/4 bedrock players gets kicked the error message is: Tried to log in as a Java Edition player! Is Floodgate set up correctly? [Geyser-Spigot] Cannot reply to ClientboundHelloPacket without profile and access token.

### To Reproduce

Join multiple times

### Server Version and Plugins

papermc (1.21) plugins: geyser+floodgate thats all

### Geyser Dump

https://dump.geysermc.org/zEh2tAzlEsiRQPycRLWbqV11duxvaTrE

### Geyser Version

2.4.0-SNAPSHOT (git-master-2e6cf2f)

### Minecraft: Bedrock Edition Device/Version

1.20.1.1 (Minecraft for windows)

### Additional Context

[Server logs.txt](https://github.com/user-attachments/files/15945143/Server.logs.txt)

**Comment by onebeastchris** [comment] 2024-06-23 16:35
Closing as this is a duplicate of https://github.com/GeyserMC/Geyser/issues/4777. Thanks anyways for reporting!

**Closed by onebeastchris** 2024-06-23 16:35 UTC
