### ISSUE TITLE
Some problems with geyser

### ISSUE THREAD

**Issue by raksodnus61** [GeyserMC/Geyser#4033] opened 2023-08-04 18:27 UTC
### Describe the bug

All my plugins;
Bungee;
![resim](https://github.com/GeyserMC/Geyser/assets/82219658/7cc9c1b6-e575-4c99-a279-8dd2b35317be)

Server;
![resim](https://github.com/GeyserMC/Geyser/assets/82219658/ac871ad2-ed50-42a4-98b8-1b38cbc3571e)

I have latest plugins (I downloaded a moments ago all of them)
but me and my players getting that error

![resim](https://github.com/GeyserMC/Geyser/assets/82219658/b2fd717d-9e44-4724-bd01-5997b7e8118a)
it says "Disconnect" no console error no anything only get time out or kick

### To Reproduce

1. start server with 4 plugins
2. start Bungee with 3 plugins
3. join the server
4. wait 3 or 4 minutes
5. get kicked
6 Hurting myself

### Expected behaviour

JUST PLAYING MINECRAFT WITH MY FRIENDS
I NEED SUPPORT 1 HAVE SAME ERROR 2 WEEK
AND NO ONE CAN HELP ME

### Screenshots / Videos

![resim](https://github.com/GeyserMC/Geyser/assets/82219658/0e2ee798-d084-4503-8a3e-b9cbd6de093f)

![resim](https://github.com/GeyserMC/Geyser/assets/82219658/68271136-be05-4829-986a-ccc661888af8)

### Server Version and Plugins

Bungee Waterfall 
![resim](https://github.com/GeyserMC/Geyser/assets/82219658/abe80369-d450-4c99-a75e-59c11342d20b)

Spigot
![resim](https://github.com/GeyserMC/Geyser/assets/82219658/3732c6d9-9efb-43ab-a1b0-ae62766657f3)

### Geyser Dump

https://dump.geysermc.org/imH5nQpA9wtNdbsgaPgI434kwtoN0zma

### Geyser Version

Geyser-BungeeCord version 2.1.2-SNAPSHOT (fc9ee65)

### Minecraft: Bedrock Edition Device/Version

Server: 1.18.2 / MCPE: 1.20.12

### Additional Context

I need help PLEASE I am begging you

**Comment by raksodnus61** [comment] 2023-08-04 18:30
I don't wanna get Duplicate I want HELP

**Comment by onebeastchris** [comment] 2023-08-04 18:49
If you don't want to get more of your posts closed as duplicates, then don't create more posts about the same issue.

By the way, Kastle responded in your previous issue.. you haven't yet.
Furthermore, we are all volunteers here - there are currently more than 200 open issues/bugs/feature requests, going through them, updating Geyser, and fixing bugs takes up a lot of time. 

Closing, since this is a duplicate of #4031.

**Closed** 2023-08-04 18:49 UTC
