### ISSUE TITLE
[FR] BungeeCord IP forwarding protocol

### ISSUE THREAD

**Issue by JuniorJPDJ** [GeyserMC/Geyser#216] opened 2020-03-18 02:11 UTC
Hi guys,
First, thank you for amazing work!
What if you would implement bungeecord ip forwarding to provide original IP to java server?
It is very simple protocol adding original IP to host field in login packet, this needs to be available and enabled in server, therefore it would be nice to have toggle in config.
The protocol is very widely supported.

**Comment by RednedEpic** [comment] 2020-03-18 02:14
> Hi guys,
> First, thank you for amazing work!
> What if you would implement bungeecord ip forwarding to provide original IP to java server?
> It is very simple protocol adding original IP to host field in login packet, this needs to be available and enabled in server, therefore it would be nice to have toggle in config.
> The protocol is very widely supported.

This can be done with Floodgate. See the page on the wiki for how to set that up.

In the future, please follow the issue template and make sure that the issue you’re about to open hasn’t been created before. I mention this because this is a duplicate of #190.

**Closed by RednedEpic** 2020-03-18 02:14 UTC
Labels: Duplicate

**Comment by JuniorJPDJ** [comment] 2020-03-18 02:19
But it needs users to set up additional things and use your plugin. This plugin collides with some things I've implemented and also it doesn't work on sponge (as far as I know) and other engines not based on bukkit, Bungeecord IP forwarding is already widely supported.

**Comment by RednedEpic** [comment] 2020-03-18 02:20
> But it needs users to set up additional things and use your plugin. This plugin collides with some things I've implemented and also it doesn't work on sponge (as far as I know) and other engines not based on bukkit, Bungeecord IP forwarding is already widely supported.

You can use Floodgate on BungeeCord without problems. What exactly would it collide with?

**Comment by JuniorJPDJ** [comment] 2020-03-18 02:33
I've my very weird plugin playing with UUIDs.
So floodgate may be used as plugin for bungeecord, not only for bukkit?

**Comment by RednedEpic** [comment] 2020-03-18 02:33
> I've my very weird plugin playing with UUIDs.
> So floodgate may be used as plugin for bungeecord, not only for bukkit?

Yeah, and velocity too.
