### ISSUE TITLE
Nintendo Switch Bedrock players can't place signs properly

### ISSUE THREAD

**Issue by skyman478** [GeyserMC/Geyser#1590] opened 2020-11-24 18:51 UTC
When my NS players place signs and type something, the text is showed just for them and not for other players like java edition players.

Version that the bug was discovered: Geyser version 1.2.0-SNAPSHOT

**Comment by DoctorMacc** [comment] 2020-11-24 18:55
This is a duplicate of #1063. In the future, please follow the issue template! Thank you!

**Closed by DoctorMacc** 2020-11-24 18:55 UTC
