### ISSUE TITLE
Can't walk on non-full blocks properly

### ISSUE THREAD

**Issue by SinanGentoo** [GeyserMC/Geyser#566] opened 2020-05-15 16:07 UTC
**Describe the bug**
Cannot climb or walk on non-full blocks, This problem also appears on half bricks

**To Reproduce**

**Expected behavior**

Able to move normally

**Screenshots / Videos**

[Video](http://pan.hydrostic.com:5212/api/v3/file/get/5/2020_05_15_23_35_17.mp4?sign=_rFpxw0DOlVMFEh7CdxDqwDpmN5Xnu7UzIB5Xsmv47I%3D%3A0)
**Server Version**
Paper-257(MC:1.15.2)

**Geyser Version**

The latest master and feature/enity-mounts
**Minecraft: Bedrock Edition Version**

1.14.60
**Additional Context**

**Comment by RednedEpic** [comment] 2020-05-15 16:08
Duplicate of #204.

**Closed by RednedEpic** 2020-05-15 16:08 UTC
Labels: Duplicate

**Comment by Heath123** [comment] 2020-05-15 16:09
> 
> 
> Duplicate of #204.

But that's "Player can't move correctly when cord number is higher than 4096"

**Comment by RednedEpic** [comment] 2020-05-15 16:09
> > Duplicate of #204.
> 
> But that's "Player can't move correctly when cord number is higher than 4096"

Did you watch the video?

**Comment by SinanGentoo** [comment] 2020-05-15 16:10
umm...It also happened within 4096 coordinates

**Comment by RednedEpic** [comment] 2020-05-15 16:10
> umm...It also happened within 4096 coordinates

Could be anticheat.

**Comment by RanTDR** [comment] 2020-06-02 11:12
occurs on servers without anticheat

**Comment by Heath123** [comment] 2020-06-02 11:13
It happens with snow layers anywhere for example (will be fixed in #699)

**Comment by Heath123** [comment] 2020-06-02 11:14
I think either the issue name should be changed or we should stop closing issues about that as duplicates because there are definitely movement bugs still within 4096 range

**Comment by Heath123** [comment] 2020-06-02 11:14
Oh

**Comment by Heath123** [comment] 2020-06-02 11:14
I thought this was a different issue

**Comment by Heath123** [comment] 2020-06-02 11:15
Oh, it was closed
I'll delete most of these messages and edit the original because it's getting a bit spammy
