### ISSUE TITLE
Bedrock players get bugged when enter on the server and cant move

### ISSUE THREAD

**Issue by richardGonzalez-std** [GeyserMC/Geyser#4043] opened 2023-08-08 07:05 UTC
### Describe the bug

I installed Geyser and floodgate and just when i run the server and a bedrock player enter in the server it get bugged and cant move

### To Reproduce

1. Install geyser
2. install floodgate
3. reload the server
4. auth-mode: floodgate
5. run the server

### Expected behaviour

I expected to play on movile but i can play on the server

### Screenshots / Videos

https://github.com/GeyserMC/Geyser/assets/84289391/35278bae-8347-4ab3-a024-518ea0371dcc

https://dump.geysermc.org/AWx6xFmjz98YRCbeEik0lganRnXsIRIW

### Geyser Version

2.1.2-SNAPSHOT

**Comment by onebeastchris** [comment] 2023-08-08 10:40
Yup, as Elavalur said - nothing we can do about this.
Also duplicate of https://github.com/GeyserMC/Geyser/issues/3804, closing

**Closed by onebeastchris** 2023-08-08 10:40 UTC
