### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "org.cloudburstmc.netty.channel.raknet.packet.RakDatagramPacket.getNextSend()" because "datagram" is null

### ISSUE THREAD

**Issue by ximuya2** [GeyserMC/Geyser#4285] opened 2023-11-11 13:34 UTC
### Describe the bug

When I click on a block near the player's feet in Bedrock Edition, the player is forced to quit the game
————————————————————————————————————————————————————
Error while ticking RakSessionCodec state=CONNECTED channelActive=true
java.lang.NullPointerException: Cannot invoke "org.cloudburstmc.netty.channel.raknet.packet.RakDatagramPacket.getNextSend()" because "datagram" is null
    at org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.sendStaleDatagrams(RakSessionCodec.java:501)
    at org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.onTick(RakSessionCodec.java:436)
    at org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.tryTick(RakSessionCodec.java:381)
    at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
    at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:159)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:1589)

### To Reproduce

When I click on a block near the player's feet in Bedrock Edition, the player is forced to quit the game

### Expected behaviour

When I click on a block near the player's feet in Bedrock Edition, the player is forced to quit the game

### Screenshots / Videos

When I click on a block near the player's feet in Bedrock Edition, the player is forced to quit the game

### Server Version and Plugins

Paper1.20.2
Geyser-BungeeCord.jar

### Geyser Version

Latest

### Minecraft: Bedrock Edition Device/Version

all

**Comment by onebeastchris** [comment] 2023-11-11 14:15
please send a full latest.log file via mclo.gs

**Comment by ximuya2** [comment] 2023-11-15 14:39
> 请通过 mclo.gs 发送完整的最新.log文件

It only shows these messages in my Bungeecord console, actually I'm not sure if it's the Bungeecord or Geyser's problem, if you can help me out, I'd be very grateful

**Comment by ximuya2** [comment] 2023-11-15 14:40
> please send a full latest.log file via mclo.gs

It only shows these messages in my Bungeecord console, actually I'm not sure if it's the Bungeecord or Geyser's problem, if you can help me out, I'd be very grateful
————————————————————————————————————
[BE.WorldlyHat980] <-> DownstreamBridge <-> [e] - could not decode packet! io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: index: 3, length: 394 (expected: range(0, 12))

**Comment by onebeastchris** [comment] 2023-11-15 14:55
That's not a full log, please attach the complete log file and send it via one of the aforementioned site.
Additionally, please also send a geyser dump by running `/geyser dump` in the server console and sending the link here.

**Comment by ximuya2** [comment] 2023-11-15 15:06
https://dump.geysermc.org/aOf4td9BNJQcdheQclupllipNh1dmML6

> /geyser dump

**Comment by onebeastchris** [comment] 2023-12-20 22:50
sorry for the longer wait - can you update Geyser and see if the issue persists? We've updated our cloudburst dependencies, which might resolve the issue.

**Comment by ximuya2** [comment] 2023-12-23 13:28
thanks

**Comment by yululiYT** [comment] 2024-01-20 14:53
Similar problems were identified in paper1.20.1.
We did not use BungeeCord etc. and put it in PAPER.

[23:50:00 ERROR]: [org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec] [/IP:Port] Error while ticking RakSessionCodec state=CONNECTED channelActive=true
java.lang.NullPointerException: Cannot invoke "org.cloudburstmc.netty.channel.raknet.packet.RakDatagramPacket.getNextSend()" because "datagram" is null
        at org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.sendStaleDatagrams(RakSessionCodec.java:522) ~[Geyser-Paper.jar:?]
        at org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.internalFlush(RakSessionCodec.java:457) ~[Geyser-Paper.jar:?]
        at org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.onTick(RakSessionCodec.java:420) ~[Geyser-Paper.jar:?]
        at org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.tryTick(RakSessionCodec.java:392) ~[Geyser-Paper.jar:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:159) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406) ~[netty-transport-classes-epoll-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by onebeastchris** [comment] 2024-01-20 15:05
It's an issue of the bedrock network library we use (https://github.com/CloudburstMC/Network) - we've not been able to narrow down this bug to this day. If you can find a way to consistently reproduce it, please let us know

**Comment by onebeastchris** [comment] 2024-07-14 17:30
Given that this error is only *occasionally* occurrs *after* a player disconnects, and because there are currently no known reliable reproduction steps, ill close this issue. If this still occurs, please create a new issue with reproduction steps.

**Closed by onebeastchris** 2024-07-14 17:30 UTC
Labels: Unconfirmed Bug/Not Currently Replicable
