### ISSUE TITLE
Water & Lava

### ISSUE THREAD

**Issue by tunikakeks** [GeyserMC/Geyser#704] opened 2020-05-30 20:37 UTC
Can't place water or Lava. Please fix it. Thanks!

**Comment by DoctorMacc** [comment] 2020-05-30 20:38
Closing because it's a duplicate of #321.

**Comment by RednedEpic** [comment] 2020-05-30 20:38
Please follow the issue template in future issues.

**Closed by DoctorMacc** 2020-05-30 20:38 UTC

**Comment by E404NNF** [comment] 2020-05-30 20:39
use the template when creating an issue next time please
