### ISSUE TITLE
Compatibility issues with multiple NIC device

### ISSUE THREAD

**Issue by 90257550** [GeyserMC/Geyser#4647] opened 2024-05-07 16:07 UTC
### Describe the bug

If a server with more than one network interface uses geyser，There will be a situation where the link cannot be established

### To Reproduce

1 My server has public IP on both lines.(IPv4）
2 Use geyser
3 One line can be used, but the other is always not available.
4 I can only block the IPv4 function of one network card

### Expected behaviour

Both network lines can be used

### Server Version and Plugins

geyser Stand-alone version

### Geyser Version

It was downloaded from the website about four hours ago.

### Minecraft: Bedrock Edition Device/Version

1.20.2 spioght

**Comment by 90257550** [comment] 2024-05-08 02:16
In addition, the Java version can use two lines normally.

**Comment by onebeastchris** [comment] 2024-05-10 23:45
https://github.com/GeyserMC/Geyser/issues/3547
This isn't a feature Geyser currently supports - if you want to bind to multiple listeners, you'll currently need to set up multiple Geyser instances. Or, if it's about ipv4/ipv6, binding to the `::` wildcard seems to work. Going to close this as a duplicate of the linked issue - thanks anyways for reporting.

**Closed by onebeastchris** 2024-05-10 23:45 UTC

**Comment by 90257550** [comment] 2024-05-11 00:22
> #3547 这不是 Geyser 目前支持的功能 - 如果你想绑定到多个监听器，你目前需要设置多个 Geyser 实例。或者，如果它是关于 ipv4/ipv6 的，绑定到通配符似乎可以工作。将关闭它作为链接问题的副本 - 无论如何感谢您的报告。`::`

Thank you, at least let me know that this is not feasible at present, I can not continue to waste time to try this, I hope geyser support this demand soon, even if very few people need it.
