### ISSUE TITLE
Wooden CARDS and floating characters cannot be displayed properly

### ISSUE THREAD

**Issue by pbs666** [GeyserMC/Geyser#701] opened 2020-05-30 14:21 UTC
Bedrock edition players cannot see wooden signs, or sometimes floating characters
I think maybe it's because I forgot to refresh the wooden board and float the empty characters. Maybe it's an oversight?
hope it will be fixed soon...

**Comment by RednedEpic** [comment] 2020-05-30 14:23
> Bedrock edition players cannot see wooden signs, or sometimes floating characters
> I think maybe it's because I forgot to refresh the wooden board and float the empty characters. Maybe it's an oversight?
> hope it will be fixed soon...

Please follow the issue template. This is also likely a duplicate of #603 but we need more information (see issue template).

**Comment by RednedEpic** [comment] 2020-05-30 22:29
Closing for the time being as this seems likely to be a duplicate of #603. If this is not the case, please provide more information about your problem.

**Closed by RednedEpic** 2020-05-30 22:29 UTC
Labels: Duplicate
