### ISSUE TITLE
Biome-dependent gradients not present on Bedrock client

### ISSUE THREAD

**Issue by ExecuteOrd66** [GeyserMC/Geyser#3940] opened 2023-07-05 12:07 UTC
### Describe the bug

1. I use a datapack called Terralith which alters the world generation. In particular to this thread, it changes the gradients for various types of grasses and leaves in its custom biomes. These colours are displayed correctly on the Java client (as expected), but are not represented in that way in Bedrock. 

### To Reproduce

1. Generate a world with the Terralith datapack enabled
2. Locate a biome that alters the colour of foliage (the Amethyst rainforest will likely have the most stark difference in this regard). This can be accomplished with the _/locate biome terralith:amethyst_rainforest_ command
3. Compare Java and Bedrock representations

### Expected behaviour

Bedrock colours should match that of Java

### Screenshots / Videos

Here is a screenshot of spawn on my server in Bedrock (left) and Java (right). As can be seen, the autum colours of the leaves do not appear on the Bedrock client as they do in Java.
![image](https://github.com/GeyserMC/Geyser/assets/57319507/01bf04eb-be4e-4e2c-94b6-c71fc3fa7eb4)

### Server Version and Plugins

Minecraft version: 1.20.1
Server backend: Fabric Loader 0.14.21
Mods: Geyser, Floodgate

### Geyser Dump

https://dump.geysermc.org/F4wInBliV7WjSe6FRk2GTyBZVqFiKw0Z

### Geyser Version

212-SNAPSHOT-222

### Minecraft: Bedrock Edition Device/Version

Minecraft Windows 10 Edition

**Comment by onebeastchris** [comment] 2023-07-05 12:28
Duplicate of https://github.com/GeyserMC/Geyser/issues/3645 - as for whether this can be implemented is tough to say since Bedrock (to my knowledge) has no such for custom leaf/biome colors.

**Closed** 2023-07-05 12:28 UTC
Labels: Duplicate
