### ISSUE TITLE
Bedrock Generating World Screen Stuck After Death

### ISSUE THREAD

**Issue by bubbakadriu** [GeyserMC/Geyser#3485] opened 2022-12-31 13:39 UTC
### Describe the bug

So when players die, it doesnt happen every time but they get stuck on a screen saying “Generating World”. I find that this happens ONLY when in minigames, so things like Skywars, KitPvP, Party Games, Bedwars ect. I notice it happens more when players die from falling at a height. 

Only way to resolve this issue is to /kill the player and then they respawn fine.

### To Reproduce

Install a minigame plugin

Join a game in that plugin, for example join the bedwars lobby and start the game

Jump into the void or fall from a high height (100 block)

Keep doing this or getting someone to kill you, its likely you will get stuck on the screen. 

### Expected behaviour

Players should not get a screen saying generating world

### Screenshots / Videos

![4E3108B3-CD36-4E04-9CB7-A56135B31BB0](https://user-images.githubusercontent.com/38432044/210138541-1a13acbb-42fc-4c55-87bf-330a1636122c.png)
![691455DC-DE18-4A79-9F42-66B240FC1461](https://user-images.githubusercontent.com/38432044/210138554-deafff59-ad35-4747-b657-a006eb492286.png)
![1D21DC6A-961B-4CF2-A40B-78252D5FBB35](https://user-images.githubusercontent.com/38432044/210138558-4e850d01-608d-4c04-a426-1e48d9e28745.png)

### Server Version and Plugins

![39D42341-4EA4-4B04-AC58-63F712085760](https://user-images.githubusercontent.com/38432044/210138636-4a789296-f0ae-4392-b5f3-c56b5272d052.jpeg)
![87A49BFB-763E-4D78-9B95-26F0E14EB9C8](https://user-images.githubusercontent.com/38432044/210138654-68d741c3-f5a2-49da-bc1a-132bc8264137.jpeg)

### Geyser Dump

https://dump.geysermc.org/aF8fCO5KiwwPiOcU8Xq1Ezd4ZXL1jcWt

### Geyser Version

2.1.0 SNAPSHOT (git-master-03390b 9) (Java: 1.19.3, Bedrock: 1.19.20 - 1.19.50 /1.19.51)

### Minecraft: Bedrock Edition Device/Version

All Bedrock Clients

**Comment by onebeastchris** [comment] 2022-12-31 13:41
Could you link a few of the minigame plugins you've tried? It'll help us pin down the issue quicker ^^

**Comment by bubbakadriu** [comment] 2022-12-31 13:44
Arcade: https://www.spigotmc.org/resources/➢-arcade-minigames.49093/

Hide&Seek: https://www.spigotmc.org/resources/hideandseek.9777/

Party Games: https://www.spigotmc.org/resources/♛-party-games-x-♛-23-minigames-parties-spleef-quake-tntrun-tons-more.83240/

Bedwars: https://www.spigotmc.org/resources/➢-bedwars-clashwars-minigame.51340/

**Comment by bubbakadriu** [comment] 2022-12-31 13:44
Same issue on every plugin above

**Comment by onebeastchris** [comment] 2022-12-31 13:46
It's likely connected to Geyser, as it only affects bedrock players, so that's correct - thanks for providing exact plugin links!

**Comment by Kas-tle** [comment] 2022-12-31 15:32
Given these are all paid plugins, its unlikely that someone here is going to buy the plugin to reproduce it. I would recommend trying to find a free and open source plugin that you can reproduce this on.

**Comment by bubbakadriu** [comment] 2022-12-31 15:34
https://www.spigotmc.org/resources/skywarsreloaded-updated-recoded-1-19-support-new-features-1-8x-1-19x.69436/ Try this one

**Comment by onebeastchris** [comment] 2023-06-11 01:37
Duplicate of https://github.com/GeyserMC/Geyser/issues/3048; thanks for the reproduction plugin. Will link to that in the other post for when someone might try and fix this

**Closed by onebeastchris** 2023-06-11 01:37 UTC

**Comment by bubbakadriu** [comment] 2023-06-11 07:13
Can be reproduced on this duel plugin also

https://www.spigotmc.org/resources/duels.20171/
