### ISSUE TITLE
Issues with GUI/chest inventory

### ISSUE THREAD

**Issue by ItzCookies** [GeyserMC/Geyser#410] opened 2020-04-23 10:12 UTC
**Describe the bug**
As the name of the issue describes

**To Reproduce**
1. Install AuctionHouse plugin
2. Buy an auctioned item
3. The confirmation menu will be modifiable.
**Expected behavior**

**Screenshots / Videos**

https://youtu.be/9Ty0ougJ4os

**Server Version**
Paper 185

**Geyser Version**
1.0 SNAPSHOT, Inventory branch.

**Minecraft: Bedrock Edition Version**
1.14.60

**Additional Context**
This could be because there were 2 menus. (1st menu was catalog, 2nd menu was confirmation)

**Comment by ItzCookies** [comment] 2020-04-23 10:13
Expected behaviour:
Allow purchase, close menu.

**Comment by TheMasterBlaster** [comment] 2020-04-23 10:32
I can confirm, seems to happen with most if not all Inventory GUIs after the first or second click.

**Comment by RednedEpic** [comment] 2020-04-26 05:19
Duplicate of #211.

**Closed by RednedEpic** 2020-04-26 05:19 UTC
Labels: Duplicate
