### ISSUE TITLE
[Geyser-Spigot] Could not find an entity definition with type BLOCK_DISPLAY

### ISSUE THREAD

**Issue by xPOLT3RG3ISTx** [GeyserMC/Geyser#4026] opened 2023-08-01 03:19 UTC
### Describe the bug

It keeps coming in my command panel. Not sure why. 

### To Reproduce

Restart my server it happens and frequent as running

### Expected behaviour

Not to see that

### Screenshots / Videos

![Screenshot 2023-07-31 231732](https://github.com/GeyserMC/Geyser/assets/139196236/70421e93-65d8-4ef3-b14f-3bd9f2d837ad)

### Server Version and Plugins

1.20.1

### Geyser Dump

https://dump.geysermc.org/HlB52Hbb4PUEGt9HU80QFUnKj8Fj8Qmy

### Geyser Version

Spigot/Paper/Purpur

### Minecraft: Bedrock Edition Device/Version

JAVA/Bedrock Server

**Comment by Konicai** [comment] 2023-08-01 03:30
duplicate of #3810

**Closed by Konicai** 2023-08-01 03:30 UTC
