### ISSUE TITLE
Netherbrick and Nether Bricks 

### ISSUE THREAD

**Issue by abc13131412** [GeyserMC/Geyser#986] opened 2020-07-20 10:32 UTC
**Describe the bug**

（My English is poor,and I used google translation,sorry about this~)
In be What you burned out looks like netherblocks, but in fact his data is netherbricks. Please fix it. It will bring players "Why can't I create"'sproblem
**To Reproduce**

Burning Nether Rock

**Expected behavior**

data error
**Screenshots / Videos**

**Server Version**

Paper version git-paper-80(mc:1.16.1)(Implementing API version 1.16.1-R0.1-SNAPSHOT)
**Geyser Version**

1.0.0(git-master-64d5390)
**Minecraft: Bedrock Edition Version**

1.16.0
**Additional Context**

https://dump.geysermc.org/R1UBDqK4E7wB85puXlvR2I9kCQXZzPgi

**Comment by rtm516** [comment] 2020-07-20 10:33
Thanks for the report but this is a duplicate of https://github.com/GeyserMC/Geyser/issues/972 and we are working on a fix.

**Closed by rtm516** 2020-07-20 10:33 UTC
