### ISSUE TITLE
"/scoreboard objectives setdisplay sidebar.team.<color> [team name]" doesn't work as intended on bedrock

### ISSUE THREAD

**Issue by HaveSomeRubicon** [GeyserMC/Geyser#3181] opened 2022-07-28 20:20 UTC
### Describe the bug

The "/scoreboard objectives setdisplay sidebar.team.<color> [team name]" command is very glitchy on bedrock.
If a player logs in without the same team colour as what the objectives setdisplay was assigned then will not see the scoreboard as intended.
If that player joins the same team colour as what the objectives was set to then they can see the scoreboard.
However if the player leaves and joins a team that should not be able to see the scoreboard they are still able to see the scoreboard.
They can continue to join different teams and they will still be able to see the scoreboard regardless of what the objectives team color was set to.

### To Reproduce

1. Run "/scoreboard objectives setdisplay sidebar.team.<colour> [team name]"
2. Join a team with the colour you assigned the set display to
3. Join a team that shouldn't be able to see the scoreboard

### Expected behaviour

The player should no be able to see the scoreboard if they are on a team with the wrong colour

### Server Version and Plugins

This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)

DiscordSRV-Build-1.25.1.jar
floodgate-spigot.jar
Geyser-Spigot.jar
Multiverse-Core-4.3.1.jar
Multiverse-Inventories-4.2.3.jar
SnowballDamage.jar
worldedit-bukkit-7.2.11-beta-01.jar

### Geyser Dump

https://dump.geysermc.org/3C59iIipqWbrECe4Tk504Et3HljfIR4R

### Geyser Version

This server is running Geyser version 2.0.5-SNAPSHOT (git-master-f4a5ccb) (Java: 1.19, Bedrock: 1.19.0/1.19.2 - 1.19.10)

### Minecraft: Bedrock Edition Device/Version

1.19.2, android

**Comment by Kas-tle** [comment] 2024-03-19 05:39
Hello, could you confirm that this is still an issue on the latest Geyser build and update your reproduction steps to include an exact list of all commands required to reproduce this issue?

**Comment by onebeastchris** [comment] 2024-06-06 17:19
Closing due to no further response. If this issue still occurs, please comment here with updated reproduction steps. Thanks!

**Closed by onebeastchris** 2024-06-06 17:19 UTC
Labels: Waiting On Response

**Comment by HaveSomeRubicon** [comment] 2024-06-06 20:42
I'm really sorry but its been 2 years and i have moved past this game and no longer play it thus i am unable to test further
