### ISSUE TITLE
[Geyser-Spigot] Downstream pack et error! readerIndex(25) + length(1) exceeds wr iterIndex(25): PooledUnsafeDirectByteBuf(ridx: 2  5, widx: 25, cap: 25)

### ISSUE THREAD

**Issue by NotViper** [GeyserMC/Geyser#4669] opened 2024-05-17 06:41 UTC
### Describe the bug

Bedrock Client Cannot Join My Server except Java Client

### To Reproduce

I don't know

### Expected behaviour

I don't know

### Screenshots / Videos

![Screenshot_2024-05-17-14-33-07-77_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/GeyserMC/Geyser/assets/92613023/057c40be-a8d1-4e80-bd02-13bf969df792)

### Server Version and Plugins

Server: 1.20.4

### Geyser Dump

https://dump.geysermc.org/YO7kRhmjp2Rj7Wo7Bp7Y6gYjr9LYdmRR

### Geyser Version

2.3.1 SNAPSHOT (git-master-4d61766)

### Minecraft: Bedrock Edition Device/Version

1.20.73

**Comment by onebeastchris** [comment] 2024-06-13 16:17
Closing due to no further response - this is likely caused by an outdated Geyser/ViaVersion build.

**Closed by onebeastchris** 2024-06-13 16:17 UTC
Labels: More Info Needed, Unconfirmed Bug/Not Currently Replicable, Waiting On Response
