### ISSUE TITLE
enable-proxy-protocol - the option does not work correctly

### ISSUE THREAD

**Issue by lootoos** [GeyserMC/Geyser#3231] opened 2022-08-13 03:52 UTC
### Describe the bug

when this option is enabled, when trying to log in to the server writes: couldn't connect to the world.
is the server visible? yes the server shows online 0 out of 100.

### To Reproduce

1. enable option: proxy-protocol in Geyser-Spigot>config.yml(https://pastebin.com/1H5MMEBA)
2. configure nginx as HAProxy (https://ibb.co/Bf4DcyL)
3. go to the game menu, make sure that it shows 0 out of 100 online, then try to log in to the server

### Expected behaviour

I expected to log in to the server, but he writes to me: couldn't connect to the world

### Server Version and Plugins

1.19.2, plugins:floodgate + geyserspigot.

### Geyser Dump

https://dump.geysermc.org/NHHfMWgkvWVukLK0DtYVOgWKLBSufvoA

### Geyser Version

Build #1175(https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/1175/)

### Minecraft: Bedrock Edition Device/Version

os android, game client bedrock version 1.19.20(Bedrock).

**Comment by lootoos** [comment] 2022-08-13 18:21
logs minecraft server:https://pastebin.com/6UxfuuGD

**Comment by Konicai** [comment] 2022-08-13 19:19
... duplicate of #3226? Why did you repost your own issue

**Closed by Konicai** 2022-08-13 19:19 UTC

**Comment by lootoos** [comment] 2022-08-13 19:21
in order to get an answer faster why is this happening

**Comment by Konicai** [comment] 2022-08-13 19:25
No. You just need to wait and be patient.
