### ISSUE TITLE
Add Debug Screen on Bedrock

### ISSUE THREAD

**Issue by S0M0G** [GeyserMC/Geyser#2541] opened 2021-09-21 23:00 UTC
### What feature do you want to see added?

I would like to have a debug screen on Bedrock. Just so that you can see which biome you are in our like where the chunk borders are.

### Are there any alternatives?

There are no alternatives

**Comment by Camotoy** [comment] 2021-09-21 23:03
Duplicate of https://github.com/GeyserMC/GeyserOptionalPack/issues/15. Thanks anyway!

**Closed by Camotoy** 2021-09-21 23:03 UTC
Labels: Feature Request
