### ISSUE TITLE
Broken Bamboo

### ISSUE THREAD

**Issue by Giggybluf** [GeyserMC/Geyser#2369] opened 2021-07-11 16:52 UTC
### Describe the bug

Whenever a player gets close to grown bamboo (the stick and not the plant) the game teleports him back a block before the bamboo, and sometimes crashes the whole server especially when a player gets close to a bamboo forest/jungle.
it is like the game is considering the bamboo as a full block and does not let us walk through it.

### To Reproduce

1. plant bamboo 
2. grow with bone meal
3. walk into it

### Expected behaviour

the player gets teleported back to a block before the bamboo and/or crashes the server.

### Screenshots / Videos

Uploading Rewriters bug 2.mp4…

### Server Version and Plugins

paper 1.17.1

No plugins other than 
floodgate v2.0-SNAPSHOT
and
Geyser-Spigot v1.4.0-SNAPSHOT

### Geyser Version

Geyser-Spigot v1.4.0-SNAPSHOT

**Comment by Chew** [comment] 2021-07-11 16:54
This is documented as known on our limitations page. In the future, we may have an official way to fix this, but for now, if you want a hacky solution: [Camotoy/BambooCollisionFix](https://github.com/Camotoy/BambooCollisionFix)

Thank you anyway!

Also a duplicate of a few other issues.

**Closed by Chew** 2021-07-11 16:54 UTC
