### ISSUE TITLE
[Geyser-Spigot] GAman19993700 has been kicked for trying to log in as a Java edition player! Is Floodgate set up correctly? Disconnected from the Java server.

### ISSUE THREAD

**Issue by chenshupe** [GeyserMC/Geyser#5003] opened 2024-08-28 04:24 UTC
### Describe the bug

Players using the Bedrock edition often get kicked with the message 'Attempting to log in as a Java edition player! Is Floodgate set up correctly?' when they join the server, and then get disconnected from the Java server. However, they can rejoin and enter the server normally. Moreover, this prompt does not trigger 100% of the time, but it appears very frequently.

### To Reproduce

1.Bedrock edition players join the server.
2.Then there is a chance that this prompt will appear.

### Expected behaviour

I hope this issue can be resolved.

### Screenshots / Videos

![QQ20240828-122226](https://github.com/user-attachments/assets/da9e4bd9-59eb-4786-a313-d65766cce015)

### Server Version and Plugins

This server is running Leaf version 1.21.1-DEV-ver/1.21.1@539b8b3 (2024-08-20T17:17:06Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
此服务器正在运行 Geyser 版本 2.4.2-b654 (git-master-2274377) (Java: 1.21, Bedrock: 1.20.80/1.20.81 - 1.21.20/1.21.21)

### Geyser Dump

https://dump.geysermc.org/WyPLOTMfwfl9EI4qXL7xI151DgJfRqnM

### Geyser Version

2.4.2-b654 (git-master-2274377)

### Minecraft: Bedrock Edition Device/Version

1.21.21

**Comment by onebeastchris** [comment] 2024-08-28 09:31
Duplicate of https://github.com/GeyserMC/Geyser/issues/4403

**Closed by onebeastchris** 2024-08-28 09:31 UTC
