### ISSUE TITLE
Cannot enchant books

### ISSUE THREAD

**Issue by zimzaza4** [GeyserMC/Geyser#1561] opened 2020-11-18 12:11 UTC
**Describe the bug**

Cannot enchant books
**To Reproduce**

Open the enchantment table

Put in books and lapis lazuli

Can't enchant
![Screenshot_20201118_200414_com mojang minecraftpe](https://user-images.githubusercontent.com/53421735/99528717-abafcf80-29d9-11eb-9857-e0d268527d3d.jpg)

**Expected behavior**

Books should be enchanted
**Screenshots / Videos**

**Server Version**

Paper-283 1.16.4
**Geyser Version**

480
**Minecraft: Bedrock Edition Version**

1.16.20
**Additional Context**

**Comment by DoctorMacc** [comment] 2020-12-01 02:33
Has this been fixed? (If you're in creative mode, the latest build should have fixed this; you will have to get new books)

**Comment by DoctorMacc** [comment] 2020-12-07 01:32
I'm going to assume you are in creative mode (seeing as you're holding an enchantment table). If the issue is not resolved with the latest Geyser build, please let us know!

**Closed by DoctorMacc** 2020-12-07 01:32 UTC
