### ISSUE TITLE
Impossible to merge swords on the anvil.

### ISSUE THREAD

**Issue by Brasil150** [GeyserMC/Geyser#4714] opened 2024-06-02 03:12 UTC
### Describe the bug

Merging enchanted swords does not work on Anvil. Trying to merge will cause nothing to happen.

### To Reproduce

1. Place sword 1 with charms on the anvil
2. Place sword 2 with charms on the anvil
3. Try to combine both.

### Expected behaviour

The swords blend together as they should.

### Screenshots / Videos

https://github.com/GeyserMC/Geyser/assets/55663598/6e70840e-01b2-40bf-8148-e34014572f78

### Server Version and Plugins

Waterfall #578
Pupur 1.20.4 git-Purpur-2176

### Geyser Version

Geyser 2.3.1-SNAPSHOT git-master-66f30a2

### Minecraft: Bedrock Edition Device/Version

1.20.81

### Additional Context

Tools such as shovel and pickaxe are not affected in this issue.

**Comment by onebeastchris** [comment] 2024-06-06 21:44
please run `paper dumpitem` while holding the sword that's affected , and send the output for both swords here
That'll help replicating the issue

**Comment by onebeastchris** [comment] 2024-07-04 14:40
Closing due to incomplete reproduction steps - further, i am unable to reproduce this issue. If this issue still occurs, please provide full replication steps, and if needed, mention the plugins that cause the misbehavior.

**Closed by onebeastchris** 2024-07-04 14:40 UTC
Labels: More Info Needed, Waiting On Response
