### ISSUE TITLE
java.lang.ClassCastException: class org.geysermc.geyser.inventory.PlayerInventory cannot be cast to class org.geysermc.geyser.inventory.Container 

### ISSUE THREAD

**Issue by DxrkCat** [GeyserMC/Geyser#4290] opened 2023-11-13 18:35 UTC
### Describe the bug

(velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)
adoptium java 21
https://paste.gg/p/anonymous/0cf74764a92641bf966b1c98ca22e3b4

### To Reproduce

Go to the server with Velocity that has Geyser-Velocity and floodgate installed. An important addition this does not happen all the time, but only sometimes some players come in they are fine. And some of them have such errors.

### Expected behaviour

idk

### Geyser Version

https://github.com/GeyserMC/Geyser/commit/f40ca2004e2828d40df368432399bebd681d3c4b

**Comment by onebeastchris** [comment] 2023-11-13 18:43
Duplicate of https://github.com/GeyserMC/Geyser/issues/4141 - thanks anyways.

**Closed by onebeastchris** 2023-11-13 18:43 UTC
