### ISSUE TITLE
Respawn crash

### ISSUE THREAD

**Issue by epserv** [GeyserMC/Geyser#1559] opened 2020-11-18 08:12 UTC
**Describe the bug**
Server freezes every time a bedrock player respawns

**To Reproduce**
1. die somehow
2. respawn
3. server froze

**Expected behavior**
everyone can respawn well

**Screenshots / Videos**
none

**Server Version**
This server is running Yatopia version git-Yatopia-"24b5188" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
Previous version: git-Yatopia-"feb1bdf" (MC: 1.16.3)

**Geyser Version**
На этом сервере Geyser версии 1.2.0-SNAPSHOT (git-feature/1.16.100-1a650ac) (Java: 1.16.4, Bedrock: 1.16.100.60)

**Minecraft: Bedrock Edition Version**
1.16.100

**Additional Context**
I also had this bug on geyser for 1.16.20

**Comment by rtm516** [comment] 2020-11-18 09:19
Can you try with vanilla paper? As I haven't had this issue nor have we had any other reports on this version and the previous.

**Comment by DoctorMacc** [comment] 2020-11-18 15:42
Also, can you please provide a Geyser dump?

**Comment by DoctorMacc** [comment] 2020-11-18 16:10
> server froze

This implies that it's a server-software-specific bug, as Geyser shouldn't be doing this.

**Comment by toinouH** [comment] 2020-11-18 16:32
`[11:04:22] [Yatopia Watchdog Thread/ERROR]: Position: world: 'world' at location (146.5, 57.099998474121094, 16.5)
[11:04:22] [Yatopia Watchdog Thread/ERROR]: Move call information: 
[11:04:22] [Yatopia Watchdog Thread/ERROR]: Start position: (146.5, 57.099998474121094, 16.5)
[11:04:22] [Yatopia Watchdog Thread/ERROR]: Move vector: (-146.5, -58.89999842643738, -16.5)
[11:04:22] [Yatopia Watchdog Thread/ERROR]: Total packets processed on the main thread for all players: 87359
[11:04:22] [Yatopia Watchdog Thread/ERROR]: ------------------------------
[11:04:22] [Yatopia Watchdog Thread/ERROR]: Current Thread: Server thread
[11:04:22] [Yatopia Watchdog Thread/ERROR]:     PID: 25 | Suspended: false | Native: false | State: RUNNABLE
[11:04:22] [Yatopia Watchdog Thread/ERROR]:     Stack:
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             app//org.bukkit.craftbukkit.v1_16_R3.util.UnsafeList.indexOf(UnsafeList.java:115)
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             app//org.bukkit.craftbukkit.v1_16_R3.util.UnsafeList.contains(UnsafeList.java:126)
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             app//net.minecraft.server.v1_16_R3.VoxelShapes.addBoxesToIfIntersects(VoxelShapes.java:43)
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             app//me.jellysquid.mods.lithium.common.entity.LithiumEntityCollisions.lambda$fillBlockCollisionsList$0(LithiumEntityCollisions.java:45)
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             app//me.jellysquid.mods.lithium.common.entity.LithiumEntityCollisions$$Lambda$5278/0x00000008011e5d78.accept(Unknown Source)
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             app//me.jellysquid.mods.lithium.common.util.Producer.fillList(Producer.java:45)
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             app//me.jellysquid.mods.lithium.common.entity.LithiumEntityCollisions.fillBlockCollisionsList(LithiumEntityCollisions.java:42)
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             app//net.minecraft.server.v1_16_R3.WorldServer.getCollisions(WorldServer.java:796)
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             app//net.minecraft.server.v1_16_R3.Entity.performCollision(Entity.java:1028)
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             app//net.minecraft.server.v1_16_R3.Entity.move(Entity.java:703)
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             app//net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1200)
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             app//net.minecraft.server.v1_16_R3.PacketPlayInFlying.a(SourceFile:122)
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             app//net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             app//net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43)
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             app//net.minecraft.server.v1_16_R3.PlayerConnectionUtils$$Lambda$5705/0x00000008012bbb88.run(Unknown Source)
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             app//net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             app//net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:151)
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             app//net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             app//net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:114)
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             app//net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1204)
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             app//net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1197)
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             app//net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:125)
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             app//net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1272)
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             app//net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1012)
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             app//net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179)
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             app//net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3171/0x00000008007a6260.run(Unknown Source)
[11:04:22] [Yatopia Watchdog Thread/ERROR]:             java.base/java.lang.Thread.run(Thread.java:832)
[11:04:22] [Yatopia Watchdog Thread/ERROR]: ------------------------------
[11:04:22] [Yatopia Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO YATOPIA - THIS IS NOT A BUG OR A CRASH ---
[11:04:22] [Yatopia Watchdog Thread/ERROR]: ------------------------------
[11:04:24] [Yatopia Watchdog Thread/ERROR]: ------------------------------
[11:04:24] [Yatopia Watchdog Thread/ERROR]: The server has stopped responding! This is (probably) not a Yatopia bug.
[11:04:24] [Yatopia Watchdog Thread/ERROR]: If you see a plugin in the Server thread dump below, then please report it to that author
[11:04:24] [Yatopia Watchdog Thread/ERROR]:      *Especially* if it looks like HTTP or MySQL operations are occurring
[11:04:24] [Yatopia Watchdog Thread/ERROR]: If you see a world save or edit, then it means you did far more than your server can handle at once
[11:04:24] [Yatopia Watchdog Thread/ERROR]:      If this is the case, consider increasing timeout-time in spigot.yml but note that this will replace the crash with LARGE lag spikes
[11:04:24] [Yatopia Watchdog Thread/ERROR]: If you are unsure or still think this is a Yatopia bug, please report this to https://github.com/tr7zw/Yatopia/issues
[11:04:24] [Yatopia Watchdog Thread/ERROR]: Be sure to include ALL relevant console errors and Minecraft crash reports
[11:04:24] [Yatopia Watchdog Thread/ERROR]: Yatopia version: git-Yatopia-"24b5188" (MC: 1.16.4)
[11:04:24] [Yatopia Watchdog Thread/ERROR]: ------------------------------`
These are the logs from the support channel of YatopiaMC

**Comment by Chew** [comment] 2020-11-18 16:57
That is just a generic "too much lag, imma head out" message. Still don't know *what* caused lag. Try a timings report?

**Comment by epserv** [comment] 2020-11-18 17:11
How can I get spark report after crash?

**Comment by epserv** [comment] 2020-11-18 17:12
and it's not a
> too much lag
it's like a deadlock or something

**Comment by DoctorMacc** [comment] 2020-11-18 17:27
Can you try with Paper and see if the problem persists?

**Comment by epserv** [comment] 2020-12-01 13:14
@DoctorMacc No, sorry, I can't.

**Comment by rtm516** [comment] 2020-12-01 13:44
> DoctorMacc No, sorry, I can't try, my pc dies if I start the server.

This was likely caused by hardware then, unless we get another report of this I will close it.

**Closed by rtm516** 2020-12-01 13:44 UTC
Labels: Unconfirmed Bug

**Comment by epserv** [comment] 2020-12-01 17:25
@rtm516 No, server is running on another pc, not on mine.
