### ISSUE TITLE
Xbox Crafting

### ISSUE THREAD

**Issue by Hellohi3654** [GeyserMC/Geyser#1192] opened 2020-08-24 08:31 UTC
Describe the bug
When on Xbox using the crafting book to craft (let's say a stack of tnt) it does all weird things with the inventory then only crafts one block of tnt

To Reproduce

Join a server on Xbox in survival mode
Attempt to use only the recipe book to craft a stack of something
Expected behavior
All the items craft when using the recipe book but only one does.

Server version
Paper 1.16.2

Geyser version
Lastest Build of Geyser

Bedrock version
Minecraft Bedrock 1.16.2 (Xbox One)

**Comment by rtm516** [comment] 2020-08-24 10:05
Please can you do `/geyser version` so we have a proper version number, and also provide a dump using `/geyser dump`

**Comment by Hellohi3654** [comment] 2020-08-24 11:44
I'm using my own branch of Geyser at the moment but I have triple checked all the crafting files and mappings files and I can see no difference between my branch and the master branch
https://dump.geysermc.org/AVKQ3vzn8k8BnnR6JhFaZCM7gfESvN4h

**Comment by Hellohi3654** [comment] 2020-08-24 11:44
Basically I think it is an issue with the master branch of Geyser as well

**Comment by rtm516** [comment] 2020-08-24 11:46
Can you test directly on the master branch from the CI?

**Comment by Hellohi3654** [comment] 2020-08-24 12:46
ok

**Comment by RednedEpic** [comment] 2020-08-24 17:42
If you could also provide a video of this happening, that would be helpful too so we can more easily see the problem happening.

**Comment by xXTeraXx** [comment] 2020-10-27 13:43
I can confirm that even if you are just using an xbox controller to use the recipe book the game will crash (Without ViaVersion) or it will kick you for sending to many packets

**Comment by CamJW101** [comment] 2020-10-29 14:21
Can confirm this behavior on latest Geyser artifact. Recipe book crafting on Xbox is glitchy in general. Only crafts one item at a time and lags the player, sometimes full on crashing.

**Comment by Chew** [comment] 2020-10-29 14:23
This sorta happens on Switch too. Recipe book is wonky, especially "Craft All", lags for a bit (doesn't crash, from my experience).

**Comment by ZolaKluke** [comment] 2020-10-29 14:32
Can also confirm, 2 players on my server who play on Xbox One had the exact same issue

**Comment by jackson-57** [comment] 2020-11-27 19:47
Can confirm that the recipe book is still very glitchy on Switch. It's hard to describe what happens, but it should be easy to reproduce, as it happens every time. I can record a video if necessary.

**Comment by DoctorMacc** [comment] 2020-11-27 20:39
Can also confirm, as I've been playing survival through Geyser over the past couple of days. Pressing A on a recipe book item does not work; however, pressing Y worked fine.

**Comment by bkGamingYT** [comment] 2020-12-04 01:53
This is happening to my players too. When using a controller, crafting using the recipe book is very glitchy.

Dump: [](https://dump.geysermc.org/poXGGP5PESLEUhuxUOvHNLPnum9a6oC6)

**Comment by AkanshDivker** [comment] 2020-12-21 23:00
Any estimate on when this could be fixed potentially? Since I notice this is a pretty old bug @Camotoy 

Some players on my server don't feel like playing until this is fixed due to how tedious it is to craft by manually placing each item on Xbox.

**Comment by Camotoy** [comment] 2020-12-22 00:57
Unfortunately, I cannot give an ETA on this. Ideally, this will be fixed in the inventory rewrite. I have a console on hand, so as we continue on that I will be testing with a console to confirm things are working.

**Comment by Valeri0p** [comment] 2021-01-20 12:12
Minor related bug:
On Android, if you open the recipe book, select a recipe (eg: TNT), craft one of it and then start spamming the recipe icon for that block, the server will kick you for sending too many packets.
Crafting one item at the time using the recipe book seems to work fine tho.

**Comment by rgronberg** [comment] 2021-01-20 16:25
I started using the build from the server-inventory branch for about 4 days now and it is working pretty good. Stonecutter, grindstone, and enchantment table working perfectly. Only issue with the cartography table is you can't create maps, only expand existing maps.

More importantly, single click crafting is working!

I know this is a pre-release branch of the plugin and I can expect bugs, but I am willing to test it

**Comment by Camotoy** [comment] 2021-01-20 16:43
@rgronberg I believe that map creation doesn't exist on Java Edition: https://minecraft.gamepedia.com/Cartography_Table

So it's good to hear that everything is working as intended!

**Comment by rgronberg** [comment] 2021-01-20 16:56
Ah, even better! Then I have no issues to report with the side branch. So happy it's working 😁

**Comment by isteiger** [comment] 2021-03-14 13:41
This is fixed in the inventory rewrite for me.

**Closed** 2021-03-14 15:20 UTC
Labels: Confirmed Bug
