### ISSUE TITLE
ERROR on standalone

### ISSUE THREAD

**Issue by adalmo** [GeyserMC/Geyser#3338] opened 2022-10-07 05:17 UTC
### Describe the bug

[14:10:35 ERROR] Could not translate packet ClientboundContainerSetContentPacket
java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
	at org.geysermc.geyser.inventory.Inventory.getItem(Inventory.java:118) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.inventory.updater.InventoryUpdater.updateInventory(InventoryUpdater.java:43) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.inventory.updater.ChestInventoryUpdater.updateInventory(ChestInventoryUpdater.java:50) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.translator.inventory.chest.ChestInventoryTranslator.updateInventory(ChestInventoryTranslator.java:56) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:73) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:38) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[Geyser-Standalone.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [Geyser-Standalone.jar:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [Geyser-Standalone.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [Geyser-Standalone.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser-Standalone.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser-Standalone.jar:?]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
	at org.geysermc.geyser.inventory.Inventory.getItem(Inventory.java:118)
	at org.geysermc.geyser.inventory.updater.InventoryUpdater.updateInventory(InventoryUpdater.java:43)
	at org.geysermc.geyser.inventory.updater.ChestInventoryUpdater.updateInventory(ChestInventoryUpdater.java:50)
	at org.geysermc.geyser.translator.inventory.chest.ChestInventoryTranslator.updateInventory(ChestInventoryTranslator.java:56)
	at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:73)
	at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:38)
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1589)

### To Reproduce

just running server with latest geysermc build

### Expected behaviour

[14:10:35 ERROR] Could not translate packet ClientboundContainerSetContentPacket
java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
	at org.geysermc.geyser.inventory.Inventory.getItem(Inventory.java:118) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.inventory.updater.InventoryUpdater.updateInventory(InventoryUpdater.java:43) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.inventory.updater.ChestInventoryUpdater.updateInventory(ChestInventoryUpdater.java:50) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.translator.inventory.chest.ChestInventoryTranslator.updateInventory(ChestInventoryTranslator.java:56) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:73) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:38) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[Geyser-Standalone.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [Geyser-Standalone.jar:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [Geyser-Standalone.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [Geyser-Standalone.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser-Standalone.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser-Standalone.jar:?]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
	at org.geysermc.geyser.inventory.Inventory.getItem(Inventory.java:118)
	at org.geysermc.geyser.inventory.updater.InventoryUpdater.updateInventory(InventoryUpdater.java:43)
	at org.geysermc.geyser.inventory.updater.ChestInventoryUpdater.updateInventory(ChestInventoryUpdater.java:50)
	at org.geysermc.geyser.translator.inventory.chest.ChestInventoryTranslator.updateInventory(ChestInventoryTranslator.java:56)
	at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:73)
	at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:38)
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1589)

### Server Version and Plugins

[14:15:58 INFO] This server is running Geyser version 2.1.0-SNAPSHOT (git-master-fc25592) (Java: 1.19.1 - 1.19.2, Bedrock: 1.19.0/1.19.2 - 1.19.30)

### Geyser Dump

https://dump.geysermc.org/T7V9xUEKRM2iLUOwgsDfk7Dvpc7prk7Z

### Geyser Version

2.1.0-SNAPSHOT (git-master-fc25592)

### Minecraft: Bedrock Edition Device/Version

1.19.31

**Comment by Konicai** [comment] 2022-10-13 01:00
Duplicate of #3115, if you have gameplay steps that consistently produce this issue, please add it to that issue report.

**Closed by Konicai** 2022-10-13 01:00 UTC
