### ISSUE TITLE
Riding on camels

### ISSUE THREAD

**Issue by daniel-skopek** [GeyserMC/Geyser#4000] opened 2023-07-18 22:51 UTC
### Describe the bug

When a player mounts a camel with a saddle, the camel starts to spin in a circle and cannot be controlled. Only the Bedrock player can see the spinning camel. The Java player next to him sees that he is standing still. When he tries to move, he stands still.

### To Reproduce

1. Mount camel with a saddle
2. Bedrock player see spinning camel

### Expected behaviour

The camel should be controlled

### Geyser Version

2.1.2-SNAPSHOT (git-master-c1d8009)

**Comment by Konicai** [comment] 2023-07-18 23:54
Duplicate of #3860

**Closed by Konicai** 2023-07-18 23:54 UTC
