### ISSUE TITLE
Spigot PlayerInteractEvent will not fire when Geyser player is holding a consumable

### ISSUE THREAD

**Issue by snowgears** [GeyserMC/Geyser#3393] opened 2022-11-10 16:02 UTC
### Describe the bug

Currently the mobile players cannot make shops (which rely on the PlayerInteractEvent in Spigot) because potions or any consumable food items play the eating animation instead (happens only in mobile bedrock).

### To Reproduce

1. Have Spigot server
2. Have a plugin listening in on the PlayerInteractEvent
3. Have Geyser mobile player join
4. Have the player click on a block while holding a consumable
5. The PlayerInteractEvent is not fired

### Expected behaviour

For the RIGHT_CLICK_BLOCK event to be fired instead of eating the item

### Geyser Version

build #1228

**Comment by Jens-Co** [comment] 2022-11-11 22:21
Possible duplicate of #2346.

**Comment by onebeastchris** [comment] 2023-06-11 01:26
Closing as likely duplicate.

**Closed by onebeastchris** 2023-06-11 01:26 UTC
