### ISSUE TITLE
Excellent Enchants

### ISSUE THREAD

**Issue by Krazytrain** [GeyserMC/Geyser#4193] opened 2023-10-07 01:30 UTC
### Describe the bug

Excellent Enchants does not allow bedrock players to use the enchantments. 

Bedrock players can see and use them on there gear but adding it through anvils is not allowed. 
It might be the same for enchantment tables too. 

### To Reproduce

Must be on bedrock version.
1. Place a anvil down
2. Put sword into anvil
3. add a Excellent Enchants book into anvil that can be placed onto a sword like wither 3
4. The sword does not show up on the end of the anvil GUI

### Expected behaviour

The wither 3 enchantment to be on the sword.

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/54170019/a4b2b5e5-da6f-4484-90d4-40db84fa10a9)

### Server Version and Plugins

Server version 1.20.1 
Paper version 196
Geyser version 320 or 321.

### Geyser Version

Geyser version 320 or 321.

**Comment by Krazytrain** [comment] 2023-10-07 01:40
This is what it looks like on the anvil on bedrock
![image](https://github.com/GeyserMC/Geyser/assets/54170019/334e25fb-979b-4265-ba3e-0cf1f54f03cf)

**Comment by Krazytrain** [comment] 2023-10-07 01:41
Also just updated geyser and floodgate to the latest versions to see if it happens again. 

Geyser - 322
Floodgate - 75

**Comment by onebeastchris** [comment] 2023-10-07 09:30
Duplicate of https://github.com/GeyserMC/Geyser/issues/3121 or similar - unfortunately, the Bedrock client doesn't have support for custom enchantments, hence why they don't work in anvils or don't show up in enchanting tables :/

**Closed** 2023-10-07 09:30 UTC
Labels: Duplicate, Client Bug
