### ISSUE TITLE
chunks stop loading (wrong render distance calculation)

### ISSUE THREAD

**Issue by Ch3deSlinger** [GeyserMC/Geyser#4658] opened 2024-05-11 19:12 UTC
### Describe the bug

how to reproduce:
1- start your geyser server
2- login using minecraft bedrock
3- fly around in creative mode
this issue also happened to me whilst playing survival unbelievably annoying! 

### To Reproduce

above

### Expected behaviour

chunks should load

### Screenshots / Videos

![Screenshot 2024-05-11 195311](https://github.com/GeyserMC/Geyser/assets/169554911/1b163b53-d63d-4767-b58b-96675904f505)

### Server Version and Plugins

Paper 1.20.6 (64)

### Geyser Dump

idk

### Geyser Version

Lastest build 528

### Minecraft: Bedrock Edition Device/Version

bedrock 1.20.70

### Additional Context

if there's a solution to this problem then PLEASE! tell me in the comments :)

**Comment by onebeastchris** [comment] 2024-05-11 19:36
Duplicate of https://github.com/GeyserMC/Geyser/issues/3809 - for now, the only known fix is to have the server simulation distance be the same as the client render distance.

**Closed by onebeastchris** 2024-05-11 19:36 UTC

**Comment by Ch3deSlinger** [comment] 2024-05-16 21:44
that still didn't fix it. :(
