### ISSUE TITLE
12th pc having this error msg 

### ISSUE THREAD

**Issue by adalmo** [GeyserMC/Geyser#3238] opened 2022-08-17 19:49 UTC
### Describe the bug

![20220816_153700](https://user-images.githubusercontent.com/88581750/185228944-5b681733-aad9-4534-a34e-c9360b4616fc.jpg)

### To Reproduce

turn on geyser.jar or start.bat with java -Xms12G -Xmx12G -XX:+UnlockDiagnosticVMOptions -XX:-UseAESCTRIntrinsics -jar geyser.jar

### Expected behaviour

![20220816_153700](https://user-images.githubusercontent.com/88581750/185229114-46e51b7d-884f-431c-8f39-3fc6fafdd2a1.jpg)

### Screenshots / Videos

![20220818_044708](https://user-images.githubusercontent.com/88581750/185229226-f21f616e-20e5-4c57-b00c-6ec1bc2f2646.jpg)

### Server Version and Plugins

1.19.2 
geyser & floodgate

### Geyser Dump

(https://dump.geysermc.org/RjnRETEaPVdL3i7pxCOXWjvvMGaoxmt7)

### Geyser Version

Build #1175 Geyser.jar

### Minecraft: Bedrock Edition Device/Version

1.19.0 ~ 1.19.20

**Comment by Camotoy** [comment] 2022-08-17 19:50
Please provide a Geyser dump.

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by adalmo** [comment] 2022-08-17 19:57
done

**Comment by Camotoy** [comment] 2022-08-17 20:01
OK - it might be another bug with the 12th-gen Intel processor. Can you remove the two arguments you added for encryption and replace it with `-XX:UseAVX=2`?

**Comment by adalmo** [comment] 2022-08-17 20:02
i will try

**Comment by adalmo** [comment] 2022-08-17 20:33
same as before it still appearing

**Comment by adalmo** [comment] 2022-08-17 20:34
![Uploading 20220818_053357.jpg…]()

**Comment by adalmo** [comment] 2022-08-17 20:34
![20220818_053357](https://user-images.githubusercontent.com/88581750/185237811-5fa7886d-9dca-4fef-97e7-02b5368166bc.jpg)

**Comment by TheRemote** [comment] 2022-08-19 16:50
These issues are very puzzling.  I've been trying to fix this for someone on my Docker container project that has Geyser/Floodgate.  Full logs are here (but it's this issue unless you guys spot something I didn't): https://jamesachambers.com/minecraft-java-bedrock-server-together-geyser-floodgate/#comment-14086

So far I have tried rolling back to OpenJDK18U-jre_x64_linux_hotspot_18.0.1_10 and the encryption options.  I'm going to attempt to try this fix on the container suggested here just because I really don't know how else to help this person fix this other than throwing out the CPU!

**Comment by jaybird2** [comment] 2022-08-19 17:31
HEre is a geyser dumpm with ARM: https://dump.geysermc.org/fs0qrmWIwUUvoIvOfhchTyI04CWBt7JG
and one with I7: https://dump.geysermc.org/SvBw5FNkrbbrMSjXEQtEEgVcRctSbpat

log for I7 here:
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.4+8) Host: Linux 5.10.16.3-microsoft-standard-WSL2 (amd64)
Loading libraries, please wait...
[17:22:55 INFO]: Building unoptimized datafixer
[17:23:03 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:23:17 INFO]: Loaded 7 recipes
[17:23:27 INFO]: Starting minecraft server version 1.19.2
[17:23:27 WARN]: ****************************
[17:23:27 WARN]: YOU ARE RUNNING THIS SERVER AS AN ADMINISTRATIVE OR ROOT USER. THIS IS NOT ADVISED.
[17:23:27 WARN]: YOU ARE OPENING YOURSELF UP TO POTENTIAL RISKS WHEN DOING THIS.
[17:23:27 WARN]: FOR MORE INFORMATION, SEE https://madelinemiller.dev/blog/root-minecraft-server/
[17:23:27 WARN]: ****************************
[17:23:27 INFO]: Loading properties
[17:23:28 INFO]: This server is running Paper version git-Paper-131 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 2da891f)
[17:23:28 INFO]: Server Ping Player Sample Count: 12
[17:23:28 INFO]: Using 4 threads for Netty based IO
[17:23:30 INFO]: Default game type: SURVIVAL
[17:23:30 INFO]: Generating keypair
[17:23:31 INFO]: Starting Minecraft server on *:25565
[17:23:31 INFO]: Using epoll channel type
[17:23:31 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[17:23:31 INFO]: Paper: Using Java cipher from Velocity.
[17:23:35 INFO]: [floodgate] Loading floodgate v2.2.0-SNAPSHOT (b73-4f36112)
[17:23:38 INFO]: [floodgate] Took 2,882ms to boot Floodgate
[17:23:38 INFO]: [Geyser-Spigot] Loading Geyser-Spigot v2.0.7-SNAPSHOT
[17:23:38 INFO]: Server permissions file permissions.yml is empty, ignoring it
[17:23:38 INFO]: Preparing level "world"
[17:23:45 INFO]: [floodgate] Enabling floodgate v2.2.0-SNAPSHOT (b73-4f36112)
[17:23:48 INFO]: [Geyser-Spigot] Enabling Geyser-Spigot v2.0.7-SNAPSHOT
[17:23:52 WARN]: [Geyser-Spigot] Your Geyser config is out of date! Please regenerate your config when possible.
[17:23:52 INFO]: [Geyser-Spigot] ******************************************
[17:23:52 INFO]: [Geyser-Spigot]
[17:23:52 INFO]: [Geyser-Spigot] Loading Geyser version 2.0.7-SNAPSHOT (git-master-33af9e0)
[17:23:52 INFO]: [Geyser-Spigot]
[17:23:52 INFO]: [Geyser-Spigot] ******************************************
[17:24:16 INFO]: [Geyser-Spigot] Started Geyser on 0.0.0.0:19132
[17:24:16 INFO]: [Geyser-Spigot] Done (24.144s)! Run /geyser help for help!
[17:24:17 INFO]: Running delayed init tasks
[17:24:17 INFO]: Done (49.690s)! For help, type "help"
[17:24:17 INFO]: Timings Reset
[17:25:02 INFO]: [Geyser-Spigot] /172.17.0.1:55648 tried to connect!
[17:25:03 WARN]: [io.netty.util.concurrent.AbstractEventExecutor] A task raised an exception. Task: com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener$$Lambda$6035/0x0000000801dcacb8@570bfc08
java.lang.RuntimeException: Unable to inflate buffer data
        at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:87) ~[Geyser-Spigot.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:283) ~[Geyser-Spigot.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.lambda$onEncapsulated$0(BedrockRakNetSessionListener.java:39) ~[Geyser-Spigot.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.util.zip.DataFormatException: incorrect header check
        at java.util.zip.Inflater.inflateBufferBuffer(Native Method) ~[?:?]
        at java.util.zip.Inflater.inflate(Unknown Source) ~[?:?]
        at com.nukkitx.natives.zlib.Java11Inflater.inflate(Java11Inflater.java:21) ~[Geyser-Spigot.jar:?]
        at com.nukkitx.protocol.util.Zlib.inflate(Zlib.java:56) ~[Geyser-Spigot.jar:?]
        at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:61) ~[Geyser-Spigot.jar:?]
        ... 9 more
[17:25:10 INFO]: [Geyser-Spigot] Bedrock user with ip: /172.17.0.1 has disconnected for reason Bedrock client disconnected

**Comment by TheRemote** [comment] 2022-08-19 17:44
Perfect, thanks for sharing those!  Just to be clear do you get that exact same error when someone tries to join on ARM?  I honestly don't understand how that's possible and that's one of the pieces that made me want to bring it here right to the main developers.

**Comment by jaybird2** [comment] 2022-08-19 18:00
from I7, the stracktrace at line8 is like this

at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]

while on ARM it is like this

at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]

The rest is identical (diff). This is strange to me: why in te middle of a stracktrace, the reported lines are changing???

**Comment by jaybird2** [comment] 2022-08-19 18:01
toggling use-native-transport didn't change anything, like you assumed

**Comment by TheRemote** [comment] 2022-08-19 18:07
Oh wow, that is an interesting difference actually.  Definitely worth noting.  Netty is not happy in either case but what could it be?  You are even using a Raspberry Pi which is a known good platform that is honestly probably the most popular thing it has ran on and I've never seen it for myself or from anyone else so far (but there are clearly others getting it).

**Comment by jaybird2** [comment] 2022-08-19 18:31
I reimaged it today, so pretty new.
Raspberry Pi 3 Model B Rev 1.2.
At the end of next week, I can try a Nintendo Switch.

**Comment by Camotoy** [comment] 2022-08-20 03:05
I downloaded Java on my Raspberry Pi:
`Linux COMPUTERNAME 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux`
```
openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment Temurin-17.0.4+8 (build 17.0.4+8)
OpenJDK Server VM Temurin-17.0.4+8 (build 17.0.4+8, mixed mode, sharing)
```
The latest Geyser version runs fine.

**Comment by jaybird2** [comment] 2022-08-20 05:29
Hi Comotoy,
my setting is different.
I used 3 times the docker image from this link https://jamesachambers.com/minecraft-java-bedrock-server-together-geyser-floodgate/ .
I did that with two PCs, one with Gen11 process and one with I7. And with my PI. For the last two approaches, I uploaded the dump and posted the logs above (and on the page with the docker image).

If you want to reproduce this thing, you have to install that docker image.

And I am currently using two android clients with minecraft beta. I tried to downgrade it to non-beta and will report, when that happend.

**Comment by TheRemote** [comment] 2022-08-20 06:49
To be clear the Docker image works fine on the Raspberry Pi.  I actually developed it on the Pi and it will run in either 32-bit or 64-bit ARM.  Here's with the Pi 4:

```
Downloading mojang_1.19.2.jar
Applying patches
Starting org.bukkit.craftbukkit.Main
System Info: Java 18 (OpenJDK 64-Bit Server VM 18.0.2+9) Host: Linux 5.15.32-v8+ (aarch64)
Loading libraries, please wait...
[06:46:16 INFO]: Building unoptimized datafixer
[06:46:21 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[06:46:22 INFO]: Found new data pack file/bukkit, loading it automatically
[06:46:31 INFO]: Loaded 7 recipes
[06:46:38 INFO]: Starting minecraft server version 1.19.2
[06:46:38 WARN]: ****************************
[06:46:38 WARN]: YOU ARE RUNNING THIS SERVER AS AN ADMINISTRATIVE OR ROOT USER. THIS IS NOT ADVISED.
[06:46:38 WARN]: YOU ARE OPENING YOURSELF UP TO POTENTIAL RISKS WHEN DOING THIS.
[06:46:38 WARN]: FOR MORE INFORMATION, SEE https://madelinemiller.dev/blog/root-minecraft-server/
[06:46:38 WARN]: ****************************
[06:46:38 INFO]: Loading properties
[06:46:38 INFO]: This server is running Paper version git-Paper-131 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 2da891f)
[06:46:39 INFO]: Server Ping Player Sample Count: 12
[06:46:39 INFO]: Using 4 threads for Netty based IO
[06:46:40 INFO]: Default game type: SURVIVAL
[06:46:40 INFO]: Generating keypair
[06:46:40 INFO]: Starting Minecraft server on *:25565
[06:46:40 INFO]: Using epoll channel type
[06:46:40 INFO]: Paper: Using libdeflate (Linux aarch64) compression from Velocity.
[06:46:40 INFO]: Paper: Using Java cipher from Velocity.
[06:46:42 INFO]: [floodgate] Loading floodgate v2.2.0-SNAPSHOT (b73-4f36112)
[06:46:44 INFO]: [floodgate] Took 2,141ms to boot Floodgate
[06:46:44 INFO]: [Geyser-Spigot] Loading Geyser-Spigot v2.0.7-SNAPSHOT
[06:46:44 INFO]: Preparing level "world"
[06:46:44 WARN]: Failed to parse level-type default, defaulting to minecraft:normal
[06:47:48 INFO]: [floodgate] Enabling floodgate v2.2.0-SNAPSHOT (b73-4f36112)
[06:47:50 INFO]: [Geyser-Spigot] Enabling Geyser-Spigot v2.0.7-SNAPSHOT
[06:47:52 INFO]: [Geyser-Spigot] ******************************************
[06:47:52 INFO]: [Geyser-Spigot] 
[06:47:52 INFO]: [Geyser-Spigot] Loading Geyser version 2.0.7-SNAPSHOT (git-master-33af9e0)
[06:47:52 INFO]: [Geyser-Spigot] 
[06:47:52 INFO]: [Geyser-Spigot] ******************************************
[06:48:05 INFO]: [Geyser-Spigot] Started Geyser on 0.0.0.0:19132
[06:48:05 INFO]: [Geyser-Spigot] Done (13.417s)! Run /geyser help for help!
[06:48:06 INFO]: Running delayed init tasks
[06:48:06 INFO]: Done (87.604s)! For help, type "help"
[06:48:06 INFO]: Timings Reset
[06:48:06 INFO]: [Geyser-Spigot] Downloading Minecraft JAR to extract en_us locale, please wait... (this may take some time depending on the speed of your internet connection)
[06:48:13 INFO]: [Geyser-Spigot] Minecraft JAR has been successfully downloaded and loaded!
[06:48:43 INFO]: [Geyser-Spigot] /192.168.1.18:57318 tried to connect!
[06:48:44 INFO]: [Geyser-Spigot] Player connected with username Jimmy Cham
[06:48:44 INFO]: [Geyser-Spigot] Jimmy Cham (logged in as: Jimmy_Cham) has connected to the Java server
[06:48:45 INFO]: UUID of player .Jimmy_Cham is 00000000-0000-0000-0009-000001777226
[06:48:46 INFO]: [floodgate] Floodgate player logged in as .Jimmy_Cham joined (UUID: 00000000-0000-0000-0009-000001777226)
[06:48:54 INFO]: .Jimmy_Cham joined the game
[06:48:54 INFO]: .Jimmy_Cham[/192.168.1.18:0] logged in with entity id 1 at ([world]95.5, 69.0, 146.5)
> 
```

You can certainly try running the server manually without the Docker container at all and install Geyser/Spigot manually as a test to confirm this.  I think you need to do this at this point.  It's never had any trouble running on the Pi.  Nobody has ever had this issue on any platform except you so far!

**Comment by jaybird2** [comment] 2022-08-21 20:00
It works now! My android is running non-beta and there I have no issue.

An the long run: what will happen, if this beta code going public? Than, lots of people will have this issue.
:-(

**Comment by Camotoy** [comment] 2022-08-21 20:07
Beta 1.19.30 currently operates in a different manner that requires a Geyser update. This is known and will be fixed.

**Comment by TheRemote** [comment] 2022-08-21 22:22
Thanks everyone!

**Comment by adalmo** [comment] 2022-08-28 21:52
[06:50:53 WARN] A task raised an exception. Task: com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener$$Lambda$1000/0x00000008011accb8@652635ef
java.lang.RuntimeException: Unable to inflate buffer data
        at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:87) ~[Geyser.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:283) ~[Geyser.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.lambda$onEncapsulated$0(BedrockRakNetSessionListener.java:39) ~[Geyser.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[Geyser.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [Geyser.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [Geyser.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) [Geyser.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [Geyser.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.util.zip.DataFormatException: incorrect header check
        at java.util.zip.Inflater.inflateBufferBuffer(Native Method) ~[?:?]
        at java.util.zip.Inflater.inflate(Inflater.java:543) ~[?:?]
        at com.nukkitx.natives.zlib.Java11Inflater.inflate(Java11Inflater.java:21) ~[Geyser.jar:?]
        at com.nukkitx.protocol.util.Zlib.inflate(Zlib.java:56) ~[Geyser.jar:?]
        at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:61) ~[Geyser.jar:?]
        ... 9 more <- it was 8 but on latest geyser standalone it become to 9

**Comment by onebeastchris** [comment] 2023-05-21 21:30
Is this issue still occurring? If it is; please provide a new geyser dump & a full log file via mclo.gs.

**Comment by onebeastchris** [comment] 2023-06-11 01:20
Closing due to no response.

**Closed by onebeastchris** 2023-06-11 01:20 UTC
Labels: Waiting On Response
