### ISSUE TITLE
Geyser feedback on Floodgate 2.0 support

### ISSUE THREAD

**Issue by CuleSKY** [GeyserMC/Geyser#2191] opened 2021-05-03 13:47 UTC
### Describe the bug

1.Bedrock Edition of the player synthesis items will have the probability of not synthesized or synthesis table error
2.When Bedrock player try to cross the baboos,they will bounce back

### To Reproduce

Using the latest Geyser version with Floodgate 2.0 support

### Server Version and Plugins
The lastest tuinity version
CMI and luckperms

### Geyser Version

1.3.0-SNAPSHOT (git-floodgate-2.0-3b9674a)

### Minecraft: Bedrock Edition Version

1.16.221

**Comment by Konicai** [comment] 2021-05-03 14:01
1. I'm not sure what you mean, but it would probably be better to come to our discord https://discord.gg/geysermc/ and ask in one of the support channels

2. Duplicate of #1899. The hitbox of the bedrock bamboo is in a different location than the hitbox of the java bamboo. This causes the client to collide with the bamboo _server side_, while the client doesn't realize it is. Camotoy made a hacky plugin to fix it, which just disables the bamboo collision server side: https://discord.com/channels/613163671870242838/613170125696270357/827982346539368498

**Comment by Camotoy** [comment] 2021-05-03 14:26
Yeah, I assume you're using a translator? Please ask in our #general-l18n channel in your native language and someone will be along to help.
Thanks!

**Closed by Camotoy** 2021-05-03 14:26 UTC

**Comment by Galactor007** [comment] 2021-09-07 13:42
While in geyser mc bedrock players cant build anything on nether roof itz showing build limit 126 smth pls i request to fix it in the next update

**Comment by Camotoy** [comment] 2021-09-07 13:43
There is a config option to fix this: https://github.com/GeyserMC/Geyser/wiki/Understanding-the-Config
Please do not bump old issues, especially with unrelated content. If you have further questions, please join our Discord server. Thanks.
