### ISSUE TITLE
Players Cannot Ride Striders Or Pigs Using Geyser On A Spigot 1.17 Server

### ISSUE THREAD

**Issue by AidenMoonBow** [GeyserMC/Geyser#2452] opened 2021-08-08 00:09 UTC
### Describe the bug

The Players on BedRock Just sit there they can turn the mountable animals but they cannot actually drive them using the correct steering item

### To Reproduce

log into server with bedrock account
sit on animal holding correct steering item
animal does not move forward or in any direction just spins

### Expected behaviour

animal to work properly like java accounts do

### Server Version and Plugins

spigot 1.17

### Geyser Version

Geyser-Spigot v1.4.1-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.17.1

**Comment by Camotoy** [comment] 2021-08-08 01:20
Duplicate of #638. Thank you for reporting anyway!

**Closed by Camotoy** 2021-08-08 01:20 UTC

**Comment by AidenMoonBow** [comment] 2021-08-08 01:21
Was it ever solved though I could never figure out by reading it

**Comment by Camotoy** [comment] 2021-08-08 01:30
The issue is still open, meaning it is not yet fixed (nor should you expect it to be for a while).
