### ISSUE TITLE
Bedrock Client Crashing Using C&C preview datapack

### ISSUE THREAD

**Issue by NoobMC105** [GeyserMC/Geyser#2400] opened 2021-07-20 08:59 UTC
### Describe the bug

Whenever I try to join with the caves and cliffs datapack enabled the client gets crashed tested with both inject and master with the extended-height: true in config.

### To Reproduce

Put the caves and cliffs datapack
Start the server
Try to join the server
Client Crashes

### Expected behaviour

Clients should be able to join without crashing

### Server Version and Plugins

This server is running AirplanePurpur version git-AirplanePurpur-22 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 5e4deb0 on HEAD)

### Geyser Dump

https://dump.geysermc.org/5yX2pZT1MGFJtTHDwaCJo38AkRXQab2x

### Geyser Version

Geyser version 1.4.1-SNAPSHOT (git-master-2766038) (Java: 1.17.1, Bedrock: 1.17.10)

### Minecraft: Bedrock Edition Version

1.17.10

**Comment by Jens-Co** [comment] 2021-07-20 09:04
https://mclo.gs/W24qIuS These are his logs.

**Comment by Camotoy** [comment] 2021-07-20 12:22
Does your issue happen with Paper?

**Comment by NoobMC105** [comment] 2021-07-20 13:44
Yes tested with paper and tuinity aswell happens on both.

**Comment by Camotoy** [comment] 2021-07-20 13:47
Does it happen on a clean server with no plugins? I definitely don't crash with just Paper.

**Comment by NoobMC105** [comment] 2021-07-20 14:12
Right it doesnt happen without plugins

**Comment by Camotoy** [comment] 2021-07-20 14:13
If you have a possible plugin interfering with Geyser or Floodgate, follow these steps to find the culprit plugin:
- Temporarily remove/move half of your plugins from your server's plugins folder.
- If the problem persists, remove another half.
- If the problem goes away, swap that half of your plugins with the other half.
- Keep repeating this pattern, this time with the half that exhibits the problem, until you find your problematic plugin.

**Comment by NoobMC105** [comment] 2021-07-20 15:21
Found that its multiverse

**Comment by NoobMC105** [comment] 2021-07-20 19:25
Any idea what could be causing this to?

**Comment by Puremin0rez** [comment] 2021-07-21 10:11
I'm getting this same issue and I'm on a server that has a few basic plugins with Geyser and Floodgate. No Multiverse.

I'm using the extended height option on an extended height world made using a datapack.

I'm able to load most of the world just fine, but there's a few specific areas that when I go to them on the bedrock client, the game immediately closes. I'm able to load these areas just fine using Java client.

The issue does not occur when extended height support on Geyser is disabled.

I'm not familiar with bedrock, but is there a way to get my client crash logs to identify what's causing the problem?

**Comment by NoobMC105** [comment] 2021-07-21 10:36
One more issue reported by my player on xbox one he crashes on joining if geyser have extended height true even without the datapack

**Comment by Camotoy** [comment] 2021-07-21 12:14
@Puremin0rez if you have a world you could send over our way with the chunk coordinates that cause the player to crash as well as the Bedrock platform type?
Also, no, Bedrock doesn't really have crash logs. :/

**Comment by Camotoy** [comment] 2021-07-21 12:22
Extended World Height did not crash an Xbox just with that setting in my testing.

**Comment by RishavV123** [comment] 2021-07-22 03:33
I am getting the same issue

**Comment by Jens-Co** [comment] 2021-07-22 05:19
> I am getting the same issue

Hi there, do you have the multi-verse core plugin on your server ?

**Comment by Puremin0rez** [comment] 2021-07-22 07:12
@Camotoy here's a zip containing everything important to reproduce this crash - it's a world that has my `level.dat` (for the seed) and the `datapacks/` used to create my world. I did not include any region files since the server will generate identical chunks that cause the crash.

**Download:** [geyser_crash_reproduction_world.zip](https://github.com/GeyserMC/Geyser/files/6860304/geyser_crash_reproduction_world.zip)

My reproduction steps:
1) Setup clean Paper environment (just the jar, eula.txt, etc)
2) Extract / place the `world/` directory from my zip into the server directory
2) Install & setup Geyser (I used offline auth to avoid floodgate for this test)
3) Enable `extended-world-height` in Geysers config
4) Login to the world using Bedrock Windows 10 Edition (specifically, `v1.17.10`)
5) Execute `/tp -5 72 -428`
6) Give it a moment while the terrain generates, but you'll crash eventually assuming you're using a good view distance. The crash is caused by one of the chunks near that coordinate that loads into view.

Reproduction was done using...
Paper `#123`, Geyser `#764`

The same problem does not occur while using the Java client. It also does not occur when the `extended-world-height` option is turned off in Geyser.

Hope it helps :) if you need any additional information, let me know.

**Comment by Camotoy** [comment] 2021-07-23 18:21
@Puremin0rez I was also able to replicate a crash with that setup on a vanilla server.

**Comment by Camotoy** [comment] 2021-07-24 01:46
@Puremin0rez your specific problem has been fixed in the next build. To properly fix it will mean a little bit more work.

Bedrock doesn't have every biome that Java Edition has. This hasn't really been an issue - we've just mapped any obviously invalid biome to its Bedrock counterpart. With 1.17.10, Bedrock crashes on any biome ID that doesn't exist in its game. 
With this, there are two things we ought to do:
- Try to be more Java-server-based and use the biome IDs from the server instead of hardcoded IDs.
- Take those IDs and map them to Bedrock's constants.

**Comment by Puremin0rez** [comment] 2021-07-24 03:03
@Camotoy Thanks! It works perfectly now :)

Didn't realize it was a biome mapping issue, that makes sense. I think my biggest struggle with Bedrock so far in my limited experience is that there are no client logs... that seems like a very important omission, and one that would have (presumably) quickly identified this issue.

I've only just started using Geyser for production last week and this was my only blocker. Hopefully smooth sailing from here :P

Appreciate the quick response and fix <3

**Comment by Greg-J** [comment] 2021-07-28 18:45
For what it's worth, I had a player log in and travel to an Incendium Biome. While he did crash in The Nether, he was able to traverse Incendium Biomes just fine.

I am using the latest version of fabric-geyser and fabric-floodgate along with the latest version of Incendium on 1.17.1.

**Comment by Camotoy** [comment] 2021-07-29 00:40
For anyone experiencing this issue, please update to the latest Geyser version and re-test.

**Comment by Greg-J** [comment] 2021-07-29 06:42
> For anyone experiencing this issue, please update to the latest Geyser version and re-test.

How far behind the main branch does the fabric branch generally follow?

**Comment by Camotoy** [comment] 2021-07-31 20:39
For those who were able to replicate this bug with Multiverse, please try the latest build.

**Comment by Camotoy** [comment] 2021-08-14 04:38
Closing as there have been no reports of crashing with `extended-world-height` enabled after the final bug fix. Please let me know if a bug still manifests only with the toggle enabled!

**Closed by Camotoy** 2021-08-14 04:38 UTC
