### ISSUE TITLE
My server has multiple IP addresses, but geyser can only use one of them

### ISSUE THREAD

**Issue by 10935336** [GeyserMC/Geyser#1287] opened 2020-09-13 09:44 UTC
**Describe the bug**
My server has multiple IP addresses for load balancing. These addresses are bound to different domain names. For some reasons, I did not use HAproxy.
After using Geyser, I added all the domain names in Bedrock Edition, but only one domain name can enter the server, and it is completely random. Every time I restart the bungeecord, a different domain name can enter.
In addition, my server has an IPv6 address, which is also unavailable
Although this is not a big problem, I still hope to be able to use all the lines.

config.yml:
```
bedrock:
  # The IP address that will listen for connections.
  # There is no reason to change this unless you want to limit what IPs can connect to your server.
  address: 0.0.0.0
  # The port that will listen for connections
  port: 19132
```

**To Reproduce**
1. Install geyser in bungeecord
2. Configuration
3. Add all server domain names to Bedrock Edition
4. See that only one domain name can connect to the server

**Expected behavior**
Should be able to connect to the server using all domains/IP addresses

**Server Version**
I use bungeecord version of geyser.
I use the waterfall fork Traverine.
Traverine version:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:ed11f57:160 by md_5 # 160
Server version: git-Paper-"d35903e" # 195

**Geyser Version**
Geyser version: git-master-8c86308
Not using Floodgate

**Minecraft: Bedrock Edition Version**
Android: v1.16.40
Windows10: beta 1.16.100.55

**Comment by bundabrg** [comment] 2020-09-13 10:20
You may need to explain your setup a little (how you have your java server hooked up). I assuming you have multiple transits (since load balancing across a single isp would not make sense unless this is for HA purposes). Does each IP get forwarded to a single IP on a host or do you have a host with multiple routes itself which owns all the IPs?

**Comment by 10935336** [comment] 2020-09-13 10:54
> You may need to explain your setup a little (how you have your geyser proxy hooked up). I assuming you have multiple transits (since load balancing across a single isp would not make sense unless this is for HA purposes). Does each IP get forwarded to a single IP on a host or do you have a host with multiple routes itself which owns all the IPs?
> 
> My working theory at the moment is Geyser not allowing a connection because its sending the wrong IP in the response packet which occurs during a connection though it doesn't quite fit all the symptoms.

I use a server with multiple network interfaces and connect to the networks provided by different ISPs through a single router.
I have configured the server to send packets from which line back to which line, so it works well with other applications such as the JAVA version of Minecraft and web applications. I can use 2 lines at the same time without discrimination.
![image](https://user-images.githubusercontent.com/32383605/93016194-e704db00-f5f1-11ea-9d93-b9979f1f4241.png)

**Comment by bundabrg** [comment] 2020-09-13 11:08
Excellent. Does your routers perform NAT and thus your server has 2 private IP's, 1-1 bound to the external ips? I assume you must be tagging the inbound route to be able to then policy route it back out the appropriate transit.

**Comment by 10935336** [comment] 2020-09-13 11:41
I use DMZ, so I don’t need to use NAT, and yes I use policy route based on the source IP.
This is how i achieve: 
```
route add -net 10.1.1.0 netmask 255.255.255.0 gw 10.1.1.2
route add -net 10.1.2.0 netmask 255.255.255.0 gw 10.1.2.2

ip route flush table net_nem1
ip route add default via 10.1.1.2 dev em1 src 10.1.1.241 table net_nem1
ip rule add from 10.1.1.241 table net_nem1
ip route flush table net_nem2
ip route add default via 10.1.2.2 dev em2 src 10.1.2.241 table net_nem2
ip rule add from 10.1.2.241 table net_nem2
```
As I mentioned before, this setting works fine on most applications.

**Comment by bundabrg** [comment] 2020-09-13 11:47
Thanks. I'll try reproduce the environment tomorrow and get back. Raknet has an annoying habit of embedding IP's in the packets which I suspect may be the issue here though I'm hoping its something I've overlooked.

**Comment by andrewathalye** [comment] 2020-09-16 23:44
This is somewhat related, but I've also observed that Geyser (built from master on 2020/09/16) seems to also allow only IPv4 connections with 0.0.0.0 set, and does not accept :: or 0:0:0:0:0:0:0:0(with or without %0) as a bind address. This may be an error within netty, as a netty bind fail is referenced in the latter two cases.

**Comment by Camotoy** [comment] 2021-05-22 00:27
This should be fixed with the new forward host option added in the Geyser config. If it's not, do let us know!

**Closed by Camotoy** 2021-05-22 00:27 UTC
