### ISSUE TITLE
CAN'T SEE WORLD BORDERS

### ISSUE THREAD

**Issue by ConnorServers** [GeyserMC/Geyser#2308] opened 2021-06-21 10:16 UTC
### Describe the bug

I run a skyblock server.
Each island has a 150x150 world border.
If the Bedrock player leaves that border (because they can't see it) they either crash or glitch and die.

### To Reproduce

create a worldborder and leave it.

### Expected behaviour

at the very least, can't go past border.
at the most, be able to both see border and not go past it.

### Screenshots / Videos

I dont have bedrock.
This is from multiple player complaints on my network.

### Server Version and Plugins

1.8.8 R0.2

### Geyser Dump

https://dump.geysermc.org/UO7MbWzoSforpT39EH5lXzW5Qd8RgC3H

### Geyser Version

1.4.0-SNAPSHOT (git-master-1df6e21)

### Minecraft: Bedrock Edition Version

N/A

### Additional Context

N/A

**Comment by rtm516** [comment] 2021-06-21 10:50
Duplicate of #447. Thank you for reporting anyway!

**Closed by rtm516** 2021-06-21 10:50 UTC
