### ISSUE TITLE
Bedrock skins not appearing on Bungeecord servers

### ISSUE THREAD

**Issue by IsaacTheDev** [GeyserMC/Geyser#2442] opened 2021-08-03 02:39 UTC
### Describe the bug

I have a Waterfall Proxy, along with Geyser Standalone, and Floodgate on my proxy and all backend servers. Everything is Up-to-date with all updates possible, with the proxy sending Floodgate data to other servers. When a bedrock player joins the Proxy they get automatically redirected to our Hub server, which when they have the skin uploaded to the GlobalAPI thing and a Java player looks at them they can see the skin. The issue happens when the bedrock player joins another server from that Hub server. The skin that was there once before ceases to show to anyone and displays as Steve/Alex to Java.

### To Reproduce

1. Create a PaperMC Waterfall Server with 2 servers (Hub and Survival) loaded with Floogate-Bungee and so the proxy puts you in the Hub server
2. Setup a Geyser Standalone with the auth set to Floodgate and the players sent to that Proxy
3. Make a PaperMC Hub/Survival server with Floodgate-Spigot
4. Join a bedrock player to that Standalone instance, and it should connect you to the hub where Java players should see the skin.
5. Then run your server join command or whatever (`/server survival`), the bedrock players skin will now disappear to everyone

### Expected behaviour

The bedrock players skin should be visible regardless of server joined

### Server Version and Plugins

Proxy: This server is running Waterfall version git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448 by md_5
Hub: This server is running Paper version git-Paper-778 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Survival: This server is running Paper version git-Paper-778 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Geyser Dump

https://dump.geysermc.org/BmUteidypWMZrJWInMl7aUmXHKTZIrtW

### Geyser Version

1.4.1-SNAPSHOT (git-master-3eb73a5)

### Minecraft: Bedrock Edition Version

Latest

**Comment by Camotoy** [comment] 2021-08-03 02:44
Likely a duplicate of https://github.com/GeyserMC/Floodgate/issues/147. Thanks anyway!

**Closed by Camotoy** 2021-08-03 02:44 UTC
