### ISSUE TITLE
Black boxes where the attack cooldown should be

### ISSUE THREAD

**Issue by MrRazamataz** [GeyserMC/Geyser#2032] opened 2021-03-12 21:15 UTC
### Describe the bug

When show attack cooldown is true, some players are reporting that black boxes appear on their screen within the attack cooldown time.

### To Reproduce

I have had trouble trying to reproduce it, but multiple players have reported it so its differently an issue. 
I asked them what they were running, one person said: 
1. Version: 1.16.210?
2. Mobile
3. Split controls
4. Classic gui mode

However, it happens with other players on different settings. 

### Expected behaviour

The normal fake attack cooldown should show. 

### Screenshots / Videos

Image 1: https://mrrazamataz.ga/archive/mcserver/Screenshot_20210311_234756.jpg
Image 2: https://mrrazamataz.ga/archive/mcserver/IMG_20210312_081630.png
Image 3: https://mrrazamataz.ga/archive/mcserver/20210311_202602.jpg

### Server Version and Plugins

This server is running Yatopia version git-Yatopia-ver/1.16.5-40 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Previous version: git-Yatopia-ver/1.16.5-36 (MC: 1.16.5)

Plugins (59): AuctionHouse, AutoAnnouncer*, AutoRestart*, BetterSleeping3, Citizens, CombatLogX, CoreProtect, DeathMessagesPrime, DiscordSRV, DiscordSRV-Staff-Chat, DMPMonitorCompat, EazyNick, Essentials, EssentialsGeoIP, EssentialsSpawn, GeyserSkinManager, Graves, HolographicDisplays, ImageOnMap, InvRestore*, LimitCreative, LiteBans, LuckPerms, mcMMO, MineEconomy*, MobBanners, MovingDevApi, MultiWorld*, MythicMobs, NPC_Destinations, Oh_the_dungeons_youll_go, PistonChat, PlaceholderAPI, Plan, PlayerWarps, PlugMan, ProtocolLib, PsudoCommand, QuickShop, Residence, RewardPRO, RttChat*, SaveRegion, Scoreboard-revision*, ServerlistMOTD*, SimplePets, SkinsRestorer, SkQuery, Skript, SuperVanish, Vault, Votifier*, VotingPlugin, WelcomeTitle*, Wild, WorldBorder, WorldEdit, WorldGuard, Worldstats*

### Geyser Dump

https://dump.geysermc.org/brO8VqVHtDj1Q8pyUMMpCQTqfJT0o8uE

### Geyser Version

This server is running Geyser version 1.2.0-SNAPSHOT (git-server-inventory-d4c21bb) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.210)

### Minecraft: Bedrock Edition Version

1.16.210 

### Additional Context

Server inventory branch 
Not all players have the issue

**Comment by Camotoy** [comment] 2021-03-12 21:16
Duplicate of #1710. Regardless, thank you for reporting!

**Closed by Camotoy** 2021-03-12 21:16 UTC
