### ISSUE TITLE
Can't switch to another Server

### ISSUE THREAD

**Issue by EpicJosch** [GeyserMC/Geyser#4191] opened 2023-10-06 14:26 UTC
### Describe the bug

When i join my bungeecord network everything works fine. But as soon as i switch the server i get disconnected and in the console there is the following error:

```
[16:08:43 INFO]: [/85.216.5.129:0|.Rotkauz] <-> DownstreamBridge <-> [lobby] has disconnected
[16:08:43 WARN] [Geyser-BungeeCord]: Downstream packet error! Unregistered serverbound packet class: com.github.steveice10.mc.protocol.packet.ingame.serverbound.player.ServerboundMovePlayerPosPacket
[16:08:43 WARN] [Geyser-BungeeCord]: Downstream packet error! Unregistered serverbound packet class: com.github.steveice10.mc.protocol.packet.ingame.serverbound.player.ServerboundPlayerCommandPacket
[16:08:43 WARN]: [/85.216.5.129:0|.Rotkauz] -> UpstreamBridge - bad packet, are mods in use!? No more bytes reading varint
[16:08:43 INFO]: [.Rotkauz] disconnected with: DecoderException : net.md_5.bungee.protocol.BadPacketException: No more bytes reading varint @ io.netty.handler.codec.MessageToMessageDecoder:98
[16:08:43 INFO] [floodgate]: Floodgate player logged in as .Rotkauz disconnected
[16:08:43 INFO] [Geyser-BungeeCord]: Rotkauz has disconnected from the Java server because of DecoderException : net.md_5.bungee.protocol.BadPacketException: No more bytes reading varint @ io.netty.handler.codec.MessageToMessageDecoder:98
[16:08:43 INFO]: [/85.216.5.129:0|.Rotkauz] -> UpstreamBridge has disconnected
[16:08:43 INFO]: [/85.216.5.129:0|.Rotkauz] <-> DownstreamBridge <-> [citybuild] has disconnected
```

This error does not happen always though. Sometimes i can switch the server without getting error but then when i move a bit on this server then switch server back to lobby and switch back to the other server again i get this error.

### To Reproduce

1. Connect to the network
2. Switch server

### Expected behaviour

- There should be no Decoder Exception when switching server

### Screenshots / Videos

![grafik](https://github.com/GeyserMC/Geyser/assets/50040609/f52231f1-57af-4fcb-b7cd-5703e3c7856a)

### Server Version and Plugins

Version: Well you cant use /version on bungeecord but im running "waterfall-1.20-544"
Plugins:
![grafik](https://github.com/GeyserMC/Geyser/assets/50040609/948ab436-5de7-481b-8514-7a181ff7c69d)

### Geyser Dump

https://dump.geysermc.org/F2WzgeDWhU1qadbO8oJ9Tep27GbKHCse

### Geyser Version

2.2.0-SNAPSHOT (git-master-82541a5) (Java: 1.20.2, Bedrock: 1.20.0/1.20.1 - 1.20.30/1.20.31)

### Minecraft: Bedrock Edition Device/Version

1.20.32 (Windows 10 and iOS)

**Comment by hasankayra04** [comment] 2023-10-06 14:29
Please send logs from both Waterfall and the server you are trying to connect to. 

Upload your latest.log file to https://mclo.gs hit save and send the link here.

**Comment by Kas-tle** [comment] 2023-10-06 14:32
This issue is likely related to some bungee plugin that needs to be updated sending packets to the player while they are still in the config phase. Please try to reproduce without any plugins other than Geyser and Floodgate on the proxy

**Comment by EpicJosch** [comment] 2023-10-06 14:45
Waterfall Log: https://mclo.gs/qHhhvAI
Spigot Log: https://mclo.gs/jG2mMSe

**Comment by EpicJosch** [comment] 2023-10-06 14:49
With no others plugins on the proxy i have the same issue

**Comment by EpicJosch** [comment] 2023-10-06 19:14
> Please send logs from both Waterfall and the server you are trying to connect to.
> 
> Upload your latest.log file to https://mclo.gs hit save and send the link here.

just posted the logs

**Comment by EpicJosch** [comment] 2023-10-07 04:24
Also everything worked fine until I updated to the latest build of papermc-1.20.1

From there on this issue started occurring

**Comment by EpicJosch** [comment] 2023-10-07 08:31
@hasankayra04 @Kas-tle i now updated via version and via backwards and now i dont get any error message on the server i try to switch to. I only get the error in the proxy and still the exact same issue..

**Comment by EpicJosch** [comment] 2023-10-07 08:34
Those are the new logs after veaversion update:

Waterfall: https://mclo.gs/NoqGd0z
Paper: https://mclo.gs/LqIqAVk

**Comment by EpicJosch** [comment] 2023-10-08 17:45
Switched to Geyser stand-alone now. Exact same error. Also same errors in logs.

**Comment by EpicJosch** [comment] 2023-10-09 04:14
@onebeastchris what more info do you need?

**Comment by EpicJosch** [comment] 2023-10-09 09:06
I guess the problem is solved. My problem was that i used bungee portals to switch server. I don't know why but that caused the issue. When i use /server <Servername> it workes perfectly. But this should be solved anyway because its pretty bad if it does not work with portals...

**Comment by EpicJosch** [comment] 2023-10-09 09:17
I found out that this issue only occurres when I jump into the portal. When I walk in straight then the error is not occurring.

**Comment by onebeastchris** [comment] 2023-10-09 09:20
Well, as Kastle already mentioned (https://github.com/GeyserMC/Geyser/issues/4191#issuecomment-1750783853), it's likely an issue where said plugin might be sending data during the configuration phase instead of the play phase, which leads to Geyser's downstream error. This could be an issue with BungeeCord (if e.g. said portals plugin is using bungee api which might mess with configuration states improperly), or with how the plugin manually sends packets - in any case, you may want to try & attempt to reproduce that issue with a 1.20.2 Java client and reach out to that plugins author.

**Comment by EpicJosch** [comment] 2023-10-09 09:36
Well fair enough..

**Comment by EpicJosch** [comment] 2023-10-09 09:51
No. This issue is NOT occuring with an 1.20.2 Java Client. So it is an Geyser issue

**Comment by EpicJosch** [comment] 2023-10-09 10:44
I tried again and now I'm also getting this issue when walking normal in the portal. So same problem again. Just don't work..

**Comment by EpicJosch** [comment] 2023-10-09 10:50
We can't say it's because of other plugins since it only occurres on bedrock. Also a month ago server switching worked perfectly fine on bedrock also with jumping in portals..

**Comment by EpicJosch** [comment] 2023-10-09 12:08
I tested again and using the build in /server command also causes the issue.

**Comment by EpicJosch** [comment] 2023-10-09 12:53
Okay see I REALLY don't know what I should do to fix this @onebeastchris I tried everything! I even ran the server with NO plug-ins except geyser and floodgate. And this exception just keeps occurring. I even tried multiple different paper and waterfall builds but still always the same issue. Really need some help here!

**Comment by MattTheTekie** [comment] 2023-10-09 16:48
> Okay see I REALLY don't know what I should do to fix this @onebeastchris I tried everything! I even ran the server with NO plug-ins except geyser and floodgate. And this exception just keeps occurring. I even tried multiple different paper and waterfall builds but still always the same issue. Really need some help here!

same here

**Comment by MattTheTekie** [comment] 2023-10-09 16:49
It's really annoying.

**Comment by TylerJohnson177** [comment] 2023-10-09 17:52
I am having the exact same issue with my bungeecord server network. At least for me, using /server servername works fine. The issue only arises when I try to switch to a different server via entering a portal. I am using the latest version of SimplePortals plugin. I would say that around 50% to 70% of the time, bedrock players get this error when switching servers via a portal.

**Comment by MattTheTekie** [comment] 2023-10-09 17:59
> I am having the exact same issue with my bungeecord server network. At least for me, using /server servername works fine. The issue only arises when I try to switch to a different server via entering a portal. I am using the latest version of SimplePortals plugin. I would say that around 50% to 70% of the time, bedrock players get this error when switching servers via a portal.

I'm having roughly the same error margin.

**Comment by EpicJosch** [comment] 2023-10-09 18:27
@TylerJohnson177 

I was also using SimplePortals before. With CMI it worked a **little bit** better but not nearly a solution.. i switched to NPC's now (Plugin: Citizens) with the NPC it works 90% of the time. I testet a few times with NPC's but when i jump and click the npc at the same time (running to npc while jumping) the same error occures again. Its a workaround but this issue really needs to be fixed!

**Comment by Kas-tle** [comment] 2023-10-09 18:32
It is still likely a Java issue but is more likely to occur with Geyser on average tends to remain in the config phase longer than the normal Java client. There's nothing we can do about this. And when a client is in the config phase, a plugin should not be sending it packets that it's not yet ready to receive yet. Otherwise bungee will throw the error seen here. 

These plugins need to be updated to not send packets to the client when it is in the config phase.

**Comment by EpicJosch** [comment] 2023-10-09 19:47
Did you even read my comments? I tried it with **NO PLUG-INS** installed but geyser and floodgate and it still occurred. So there are no plug-ins sending packets in config phase!

**Comment by EpicJosch** [comment] 2023-10-09 19:48
And also as I said a month ago it worked with SimplePortals!

**Comment by Kas-tle** [comment] 2023-10-09 19:58
Then SimplePortals is trying to send packets before it is safe to do so. Please open an issue with them.

**Comment by MattTheTekie** [comment] 2023-10-09 20:12
> Then SimplePortals is trying to send packets before it is safe to do so. Please open an issue with them. One month ago Geyser was still on 1.20.1 so there was no config phase. I'm using https://www.spigotmc.org/resources/deluxehub-3-professional-hub-management.49425/

**Comment by MattTheTekie** [comment] 2023-10-09 20:13
> Did you even read my comments? I tried it with **NO PLUG-INS** installed but geyser and floodgate and it still occurred. So there are no plug-ins sending packets in config phase!

I've had the same issue. I did try it clean before a few times

**Comment by TylerJohnson177** [comment] 2023-10-09 20:16
I don't think SimplePortals has anything to do with this issue. I was able to replicate the problem by teleporting myself 500 blocks in the sky and by running "/server servername" mid free fall. This may be an issue with Bungeecord/Waterfall, but I was unable to replicate it on a Java 1.20.2 client. I tried to replicate it about 50 times.

When I use the 1.20.1 version of Geyser Stand-alone (which supports bedrock 1.20.30) the issue does not occur.

**Comment by onebeastchris** [comment] 2023-10-09 20:19
That's because 1.20.1 doesn't have the Configuration/Play phase setup that 1.20.2 introduced.
Geyser is receiving play-phase packets from bungee/other plugins while being in the configuration phase (again, after the server sent us that phase).
This could be a BungeeCord issue, or a plugin sending packets manually. If you look at the existing issues with proxies on 1.20.2 - heck, the reason why Velocity is delayed - it's due to this newly added complexity.

**Comment by MattTheTekie** [comment] 2023-10-09 20:20
> That's because 1.20.1 doesn't have the Configuration/Play phase setup that 1.20.2 introduced. Geyser is receiving play-phase packets from bungee/other plugins while being in the configuration phase (again, after the server sent us that phase). This could be a BungeeCord issue, or a plugin sending packets manually. If you look at the existing issues with proxies on 1.20.2 - heck, the reason why Velocity is delayed - it's due to this newly added complexity.

Can someone open a issue with BungeeCord?

**Comment by MattTheTekie** [comment] 2023-10-09 20:42
I think I found the issue
https://github.com/SpigotMC/BungeeCord/issues/3542

**Comment by MattTheTekie** [comment] 2023-10-09 20:47
@Kas-tle The project needs to implement around this limitation or this will cause issues. Check the linked issue.

**Comment by MattTheTekie** [comment] 2023-10-09 20:51
The fact that it doesn't happen without geyser and works fine on normal java, means it's a geyser implementation issue.

**Comment by Kas-tle** [comment] 2023-10-12 02:54
On closer examination if this is the fault of the movement packets we can probably block sending them.

**Comment by Kas-tle** [comment] 2023-10-12 04:59
This should be resolved by https://github.com/GeyserMC/Geyser/pull/4210
Please feel free to test with the artifacts here: https://github.com/GeyserMC/Geyser/actions/runs/6491305641
I am sorry for misunderstanding the issue.

**Closed** 2023-10-12 13:02 UTC
Labels: Unconfirmed Bug/Not Currently Replicable, Suspected Server Behavior

**Comment by MattTheTekie** [comment] 2023-10-13 14:44
It seems to work for me

**Comment by MattTheTekie** [comment] 2023-10-13 14:44
ty
