### ISSUE TITLE
Failed to Encrypt Message

### ISSUE THREAD

**Issue by Azrian0** [GeyserMC/Geyser#4616] opened 2024-04-29 14:32 UTC
### Describe the bug

Trying to connect to java 1.20.4 server on latest bedrock version. When connecting to the server ip and port I receive a "Failed to encrypt message" error. 

### To Reproduce

1. Have updated geyser and floodgate
2. Attempt to join server with IP and Port
3. Receive error for "Failed to encrypt message"

### Expected behaviour

I expect to be able to join the server

### Screenshots / Videos

![ApplicationFrameHost_MsLsovx1mD](https://github.com/GeyserMC/Geyser/assets/54731285/1a2af6f7-9ef2-40ef-957f-ef506b531ccf)

### Server Version and Plugins

Paper version git-Paper-496 (MC: 1.20.4)
Geyser build #515
Floodgate build #100 

Plugins:
DiscordSRV, FastAsyncWorldEdit, floodgate, Geyser-Spigot, GPFlags, GriefPrevention, GSit, HeadDatabase, ImageFrame, LuckPerms, MoDispenserMechanics, ProtocolLib, SimpleTpa, UltimateHomes, UltimateTimber, ViaVersion

### Geyser Dump

https://dump.geysermc.org/zsmTDlr3cLbEuXHfElGXY2zIRIXR5ZWX

### Geyser Version

Build #515

### Minecraft: Bedrock Edition Device/Version

1.20.80

**Comment by onebeastchris** [comment] 2024-05-02 10:21
Likely a duplicate of #2861 - please try updating java as described there

**Comment by onebeastchris** [comment] 2024-06-06 17:17
Closing as duplicate.

**Closed by onebeastchris** 2024-06-06 17:17 UTC
Labels: Waiting On Response, Possible Duplicate
