### ISSUE TITLE
Text on signs doesn’t save on Bedrock

### ISSUE THREAD

**Issue by Garfieldwxg55** [GeyserMC/Geyser#1909] opened 2021-02-08 03:38 UTC
Hi, I’ve been using GeyserMC on my SMP for a few months now, and recently I discovered a glitch involving text on signs. I was using my Switch and placed down a sign which I wrote some text on, but when I left the server and rejoined, I noticed that although the signs were there the text which I typed on it was not.

Steps to reproduce:
1. Join a server from a bedrock client
2. Place down a sign and write some text on it
3. Exit the server
4. Rejoin the server and noticed the sign is missing the text which was typed on it

Geyser version:
GeyserMC #604

Server API:
PaperMC #465

**Comment by Camotoy** [comment] 2021-02-08 03:40
This is likely a duplicate of #1063 - it triggers when you press enter on some platforms.

Therefore, I am going to close this. If you believe this is in error, please let me know. Thank you!

**Closed by Camotoy** 2021-02-08 03:40 UTC
