### ISSUE TITLE
Chat starting with a period . is sent as a /command

### ISSUE THREAD

**Issue by Jakesta13** [GeyserMC/Geyser#1516] opened 2020-11-08 17:46 UTC
**Describe the bug**
Any message sent where the first character is a period '.' Geyser sends it as a command to the server.
This can be worked around by back-slash escaping the first character and Geyser will send it as a chat message without the initial back-slash.
(E.g "\\.home" will work around it and send ".home" as intended.)

**To Reproduce**

1. Try to send ".home" for example
2. Recieve server warning that "/home" is not a valid command.

**Expected behavior**

To send ".home" (or any other message with an initial period) to the server.

**Screenshots / Videos**

https://streamable.com/z5vwx3

**Server Version**

1.16.4

**Geyser Version**

Geyser version 1.1.0 (git-master-2d95302) (Java: 1.16.4, Bedrock: 1.16.0 - 1.16.20)

**Minecraft: Bedrock Edition Version**

v1.16.50

**Additional Context**

https://dump.geysermc.org/RJAB338aLmcLfX8eZDtfboPpuixjJgpB

**Comment by rtm516** [comment] 2020-11-08 17:54
This is an intended feature and a duplicate of https://github.com/GeyserMC/Geyser/issues/1309
See https://github.com/GeyserMC/Geyser/issues/462 for more information.

**Closed by rtm516** 2020-11-08 17:54 UTC
