### ISSUE TITLE
Native fill command doesnt effect BE players

### ISSUE THREAD

**Issue by anar4732** [GeyserMC/Geyser#792] opened 2020-06-20 08:12 UTC
**Describe the bug**

Native fill command doesnt effect BE players

**To Reproduce**

 1. Set a command block to fill command
 2. run it
 3. see blocks placed on JE but not in BE

**Expected behavior**

**Screenshots / Videos**

**Server Version**

**Geyser Version**

**Minecraft: Bedrock Edition Version**

**Additional Context**

**Comment by Heath123** [comment] 2020-06-20 08:13
Please fill in the issue template next time

**Comment by Heath123** [comment] 2020-06-20 08:14
Duplicate of #399

**Closed** 2020-06-20 08:14 UTC
