### ISSUE TITLE
Falling out of world doesn't kill player

### ISSUE THREAD

**Issue by elliotnash** [GeyserMC/Geyser#824] opened 2020-06-28 06:54 UTC
**Describe the bug**
Falling out of the world does not kill you and you instead get stuck at the bottom of the world.

**To Reproduce**
1) be in creative mode
2) tunnel down to the bottom of the world and break the bedrock
3) fall through the world and not die

**Expected behavior**
Expected to take damage and fall out of the world/die

**Server Version**
waterfall 1.16-R0.1-SNAPSHOT:6bfefea:357
spigot 1.16.1 : git-spigot-1a27cfd-d77f4d9

**Geyser Version**
Geyser build #39 of feature/1.16
Floodgate #24

**Minecraft: Bedrock Edition Version**
bedrock 1.16.0

**Additional Context**
No other plugins on the server

**Comment by Mari023** [comment] 2020-06-28 07:17
This also happens if you are in survival mode, and have some sort of fall damage protection.
This happens since in bedrock edition, the void is not endless but you rather fall onto a platform at y = -40.
if you are in survival, and fall in the void, your death message will be "fell from a high place" instead of "fell out of the world"

**Comment by DoctorMacc** [comment] 2020-06-28 14:34
Duplicate of #406 (though it was previously closed). Thank you for reporting anyway!

**Closed by DoctorMacc** 2020-06-28 14:34 UTC
