### ISSUE TITLE
Old Spigot versions don't have mining animation!! (BUG!)

### ISSUE THREAD

**Issue by WolfyRed** [GeyserMC/Geyser#1765] opened 2020-12-30 21:59 UTC
_Old Spigot versions don't have mining animation!! (BUG!)_

**Describe the bug**
In Survival mode, if you are breaking a block, it will not have the mining animation!

**To Reproduce**

  1. Go to a block in survival! (Any block!) 
  2. Hold-click on it (if on PC, if not on pc hold RT/hold finger/etc!) 
  3. It will not produce the mining animation! 
  4. That's,,, it. 

**Expected behavior**
A mining animation whilst breaking a block (in Survival mode), since it's client side.

**Screenshots / Videos**
https://user-images.githubusercontent.com/66114400/103383313-43680980-4ac0-11eb-9fc8-dc31ab1054bb.mp4

**Server Version**
The 'final' build of 1.12.

**Geyser Version**
Geyser 1.2.0-SNAPSHOT (git-master-77de991) 

**Minecraft: Bedrock Edition Version**
v1.16.201 !

**Additional Context**
I run Geyser and ViaVersion plugins, all in... A Spigot server. Typical.

**Comment by Camotoy** [comment] 2020-12-30 22:53
This is a duplicate of #963. Thank you regardless for reporting!

**Closed by Camotoy** 2020-12-30 22:53 UTC

**Comment by WolfyRed** [comment] 2020-12-30 23:05
> This is a duplicate of #963. Thank you regardless for reporting!

Did you know about the Villager trading broken for all clients and Command blocks not opening for Java clients in older Spigot versions too?

**Comment by Camotoy** [comment] 2020-12-30 23:09
We know about villager trading not working for older versions.

**Comment by WolfyRed** [comment] 2020-12-30 23:11
> We know about villager trading not working for older versions.

Well do I just change my Geyser version to updated to fix the block animation and chunk issues, or do I need to go into the files of the world to fix it?

**Comment by Camotoy** [comment] 2020-12-30 23:11
The solution right now to fix villager trading is to do it on Java Edition or update your server, unfortunately.

**Comment by WolfyRed** [comment] 2020-12-30 23:15
> The solution right now to fix villager trading is to do it on Java Edition or update your server, unfortunately.

I actually meant the original issues I had in this cawse

**Comment by Camotoy** [comment] 2020-12-30 23:25
You need to update your Geyser version from here: https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/

**Comment by WolfyRed** [comment] 2020-12-30 23:39
> You need to update your Geyser version from here: https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/

The block animations will still not show... so I assume there is a setting that I must change in the plugin.

**Comment by Camotoy** [comment] 2020-12-30 23:40
This is a bug on our end that we will fix in the future. If you desperately need these, update to 1.16 Java.
