### ISSUE TITLE
Bedrock players crash when joining servers

### ISSUE THREAD

**Issue by MrNipz** [GeyserMC/Geyser#4260] opened 2023-10-31 10:58 UTC
### Describe the bug

Bedrock players on my server are reporting that they crash when they load in. Or when they load into spawn. Except there skyblock islands for some reason i tested this on other servers and i just crash upon joining.

### To Reproduce

Join a server

### Expected behaviour

client will crash

### Server Version and Plugins

Geyser version 2.2.0-SNAPSHOT (git-master-2e68244) (Java: 1.20.2, Bedrock: 1.20.0/1.20.1 - 1.20.40)

### Geyser Dump

https://dump.geysermc.org/cPoPIlwaKcBH3wrIveTtjCLaX9XMsRYr

### Geyser Version

2.2.0-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.20.40

**Comment by onebeastchris** [comment] 2023-10-31 10:59
Duplicate of https://github.com/GeyserMC/Geyser/issues/4240

**Comment by onebeastchris** [comment] 2023-10-31 11:00
Additionally, your Geyser version is behind by one commit - try updating to that version, it has a temporary fix.

**Closed** 2023-10-31 10:59 UTC
Labels: Duplicate
