### ISSUE TITLE
Bedrock players getting time out in 10 minutes

### ISSUE THREAD

**Issue by raksodnus61** [GeyserMC/Geyser#4032] opened 2023-08-04 16:34 UTC
### Describe the bug

on version 1.20.10 and latest my geyser connected players getting time out and kicking from server
no any effective on java players only getting bedrock players

### To Reproduce

1. Start the server
2. join 1 bedrock and 1 Java player
3. maybe 9, maybe 10 minutes after kicking bedrockplayer
4. alonely java player :(

### Expected behaviour

I expecting bedrock players are not get timeout

### Screenshots / Videos

N/A

### Server Version and Plugins

Bungee / Waterfall •  
Floodgate • Towny

### Geyser Dump

https://dump.geysermc.org/CHwc3nZ5x4wZNsQx9ECbpjZ6j9aSFuil

### Geyser Version

Geyser-BungeeCord version 2.1.2-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.20.10 - 1.19.80 / 1.19.82

### Additional Context

[19:36:47] [defaultEventLoopGroup-5-3/INFO] [Geyser-BungeeCord]: uWuKing00 has disconnected from the Java server because of Bedrock client disconnected
[19:36:47] [Netty Worker IO Thread #4/INFO] [floodgate]: Floodgate player logged in as uWuKing disconnected
[19:36:47] [Netty Worker IO Thread #4/INFO]: [/78.190.138.75:0|uWuKing -> UpstreamBridge has disconnected
[19:36:47] [Netty Worker IO Thread #4/INFO]: [/78.190.138.75:0|uWuKing] <-> DownstreamBridge <-> [t181q] has disconnected

**Comment by onebeastchris** [comment] 2023-08-04 16:35
Duplicate of https://github.com/GeyserMC/Geyser/issues/4031, closing.

**Comment by raksodnus61** [comment] 2023-08-04 16:36
> Duplicate of #4031, closing.

but no ansver for #4031 ?

**Closed** 2023-08-04 16:36 UTC

**Comment by raksodnus61** [comment] 2023-08-04 16:44
> Duplicate of #4031, closing.

I know I'm very tight, but what do you suggest I do? I can't sleep for a week because of this, my server is hurting and I can't get help from you, please show me a way (sorry for English)
