### ISSUE TITLE
I want to customize the login page

### ISSUE THREAD

**Issue by Jerry12228** [GeyserMC/Geyser#3376] opened 2022-10-31 09:52 UTC
### What feature do you want to see added?

I want to be able to customize the client login page when using online mode
That is, the following page

![Screenshot_20221031_175016_com mojang minecraftpe](https://user-images.githubusercontent.com/86408775/198980534-f5cd3dff-4578-4b21-82a9-b90ebdaf6bd8.jpg)
![Screenshot_20221031_175022_com mojang minecraftpe](https://user-images.githubusercontent.com/86408775/198980558-d3703a2f-446c-4fb5-bb31-14a9155e364b.jpg)

### Are there any alternatives?

I didn't find another alternatives.

**Comment by onebeastchris** [comment] 2022-10-31 09:54
wdym by "customize"?
if you want to remove it, you can use floodgate - this would allow bedrock players to play without needing a java account

**Comment by Jerry12228** [comment] 2022-10-31 09:59
> wdym by "customize"? if you want to remove it, you can use floodgate - this would allow bedrock players to play without needing a java account

My server needs to use an external login server account to log in, and genuine users are not allowed to join directly. However, the options here are not clear, so I want to customize them
(I use Yggdrasil API and [Authlib Injector](https://github.com/yushijinhun/authlib-injector) to implement external login)

**Comment by onebeastchris** [comment] 2022-11-03 21:14
tbh, thinking about it - this sounds a lot like a login plugin
you could theoretically make your server + geyser offline mode, and implement a login yourself (similar to auth plugins..)
although this doesn't sound like a secure solution/supported one

**Comment by Chew** [comment] 2022-11-03 23:20
This is a duplicate of #2059, but I'll link a comment that basically states the situation here.  https://github.com/GeyserMC/Geyser/issues/2059#issuecomment-846712422

**Closed** 2022-11-03 23:20 UTC
Labels: Feature Request
