### ISSUE TITLE
Geyser-Spigot: Could not pass event ServerLoadEvent to Geyser-Spigot v2.2.2-SNAPSHOT

### ISSUE THREAD

**Issue by larsalbrecht** [GeyserMC/Geyser#4492] opened 2024-03-13 15:46 UTC
### Describe the bug

Current version (hash: 5764df28c88bbbb7fe48b254133b5005d4f4c01894551a1ca13ddf374caa948b) of Geyser (updated today) throws error during server start.

The result is:
- Java Users can join
- Bedrock Users cant join

Dump cannot be build. If I type `/geyser dump`, it just shows `/geyser <subcommand>`

### To Reproduce

Update to latest version of Geyser (Spigot).
Restart Server
See logs

### Expected behaviour

Server starts without exception and Bedrock players can join

### Screenshots / Videos

```
>....
[16:15:37 INFO]: [Geyser-Spigot] ******************************************
>....
[16:15:37 INFO]: [Geyser-Spigot] 
>....
[16:15:37 INFO]: [Geyser-Spigot] Loading Geyser version 2.2.2-SNAPSHOT (git-master-a9467cf)
>....
[16:15:37 INFO]: [Geyser-Spigot] 
>....
[16:15:37 INFO]: [Geyser-Spigot] ******************************************
>....
[16:16:05 ERROR]: Could not pass event ServerLoadEvent to Geyser-Spigot v2.2.2-SNAPSHOT
java.lang.ExceptionInInitializerError: null
	at org.geysermc.geyser.network.netty.GeyserServer.<init>(GeyserServer.java:115) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.GeyserImpl.startInstance(GeyserImpl.java:405) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.GeyserImpl.initialize(GeyserImpl.java:237) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.GeyserImpl.start(GeyserImpl.java:789) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin.onGeyserEnable(GeyserSpigotPlugin.java:214) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin$1.onServerLoaded(GeyserSpigotPlugin.java:198) ~[Geyser-Spigot.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-450]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-450]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-450]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:672) ~[paper-1.20.4.jar:git-Paper-450]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-450]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-450]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-450]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-450]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NumberFormatException: For input string: "20+rpt"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:665) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:781) ~[?:?]
	at org.geysermc.geyser.network.netty.Bootstraps.fromString(Bootstraps.java:93) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.network.netty.Bootstraps.<clinit>(Bootstraps.java:60) ~[Geyser-Spigot.jar:?]
	... 18 more
```

### Full Log ###

```
[17:08:28] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[17:08:37] [ServerMain/INFO]: Loaded 1174 recipes
[17:08:39] [ServerMain/INFO]: Loaded 1271 advancements
[17:08:40] [Server thread/INFO]: Starting minecraft server version 1.20.4
[17:08:40] [Server thread/WARN]: ****************************
[17:08:40] [Server thread/WARN]: YOU ARE RUNNING THIS SERVER AS AN ADMINISTRATIVE OR ROOT USER. THIS IS NOT ADVISED.
[17:08:40] [Server thread/WARN]: YOU ARE OPENING YOURSELF UP TO POTENTIAL RISKS WHEN DOING THIS.
[17:08:40] [Server thread/WARN]: FOR MORE INFORMATION, SEE https://madelinemiller.dev/blog/root-minecraft-server/
[17:08:40] [Server thread/WARN]: ****************************
[17:08:40] [Server thread/INFO]: Loading properties
[17:08:40] [Server thread/INFO]: This server is running Paper version git-Paper-450 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 62b220a)
[17:08:42] [Server thread/INFO]: Server Ping Player Sample Count: 12
[17:08:42] [Server thread/INFO]: Using 4 threads for Netty based IO
[17:08:43] [Server thread/WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[17:08:44] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads
[17:08:45] [Server thread/INFO]: Default game type: SURVIVAL
[17:08:45] [Server thread/INFO]: Generating keypair
[17:08:45] [Server thread/INFO]: Starting Minecraft server on *:25565
[17:08:45] [Server thread/INFO]: Using epoll channel type
[17:08:46] [Server thread/INFO]: Paper: Using libdeflate (Linux aarch64) compression from Velocity.
[17:08:46] [Server thread/INFO]: Paper: Using OpenSSL (Linux aarch64) cipher from Velocity.
[17:08:47] [Server thread/WARN]: [org.bukkit.craftbukkit.v1_20_R3.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[17:09:04] [Server thread/INFO]: [ViaVersion] Loading server plugin ViaVersion v4.9.4-SNAPSHOT
[17:09:04] [Server thread/INFO]: [ViaVersion] ViaVersion 4.9.4-SNAPSHOT is now loaded. Registering protocol transformers and injecting...
[17:09:06] [Via-Mappingloader-0/INFO]: [ViaVersion] Loading block connection mappings ...
[17:09:07] [Via-Mappingloader-0/INFO]: [ViaVersion] Using FastUtil Long2ObjectOpenHashMap for block connections
[17:09:07] [Server thread/INFO]: [floodgate] Loading server plugin floodgate v2.2.2-SNAPSHOT (b96-7f38765)
[17:09:09] [Server thread/INFO]: [floodgate] Took 2,282ms to boot Floodgate
[17:09:10] [Server thread/INFO]: [Geyser-Spigot] Loading server plugin Geyser-Spigot v2.2.2-SNAPSHOT
[17:09:12] [Server thread/INFO]: [Geyser-Spigot] Loading extensions...
[17:09:12] [Server thread/INFO]: [Geyser-Spigot] Loaded 0 extension(s)
[17:09:19] [Server thread/INFO]: Preparing level "world"
[17:09:21] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[17:09:22] [Server thread/INFO]: Time elapsed: 1008 ms
[17:09:22] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[17:09:23] [Server thread/INFO]: Time elapsed: 702 ms
[17:09:23] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[17:09:23] [Server thread/INFO]: Time elapsed: 437 ms
[17:09:39] [Server thread/INFO]: [ViaVersion] Enabling ViaVersion v4.9.4-SNAPSHOT
[17:09:40] [Server thread/INFO]: [ViaVersion] ViaVersion detected server version: 1.20.3/1.20.4 (765)
[17:09:40] [Server thread/WARN]: [ViaVersion] ViaVersion does not have any compatible versions for this server version!
[17:09:40] [Server thread/WARN]: [ViaVersion] Please remember that ViaVersion only adds support for versions newer than the server version.
[17:09:40] [Server thread/WARN]: [ViaVersion] If you need support for older versions you may need to use one or more ViaVersion addons too.
[17:09:40] [Server thread/WARN]: [ViaVersion] In that case please read the ViaVersion resource page carefully or use https://viaversion.com/setup
[17:09:40] [Server thread/WARN]: [ViaVersion] and if you're still unsure, feel free to join our Discord-Server for further assistance.
[17:09:40] [Server thread/INFO]: [floodgate] Enabling floodgate v2.2.2-SNAPSHOT (b96-7f38765)
[17:09:43] [Server thread/INFO]: [Geyser-Spigot] Enabling Geyser-Spigot v2.2.2-SNAPSHOT
[17:10:05] [Server thread/INFO]: [Geyser-Spigot] ******************************************
[17:10:05] [Server thread/INFO]: [Geyser-Spigot] 
[17:10:05] [Server thread/INFO]: [Geyser-Spigot] Loading Geyser version 2.2.2-SNAPSHOT (git-master-a9467cf)
[17:10:05] [Server thread/INFO]: [Geyser-Spigot] 
[17:10:05] [Server thread/INFO]: [Geyser-Spigot] ******************************************
[17:10:33] [Server thread/ERROR]: Could not pass event ServerLoadEvent to Geyser-Spigot v2.2.2-SNAPSHOT
java.lang.ExceptionInInitializerError: null
	at org.geysermc.geyser.network.netty.GeyserServer.<init>(GeyserServer.java:115) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.GeyserImpl.startInstance(GeyserImpl.java:405) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.GeyserImpl.initialize(GeyserImpl.java:237) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.GeyserImpl.start(GeyserImpl.java:789) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin.onGeyserEnable(GeyserSpigotPlugin.java:214) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin$1.onServerLoaded(GeyserSpigotPlugin.java:198) ~[Geyser-Spigot.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-450]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-450]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-450]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:672) ~[paper-1.20.4.jar:git-Paper-450]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-450]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-450]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-450]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-450]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NumberFormatException: For input string: "20+rpt"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:665) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:781) ~[?:?]
	at org.geysermc.geyser.network.netty.Bootstraps.fromString(Bootstraps.java:93) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.network.netty.Bootstraps.<clinit>(Bootstraps.java:60) ~[Geyser-Spigot.jar:?]
	... 18 more
[17:10:33] [Server thread/INFO]: Running delayed init tasks
[17:10:33] [Craft Scheduler Thread - 5 - ViaVersion/INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[17:10:35] [Server thread/WARN]: [ViaVersion] You are running a development version of the plugin, please report any bugs to GitHub.
[17:10:35] [Server thread/INFO]: Done (115.171s)! For help, type "help"
[17:10:35] [Server thread/INFO]: Timings Reset
```

### Server Version and Plugins

Server Version: 1.20.4

Installed Plugins:
- Floodgate-Spigot
- Geyser-Spigot
- ViaVersion

### Geyser Dump

Dump cannot be build. If I type `/geyser dump`, it just shows `/geyser <subcommand>`

### Geyser Version

2.2.2-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

Android

**Comment by Kas-tle** [comment] 2024-03-13 16:15
Please post the entire startup log

**Comment by onebeastchris** [comment] 2024-03-13 16:17
it seems like this issue is caused by the version parsing in the `Bootstraps` file.. sounds like we need to adapt that

**Comment by Kas-tle** [comment] 2024-03-13 16:18
How would it only be happening here though?

**Comment by Kas-tle** [comment] 2024-03-13 16:19
Or is that a recent paper update?

**Comment by Kas-tle** [comment] 2024-03-13 16:21
Oh, that PR

**Comment by larsalbrecht** [comment] 2024-03-13 16:24
> Please post the entire startup log

Added in the opening post

**Comment by onebeastchris** [comment] 2024-03-13 22:39
Out of curiosity, are you hosting this on a raspberry pi?

**Comment by larsalbrecht** [comment] 2024-03-13 22:40
> Out of curiosity, are you hosting this on a raspberry pi?
@onebeastchris 
Yes, inside a Docker Container

**Comment by onebeastchris** [comment] 2024-03-13 22:43
That would explain why the kernel version returned that suffix... which isn't a number, which well, fails when we try to parse one. I'll try and add an exception catch tomorrow to just fall back to no port reusing; that should resolve this issue

**Comment by Camotoy** [comment] 2024-03-14 02:39
Sounds like a good idea, but maybe we can either strip the `+` part, or we can see if the rest of the Linux kernel string would exceed the required version.

**Comment by onebeastchris** [comment] 2024-03-14 14:25
Could you try the build from the linked PR (see the `Checks` tab) and see if that works?

**Comment by larsalbrecht** [comment] 2024-03-14 15:51
> Could you try the build from the linked PR (see the `Checks` tab) and see if that works?

```
[16:48:54 INFO]: [Geyser-Spigot] ******************************************
[16:48:54 INFO]: [Geyser-Spigot] 
[16:48:54 INFO]: [Geyser-Spigot] Loading Geyser version 2.2.2-SNAPSHOT (git-master-c91ee53)
[16:48:54 INFO]: [Geyser-Spigot] 
[16:48:54 INFO]: [Geyser-Spigot] ******************************************
[16:49:27 ERROR]: Could not pass event ServerLoadEvent to Geyser-Spigot v2.2.2-SNAPSHOT
java.lang.ExceptionInInitializerError: null
	at org.geysermc.geyser.network.netty.GeyserServer.<init>(GeyserServer.java:115) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.GeyserImpl.startInstance(GeyserImpl.java:405) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.GeyserImpl.initialize(GeyserImpl.java:237) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.GeyserImpl.start(GeyserImpl.java:789) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin.onGeyserEnable(GeyserSpigotPlugin.java:214) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin$1.onServerLoaded(GeyserSpigotPlugin.java:198) ~[Geyser-Spigot.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-450]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-450]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-450]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:672) ~[paper-1.20.4.jar:git-Paper-450]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-450]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-450]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-450]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-450]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NumberFormatException: For input string: "20+rpt"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:665) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:781) ~[?:?]
	at org.geysermc.geyser.network.netty.Bootstraps.fromString(Bootstraps.java:93) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.network.netty.Bootstraps.<clinit>(Bootstraps.java:60) ~[Geyser-Spigot.jar:?]
	... 18 more
```

Unfortunately does not work

**Comment by larsalbrecht** [comment] 2024-03-14 15:55
I think this can help you. It is missing in the minecraft logs:
> System Info: Java 19 (OpenJDK 64-Bit Server VM 19.0.2+7-Ubuntu-4) Host: Linux 6.6.20+rpt-rpi-v8 (aarch64)

**Comment by onebeastchris** [comment] 2024-03-14 16:16
just turn on `debug-mode` in the geyser config, that should print it + the error 
Regardless, @Kas-tle has proposed a different, more robust solution to version parsing; I'll try to get that running & update you here

**Comment by onebeastchris** [comment] 2024-03-14 16:17
and fyi the new log you've sent shows you still using the master version - the fix isn't currently there, and just on the PR build

**Comment by onebeastchris** [comment] 2024-03-14 16:26
that looks correct :p
Check the version number in the geyser startup log - if you're running the PR build, the Geyser version should be something like 
`Loading Geyser version 2.2.2-SNAPSHOT (git-kernel-version-parsing-adc90f9)`

**Comment by larsalbrecht** [comment] 2024-03-14 16:27
> that looks correct :p Check the version number in the geyser startup log - if you're running the PR build, the Geyser version should be something like `Loading Geyser version 2.2.2-SNAPSHOT (git-kernel-version-parsing-adc90f9)`

Ah, i get it. Artifacts seems to be wrong. If i click in the build step on "Archive artifacts", and download it from https://github.com/GeyserMC/Geyser/actions/runs/8282391341/artifacts/1326261208, I get another file. Give me second

**Comment by onebeastchris** [comment] 2024-03-14 16:41
I've just downloaded that same file, if I unzip it, and look at the `git.properties` file where that info originates from, it shows me that it's from a dev build & a different commit

Do you perchance have an automatic auto-updater/installer that might be overriding the file?

**Comment by larsalbrecht** [comment] 2024-03-14 17:16
> I've just downloaded that same file, if I unzip it, and look at the `git.properties` file where that info originates from, it shows me that it's from a dev build & a different commit
> 
> Do you perchance have an automatic auto-updater/installer that might be overriding the file?

OMG, I'm terribly sorry for wasting your time on this. You were right, I had an auto-update running.

It runs. No error message and I can reconnect to my Android smartphone.
A few thalers will end up in your donation pot

**Comment by onebeastchris** [comment] 2024-03-15 11:14
Thanks for testing, glad to hear it works :)
We'll close this issue once the fix is available in the master build - thanks for reporting it here.

**Comment by jeosalih** [comment] 2024-03-15 11:19
I had the same problem. thanks. Will it be added to the original package for other people?

**Comment by onebeastchris** [comment] 2024-03-15 11:20
yes, once the associated PR is finalized - I'll try and finish that up later today.

**Closed** 2024-03-15 12:52 UTC
Labels: Confirmed Bug
