### ISSUE TITLE
Disconnect messages are not read properly on Bungeecord.

### ISSUE THREAD

**Issue by hasankayra04** [GeyserMC/Geyser#4281] opened 2023-11-10 14:13 UTC
### Describe the bug

Disconnect messages are not read properly on Bungeecord. Hence showing "Connection closed." instead of the actual disconnect reason.

### To Reproduce

Turn whitelist on the first server your Bungeecord tries to connect you to.
Join on Bedrock.

### Expected behaviour

Disconnect messages  to be read properly.

### Geyser Version

f40ca2

**Comment by onebeastchris** [comment] 2023-11-10 21:42
Duplicate of https://github.com/GeyserMC/Geyser/issues/4272 - thanks for reporting.

**Closed by onebeastchris** 2023-11-10 21:42 UTC
