### ISSUE TITLE
Camel not working in Bedrock Version

### ISSUE THREAD

**Issue by chy8952** [GeyserMC/Geyser#4284] opened 2023-11-11 06:23 UTC
### Describe the bug

When the player gets on the camel, the camel starts to turn around meaninglessly and does not obey instructions
But it listens to instructions on Java ver.

### To Reproduce

1.Get on camel
2.See Error

### Expected behaviour

Listen to instructions

### Screenshots / Videos

https://drive.google.com/file/d/1Ou5lLSOGwpdEjXJRQmXAoHjG3aV_Ug7r/view?usp=sharing

### Server Version and Plugins

This server is running Paper version git-Paper-263 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 487109f)
You are 17 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-249 (MC: 1.20.2)

### Geyser Version

2.2.0-SNAPSHOT (git-master-8d2ebcf) (Java: 1.20.2, Bedrock: 1.20.0/1.20.1 - 1.20.40)

### Minecraft: Bedrock Edition Device/Version

1.20.40.01

**Comment by onebeastchris** [comment] 2023-11-11 09:38
Duplicate of https://github.com/GeyserMC/Geyser/issues/3860 - thanks anyways for reporting.

**Closed** 2023-11-11 09:38 UTC
Labels: Duplicate
