### ISSUE TITLE
Error from players that do not exist??? Literally

### ISSUE THREAD

**Issue by Yomamaeatstoes** [GeyserMC/Geyser#3641] opened 2023-03-26 14:42 UTC
### Describe the bug

This is one of the more strange bugs I have found, but here it goes. I am getting errors saying 

[26.03 14:34:10] [Server] [WARN] [Geyser-Spigot] Haven't received PlayerListEntry packet before spawning player! We ignore the player 45f0c36b-2d89-46fa-ba32-5dca696b43a7

When I look up the UUID It says it doesn't exist. I don't know what triggers this, but I suspect it could be clicking on NPC's like citizens but I can't be for sure. 

### To Reproduce

Get bedrock players to do stuff

Maybe it will appear??

These errors occur at the same time or close as clicking NPC's

### Expected behaviour

No errors

### Screenshots / Videos

![Minecraft 1 19 4 - Multiplayer (3rd-party Server) 3_26_2023 10_38_38 AM](https://user-images.githubusercontent.com/114538961/227783190-a363c33c-54ba-4d4c-8787-eb97682b3e28.png)

https://www.youtube.com/watch?v=7CYfoWDiEcE

### Server Version and Plugins

git-Paper-470 (MC: 1.19.4)

My plugins are DisableBreeding, DiscordSRV, dynmap, ElytraSpeed, floodgate, Geyser-Spigot, GlobalTrackedMaps, HarmonyScoreboard, IridiumSkyblock, LuckPerms, mcMMO, Multiverse-Core, Multiverse-NetherPortals, Parkour, PL-Hide, PlaceholderAPI, PlayerBountiesPlus, PlayerKits, ProtocolLib, ScoreboardChatShop, *SecondThreadAPI, SilkySpawnersLITE, Skywars, spark, Spartan, *Spleef, StackMob, StormerAntiNetherRoof, StormerAntiSpam, StormerHomesReloaded, StormerTPAReloaded, StormerWarpsReloaded, Themis, TNTRun_reloaded, Vault, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin

### Geyser Dump

https://dump.geysermc.org/RA8slVUoWzOfjHP6TUc2zQm2q0j2mU78

### Geyser Version

https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/1340/

### Minecraft: Bedrock Edition Device/Version

PC, and presumably others

**Comment by Kas-tle** [comment] 2023-03-27 06:12
I think this is really works as intended and is just the result of plugins doing things that they should not with scoreboards. The vanilla client should also warn you about this.

Also note that this is a warning, not an error.

**Comment by Yomamaeatstoes** [comment] 2023-03-27 19:03
Hmm so this is probably an issue with my warps plugin?

**Comment by Yomamaeatstoes** [comment] 2023-03-27 20:21
Is there a way to find out what plugin is causing this if it not warps, and how do I stop this issue from happening? Should I reset geyser, and delete the scoreboard files if that is even possible?

**Comment by Yomamaeatstoes** [comment] 2023-03-28 02:32
Oh yea and I get [28.03 02:23:53] [Server] [WARN] [Geyser-Spigot] Could not find an entity definition with type TEXT_DISPLAY error with NPC's as well. Presumed to be all NPC's. I presume this has to do with Issue #3640 as well, but I am not sure.

**Comment by onebeastchris** [comment] 2023-05-21 21:28
Likely duplicate of https://github.com/GeyserMC/Geyser/issues/3442 - not sure though.
As for text displays; that's separate & should be resolved

**Closed** 2023-06-11 02:05 UTC
Labels: Duplicate
