### ISSUE TITLE
Players game freeze when trying to join

### ISSUE THREAD

**Issue by InfiniteBR** [GeyserMC/Geyser#4246] opened 2023-10-25 16:18 UTC
### Describe the bug

Players are joining on bedrock and they say the game freezes.
On console it shows as this:
25.10 17:08:29 [Server] INFO [Geyser-Spigot] Player has disconnected from the Java server because of Bedrock client timed out
25.10 17:08:29 [Server] INFO [floodgate] Floodgate player logged in as Player disconnected

### To Reproduce

1. Join server
2. Game crashes

### Expected behaviour

Join server
Play

### Server Version and Plugins

Build 339
Minecraft paper spigot 1.20.2
Bedrock version: 1.20.40

### Geyser Dump

https://dump.geysermc.org/Dpjm8up6nICCu7ywNbWkWp6dNYqp8Zbm

### Geyser Version

Build 339

### Minecraft: Bedrock Edition Device/Version

1.20.40

**Comment by InfiniteBR** [comment] 2023-10-25 16:19
One of these players are on Playstation 5. Anyone else yet to confirm.

**Comment by JH3Y50N** [comment] 2023-10-25 16:34
PS4 player too, and xbox, the game just close..

**Comment by vikingnope** [comment] 2023-10-25 17:03
Android Devices, and Minecraft Windows Edition the same

**Comment by hasankayra04** [comment] 2023-10-25 17:09
Yes, we are aware of this issue and are actively working to fix it.

**Comment by Konicai** [comment] 2023-10-25 17:18
Duplicate of #4240

**Closed by Konicai** 2023-10-25 17:18 UTC
