### ISSUE TITLE
The Fabric version of Geyser won't let the server shut down

### ISSUE THREAD

**Issue by AdolfRoxler** [GeyserMC/Geyser#3745] opened 2023-05-05 07:20 UTC
### Describe the bug

When you run `stop`

It'll "stop". It'll save the worlds. But, the java instance will keep running for whatever reason.

### To Reproduce

1. Install the fabric version of GeyserMC onto a Fabric MC server
2. Run /stop to stop the server
3. Wait indefinetely for the instance to actually shut down

### Expected behaviour

The instance should close.

### Geyser Dump

https://dump.geysermc.org/S7sPmAmz5fSv350UWeILRCPyzAjI0RDJ

### Geyser Version

2.1.0-SNAPSHOT (git-master-f801dc0)

### Minecraft: Bedrock Edition Device/Version

Not device related.

**Comment by AdolfRoxler** [comment] 2023-05-05 09:29
Refer to these issues:
https://github.com/GeyserMC/Geyser-Fabric/issues/58
https://github.com/GeyserMC/Geyser-Fabric/issues/11

**Comment by onebeastchris** [comment] 2023-05-08 02:34
https://github.com/GeyserMC/Geyser/issues/3519
Duplicate of this issue - it's probably caused by some open thread which wasn't closed; didn't have much luck on finding the cause yet

**Comment by onebeastchris** [comment] 2023-05-21 10:07
Closing, as this issue is a duplicate of #3519 - thanks anyways!

**Closed** 2023-05-21 10:07 UTC
Labels: Duplicate
