### ISSUE TITLE
Text Display packets not appearing for Bedrock Players

### ISSUE THREAD

**Issue by CoolDCB** [GeyserMC/Geyser#4122] opened 2023-09-14 21:25 UTC
### Describe the bug

I am using the FancyHolograms plugin to display Text Displays in my server but they don't appear to Bedrock players

I believe this is probably the relevent code within FancyHolograms if it is of any help:
https://github.com/FancyMcPlugins/FancyHolograms/blob/3386a6777ba79778672459dc7c70d4cc7c76cf85/implementation_1_20/src/main/java/de/oliver/fancyholograms/version/Hologram1_20.java#L70C112-L70C112

### To Reproduce

1. Download FancyHolograms
2. Create a hologram with `/hologram create`
3. Join on Bedrock

### Expected behaviour

To display in the same way that normal Text Displays do (invisible armour stand)

### Server Version and Plugins

Server Version: git-Paper-100 (MC: 1.20.1)
Geyser Standalone Build #287
FancyHolograms (2.0.1)

### Geyser Version

Geyser Standalone Build #287

### Minecraft: Bedrock Edition Device/Version

Mobile (Android)

**Comment by CoolDCB** [comment] 2023-10-15 15:49
Unsure if this is helpful: https://github.com/FancyMcPlugins/FancyHolograms/blob/main/implementation_1_20_2/src/main/java/de/oliver/fancyholograms/version/Hologram1_20_2.java

**Comment by SonnenPingu** [comment] 2023-10-17 11:34
Same with cmi

**Comment by onebeastchris** [comment] 2023-11-03 16:42
Send a geyser dump please - also, does a display appear when spawning one manually?

**Comment by CoolDCB** [comment] 2023-11-03 16:45
I just noticed this whilst moving around, if you look directly at where they should be you can then see them 

https://gyazo.com/47e8976b684224d6818c1530a1383345

**Comment by SonnenPingu** [comment] 2023-11-03 16:45
I can say that it was because of the plugin CMI for me. 
Have now switched to another hologram plugin and now it works. 

According to Cmi, there is no fault on your part.

**Comment by CoolDCB** [comment] 2023-11-03 16:48
> Send a geyser dump please - also, does a display appear when spawning one manually?

Normal text displays work as intended

**Comment by onebeastchris** [comment] 2023-11-03 16:49
https://github.com/FancyMcPlugins/FancyHolograms/issues/43 It seems like FancyHolograms doesnt properly work on 1.20.2 Java aswell - Geyser emulates a 1.20.2 Java client. As for CMI, not sure if they do support 1.20.2 (yet). 
There was an issue on our end due to some changes in 1.20.2 for text displays; the PR that closed this issue has more info linked.

I'd recommend to check how a Java 1.20.2 client behaves with FancyHolograms - maybe they're intentionally only showing the text when looked at? Not sure though. On our end, we would only remove the text if the server told us to

**Comment by CoolDCB** [comment] 2023-11-03 16:58
I am personally running on 1.20.1

**Comment by onebeastchris** [comment] 2023-11-03 17:01
If Java 1.20.2 behaves the same way, that seems intentional and not a bug on our side

**Comment by onebeastchris** [comment] 2023-11-03 17:04
Which version was the Java edition client on?

**Comment by CoolDCB** [comment] 2023-11-03 17:05
My Java client is on 1.20.1 currently, I am happy to try different versions if that's helpful at all

**Comment by onebeastchris** [comment] 2023-11-03 17:08
It would be. Even if the server isn't on 1.20.2, Geyser still emulates a 1.20.2 client. Hence, why ViaVersion is needed to use Geyser on java servers that aren't on the latest version.
Testing what a Java 1.20.2 client would see could help identify whether it's an issue from e.g. ViaVersion, or whether it's different handling on our side

**Comment by CoolDCB** [comment] 2023-11-03 17:09
Just to note, the issue did also happen when the latest Minecraft version was 1.20.1

**Comment by CoolDCB** [comment] 2023-11-03 17:10
![image](https://github.com/GeyserMC/Geyser/assets/55620516/17d60b74-2e0a-40ac-beac-7f7363b7408e)
![image](https://github.com/GeyserMC/Geyser/assets/55620516/c6f0c452-ebaf-4a46-9445-4cc775b56751)
All displays as intended on 1.20.2

**Comment by onebeastchris** [comment] 2023-11-03 17:15
Okay, please send a Geyser dump, and I'll try and replicate that setup :)

**Comment by CoolDCB** [comment] 2023-11-03 17:16
For sure, here you go!
https://dump.geysermc.org/QIetgtQr0nDVPFztc6HzHfQKsQjfMDJs

**Comment by tadhunt** [comment] 2023-11-03 19:38
I'm having the same issue but with DecentHolograms.  Java works fine, Bedrock clients don't see holograms.

Setup:
* Proxy: Velocity 3.2.0 snapshot 276
  * Geyser-Velocity build 1526
  * Floodgate build 95
* Server: Paper 1.20.2 Build 240
  * Advanced Portals 0.9.2
  * DecentHolograms 2.8.4
  * DisableChat 1.1
  * LuckPerms 5.4.104
  * ViaBackwards 4.8.1
  * ViaVersion 4.8.1
  * Floodgate build 95
  * Images 2.3.1

**Comment by onebeastchris** [comment] 2023-11-04 15:54
Was able to replicate and fix - @CoolDCB feel free to try the build found under `Checks` in the linked PR.
As for @tadhunt - feel free to also try that build, but if chromebook specifically does not work, that would likely be a bedrock bug.

**Comment by CoolDCB** [comment] 2023-11-04 16:17
> Was able to replicate and fix - @CoolDCB feel free to try the build found under `Checks` in the linked PR. As for @tadhunt - feel free to also try that build, but if chromebook specifically does not work, that would likely be a bedrock bug.

Yep, all works as expected!

**Closed** 2023-11-04 17:59 UTC
Labels: Confirmed Bug
