### ISSUE TITLE
Player.openSign Does not works in bedrock edition users.

### ISSUE THREAD

**Issue by StayCake** [GeyserMC/Geyser#3340] opened 2022-10-07 15:39 UTC
### Describe the bug

Trying to open sign edit with custom plugin is not working for bedrock users.

### To Reproduce

1. Get anything that uses player.opensign() method for java edition
2. Try use it for bedrock edition players

### Expected behaviour

Should open sign edit ui for bedrock users properly.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/36215887/194592478-91c7d9eb-8000-401b-8d0d-ecb7a3c1ac89.png)

### Server Version and Plugins

![image](https://user-images.githubusercontent.com/36215887/194593012-b540ac9b-3920-4da5-b501-300463b859fb.png)
![image](https://user-images.githubusercontent.com/36215887/194593071-b383fd7d-a6c4-4060-8ef8-ad5768c06c7c.png)
* KeloPaper / KoiLock - Custom

### Geyser Dump

https://dump.geysermc.org/7MxaHIJSKStEzHJVdYwtANHU4hsr06w9

### Geyser Version

Geyser 2.1.0-SNAPSHOT (git-master-cb864b3)

### Minecraft: Bedrock Edition Device/Version

1.19.31

**Comment by Konicai** [comment] 2022-10-07 16:56
Duplicate of https://github.com/GeyserMC/Geyser/issues/1671

**Comment by Camotoy** [comment] 2022-10-07 17:08
I would recommend using Bedrock forms as an alternative if you're able.

**Closed** 2022-10-07 17:08 UTC
Labels: Missing Client Feature
