### ISSUE TITLE
Bedrock Players can't hit a respawned ender dragon

### ISSUE THREAD

**Issue by vijaypondini** [GeyserMC/Geyser#1373] opened 2020-10-06 09:45 UTC
**Describe the bug**
A dragon respanwed ( with end crystals ) cannot be hit with a sword, only with arrows

**To Reproduce**
1. Kill the ender dragon naturally spanwed
2. Respawn the dragon using the end crystals, be on bedrock edition, and wait for the dragon to come to the end fountain where you can hit the dragon with a sword/axe.

**Expected behavior**
Player cannot hit the dragon, no bossbar appeared either, and we tested this two times

**Screenshots / Videos**
https://imgur.com/a/wVPLGIH

**Server Version**
server is running Paper version git-Paper-174 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Geyser Version**
server is running Geyser version 1.1.0 (git-master-0cd4381) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.20)

**Minecraft: Bedrock Edition Version**
1.16.40

**Additional Context**
No possible plugins affecting the end world is really there, except mv-core

**Comment by rtm516** [comment] 2020-10-06 12:12
Thanks for the report but this is a duplicate of https://github.com/GeyserMC/Geyser/issues/1090

**Closed by rtm516** 2020-10-06 12:12 UTC
