### ISSUE TITLE
Able to use the offhand on bedrock

### ISSUE THREAD

**Issue by timr2000** [GeyserMC/Geyser#2425] opened 2021-07-27 11:28 UTC
### What feature do you want to see added?

If this is possible, make it possible to let users use their offhand. For placing torches or eat their food in their offhand.

### Are there any alternatives?

No alternatives.

**Comment by Chew** [comment] 2021-07-27 16:04
Duplicate of #1281, #1624, #1962, and #2057. 

From camo:
> Unfortunately, this is a Bedrock limitation. There's nothing we can do about it. :(
>
> If it becomes apparent that we can, we will implement it, but for now, I'm closing this as a Can't Fix. Thanks for asking anyway.

**Closed by Chew** 2021-07-27 16:04 UTC
Labels: Feature Request

**Comment by neco222** [comment] 2023-03-06 03:58
it is doable.
It can be activated by holding shift and pressing the button that places the block. (I think you can go without shift)

Functionality implemented in another plugin.
It was also available in the bedrock version.

What is another plugin
Open the Shellker Box in your inventory
