### ISSUE TITLE
Players cannot move when crawling 

### ISSUE THREAD

**Issue by Gnfhaotian** [GeyserMC/Geyser#4880] opened 2024-07-20 07:34 UTC
### Describe the bug

When prostrating by closing a trapdoor and trying to get through a 1-block high access, players cannot move and the picture jitters.The TPS or network delay is normal

### To Reproduce

1.set a trapdoor and open it
2.stand at the block of the trapdoor
3.close the trapdoor and try to move away

### Expected behaviour

Be able to move through the 1-block high access or move away from the trapdoor and stand.

### Screenshots / Videos

![Screenshot_2024-07-20-15-13-43-628_com mojang minecraftpe](https://github.com/user-attachments/assets/65a3d95b-2f69-4ff9-8be9-84907f76e23d)

### Server Version and Plugins

server runs on 1.20.1

### Geyser Version

2.4.0-Snapshot (git-fixrenderdistance-de0d87f)

### Minecraft: Bedrock Edition Device/Version

1.20.81, Android

**Comment by onebeastchris** [comment] 2024-07-20 23:01
Unable to reproduce. Please check if this also occurs without others plugins (most notably, anticheats)

**Comment by onebeastchris** [comment] 2024-11-28 17:40
Closing due to no further response.

**Closed by onebeastchris** 2024-11-28 17:40 UTC
Labels: Unconfirmed Bug/Not Currently Replicable, Waiting On Response
