### ISSUE TITLE
Bedrock Client connects but doesn't realize it 

### ISSUE THREAD

**Issue by vivianh-dev** [GeyserMC/Geyser#5016] opened 2024-09-03 06:28 UTC
### Describe the bug

Hi, attempting to set up reverse proxying and I am having players who are able to send data (they're able to join on the server side but client doesn't realize they did)
Notable config portions
```nginx
stream {
    upstream geyser_backend {
        server 127.0.0.1:19133; 
    }

    server {
        listen 19132 udp;
        proxy_pass geyser_backend;
        proxy_protocol on; 
    }
}
```

```yaml
address: 0.0.0.0
port: 19133
clone-remote-port: false
enable-proxy-protocol: true
proxy-protocol-whitelisted-ips: [ "127.0.0.1" ]

broadcast-port: 19132

remote:
  address: 1270.0.0.1
  port: 25566 # Local port its running on
  auth-type: floodgate
```
 I think at this point it's an nginx config issue but I wanna make sure I'm not missing some neon sign of obvious error

### To Reproduce

1. Create a paper server with the configuration provided and use nginx to forward 191932 requests to 19133 with the above configuration

### Expected behaviour

The client knows its connected and allows the client to interact

### Geyser Version

Build #663

**Comment by Camotoy** [comment] 2024-09-03 23:30
Try flipping around `port` and `broadcast-port`?

**Comment by vivianh-dev** [comment] 2024-09-03 23:34
> Try flipping around `port` and `broadcast-port`? 

I need the server to not use 19132 since I also have a second server. Disabling floodgate's linkage seems to have fixed it but it's tentative since I don't have enough of a sample size rn

**Comment by Camotoy** [comment] 2024-09-03 23:36
No, I see it now, OK. Can you send logs with Floodgate's linking enabled then?

**Comment by onebeastchris** [comment] 2024-10-07 18:17
Closing due to no further response - will reopen once reproduction steps/logs are provided

**Closed by onebeastchris** 2024-10-07 18:17 UTC
