### ISSUE TITLE
Custom inventories don't open when outside of the world

### ISSUE THREAD

**Issue by Benedani** [GeyserMC/Geyser#1441] opened 2020-10-23 12:47 UTC
**Describe the bug**
My server has a GUI that works by teleporting the player waaaaaaay above the world (so that blocks in the world, that can be placed by players have no chance of interfering with the process). To my understanding, such inventory GUIs are handled on Bedrock Edition by placing a chest and forcing the player to open them, as simply opening an inventory out of nowhere is impossible.
When the player is way above the world, like in my situation, said chest cannot exist, and so no GUI appears.

**To Reproduce**
Try to open a custom inventory GUI (using a plugin) when above or below the world.

**Expected behavior**
The player should be able to interact with the custom GUI. I'm not exactly sure how this would work without secretly teleporting the player somewhere near inside the bounds.

**Screenshots / Videos**
![a](https://cdn.discordapp.com/attachments/592276618370875422/769179743014617149/Screenshot_2020-10-23-14-44-37-300_com.mojang.minecraftpe.jpg)

**Server Version**
1.16.2 (git-Paper-189)

**Geyser Version**
1.1.0 (git-master-62d984d), running on Waterfall

**Minecraft: Bedrock Edition Version**
1.16.40

**Comment by rtm516** [comment] 2020-10-23 12:51
This like you said is due to a bedrock limitation, but it may be resolvable by updating #708 and getting it merged but that will likely be after the inventory rewrite.

**Comment by Heath123** [comment] 2020-10-25 10:29
That will only work for single chests though

**Comment by Benedani** [comment] 2020-10-25 10:38
> That will only work for single chests though

A double chest could be used when within the world's bounds - I'm not sure if there are any other servers that put you out of bounds, but I'm not a big Java multiplayer gamer.
Then again, most custom GUIs don't expect you to use the inventory, so perhaps your inventory could be used as the other chest's slots if a double chest doesn't work.

**Comment by ChiAkuma** [comment] 2021-05-13 20:40
Yep have that problem too but with protected areas (Worldguard) or other plugins that protect areas

**Comment by rtm516** [comment] 2021-05-14 00:33
> Yep have that problem too but with protected areas (Worldguard) or other plugins that protect areas

The chest is sent to the bedrock client and doesn't really exist above the players head so server protection plugins shouldn't cause an issue with the placement of it. It is likely caused by not having permission to open the chest in the first place.

**Comment by ChiAkuma** [comment] 2021-05-14 01:26
It opens if i change the world and if i teleport or do anything i dont know the cause yet but eventually it stops letting me open it until i change world/server.

**Comment by RednedEpic** [comment] 2021-05-22 00:08
Superseded by #2210.

**Closed by RednedEpic** 2021-05-22 00:08 UTC
Labels: Confirmed Bug, Missing Client Feature
