### ISSUE TITLE
[Feature Request] Geyser for Nukkit

### ISSUE THREAD

**Issue by TheBalkanDev** [GeyserMC/Geyser#2507] opened 2021-08-30 08:40 UTC
### What feature do you want to see added?

GeyserMC on the Bedrock Java Based Server Software Nukkit, It would be nice when java Players can join Bedrock Servers.
Like the other way arround.
Java addition client since the packets —> Geyser Translate them —> Bedrock server receives translated packets.

### Are there any alternatives?

I donˋt know maybe as an Mod.

**Comment by Tim203** [comment] 2021-08-30 08:44
Duplicate of various issues like #2274
Basically, if we're ever going to make that it'd be a separate project.

**Closed by Tim203** 2021-08-30 08:44 UTC
Labels: Feature Request

**Comment by ImDaBigBoss** [comment] 2021-08-30 10:33
@TheBalkanDev if you want that, you can try this: https://github.com/THEREALWWEFAN231/TunnelMC but it’s in early development.

**Comment by TheBalkanDev** [comment] 2021-08-30 22:30
O know this it laggs as **** and its buggy too
