### ISSUE TITLE
The non existent scoreboard.

### ISSUE THREAD

**Issue by snaildos** [GeyserMC/Geyser#1478] opened 2020-10-31 14:42 UTC
**Describe the bug**
A bug that doesnt allow bedrock clients to see a scoreboard.
Java:
![image](https://user-images.githubusercontent.com/46210117/97781976-d91f0f80-1bc9-11eb-9e15-7780169c8c36.png)
![image](https://user-images.githubusercontent.com/46210117/97782007-feac1900-1bc9-11eb-8df4-0192cd72fbf0.png)

**To Reproduce**
Install geyser
make a scoreboard
join on bedrock
watch it not appear

**Expected behavior**
I should see my scoreboard.

**Screenshots / Videos**
Labeled above.

**Server Version**
Paper Latest
Latest Geyser
trust me; its latest.

**Geyser Version**
Apparently im 28 builds behind:
1.1.0 git

**Minecraft: Bedrock Edition Version**
l a t e s t

**Additional Context**
Nothing else; I want my scoreboard.

Look, I am properly just stupid and didn't enable it god knows where in the config. Just tell me what I need to do please.

**Comment by DoctorMacc** [comment] 2020-10-31 14:43
This is a duplicate of #1385. Thank you regardless for reporting!

**Closed by DoctorMacc** 2020-10-31 14:43 UTC

**Comment by snaildos** [comment] 2020-10-31 23:25
I thought it was, Thanks.
