### ISSUE TITLE
Not working chests, item frames, scaffoldings, encahants, block break

### ISSUE THREAD

**Issue by RisksY** [GeyserMC/Geyser#159] opened 2020-02-10 19:01 UTC
**Describe the bug**
You see an invisible block if there is a chest.
You can see the scaffoldings but you can't use it on Bedrock. Maybe I can't use it.
Item frames and its item not shown.

**To Reproduce**
1. Go to chest you placed before on Java Edition.
2. Click on chest
3. It won't open, its invisible but there is blocks outline selection. Like barrier.

1. Go to an item frame you placed before.
2. Its invisible, there is no item also and there is no outline selection.

1. Go to any scaffoldings try going down.
2. I think it should go down when you sneak or i know it wrong. It works when you try going up.

1. Put an enchanted item in your inventory while in Java.
2. Try opening inventory.
3. You won't see its enchant.

1. Put a block in Bedrock.
2. Try breaking it in Bedrock.
3. When you break it will appear again. (Tried Spruce Planks and breaking it with stone axe.)

**Expected behavior**
Visible chests and open chests.
Visible item frames with an item in it that you can rotate.
Go down with scaffoldings.
See enchants on the items in Bedrock.
Break blocks that they won't back placed.

**Screenshots**
Will try. 

**Server version**
/version: This server is running CraftBukkit version git-Spigot-800b93f-8160e29 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Geyser version**
Jenkins

**Bedrock version**
Blocklauncher Free 1.14.1.5

**Additional context**
Yoır job is perfect. I support it reporting to fix them. Not to make it bad. Will use on my survival server.

**Comment by RednedEpic** [comment] 2020-02-10 19:46
Chests not visible are due to block entities not implemented in the main branch (see README, and also duplicate of #72). Scaffolding is likely due to movement bugs which are being worked on (see README and duplicate of #109). For item frames, please open a separate issue, enchanted items, duplicate of #133, block break, duplicate of #153. 

Next time, please open one issue per bug or problem you encounter and please make sure to check the README and currently opened issues before doing so.

**Closed by RednedEpic** 2020-02-10 19:46 UTC
Labels: Duplicate, Invalid
