### ISSUE TITLE
Support for the latest build of Via plugins.

### ISSUE THREAD

**Issue by MrZomka** [GeyserMC/Geyser#1323] opened 2020-09-22 13:08 UTC
**What feature do you want?**
Support for the latest build of Via plugins since I've got a few issues on the latest builds of Via plugins. (https://discordapp.com/channels/613163671870242838/613168464634576897/754350753631567923)

**Alternatives?**
Downgrading to the release version of Via plugins won't help since the release version has a bug with invisible text on the signs.

**Comment by DoctorMacc** [comment] 2020-09-22 14:23
Thanks for requesting this feature! However, this is more or less a duplicate of #1257 since they both address the same problem.

**Closed by DoctorMacc** 2020-09-22 14:23 UTC
