### ISSUE TITLE
Persistent "fake" rain on Bedrock clients

### ISSUE THREAD

**Issue by axieum** [GeyserMC/Geyser#3679] opened 2023-04-14 11:30 UTC
### Describe the bug

Occasionally, all Bedrock players' rain (weather) will never end until they all log out and back in. This appears to affect all Bedrock players simultaneously.

### To Reproduce

1. Login to Geyser-Fabric server from Bedrock client
2. Wait for rain
3. Confirm with Java players if it is actually raining
4. If fake rain, logout and back in, notice rain has stopped

### Expected behaviour

The rain is in sync with Java clients, and stops with everyone else.

### Screenshots / Videos

https://user-images.githubusercontent.com/7577851/232031228-c1bae83d-dc49-47ed-8be7-1340f9e56144.mp4

Notice this player's Conduit effect is not reaching them through the rain - it is fake rain.

_It's quite hard to capture "proof" of this bug without everyone's POVs._

### Geyser Dump

https://dump.geysermc.org/OACSRpUtY3yBqOwBnl3vg259Fpmyy0HT

### Geyser Version

2.1.0-SNAPSHOT (git-master- 0f99abc )

### Minecraft: Bedrock Edition Device/Version

1.19.73, Xbox Series S|X

### Additional Context

`/seed` → `Seed: [-7181305874542611689]`
`/time query gametime` → `The time is 27583805`

**Comment by axieum** [comment] 2023-04-14 13:04
A player with the fake rain tried going to the Nether and back. It was still raining for them, so changing world/dimension doesn't fix it. Seems like you HAVE TO re-login.

**Comment by Kas-tle** [comment] 2023-04-14 14:18
Please try removing all mods and see if this issue persists. For this we would likely need to see the packets to see what's going on. Does this occur when rain is started and stopped via the weather command?

**Comment by kamil445** [comment] 2023-04-15 11:57
I also have this issue, using command /weather sun doesn't change weather for bedrock clients, they need to relog.

**Comment by BigJoys** [comment] 2023-04-17 22:50
The error also exists with Spigot/Paper Standalone Geyser

**Comment by axieum** [comment] 2023-04-21 09:28
Okay, the rain just started for all the Bedrock players at the same time but not the Java players.

Using `/weather clear` did not clear the rain for Bedrock players.

Only once I ran `/weather rain` so Java was **also** raining, did `/weather clear` actually clear the rain for Bedrock players.

**Comment by hw2007** [comment] 2023-04-28 20:26
Something I've noticed is that this tends to happen more often if you have a server with players-sleeping-percentage gamerule set to 0. Then, if its raining and a java player sleeps away the night and the rain, it will continue to rain for bedrock players almost every time.

**Comment by axieum** [comment] 2023-04-29 03:43
@hw2007, I think you're onto something with that; our server's `playersSleepingPercentage` gamerule is currently set to `0`.

**Comment by valaphee** [comment] 2023-04-29 12:48
Its a known Minecraft bug: https://bugs.mojang.com/browse/MCPE-131325, solution would be to pro-actively send stop rain in fixed intervals

**Comment by DuneSciFye** [comment] 2023-04-29 18:34
`playersSleepingPercentage` is set to 100 for me, and I also experience this rain issue.

**Comment by agoniaprivat** [comment] 2023-06-22 08:13
Can confirm. Pictures taken same time: ![image](https://github.com/GeyserMC/Geyser/assets/50961682/58e45df8-4827-4d2f-8ef2-7b93281bdd12)

![image](https://github.com/GeyserMC/Geyser/assets/50961682/553edf46-8de8-4b88-a292-eb2282bdae64)

**Comment by TalonFloof** [comment] 2024-04-09 23:32
I've actually noticed that this issue still persists, I wonder if this will be looked into eventually because it can be annoying at times.

**Comment by sanforjr2021** [comment] 2024-06-10 21:01
Can confirm it is still a bug for our server. Pufferfish 1.20.4. Latest geyser velocity

**Comment by TheCrafter8000** [comment] 2024-07-25 00:45
I can confirm this issue still exists. Velocity, Purpur 1.21

**Closed** 2024-09-09 03:06 UTC
Labels: Confirmed Bug
