### ISSUE TITLE
Item frames show an item name when they shouldn't

### ISSUE THREAD

**Issue by onebeastchris** [GeyserMC/Geyser#5194] opened 2024-12-05 13:04 UTC
### Describe the bug

![image](https://github.com/user-attachments/assets/97667fb2-c03c-4614-811c-b93d6fc5555c)
Since this item wasn't renamed, it shouldn't show a custom name when hovering over it

### To Reproduce

1. Place item frame
2. Insert any item
3. See that there's a name hovering on the item frame

### Expected behaviour

Item names should only show when the item was renamed to match Java edition behavior.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/e7428b1c-bdf7-4445-a3c8-d3355a069d6c)

### Server Version and Plugins

not applicable

### Geyser Dump

https://dump.geysermc.org/EZlQD39nH5G9DQz94KsrDzvaGz3sRxI3

### Geyser Version

2.6..0-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

tested on both 1.21.40/1.21.50

**Comment by letsgoawaydev** [comment] 2024-12-14 04:49
this can probably be fixed by checking for the "minecraft:custom_name" component

**Comment by BUGTeas** [comment] 2024-12-22 04:58
This issue appears to be caused by all vanilla components be used during conversation since 8779eab, include vanilla `item_name` compoment. It cause all items have custom name in bedrock client, making item names implemented by other methods to not take effect. For example, the title of a written book, potion and map name.
![image](https://github.com/user-attachments/assets/467b84e6-028d-4876-bd0d-75ae3fb820e8)
![image](https://github.com/user-attachments/assets/eff2d864-772a-431b-822e-ebe7fddb5976)
![image](https://github.com/user-attachments/assets/2783df77-3e84-4f93-a4b1-d6f4f1ac7661)
![image](https://github.com/user-attachments/assets/c0b0fca9-d459-4ef0-9363-8c9b1b315a2b)

**Comment by onebeastchris** [comment] 2024-12-22 05:02
Yeah, figured something like it. I have a fix in mind, can try and make a fix for this this Tuesday

**Closed** 2024-12-23 16:19 UTC
Labels: Confirmed Bug
