### ISSUE TITLE
 display entities support！

### ISSUE THREAD

**Issue by ximuya2** [GeyserMC/Geyser#4994] opened 2024-08-25 14:23 UTC
### What feature do you want to see added?

![image](https://github.com/user-attachments/assets/7457ac11-a582-4d72-8a36-dab5d985cb0c)
# Poll
## Do you think it's better to keep armorstand entities compatibility or stop and use display entities? (for both furniture and custom entities)
Downsides:
- Armostand compatibility allows Geyser clients to see these things, since Bedrock doesn't have display entities.
- 1.19.3 and lower clients can't see display entities because they didn't exist back then

On the other hand Display entities are very powerful:
- better performance
- resize models to any size without limitation
- smoother movement

## Vote
✅  to approve display entities and discard armorstands
❌  to disapprove display entities and implement them later in time when most people updated to 1.19.4 and maybe Bedrock introduces display entities

### Are there any alternatives?

can not

**Comment by ximuya2** [comment] 2024-08-25 14:24
itemsadder

**Comment by onebeastchris** [comment] 2024-08-25 15:16
Duplicate of https://github.com/GeyserMC/Geyser/issues/3810 - implementing display entities unfortunately is not an easy task.

**Closed** 2024-08-25 15:16 UTC
Labels: Feature Request
