### ISSUE TITLE
Bamboo causes rubberbanding on bedrock.

### ISSUE THREAD

**Issue by Tydium** [GeyserMC/Geyser#1899] opened 2021-02-05 15:18 UTC
**Describe the bug**
Basically if you walk through a forest of bamboo it basically rubberbands you back on bedrock edition. It sort of reminds me of what it feels like with cached chunks off. I think it could be possible that it is related to that. The rubber banding is to the point where you can make a jail for bedrock players simply made out of bamboo and they cant get out because it just rubberbands or TP's back to their spot.

**To Reproduce**

1. Find a forest (or make your own) of bamboo. 
2. Walk through the forest and when your close enough to the bamboo you get rubberbanded (or teleported)
3. Good luck getting out.... or in....
**Expected behavior**
It should act like nothing and let the player walk through normally. Not scream racial slurs at the player

**Screenshots / Videos**
No screenshots or videos at the moment. I will edit this later and put one.

**Server Version and Plugins**
Using latest version of Geyser Bungeecord (Geyser version 1.2.0-SNAPSHOT (git-master-c26a2ba) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.200/1.16.201))

Paper 1.16.5

**Geyser Dump**
https://dump.geysermc.org/agndvZLujtjjEhgCevQpbphE1SorKpgy

**Minecraft: Bedrock Edition Version**
Bedrock Editon on the Nintendo Switch/Windows10/and on Android (havent tested any other devices) on version 1.16.201 
**Additional Context**
I think this may have to do with cached chunks, but Im not entirely sure. You would know better than me.

**Comment by Camotoy** [comment] 2021-02-05 15:41
This is an issue with Bedrock bamboo collision being entirely different from Java.

**Comment by YodaLightsabr** [comment] 2021-03-22 00:33
Is there any update on this? It seems that stairs and slabs sometimes also have this behavior for me.

**Comment by Chew** [comment] 2021-03-22 00:52
Please don't pointlessly bump issues. You can check for updates by checking the linked PR if any. If there's not, you're more than welcome to take this on yourself. Asking for updates will not speed anything up.

**Comment by Camotoy** [comment] 2021-03-22 00:53
This is still unfixable to our knowledge.

**Comment by RednedEpic** [comment] 2021-05-22 01:02
Duplicate of #745. We are still looking into options here on Spigot platforms though, despite this having a "Can't Fix" label.

**Closed by RednedEpic** 2021-05-22 01:02 UTC
Labels: Can't Fix, Confirmed Bug
