### ISSUE TITLE
Painting apear in wall

### ISSUE THREAD

**Issue by tbvns2** [GeyserMC/Geyser#3220] opened 2022-08-10 12:23 UTC
### Describe the bug

When you spawn a painting, it spawn in the wall

### To Reproduce

1. take a painting
2. place it
3. break the wall behind the painting to see it
(java player can see the painting)

### Expected behaviour

The painting should appear on the wall but not in the wall

### Server Version and Plugins

Latest geyser, running on waterfall (paper 1.19.1)

### Geyser Dump

https://dump.geysermc.org/GR2m2Lh5wdoebxIgC7hwVwMBUWR8y0pF

### Geyser Version

latest

### Minecraft: Bedrock Edition Device/Version

1.19.11 / 1.19.20

**Comment by Camotoy** [comment] 2022-08-10 12:34
This is probably a duplicate of #3014. Thanks anyway!

**Closed by Camotoy** 2022-08-10 12:34 UTC
