### ISSUE TITLE
The glass bottle does not spread water.

### ISSUE THREAD

**Issue by hoehoetvhss** [GeyserMC/Geyser#2642] opened 2021-11-19 14:06 UTC
### Describe the bug

When pouring water into a glass bottle, it should be changed to a water bottle.

### To Reproduce

1. Hold a glass bottle.
2. I'm going to scoop out the water.

### Expected behaviour

After clicking on the water, it should be changed to a water bottle.

### Screenshots / Videos

Java Edition: https://youtu.be/ocGVYWUI_s8
Bedrock Edition: https://youtu.be/CGIUKtxiWFs

### Server Version and Plugins

git-Paper-386 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: e22a1a9)

### Geyser Dump

https://dump.geysermc.org/iceAdGx9rPdkKz0bcGt7tQy2m56GibgD

### Geyser Version

1.4.3-SNAPSHOT (git-master-b92b49b)

### Minecraft: Bedrock Edition Version

1.17.41.01

**Comment by Konicai** [comment] 2021-11-22 17:23
Try pointing the crosshair directly on the water, and tapping exactly on the crosshair. This is likely a duplicate of https://github.com/GeyserMC/Geyser/issues/2075

The server only allows picking up water where the crosshair is pointed, which results in this happening if you don't pick up exactly on the crosshair

**Closed by Konicai** 2021-11-22 17:23 UTC

**Comment by hoehoetvhss** [comment] 2021-11-22 23:48
https://youtu.be/skOYP4Qi9cQ

I scooped underwater to do the exact crosshair, but the same phenomenon occurs.
