### ISSUE TITLE
Players are pulled back/shaken up and down as they walk/stand on top of a flat trapdoor

### ISSUE THREAD

**Issue by pbs666** [GeyserMC/Geyser#702] opened 2020-05-30 14:23 UTC
Players are pulled back/shaken up and down as they walk/stand on top of a flat trapdoor
no others ....

**Comment by RednedEpic** [comment] 2020-05-30 14:24
Again, follow the issue template. This likely would be a duplicate of #204. Closing in favor of that. Also make sure the issue you’re reporting is not already open.

**Closed by RednedEpic** 2020-05-30 14:24 UTC
