### ISSUE TITLE
Can't get water bottles from plain water.

### ISSUE THREAD

**Issue by hirata-estate** [GeyserMC/Geyser#2727] opened 2021-12-23 07:56 UTC
### Describe the bug

This was tested on a Java 1.18.1 server.
If a player on bedrock right-clicks a water-source with an empty water bottle, it'll appear as though they did get the water bottle, but if you check their inventory or what they're holding with a java client, they only have empty bottles.
If they put the "ghost water bottles" in a brewing stand or other, it seems to revert back to empty.

### To Reproduce

1. Join with bedrock 1.18.0. Server is on 1.18.1, Bungeecord (waterfall).
2. Right-click water source with water bottle.
3. Put water bottle in container. (chest, brewing stand, etc.)

### Expected behaviour

Right-clicking water with an empty bottle will make it a water bottle.

### Server Version and Plugins

Waterfall version git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:f8d136f:472
AdvancedBan
BotSentry
BungeeAliases
BungeeGuard
BungeeTablistPlus
BungeeWhitelist
Geyser
JPremium
LuckPerms
MiniMotD
PLAN
SkinsRestorer

Pufferfish 1.18.1 (pretty much paper)
AltDetector, BetterSlimeChunks, BlockBelt, BungeeGuard, BungeeTabListPlus, Chunky, CoreProtect, CraftingStore, DiscordSRV, DiscordSRV-Staff-Chat, EntityDetection, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, FarmControl, GriefPrevention, HaoNick, HeadDB, ImageOnMap, InteractiveChat, InteractiveChatDiscordSrvAddon, InventoryRollbackPlus, JPremium, LuckPerms, Multiverse-Core, Multiverse-Inventories, NickAPI, OpenInv, PlaceholderAPI, Plan, ProtocolLib, ServerSigns, ServerUtils, Shopkeepers, SilenceMobs, SkinsRestorer, SpectatorMode, SpigotPing, SuperVanish, Tamablefoxes, UnbreakableLeashes, Vault, ViaBackwards, ViaRewind, ViaVersion, ViewDistanceTweaks, VoidGen, Votifier, VotingPlugin, Wild, WorldEdit, WorldGuard, spark

### Geyser Dump

https://dump.geysermc.org/Qr0DiZtMDyHg7UzTZAGp9jfvfz89ica7

### Geyser Version

 Geyser version 2.0.0-SNAPSHOT (git-master-3bf68af)

### Minecraft: Bedrock Edition Version

1.18.0

### Additional Context

Right-clicking a full water cauldron with an empty water bottle seems to work just fine on both the java and bedrock client sides. (java watching bedrock player)

**Comment by Konicai** [comment] 2021-12-23 16:49
This only occurs with touchpad devices, right?

**Comment by ultraic-space** [comment] 2021-12-23 16:54
> This only occurs with touchpad devices, right?

Not exactly sure if it only happens with touchpad devices, I have not tested it on PC as I myself don't have a bedrock account. The player was on mobile though, yes. I'll try to ask other bedrock players if I come across any other more to test it if I can.

**Comment by Konicai** [comment] 2021-12-23 17:00
This bug is already known, but I'm going to keep this issue open and close this other one since this one is a lot more detailed.

**Comment by 7Blue7** [comment] 2021-12-23 17:45
It happened to me once but a way I figured out around it was too fill your inventory and let the water bottles pop out when right clicking water, making them real and not ghosts. Also for touch/mobile players they usually just click the water source but long tapping makes it work.

**Comment by TerdyTheTerd** [comment] 2022-01-03 19:32
I think I recall this being the same solution I had told my previous mobile users. I have a mobile account I can test with later to confirm the long press work around. Ideally the bottles would still get filled regardless since the client shows it, but long pressing is a fine workaround.

**Comment by DJelly4K** [comment] 2022-05-14 15:03
Any fix progress about this?

**Comment by onebeastchris** [comment] 2023-05-22 11:48
Hey! Unfortunately, I wasn't able to reproduce this with the latest version of Geyser, and Bedrock 1.19.81 on Android + win10. 
If this issue is still occurring with the latest version of Geyser, please send a new Geyser dump by running "geyser dump" in the server console & sending the link you get here. Please also mention the device which was used. Thanks!

**Closed** 2023-06-10 23:36 UTC
Labels: Waiting On Response
