### ISSUE TITLE
Xbox / Windows 10 crafting & inventory glitch

### ISSUE THREAD

**Issue by willbuck115** [GeyserMC/Geyser#2614] opened 2021-11-03 06:06 UTC
### Describe the bug

When using the recipe book, game glitches items around (worst on xbox) tried on a paid server and private (with much more resources to eliminate lag). Seems to be present on both Spigot and Fabric forks and is not fixed by changing any settings.

Server: Paper version git-Paper-359 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: bc43f40)
Geyser: Loading Geyser version 1.4.3-SNAPSHOT (git-master-6cda15c)
Floodgate (bug present with and without): floodgate v2.0-SNAPSHOT
Bedrock: 1.17.41

### To Reproduce

Use any version of geyser with or without floodgate
Attempt to craft on either xbox or windows 10 using recipe book

### Expected behaviour

Should gain crafted item in inventory
OR
Be able to remove the items from the crafting interface

### Screenshots / Videos

https://user-images.githubusercontent.com/43417068/140015971-dacafe85-01ce-42cd-aa3e-3462d96e2b46.mp4

### Server Version and Plugins

floodgate v2.0-SNAPSHOT

### Geyser Dump

https://dump.geysermc.org/oykrNdiWjkxVVQ0T93oFUrI3fjwLCEMr

### Geyser Version

Geyser version 1.4.3-SNAPSHOT (git-master-6cda15c)

### Minecraft: Bedrock Edition Version

1.17.41

**Comment by Jens-Co** [comment] 2021-11-03 09:21
Duplicate of #2462

We are aware there is an bug within the quick crafting option in bedrock. Thanks for the report!

**Closed by Jens-Co** 2021-11-03 09:21 UTC
Labels: Duplicate

**Comment by willbuck115** [comment] 2021-11-04 00:04
How come it happens on some servers and not others? If you don't mind me asking, I noticed the test server does not have this issue if it's specific versions I will happily change to fix this issue

**Comment by Camotoy** [comment] 2021-11-04 00:16
The test server is on version `git-Paper-788 (MC: 1.16.5)` so it may be a bug that manifests only in 1.17?
