### ISSUE TITLE
Unable to use the bag with the bedrock version of the game

### ISSUE THREAD

**Issue by Sergan023** [GeyserMC/Geyser#5175] opened 2024-11-30 11:03 UTC
### Describe the bug

Crafting a bag creates a shulker shell, which can't be used as either a bag or a shell (which makes sense). However, if you swap this "bag" with any item in your inventory, it will be stuffed into it and cannot be retrieved, except in the Java version of the game.

### To Reproduce

1. Open the workbench
2. Lay out the craft bag
3. Observe the bug

### Expected behaviour

I expected the bags to work fine.

### Screenshots / Videos

https://github.com/user-attachments/assets/5ccf46c5-fc90-4258-808a-37caafd080a2

### Server Version and Plugins

1.21.3 spigot/bukit
Plugins:
GSit, GeyserMC, AuthMe Reloaded

### Geyser Version

720

### Minecraft: Bedrock Edition Device/Version

Android, 1.21.

### Additional Context

Host - Aternos

**Comment by Camotoy** [comment] 2024-11-30 16:30
This will be fixed when https://github.com/GeyserMC/Geyser/pull/5145 is merged.

**Comment by onebeastchris** [comment] 2024-12-01 08:49
Duplicate of https://github.com/GeyserMC/Geyser/issues/5146 - will be fixed soon. Thanks for reporting!

**Closed by onebeastchris** 2024-12-01 08:49 UTC
