### ISSUE TITLE
Chunk error

### ISSUE THREAD

**Issue by D3ATHBRING3R13** [GeyserMC/Geyser#645] opened 2020-05-24 18:32 UTC
**Describe the bug**

Some sort of NullPointerException chunk error

**To Reproduce**

Just saw it in the log

**Expected behavior**

No errors

**Screenshots / Videos**

**Server Version**

git-Paper-312

**Geyser Version**

Build #188

**Minecraft: Bedrock Edition Version**

1.14.60

**Additional Context**

only had geyser, floodgate and worldedit
console log error: https://pastebin.com/QEBLVU53

**Comment by james090500** [comment] 2020-05-24 18:34
I believe we can sort this with 

``null = false`` 

Up to @RednedEpic  to decide tbh🍆 😫😫

**Comment by RednedEpic** [comment] 2020-05-24 18:34
Can you please provide the _full_ error? This seems to be missing some line numbers and other important details we need in order to investigate the error. Also, please update Geyser.

**Comment by D3ATHBRING3R13** [comment] 2020-05-24 18:42
yeah sorry this was from earlier today and I thought it just kept repeating
pastebin.com/wmiKzzP6

**Comment by rtm516** [comment] 2020-05-24 18:43
Still doesn't have the parts we need, can you pull it from the server log instead of console? assuming that's from console.

**Comment by D3ATHBRING3R13** [comment] 2020-05-24 18:47
that was from the log I can attach the whole file if you want, it's not too long

**Comment by RednedEpic** [comment] 2020-05-24 18:48
As you said this was from earlier today, could you try updating and then if this issue persists, send the log containing the errors from the newer version?

**Comment by D3ATHBRING3R13** [comment] 2020-05-24 18:49
ok, will do, might take me a while though

**Comment by towuk118** [comment] 2020-05-24 19:49
maybe start not paper and spigot?

**Comment by D3ATHBRING3R13** [comment] 2020-05-24 21:57
> 
> 
> maybe start not paper, start spigot?
what do you mean?

**Comment by D3ATHBRING3R13** [comment] 2020-05-25 15:49
I will still try and test for it, but when updating to the latest version of paper it lists fixing chunk unloading errors, which does seem to be the problem, though I don't know why that would affect geyser

**Comment by AJ-Ferguson** [comment] 2020-05-26 10:31
I think the NPE is happening here.
https://github.com/GeyserMC/Geyser/blob/14fcd77925f2246ad5e526038d21a521c141dd8d/connector/src/main/java/org/geysermc/connector/network/translators/java/world/JavaChunkDataTranslator.java#L111

When the player disconnects, `chunkCache` is set to `null`. And since chunks are processed in different threads, its possible for the NPE to happen.
https://github.com/GeyserMC/Geyser/blob/14fcd77925f2246ad5e526038d21a521c141dd8d/connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java#L394

**Comment by D3ATHBRINGER13** [comment] 2020-06-25 22:25
Haven't seen this error since when I reported it, so it is probably fixed

**Comment by RednedEpic** [comment] 2020-12-12 01:02
Closing as no future reports of this have came in and due to the fact that we've redone a decent bit of our chunk code. If anyone manages to reproduce this, please attach it to this issue and I'll reopen it.

**Closed by RednedEpic** 2020-12-12 01:02 UTC
Labels: Confirmed Bug, Priority: Low
