### ISSUE TITLE
Problem opening a menu on CosmeticsCore

### ISSUE THREAD

**Issue by angelooscuro77** [GeyserMC/Geyser#4650] opened 2024-05-08 19:41 UTC
### Describe the bug

When a Bedrock user tries to interact with a CosmeticsCore menu it appears that the menu is closed or the click event is completely ignored.

### To Reproduce

1. Open the CosmeticsCore menu
2. Select the cosmetic category you want to view
3. The menu closes by itself

### Expected behaviour

Once you have chosen the desired category and clicked it, a different specific menu should open

### Screenshots / Videos

Youtube video: https://youtu.be/2zdDeJMPxlI

### Server Version and Plugins

Server version: git-Purpur-1632 (MC: 1.18.2)

### Geyser Version

2.3.0-SNAPSHOT

**Comment by onebeastchris** [comment] 2024-05-18 23:26
Please provide exact replication steps/necessary setup of the mention plugin to be able to reproduce this issue.

**Comment by onebeastchris** [comment] 2024-06-18 14:44
Closing due to no further response. If this still occurs, please provide more information here, including reproduction steps - ideally with a non-paid plugin so we're able to reproduce it.

**Closed by onebeastchris** 2024-06-18 14:44 UTC
Labels: More Info Needed, Unconfirmed Bug/Not Currently Replicable, Priority: Low
