### ISSUE TITLE
Add Plugin API Support

### ISSUE THREAD

**Issue by x9nico** [GeyserMC/Geyser#612] opened 2020-05-21 11:18 UTC
**What feature do you want?**
My idea is to add a plugin API for Geyser to create plugins for Geyser Proxy.
We can have Player Events like PlayerJoinEvent, etc...

**Comment by Heath123** [comment] 2020-05-21 11:22
This used to exist but was removed

**Comment by DoctorMacc** [comment] 2020-05-21 13:38
Duplicate of #542. Also, that replicating that PlayerJoinEvent can largely be done with the Floodgate API.

**Closed by DoctorMacc** 2020-05-21 13:38 UTC
