### ISSUE TITLE
Stuck rendering

### ISSUE THREAD

**Issue by GuckTubeYT** [GeyserMC/Geyser#131] opened 2020-01-05 06:40 UTC
Stuck rendering

**Comment by GuckTubeYT** [comment] 2020-01-05 06:42
When i use vanilla, i got stuck rendering

**Comment by RednedEpic** [comment] 2020-01-05 06:46
Could you please elaborate and fill out the format, that way we can better investigate the issue?

**Comment by GuckTubeYT** [comment] 2020-01-05 06:57
![Screenshot_20200105-135651_Minecraft](https://user-images.githubusercontent.com/56192597/71776376-53d7c800-2fc3-11ea-9a01-97cd9c913412.jpg)
And then like this

**Comment by RednedEpic** [comment] 2020-01-05 06:58
Again, you’ll need to go into detail about what “stuck rendering” means.

**Comment by GuckTubeYT** [comment] 2020-01-05 07:00
I use vanilla = stuck rendering
But when i use spigot = stuck rendering and then i got message "read time out"

**Comment by GuckTubeYT** [comment] 2020-01-05 07:01
I can move, but so fast

**Comment by RednedEpic** [comment] 2020-01-05 07:01
> I can move, but so fast

How does that have to do with rendering? Could you please go into more detail?

**Comment by GuckTubeYT** [comment] 2020-01-05 07:05
Wait

**Comment by GuckTubeYT** [comment] 2020-01-05 07:05
I start my server

**Comment by GuckTubeYT** [comment] 2020-01-05 07:08
it's my first time making a minecraft java server and minecraft pe player can join, but error, i dont know where wrong

**Comment by RednedEpic** [comment] 2020-01-05 07:09
> it's my first time making a minecraft java server and minecraft pe player can join, but error, i dont know where wrong

Are you trying to say chunks won’t load in?

**Comment by GuckTubeYT** [comment] 2020-01-05 07:15
> > it's my first time making a minecraft java server and minecraft pe player can join, but error, i dont know where wrong
> 
> Are you trying to say chunks won’t load in?

I dont know

**Comment by RednedEpic** [comment] 2020-01-05 07:19
Seems like a duplicate of #121. Next time when opening an issue please follow the format and make sure you know what you’re taking about. If you find an issue and have no clue what’s going on or what it may be, please contact us on Discord first before opening an issue here.

**Closed by RednedEpic** 2020-01-05 07:19 UTC
Labels: More Info Needed

**Comment by GuckTubeYT** [comment] 2020-01-05 07:22
Its work
