### ISSUE TITLE
Java Disconnected/Bedrock Connection Closed

### ISSUE THREAD

**Issue by MrHentai** [GeyserMC/Geyser#2136] opened 2021-04-14 21:54 UTC
### Describe the bug

When java players or bedrock players connect to the server with the geyser floodgate 2.0 and floodgate 2.0 itself, They won't connect and get a message immediately after trying. On Java it just says Disconnected, and on Bedrock it says Connection Closed.

### To Reproduce

1.) use either Spigot or Paper 1.8.8 with Viaversion
2.) and just try to connect

### Expected behaviour

nothing will be able to connect, and the server will even say its offline and cant connect when its on the server menu

### Screenshots / Videos

[https://pastebin.com/raw/5dPAPx6c](url) <-- server log
[https://imgur.com/dgsobM8](url) <-- java screenshot
[https://imgur.com/oqYtsWK](url) <--bedrock screenshot

### Server Version and Plugins

CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

(i did this same test on a spigot 1.8.8 server with no plugins but geyser, floodgate, and Viaversion and it still happened)

### Geyser Dump

https://dump.geysermc.org/hJ3YvLZYsoeAlATBdwCQaIg7M0jxpyJJ

### Geyser Version

Geyser version 1.3.0-SNAPSHOT (git-floodgate-2.0-404419d)

### Minecraft: Bedrock Edition Version

1.16.220

**Comment by Camotoy** [comment] 2021-04-14 21:55
Duplicate of https://github.com/GeyserMC/Floodgate/issues/135. Thank you for reporting anyway!

**Closed by Camotoy** 2021-04-14 21:55 UTC
