### ISSUE TITLE
chunks stop loading

### ISSUE THREAD

**Issue by Ai-Kiwi** [GeyserMC/Geyser#3490] opened 2023-01-04 00:56 UTC
### Describe the bug

Some chunks just dont seem to load for some reason. They just stop loading all of a sudden but i can fly around x area that hasnt loaded and the rest load fine.

### To Reproduce

1: fly around
2: see chunks that don't load

### Expected behaviour

for them to load

### Screenshots / Videos

![Screenshot 2023-01-04 134632](https://user-images.githubusercontent.com/66819523/210465235-d1bbb6f0-19e5-4e7f-84f5-24a8bb571d95.png)
![Screenshot 2023-01-04 134936](https://user-images.githubusercontent.com/66819523/210465241-9ae0a139-e03f-41f3-8571-51b93e6a6b9e.png)

### Server Version and Plugins

fabric 1.19.3 
cloth-config-9.0.93-fabric.jar       
fabric-carpet-1.19.3-1.4.93+v221230.jar  
lithium-fabric-mc1.19.3-0.10.4.jar  
textile_backup-2.5.0-1.19.jar
Dynmap-3.5-beta-1-fabric-1.19.3.jar  
ferritecore-5.1.0-fabric.jar             
servercore-1.3.4-1.19.3.jar         
f2d-2.1.0+1.19.3.jar                 
floodgate-fabric.jar                     
starlight-1.1.1+fabric.ae22326.jar  
fabric-api-0.70.0+1.19.3.jar         
Geyser-Fabric.jar                        
tabtps-fabric-mc1.19.3-1.3.16.jar

### Geyser Dump

https://dump.geysermc.org/sZZRL5lgFRZtm3ZeCds6Inx0yTTaA6tG

### Geyser Version

Geyser : 2.1.0—SNAPSHOT

**Comment by Ai-Kiwi** [comment] 2023-01-04 01:10
to update I have tried removing all of my mods and the issue is still happening.

**Comment by Ai-Kiwi** [comment] 2023-01-04 01:16
this issue also appears not to happen when connecting va lan but does appear when connecting va my routing server.

**Comment by Camotoy** [comment] 2023-01-04 01:47
Does the issue happen with this build? https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/1265/

**Comment by Ai-Kiwi** [comment] 2023-01-04 02:34
> Does the issue happen with this build? https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/1265/

yes the issue is still happening with that version.

**Comment by Ai-Kiwi** [comment] 2023-01-04 02:42
it is also happening with the last non snapshot version.

**Comment by Ai-Kiwi** [comment] 2023-01-04 02:45
I don;t know if its just me imaging things but it feels like it happens a lot less on the last non snapshot build.

**Comment by Ai-Kiwi** [comment] 2023-01-04 02:53
![Screenshot 2023-01-04 155039](https://user-images.githubusercontent.com/66819523/210475464-f8028c14-dc01-4bca-a4a8-d112da780798.png)
weirdly tho in most of the chunks i can go into them fully and brake blocks and stuff and it just works. but i cant see anything but then after going abit further more into it i reach a invisible wall.

**Comment by Ai-Kiwi** [comment] 2023-01-04 03:02
tried resetting my settings file and this also has not fixed it

**Comment by Ai-Kiwi** [comment] 2023-01-04 03:03
> this issue also appears not to happen when connecting va lan but does appear when connecting va my tunneling server.

nvm it is happening on lan to

**Comment by Camotoy** [comment] 2023-01-04 03:55
What is your server render distance and Bedrock client render distance?

**Comment by Ai-Kiwi** [comment] 2023-01-04 05:25
> 

16 for both i have tried higher on bedrock and it doesn't seem to fix the problem.

**Comment by chenxi050402** [comment] 2023-01-06 05:03
same problem for mobile here, haven't got the problem with bedrock for windows yet

**Comment by Ai-Kiwi** [comment] 2023-01-07 08:47
> same problem for mobile here, haven't got the problem with bedrock for windows yet

The problem for me appeared to be happening on mobile and on computer.

**Comment by Ai-Kiwi** [comment] 2023-01-09 01:03
I have since moved my server to velocity and the issue persists

**Comment by Kas-tle** [comment] 2023-01-09 01:10
@Ai-Kiwi Would you mind allowing me to come on your server to capture some packets? I have not been able to reproduce this on my own. Feel free to DM the IP if you do not want to say it publicly (Kastle#4801 on Discord)

**Comment by DeRp-DaWg** [comment] 2023-01-09 01:47
This happens on my fabric server as well, on both the mobile and desktop bedrock client. I have a Velocity server with geyser and floodgate installed, that can connect you to the aforementioned fabric server, or my purpur server. The issue does not appear to happen on my purpur server, which i tested by flying around in creative mode.

**Comment by DeRp-DaWg** [comment] 2023-01-09 02:14
This also happens on my fabric server, on both the mobile and desktop bedrock client. I have a Velocity server with geyser and floodgate installed, that can connect you to the aforementioned fabric server, or my purpur server. The issue does not appear to happen on my purpur server, which i tested by flying around in creative mode.

**Comment by Kas-tle** [comment] 2023-01-09 08:56
@DeRp-DaWg could you see if this build improves things at all?
https://cdn.discordapp.com/attachments/1061824709995544727/1061899961312231484/Geyser-Velocity.jar

**Comment by ipodtouch6** [comment] 2023-01-09 17:47
I also encountered the same problem, I can't load the block when riding a minecart in the bedrock

**Comment by Kas-tle** [comment] 2023-01-09 18:25
@ipodtouch6 could you post a Geyser dump (obtain by executing the command `geyser dump` in console and providing the link here) and some screenshots if possible?

**Comment by ipodtouch6** [comment] 2023-01-09 18:29
> @ipodtouch6 could you post a Geyser dump (obtain by executing the command `geyser dump` in console and providing the link here) and some screenshots if possible?

I solved the problem with the old version, but the new version doesn't seem to work

**Comment by Kas-tle** [comment] 2023-01-09 18:35
@ipodtouch6 which new and which old version are you referring to? Also could you still please post a link to a Geyser dump here? It will help us better understand if there are any commonalities between the people experiencing the issue.

**Comment by ipodtouch6** [comment] 2023-01-09 18:55
https://dump.geysermc.org/qtF6QIZ1vsUTcas1HnLOxt7qgRiA8ktZ
2.1.0-SNAPSHOT (git-master-3437fc9) works fine
2.1.0-SNAPSHOT (git-master-c928baf) does not work
![F71624B7E53F59FC2D3E498E4DFAA359](https://user-images.githubusercontent.com/87911476/211385859-22714989-64c5-4db5-b3d2-63bddb6a7398.png)

**Comment by Kas-tle** [comment] 2023-01-09 19:13
@ipodtouch6 could you try with this build and see if it resolves the issue? It is based on the latest build with a single change made to the view distance the server sends to the client:
https://cdn.discordapp.com/attachments/1059942277025374329/1061900528302444574/Geyser-Spigot.jar

**Comment by ipodtouch6** [comment] 2023-01-09 19:40
> @ipodtouch6 could you try with this build and see if it resolves the issue? It is based on the latest build with a single change made to the view distance the server sends to the client: https://cdn.discordapp.com/attachments/1059942277025374329/1061900528302444574/Geyser-Spigot.jar

I think this is the build that is not working

**Comment by Kas-tle** [comment] 2023-01-09 19:42
You still experience the view distance issue with this build?

**Comment by ipodtouch6** [comment] 2023-01-09 19:46
> You still experience the chunk loading issue with this build?

Problem solved, it looks like everything works, thank you

**Comment by ipodtouch6** [comment] 2023-01-09 20:14
> > You still experience the chunk loading issue with this build?
> 
> Problem solved, it looks like everything works, thank you



> You still experience the chunk loading issue with this build?

I have a question, does Geyser bedrock support structure blocks?

**Comment by Kas-tle** [comment] 2023-01-09 20:15
For any discussion not related to this bug please join our discord: https://discord.gg/geysermc

**Comment by Kas-tle** [comment] 2023-01-10 05:25
So far I have confirmed that:
- The render distance chosen does not seem to be a factor.
- The errors seem to occur in roughly the same place and can persist over restarts.
- This is related to this PR: https://github.com/GeyserMC/Geyser/pull/3459. (Merged January 4th)
- Reverting the changes in this PR resolves the issue.
- The issue only affects Spigot and Fabric. Paper is not affected. I assume this has to do with the differences in Paper's chunk loading system since the whole thing is basically rewritten at this point.

**Comment by ipodtouch6** [comment] 2023-01-17 07:22
Unfortunately, the January 17th build still has issues with chunks not loading

> So far I have confirmed that:
> 
> * The render distance chosen does not seem to be a factor.
> * The errors seem to occur in roughly the same place and can persist over restarts.
> * This is related to this PR: [Fix wrong render distance calculation #3459](https://github.com/GeyserMC/Geyser/pull/3459). (Merged January 4th)
> * Reverting the changes in this PR resolves the issue.
> * The issue only affects Spigot and Fabric. Paper is not affected. I assume this has to do with the differences in Paper's chunk loading system since the whole thing is basically rewritten at this point.
> 
> It has been reported to me (but not personally confirmed) that:
> 
> * This may affect older versions of paper (1.17 is the newest version I was told)

Unfortunately, the January 17th build still has issues with chunks not loading

**Comment by Ai-Kiwi** [comment] 2023-01-17 07:25
> 
> Unfortunately, the January 17th build still has issues with chunks not loading
> 
> > So far I have confirmed that:
> > 
> > * The render distance chosen does not seem to be a factor.
> > * The errors seem to occur in roughly the same place and can persist over restarts.
> > * This is related to this PR: [Fix wrong render distance calculation #3459](https://github.com/GeyserMC/Geyser/pull/3459). (Merged January 4th)
> > * Reverting the changes in this PR resolves the issue.
> > * The issue only affects Spigot and Fabric. Paper is not affected. I assume this has to do with the differences in Paper's chunk loading system since the whole thing is basically rewritten at this point.
> > 
> > It has been reported to me (but not personally confirmed) that:
> > 
> > * This may affect older versions of paper (1.17 is the newest version I was told)
> 
> Unfortunately, the January 17th build still has issues with chunks not loading

The pull request had not yet been accepted as such the fix hasn't been added to code.

**Closed** 2023-01-20 15:02 UTC

**Comment by Tanza3D** [comment] 2023-07-04 13:42
i'm still having issues with this on my server
![image](https://github.com/GeyserMC/Geyser/assets/33783503/551e9a06-8067-40e5-b7bd-2de5a25d5b21)

**Comment by johnholton0** [comment] 2023-08-17 20:47
@Tanza3D Did you ever get a resolution to this? I'm encountering this issue with Minecraft PE players connecting to my Geyer-Spigot server.

**Comment by Tanza3D** [comment] 2023-08-17 22:26
> @Tanza3D Did you ever get a resolution to this? I'm encountering this issue with Minecraft PE players connecting to my Geyer-Spigot server.

i remember it kind of just not happening anymore after a while, but i don't think i ever did anything to explicitly stop it

**Comment by iDarknessSam** [comment] 2023-09-17 18:30
This problem is happening on me too

**Comment by Insane-Owl** [comment] 2023-10-23 21:50
This is still a problem for me as well

**Comment by KoenKDev** [comment] 2023-11-05 14:56
Happening to me too. Not a game-breaking because I can rejoin, but it's quite annoying, as you can't walk past the un-loaded chunk.
<img width="1440" alt="Screenshot 2023-11-05 at 9 56 03 AM" src="https://github.com/GeyserMC/Geyser/assets/78868475/8465bf56-266b-4bad-a9fe-28815ffac7fe">
<img width="1440" alt="Screenshot 2023-11-05 at 9 55 53 AM" src="https://github.com/GeyserMC/Geyser/assets/78868475/c5895a32-05eb-4c70-aec7-51aac6ffcc1f">

**Comment by Himori-0** [comment] 2023-12-13 17:38
> Happening to me too. Not a game-breaking because I can rejoin, but it's quite annoying, as you can't walk past the un-loaded chunk.
> <img width="1440" alt="Screenshot 2023-11-05 at 9 56 03 AM" src="https://github.com/GeyserMC/Geyser/assets/78868475/8465bf56-266b-4bad-a9fe-28815ffac7fe">
> <img width="1440" alt="Screenshot 2023-11-05 at 9 55 53 AM" src="https://github.com/GeyserMC/Geyser/assets/78868475/c5895a32-05eb-4c70-aec7-51aac6ffcc1f">
> 

Mine server have this problem too. Chunk stop loading for bedrock player they had to logout and in to load the chunk

**Comment by GERDominik165** [comment] 2024-01-16 20:23
![image](https://github.com/GeyserMC/Geyser/assets/11680289/ca8ce782-9e94-43a5-b20d-92428e8b405e)

same for me Paper Geyser 1.20.4 [Bedrock Screenshot]

**Comment by Bagashidayat1** [comment] 2024-06-30 17:04
still having same issue paper 1.21

**Comment by radishsprouts** [comment] 2024-07-27 09:56
I have still same problem in paper 1.21 too.

**Comment by Clumsius** [comment] 2024-08-06 00:42
Confirmed it still happens on Fabric 1.21.

**Comment by Clumsius** [comment] 2024-08-06 00:43
Has there been any way of bypassing this issue, or perhaps a branch?

**Comment by MarkHarrisMedia** [comment] 2024-09-29 15:56
My players and I are having this issue, some chunks wont load for bedrock players. Restarting the server and client wont help.  

Any recommendations??

**Comment by GERDominik165** [comment] 2024-10-25 12:00
Samen for me and my Friends on paper 1.21.1~

**Comment by Clumsius** [comment] 2024-11-10 16:27
Is this issue being worked on?

**Comment by CherubicBoot** [comment] 2025-01-18 04:35
> This problem has not yet been resolved. I was presented with a fixed build, but it is not up to date.

yep I can confirm this. it happened to me with the latest geyser standalone, connected to fabric 1.21.4 server.

**Comment by radishsprouts** [comment] 2025-01-21 06:31
I'm sure you know the cause of the problem, that the fixed build was released to the public on a limited basis a while ago, but why hasn't it been fixed forever?

**Comment by merkalev** [comment] 2025-07-27 07:19
problem not resolved on geyser velocity

**Comment by iDarknessSam** [comment] 2025-12-29 04:30
![Image](https://github.com/user-attachments/assets/4bb8189d-f2b6-477f-84e9-53a69502589c)

the client is on Minecraft Bedrock 1.21.131 while the server is on Paper 1.21.11
the issue is still the same on the newest update of Geyser. However, something is different today.
some users had reported that if they die close to the chunks that are not loading it suddenly start loading again as normal but only for a bit of time.

so they don't need to left the server and enter again, dying next to those unloaded chunks can also fix it.

**Comment by iDarknessSam** [comment] 2025-12-29 04:31
I wish geyser could provide a better debug feature to analyze how this bug actually happens, like a better log system or something.
