### ISSUE TITLE
Spectator Respawn or World Switch Zoom

### ISSUE THREAD

**Issue by gre3x** [GeyserMC/Geyser#3896] opened 2023-06-19 15:48 UTC
### Describe the bug

If you give mining fatigue to a bedrock player and set them in spectator mode at the same time as they are respawning, they get stuck in the mining fatigue/speed zoomed in view. 

Giving them further effects does not fix the zoom. Switching servers under a Bungeecord network does not fix the zoom. The only fix is to disconnect from the server entirely.

### To Reproduce

1. Kill player
2. On respawn, set the player to spectator mode and give them mining fatigue level 2+
3. Notice the zoomed in view
4. Remove the mining fatigue
5. Notice that the zoom stays forever until you disconnect from the server

### Expected behaviour

The zoom effect does not stay after mining fatigue is removed

### Screenshots / Videos

https://github.com/GeyserMC/Geyser/assets/123699236/446e28fe-528c-49b8-8ea6-7deaf101f547

### Server Version and Plugins

- Using Geyser standalone, but I have talked to others with this issue and it happens on regular Bungeecord setup too
- Flamecord is proxy with latest Floodgate for Bungee installed
- Server that this is happening on is Paper 1.12.2 with latest Floodgate for spigot and ViaVersion installed

### Geyser Dump

https://dump.geysermc.org/V8wZFQkb6l4kHpS8X8mCy0reA1RC5hjg

### Geyser Version

2.1.1-SNAPSHOT (git-master-bf5e084)

### Minecraft: Bedrock Edition Device/Version

1.20.0

### Additional Context

This bug was introduced within the last month.

It seems to have been introduced around one of these two PRs:
- https://github.com/GeyserMC/Geyser/pull/3770/files
- https://github.com/GeyserMC/Geyser/pull/3756/files

**Comment by gre3x** [comment] 2023-06-19 15:59
Here is a simple Skript to recreate this issue:

```
on respawn:
    set player's gamemode to spectator
    apply mining fatigue of tier 5 to player for 99 seconds
```

**Comment by SuprexDE** [comment] 2023-06-21 19:28
I have the same issue with my players: https://suprexde.de/img/Vove1/ZOvUwAFU86.mp4

**Comment by frogglen** [comment] 2023-06-22 08:33
same issue

**Comment by gre3x** [comment] 2023-06-27 17:38
Are there any updates on this? This has been causing issues for my players for over a week now and it is very inconvenient for them to have to leave and rejoin each time

**Comment by frogglen** [comment] 2023-06-27 20:47
> Are there any updates on this? This has been causing issues for my players for over a week now and it is very inconvenient for them to have to leave and rejoin each time

yeah me too

**Comment by gre3x** [comment] 2023-07-05 01:34
Are there any updates on this? This has been causing issues for my players for weeks now and it is very annoying for them to have to leave and rejoin each time

**Comment by lastsurvivors** [comment] 2023-07-06 08:55
same

**Comment by gamer50082** [comment] 2023-07-06 11:46
The issue is just being in spectator then changing to another dimension or server

**Comment by frogglen** [comment] 2023-07-06 17:09
this bug is very annoying

**Comment by onebeastchris** [comment] 2023-07-06 17:10
Thanks, noted. Bumping this issue will not help, it'll be fixed once someone has time to look into the bug & fix it - we are all volunteers here.

**Comment by frogglen** [comment] 2023-07-06 18:18
> Thanks, noted. Bumping this issue will not help, it'll be fixed once someone has time to look into the bug & fix it - we are all volunteers here.

Have you thought about converting to a paid geyser? I don't know maybe some monthly subscription or something that the project is more active with bug fixes, maybe some freepremium model that for those who pay they get the updates in a shorter time?

Don't you see it viable?

**Comment by onebeastchris** [comment] 2023-07-06 18:22
No.

**Comment by Camotoy** [comment] 2023-07-06 19:50
Geyser will never convert away from an open-source model. No tiers, no nothing - I believe in the power of open source and I'll stick with it.

Obviously this also means that some bugs can't be fixed as fast. If we ever need a revenue model, we'll look at a tier of paid support of some kind.

**Comment by guifenske** [comment] 2023-07-06 21:43
maybe is a good idea open like a donation thing, like ko-fi, or another platform to donate.

**Comment by onebeastchris** [comment] 2023-07-06 21:46
There already is a way to donate money to Geyser; but it currently isn't being used - https://opencollective.com/geysermc

It also specifically says 
> Please don’t donate specifically to request a specific feature. If you would like a feature to be implemented, create an issue on the GitHub repo and fill out the correct template!

**Comment by gamer50082** [comment] 2023-07-07 05:04
**Why is this happening**
- In spectator mode when switching server or dimension
**TEMPORARY FIX**
- Disable spectator mode when switching server or dimension (anything that will show the loading world screen on bedrock)

**Closed** 2023-09-06 22:13 UTC
Labels: Confirmed Bug
