### ISSUE TITLE
Water buckets and Lava buckets don't place properly

### ISSUE THREAD

**Issue by vijaypondini** [GeyserMC/Geyser#1674] opened 2020-12-14 10:55 UTC
**Describe the bug**
Water buckets either do not get placed, or gets placed in the incorrect position. Picking up water is also an issue. Same goes with lava

**To Reproduce**
Get a bucket and try to pick up water from a nearby water or lava source

**Expected behavior**
Should be placed on correct block, should be picking up the water/lava

**Screenshots / Videos**
https://imgur.com/a/f7BU5jK
_you can see for picking up water first few attempts worked but not after that _

**Server Version**
This server is running Paper version git-Paper-324 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
Previous version: git-Paper-320 (MC: 1.16.4)
You are 1 version(s) behind

**Geyser Version**
This server is running Geyser version 1.2.0-SNAPSHOT (git-master-41cb593) (Java: 1.16.4, Bedrock: 1.16.100/1.16.101 - 1.16.200.5)
Checking version, please wait...
1 versions behind
Using floodgate, and running on bungeecord

**Minecraft: Bedrock Edition Version**
Bedrock 1.16.200 ( latest )

**Additional Context**
https://dump.geysermc.org/X7XGpcx8mawBi5KaXfk6wJ40WrSrUGXK

**Comment by rtm516** [comment] 2020-12-14 10:56
Duplicate of #1293.

**Closed by rtm516** 2020-12-14 10:56 UTC
