### ISSUE TITLE
Hide BungeeTabListPlus fake players from the playerslist

### ISSUE THREAD

**Issue by Artuto** [GeyserMC/Geyser#1304] opened 2020-09-17 07:30 UTC
**What feature do you want?**
BungeeTabListPlus adds fake players to simulate a static tablist on Java, however, in Bedrock it just floods the tablist with fake entries. Would be nice for Geyser to filter them.

![Screenshot_20200917-022900.png](https://user-images.githubusercontent.com/9273973/93434371-ab863d00-f88d-11ea-80a1-bfece9b74b7a.png)

**Alternatives?**
I don't know any alternative

**Comment by bundabrg** [comment] 2020-09-17 07:36
Solved (sorta) in https://github.com/GeyserMC/Geyser/pull/711. This shows the actual names but they're all over the place due to order.

**Comment by DoctorMacc** [comment] 2020-09-18 17:41
Perhaps it would be worth it to add an option for plugins to instead use the API to determine which players are online?

**Comment by Chew** [comment] 2021-04-05 23:55
Hello! This appears to be a duplicate of #171, so we are closing in favor of it. Thank you for the report!

**Closed by Chew** 2021-04-05 23:55 UTC
