### ISSUE TITLE
Blocks in a large concentration are vacant when bedrock players play

### ISSUE THREAD

**Issue by Bluey-Wolf** [GeyserMC/Geyser#4436] opened 2024-02-10 15:05 UTC
###描述bug

基岩版的玩家在游玩时，会在一个不固定的位置出现一个很大的区块空缺，通过它可以看穿其他区块的内部，而这个空缺的区块在重新加入服务器后会被恢复。只有基岩玩家才会有这个问题。

###要复制

1.加入游戏并四处走动
2.观察到地图中有一个或多个块是空的。

###预期行为

发现地图中有一个或多个区块空缺，重新进入服务器后恢复正常。

###截图/视频

![Image_1707580530137](https://github.com/GeyserMC/Geyser/assets/158538687/9f27d9ee-3927-4a77-b10d-05570491f213)
![Image_1707580528324](https://github.com/GeyserMC/Geyser/assets/158538687/5ce013ea-644f-435b-a302-32699185a741)
![Image_1707580526627](https://github.com/GeyserMC/Geyser/assets/158538687/6d5bdcaf-4593-44eb-96c7-0cfdfdacf69d)
![Image_1707580524524](https://github.com/GeyserMC/Geyser/assets/158538687/87212160-8442-4db8-a07a-415870b52977)
![Image_1707580521852](https://github.com/GeyserMC/Geyser/assets/158538687/187b4674-1e3c-4480-98c1-d753fdcdcce2)
![IMG_20240210_235749](https://github.com/GeyserMC/Geyser/assets/158538687/400a65f0-6721-432d-8ae8-b19c9a4b3e3c)

###服务器版本和插件

插件（8个）:SpigotPing，MoveLight，CustomCommandPrefix，ViaVersion，floodgate，eBackup，VeinMiner，Geyser-spigop

###喷泉垃圾场

https://dump.geysermc.org/9BSpk8rKHhSZsX2YsRGgvu3jzYIdNBkN

###间歇泉版本

2.2.2快照（git-master-19c6648）

###《我的世界》:基岩版设备/版本

iOS、Android和Windows系统

###附加上下文

_无响应_

**Comment by onebeastchris** [comment] 2024-02-10 15:08
please share a screrenshot or video showcasing the issue

**Comment by Bluey-Wolf** [comment] 2024-02-10 15:58
> 请分享展示该问题的截图或视频

![IMG_20240210_235749](https://github.com/GeyserMC/Geyser/assets/158538687/a1619a64-8538-4ffb-b1b2-25ddb0460a72)
![Image_1707580530137](https://github.com/GeyserMC/Geyser/assets/158538687/b0a46073-c65e-43f1-86b5-08bd4f635f79)
![Image_1707580528324](https://github.com/GeyserMC/Geyser/assets/158538687/8bb3b71e-c0a8-4ed4-a496-00a0332d62e1)
![Image_1707580526627](https://github.com/GeyserMC/Geyser/assets/158538687/a9a9eda5-2581-4da5-b627-0a8e41227156)
![Image_1707580524524](https://github.com/GeyserMC/Geyser/assets/158538687/a51342b3-3c3a-46d6-9ff3-396597734999)
![Image_1707580521852](https://github.com/GeyserMC/Geyser/assets/158538687/01756d42-a1ab-455d-9685-eaffa77c5fab)

**Comment by onebeastchris** [comment] 2024-02-10 16:14
Are you seeing any errors in the server console?
Please send a full log (latest.log file) via mclo.gs (or paste.gg) here

**Comment by Kas-tle** [comment] 2024-02-10 16:32
Looks like a duplicate of https://github.com/GeyserMC/Geyser/issues/3809

**Comment by Kas-tle** [comment] 2024-02-10 16:33
What is the server view distance and what is the view distance of the bedrock client?

**Comment by Bluey-Wolf** [comment] 2024-02-11 02:55
> 您是否在服务器控制台中看到任何错误？请在此处通过 mclo.gs（或 paste.gg）发送完整的日志（latest.log文件）
It only sometimes appears when a player joins.It seems that when an error appears, the player cannot join the game
https://mclo.gs/qtimp3u
I think these errors are related to another issue. Because even if there are no errors, these problems still occur. I've used paper1.18.2 before and the issue still appears and the console doesn't report an error.

**Comment by Bluey-Wolf** [comment] 2024-02-11 03:04
> 什么是服务器视距，什么是基岩客户端的视距？
The server sight distance used to be set to 16 blocks, 12 blocks, and 10 blocks
The client has probably only set 10 and 12 sight distances, and I don't know if players have changed this setting.
However, it can be confirmed that the problem occurs no matter how far the server is set. Just set the same issue to appear a little less?

**Comment by Kas-tle** [comment] 2024-02-11 03:07
Setting the server render distance further will only increase the frequency of the issue. It must be decreased to below the render distance of the client.

**Comment by Bluey-Wolf** [comment] 2024-02-11 09:11
> 进一步设置服务器渲染距离只会增加问题出现的频率。它必须减小到客户端的渲染距离以下。

Okay, I did it. Don't close the topic, I will observe for a few more days to see if the problem has occurred.

Now the sight distance of the server is set to 8 blocks.The sight distance of the player client is nine blocks, ten blocks and sixteen blocks respectively.

**Comment by Bluey-Wolf** [comment] 2024-02-11 14:11
> 进一步设置服务器渲染距离只会增加问题出现的频率。它必须减小到客户端的渲染距离以下。
The problem still appears, but with less frequency.

The sight distance of the server is set to 8 blocks, and several players with the sight distance of the client set to 9 blocks reported the situation.

**Comment by Bluey-Wolf** [comment] 2024-02-11 14:13
> 进一步设置服务器渲染距离只会增加问题出现的频率。它必须减小到客户端的渲染距离以下。

The problem still exists, but the frequency is reduced. The sight distance of the server is set to 8 blocks, and several players with the sight distance of the client set to 9 blocks reported this situation.

**Comment by Bluey-Wolf** [comment] 2024-02-11 14:14
> 进一步设置服务器渲染距离只会增加问题出现的频率。它必须减小到客户端的渲染距离以下。

The problem still exists, but the frequency is reduced. The sight distance of the server is set to 8 blocks, and several players with the sight distance of the client set to 9 blocks reported this situation.

**Comment by Bluey-Wolf** [comment] 2024-02-12 03:53
> Setting the server render distance further will only increase the frequency of the issue. It must be decreased to below the render distance of the client.

The problem still exists, but the frequency is reduced.![Image_1707709907109.jpg](https://github.com/GeyserMC/Geyser/assets/158538687/0ea05fc4-5b4e-4db6-af62-124df1a01789)

![Image_1707709904700.jpg](https://github.com/GeyserMC/Geyser/assets/158538687/9c521583-57b1-4863-983c-745ab181e927)

![Image_1707709902560.jpg](https://github.com/GeyserMC/Geyser/assets/158538687/721df4bf-4546-48b8-bf6b-5f2eef39177d)

**Comment by Bluey-Wolf** [comment] 2024-03-06 04:09
> 我也遇到相同的问题，且日志中也没有见到相关的报错，同时如果在问题出现前有铺设铁轨，借助矿车能够移动到无法加载的区域中，但如果没有，光靠方向键移动则会遇到一种类似于假墙的东西，有一条无形的边界，哪怕是开创造模式在空中飞行也无法穿过，只有靠退出游戏再重新进入来解决 我也遇到了同样的问题，我在日志中没有看到任何相关错误。同时，如果在问题发生之前铺设了铁轨，我可以使用矿车移动到无法装载的区域，但如果没有，我只能依靠方向键来移动。你会遇到类似于假墙的东西，有一个看不见的边界，即使你以创造模式在空中飞行也无法通过。您只能通过退出游戏并重新进入游戏来解决它。
> 
> 更新：我使用命令上传转储和错误报告，这是网址：https://dump.geysermc.org/cY3MT2czWKRlRdGfeNGkisUob9bG0860`geyser dump`

I'm in the same situation! And wandering animals can also enter the empty area, players can not.

**Comment by Bluey-Wolf** [comment] 2024-03-06 04:10
The problem was solved after the sight distance was set, but this was awkward and the server's sight distance was forced to be adjusted very low to suit the player's needs. Will this issue be resolved in future versions?

**Comment by Bluey-Wolf** [comment] 2024-03-06 04:11
> please share a screenshot or video showcasing the issue
The problem was solved after the sight distance was set, but this was awkward and the server's sight distance was forced to be adjusted very low to suit the player's needs. Will this issue be resolved in future versions?

**Comment by Kas-tle** [comment] 2024-03-06 04:20
Given reducing the render distance solves this issue this is a duplicate of https://github.com/GeyserMC/Geyser/issues/3809 so I'll be closing this and you can follow for updates there. Unfortunately we have not been able to pinpoint the cause of this issue, but I suspect it comes down to the client getting chunks from the server outside the range it's expecting. You could try using Paper, which as I recall is less likely to experience this issue than plain Spigot.

**Closed** 2024-03-06 04:21 UTC
