### ISSUE TITLE
Blank world when joining

### ISSUE THREAD

**Issue by ScribbleNerd** [GeyserMC/Geyser#265] opened 2020-04-03 12:50 UTC
**Describe the bug**
When joining my server, Bedrock just shows a void and I cant move, in Java it just shows the player standing in one spot and they cannot be interacted with.

**To Reproduce**
1. Setup Geyser as a plugin on a bungeecord server
2. Setup floodgate as a plugin on the bungeecord server
3. Connect to bungeecord server
4. Shows void

**Expected behavior**
I'm supposed to be able to join the server and see the world

**Screenshots**
![image](https://user-images.githubusercontent.com/31575858/78362373-99cf0880-757f-11ea-8b81-a0aea182674f.png)
![image](https://user-images.githubusercontent.com/31575858/78362392-9fc4e980-757f-11ea-8146-511339e7fdc0.png)

**Server version**
CraftBukkit version git-Spigot-a03b1fd-bbe3d58 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Geyser version**
Jenkins Bungeecord

**Bedrock version**
v1.14.30

**Comment by ScribbleNerd** [comment] 2020-04-03 12:52
The server you see in the screenshots has no plugins so its not an issue with conflicting plugins at least on the spigot side... on BungeeCord I have:
1. BungeeChat-2.1.6.855
2. floodgate-bungee
3. Geyser-BungeeCord.jar
4. LuckPerms-Bungee-5.0.104

**Comment by DoctorMacc** [comment] 2020-04-03 14:28
This is likely connected to issue #186. (The title mentions ViaVersion but people have had problems without it as well)

**Comment by Ruymanphone** [comment] 2020-04-03 17:48
+1 I have too this problem

**Comment by RednedEpic** [comment] 2020-04-03 17:48
Try using #196.

**Comment by Ruymanphone** [comment] 2020-04-03 17:52
Can you offer us the previous version of the plugin? It only failed me in this build xd

**Comment by RednedEpic** [comment] 2020-04-03 17:53
> Can you offer us the previous version of the plugin? It only failed me in this build xd

Click the `Checks` tab on that PR page, then click `Artifacts`.

**Comment by Heath123** [comment] 2020-04-03 19:16
> I don't have Github in English xd

https://github.com/GeyserMC/Geyser/suites/502761101/artifacts/2584235
Here's the link to the BungeeCord version

**Comment by Loganh4005** [comment] 2020-04-03 22:18
https://github.com/GeyserMC/Geyser/issues/263 This issue might have SOMETHING to do with your case due to spaces in your name

**Comment by RednedEpic** [comment] 2020-04-03 22:19
> #263 This issue might have SOMETHING to do with your case due to spaces in your name

Highly unlikely.

**Comment by Loganh4005** [comment] 2020-04-03 22:20
ok (you were very fast)

**Comment by barpec12** [comment] 2020-04-03 22:54
> 
> 
> > I don't have Github in English xd
> 
> https://github.com/GeyserMC/Geyser/suites/502761101/artifacts/2584235
> Here's the link to the BungeeCord version

This fixed this issue for me (Waterfall with Viaversion, servers on 1.15.2), latest Bedrock Edition

**Comment by awSteven** [comment] 2020-04-04 06:43
Can confirm this is also a bug on the bukkit plugin version of floodgate.

**Comment by LegacyGamerHD** [comment] 2020-04-04 06:47
I can confirm also

**Comment by RednedEpic** [comment] 2020-04-04 07:12
Fixed with ad3ca436b9f9edbe423fed02c94ebf953a524766.

**Closed by RednedEpic** 2020-04-04 07:12 UTC
Labels: Confirmed Bug, Priority: High

**Comment by LegacyGamerHD** [comment] 2020-04-04 09:33
@RednedEpic its still happning

**Comment by barpec12** [comment] 2020-04-04 22:07
For me it does not work too (tested with inventory branch), this version https://github.com/GeyserMC/Geyser/issues/265#issuecomment-608763280 still works.

**Comment by RednedEpic** [comment] 2020-04-04 22:08
> For me it does not work too (tested with inventory branch), this version [#265 (comment)](https://github.com/GeyserMC/Geyser/issues/265#issuecomment-608763280) still works.

Do you by chance get any sort of error in console?

**Comment by barpec12** [comment] 2020-04-04 22:11
Unfortunately no.

**Comment by RednedEpic** [comment] 2020-04-04 22:12
> Unfortunately no.

And how about with master?

**Comment by barpec12** [comment] 2020-04-04 22:17
Same.

**Comment by Ruymanphone** [comment] 2020-04-05 00:32
Fixed to me in #5 build

**Comment by Ruymanphone** [comment] 2020-04-05 00:37
@RednedEpic I put more information about the problem #209

**Comment by barpec12** [comment] 2020-04-06 18:48
Now everything works in master and inventory branch
