### ISSUE TITLE
Ghost players

### ISSUE THREAD

**Issue by Elapy** [GeyserMC/Geyser#695] opened 2020-05-30 03:25 UTC
**Describe the bug**
So far all I know of is this occurring when transitioning world, teleporting, or switching servers so I believe this happens when your position changes instantaneously. The bug, as in the title, is a ghost in some way. It's as if, your soul left your body or something. On the server, it just sees you as a normal afk player that can be punched and other stuff, but on the bedrock screen, he could be off a million blocks away, (just an example he doesn't have to be super far away for this to happen) on the bedrock screen, as a ghost, can't really edit anything, and the ghost can't be edited. For example, the quote on quote "player" which technically doesn't exist to the server can't break any blocks (apparently they actually can even though they aren't there as seen in the video), and mobs can't see it, and can't get hurt, but if the "afk" body gets hurt, it'll show the ghost take damage on he bedrock screen. And when the bedrock "player" moves around, the actual player doesn't. As i said, as if he's just standing there afk. Also, when you relog on bedrock your character spawns in the place it was supposed to be, the place the the character was on the java screen.

**To Reproduce**

**Expected behavior**
 For the controls to move the real player. not a fake ghost that doesn't exist 

**Screenshots / Videos**
[https://drive.google.com/file/d/1Iaflmg_yggEeE9c4cb1J7llEhwqed7H3/view?usp=sharing](url) [https://drive.google.com/file/d/1RC-Lz2ZQDccp7CwBOzfSGYRZjwujfhZs/view?usp=sharing](url) [https://drive.google.com/file/d/19s9NHbMxGFI0obcNmMhAA1O0tJV6AZQt/view?usp=sharing](url) [https://drive.google.com/file/d/1uRuVF54XGZdmM11ZAoLcEq5aoqQJYdBB/view?usp=sharing](url) [https://drive.google.com/file/d/11acZBw1qRIB06qPxOC1ufsgBcl0tKIDW/view?usp=sharing](url)

**Server Version**
 Paper version git-Paper-280 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT) (45 version(s) behind)

**Geyser Version**
 I'm using Geyser-Bukkit v1.0-SNAPSHOT 

**Minecraft: Bedrock Edition Version**
1.14.60 

**Additional Context**
 I think I covered everything I've discovered so far. Sorry I couldn't screen record my java screen because I'm still trying to fix my screen recorder atm

**Comment by OnlyBMan** [comment] 2020-05-30 03:28
Can you please fill out the forum to help us figure out the cause of the problem? It would be greatly appreciated! Thanks!

**Comment by Elapy** [comment] 2020-05-30 03:29
I don't know what's happening. They are filled out. My forms look empty but when I edit it, it shows everything

**Comment by DoctorMacc** [comment] 2020-05-30 03:30
Issue has been fixed.

**Comment by Elapy** [comment] 2020-05-30 03:35
> Issue structure has been fixed.

Oh thanks. Can you guys see it now?

**Comment by pilock** [comment] 2020-06-02 14:14
i have that problem too
When be players walk on the steps, they are occasionally pulled back, and there is a probability that players' entities stay in place (on the Java screen), but on the bedroom screen, and they are always moving

**Comment by RednedEpic** [comment] 2020-07-12 01:19
Is this still a problem?

**Comment by Elapy** [comment] 2020-07-12 01:47
I don’t know I haven’t tested it for any while. I disabled the command
block till resolved

**Comment by RednedEpic** [comment] 2020-12-12 08:16
Closing in favor of #1468.

**Closed by RednedEpic** 2020-12-12 08:16 UTC
