### ISSUE TITLE
[1.16] Command blocks do not work

### ISSUE THREAD

**Issue by ayunami2000** [GeyserMC/Geyser#914] opened 2020-07-07 17:38 UTC
**Describe the bug**

Using the 1.16 release, command blocks do not work at all and I also cannot break them even though I have given myself op on the server.
**To Reproduce**

1. Start the server
2. Give yourself OP via server console
3. Give yourself a command block (/give @s command_block) (note: this also affects repeating command blocks and chain command blocks I believe)
4. Try to break or open the command block and nothing will happen
**Expected behavior**

When right clicking the command block the command editing GUI opens and you can edit the command block.
When left clicking the command block the command block breaks.
**Screenshots / Videos**

they are applicable but this is a very simple issue
**Server Version**

`Paper version git-Paper-79 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)`
**Geyser Version**

`Geyser version 1.0.0 (git-feature/1.16-f68632f)`
**Minecraft: Bedrock Edition Version**

Minecraft Windows 10 edition v1.16.1
**Additional Context**

Plugins:
Geyser (Spigot plugin)
LibsDisguises 10.0.14 (Free)
ProtocolLib 4.6.0-SNAPSHOT-b472

My guess for this issue is that geyser is telling the bedrock edition client that they don't have permission to edit command blocks. But that's just a guess based on what this issue actually is.

**Comment by DoctorMacc** [comment] 2020-07-07 17:41
Duplicate of #754. I don't think there is information on the breaking part however if you would like to copy that information over. Thank you for reporting anyway!

**Closed by DoctorMacc** 2020-07-07 17:41 UTC
