### ISSUE TITLE
Anvils appearing above players heads

### ISSUE THREAD

**Issue by Wolfst0rm** [GeyserMC/Geyser#1449] opened 2020-10-25 12:01 UTC
**Describe the bug**
Anvils when being operated by Bedrock Players, glitches out slightly

**To Reproduce**
1. Open Up any anvil
2. Anvil moves to above players head. 

**Expected behavior**
Anvil should not be moving to be above a player. 

**Screenshots / Videos**
https://youtu.be/3InMzJkBrrw 

**Server Version**
git-Paper-246 (MC: 1.16.3) (Implementing API Version 1.16.3-R0.1-SNAPSHOT)

**Geyser Version**
Geser Version 1.1.10 (git-master-dfba278) (Java 1.16.3, Bedrock: 1.16.0 - 1.16.20)

**Minecraft: Bedrock Edition Version**
v1.16.40

**Additional Context**

https://dump.geysermc.org/6kRYDiyPfTopY1D8zZsVNMesFZyx3NBl

**Comment by XlynxX** [comment] 2020-10-25 12:11
btw video is blocked to watching

**Comment by Wolfst0rm** [comment] 2020-10-25 12:13
Ah forgot to save the Setting for Unlisted! My bad!

**Comment by JonArcherII** [comment] 2020-10-25 12:44
AFAIK this is a workaround for Java clients expecting the anvil to be straight forward from where the player is facing, and this happens for cases when the player isn't (ie. tapping on the far left/right of their screen). So this actually is the intended behavior.

Also, I believe this happens with chests as well.

**Comment by DoctorMacc** [comment] 2020-10-25 14:47
Yes, as this is intentional for the time being, I am going to close it. (The reason is that Bedrock always needs to have a physical inventory to open, so in cases like virtual inventories this is required) We are aware of this issue, and other issues cover the "inventory on top of your head" in different aspects. Regardless, thank you for reporting!

**Closed by DoctorMacc** 2020-10-25 14:47 UTC
