### ISSUE TITLE
Bedrock players crashing upon slash Command use 

### ISSUE THREAD

**Issue by TheGodPancake** [GeyserMC/Geyser#4256] opened 2023-10-30 03:44 UTC
### Describe the bug

Bedrock players crashing upon using any / commands and sometimes when they are typing started happening after the newest bedrock update.

### To Reproduce

Go onto bedrock edition do a /command 

### Expected behaviour

It will crash for some players but other can still use commands it's inconsistent 

### Geyser Version

Latest

### Minecraft: Bedrock Edition Device/Version

Ps4, Xbox series x

**Comment by onebeastchris** [comment] 2023-10-30 07:29
Duplicate of https://github.com/GeyserMC/Geyser/issues/3990 - see there for a temp fix. This is likely a Bedrock edition client bug.

**Closed by onebeastchris** 2023-10-30 07:29 UTC
