### ISSUE TITLE
Native teleport command doesn't work with coordinates

### ISSUE THREAD

**Issue by tlaundal** [GeyserMC/Geyser#565] opened 2020-05-15 10:13 UTC
**Describe the bug**
When teleporting a player with the "native" teleport command (`/minecraft:teleport`) with  a target and absolute coordinates, the bedrock client does not receive any chunks, and the player appears to float in the sky.

Example command: `/minecraft:teleport aplayername 10 65 10`

I have only tried to reproduce on standalone geyser.

**To Reproduce**
1. Setup a fresh vanilla minecraft server and standalone geyesr
2. Connect with a bedrock client
3. Find your coordinates and execute the teleport command, for example with location a few blocks above your head

**Expected behavior**
The client should be moved to the location specified in the command

**Server Version**

Vanilla minecraft server 1.15.2 and paper `git-Paper-245 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`

**Geyser Version**

Geyser standalone built from source: `Geyser version 1.0-SNAPSHOT (git-master-919af52)`

**Minecraft: Bedrock Edition Version**

Bedrock `1.14.60`

**Comment by rtm516** [comment] 2020-05-15 10:16
Using essentials tp works fine.
So if I use essentials TP to do `/tp 1230 100 934` I end up at `1230 100 934`
Then if I try `/minecraft:tp -1000 100 500` from there I end up at `231.0, 202.0, 1435.0`
We do get an unconfirmed teleport, which is most likely causing the bug.
```
Unconfirmed Teleport 5 Ignore movement (231.0, 202.0, 1435.0) expected TeleportCache(x=-999.5, y=100.0, z=500.5, teleportConfirmId=5)
```

**Comment by Heath123** [comment] 2020-05-29 11:03
> Using essentials tp works fine.
> So if I use essentials TP to do `/tp 1230 100 934` I end up at `1230 100 934`
> Then if I try `/minecraft:tp -1000 100 500` from there I end up at `231.0, 202.0, 1435.0`
> We do get an unconfirmed teleport, which is most likely causing the bug.
> 
> ```
> Unconfirmed Teleport 5 Ignore movement (231.0, 202.0, 1435.0) expected TeleportCache(x=-999.5, y=100.0, z=500.5, teleportConfirmId=5)
> ```
> 
>  
> Edit: (Most likely a separate issue)
> Looks like an issue with TP cache as using a relative TP `/minecraft:tp ~ ~10 ~` causes the cache to think the target coords are `0 10 0`

The issue happens because the teleport translator assumes that teleports are always either relative or absolute, but they can be a combination of both. Fixed in #688. See https://wiki.vg/Protocol#Player_Position_And_Look_.28clientbound.29 and https://github.com/Steveice10/MCProtocolLib/blob/master/src/main/java/com/github/steveice10/mc/protocol/packet/ingame/server/entity/player/ServerPlayerPositionRotationPacket.java

**Closed** 2020-05-29 19:11 UTC
Labels: Confirmed Bug, Priority: High
