### ISSUE TITLE
Boat

### ISSUE THREAD

**Issue by TANJIL87** [GeyserMC/Geyser#2708] opened 2021-12-16 22:14 UTC
### Describe the bug

When u place a boat on water it disappears from you're inventory but it doesn't place on water ! Other player cab see your boat on your hand ! If you switch anything with that inventory slot it appears again on you're inventory ! You need try many times ti place it ! 

### To Reproduce

I don't know

### Expected behaviour

It should be normal ! It should place the boat at first time

### Server Version and Plugins

Geyser 2.0.0

### Geyser Dump

https://dump.geysermc.org/ebGzWbMQ6yUCZlZjDiBrnna5KLqNDkbg

### Geyser Version

Geyser 2.0.0- snapshot (git-master 90442a8 )

### Minecraft: Bedrock Edition Version

1.8.0

### Additional Context

What else ?

**Comment by Konicai** [comment] 2021-12-16 23:27
Duplicate of https://github.com/GeyserMC/Geyser/issues/1247

**Closed by Konicai** 2021-12-16 23:27 UTC
