### ISSUE TITLE
Pottery, Unable to Craft Sherds into Jars

### ISSUE THREAD

**Issue by BinaryBible** [GeyserMC/Geyser#3991] opened 2023-07-17 03:46 UTC
### Describe the bug

Players on Bedrock are unable to craft Pottery Sherds into Pottery Jars on our server.

Java players are able to craft Pottery Sherds into Pottery Jars.

### To Reproduce

1. Collect or spawn in 4 Pottery Sherds or 3 Pottery Sherds and 1 Clay Brick
2. Arrange Sherds/Brick into crafting grid

### Expected behaviour

Ability to make Pottery Jars

### Screenshots / Videos

![Screenshot_20230709_132028_Minecraft](https://github.com/GeyserMC/Geyser/assets/41652148/9cc58da7-f355-4b2a-959d-6788452c95e1)

### Geyser Dump

https://dump.geysermc.org/fIo7swIKOJ1Hsl3aapKYihlrHFoDPsqx

### Geyser Version

2.1.2-SNAPSHOT (git-master-340be2d)

### Minecraft: Bedrock Edition Device/Version

1.20.1 Bedrock, All Platforms

### Additional Context

Able to craft Pottery Sherds into Pottery Jars on 1-player Bedrock Worlds.

**Comment by onebeastchris** [comment] 2023-08-03 15:18
I cannot replicate this issue using Paper 1.20.1. 
![image](https://github.com/GeyserMC/Geyser/assets/105284508/2eb12025-f276-4206-804c-75cc6f73b660)
What i could imagine would be the recipe not being sent to the client during login; are all your servers on 1.20/1.20.1?

**Comment by BinaryBible** [comment] 2023-08-03 22:35
Yes. I am thinking of contacting CustomCrafting about this as well, as I feel they could be the culprit. I have been on other cross-compatible servers which don't seem to have this issue,  but they don't have custom crafted items. Thank you for your attempts to replicate.

**Comment by onebeastchris** [comment] 2024-06-10 23:51
Closing due to no reproduction steps being provided - if this is still an issue, open a new issue with steps to replicate the issue. Thanks!

**Closed by onebeastchris** 2024-06-10 23:51 UTC
Labels: Unconfirmed Bug/Not Currently Replicable
