### ISSUE TITLE
[TAB/Geyser] Nametag Issue & Nametag Delay

### ISSUE THREAD

**Issue by bubbakadriu** [GeyserMC/Geyser#3477] opened 2022-12-24 19:59 UTC
### Describe the bug

Nametag Issue:

Hi, i recently added the plugin TAB to edit my players nametag above head. I was using no previous nametag plugin before adding this. I am having an issue where the old nametag prints ontop/behind the new nametag created by TAB. As a result you can see the image below. Ive also noticed that the nametag doesnt always appear aswell, it just appears as a plain white text name. The issue only happens on bedrock as ive had java players testing it.

Nametag Delay:

When players run around, you can see their nametag lagging behind and not staying right above their heads. It looks kind of janky not being a static nametag and bouncing around.

### To Reproduce

Add TAB Plugin

Setup a nametag (multiple would be best)

Have java players on your server (seems to happen to java players)

It doesnt always happen, its around 10% chance for me to have this issue

### Expected behaviour

Players name tags should be static above head, and never have another nametag overlay

### Screenshots / Videos

![2572066F-F7D9-4536-A9C8-1B5A18C617F3](https://user-images.githubusercontent.com/38432044/209449561-47855cd0-b346-4622-92a5-17cad83aab97.jpeg)

### Server Version and Plugins

![F746C167-D915-460F-AF50-61C9724C09C3](https://user-images.githubusercontent.com/38432044/209449570-202ce21f-74a7-4565-a495-d13f920001a3.png)

### Geyser Dump

https://dump.geysermc.org/eA4VzcfdX4XFf63jDyHPd6RNJS81OGJ3

### Geyser Version

2.1.0-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

git-Purpur-1845

**Comment by Camotoy** [comment] 2022-12-24 20:47
Looks like this is a duplicate of #3323. I'll try to test this when I'm free, but I think the last time I tested this I was unable to replicate so maybe there's something specific in your config that causes it?

**Closed by Camotoy** 2022-12-24 20:47 UTC
