### ISSUE TITLE
1.12.2 Players are automatically kicked out of the server after one minute.

### ISSUE THREAD

**Issue by Monutchuan** [GeyserMC/Geyser#5082] opened 2024-10-13 12:29 UTC
### Describe the bug

1.12.2 Players are automatically kicked out of the server after one minute.

### To Reproduce

After joining the server, about a minute later, the player disconnected in the background, but the game was still running. Meanwhile, some messages appeared in the console such as...

[20:17:00 WARN] Unknown compression algorithm 94
[20:17:00 WARN] Unknown compression algorithm 43
[20:17:00 WARN] Unknown compression algorithm -17
[20:17:00 WARN] Unknown compression algorithm -100
[20:17:00 WARN] Unknown compression algorithm 74
[20:17:00 WARN] Unknown compression algorithm 23
[20:17:00 WARN] Unknown compression algorithm -62
[20:17:00 WARN] Unknown compression algorithm 122
[20:17:00 WARN] Unknown compression algorithm 111
[20:17:00 WARN] Exception caught in session ofMonutchuan: readerIndex(2) + length(10281) exceeds writerIndex(31): AbstractPooledDerivedByteBuf$PooledNonRetainedSlicedByteBuf(ridx: 2, widx: 31, cap: 31/31, unwrapped: PooledUnsafeDirectByteBuf(ridx: 55, widx: 55, cap: 2048))
[20:17:01 WARN] Unknown compression algorithm -64
[20:17:01 WARN] Unknown compression algorithm 38
[20:17:01 WARN] Unknown compression algorithm 58
[20:17:01 WARN] Unknown compression algorithm 68
[20:17:01 WARN] Unknown compression algorithm -82
[20:17:01 WARN] Unknown compression algorithm -84
[20:17:01 WARN] Unknown compression algorithm -55

### Expected behaviour

The player can play the game normally, for example, blocks will fall when destroyed, the inventory interface can be opened, etc. (this is exactly what I want to do).

### Server Version and Plugins

Server Version: paper-1.12.2-1620.jar
Plugins: (with Geyser-Standalone)
![屏幕截图 2024-10-13 202602](https://github.com/user-attachments/assets/c89fa25f-209a-485b-b68e-c23f3e0407c1)

### Geyser Dump

 https://dump.geysermc.org/YiBsAXvro2KazGcauwdV43DBsYtvNbYl

### Geyser Version

2.4.3-b689 (git-master-d64c0b3)

### Minecraft: Bedrock Edition Device/Version

1.20.80, Windows 10 & Android

**Comment by onebeastchris** [comment] 2024-10-17 07:13
Duplicate of https://github.com/GeyserMC/Geyser/issues/2861 - update your Java installation, for example from here: https://adoptium.net/temurin/releases/

**Closed by onebeastchris** 2024-10-17 07:13 UTC
