### ISSUE TITLE
Java to bedrock texterpack support

### ISSUE THREAD

**Issue by Creeperz653** [GeyserMC/Geyser#1726] opened 2020-12-21 19:02 UTC
**What feature do you want?**
so there needs to be support for java texterpacks to bedrock even if they cant do that can they at lest add a area where i can put my bedrock texterpack  because i have no problem remaking the texter pack for bedrock <my texterpack adds custom music disks
**Alternatives?**
none

**Comment by Creeperz653** [comment] 2020-12-21 19:04
**e**

**Comment by Camotoy** [comment] 2020-12-21 19:05
Duplicate of #210. Thank you for reporting regardless!

**Comment by EasyClifton** [comment] 2020-12-21 19:05
This functionality already exists. You can put bedrock resource packs into the `packs` folder in the Geyser folder and they will be sent to bedrock players on join. Also, please ask these sorts of questions on our [Discord](https://discord.geysermc.org) server.

**Closed by Camotoy** 2020-12-21 19:05 UTC

**Comment by Creeperz653** [comment] 2020-12-21 19:14
ohhhh i didnt know

**Comment by ByteMyRaspberryPi** [comment] 2021-08-05 21:12
Do I have to manually convert a Java resource pack to a bedrock resource pack with an online tool and then place it in this folder?
