### ISSUE TITLE
the name with space will caue the command not work fine

### ISSUE THREAD

**Issue by pbs666** [GeyserMC/Geyser#700] opened 2020-05-30 14:11 UTC
sometimes the bedrock edition players'names with space will cause the commands not work fine
This caused me to be unable to execute some instructions to some players with blank names, especially the plugin registration instructions, the server will see "XXX XXX" as two parts, resulting in the command can not be used normally, I hope to fix it as soon as possible! It made a big difference. Thank you.

**Comment by DoctorMacc** [comment] 2020-05-30 14:12
Marking this as a duplicate of #263 since they both cover the same thing.

**Comment by DoctorMacc** [comment] 2020-05-30 14:13
For now, if you want to solve the problem, use Floodgate.

**Closed** 2020-05-30 14:12 UTC
Labels: Duplicate

**Comment by pbs666** [comment] 2020-05-30 14:16
emmm....what is the Floodgate?

**Comment by DoctorMacc** [comment] 2020-05-30 14:19
https://github.com/GeyserMC/Floodgate/
https://github.com/GeyserMC/Geyser/wiki/Floodgate

**Comment by rtm516** [comment] 2020-05-30 14:19
Join the discord if you have any other questions http://discord.geysermc.org/

**Comment by pbs666** [comment] 2020-05-30 15:23
emmmm
what's happen?
i use the Floodgate,but it seem meet some problems and i can't solve it
help

**Comment by pbs666** [comment] 2020-05-30 15:24
![Screenshot_2020-05-30-23-21-40-840_com termux](https://user-images.githubusercontent.com/60499296/83332248-95765180-a289-11ea-83f2-75f19bb27fa6.jpg)
![Screenshot_2020-05-30-23-16-58-025_com mojang minecraftpe](https://user-images.githubusercontent.com/60499296/83332252-9b6c3280-a289-11ea-938f-4e406e1ea137.jpg)
png

**Comment by DoctorMacc** [comment] 2020-05-30 15:27
Please join us on Discord.

**Comment by pbs666** [comment] 2020-05-30 15:28
but i'm in china,i can't join you

**Comment by pbs666** [comment] 2020-05-30 15:28
so how can i fix it

**Comment by pbs666** [comment] 2020-05-30 15:28
that's too bad

**Comment by Heath123** [comment] 2020-05-30 15:29
> so how can i fix it

Floodgate
https://github.com/GeyserMC/Geyser/wiki/Floodgate

**Comment by Heath123** [comment] 2020-05-30 15:30
> i use the Floodgate,but it seem meet some problems and i can't solve it
> help

Oh
Do you have ProtocolSupport?

**Comment by pbs666** [comment] 2020-05-30 17:15
> > i use the Floodgate,but it seem meet some problems and i can't solve it
> > help
> 
> Oh
> Do you have ProtocolSupport?

yes

**Comment by pbs666** [comment] 2020-05-30 17:15
it because it?

**Comment by DoctorMacc** [comment] 2020-05-30 17:15
Remove ProtocolSupport. Replace it with ViaBackwards/ViaReward if you need it.

**Comment by pbs666** [comment] 2020-05-30 17:16
thanks!

**Comment by pbs666** [comment] 2020-05-30 17:19
need i remove the ProtocolLib?

**Comment by Heath123** [comment] 2020-05-30 17:24
> need i remove the ProtocolLib?

No

**Comment by pbs666** [comment] 2020-05-31 02:31
the players can't send chat....maybe it's because the *....hoe can i fix it?

**Comment by pbs666** [comment] 2020-05-31 02:31
![Screenshot_2020-05-31-10-29-26-151_com termux](https://user-images.githubusercontent.com/60499296/83343217-d6e91a00-a2e6-11ea-8651-e873ff7e5e0f.jpg)
jpg
