### ISSUE TITLE
Shift clicking armor does not work with attributes applied

### ISSUE THREAD

**Issue by InstantlyMoist** [GeyserMC/Geyser#4580] opened 2024-04-17 23:17 UTC
### Describe the bug

I can not shift-click items to/from my armor slot when attributes are applied.
These items are coming from the plugin OldCombatMechanics.
Good to note is that in both videos the plugin is disabled, there is no logic from their plugin being called.

Here are 2 videos showing the difference:

Without attributes applied:
https://github.com/GeyserMC/Geyser/assets/32609460/13523c22-21a7-417a-bb1a-6f84c717898c

With attributes applied:

https://github.com/GeyserMC/Geyser/assets/32609460/c6d037ea-067f-4ba9-bb44-4ea4fe27e8ba

### To Reproduce

1. Get armor with and without attributes, easiest is from OCM.
2. Shift-click to your armor slot, like you would do in Java

### Expected behaviour

It would swap normally to my armor slot.

### Server Version and Plugins

[01:13:54 INFO]: This server is running Paper version git-Paper-e3bf31e5f (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[01:13:54 INFO]: Previous version: git-Paper-"662261c1" (MC: 1.12.2)
[01:13:54 INFO]: Checking version, please wait...
[01:13:54 INFO]: Unknown version

### Geyser Dump

https://dump.geysermc.org/ZrtRsgrrJReatiPo1CFubMJ0BGjcjlbj

### Geyser Version

Geyser versie 2.2.3-SNAPSHOT (git-master-c8475d8)

### Minecraft: Bedrock Edition Device/Version

latest downloaded from the launcher, windows 11

### Additional Context

No errors occur in the console.

**Comment by AJ-Ferguson** [comment] 2024-04-19 09:26
This issue was caused by a bug in ViaVersion and should be fixed in their next build.

**Closed by AJ-Ferguson** 2024-04-19 09:26 UTC
