### ISSUE TITLE
Microsoft login with 2FA

### ISSUE THREAD

**Issue by SansSerif1** [GeyserMC/Geyser#2496] opened 2021-08-25 15:14 UTC
### What feature do you want to see added?

When logging in with Microsoft account using mail and password (while having 2FA enabled on the account), it should continue the login dialog and wait until the user approves the login request in Microsoft authenticator, instead of disconnecting the user for invalid credentials. 

### Are there any alternatives?

You could use the web browser login, but when you are on the go where you don't have another device, you simply can't login.

**Comment by Yuta12342** [comment] 2021-09-27 00:40
The only way I could see this possibly being handled better, is if there was some sort of API that Geyser could internally use, to handle 2FA on its own, if that even exists.

**Comment by Greaper88** [comment] 2021-12-26 19:25
Duplicate of  #2448

**Comment by Chew** [comment] 2021-12-26 20:46
Not quite, different concepts

**Comment by Camotoy** [comment] 2022-12-30 06:18
This issue is no longer relevant; we do not support logging in with username/password for Microsoft. Thank you anyway!

**Closed by Camotoy** 2022-12-30 06:18 UTC
Labels: Feature Request
