### ISSUE TITLE
After modifying the game height, the modified parts of geyser cannot be converted

### ISSUE THREAD

**Issue by yzklpaa** [GeyserMC/Geyser#4998] opened 2024-08-27 08:31 UTC
### Describe the bug

After modifying the height of the original Minecraft game using data packets, it was found that geyser was unable to convert normal blocks located in extremely high areas (y=320 or above) and extremely low areas (y=-64 or below), resulting in players of the Bedrock version being unable to render any content.

### To Reproduce

1. Load any data package that modifies the height of the game. Here is [Infinite Cave.](https://modrinth.com/datapack/infinity-cave)
2. Enter the server (Infinite Cave modified the world's lowest altitude from y=-64 to y=-128) and arrive at the y=-64~-128 area.
4. 3. It can be seen that the bug has already appeared.

### Expected behaviour

Should be square area, showing a blank.

### Screenshots / Videos

![Screenshot_20240827_162644_com mojang minecraftpe](https://github.com/user-attachments/assets/7448481b-1dc5-4f08-940a-1551d9948a1e)
![Screenshot_20240827_162455_com tungsten fcl](https://github.com/user-attachments/assets/c3b78faf-f933-4260-be76-68466f499fe4)
The following is a scene of Java and Bedrock players watching from the same locationLeft  bedrock , right Java 

### Geyser Dump

https://dump.geysermc.org/i0hJAgzlxcbrhW0ZMapiQc8dsVR6nQXJ

### Geyser Version

1.21 2.4.2-b650 (git-master-7da1d7d)

### Minecraft: Bedrock Edition Device/Version

1.21.2

### Additional Context

I think we can modify the geyser conversion height through configuration

**Comment by onebeastchris** [comment] 2024-08-27 08:40
This is a duplicate of https://github.com/GeyserMC/Geyser/issues/3804, and a can't fix - Bedrock's world heights/lows are hardcoded

**Closed by onebeastchris** 2024-08-27 08:40 UTC
Labels: Duplicate

**Comment by yzklpaa** [comment] 2024-08-27 09:12
Is there no good solution?
