### ISSUE TITLE
Imbalance use of shields

### ISSUE THREAD

**Issue by PukPukov** [GeyserMC/Geyser#2531] opened 2021-09-15 21:46 UTC
### Describe the bug

The player from the bedrock has an advantage in pvp over the player from the PC, because you can hit from the bedrock simultaneously with the protection of the shield

### To Reproduce

1. Start PVP from bedrock
2. see

### Expected behaviour

prohibit dealing damage while holding a shield

### Geyser Version

latest

**Comment by Camotoy** [comment] 2021-09-16 20:46
Duplicate of #1453; will be fixed by #2172. Thanks for reporting anyway!

**Closed by Camotoy** 2021-09-16 20:46 UTC
