### ISSUE TITLE
Error: Villager with Lama Invisible

### ISSUE THREAD

**Issue by GayKevin** [GeyserMC/Geyser#2661] opened 2021-12-01 19:04 UTC
### Describe the bug

Hello,

The villager with the lama spawn next to us, but he was invisible, only the lama was visible but we were able to interact with the villager.
After killing the lama the villager was not invisible anymore.
 

### To Reproduce

I think spawning a villager next to you may make the issue again

### Expected behaviour

The villager should be visible 

### Screenshots / Videos

```

[18:40:59] [Geyser player thread-3-2/WARN]: [Geyser-Spigot] Could not translate packet ClientboundMerchantOffersPacket

java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.entity.type.Entity.getDirtyMetadata()" because "villager" is null

	at org.geysermc.geyser.translator.protocol.java.inventory.JavaMerchantOffersTranslator.translate(JavaMerchantOffersTranslator.java:63) ~[?:?]

	at org.geysermc.geyser.translator.protocol.java.inventory.JavaMerchantOffersTranslator.translate(JavaMerchantOffersTranslator.java:50) ~[?:?]

	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[?:?]

	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[?:?]

	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [netty-all-4.1.68.Final.jar:4.1.68.Final]

	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:4.1.68.Final]

	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:4.1.68.Final]

	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.68.Final.jar:4.1.68.Final]

	at java.lang.Thread.run(Thread.java:833) [?:?]

[18:40:59] [Geyser player thread-3-2/WARN]: java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.entity.type.Entity.getDirtyMetadata()" because "villager" is null

[18:40:59] [Geyser player thread-3-2/WARN]: 	at org.geysermc.geyser.translator.protocol.java.inventory.JavaMerchantOffersTranslator.translate(JavaMerchantOffersTranslator.java:63)

[18:40:59] [Geyser player thread-3-2/WARN]: 	at org.geysermc.geyser.translator.protocol.java.inventory.JavaMerchantOffersTranslator.translate(JavaMerchantOffersTranslator.java:50)

[18:40:59] [Geyser player thread-3-2/WARN]: 	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)

[18:40:59] [Geyser player thread-3-2/WARN]: 	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)

[18:40:59] [Geyser player thread-3-2/WARN]: 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)

[18:40:59] [Geyser player thread-3-2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)

[18:40:59] [Geyser player thread-3-2/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

[18:40:59] [Geyser player thread-3-2/WARN]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

[18:40:59] [Geyser player thread-3-2/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Server Version and Plugins

3336-Spigot-a5dea1c-a008701 (MC: 1.18)

### Geyser Dump

https://dump.geysermc.org/798O9fq3LhJXHrDXR1ABeoKh0AG74yM4

### Geyser Version

2.0.0-SNAPSHOT (git-master-295e716)

### Minecraft: Bedrock Edition Version

1.18

**Comment by Konicai** [comment] 2021-12-01 21:56
I wasn't able to reproduce this with spawn eggs: https://dump.geysermc.org/2kBIlcFgoMuhjbUNPIEqK0BoY5LQrqyo

Can you check if the trader was invisible because of an invisibility potion? Also, could you provide steps to reproduce the issue, and a video?

**Comment by GayKevin** [comment] 2021-12-01 21:58
Unfortunately I wasn't able to reproduce the error either.
If it happens again I'm going to send you more information. 

Thank you for your fast answer

**Comment by Konicai** [comment] 2021-12-23 00:02
Without any further reports, we'll close this. Let us know if it occurs again.

**Closed by Konicai** 2021-12-23 00:02 UTC
Labels: Unconfirmed Bug/Not Currently Replicable
