### ISSUE TITLE
Interaction difference  between Bedrock PC and Bedrock PE ( failure on Bedrock PE ) ( success on Bedrock PC )

### ISSUE THREAD

**Issue by Yomamaeatstoes** [GeyserMC/Geyser#3669] opened 2023-04-07 07:44 UTC
### Describe the bug

There seems to be a interaction difference between Bedrock PC and Bedrock PE. Bedrock PE does not register the interactions while Bedrock PC does. The interactions do not register on Bedrock PE while they do register on Bedrock PC

### To Reproduce

Download a NPC plugin
Do an interaction on Bedrock PE
It will not register.

Test on PC

Do an interaction on Bedrock PC
It will register

### Expected behaviour

It should register regardless of if it on is on Minecraft Bedrock PE or PC

### **_Minecraft Bedrock PE Video_** 

https://youtu.be/cKxe3oIHFuA

### **_Minecraft Bedrock PC Video_**

https://youtu.be/JXxtNvxHyj4

### Server Version and Plugins

This server is running Paper version git-Paper-498 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: ad6c14c) 

### Geyser Dump

https://dump.geysermc.org/UkffOfliE55epBqgMyqSBozRtqfnV6pu

### Geyser Version

This server is running Geyser version 2.1.0-SNAPSHOT (git-master-0f99abc) (Java: 1.19.4, Bedrock: 1.19.30/1.19.31 - 1.19.70/1.19.71)

### Minecraft: Bedrock Edition Device/Version

IPHONE, IPAD and PC

### Additional Context

None

**Comment by onebeastchris** [comment] 2024-03-10 22:58
> download a npc plugin
Which one? Last I tested, e.g. citizens works fine - please provide more details here.

**Comment by Yomamaeatstoes** [comment] 2024-03-11 16:28
I would have to retest this out. This was happening 11 months ago. The vidoes I have created have since been deleted of it.

**Comment by Kas-tle** [comment] 2024-03-17 04:13
Closing since this could not be reproduced on citizens which is the most common NPC plugin. If you can reproduce this with another plugin, provide specific reproduction steps and it will be reopened.

**Closed** 2024-03-17 04:13 UTC
Labels: More Info Needed, Unconfirmed Bug/Not Currently Replicable, Waiting On Response
