### ISSUE TITLE
Boats sometimes disappear when placed

### ISSUE THREAD

**Issue by RealBitslayn** [GeyserMC/Geyser#2013] opened 2021-03-08 16:05 UTC
### Describe the bug

Sometimes when you place a boat in an invalid location such as right next to a block or an entity the boat disappears from your inventory and the world.

### To Reproduce

1. Attempt to place a boat next to a block or entity.
2. Boat doesn't place and item disappears.

### Expected behaviour

The boat should either place or stay visible in your inventory.

### Server Version and Plugins

This server is running Paper version git-Paper-441 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Plugins (18): DiscordSRV, dynmap*, DynmapBannerMarkers, Essentials, floodgate-bukkit, Geyser-Spigot, GeyserSkinManager, GeyserUpdater, Graves, LuckPerms, NoBoom, SignShop, SilkSpawners, StatsSB, SuperChairs, TimeIsMoney*, Vault, WorldBorder

### Geyser Dump

https://dump.geysermc.org/sKsZTlSlJZVk7kqhEIIwPuVrWcwNG01t

### Geyser Version

Geyser version 1.2.0-SNAPSHOT (git-server-inventory-814fa95)

### Minecraft: Bedrock Edition Version

1.16.201

**Comment by Camotoy** [comment] 2021-03-08 16:06
This is likely a duplicate of #1247. Thank you anyway for reporting!

**Closed by Camotoy** 2021-03-08 16:06 UTC
