### ISSUE TITLE
Cant connect to server:"Unsupported Bedrock version. Are you rrunning an outdated version?"

### ISSUE THREAD

**Issue by 2Peti** [GeyserMC/Geyser#357] opened 2020-04-16 18:55 UTC
**Describe the bug**
Cant connect to server:"Unsupported Bedrock version. Are you rrunning an outdated version?"

**To Reproduce**
Run start.bat
Open Minecraft on a phone
Click play
Goto friends tab
Click on Geyser

**Expected behavior**
when i want to join the server from my phone it says:Unsupported Bedrock version. Are you rrunning an outdated version?

**Screenshots / Videos**

**Server Version**
This server is running CraftBukkit version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
This is a final build for 1.12.2. Please see https://www.spigotmc.org/ for details about upgrading

**Geyser Version**
#20 inventory

**Minecraft: Bedrock Edition Version**
1.14.60

**Additional Context**

**Comment by RednedEpic** [comment] 2020-04-16 18:56
Duplicate of #352.

**Closed by RednedEpic** 2020-04-16 18:56 UTC
Labels: Duplicate, Invalid
