### ISSUE TITLE
Slime block not bouncy with piston on Bedrock

### ISSUE THREAD

**Issue by pdyq** [GeyserMC/Geyser#4780] opened 2024-06-21 07:42 UTC
### Describe the bug

A piston with a slime block on top should bounce the player upwards. However, when it is on Bedrock (on mobile specifically, unsure about other platforms), it pushes the player away.
It works on both Java and Bedrock in a singleplayer world. However, it does not work when a Bedrock player is connected to the server with GeyserMC.

### To Reproduce

1. Be on Bedrock 
2. Put a piston facing upwards
3. Put a slime block on top of the piston
4. Stand on the slime block
5. Power the piston

### Expected behaviour

The player should bounce on top of the slime block after the piston is powered.

### Screenshots / Videos

On Java: (with shaders)
https://github.com/GeyserMC/Geyser/assets/112796080/5c6b022b-61cf-4410-a53c-6b30e6d7f461

On bedrock: (in Chinese)
https://github.com/GeyserMC/Geyser/assets/112796080/206110ad-233f-4eda-8628-7c941f36c9ab

### Server Version and Plugins

This server is running Geyser version 2.4.0-SNAPSHOT (git-master-63a3da7) (Java: 1.21, Bedrock: 1.20.80/1.20.81 - 1.21.0)
Fabric server 0.15.11, Minecraft 1.21
Plugins:
[VMP](https://modrinth.com/mod/vmp-fabric)
[Styled Nicknames](https://modrinth.com/mod/styled-nicknames)
[Lithium](https://modrinth.com/mod/lithium)
[Krypton (fork)](https://github.com/BenCat07/krypton/tree/master) 
[FerriteCore](https://modrinth.com/mod/ferrite-core)
[Factions](https://modrinth.com/mod/factions)
[Carpet](https://modrinth.com/mod/carpet)
Fabric API
[C2ME](https://modrinth.com/mod/c2me-fabric)
Geyser
Floodgate
[Chunky](https://modrinth.com/plugin/chunky)

### Geyser Dump

https://dump.geysermc.org/sacW8a65s3QnAZeWEf7HxNxOZwlKuNP5

### Geyser Version

2.4.0-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.21.1

**Comment by Camotoy** [comment] 2024-06-21 17:10
Can't reproduce on a Fabric 1.21 server with no mods. Seems like you're on a bit of an outdated build, so do try to update and see if that fixes your issue, otherwise, try without other mods temporarily.

**Comment by onebeastchris** [comment] 2024-07-23 21:14
Able to reproduce on a clean Fabric 1.21 server, marking as confirmed

**Closed** 2024-07-30 08:26 UTC
Labels: Confirmed Bug
