### ISSUE TITLE
Copying banners broken on latest

### ISSUE THREAD

**Issue by spookymgmt** [GeyserMC/Geyser#4423] opened 2024-02-08 01:04 UTC
### Describe the bug

Cannot copy banners no mo 

![image](https://github.com/GeyserMC/Geyser/assets/78775526/19093be5-911a-4a41-bd9a-763f3fe179f4)

### To Reproduce

Just go copy a banner, wont work

### Expected behaviour

Banners should copy

### Server Version and Plugins

Spigot server is on 1.20.1, geyser is well lets see below 

### Geyser Dump

 https://dump.geysermc.org/CbaLJBPAWKns1PjympMJqK9c932X52Ye

### Geyser Version

Run 426 https://github.com/GeyserMC/Geyser/actions/runs/7816162067

### Minecraft: Bedrock Edition Device/Version

Latest bedrock

**Comment by onebeastchris** [comment] 2024-02-08 12:24
![image](https://github.com/GeyserMC/Geyser/assets/105284508/6f6443ec-d202-4c79-8290-a5f7f09d0d7d)
Unable to replicate on Geyser-Standalone and Paper 1.20.4. Can you provide exact replication steps please? For example, is this only an issue with specific batter patterns?

**Comment by onebeastchris** [comment] 2024-05-17 22:53
Closing due to no further response. If the issue persists, please open a new issue with reproduction steps.

**Closed by onebeastchris** 2024-05-17 22:53 UTC
Labels: More Info Needed, Unconfirmed Bug/Not Currently Replicable, Waiting On Response
