### ISSUE TITLE
Pressure Plates broken

### ISSUE THREAD

**Issue by Paul19988** [GeyserMC/Geyser#842] opened 2020-06-28 23:23 UTC
**Describe the bug**
When a player places down pressure plates they are invisible until switching back to that world & Bedrock players cannot interact with pressure plates.

**To Reproduce**
1. Put down a pressure plate in front of a bedrock player using a Java player
2. Plate is invisible

1. Walk onto a pressure plate as a bedrock player

**Expected behavior**
Plate should appear & Plate should compress down & cause an interaction.

**Server Version**
Paper Spigot 354 (1.15.2)

**Geyser Version**
feature/1.16/#46

**Minecraft: Bedrock Edition Version**
v1.16.0

**Comment by endevrr** [comment] 2020-06-29 13:54
Jumping on pressure plates actuates them

**Comment by endevrr** [comment] 2020-06-29 20:16
Duplicate of #865

**Closed by endevrr** 2020-06-29 20:17 UTC
