### ISSUE TITLE
Bedrock Players get stuck on respawn screen while playing PVP minigames

### ISSUE THREAD

**Issue by J-SHarper** [GeyserMC/Geyser#780] opened 2020-06-18 01:14 UTC
**Describe the bug**

Bedrock players who are playing PVP minigames (happens mainly with [PVPArena](https://github.com/Eredrim/pvparena)) do not respawn after dying - instead, they are perpetually stuck on a "Generating World" screen until they log out and log back in, after which they spawn properly at the main lobby spawn, but not within the game (clearly). 

**To Reproduce**

Bedrock players to respawn. Based on a conversation we had on the Discord support channel, my assumption is that the pvp plugin is using a forced respawn to bypass the normal respawn process, and Geyser is not handling that well. 

**Screenshots / Videos**

![2020-06-17](https://user-images.githubusercontent.com/6518001/84966109-a377ff00-b0de-11ea-80cd-dc5002646eee.jpg)

Frozen screen looks like this ^

**Server Version**

PaperMC-347

**Geyser Version**

Geyser-Bukkit Build #225

**Minecraft: Bedrock Edition Version**

Has been tested on latest iPad edition and Minecraft for Windows 10. 

**Additional Context**

Thank you!

**Comment by 77Z** [comment] 2020-06-22 03:27
I think instant respawn might solve this, however I don't know how to set it

**Comment by toinouH** [comment] 2020-06-22 09:05
![image](https://user-images.githubusercontent.com/64892431/85269399-1c2ce180-b478-11ea-9eef-3ab373c33b00.png)
@77Z I found this if you want to modify your mini game.

**Comment by 77Z** [comment] 2020-06-22 18:13
I've already looked into this, it works on the java side but not the bedrock one. I might look into the code to see if there is a way to link this gamerule to MCBE's gamerule. Thanks anyway

**Comment by chenxi050402** [comment] 2020-06-30 10:23
die by elytra can also cause this
but normal fall damage can't cause this

**Comment by chenxi050402** [comment] 2020-06-30 10:26
> die by elytra can also cause this
> but normal fall damage can't cause this

Damage by any entities can cause this

**Comment by chenxi050402** [comment] 2020-07-01 01:05
https://www.spigotmc.org/resources/instant-respawn.2884/
This plugin can fix the problem

**Comment by RednedEpic** [comment] 2020-07-04 17:37
We recently put in some fixes for respawning (on 1.16). Can you confirm if they fix this problem?

**Comment by 77Z** [comment] 2020-07-04 17:48
I was playing on the 1.16 build and noticed a lot of the same issues

**Comment by toinouH** [comment] 2020-07-04 17:51
@77Z On which build ?

**Comment by 77Z** [comment] 2020-07-04 17:56
I'm not sure unless there is a way to check from the Geyser jar file directly. It might have been build 64 based on the date modified. But I'm gonna test with the newer builds too

**Comment by 77Z** [comment] 2020-07-06 00:06
I've done more "testing"(playing mini games with friends) on some of the latest builds and not once did we encounter a bug with respawning. So I think this bug can be closed :)

**Comment by rtm516** [comment] 2020-07-06 00:08
Since we have had no more reports of this, and it has been tested to work I'm going to close it.

**Comment by DoctorMacc** [comment] 2020-07-06 00:09
Let us know if a similar issue pops back up.

**Closed by rtm516** 2020-07-06 00:08 UTC
Labels: More Info Needed, Priority: Medium

**Comment by tienthanh2929** [comment] 2022-10-02 14:30
> Let us know if a similar issue pops back up.

Bug still present in the game

**Comment by EARTHIIAN** [comment] 2022-10-07 08:32
@chenxi050402 
InstantRespawn has alot of problems so I made another plugin fixing mostly all of the problems like not being able to pick up items after death: https://github.com/EARTHIIAN/respawnglitchfix

**Comment by tigersmusic** [comment] 2023-06-28 00:52
> @chenxi050402 InstantRespawn has alot of problems so I made another plugin fixing mostly all of the problems like not being able to pick up items after death: https://github.com/EARTHIIAN/respawnglitchfix

I wasn't sure if I should start a new thread for an old issue, but I've run across this exact same issue. Do you know if your rewrite of that plugin still functions? I've enabled it on my server and it doesn't appear to work as intended. Which is strange because it seems as if it functions outside of minigames, but once PVP Arena is launched the problem persists.

**Comment by tigersmusic** [comment] 2023-06-29 00:42
UPDATE: I reached out on discord to the dev of the PVP Arena plugin for Spigot and they were brief but very helpful! They issued a workaround to the issue with a dev build they released today. I am testing it out now and so far I am not recreating the issue. There are some changes from previous builds, but it's promising as a work in progress. Will let you know if I experience any more issues. 
Alas, this will likely not fix the issue for other plugins, including Duels which I do run, as it seems to be primarily a Geyser issue. But now I know workarounds exist which is a very hopeful sign.

**Comment by Coding-Yasaru-Deneh** [comment] 2024-08-24 12:06
> die by elytra can also cause this but normal fall damage can't cause this

no this happen to me to when i in my flat project world and changing the world spawn point then i go to survival to check is it working i got the some this screen coming sometime when you get fall damage i got two different screen one like this screen and second one have respawn and main menu buttons but cant click it in bedrock

**Comment by 2048hertz** [comment] 2025-01-07 18:29
> > > @chenxi050402 InstantRespawn has alot of problems so I made another plugin fixing mostly all of the problems like not being able to pick up items after death: https://github.com/EARTHIIAN/respawnglitchfix
> > 
> > 
> > I wasn't sure if I should start a new thread for an old issue, but I've run across this exact same issue. Do you know if your rewrite of that plugin still functions? I've enabled it on my server and it doesn't appear to work as intended. Which is strange because it seems as if it functions outside of minigames, but once PVP Arena is launched the problem persists.
> 
> I've tried using this plugin to fix the issue happening on my server too, but it doesn't help me either


I'm not sure why it didn't work for some other people, could be due to other plugins. Maybe checking the configuration files might do the trick. It was nice to hear, @tigersmusic, that you found a workaround. Also, I haven't been updating the plugin mostly because I don't play that much Minecraft anymore so it might be because of that, newer versions can occasionally cause problems; even with plugins that are supposed to work with these versions without updates. Plus I remember testing it with 1.17. Good luck to anyone who is facing this issue.
