### ISSUE TITLE
block placing and breaking issue

### ISSUE THREAD

**Issue by XXdavodXX** [GeyserMC/Geyser#2981] opened 2022-05-20 18:57 UTC
### Describe the bug

When I try to place a row of blocks the action just stops or the blocks just don't want to be placed. Also when I try to break them they often do not break or at least get the animation of breaking. This is only happening on the bedrock side. Because of that issue bedrock, users can't build or explore properly.

### To Reproduce

As shown in the video

### Expected behaviour

block placing and breaking should be smooth as a normal server or solo playing

### Screenshots / Videos

https://www.youtube.com/watch?v=bdScuwbO3k8

### Server Version and Plugins

![plugins list](https://user-images.githubusercontent.com/105943880/169593642-74883b15-676e-4dce-a7cc-05b9cef114e4.PNG)
![server verson](https://user-images.githubusercontent.com/105943880/169593644-bda8dad5-791f-4a8e-b9fc-11f28d53a90d.PNG)

### Geyser Dump

https://dump.geysermc.org/fFz8G5PTXVK5WWgsU3lHoo8IGG7bSvFT

### Geyser Version

Geyser-Spigot v2.0.3-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.18.31 Windows 10

**Comment by hausemaster3734** [comment] 2022-05-29 16:43
Duplicate of #2921

**Comment by onebeastchris** [comment] 2023-06-11 00:12
Unable to replicate - closing. If you still experience this issue, send a geyser dump here & updated reproduction steps

**Closed** 2023-06-11 00:12 UTC
Labels: Confirmed Bug
