### ISSUE TITLE
iOS players are stuck at "Locating Server"

### ISSUE THREAD

**Issue by MyDandan233** [GeyserMC/Geyser#1038] opened 2020-07-28 03:49 UTC
**Describe the bug**
iOS players are stuck at "Locating Server", terminal shows
```
[11:32:49 INFO] /183.160.45.221:8078 tried to connect!
[11:32:50 INFO] Player connected with username Limo23333
[11:34:12 INFO] Bedrock user with ip: /183.160.45.221 has disconnected for reason CLOSED_BY_REMOTE_PEER
```
Geyser's terminal shows the player connected to the server, but Spigot's terminal doesn't show anything.
I tried to join the server on two different iOS device (an iPad and an iPhone) and neither of them are able to join the server.

**Server Version**
[Spigot-1.16.1](https://cdn.getbukkit.org/spigot/spigot-1.16.1.jar)

**Geyser Version**
 Geyser version 1.0.0 (git-master-fe75320), standalone version, no Fooldgate.

**Minecraft: Bedrock Edition Version**
1.16.10

**Additional Context**
https://dump.geysermc.org/y8MRe1sfo6O8scnXpHWpc3U1F9NEK45Y

**Comment by PQguanfang** [comment] 2020-07-28 04:20
I am also a iOS user, but I don't have this problem...

**Comment by rtm516** [comment] 2020-07-28 11:39
Duplicate of https://github.com/GeyserMC/Geyser/issues/957

**Closed by rtm516** 2020-07-28 11:39 UTC
