### ISSUE TITLE
Strider won't move

### ISSUE THREAD

**Issue by Deathkraft** [GeyserMC/Geyser#3167] opened 2022-07-22 20:23 UTC
### Describe the bug

I saddle the strider, I then mount it. Pull out warped fungus on stick. It looks in every direction I look but doesn't move.

### To Reproduce

I saddle the strider, 
I then mount it. 
Pull out warped fungus on stick.
 It looks in every direction I look but doesn't move.

Bedrock 1.19.10

### Expected behaviour

To move. 

### Geyser Version

I'm not sure, I'm not the server owner.

### Minecraft: Bedrock Edition Device/Version

Xbox/1.19.10

**Comment by Konicai** [comment] 2022-07-22 20:42
Duplicate of https://github.com/GeyserMC/Geyser/issues/638

As Camotoy said there:
> I've implemented a server-side workaround that should be fairly stable. https://github.com/Camotoy/GeyserHacks

**Closed by Konicai** 2022-07-22 20:42 UTC
Labels: Duplicate
