### ISSUE TITLE
Add armor dressing in one click or tap

### ISSUE THREAD

**Issue by CAT555502** [GeyserMC/Geyser#2364] opened 2021-07-09 20:27 UTC
### What feature do you want to see added?

Although this is a feature of Minecraft Bedrock, but it has a place to be. 
This makes it uncomfortable for many players.

### Are there any alternatives?

None

**Comment by Camotoy** [comment] 2021-07-09 20:29
Can you send a screenshot or video of what you want?

**Comment by CAT555502** [comment] 2021-07-09 20:32
> Can you send a screenshot or video of what you want?
https://youtu.be/nHunDu8q4Uc

**Comment by Camotoy** [comment] 2021-07-09 20:33
Duplicate of #2364. Thank you anyway!

**Closed by Camotoy** 2021-07-09 20:33 UTC
Labels: Feature Request
