### ISSUE TITLE
Villager trades no work

### ISSUE THREAD

**Issue by DUDEbehindDUDE** [GeyserMC/Geyser#1536] opened 2020-11-14 07:39 UTC
**Describe the bug**
Villager trades allow you to access the npc, and it shows the correct trades, but when you try to get the item that you're buying out, nothing happens. 
**To Reproduce**
1. Open a villager's gui
2. Put in the item(s) you give to it
3. Take the item you're buying out
4. It makes the animation of the item coming out but then it goes back to how it was before

**Expected behavior**
I expect to get the item that I buy from the villager.

**Screenshots / Videos**
I think that a screenshot of video of the problem is not neccecary to understand the issue

**Server Version**
BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:9c078b7:1539 according to console
(Connecting to fabric version 0.6.1.51 (java 1.16.4) but geyser is NOT installed here, only on bungeecord)
**Geyser Version**
1.1.0

**Minecraft: Bedrock Edition Version**

1.16.40
**Additional Context**

https://dump.geysermc.org/YzNvVsVVZM644FXz1jbkUrKmPmdyApx8

**Comment by rtm516** [comment] 2020-11-14 12:39
I have just attempted this, and I'm unable to replicate it. Are you using any villager altering mods or datapacks?

**Comment by DUDEbehindDUDE** [comment] 2020-11-14 19:41
no. should i send a zip of the setup i have?

**Comment by DUDEbehindDUDE** [comment] 2020-11-14 20:00
i had to upload it to mediafire because its 130ish MB
http://www.mediafire.com/file/ojf1n9k88u1jxk5/geyser_test.zip/file

**Comment by DUDEbehindDUDE** [comment] 2020-11-15 00:30
okay i figured out the issue has to do with fabric in some way (probably fabricproxy)

**Comment by DUDEbehindDUDE** [comment] 2020-11-15 01:05
yeah it just doesn't work unless you use spigot/paper/etc on the other end of bungeecord

**Comment by RednedEpic** [comment] 2020-12-12 08:14
Duplicate of #1447.

**Closed by RednedEpic** 2020-12-12 08:14 UTC
Labels: Unconfirmed Bug
