### ISSUE TITLE
Biome problem

### ISSUE THREAD

**Issue by mani1232** [GeyserMC/Geyser#1226] opened 2020-08-30 15:35 UTC
mani123_(Никита)#7953
(http://discord.geysermc.org).-->

The problem with biomes, on Minecraft Java everything is fine, but on minecraft PE it is somehow displayed

**To Reproduce**
-

**Expected behavior**
so that it is the same there and there

**Screenshots / Videos**
![2020-08-30_17 53 57](https://user-images.githubusercontent.com/70480001/91663040-06c6da00-eaef-11ea-965f-a9d55045b10d.png)
![Сн23имок](https://user-images.githubusercontent.com/70480001/91663044-09293400-eaef-11ea-89df-40156b31ee1d.PNG)

**Server Version**
paperMC-162

**Geyser Version**
![Сни3213мок](https://user-images.githubusercontent.com/70480001/91663102-71781580-eaef-11ea-93cd-2f1883db5136.PNG)

**Minecraft: Bedrock Edition Version**
 1.16.20

**Additional Context**
https://dump.geysermc.org/qOeq94qWqAYLi0xQAS3wzUGII8Ir536a

**Comment by xXTeraXx** [comment] 2020-09-01 00:49
I know that you have probably tried this but use world edit to select the 2 corners the area you want to be a jungle, then use the //setbiome command to set the biome exit the server and go back in and see if the problem is fixed

**Comment by Chew** [comment] 2021-04-10 04:42
Hey there! Are you still running into issues with this on the latest build? We'd love to dive deeper, if so.

**Comment by angelXwind** [comment] 2021-04-13 01:47
While I'm not the OP, I can confirm that this issue is still occurring on the latest builds.

Specifically, I am able to reproduce this issue on a server running Geyser 1.2.1 `22c492f`, running on Paper 591.

The Bedrock client versions I have specifically seen this occur on are Windows 10 UWP and iOS — both on 1.16.220.

And just like the OP, Java Edition clients (1.16.5) do not have this biome issue.

Please let me know if any additional information would be helpful to you.

**Comment by Camotoy** [comment] 2021-04-13 01:48
If you're comfortable, are you willing to send a world download?

**Comment by MagnoBooter** [comment] 2021-04-14 19:56
I have a similar problem with a world converted from LevelDB format by the [Amulet Map Editor](https://amulet-editor.com). I posted [an issue](https://github.com/Amulet-Team/Amulet-Map-Editor/issues/257) to them about this, because it might have something to do with chunk data after conversion. This does not occur when I use [Chunker](https://chunker.app) to convert the same world, no stripes there.

**Comment by angelXwind** [comment] 2021-04-15 14:40
> If you're comfortable, are you willing to send a world download?

@Camotoy I've attached a copy of a testing world I just set up that reproduces this issue. If the spawn point is somehow incorrect, just `/tp` to the coordinates `103x, 74y, 658z`.

Basically, all I did to reproduce the bug was use WorldEdit to change the biome of a region of land, which causes the striped biome appearance as depicted above in the OP.

Also placed some signs in the affected area with what the original biome was (`desert_hills`) and what the biome was changed to (`ocean`). (If they appear cut off, you will need to enable Force Unicode Font in Java Edition. Unfortunately, Bedrock Edition _somehow_ still does not have this as an option…)

[GeyserTesting.zip](https://github.com/GeyserMC/Geyser/files/6318738/GeyserTesting.zip)

Versions of all software involved, if it's helpful:
Geyser 1.2.1-22c492f
Paper 1.15.6-592
WorldEdit 7.2.4+5723-e3bfc64
Minecraft Bedrock (iOS) 1.16.220
Minecraft Bedrock (Windows 10 UWP) 1.16.220
Minecraft Java 1.16.5

**Comment by SydeVersus** [comment] 2021-11-24 21:22
![obraz](https://user-images.githubusercontent.com/94997563/143314392-c6d96b97-e07d-4fe1-a9ab-caf3b878b1b7.png)
The problem still exist in the newest build.

**Comment by Camotoy** [comment] 2021-12-01 00:15
Can you please re-test with the latest Geyser build?

**Comment by SydeVersus** [comment] 2021-12-06 00:01
The issue is fixed in the latest build.

**Comment by Camotoy** [comment] 2021-12-06 00:03
Great! I will assume this is no longer an issue because of our new biome handling code.

**Closed by Camotoy** 2021-12-06 00:03 UTC
Labels: Waiting On Response
