### ISSUE TITLE
MOTD, Player Count, & Ping Passthrough Not Working in Proxy Mode

### ISSUE THREAD

**Issue by jongames** [GeyserMC/Geyser#2952] opened 2022-04-24 20:30 UTC
### Describe the bug

I am using the latest Geyser built (# 1090 (Apr 24, 2022, 6:59:02 PM)) for players to connect.  Recently I changed my bungeecord server to **HAproxy mode** due to TCPshield deprecating their old custom connection handling with their extra plugin.  My backend server is waterfall 1.18.2 build # 483.  

So HAproxy backend + Geyser = no passthrough of MOTD, player count, or ping

### To Reproduce

Run Geyser with: 

passthrough-motd: true
passthrough-protocol-name: true
passthrough-player-counts: true
legacy-ping-passthrough: true/false (doesn't matter)
remote:
  use-proxy-protocol: true
  
Open Bedrock Minecraft and check the server MOTD and player count, it will be "Geyser" and 0.

### Expected behaviour

MOTD & player count should be forwarded from the java server to geyser so players can view the correct server information.

### Server Version and Plugins

Geyser built (# 1090 (Apr 24, 2022, 6:59:02 PM))
waterfall 1.18.2 build # 483

connected using HAproxy mode

### Geyser Version

Geyser built (# 1090 (Apr 24, 2022, 6:59:02 PM))

**Comment by RednedEpic** [comment] 2022-04-24 20:37
Duplicate of #2323.

**Closed by RednedEpic** 2022-04-24 20:37 UTC
