### ISSUE TITLE
Bedrock 1.17.10 clients cause some problem

### ISSUE THREAD

**Issue by Xeltica** [GeyserMC/Geyser#2382] opened 2021-07-14 12:07 UTC
### Describe the bug

1. Dropped item entities are rendered wrongly
2. Scaffolds action works wrongly. I can't interact fully on smartphone, and on PC can climb but cannot get off.

## 1

1. Drop any item

## 2

1. Place some scaffolds
2. Climb it
3. Then get off

### Expected behaviour

1. Items dropping animation render correctly
2. Scaffolds work as well as Java and previous version of Bedrock

### Server Version and Plugins

|--|Version|
|--|--|
|Geyser|version 1.4.1-SNAPSHOT (git-master-a170636) (Java: 1.17.1, Bedrock: 1.17.0 - 1.17.10)|
|Java Server|git-Tuinity-17 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 2310a94 on HEAD)|

**Plugins**

AdvancedBan, BlockHat, BonemealPlus, ChestCleaner, Citizens, CMILib, CoreProtect, DiscordSRV, dynmap, EasyDuels, EbiFly*, floodgate, Geyser-Spigot, GSit, Harbor, Jecon, Jobs, LuckPerms, LunaChat*, LWC, MOTD, Multiverse-Core, Multiverse-NetherPortals, NickNames*, OpenInv, PermissionGamemode*, PlaceholderAPI, PlugMan, ProtocolLib, Scoreboard-revision*, ServerRestorer, ServerTap, Shop, SkinsRestorer, Vault, VoidGenerator, VoxelSniper, WorldEdit, WorldGuard, XelticaMCOtanoshimiPlugin

### Geyser Dump

https://dump.geysermc.org/erlYWxEFKGRjIiWAVzuKB0TpCBPkoSMQ

### Geyser Version

1.4.1-SNAPSHOT (git-master-a170636)

### Minecraft: Bedrock Edition Version

1.17.10

### Additional Context

on Bedrock 1.17.2, scaffolds works perfectly

**Comment by Camotoy** [comment] 2021-07-14 12:19
I'm going to keep item visuals within issue #2080 since it's the same problem but worse. Scaffolding is confirmed buggy.

**Comment by Camotoy** [comment] 2021-07-14 13:34
Scaffolding is fixed with ba4e0cf. As items are addressed elsewhere, I'm closing this. Thanks!

**Closed by Camotoy** 2021-07-14 13:34 UTC
Labels: Confirmed Bug
