### ISSUE TITLE
Bedrock "Read timed out" message.

### ISSUE THREAD

**Issue by ProjectHSI** [GeyserMC/Geyser#4250] opened 2023-10-27 09:53 UTC
### Describe the bug

When joining, the MOTD appears in the server list, joins to the backend server (according to backend server logs, client is in "locating server" during this stage.), and the client is then kicked for "Read timed out." with the world never being loaded or seen. Java clients load fine, only Bedrock clients can't connect.

### To Reproduce

- Set up a Velocity server, that has both Floodgate and GeyserMC, with a Paper Backend, not to have Floodgate or GeyserMC.
- Set the Bedrock port to be the same as the Java port.
- Attempt to join the server on a Bedrock client.

*note: based on issue with the server i have set up

### Expected behaviour

The world loads and the client is able to play as normal.

### Server Version and Plugins

Versions are listed as their short git commit hash due to me manually building the projects.

VELOCITY:
Version: SELF-BUILT; (4b795065)
Plugins:
- floodgate-velocity.jar
- Geyser-Velocity.jar
- LuckPerms-Velocity-5.4.104.jar
- ViaBackwards-4.8.1.jar
- ViaForward-4.8.1.jar

PAPER:
Version: SELF-BUILT: (fb06829, I think.)
Plugins:
- FastAsyncWorldEdit-Bukkit-2.8.2-SNAPSHOT-585.jar
- LuckPerms-Bukkit-5.4.104.jar
- [MobArena-1.0-SNAPSHOT.jar](https://github.com/ProjectHSI/MobArena)
- multiverse-core-4.3.12.jar

### Geyser Dump

https://dump.geysermc.org/oaBGUeQDR39sv5UFh03uCHMPphjpdLxj

### Geyser Version

version 2.2.0-SNAPSHOT (git-master-8d2ebcf)

### Minecraft: Bedrock Edition Device/Version

1.20.40

### Additional Context

Both the proxy and the backend server report the player as being connected, before being disconnected when the read timeout occurs. The bedrock client never sees the world (atleast to the end user.)

**Comment by CloudyOrk** [comment] 2023-10-27 09:57
Remove ViaVersion and ViaBackwards from velocity, install them on backend server ( paper server ) and try again.

**Comment by ProjectHSI** [comment] 2023-10-27 21:44
will hopefully be done soon, just updating the servers to the latest avaliable commits (i'm not a contributor, these servers are for plugin-testing)

**Comment by ProjectHSI** [comment] 2023-10-28 05:50
nrgh, sorry i lied (accidently).
i'll test it now.

**Comment by ProjectHSI** [comment] 2023-10-28 05:54
@CloudyOrk (sorry if you're offline, you're the one who replied) i can confirm it works.

**Comment by onebeastchris** [comment] 2023-10-30 07:40
In that case, closing as duplicate of https://github.com/GeyserMC/Geyser/issues/4236

**Closed by onebeastchris** 2023-10-30 07:40 UTC
