### ISSUE TITLE
Scaffolding not working

### ISSUE THREAD

**Issue by RedZephon** [GeyserMC/Geyser#1205] opened 2020-08-25 21:26 UTC
**Describe the bug**
Bedrock users can't climb down Scaffolding but can climb up.

**To Reproduce**

1. Build Scaffold
2. Try to climb down
3. Fail

**Expected behavior**
Should be able to climb down scaffolding

**Screenshots / Videos**

**Server Version**
This server is running Paper version git-Paper-135 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Geyser Version**

 This server is running Geyser version 1.1.0 (git-master-b074336) (Java: 1.16.2, Bedrock: 1.16.20)
 floodgate-bukkit version 1.0-SNAPSHOT

**Minecraft: Bedrock Edition Version**
iPad Pro
Confirmed with users on Win10 and Android

**Additional Context**

**Comment by DoctorMacc** [comment] 2020-08-26 03:32
Thanks for the bug report! However, this is a duplicate of #617.

**Closed by DoctorMacc** 2020-08-26 03:32 UTC
