### ISSUE TITLE
If you wish to use IP forwarding, please enable it in your BungeeCord config as well!

### ISSUE THREAD

**Issue by CTR3X** [GeyserMC/Geyser#4343] opened 2023-12-16 09:07 UTC
### Describe the bug

Well i keep getting this and no idea how to fix this problem, ive tried to reinstall velocity to many times still get the same error
The logs:
"[08:59:05 INFO]: [connected player] SmileySweed (/) has disconnected: Unable to connect to lobby: If you wish to use IP forwarding, please enable it in your BungeeCord config as well!"

Hope i can get some help to solve this problem

### To Reproduce

I put everything correctly i guess and i cant find the problem in what i did wrong.

### Expected behaviour

Was expected it to work xD

### Server Version and Plugins

Velocity 3.3.0-SNAPSHOT (git-21ae82e7-b306)...

### Geyser Version

Velocity 3.3.0-SNAPSHOT (git-21ae82e7-b306)...

### Additional Context

[08:55:42] [Netty epoll Worker #5/INFO] [com.velocitypowered.proxy.connection.MinecraftConnection]: [server connection] SmileySweed -> lobby has disconnected
[08:55:42] [Netty epoll Worker #5/ERROR] [com.velocitypowered.proxy.connection.client.ConnectedPlayer]: [connected player] SmileySweed (

**Comment by onebeastchris** [comment] 2023-12-16 11:22
This error is caused either by BungeeCord/Waterfall not having IP forwarding enabled, or by a Floodgate mismatched key.pem from the proxy to the backend servers.
This could also be caused by *send-floodgate-data:* being enabled without Floodgate being present on all backend servers.
For more information on how to setup Floodgate API on proxies; see our floodgate setup guide:

https://wiki.geysermc.org/floodgate/setup/#installing-floodgate-also-on-spigot-servers-behind-bungeecord-or-velocity

**Comment by onebeastchris** [comment] 2023-12-17 16:30
Closing as this is a configuration issue. Please visit our wiki for help - wiki.geysermc.org. Alternatively, join the GeyserMC discord and ask in the support channel.

**Closed** 2023-12-17 16:30 UTC
