### ISSUE TITLE
Boats rode by a bedrock edition player aren't affected by gravity

### ISSUE THREAD

**Issue by EpicEnder56** [GeyserMC/Geyser#1644] opened 2020-12-09 18:57 UTC
If a bedrock player moves off a tower in a boat the boat doesn't fall.

**Comment by DoctorMacc** [comment] 2020-12-09 18:58
Duplicate of #1585. In the future, please follow the entire issue template. Thank you!

**Comment by 20Enderdude20** [comment] 2020-12-09 18:58
(Wow, that was quick)

**Closed by DoctorMacc** 2020-12-09 18:58 UTC
