### ISSUE TITLE
Fabric Floodgate Mod

### ISSUE THREAD

**Issue by jkramer5103** [GeyserMC/Geyser#3650] opened 2023-03-30 11:53 UTC
### Describe the bug

Hello, i have a Problem, if i click on the Fabric Floodgate Download Button it didn't works,

### To Reproduce

click on the Fabric Floodgate Download Button

### Expected behaviour

in the Screenshot

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/121427510/228827286-655bbebd-58b0-4751-8466-17fa93714599.png)

### Geyser Version

1.19.4 Fabric

**Comment by onebeastchris** [comment] 2023-04-19 22:56
link was updated so it at least points to the Jenkins download page; it'll hopefully be added a bit more seamlessly lateron

**Comment by Camotoy** [comment] 2023-04-19 23:01
I'm closing this issue since the issue is "patched". Thanks!

**Closed by Camotoy** 2023-04-19 23:01 UTC
