### ISSUE TITLE
Phantom Spawners Extremely Buggy

### ISSUE THREAD

**Issue by RealFinePoint** [GeyserMC/Geyser#3326] opened 2022-09-30 17:03 UTC
### Describe the bug

Phantom spawners are completely borked, and create massive visual glitches that lag people's games on Bedrock. Java players don't see it at all.

### To Reproduce

1. Place a phantom spawner on Bedrock using SilkSpawners

### Expected behaviour

A normal phantom spawner that spawns phantoms without looking like an eldritch abomination.

### Screenshots / Videos

https://user-images.githubusercontent.com/105620526/193320856-0adc3364-863a-4249-b37c-c1e21c4b9fad.mp4

### Server Version and Plugins

git-Paper-177

### Geyser Dump

https://dump.geysermc.org/g7fUf44Ag85lpnCohGylqadnGHbmLTHp

### Geyser Version

2.1.0-SNAPSHOT (git-master-c3c2e18)

**Comment by Camotoy** [comment] 2022-10-03 13:30
We know about this but we have no idea what's going on. We have this PR for GeyserOptionalPack that works, but I don't think it's an ideal solution: https://github.com/GeyserMC/GeyserOptionalPack/pull/37

**Comment by DimaSergeew** [comment] 2022-11-10 17:05
> We know about this but we have no idea what's going on. We have this PR for GeyserOptionalPack that works, but I don't think it's an ideal solution: [GeyserMC/GeyserOptionalPack#37](https://github.com/GeyserMC/GeyserOptionalPack/pull/37)

Still haven't been able to solve this problem?

**Comment by onebeastchris** [comment] 2023-06-06 00:19
Closing this issue, since the issue is already tracked here https://github.com/GeyserMC/Geyser/issues/2987 - thanks anyways for reporting it.

**Closed by onebeastchris** 2023-06-06 00:19 UTC
Labels: Duplicate, Confirmed Bug
