### ISSUE TITLE
respawning issues

### ISSUE THREAD

**Issue by LegacyGamerHD** [GeyserMC/Geyser#110] opened 2019-12-14 15:28 UTC
totem of undying is very broken and respawing it self this Is reminder to redned and the others

love you guys in a mainly way XD

**Comment by Nerdtality** [comment] 2019-12-23 02:58
This is related to my ticket
https://github.com/GeyserMC/Geyser/issues/76

**Comment by RednedEpic** [comment] 2019-12-23 02:59
Closing since this is a duplicate of #76 (as mentioned above).

**Closed by RednedEpic** 2019-12-23 02:59 UTC
Labels: Confirmed Bug, Priority: High, Work in Progress
