### ISSUE TITLE
Armor occasionally disappears from inventory and body model (purely visual)

### ISSUE THREAD

**Issue by Tydium** [GeyserMC/Geyser#1901] opened 2021-02-05 15:30 UTC
**Describe the bug**
Sometimes armor will just completely dissapear for other players however they still have the armor on. This is a complete visual bug.

**To Reproduce**
1. Wear armor
2. Hope that you see the bug or glitch (we mainly noticed this after dying. Try turning on keep inventory to see if it works that way also)
**Expected behavior**
For there to be armor on my body and me not looking naked to other players.

**Screenshots / Videos**
None
**Server Version and Plugins**
Using latest version of Geyser Bungeecord (Geyser version 1.2.0-SNAPSHOT (git-master-c26a2ba) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.200/1.16.201))

Paper 1.16.5

**Geyser Dump**
https://dump.geysermc.org/lCTt0NfbGnosvt4hlO2xwwyvAvywh6XL

**Minecraft: Bedrock Edition Version**

Nintendo Switch/Windows10/and on Android (havent tested any other devices) on version 1.16.201

**Additional Context**
Nothing at the moment.

**Comment by Camotoy** [comment] 2021-02-05 15:42
This is a duplicate of #1722. Regardless, thank you for reporting!

**Closed by Camotoy** 2021-02-05 15:42 UTC
