### ISSUE TITLE
Cannot use fireworks to boost elytra flight 

### ISSUE THREAD

**Issue by Micro-Chan** [GeyserMC/Geyser#400] opened 2020-04-22 13:30 UTC
**Describe the bug**
Using fireworks does not boost you forward while elytra flying. 

**To Reproduce**
Get an elytra and equip it, then get some fireworks. Start flying from high and you will notice that using fireworks has no effect whatsoever. 

**Expected behavior**
Fireworks should make you fly faster. 
**Screenshots / Videos**

**Comment by Tim203** [comment] 2020-04-22 13:31
Duplicate of #197

**Closed** 2020-04-22 13:32 UTC
Labels: Duplicate
