### ISSUE TITLE
invisible armorstands name tag will be in the wrong y location

### ISSUE THREAD

**Issue by maxw2000** [GeyserMC/Geyser#640] opened 2020-05-24 15:12 UTC
**Describe the bug**

When making the armorstand invisible the position of the name tag will be in the wrong position

**To Reproduce**
  - Using the plugin Armorstand tools
  - Add a tag to an armorstand
  - make it invisible 

**Expected behavior**
The name tag should be in the same position as before the 

**Screenshots / Videos**

https://youtu.be/bSghYhBx_GI

**Server Version**
![image](https://user-images.githubusercontent.com/22998325/82757480-feb91900-9de0-11ea-9751-3a46a4a20cb9.png)

**Geyser Version**
Master build 188

**Minecraft: Bedrock Edition Version**
1.14.60

**Additional Context**
I've tested this on a build server using the following plugins: 
![image](https://user-images.githubusercontent.com/22998325/82757559-7e46e800-9de1-11ea-85fd-ad44821d9caa.png)

**Comment by RednedEpic** [comment] 2020-05-24 15:13
Duplicate of #346. In the future please make sure an issue isn’t already open for what you’re reporting.

**Comment by RednedEpic** [comment] 2020-05-24 15:14
Also update your Paper version.

**Closed by RednedEpic** 2020-05-24 15:13 UTC
Labels: Duplicate
