### ISSUE TITLE
Goat horn sounds don't work for bedrock players

### ISSUE THREAD

**Issue by JHarris12345** [GeyserMC/Geyser#3806] opened 2023-05-30 11:23 UTC
### Describe the bug

A player cannot hear goat horn sounds if they're inbedrockin bedrock

### To Reproduce

1. Log on with a bedrock account
2. Try and hear a goat horn

### Expected behaviour

Hear goat horn

### Server Version and Plugins
This server is running Pufferfish version git-Pufferfish-11 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: a593bf6 on HEAD)

_No response_

### Geyser Dump
https://dump.geysermc.org/5egyAyCn9VOonKminnBH3BDQve4R3dub

_No response_

### Geyser Version

2.1.0-SNAPSHOT

**Comment by onebeastchris** [comment] 2023-05-30 22:31
Duplicate of https://github.com/GeyserMC/Geyser/issues/3082 - thanks anyways for reporting.

**Closed by onebeastchris** 2023-05-30 22:31 UTC
Labels: Duplicate
