### ISSUE TITLE
[Geyser-BungeeCord]: 无法翻译数据包 ServerWindowItemsPacket

### ISSUE THREAD

**Issue by xiaomoDDJ** [GeyserMC/Geyser#2653] opened 2021-11-28 05:53 UTC
### Describe the bug

java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
        at org.geysermc.connector.inventory.Inventory.getItem(Inventory.java:102) ~[?:?]
        at org.geysermc.connector.network.translators.inventory.updater.ChestInventoryUpdater.updateInventory(ChestInventoryUpdater.java:55) ~[?:?]
        at org.geysermc.connector.network.translators.inventory.translators.chest.ChestInventoryTranslator.updateInventory(ChestInventoryTranslator.java:56) ~[?:?]
        at org.geysermc.connector.network.translators.java.window.JavaWindowItemsTranslator.translate(JavaWindowItemsTranslator.java:55) ~[?:?]
        at org.geysermc.connector.network.translators.java.window.JavaWindowItemsTranslator.translate(JavaWindowItemsTranslator.java:37) ~[?:?]
        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:115) ~[?:?]
        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:96) ~[?:?]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[waterfall-1.17-448.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall-1.17-448.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.17-448.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[waterfall-1.17-448.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[13:40:28 ERROR]: java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
[13:40:28 ERROR]:       at org.geysermc.connector.inventory.Inventory.getItem(Inventory.java:102)
[13:40:28 ERROR]:       at org.geysermc.connector.network.translators.inventory.updater.ChestInventoryUpdater.updateInventory(ChestInventoryUpdater.java:55)
[13:40:28 ERROR]:       at org.geysermc.connector.network.translators.inventory.translators.chest.ChestInventoryTranslator.updateInventory(ChestInventoryTranslator.java:56)
[13:40:28 ERROR]:       at org.geysermc.connector.network.translators.java.window.JavaWindowItemsTranslator.translate(JavaWindowItemsTranslator.java:55)
[13:40:28 ERROR]:       at org.geysermc.connector.network.translators.java.window.JavaWindowItemsTranslator.translate(JavaWindowItemsTranslator.java:37)
[13:40:28 ERROR]:       at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:115)
[13:40:28 ERROR]:       at org.geysermc.connector.network.translators.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:96)
[13:40:28 ERROR]:       at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[13:40:28 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[13:40:28 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[13:40:28 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[13:40:28 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:831)

### To Reproduce

Use TrMenu's Menu

Use SlimeFun GuideBook

[Trmenu](https://github.com/TrMenu/TrMenu) Plugin Github

### Expected behaviour

The menu can be displayed completely 
I can see SlimeFun Skull

### Server Version and Plugins

Waterfall 1.17-R0.1
PaperSpigot 1.16.5 R0.1

### Geyser Version

1.4.3

### Minecraft: Bedrock Edition Version

1.17.41

### Additional Context

Can’t show the complete menu 
I cannot see the skull skin of the SlimeFun plugin

**Comment by Konicai** [comment] 2021-11-28 06:03
Duplicate of https://github.com/GeyserMC/Geyser/issues/2577

**Closed by Konicai** 2021-11-28 06:03 UTC
