### ISSUE TITLE
Bedrock clients kicked for irregular movements / speed by anti-cheat

### ISSUE THREAD

**Issue by GerwinVerkerk** [GeyserMC/Geyser#460] opened 2020-04-30 14:30 UTC
**Describe the bug**
When a player using the bedrock edition of minecraft connects to a Java server that runs an anti-cheat. The bedrock player will be suspected of irregular movements / speed when he is jump sprinting.

**To Reproduce**
1. Connect to a Java server that runs an anti-cheat with a bedrock client (in this case Spartan)
2. Sprint while tapping jump
3. Get kicked by anti-cheat

**Expected behavior**
To not get kicked

**Server Version**
CraftBukkit version git-Spigot-2040c4c-a1a705e (MC: 1.15.2)

**Geyser Version**
Geyser Bungeecord build 99

**Minecraft: Bedrock Edition Version**
v1.14.60

**Additional Context**
I think the problem is caused by bedrock players being able to achieve a slightly higher speed when sprint jumping.

**Comment by danielboos1** [comment] 2020-04-30 23:44
I think the issue is deeper than that to be honest hence the gameplay mechanics are a little different in bedrock. Metrix anti cheat has updated their anti cheat to work perfect with geysermc. Their update was to listen for bedrock users and make the anti cheat Ignore them. I can confirm that it works really good.

**Comment by historylab7** [comment] 2020-08-10 20:53
I get kicked by all the servers that I join, it's very annoying.

**Comment by RednedEpic** [comment] 2020-08-18 02:54
As #204 is more or less where we're currently tracking all movement issues, I'm going to close this issue.

**Closed by RednedEpic** 2020-08-18 02:54 UTC
