### ISSUE TITLE
World border issues

### ISSUE THREAD

**Issue by Comstepr** [GeyserMC/Geyser#1193] opened 2020-08-24 12:43 UTC
**Describe the bug**
Worldborder cannot be seen on Bedrock Edition

I'm omitting some information as I am aware that there is a Worldborder branch on this repo, but it is still a bug.

**Comment by Hellohi3654** [comment] 2020-08-24 12:47
I'm guessing they're working on the world border that's why it's still a separate branch

**Comment by RednedEpic** [comment] 2020-08-24 17:42
Duplicate of #447. Additionally, in the future, please follow the full issue template when reporting bugs.

**Closed** 2020-08-24 22:33 UTC
Labels: Duplicate
