### ISSUE TITLE
bedrock players can use any head in a villager trade

### ISSUE THREAD

**Issue by ckoseyan** [GeyserMC/Geyser#4389] opened 2024-01-13 19:46 UTC
### Describe the bug

![image](https://github.com/GeyserMC/Geyser/assets/105831017/7ab86fe8-91d9-48f4-992c-7185bf89ac1a)
in a trade like this one in a custom villager, on java editon you can only use that spefic player head specified in the trade to do the trade, but on bedrock any player head can be used

### To Reproduce

make a trade using a custom villager trades plugin that has a **custom player head** as the thing you give
go on bedrock editon and you will be able to trade any head to the villager

### Expected behaviour

on bedrock edtion it should only let you use the spefic custom head specifed in the trade

### Screenshots / Videos

this works on java (intended):
![image](https://github.com/GeyserMC/Geyser/assets/105831017/e505839b-b7e4-4988-ae46-cdb4fd19fd2f)

this dosent work on java (intended):
![image](https://github.com/GeyserMC/Geyser/assets/105831017/460653fc-7c05-41e8-bc90-d8900a60f931)

on bedrock:

the intended trade works:
![image](https://github.com/GeyserMC/Geyser/assets/105831017/006a1bfd-9457-4903-a4fb-6d85637c04ce)

however any other head will also work (not intended):
![image](https://github.com/GeyserMC/Geyser/assets/105831017/41b4ef4c-fdb7-49ab-85fc-ed6723e18312)
![image](https://github.com/GeyserMC/Geyser/assets/105831017/4803479c-83ae-4126-828d-292f4bbbe37e)

### Geyser Dump

https://dump.geysermc.org/yveYM7AiHm3o348CqiDmEkilCGAuslkR

### Geyser Version

2.2.0-SNAPSHOT (git master 7613bdb)

### Minecraft: Bedrock Edition Device/Version

v1.20.51

**Comment by Kas-tle** [comment] 2024-03-17 05:27
I cannot reproduce this at all, but rather I find that Geyser in this case does not allow the trade to go through even when the correct skull is used, which would be a duplicate of https://github.com/GeyserMC/Geyser/issues/4092. If you can still reproduce this, please provide the command to spawn such a villager with this issue and I will reopen.

**Closed by Kas-tle** 2024-03-17 05:27 UTC
