### ISSUE TITLE
No sound on block place

### ISSUE THREAD

**Issue by Heath123** [GeyserMC/Geyser#495] opened 2020-05-05 18:35 UTC
**Describe the bug**

When placing a block a sound is not played. On both Bedrock and Java a sound is played when placing.

**To Reproduce**
1) Join via Geyser
2) Place any block

**Expected behavior**
A sound should play

**Screenshots / Videos**
None but it's self-explanatory

**Server Version**
Paper version git-Paper-245 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
This is currently the latest

**Geyser Version**
Geyser-Bukkit PR #490 as this fixes breaking, but it should happen on any version

**Minecraft: Bedrock Edition Version**
1.14.60

**Additional Context**
None

**Comment by rtm516** [comment] 2020-05-05 19:43
Fine in standalone

**Comment by LoudSoftware** [comment] 2020-05-06 00:22
Works in bungee version as well

**Comment by RednedEpic** [comment] 2020-05-06 00:33
Unable to reproduce on the latest version (tested standalone and Bukkit). Please make sure you're on the latest version of Geyser. If this continues to happen, please include a video of it not working and additionally, include in the video that other sounds work too (such as breaking blocks). Will reopen the issue if the following is done and there are still problems.

**Comment by DoctorMacc** [comment] 2020-05-09 16:14
https://streamable.com/y4adca

Paper 261, Geyser 129 Bukkit.

(Also of note: when I was testing my ViaVersion plugin and accidentally switched it to always return an air block, it worked)

**Comment by DoctorMacc** [comment] 2020-05-09 18:23
An additional video, also on Geyser Bukkit, from Discord user Skullfurious#9975: https://dl.dropboxusercontent.com/s/59y3wfabfzgpy1a/2020-05-09_93.mp4

**Comment by RednedEpic** [comment] 2020-05-10 20:26
Fixed in #522.

**Closed by RednedEpic** 2020-05-10 20:26 UTC
Labels: Confirmed Bug, Priority: Low, Work in Progress
