### ISSUE TITLE
PS4 players get rubberbanded on stairs.

### ISSUE THREAD

**Issue by Zoxplers** [GeyserMC/Geyser#1084] opened 2020-08-02 20:42 UTC
**Describe the bug**
Ps4 players have a hard time climbing and descending stairs 

**To Reproduce**
walk up and down stairs

**Expected behavior**
should be smooth

**Server Version**
git-Paper-130 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Geyser Version**
git-master-86f18c9

**Minecraft: Bedrock Edition Version**
PS4 Bedrock 1.16.0

**Comment by DoctorMacc** [comment] 2020-08-02 20:43
Thank you for reporting! However this is a duplicate of #204.

**Closed by DoctorMacc** 2020-08-02 20:43 UTC
