### ISSUE TITLE
[1.16] Daylight Detector cannot be switched to Inverted Daylight Detector.

### ISSUE THREAD

**Issue by HeyDon-Lee** [GeyserMC/Geyser#858] opened 2020-06-29 16:52 UTC
**Describe the bug**
Daylight Detector cannot be switched to Inverted Daylight Detector.
Daylight Detector still shows after being destroyed.

**Server Version**
1.16.1 / Paper-21

**Geyser Version**
1.16

**Minecraft: Bedrock Edition Version**
1.16

**Comment by rtm516** [comment] 2020-06-29 16:54
This works fine, just I presume it doesn't update on the bedrock side. (Mine doesn't display at all)

**Comment by endevrr** [comment] 2020-06-29 17:09
Daylight sensors function correctly, however they do not update visually on the bedrock client until a block is updated close to it, this is not an issue with daylight sensors but an issue with all non full blocks

**Comment by endevrr** [comment] 2020-06-29 20:16
Duplicate of #865

**Closed** 2020-06-29 20:16 UTC
Labels: Confirmed Bug, Priority: Medium
