### ISSUE TITLE
Sign issues

### ISSUE THREAD

**Issue by colicht** [GeyserMC/Geyser#479] opened 2020-05-04 19:44 UTC
**Describe the bug**
 Signs text dissapears when you switch between worlds using multiverse

**To Reproduce**

Create a Sign
/mvtp to different world
/mvtp to return
Signs text should be gone

**Expected behavior**
Sign text should remain in place.

**Screenshots / Videos**

**Server Version**

**Geyser Version**
Downloaded off of Jenkins on the 3rd of May. Geyser.jar 

**Minecraft: Bedrock Edition Version**
 1.14.2

**Additional Context**

![Screenshot (5)](https://user-images.githubusercontent.com/64806518/81006322-f179c180-8e14-11ea-9633-01933b092e2c.png)

**Comment by rtm516** [comment] 2020-05-04 20:19
Most likely a duplicate of https://github.com/GeyserMC/Geyser/issues/335

**Comment by RednedEpic** [comment] 2020-05-05 02:33
> **Describe the bug**
> 
> Signs text dissapears when you switch between worlds using multiverse
> **To Reproduce**
> 
> Create a Sign /mvtp to different world /mvtp to return Signs text should be gone
> **Expected behavior**
> 
> Sign text should remain in place.
> **Screenshots / Videos**
> 
> **Server Version**
> 
> **Geyser Version**
> 
> Downloaded off of Jenkins on the 3rd of May. Geyser.jar
> **Minecraft: Bedrock Edition Version**
> 
> 1.14.2
> **Additional Context**
> 
> ![Screenshot (5)](https://user-images.githubusercontent.com/64806518/81006322-f179c180-8e14-11ea-9633-01933b092e2c.png)

Are the signs in the world you initially join visible?

**Closed** 2020-05-06 21:52 UTC
Labels: More Info Needed

**Comment by colicht** [comment] 2020-05-07 01:54
They are if you create them.
