### ISSUE TITLE
Unable to inflate buffer data

### ISSUE THREAD

**Issue by Sasuke449** [GeyserMC/Geyser#2694] opened 2021-12-11 11:03 UTC
### Describe the bug

Chunks are not loading for bedrock players and they are in a timeout state

### To Reproduce

1. run 1.18 paper server
2. install geyser and floodgate on it

### Expected behaviour

Bedrock players should be able to play without any issue's

### Server Version and Plugins

This server is running Paper version git-Paper-66 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: dce79f3)

### Geyser Dump

https://dump.geysermc.org/RStAnIPdYVISTqefBD2K8pus45dxX8Fk

### Geyser Version

 2.0.0-SNAPSHOT (git-master-1885a75)

### Minecraft: Bedrock Edition Version

1.18.2

### Additional Context

Stacktrace: https://paste.gg/3f0b3d4339584ae1830b7e505bb9ab37

**Comment by Konicai** [comment] 2022-01-06 23:39
Can you reupload the logs if you can still reproduce this issue?

**Comment by uplusion23** [comment] 2022-01-07 06:47
Same issue here.

[Geyser Dump File](https://dump.geysermc.org/S8CCYDP98n07eT8UenUkKLBb4mQUPQhs)

**Comment by uplusion23** [comment] 2022-01-28 20:30
Just a quick update, with no change in configuration or operating system I was able to get Geyser working by switching to new hardware. The previous model was running an intel 11900k, and the current is running on the AMD platform (5950x). I'm unable to list any other changes such as the network adapter since that information isn't available to me, but it does indeed to seem hardware-specific.

**Comment by valenvaio** [comment] 2022-02-07 08:00
Who managed to get the plugin to work?
I have a similar problem on an Intel Core i5-11600.

**Comment by Insidi0usAngel** [comment] 2022-02-09 12:58
Similar problem, I am using CPU: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz   1.50 GHz. I created a spigot server 1.18.1 with only plugins geyser+floodgate.  After set up Bedrock player was able to join and play as expected, however, as soon as another player would join, irresepective of whether the other player was bedrock or Java the first bedrock user would now no longer be able to open chests or interact with the world - any blocks mined would happen but invisible. Trees would not be mined.  Bedrock player a) on logging out and back in again would only see sky, bedrock player b) on logging in and out would also now just get blue sky blocks.  These problems occurred yesterday with version 1.18.1.  Today bedrock device a) updated to minecraft 1.18.2 and can log into the server but cannot access chests or mine blocks, logging in and out there is no blue sky but still cannot open chest or mine blocks and inventory on hotbar was empty on second join (today 0 error messages were generated on the server panel despite these problems). Bedrock player b) still using minecraft **1.18.1** was unable to connect with message: Outdated Geyser proxy! This server supports the following Bedrock versions: 1.17.30, 1.17.40, 1.18.0/1.18.1/1.18.2  Of interest bedrock player a) yesterday could play the server the whole time they were the only person in the world but today on 1.18.2 they can no longer ineract with the world - blue skies bug on second log in no longer happens but they still have no functionality in the world - less than yesterday where they could play if only person on the server.  Attached are the error messages that came up yesterday.  Maybe this is a hardware issue like others have had - maybe my CPU is not supported, maybe there will be a future version of geyser/floodgate that can fix these problems for us.
[geyser problems.txt](https://github.com/GeyserMC/Geyser/files/8032803/geyser.problems.txt)

**Comment by janiiik** [comment] 2022-02-17 11:51
Also experiencing this kind of issues, 1 in 10 attempts to connect end up with this kinf od WARNS:

[12:45:35 WARN]: [io.netty.util.concurrent.AbstractEventExecutor] A task raised an exception. Task: com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener$$Lambda$6136/0x0000000801ea2308@5abffc93
java.lang.RuntimeException: Unable to inflate buffer data
        at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:87) ~[Geyser-Spigot.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:283) ~[Geyser-Spigot.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.lambda$onEncapsulated$0(BedrockRakNetSessionListener.java:39) ~[Geyser-Spigot.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.util.zip.DataFormatException: invalid distance too far back
        at java.util.zip.Inflater.inflateBufferBuffer(Native Method) ~[?:?]
        at java.util.zip.Inflater.inflate(Inflater.java:546) ~[?:?]
        at com.nukkitx.natives.zlib.Java11Inflater.inflate(Java11Inflater.java:21) ~[Geyser-Spigot.jar:?]
        at com.nukkitx.protocol.util.Zlib.inflate(Zlib.java:56) ~[Geyser-Spigot.jar:?]
        at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:61) ~[Geyser-Spigot.jar:?]
        ... 8 more

**Comment by janiiik** [comment] 2022-02-17 12:42
https://user-images.githubusercontent.com/33089907/154483826-6307545d-1011-4669-a0bd-9cba51e0b5c6.mp4

I have made a fresh latest paper with latest geyser-floodgate and was able to get this error after few attempts. video included. hope it helps.

**Comment by Insidi0usAngel** [comment] 2022-02-24 14:57
In reference to my post of 15 days ago, this is 100% a hardware issue, we copied all my server files and folders onto another laptop in the house and bedrock was able to join the server with the same geyser/floodgate setup straight away, without any of the problems of crashing on talking/interacting with chests/commands/loading nothing but sky/empty inventory issues etc. The other laptop has an I5 processor whereas my I7 seems to be incompatible. Unfortunately the older laptop has 3 times less RAM and a less capable CPU etc, which makes it hard to play more than single player without a lot of lag and loss in performance...  Would be very grateful if there can be a fix for the CPU incompatability issues at some point in the future :)

**Comment by Camotoy** [comment] 2022-02-24 15:52
Oops, I must have missed this one in my issue purging; this is likely the same issue as https://github.com/GeyserMC/Geyser/issues/2861, so I will close this for that. Thanks!

**Closed by Camotoy** 2022-02-24 15:52 UTC
Labels: More Info Needed

**Comment by Camotoy** [comment] 2022-04-14 15:24
Please see issue #2861 for a temporary workaround.
