### ISSUE TITLE
Players getting glitched back when walking near a bamboo block

### ISSUE THREAD

**Issue by BeetGaming45** [GeyserMC/Geyser#2349] opened 2021-07-03 04:47 UTC
### Describe the bug

Players are getting teleported back into where they are before when going near a bamboo block

### To Reproduce

1. Walk near a bamboo

### Expected behaviour

Expected on not getting teleported back

### Screenshots / Videos

https://user-images.githubusercontent.com/79033198/124343198-4ae9a600-dbfc-11eb-8ae9-fd042838bf3d.mp4

### Geyser Version

1.4.0-SNAPSHOT (git-master-7ae27c7)

### Minecraft: Bedrock Edition Version

1.17.1/1.17.2

**Comment by Chew** [comment] 2021-07-03 05:24
This is documented as known on our limitations page. In the future, we may have an official way to fix this, but for now, if you want a hacky solution: Camotoy/BambooCollisionFix

Thank you anyway!

Also a duplicate of a few other issues.

**Closed by Chew** 2021-07-03 05:24 UTC
