### ISSUE TITLE
Rain problem still persist (with video proof)

### ISSUE THREAD

**Issue by vitorgueler22** [GeyserMC/Geyser#3923] opened 2023-06-28 16:59 UTC
### Describe the bug

Hey, so, I know there's been some actions to try to fix this issue, but so far it seems to not be solved. It still starts raining out of nowhere on Bedrock with clear weather on Java. The command to clear weather does not seem to get rid of the rain, as seen on the clip (even though the clouds seems to be clear, the particles and sound still going).

### To Reproduce

1. Starts raining out of nowhere on Bedrock, clear weather on Java;
2. Execute clear weather command;
3. Clouds clear out (change to a lighter color);
4. Rain particles and sound still going;

### Expected behaviour

Weather in sync with Java edition, there's severe sync issues there.

### Screenshots / Videos

https://clips.twitch.tv/HardAmusedLarkTebowing-yKJ-tsclCK8ivIA5

### Server Version and Plugins

This server is running CraftBukkit version 3814-Spigot-64b565e-c1279f7 (MC: 1.20.1)

Plugins: GeyserMC, Floodgate, Gsit, SkinsRestorer, LoginSecurity, CommandTimer, ViaVersion. 

### Geyser Dump

https://dump.geysermc.org/wRc6f5QOaWhf3RwXuT7jdagkWUfyBWOM

### Geyser Version

2.1.1-SNAPSHOT (git-master-c7304f0)

### Minecraft: Bedrock Edition Device/Version

Xbox edition

**Comment by Konicai** [comment] 2023-06-28 17:29
Duplicate of #3679

**Closed by Konicai** 2023-06-28 17:29 UTC
