### ISSUE TITLE
Trying to craft bundles gives shulker shell

### ISSUE THREAD

**Issue by TutorialMan7727** [GeyserMC/Geyser#5226] opened 2024-12-13 23:23 UTC
### Describe the bug

When tring to craft a bundle it gives a shulker shell

### To Reproduce

Try craft a bundle

### Expected behaviour

For a bunfle to be crafted

### Screenshots / Videos

https://cdn.discordapp.com/attachments/1163469797456101396/1317264005282398228/image.png?ex=675e0d34&is=675cbbb4&hm=098abf176696e01a0e19b029948bdf67ca0e52d1e8255765947781f6b41671c5&

### Server Version and Plugins

This server is running Paper version 1.21.4-14-master@b746d9d (2024-12-11T21:22:39Z) (Imp lementing API version 1.21.4-R0.1-SNAPSHOT)

### Geyser Version

This server is running Geyser versio n 2.6.0-b730 (git-master-ba5b422) (Java: 1.21.4, Bedr ock: 1.21.40 1.21.44 1.21.50 1.21.51)

**Comment by Camotoy** [comment] 2024-12-13 23:27
Duplicate of #5146 - thanks anyway for reporting!

**Closed by Camotoy** 2024-12-13 23:27 UTC

**Comment by TutorialMan7727** [comment] 2024-12-13 23:28
Sorry I didnt see that
