### ISSUE TITLE
players getting kicked  

### ISSUE THREAD

**Issue by shawn695** [GeyserMC/Geyser#3976] opened 2023-07-13 14:13 UTC
### Describe the bug

we play for a bit and all the sudden a groupe of players will get kicked from the server 

### To Reproduce

dont know how to reproduce

### Expected behaviour

players get kicked with this error 

13.07 13:40:04 [Server] WARNING [Geyser-BungeeCord] Haven't received PlayerListEntry packet before spawning player! We ignore the player e8152b61-4b8d-217b-a5c5-de6c560e208a
13.07 13:40:26 [Server] INFO [Blazzin7868] disconnected with: DecoderException : java.lang.IndexOutOfBoundsException: readerIndex(1160) + length(1) exceeds writerIndex(1160): PooledUnsafeDirectByteBuf(ridx: 1160, widx: 1160, cap: 8192) @ io.netty.handler.codec.MessageToMessageDecoder:98
13.07 13:40:26 [Server] INFO [Blazzin7868] -> UpstreamBridge has disconnected

### Server Version and Plugins

running on bungee

### Geyser Dump

 https://dump.geysermc.org/XMXFpXd6zhruy3TeRblKvuJiFmRspWGt

### Geyser Version

build 237

### Additional Context

[proxy.log.zip](https://github.com/GeyserMC/Geyser/files/12040312/proxy.log.zip)

**Comment by thiagogebrimm** [comment] 2023-07-13 16:57
same

**Comment by bridgelol** [comment] 2023-07-13 16:58
experiencing the same issue

**Comment by PedroMPagani** [comment] 2023-07-15 12:21
Is this only in bungeecord or some of you use standalone?

**Comment by shawn695** [comment] 2023-07-15 12:28
bungee, its been happening a few times a day i have to keep restarting my proxy for a temp fix

**Comment by ReclinesMC** [comment] 2023-07-16 09:02
Also experiencing this with Velocity. Likely a memory leak.

**Comment by PedroMPagani** [comment] 2023-07-16 09:41
This is not a memory leak. This is an exception due to a trial of reading not existing data on the packets.

**Comment by PedroMPagani** [comment] 2023-07-16 10:16
> > Is this only in bungeecord or some of you use standalone?
> 
> Both standalone and proxy plugin leads to the same problem. I'm running on Velocity. Problem still persists.
> 
> Disable the forward ping doesn't make it occur less. It's just pure random. Sometimes it kicks player every hour, sometime over a day doesn't occur, sometime 10 hours.

What is the version of your velocity, and the version of your backend server?

**Comment by ReclinesMC** [comment] 2023-07-16 16:12
> This is not a memory leak. This is an exception due to a trial of reading not existing data on the packets.

But when this happens to me, Velocity’s ram maxes out and stays that way until I restart.

**Comment by shawn695** [comment] 2023-07-17 01:47
https://mclo.gs/WihuWw4 
new day same problem, it seems to happen randomly when a bedrock player joins. it will kick other bedrock players and or the whole server.

**Comment by shawn695** [comment] 2023-07-17 01:56
any devs, ill try anything and or test anything on my servers if it means making progress on a fix for this

**Comment by Elkidogz** [comment] 2023-08-10 17:16
same issue repeating on my server. over and over again, eventually crashing it  1.20.1 Latest geyeser (build 525) Floodgate ( 59)

**Comment by bakerxd0** [comment] 2023-10-30 05:42
same problem here Im using bungecord

**Comment by onebeastchris** [comment] 2023-10-31 08:29
This sounds like a possible duplicate of https://github.com/GeyserMC/Floodgate/issues/420, could you try updating floodgate on all servers and re-test? (Both proxy + all backends).

**Comment by onebeastchris** [comment] 2023-10-31 08:30
@Elkidogz your issue is unrelated to this one; you likely have some NPC plugin that isn't sending correct a PlayerListEntry for a fake player. The Java client logs should also complain about that

**Comment by onebeastchris** [comment] 2024-02-02 15:27
Closing due to no further response.

**Closed by onebeastchris** 2024-02-02 15:27 UTC
Labels: Unconfirmed Bug/Not Currently Replicable
