### ISSUE TITLE
Smithing table does not work

### ISSUE THREAD

**Issue by ipad54** [GeyserMC/Geyser#1077] opened 2020-08-02 04:25 UTC
**Describe the bug**
Smithing table does not work

**To Reproduce**

1) Place smithing table 
2) Click on SmithingTable
3) upgrade you item
4) Item backs to its original form

**Server Version**

This server is running Paper version git-Paper-111 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
**Geyser Version**
This server is running Geyser version 1.0.0 (git-master-86f18c9)

**Minecraft: Bedrock Edition Version**
1.16.0

**Comment by DoctorMacc** [comment] 2020-08-02 14:33
This will be fixed in the inventory rewrite.

**Comment by HyperSkys** [comment] 2020-10-13 16:35
The issue is that bedrock and java have 2 different base's of the smithing table or it just doesn't link in the plugin (I THINK)

**Comment by DoctorMacc** [comment] 2020-10-13 16:42
No; the issue has to do with how we handle inventories, basically.

**Comment by HyperSkys** [comment] 2020-10-15 21:36
Thats what I mean lol
2 different base's bedrock and java have 2 different inventory systems lol

**Closed** 2021-03-14 01:57 UTC
Labels: Confirmed Bug, Work in Progress
