### ISSUE TITLE
Geyser sends vanished players on the player list

### ISSUE THREAD

**Issue by NFLD99** [GeyserMC/Geyser#2340] opened 2021-06-30 04:07 UTC
### Describe the bug

so after contacting the [PV](https://www.spigotmc.org/resources/premiumvanish-stay-hidden-bungee-support.14404/) dev i got this information, its seems to be a geyser issue, they had this to say: 

> Hey, do you have some sort of geyser or floodgate plugin installed on your spigot server or on bungeecord/velocity? Or are you connecting through GeyserStandalone without any Geyser/Floodgate plugin installed on your server/bungee?
> I've just looked into their code and at a glance it looks like Geyser's bungee plugin [sends the entire player list](https://github.com/GeyserMC/Geyser/blob/master/bootstrap/bungeecord/src/main/java/org/geysermc/platform/bungeecord/GeyserBungeePingPassthrough.java#L67) (including vanished players) to bedrock players who connect through geyser. If that's actually what's happening then support would have to be added from their side by using PV's BungeeVanishAPI.

### To Reproduce

1: install Geyser + floodgate
2: install [PV](https://www.spigotmc.org/resources/premiumvanish-stay-hidden-bungee-support.14404/)
3. have a player vanish
4. connect from bedrock
5. pause the bedrock client
6. note the bedrock user can still see the vanished player

### Expected behaviour

bedrock users should not see vanished players on their pause menu nor should be showing vanished players in the player count of the server in the servers menu

### Screenshots / Videos

Ingame: https://uploads.nfld99.com/XdwhBVe9vu.png

servers menu: *Java left | Bedrock Right* https://i.imgur.com/9u0TyJM.png

### Server Version and Plugins
server version:
This server is running Paper version git-Paper-590 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

main plugins[we have more than this these are the main ones that should matter]: 
floodgate, Geyser-Spigot, PremiumVanish, ProtocolLib, ViaVersion

### Geyser Dump

https://dump.geysermc.org/sUsULLifsyGOpspI2HZYQTrGmjREP6no

### Geyser Version

This server is running Geyser version 1.4.0-SNAPSHOT (git-master-71fe262) (Java: 1.17, Bedrock: 1.17.0)

### Minecraft: Bedrock Edition Version

1.17

### Additional Context

if there is any other information i can provide please let me know

**Comment by Camotoy** [comment] 2021-07-01 20:02
`If that's actually what's happening then support would have to be added from their side by using PV's BungeeVanishAPI.`

I can confirm that's definitely *not* what we need to do - we don't touch anything with Bungee's API; what we display is what we get sent as a Minecraft packet.

**Comment by Camotoy** [comment] 2021-07-01 20:03
Regardless, this looks like a duplicate of #2209, so I am closing in favor of that issue. Please redirect any updates there; thanks!

**Closed by Camotoy** 2021-07-01 20:03 UTC

**Comment by Camotoy** [comment] 2021-07-02 02:58
I just noticed the second screenshot; that can be fixed by using `legacy-ping-passthrough` which manually pings the server instead of relying on internal methods.
