### ISSUE TITLE
The bedrock players are lagging

### ISSUE THREAD

**Issue by Bart0o** [GeyserMC/Geyser#2281] opened 2021-06-11 14:49 UTC
### Describe the bug

I have a lag problem: I updated floodgate (to floodgate 2) and geyser on bungeecord, waterfall exactly. After a few minutes that the bedrock one enters, only he starts pinging 2000-3000ms. I have removed all plugins and nothing has changed. With the version before 1.17 and with floodgate 1 it did not give problems.

### To Reproduce

1) Install floodgate 2 and geyser on the latest version of waterfall
2) Have bedrock join the server.
3) After a few minutes the player starts lagging: it goes from 5-30ms to 2000-5000ms

### Expected behaviour

They just shouldn't start lagging that much .-.

### Geyser Dump

https://dump.geysermc.org/HARDRmN7sqvpBzaSNhq3iD3EcXdaDChu

### Geyser Version

1.4.0-SNAPSHOT (git-master-cc2d26d)

### Minecraft: Bedrock Edition Version

Bedrock: 1.17.0

**Comment by Camotoy** [comment] 2021-06-11 14:51
This issue is likely a duplicate of https://github.com/GeyserMC/Floodgate/issues/154, so I am closing. Regardless, thank you!

**Closed by Camotoy** 2021-06-11 14:51 UTC
