### ISSUE TITLE
Nintendo Switch complains about command text when loading

### ISSUE THREAD

**Issue by LimeDev8756** [GeyserMC/Geyser#3169] opened 2022-07-24 12:25 UTC
### Describe the bug

About 25 errors appear complaining about command text

### To Reproduce

1. Join any server on switch
2. See an error

### Expected behaviour

No errors

### Screenshots / Videos

https://user-images.githubusercontent.com/100384210/180646776-bc9b947a-58cf-4923-b323-04d3a592af13.mp4

### Server Version and Plugins

![image](https://user-images.githubusercontent.com/100384210/180646873-b69b0aba-dd89-4678-b28d-a171561c1115.png)

### Geyser Version

2.0.5-SNAPSHOT (git-master-3de2b33)

### Minecraft: Bedrock Edition Device/Version

1.19.10, Nintendo Switch

### Additional Context

This only happens when joining Geyser servers

**Comment by Camotoy** [comment] 2022-07-24 14:20
Duplicate of #2385. Thanks anyway!

**Closed by Camotoy** 2022-07-24 14:20 UTC
