### ISSUE TITLE
Bedrock Players with Empty Shulker boxes in their Inventory are kicked after connecting

### ISSUE THREAD

**Issue by endevrr** [GeyserMC/Geyser#818] opened 2020-06-27 21:56 UTC
**Describe the bug**
Any Bedrock players with Empty shulker boxes in their inventory will be kicked upon joining a Geyser server, their inventory will not load and a malformed packet (InventoryContentPacket ID:49) is reported in debug mode.

EDIT: This appears only to happen with shulker boxes that were in a players inventory before updating to 1.16, new empty shulker boxes function correctly

**To Reproduce**
Run a Geyser Server connect from a bedrock client that has an empty shulker box in their inventory.

See that you have been disconnected from the server.

**Expected behavior**
Bedrock Players are not kicked

**Packet Violation Message**
https://hasteb.in/opadeput.cs

**Server Version**
PaperMC build 10

**Geyser Version**
Latest Floodgate, Geyser 1.16.1 Build 45

**Minecraft: Bedrock Edition Version**
1.16.0

**Additional Context**
N/A

**Comment by Tim203** [comment] 2020-06-27 21:59
There should be an error saying something like platform type spigot not found

**Comment by endevrr** [comment] 2020-06-27 22:03
I don't see it, and my other xbox friend is able to join, only 1 of the 2 tested is affected.

**Comment by Tim203** [comment] 2020-06-27 22:04
Weird, it is atleast too late for me.
So someone else has to look into it or otherwise me tomorrow.

**Comment by joshudson** [comment] 2020-06-27 22:18
Considering the screenshot shows 1.16; it's probably a dupe of #807

**Comment by endevrr** [comment] 2020-06-27 22:24
It's most definitely not a dupe of #807 I'm a Geyser dev, we've added early support for 1.16

**Comment by kaydot789** [comment] 2020-06-28 13:48
> It's most definitely not a dupe of #807 I'm a Geyser dev, we've added early support for 1.16

Is this available in the latest download or do you need to compile the source code to be able to connect with bedrock 1.16? I tried compiling the source code last night according to the directions and it failed every time

**Comment by endevrr** [comment] 2020-06-28 14:01
@kaydot789 Builds are available on the [CI Server](https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/feature%252F1.16/)

**Comment by endevrr** [comment] 2020-06-28 18:27
Updated issue to include my new findings

**Comment by AJ-Ferguson** [comment] 2020-06-29 19:23
Fixed by e77f2b5dbbbcbedcff3c96e416acaa07c000a5ca

**Closed by AJ-Ferguson** 2020-06-29 19:23 UTC
