### ISSUE TITLE
Filled Composter dont render

### ISSUE THREAD

**Issue by AdyaGD** [GeyserMC/Geyser#846] opened 2020-06-29 09:46 UTC
**Describe the bug**
When you fill a composter you can't see if its filled or not, you can get the bonemeal tho

**To Reproduce**
1. place the composter
2. get seeds or something to compost with
3. rightclick with the item on the composter
4. the composter is still empty

**Expected behavior**
The composter should have something in it

**Server Version**
This server is running CraftBukkit version git-Spigot-758abbe-2b00831 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Geyser Version**
Build #46 Spigot

**Minecraft: Bedrock Edition Version**
Pocket Edition

**Comment by endevrr** [comment] 2020-06-29 20:23
Duplicate of #865

**Closed** 2020-06-29 20:23 UTC
