### ISSUE TITLE
Geyser Users stuck on "Locating server"

### ISSUE THREAD

**Issue by AceSurvival** [GeyserMC/Geyser#4437] opened 2024-02-11 08:31 UTC
### Describe the bug

Geyser users on all platforms are stuck on "Locating server" On latest version.

### To Reproduce

Logging in. play.acemc.co to see what im referring to. Bedrock can no longer connect

### Expected behaviour

To fully log in....

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/118034295/fc35b9c7-50d3-4752-b67e-718df1c1d985)

### Server Version and Plugins

![image](https://github.com/GeyserMC/Geyser/assets/118034295/9e50d522-56a4-4eae-b614-f3fadde8a026)
Velocity Build 357.

### Geyser Dump

https://dump.geysermc.org/gXfyL0d4FZvWceNDjXmKy1ONuqOxNVue

### Geyser Version

429

### Additional Context

https://dump.geysermc.org/CCgA10KqhEr5xZTrjMw1LWtjpBLQjWad

All bedrock players were able to log in before the latest update.

**Comment by LUIS9799** [comment] 2024-02-11 17:31
Same!

**Comment by onebeastchris** [comment] 2024-02-11 17:35
Please turn on `debug-mode` in Geyser's config, and send a full log via mclo.gs. 
Additionally:
- please try using paper instead of a paid spigot fork 
- try shortening your motd's - there've been issues in the past where it being too long was able to cause issues.

@LUIS9799 bumping issues without contributing more information isnt of much help - at the very least, provide a geyser dump/logs to show what kind of setup you have.

**Comment by AceSurvival** [comment] 2024-02-11 18:59
https://mclo.gs/mPGhJCR

here is the log with debugging on.

**Comment by onebeastchris** [comment] 2024-02-11 19:06
The geyser dump you sent before indicates that you have Geyser installed on the backend servers. Remove Geyser from those servers, and only keep it on the proxies - as mentioned in the Geyser setup guide.
Further, do you see anything in the server log when you're trying to connect with a client that's then stuck on "locating server"?Your log showed a geyser player connecting to the server.. but no other connection attempts

**Comment by AceSurvival** [comment] 2024-02-11 19:09
Will remove right now. Do I keep or remove floodgate from backend servers as well?

"Your log showed a geyser player connecting to the server.. but no other connection attempts"
Thats all it does. they physically log in, but they dont get past the locating server screen. Eventually they log out as it never loads.

**Comment by onebeastchris** [comment] 2024-02-11 19:11
Having floodgate installed on all backend servers is fine, even recommended.
I've just tried joining myself for testing; it looks like the client downloads resource packs fine but isn't able to join afterwards. Could you check if a client can join without the resource packs?

**Comment by AceSurvival** [comment] 2024-02-11 19:14
Thank you. It's weird, it was all working prior to the 1.20.60 update.

Anyway, about to reboot. Changed resource pack forcing for geyser to false, and also removed geyser from backend servers.

**Comment by AceSurvival** [comment] 2024-02-11 19:24
Joining works without the resource pack.
Does something need to be updated? As I didn't have this issue prior to the latest 429 update.

**Comment by onebeastchris** [comment] 2024-02-11 19:28
1.20.60 did change some things for resource packs, such as e.g. removing some item components.
I'd recommend removing parts of the resource pack, and then see when it starts working - maybe using a binary search.

**Comment by FantasyGirl1988** [comment] 2024-02-11 20:34
On my Server is the same i use Bungeecord and the version 1.19.2 with via version ![Screenshot_2024-02-11-21-33-41-080_com.server.auditor.ssh.client-edit.jpg](https://github.com/GeyserMC/Geyser/assets/98742772/a3881ff0-2d66-44ef-b8ad-9c1fc805b0ea)

So i hope you can help me

**Comment by onebeastchris** [comment] 2024-02-11 20:35
@FantasyGirl1988 you're getting a `Connection Closed` error - and judging by the `Downstream packet error`, you need to update BungeeCord and potentially ViaVersion

**Comment by FantasyGirl1988** [comment] 2024-02-11 20:36
> @FantasyGirl1988 you're getting a `Connection Closed` error - and judging by the `Downstream packet error`, you need to update BungeeCord and potentially ViaVersion. It however is unrelated to the issue described here.

But can i use my 1.19.2 server then?

**Comment by onebeastchris** [comment] 2024-02-11 20:39
Even if your server isn't on 1.20.4, you still need to use the latest version of BungeeCord. Additionally, you'll need to update/install Viaversion so 1.20.4 clients - which is what Geyser currently imitates - can join.

**Comment by victorXN** [comment] 2024-02-25 09:36
On my Server is the same,too.i use purpur 1.20.4
log with debugging:https://mclo.gs/1CvFLjM

**Comment by onebeastchris** [comment] 2024-03-02 17:26
Closing as the issue appears to be resolved - this seems to have been caused by a resource pack, not Geyser itself.

**Closed by onebeastchris** 2024-03-02 17:26 UTC
Labels: Unconfirmed Bug/Not Currently Replicable, Client Bug
