### ISSUE TITLE
Stone Cutters Work Wrong

### ISSUE THREAD

**Issue by S-SHI777** [GeyserMC/Geyser#5171] opened 2024-11-29 09:56 UTC
### Describe the bug

To use the stone cutter will craft the wrong item.

### To Reproduce

1. Click stone cutter
2. Choose the craft item
3. Take the item
4. I got wrong item

### Expected behaviour

I hope the stone cutter will craft the same correct items as in the preview.

### Screenshots / Videos

https://youtu.be/b7b9-rAaGjA?si=-DI6lHoi0iFCH6Sb

### Server Version and Plugins

I follow the dump section.
https://dump.geysermc.org/qfTNSV1X8xE5VNAcytsSwAsY0c2i7dIo

### Geyser Dump

https://dump.geysermc.org/qfTNSV1X8xE5VNAcytsSwAsY0c2i7dIo

### Geyser Version

I follow the dump section.

### Minecraft: Bedrock Edition Device/Version

Android 1.21.44

### Additional Context

The server is hosted on playit.gg

A friend of mine says that the same bug occurs on Nintendo Switch and PS4.

I am not an English speaker and I use some translation software. I apologise if there are any unnatural phrases
:(

**Comment by GGTEC** [comment] 2024-11-29 14:20
Same here

**Comment by Camotoy** [comment] 2024-11-29 18:47
Closing as duplicate of #5150. Thank you anyway for reporting!

**Closed** 2024-11-29 18:47 UTC
