### ISSUE TITLE
Bedrock players cannot read books on lecterns.

### ISSUE THREAD

**Issue by jfhorton** [GeyserMC/Geyser#3497] opened 2023-01-08 22:33 UTC
### Describe the bug

Bedrock players are unable to read books placed on lecterns. This seems to affect both books and quills as well as written books. Books in players inventory are not affected.

### To Reproduce

1. Place a lectern
2. Place a book (book and quill or written book) on the lectern.
3. Right clicking on the book does nothing.

### Expected behaviour

Book GUI should open.

### Server Version and Plugins

/version output:
```
This server is running Paper version git-Paper-358 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: f26e9cc)
You are 13 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-307 (MC: 1.19.2)
```

/plugins output:
```
Plugins (16): BungeeGuard, Chunky, ChunkyBorder, Citizens, CoreProtect, DecentHolograms, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncVoxelSniper, FastAsyncWorldEdit (WorldEdit), FreedomChat, LuckPerms, PlaceholderAPI, TAB-Bridge, Vault
```

### Geyser Dump

https://dump.geysermc.org/VTtoVZCgUppRui3L9hZjJGOUIsJMCFIY

### Geyser Version

version 2.1.0-SNAPSHOT (git-master-6485200) (Java: 1.19.3, Bedrock: 1.19.20 - 1.19.50/1.19.51)

### Minecraft: Bedrock Edition Device/Version

1.19.51 Windows Store

**Comment by snowie2000** [comment] 2023-01-11 03:01
Duplicate of #3138 and nobody is fixing it...

**Comment by Camotoy** [comment] 2023-01-11 03:25
I've looked into it and I have no idea how to fix it. Since this is a duplicate, I'm closing.

**Closed by Camotoy** 2023-01-11 03:25 UTC
