### ISSUE TITLE
The messages can't be displayed (showed as "chat.type.text")

### ISSUE THREAD

**Issue by fengye1003** [GeyserMC/Geyser#3140] opened 2022-07-15 01:19 UTC
### Describe the bug

When I sent a message or received messages , the message text can't be displayed.
There is only "chat.type.text" in the message area.
The messages can be displayed normally in Java version.

[Chinese version]
当我向聊天区域发送消息时,消息的文本不能正常显示.只有"chat.type.text"的类型被显示.
Java版MC可正常显示消息文本

### To Reproduce

1.Install and run Paper Minecraft Server git-Paper-61 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: cd215af)
2.Run Geyser 2.0.5-SNAPSHOT
3.Connect to server and login.(By Bedrock MC v.1.19.10)
4.Send or receive a message , the text can't be displayed.

### Expected behaviour

The message be displayed normally.
*The messages can be displayed normally in Java version.

### Screenshots / Videos

![IMG_3320](https://user-images.githubusercontent.com/57851633/179127022-7bb69247-d8b1-4d02-b0f8-d0d6590e4dbe.PNG)

The video can be downloaded at :
https://pan.huang1111.cn/api/v3/file/source/1578888/RPReplay_Final1657847233.MP4?sign=RKl7P4oDWN3MPdUfms21Sw5AMIuXbTVSM_I-deAmAZE%3D%3A0

### Server Version and Plugins

git-Paper-61 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: cd215af)

Can be downloaded at:
https://api.papermc.io/v2/projects/paper/versions/1.19/builds/61/downloads/paper-1.19-61.jar

### Geyser Dump

https://dump.geysermc.org/0ehUa3GXWa3bdBzFHj6mx2vnuiYZlVGw

### Geyser Version

2.0.5-SNAPSHOT (git-master-f6f886)

### Minecraft: Bedrock Edition Device/Version

1.19.10 iPad OS

### Additional Context

The messages can be displayed normally in Java version.
There is also another bug at https://github.com/GeyserMC/Geyser/issues/3139

**Comment by Chew** [comment] 2022-07-15 01:28
Seems to be a duplicate of #3008. We'll keep the discussion over there, thank you!

**Closed as not planned by Chew** 2022-07-15 01:28 UTC
