### ISSUE TITLE
Hope users can customize Geyser's login GUI

### ISSUE THREAD

**Issue by MC-Nirvana** [GeyserMC/Geyser#2436] opened 2021-08-01 06:03 UTC
### What feature do you want to see added?

Hope users can customize Geyser's login GUI
Such as customizing which buttons are displayed, as well as customizing button text, color and other functions(Realized by modifying the configuration file)

### Are there any alternatives?

If it cannot be placed in config.yml, you can choose to generate a new yml file to customize the login GUI interface

**Comment by Konicai** [comment] 2021-08-01 06:11
Duplicate of https://github.com/GeyserMC/Geyser/issues/2059 and https://github.com/GeyserMC/Geyser/issues/1390

**Closed by Konicai** 2021-08-01 06:11 UTC
Labels: Feature Request
