### ISSUE TITLE
"Playing Now" title is not the same as minecraft java titles. (Custom Music Disc)

### ISSUE THREAD

**Issue by Tydium** [GeyserMC/Geyser#3324] opened 2022-09-29 03:15 UTC
### Describe the bug

When registering custom music disc as custom items. I noticed that when you try to play them it shows the title from my datapack that I sent (which cancels the "Now playing" of the original disc on java) and it also shows the original disc title behind it.

### To Reproduce

1. Create a custom music disc using mappings.
2. Send a title on disc play with the custom disc.

### Expected behaviour

It should go over and completely get rid of the original disc playing message.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/67938521/192930266-91365dba-4db7-4b0f-8af2-805cc2172cb6.png)

Take a look on the bottom. Left is bedrock, right is java.

### Server Version and Plugins

Geyser Standalone: This server is running Geyser version 2.1.0-SNAPSHOT (git-master-98cfdb0) (Java: 1.19.1 - 1.19.2, Bedrock: 1.19.0/1.19.2 - 1.19.3

Velocity: Velocity 3.1.2-SNAPSHOT (git-213f3f88-b183)

Purpur 1.19.2: Current: git-Purpur-1760 (MC: 1.19.2)*
Previous: git-Purpur-1714 (MC: 1.19)
* You are 39 version(s) behind

### Geyser Dump

https://dump.geysermc.org/tOIHBqUxcVw1yzcrYVgYUxvC2R4MPNmI

### Geyser Version

This server is running Geyser version 2.1.0-SNAPSHOT (git-master-98cfdb0) (Java: 1.19.1 - 1.19.2, Bedrock: 1.19.0/1.19.2 - 1.19.3

### Minecraft: Bedrock Edition Device/Version

Minecraft Windows 11/10 Edition, Nintendo Switch, Android, Iphone, PS4, Xbox

### Additional Context

Feel free to ask me for my mappings file, my resource packs (they are open sourced), or any other data from me.

**Comment by Kas-tle** [comment] 2022-11-26 09:02
Have you checked if this occurs on bedrock with the vanilla music disc? In your description you only state you tried with a custom music disc and compare this behavior to java.

**Comment by Tydium** [comment] 2022-11-26 16:42
Let me test with a normal bedrock disc. (ill also test with a normal disc on geyser as well)

**Comment by Tydium** [comment] 2022-11-26 17:10
I think I may be a bit dumb on why this actually happened.

In the datapack, what I did was use the title command to show the names on the bottom considering "Disc 11" would show either way. 

The subtitles for both /title and the titles of the Jukebox, are the same as each other on Java Edition.
On bedrock edition the titles for the jukebox and subtitle are different. So I don't think this issue is a geyser issue anymore. I can probably change this via a resource pack to make it look more like a java subtitle. However it would still overlap the actual disc message on bedrock. Not entirely sure how I would fix that. Maybe I can stop the disc message from being sent if its custom. That's probably above my skill level tho.

**Comment by Jens-Co** [comment] 2023-04-29 15:22
Any updates on this topic?

**Comment by Tydium** [comment] 2023-05-03 20:40
Been awhile since I had tested. I am unsure

**Comment by onebeastchris** [comment] 2023-05-21 20:59
https://github.com/GeyserMC/Geyser/pull/3771 quite a stretch; but maybe fixed by this PR?

**Comment by rtm516** [comment] 2023-05-26 22:36
> #3771 quite a stretch; but maybe fixed by this PR?

No this is caused by the fact that bedrock client expects the server to tell it to show the record title. So we send this and it sits in a sligly different popup from the normal actionbar text.

**Comment by Kas-tle** [comment] 2024-03-19 05:33
Looking back at this, could you check if on the java side the resource pack was perhaps removing the now playing subtitle via lang files?

**Comment by onebeastchris** [comment] 2024-07-04 15:47
Closing due to no further response.

**Closed by onebeastchris** 2024-07-04 15:47 UTC
Labels: Waiting On Response
