### ISSUE TITLE
Chunks stop loading when traveling on minecarts

### ISSUE THREAD

**Issue by Gnfhaotian** [GeyserMC/Geyser#4791] opened 2024-06-23 06:46 UTC
### Describe the bug

Chunks stop loading when traveling on minecart at a high speed.

### To Reproduce

1.Joining the server
2.Traveling on a minecart
3.Chunks stop loading and need to rejoin the server

### Expected behaviour

the chunks load.

### Server Version and Plugins

Server runs on 1.20.1, Java（Spigot）
PLUGINS
via version
essential

### Geyser Version

2.4.0 （Build#582）

### Minecraft: Bedrock Edition Device/Version

both 1.20.81 and 1.21.0, Android

### Additional Context

I searched on Github and saw this was issued by 3490# and solved by 3498#. However, it still happens on the latest update of geyser.

**Comment by onebeastchris** [comment] 2024-06-23 09:00
Thanks for reporting. Unfortunately, this is a duplicate of an existing issue: https://github.com/GeyserMC/Geyser/issues/4413
Can you check the build linked there and see if that helps?

**Closed** 2024-06-23 09:00 UTC
Labels: Duplicate

**Comment by Gnfhaotian** [comment] 2024-06-23 11:25
> Thanks for reporting. Unfortunately, this is a duplicate of an existing issue: #4413 Can you check the build linked there and see if that helps?

The chunks are loaded rightly now, thx a lot
