### ISSUE TITLE
Creative Mode inventory doesn't work when switching from survival mode.

### ISSUE THREAD

**Issue by JeriRyu** [GeyserMC/Geyser#1132] opened 2020-08-12 02:38 UTC
**Describe the bug**

When a player's game mode is switched from the default Survival Mode to Creative Mode, the Creative Mode inventory doesn't work and no blocks or items can be taken from the inventory.

**To Reproduce**

1. Create a world with default game mode Survival.
2. Use ```/gamemode creative``` to set a player into Creative Mode.
3. Now check your creative mode inventory, nothing can be taken down.

**Expected behavior**

Just like normal gaming, you should be able to pick anything you want from Creative Mode inventory smoothly.

**Server Version**

Paper version git-Paper-134 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Geyser Version**

Geyser version 1.0.0 (git-master-3ef7e30) (Java: 1.16.1, Bedrock: 1.16.0)

**Minecraft: Bedrock Edition Version**

v.1.16.10

**Comment by DoctorMacc** [comment] 2020-08-12 02:40
Please update your Geyser and provide a Geyser dump, or a snippet of the bootstrap information of the dump.

**Comment by DoctorMacc** [comment] 2020-08-12 02:45
(I'm not able to confirm this on a vanilla 1.16.2 server)

**Comment by JeriRyu** [comment] 2020-08-12 03:22
Okay, I've upgraded Geyser to the latest version 1.1.0 (git-master-d3ef3a4) and done some tests. I found that this bug more happens when you directly drag items from creative inventory to the crafting table, it doesn't work.

**Comment by DoctorMacc** [comment] 2020-08-12 03:24
Ah, then this is a duplicate of #402 so I'll be closing it. The problem is that you can't access the creative inventory from the crafting table in Java. 

Thank you for reporting anyway! If the status of this bug changes please feel free to respond with more information.

**Closed by DoctorMacc** 2020-08-12 03:24 UTC
Labels: More Info Needed, Unconfirmed Bug
