### ISSUE TITLE
Enderchest Bug

### ISSUE THREAD

**Issue by Tristan3030** [GeyserMC/Geyser#820] opened 2020-06-27 23:06 UTC
**Describe the bug**
 Opening an enderchest on MCPE causes you to disconnect from the server within about 5 seconds. Also showing nothing inside the ender chest.

**To Reproduce**
1. Get an enderchest on MCPE
2. Open it
3. See nothing inside
4. Get disconnected

**Expected behavior**
 I expected to see my items inside my enderchest after i opened it.

**Screenshots / Videos**
 None

**Server Version**
This server is running CraftBukkit version git-Spigot-758abbe-2b00831 (MC: 1.16.1)(Implementing API Version 1.16.1-R0.1-SNAPSHOT) You are 43 Version(s) behind 

**Geyser Version**
I’m just a player on the server

**Minecraft: Bedrock Edition Version**
v1.16.0 

**Additional Context**
None

**Comment by DoctorMacc** [comment] 2020-06-28 14:24
Does this happen with the latest working builds on Jenkins?

**Comment by RednedEpic** [comment] 2020-06-28 15:58
Unable to reproduce. Can you please provide a video of this not working if the issue is still a problem on the latest build?

**Comment by AJ-Ferguson** [comment] 2020-06-29 19:26
I suspect the cause of this issue was the same as #818, which is now fixed.
Can you please test the latest 1.16 build?

**Comment by Tristan3030** [comment] 2020-06-29 20:51
Latest build seems to fix this somehow

**Closed** 2020-06-29 20:51 UTC
Labels: Unconfirmed Bug
