### ISSUE TITLE
Microsoft 2fa support

### ISSUE THREAD

**Issue by VoidDave** [GeyserMC/Geyser#2599] opened 2021-10-30 07:51 UTC
### What feature do you want to see added?

I really want to see 2fa support for microsoft account users, for standalone version.

### Are there any alternatives?

Optionaly some 2fa detection with give you time to accept login request

**Comment by Chew** [comment] 2021-10-30 17:36
Duplicate of #2496 

Thanks for reporting anyway!

**Closed by Chew** 2021-10-30 17:36 UTC
Labels: Feature Request
