### ISSUE TITLE
Archaeology 1.20 Issues

### ISSUE THREAD

**Issue by masonajoyner** [GeyserMC/Geyser#3989] opened 2023-07-15 20:41 UTC
### Describe the bug

I'm having an issue where bedrock players on my java server cannot use the brush on suspicious gravel and sand. Works perfectly for java players, but bedrock players use the brush and it goes about half way and then the block resets so they can't successfully brush the block and get the item. I tested the users ability to do it on a bedrock server/map and it worked fine, so the issue seems to be something with bedrock playing on java servers.

### To Reproduce

1. use brush on suspicious sand/gravel block
2. block partially breaks and then resets

### Expected behaviour

the block should break completely and produce an item

### Server Version and Plugins

Paper version git-Paper-67 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: e105354)

### Geyser Dump

https://dump.geysermc.org/VCMMRJqGuCjbNeUd4oNFlOfGzoOAqevi

### Geyser Version

Geyser version 2.1.2-SNAPSHOT (git-master-3a0c1b7) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.10)

### Minecraft: Bedrock Edition Device/Version

v1.20.22, xbox series x

**Comment by Konicai** [comment] 2023-07-15 22:10
Duplicate of 3921

**Closed by Konicai** 2023-07-15 22:10 UTC
