### ISSUE TITLE
Boats Minecarts and Hourses can't be used

### ISSUE THREAD

**Issue by AnonAlpha** [GeyserMC/Geyser#187] opened 2020-03-01 11:07 UTC
**Describe the bug**
Boat will disappear when players place them down
Minecarts can be placed but can't be sitted
Hourses can't be rided

**To Reproduce**
1. Set up Geyser
2. Put these things down
3. And you will see it

**Expected behavior**
Boats can be used
Minecarts can be sitted
Hourses can be rided

**Screenshots**
none

**Server version**
CraftBukkit version git-Spigot-800b93f-8160e29 (MC: 1.15.2)

**Geyser version**
Plugin version latest

**Bedrock version**
1.14.3

**Comment by Legit4K** [comment] 2020-03-01 11:44
This is literally a duplicate of #176 xd

**Comment by RednedEpic** [comment] 2020-03-01 14:26
See #176.

**Comment by LegacyGamerHD** [comment] 2020-03-01 14:27
@RednedEpic  doesn't state horses and minecaarts

**Comment by AnonAlpha** [comment] 2020-03-01 15:27
It seems to be a probelm with all vehicles
hourses and minecarts are caused by the right/left click problem
while boat also have a problem that it can't be placed by mobile, while win10 can place it but can't get on, there also have a possibility that players will be kicked when placing boat with the error:"Flying not allowed"

**Comment by RednedEpic** [comment] 2020-03-01 15:29
> It seems to be a probelm with all vehicles
> hourses and minecarts are caused by the right/left click problem
> while boat also have a problem that it can't be placed by mobile, while win10 can place it but can't get on, there also have a possibility that players will be kicked when placing boat with the error:"Flying not allowed"

It’s because mounting on vehicles has not yet been implemented. Although they are technically put on them when looking at the player from the perspective of Java edition, the bedrock edition does not think it’s been mounted, thus causing movement packets to have weird behavior.

**Closed** 2020-05-23 21:39 UTC
Labels: Missing Implementation, Priority: Medium, Work in Progress
