### ISSUE TITLE
Wrong teleport location and wrong facing

### ISSUE THREAD

**Issue by masterhacka** [GeyserMC/Geyser#2083] opened 2021-03-29 15:30 UTC
### Describe the bug

When joining via Bedrock Edition I mostly spawn facing south in my worlds. Sometimes when changing the world I spawn somewhere else then the world spawn. How can I fix this?

### To Reproduce

Join server with EasySetSpawn + Multiverse via Bedrock and via Java so you can see.

### Expected behaviour

Spawn in right direction as Java players

### Geyser Dump

https://dump.geysermc.org/MpiO36qV6wu15Goc4HSQm6llhQG8hrPh

### Geyser Version

1.2.0-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.16.210

**Comment by Camotoy** [comment] 2021-03-29 15:32
Sounds like this is a duplicate of #1284; therefore, I am closing. Thank you for reporting anyway!

**Closed by Camotoy** 2021-03-29 15:32 UTC
