### ISSUE TITLE
Ghost blocks appear when insta mining blocks on bedrock

### ISSUE THREAD

**Issue by HaveSomeRubicon** [GeyserMC/Geyser#3113] opened 2022-07-04 16:49 UTC
### Describe the bug

When i insta mine blocks on bedrock edition ghost blocks appear in some of the spots where i insta mined blocks.

### To Reproduce

1. Find a couple blocks you can insta mine
2. Insta mine all of them really fast
3. Result: some on the blocks you mined with be ghost blocks

### Expected behaviour

The blocks will be mined and no ghost blocks should appear.

### Server Version and Plugins

This server is running Paper version git-Paper-46 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: d86fde5)

PLUGINS:
CreeperConfetti.jar
DiscordSRV-Build-1.25.1.jar
floodgate-spigot.jarGeyser-Spigot.jar
ImageOnMap-4.2.2.jar
LocketteX-1.7.7.jar
LuckPerms-Bukkit-5.4.30.jar
Multiverse-Core-4.3.1.jar
Multiverse-Inventories-4.2.3.jar
NoEndermanGrief-1.14_1.0.3.jar
OnePlayerSleep.jar
OpenInv.jar
OreAnnouncer-2.8.3.jar
ViaBackwards-4.3.0.jar
ViaVersion-4.3.1.jar

### Geyser Dump

https://dump.geysermc.org/GKakH2CFwKOmIOpkQgFQmbdNqFzbUS5L

### Geyser Version

 This server is running Geyser version 2.0.4-SNAPSHOT (git-master-18f6836) (Java: 1.19, Bedrock: 1.19.0)

### Minecraft: Bedrock Edition Device/Version

1.19.0 android

**Comment by onebeastchris** [comment] 2022-07-04 16:52
i can confirm this issue happening to me too - used a velocity proxy with a fabric backend, no plugins other than geyser, floodgate on both, luckperms, and FabricProxyLite

**Comment by HaveSomeRubicon** [comment] 2022-07-04 18:06
Also this did not happen on 1.18

**Comment by Insidi0usAngel** [comment] 2022-07-05 22:16
This also happened with my server, but although its been happening to a bedrock player for a while even in back in 1.18.2 I thought it might be because their device is not the best as the issue is a bit like lag - mined blocks re-appearing and placed blocks later disappearing.  But recently whilst I was mining on JAVA at speed I experienced the same thing when I was stopped by an invisible block that I had mined (which when i then hit with a stick became visible) - so it maybe that this is more of a 1.19 issue than a geyser/bedrock issue.

**Comment by Camotoy** [comment] 2022-07-10 03:06
Can you please try with the latest Geyser version?

**Comment by aleixiisischmexy** [comment] 2022-08-06 16:34
> Can you please try with the latest Geyser version?

this still happens on the newest version

**Comment by AndyIsHereBoi** [comment] 2022-08-06 17:20
I was still having this happen it looks like it occurs when bedrock mines outside of the max Java mine distance especially on mobile I experienced it a lot

**Comment by Valkuris** [comment] 2022-08-14 01:08
how can i fix this?

**Comment by TheRealArchie** [comment] 2022-08-18 09:01
can confirm my server has it too.

**Comment by HaveSomeRubicon** [comment] 2022-08-24 03:46
seems to be even worse now

**Comment by spookymgmt** [comment] 2022-08-30 23:27
it's horrible on 1.19.2, plssss help

**Comment by TheRealArchie** [comment] 2022-09-15 17:39
@Camotoy Considering what others have said, this might just be a 1.19 issue. Perhaps you could provide a potential fix by giving the instant mining a slight delay?

**Comment by Camotoy** [comment] 2022-09-15 17:41
Yes, this is a 1.19 issue. I'm not sure if that would be a great workaround. I've looked into this issue and aaaaaaaaaaaaaaaaaaa. I'll look more into it once extensions is merged.

**Closed** 2022-09-27 23:24 UTC
