### ISSUE TITLE
Custom_Model_Data in itemMappings, not working with BlockMappings

### ISSUE THREAD

**Issue by Pixandi** [GeyserMC/Geyser#4326] opened 2023-12-05 14:19 UTC
### Describe the bug

When I try to make multiple BlockMappings and try to bind them to a CustomModelData in the itemMappings, only the first CustomModelData will work. all ofthe values and the default block will disappear/be invisible in Bedrock.

### To Reproduce

1. Make a ItemMapping with multiple Custom_Model_Data's
2. Make multiple BlockMappings 

### Expected behaviour

It should be possible to have multiple BlockMappings per item.

### Geyser Version

2.2.0-SNAPSHOT

**Comment by Kas-tle** [comment] 2023-12-05 17:10
Could you please share your mappings file so I can understand what you're doing here?

**Comment by Pixandi** [comment] 2023-12-06 06:43
[david.json](https://github.com/GeyserMC/Geyser/files/13577460/david.json)
[GrieferPrime-TexturePack.zip](https://github.com/GeyserMC/Geyser/files/13577461/GrieferPrime-TexturePack.zip)
[itemMappings.json](https://github.com/GeyserMC/Geyser/files/13577463/itemMappings.json)
[tobi.json](https://github.com/GeyserMC/Geyser/files/13577464/tobi.json)
I am trying to make custom 3d items with Model Data. The Models are working perfectly in item frames, but become invisible to bedrock Players when inside their inventory.

**Comment by Pixandi** [comment] 2023-12-06 16:17
I am trying to map the david.geo.json to the CustomModelData:1, and the tobi.geo.json to CustomModelData:2 of the chain_command_block. If both blockMappings are in one file, it does not work for me. But if the blockMappings are in individual files, it at least works in item frames. It is only bugged in the inventory of the Bedrock player.

**Comment by Kas-tle** [comment] 2023-12-06 16:23
That's just not how this system works. Item overrides override vanilla items with custom model data, and block overrides override vanilla blocks. I am saying that you simply cannot have individual block mappings for the same block. Those are conflicting. There's no way to know which one will be loaded first. If you are only trying to replace the item in the inventory for a specific custom model data value and not a placed block, then do not use block mappings. Only use item mappings.

**Comment by Pixandi** [comment] 2023-12-06 16:27
If that is the case, how can I create item Mappings with a 3d model and why would it work just fine in an item frame?

**Comment by Pixandi** [comment] 2023-12-06 16:48
I don't need the 3d Models for the placed Blocks. I only need the 3d Models to work in the Players Inventory. As long as the items are in item frames, both models show up just fine.
![Screenshot 2023-12-06 174615](https://github.com/GeyserMC/Geyser/assets/89071299/6d1f82eb-a9ad-4c7b-9f1c-d920566c7f72)

**Comment by Kas-tle** [comment] 2023-12-25 23:36
The pack you've sent is encrypted.

**Comment by onebeastchris** [comment] 2024-07-04 10:54
Closing due to incomplete reproduction steps.

**Closed by onebeastchris** 2024-07-04 10:54 UTC
Labels: More Info Needed
