### ISSUE TITLE
Armorstand Arm Positions and Items

### ISSUE THREAD

**Issue by iSilviu-debug** [GeyserMC/Geyser#1098] opened 2020-08-07 13:35 UTC
Hi, I'm trying a plug-in named: Armorstand tools, the Armorstand tools and items with the heads are not visible at all.
![Cattura](https://user-images.githubusercontent.com/67197594/89651056-9cda5c80-d8c3-11ea-970d-7c4c08529393.PNG)

**Comment by DoctorMacc** [comment] 2020-08-07 13:36
Please fill out the issue template.

The heads will not appear as this is currently a Bedrock limitation since there is no player head support.

**Comment by iSilviu-debug** [comment] 2020-08-07 13:36
Original
![Annotazione 2020-08-07 153557](https://user-images.githubusercontent.com/67197594/89651118-b67ba400-d8c3-11ea-89f0-7e09e589e050.png)

**Comment by iSilviu-debug** [comment] 2020-08-07 13:36
> Please fill out the issue template.
> 
> The heads will not appear as this is currently a Bedrock limitation since there is no player head support.

Ok

**Comment by rtm516** [comment] 2020-08-07 13:37
Also the arm and leg positions have presets on bedrock and as I understand you cannot change from these.

**Comment by iSilviu-debug** [comment] 2020-08-07 13:38
> Also the arm and leg positions have presets on bedrock and as I understand you cannot change from these.

I understand, no, because I saw so many bedrock servers that had these armorstand.

**Comment by iSilviu-debug** [comment] 2020-08-07 13:43
But what about the armorstand in itself because it has "weird" textures?
![Cattura](https://user-images.githubusercontent.com/67197594/89651685-96001980-d8c4-11ea-9fad-309fce962971.PNG)

**Comment by TheMasterBlaster** [comment] 2020-08-07 13:51
I do not have that texture issue using the latest Bungeecord build.

**Comment by rtm516** [comment] 2020-08-07 13:52
Nothing I've ever seen before, likely a client issue caused by a texture pack or something

**Comment by iSilviu-debug** [comment] 2020-08-07 13:53
> Compila il modello del problema.

Ok;

**Server Version**
1.16

**Geyser Version**
1.0.0

**Minecraft: Bedrock Edition Version**
1.16

**Comment by iSilviu-debug** [comment] 2020-08-07 13:54
> Nothing I've ever seen before, likely a client issue caused by a texture pack or something

I understand, then I will try to update the bungeecord version.

**Comment by RednedEpic** [comment] 2020-08-07 14:05
As mentioned, the heads not showing up are a client limitation as custom skulls are not supported on Bedrock. Additionally, custom poses as you showed in that screenshot are also not possible on Bedrock - however Bedrock does have a handful of predefined poses, but there is currently no support in the Bedrock game itself of individually tweaking each body part. Not much we can do here, sorry. Closing.

**Closed by RednedEpic** 2020-08-07 14:05 UTC
Labels: More Info Needed
