### ISSUE TITLE
Java heads not visible on bedrock

### ISSUE THREAD

**Issue by Idiot64** [GeyserMC/Geyser#1486] opened 2020-11-02 18:12 UTC
**Describe the bug**
Player heads don't show up in bedrock
[My friends are connecting over floodgate if that is theproblem]

**To Reproduce**
Grab head of a Java player
throw to bedrock user
bedrock user will only see steve's head

**Expected behavior**
See skin

**Screenshots / Videos**

Java view:

<img width="125" alt="Screenshot_6" src="https://user-images.githubusercontent.com/70104078/97903084-cbd76180-1d3e-11eb-8101-0a1365ae51fd.png">

Bedrock user's view:

![image0](https://user-images.githubusercontent.com/70104078/97903174-e7db0300-1d3e-11eb-96b2-9147ea666c0a.jpg)

**Server Version**
This server is running Paper version git-Paper-247 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
Checking version, please wait...
You are 6 version(s) behind

**Geyser Version**
This server is running Geyser version 1.1.0 (git-master-ca1f87d) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.20)
Checking version, please wait...
No updates available.

I'm using paper
and floodgate

**Minecraft: Bedrock Edition Version**
1.16.50

**Additional Context**
the dump:
https://dump.geysermc.org/DLtGuMftWAJiw2vLvFPCroQTG7lc6Jlt

**Comment by DoctorMacc** [comment] 2020-11-02 18:13
Bedrock doesn't have custom player heads at this time.

**Comment by Idiot64** [comment] 2020-11-02 18:13
ok

**Comment by Idiot64** [comment] 2020-11-02 18:13
will it be fixed?

**Comment by DoctorMacc** [comment] 2020-11-02 18:14
There's literally no way for item player heads at this time. Placed player heads we can.

**Comment by Idiot64** [comment] 2020-11-02 18:15
ok

**Comment by hteppl** [comment] 2020-11-03 16:11
> There's literally no way for item player heads at this time. Placed player heads we can.

https://cloudburstmc.org/resources/customheads.245/

**Comment by DoctorMacc** [comment] 2020-11-03 16:12
That same functionality we should have in #683.

**Comment by hteppl** [comment] 2020-11-03 16:14
> That same functionality we should have in #683.

ok :3

**Comment by Chew** [comment] 2020-11-03 20:19
Closing as a duplicate of #1454, be sure to subscribe to #683 if you wish to see if it's merged.

**Closed by Chew** 2020-11-03 20:19 UTC
Labels: Can't Fix, Confirmed Bug
