### ISSUE TITLE
Geyser Fabric Hangs when issuing stop command

### ISSUE THREAD

**Issue by JeffreyGoe** [GeyserMC/Geyser#3919] opened 2023-06-27 02:21 UTC
### Describe the bug

When you issue the server the stop command, it hangs after quitting, therefore breaking all restart scripts since the process is still running.

### To Reproduce

issue the stop command to a running server

### Expected behaviour

When issuing the stop command, the server should go back to commandline when its done shutting down

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/83684599/7166eb4e-fa4b-4888-ba76-b16dc2f080ef)

### Geyser Version

1.20.1 build 215

**Comment by Konicai** [comment] 2023-06-27 03:07
Are you able to share a jstack once the server hangs

**Comment by onebeastchris** [comment] 2023-07-09 01:06
Duplicate of https://github.com/GeyserMC/Geyser/issues/3519 - if you can provide a jstack; please share it there

**Closed** 2023-07-09 01:06 UTC
Labels: Duplicate
