### ISSUE TITLE
geyser custom block problem

### ISSUE THREAD

**Issue by 1111qqjzja** [GeyserMC/Geyser#4069] opened 2023-08-21 14:53 UTC
### Describe the bug

When registering an item with the same name as a custom block, the block has a chance to disappear
![IMG_20230821_222002](https://github.com/GeyserMC/Geyser/assets/89286242/751072a6-397b-4858-98b9-243caf313ff6)
Five shown, four gone

### To Reproduce

none

### Expected behaviour

none

### Geyser Version

2.1.2-SNAPSHOT

**Comment by 1111qqjzja** [comment] 2023-08-21 14:56
version: https://github.com/GeyserMC/Geyser/pull/3505/commits/ea42fdc8b34025c71597df02fe0bf76d2bb9cd17

**Comment by rtm516** [comment] 2023-08-22 19:13
Please update Geyser to the latest release and provide a dump and replication steps if the issue is still happening.

**Comment by 1111qqjzja** [comment] 2023-09-09 15:19
To reproduce the steps, first register multiple custom blocks on geyser, then register the item mapping of those blocks, and finally make the names of those blocks (identification names, not display names) the same as their corresponding item names, for example, the item name is xxx  , the block name also needs to be called xxx, and then you can make 3D block drops, but some blocks will be displayed and some blocks will not be displayed. I don't know if this is a bug.

**Comment by 1111qqjzja** [comment] 2023-09-09 15:25
![BY TY}_RL89W% 0$BRWP4PK](https://github.com/GeyserMC/Geyser/assets/89286242/ca5b51d6-b65c-4a28-bab6-ed8cc062d2f6)
![U1V18I8VOT SNJ{V2RFK1)K](https://github.com/GeyserMC/Geyser/assets/89286242/5fa18677-674f-43b7-860b-2e74f5c5b572)

**Comment by SuprClan** [comment] 2023-10-10 11:01
Hey can you help me in creating a custom block for geyser?

**Comment by onebeastchris** [comment] 2023-10-10 11:02
This isn't the place to ask for help creating custom blocks @SuprClan. Our wiki https://wiki.geysermc.org/geyser/custom-blocks/ has a helpful guide.

**Comment by rtm516** [comment] 2024-04-01 23:11
This has potentially been fixed with https://github.com/GeyserMC/Geyser/commit/47237e07b789e93056a0761376c688f03b86b8ae
Could you update Geyser and retest?
@1111qqjzja

**Comment by 1111qqjzja** [comment] 2024-04-02 13:43
ok, it solved, thank you

**Comment by 1111qqjzja** [comment] 2024-04-02 13:44
.

**Closed** 2024-04-02 13:44 UTC
Labels: Waiting On Response
