### ISSUE TITLE
Text display doesnt show up on bedrock edition

### ISSUE THREAD

**Issue by timtijmen2** [GeyserMC/Geyser#4172] opened 2023-10-01 19:55 UTC
### Describe the bug

Text display's do not show up for bedrock players

### To Reproduce

1. Create text display with text
2. Look at it on java
3. Look at is on bedrock
4. The text display wont show up on bedrock edition.

### Expected behaviour

The text display should show up for the bedrock player

### Screenshots / Videos

![Schermopname (4)](https://github.com/GeyserMC/Geyser/assets/70636605/2cf32b2f-8a75-4acf-9c51-0f91779c9804)

### Server Version and Plugins

1.20.2 Fabric
Geyser and floodgate

### Geyser Version

1.20.2 Fabric

### Minecraft: Bedrock Edition Device/Version

1.20.31v

**Comment by Konicai** [comment] 2023-10-01 20:06
Did this occur with the 1.20.2 update or the 1.20.30 update?

**Comment by timtijmen2** [comment] 2023-10-02 05:30
Reports only came in after updating to 1.20.2, but i dont think people on version 1.20.30v on bedrock are able to join in earlier versions of geyser
 so i guess both

**Comment by Kas-tle** [comment] 2023-10-06 14:51
Are these being added directly with the summon command or are you using a plugin? If you are using a plugin this is likely a duplicate of https://github.com/GeyserMC/Geyser/issues/4122

**Comment by timtijmen2** [comment] 2023-10-06 15:17
It is from a mod, but it used to work before the update to 1.20.2.

Ill test it when i summon it normally when i get home

**Comment by timtijmen2** [comment] 2023-10-06 18:51
> Are these being added directly with the summon command or are you using a plugin? If you are using a plugin this is likely a duplicate of #4122

Ive tested it with bedrock players and they were not able to see a summoned text display either

**Comment by Wolf2323** [comment] 2023-11-03 09:33
I am facing the same issue that TextDisplays are not shown anymore to Bedrock players. My installed version is `git-master-2e68244`.

Can i do more to may help solve this issue?

**Comment by onebeastchris** [comment] 2023-11-03 15:35
Hey there, would you be able to test the PR? (you can download the build using the `Checks` tab)
It should resolve issues with text displays not showing up.

**Closed** 2023-11-03 15:58 UTC
Labels: Waiting On Response, Possible Duplicate
