### ISSUE TITLE
/geyser statistics [BACK button] not work

### ISSUE THREAD

**Issue by TOWUK** [GeyserMC/Geyser#1508] opened 2020-11-07 17:26 UTC
**Describe the bug**

**To Reproduce**
/geyser statistics
select item
click BACK button

**Expected behavior**
none

**Screenshots / Videos**
https://youtu.be/ob_QfwrXOP8

**Server Version**
paper 1 16 4 latest (dump)

**Geyser Version**
latest (dump)

**Minecraft: Bedrock Edition Version**
1 16 40

**Additional Context**
https://dump.geysermc.org/gCyFH34hn2sj9RbvmBqJNj9NMwGUTACY

**Comment by rtm516** [comment] 2020-11-07 17:45
After testing this I'm unable to replicate it. Could you try without an item in your hand?

**Comment by TOWUK** [comment] 2020-11-07 18:19
> After testing this I'm unable to replicate it. Could you try without an item in your hand?

the button also works 50/50

**Comment by TOWUK** [comment] 2020-11-07 18:22
https://youtu.be/RFf27Q-2Flc
check it

**Comment by TOWUK** [comment] 2020-11-07 18:23
hold click - worked

**Comment by rtm516** [comment] 2020-11-09 11:44
Unless we get another report of this or someone can replicate it, I'm going to put this down to your client customisations and/or server connection. Can you disable all client modifications and tell me what your server ping is?

**Comment by TOWUK** [comment] 2020-11-09 19:45
> 
> 
> Unless we get another report of this or someone can replicate it, I'm going to put this down to your client customisations and/or server connection. Can you disable all client modifications and tell me what your server ping is?

sorry i dont understand your words

**Comment by RednedEpic** [comment] 2020-12-12 00:30
Works absolutely fine for me. Closing as I and rtm are unable to reproduce this and due to the fact that we've received no other reports on this issue.

**Closed by RednedEpic** 2020-12-12 00:30 UTC
Labels: Unconfirmed Bug
