### ISSUE TITLE
Support sending of resource pack

### ISSUE THREAD

**Issue by diamond-gold** [GeyserMC/Geyser#967] opened 2020-07-17 15:46 UTC
**What feature do you want?**
Support sending resource packs to bedrock clients

**Alternatives?**
Using a proxy that support bedrock protocol and use it to send resource pack before directing them to geyser

**Comment by Heath123** [comment] 2020-07-17 15:54
Duplicate of #210

**Comment by DoctorMacc** [comment] 2020-07-17 16:08
Thank for the feature request regardless!

**Closed by DoctorMacc** 2020-07-17 16:08 UTC
