### ISSUE TITLE
Cant strip wood logs

### ISSUE THREAD

**Issue by Pleanaa0** [GeyserMC/Geyser#5028] opened 2024-09-08 15:28 UTC
### Describe the bug

i have recently restarted my server, fresh everything since last week. since restarting, bedrock players cannot strip wood logs? this is any type of logs. server is 1.21

### To Reproduce

try to stip wood logs?

### Expected behaviour

strip wood logs into stripped wood logs?

### Server Version and Plugins

This server is running Paper version 1.21-130-master@b1b5d4c (2024-08-10T10:02:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

plugins: coreprotect, discordsrv, essentials X, floodgate-spigot, gamemodegui, gsit, invsee++, invsee++_clear, invsee++_give, luckperms, vault, viaversion, voicechat, worldedit

### Geyser Dump

https://dump.geysermc.org/tasqm7JVnNf3pVhtSkSz8BOWedHS8vNc

### Geyser Version

Geyser version 2.4.2-b661

### Minecraft: Bedrock Edition Device/Version

all bedrock players on different consoles and versions

**Comment by onebeastchris** [comment] 2024-09-08 15:31
Are the players holding a shield in their offhand while trying to strip wood?

**Comment by Pleanaa0** [comment] 2024-09-08 16:06
Okay i did ask before hand cuz i saw that was already an issue. They said
it didnt work with or without but i just had someone else try and they are
saying its only when holding a shield?

**Comment by onebeastchris** [comment] 2024-09-08 17:26
In that case, this would be a duplicate of https://github.com/GeyserMC/Geyser/issues/4871 - unequip the shield to be able to strip logs.

**Closed by onebeastchris** 2024-09-08 17:26 UTC
