### ISSUE TITLE
Server type choice

### ISSUE THREAD

**Issue by Gildur7161** [GeyserMC/Geyser#498] opened 2020-05-06 15:45 UTC
**What feature do you want?**
I was wondering, is it possible to choose if the server is Bedrock or Java? Would be a nice implementation to do, allowing Java players to join Bedrock servers or LAN games. I guess the packet translating process is done, because it wouldn't work otherwise, but I think the main problem is the account side. There is no possibility to choose "offline mode" when playing in a LAN game....

**Alternatives?**
No alternatives found yet, maybe it is just impossible to do...

**Comment by james090500** [comment] 2020-05-06 15:46
I assume you mean, join a bedrock server with a java client? That's what your asking right?
The issue is, there's currently no protocl for spoofing a bedrock client.

**Comment by Heath123** [comment] 2020-05-06 15:51
> I assume you mean, join a bedrock server with a java client? That's what your asking right?
> The issue is, there's currently no protocl for spoofing a bedrock client.

I think the NukkitX one (that Geyser already uses) can do it

**Comment by james090500** [comment] 2020-05-06 15:55
I don't think NukkitX Protocol can connect to bedrock servers as a client, almost certain that protocol is for creating a server. In this case the fake server bedrock players connect to

**Comment by DoctorMacc** [comment] 2020-05-06 16:00
Java players joining Bedrock servers is a faraway option, and if it's something that Geyser pursues it would likely be mod-only. I'm closing this since it's not really relevant to the current codebase, and it's something we've discussed before.

**Closed by DoctorMacc** 2020-05-06 16:00 UTC
Labels: Feature
