### ISSUE TITLE
Is it difficult to add mods support?

### ISSUE THREAD

**Issue by RFalcon-Mick** [GeyserMC/Geyser#3802] opened 2023-05-28 02:39 UTC
### What feature do you want to see added?

Are there any possiblilty to add mods support ?
I'm new here and don't understand the basic of Java or apis, just a user. :)

### Are there any alternatives?

Maybe Geyser can make-in forge into standalone version.

**Comment by xIsm4** [comment] 2023-05-28 04:16
> ### What feature do you want to see added?
> Are there any possiblilty to add mods support ? I'm new here and don't understand the basic of Java or apis, just a user. :)
> 
> ### Are there any alternatives?
> Maybe Geyser can make-in forge into standalone version.

Modern Forge and proxies do not get along the way it is "protocoled". At least in the BungeeCord and Velocity version for now it would be quite complicated and buggy.

**Comment by onebeastchris** [comment] 2023-05-28 05:11
Geyser already has limited mod support, atleast for fabric server side mods. Geyser-Forge is being made at the moment.

As for client mod support - that's not something we can fully implement, but we're working towards it. For example, Custom items are already possible to be mapped/added manually.
See https://wiki.geysermc.org/geyser/custom-items/ for more info.
 

Custom Blocks & custom entities are being worked on right now - you can see the progress in their respective PRs.

Seeing that this post is a duplicate of https://github.com/GeyserMC/Geyser/issues/2502 (forge support) & other requests for custom block/entities support, I'll be closing this as duplicate. Thanks anyways.

**Closed** 2023-05-28 05:11 UTC
Labels: Duplicate
