### ISSUE TITLE
Mojang Skin system not worked [online mode all configs]

### ISSUE THREAD

**Issue by TOWUK** [GeyserMC/Geyser#1092] opened 2020-08-06 00:55 UTC
**Describe the bug**
just set online mode true in all server configs
check video (advanced)
**Expected behavior**
ESBE 2G shaders, ASTRAL client - Bedrock

**Screenshots / Videos**
https://youtu.be/YN5tr0vd_co

**Server Version**
dump

**Geyser Version**
dump

**Minecraft: Bedrock Edition Version**
1.16.1+ win10

**Additional Context**
https://dump.geysermc.org/FcKbCHaBH0G68bio9wpS21vIzxzSNoha

**Comment by towuk118** [comment] 2020-08-06 01:02
log: spawning after skin set???
[latest.log](https://github.com/GeyserMC/Geyser/files/5031919/latest.log)

**Comment by rtm516** [comment] 2020-08-06 01:08
Likely caused by skin restorer, please see https://github.com/GeyserMC/Geyser/pull/680

**Comment by towuk118** [comment] 2020-08-06 10:02
> Likely caused by skin restorer, please see #680

I found this error before installing skinsrestorer, and then installed It as well...

**Comment by towuk118** [comment] 2020-08-06 10:52
UPD: skins turned out to be fixed by removing viarevind and viaversion

**Comment by DoctorMacc** [comment] 2020-08-07 16:39
Can you confirm if this is fixed in the latest build?

**Comment by DoctorMacc** [comment] 2020-08-12 16:42
Closing as there is no response and we've had several skin updates. Please reopen if this still occurs.

**Closed by DoctorMacc** 2020-08-12 16:42 UTC
