### ISSUE TITLE
Splitscreen

### ISSUE THREAD

**Issue by Stanlyhalo** [GeyserMC/Geyser#1459] opened 2020-10-27 18:07 UTC
Either this is a bug, or something not implemented yet, but it would be really cool if console players (idk about other bedrock platforms) when having 2nd player join on a server that has floodgate enabled to allow a second player for splitscreen.

**Comment by DoctorMacc** [comment] 2020-10-27 18:08
This is a duplicate of #750. Regardless, thanks for suggesting!

**Closed by DoctorMacc** 2020-10-27 18:08 UTC
