### ISSUE TITLE
Camels spin when rides with saddle on bedrock edition 

### ISSUE THREAD

**Issue by KulrajSinghSandhu** [GeyserMC/Geyser#4065] opened 2023-08-19 12:29 UTC
### Describe the bug

When you mount camel it doesn't spin but when u put saddle it starts spinning 

### To Reproduce

1. Log in server with bedrock account
2. Mount camel
3. Put saddle
4. Try to move

### Expected behaviour

It should walk normally like horses

### Geyser Dump

https://dump.geysermc.org/JYAxsrModBBRFp4uBZmZeIomwHFD7cHO

### Geyser Version

2.1.2-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.20.12,Android

**Comment by onebeastchris** [comment] 2023-08-19 12:31
Duplicate of https://github.com/GeyserMC/Geyser/issues/3860, thanks anyways for reporting.

**Closed** 2023-08-19 12:31 UTC
Labels: Duplicate
