### ISSUE TITLE
Boat de-sync problem

### ISSUE THREAD

**Issue by Leonardo-Fiori** [GeyserMC/Geyser#728] opened 2020-06-03 00:05 UTC
**Describe the bug**
An user playing from MCPE on Android mounted on a boat i spawned for him in the ocean. He stated to be lagging a bit but then the lag stopped. I was looking at him swinging his arm on the boat and moving the head around. Then he stated that he couldn't break any block. I asked him where (the fuck) was he located and he replied that he wasn't in the sea on the boat but he already landed on a nearby island. I always saw him standing in the boat in the same position moving only arms and head. Then suddenly he came back to the boat (like if teleported) and could correctly move with the vehicle. My anticheat did not trigger, and there were no errors in console.

**To Reproduce**
Don't know, sorry!

**Server Version**
git-Paper-307 (MC: 1.15.2)

**Geyser Version**
Standalone (Hosted on external VPS), with default config. Floodgate on the java server's bungeecord. 

Command to check geyser's version? Could be some builds behind the current one

**Comment by D3ATHBRINGER13** [comment] 2020-06-25 22:22
if you have the log file you can see what version geyser is
also /geyser version command is being implemented along with 1.16 update

**Comment by NathanWolf** [comment] 2021-03-01 20:10
I ran into a similar issue and may have a simple reproduction case, just have two players (possibly needing to be Bedrock players) run into each other in a boat.

The server will start spamming log messages like this one:
> [12:54:42 WARN]: Boat (vehicle of <redacted username>) moved too quickly! -54.9708251953125,0.0,-29.634033203125

```
This server is running Paper version git-Paper-497 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
This server is running Geyser version 1.2.0-SNAPSHOT (git-master-ae3f50a) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.200/1.16.201)
```

**Comment by RednedEpic** [comment] 2022-01-22 01:00
Hasn't been reported in a long time & boat behavior has changed internally since this was opened, so I am going to close this issue. If this still occurs please feel free to comment here.

**Closed by RednedEpic** 2022-01-22 01:00 UTC
Labels: Confirmed Bug, Priority: Low
