### ISSUE TITLE
Bedrock users unable to login after accidental duplicate login from the same IP

### ISSUE THREAD

**Issue by petersv5** [GeyserMC/Geyser#4807] opened 2024-06-29 07:34 UTC
### Describe the bug

Two of our players are brothers and live in the same house. They accidentally logged on once using the same account and apparently coming from the same IP address as theyt live in the same house. They naturally got kicked out as the account was already logged on. However, afterwards all Bedrock users were denied with the same message than an unexpected length of client->server packet was detected.

The issue persisted until the server was restarted. 

I understand that this is a corner case, but I wanted to let you know in case there is some way to make the error at least not affect all players.

### To Reproduce

1. Log on as bedrock player A from behind a NAT box
2. Log on as the same player A from another computer behind the same NAT box
3. Further logins from bedrock users do not work

### Expected behaviour

One or both users are kicked. Further logins are possible by player A or another player.

### Server Version and Plugins

This server is running Geyser version 2.4.0-SNAPSHOT (git-master-fc529a6) (git-master-fc529a6) (Java: 1.21, Bedrock: 1.20.80/1.20.81 - 1.21.0/1.20.1)

### Geyser Dump

https://dump.geysermc.org/3R5gJlu1bE4Z86Ma5olHsTw45m3DLsck

### Geyser Version

git-master-fc529a6

### Minecraft: Bedrock Edition Device/Version

Unknown

### Additional Context

Logs from the event: https://mclo.gs/p4Z3nem

**Comment by Kas-tle** [comment] 2024-06-29 23:28
Cannot reproduce. In your logs I only see a single Bedrock user. Can you confirm this happens with other Bedrock users? Can you also confirm the same does not occur if the same Java user attempts to join?

**Comment by petersv5** [comment] 2024-07-01 14:37
Lon ger log also showing user gaminglior2812 trying to log in: https://mclo.gs/8aGxZOz
What happened was that the two bedrock users accidentally logged in using Amogus3744 from two devices with the same NAT device. After a short while of confusion gaminglior2812 switched to the correct profile on his console, but neither was able to log on until the server was restarted.

Java could join without problems while this was going on.

Both gaminglior2812 and Amogus3744 normally play from the same two devices, but using two different logins.

**Comment by onebeastchris** [comment] 2024-07-25 01:47
The issue you're seeing with `Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet play/serverbound/minecraft:custom_payload (class_2817) was larger than I expected, found 999 bytes extra whilst reading packet serverbound/minecraft:custom_payload` has been resolved in the latest version of floodgate-fabric. I think the issue here is an indirect result of that bug? Please update Floodgate-Fabric and see if the issue persists. Thanks!

**Comment by onebeastchris** [comment] 2024-07-30 21:52
Closing as the underlying issue should have been fixed. Thanks for reporting!

**Closed by onebeastchris** 2024-07-30 21:52 UTC
Labels: Unconfirmed Bug/Not Currently Replicable, Waiting On Response
