### ISSUE TITLE
When the food is held in the offhand, the bedrock client cannot eat it.

### ISSUE THREAD

**Issue by bddjr** [GeyserMC/Geyser#3551] opened 2023-02-13 05:46 UTC
### Describe the bug

title.

### To Reproduce

1. Holding food, use command `/geyser offhand`
2. Try to eat it.

### Expected behaviour

Like the java client, you can eat it.

### Server Version and Plugins

minecraft server version 1.19.2

### Geyser Dump

https://dump.geysermc.org/e5FiHUoKPpPOob2avGvOU9i056zDiBw4

### Geyser Version

[geyser-fabric] This server is running Geyser version 2.1.0-SNAPSHOT (git-master-f9705c1) (Java: 1.19.3, Bedrock: 1.19.20 - 1.19.60)

### Minecraft: Bedrock Edition Device/Version

1.19.60

**Comment by Konicai** [comment] 2023-02-13 05:57
Duplicate of #2425, #1281

In essence, there is no way for Geyser to know if you want to use the item in your offhand. Bedrock Edition simply does not have this feature

**Closed by Konicai** 2023-02-13 05:57 UTC

**Comment by bddjr** [comment] 2023-02-13 06:04
But why can use [quick-shulker](https://www.curseforge.com/minecraft/mc-mods/quick-shulker)

**Comment by Konicai** [comment] 2023-02-13 06:06
Bedrock Edition doesn't let you use arbitrary items in the offhand

That mod detects clicking/using the item - Geyser has no way to know when you want to use the offhand item, because Bedrock Edition doesn't have that.

**Comment by bddjr** [comment] 2023-02-13 08:41
(Translate by deepl.com)
Since it can detect whether to right-click to use, is it possible to simulate left-handed use of items when right-handed items cannot be used
