### ISSUE TITLE
Can't place water or lava

### ISSUE THREAD

**Issue by KyTDK** [GeyserMC/Geyser#1306] opened 2020-09-17 09:28 UTC
**Describe the bug**
Can't place water or lava using a bucket or xbox one, running off spigot 1.16.3
**To Reproduce**

**Expected behavior**

**Screenshots / Videos**

**Server Version**
1.16.3
**Geyser Version**
#392
**Minecraft: Bedrock Edition Version**
Latest
**Additional Context**

**Comment by RednedEpic** [comment] 2020-09-17 12:45
Duplicate of #1293.

**Closed by RednedEpic** 2020-09-17 12:45 UTC

**Comment by freekvh** [comment] 2020-10-04 08:51
I still have issues with water, since updating everything to latest [https://dump.geysermc.org/LdI4aOAPL82cp9nMvJD2VINKbWRfQQpZ](https://dump.geysermc.org/LdI4aOAPL82cp9nMvJD2VINKbWRfQQpZ) I can now sometimes place water but it just sits there, not flowing (I did this on sand btw), see here:

![schermshot](https://user-images.githubusercontent.com/12241293/95011231-8c2e3480-062f-11eb-8d0b-073ca5d2db3e.png)
