### ISSUE TITLE
Geyser overwrites floodgate config on Quilt MC

### ISSUE THREAD

**Issue by TheUnknownCod3r** [GeyserMC/Geyser#3968] opened 2023-07-12 12:57 UTC
### Describe the bug

When running QuiltMC on a server, and adding both Geyser and Floodgate, the config for Floodgate will be completely overwritten by Geyser, thus making Floodgate's original config invalid and it fails to load with the error below

https://pastebin.com/3piQRT1T

The actual issue is Geyser overwriting the config for Floodgate with its own, thus making them both unusable together. I believe this is Geyser related, not floodgate

### To Reproduce

Set up a Minecraft server with Floodgate and QSL, run it once until it finishes loading, then stop the server.
make a note of the contents of floodgate's config.yml

Add Geyser to the mods folder, and reboot the server, Geyser will overwrite the config for Floodgate, leading to a crash.

### Expected behaviour

Geyser and Floodgate to run concurrently without issues.

### Server Version and Plugins

Quilt MC 1.20.1 0.19.2

### Geyser Version

Not sure, one version before latest as this has been an issue for a couple of days

### Minecraft: Bedrock Edition Device/Version

N/A

**Comment by onebeastchris** [comment] 2023-07-12 12:59
Duplicate of https://github.com/GeyserMC/Floodgate-Fabric/issues/7 - additionally, Geyser-Fabric's side was fixed already here https://github.com/GeyserMC/Geyser/commit/dd632ef4b19a52e99107eec77334efe2cac4a9f8

**Closed** 2023-07-12 12:59 UTC
Labels: Duplicate

**Comment by TheUnknownCod3r** [comment] 2023-07-12 13:02
> Duplicate of [GeyserMC/Floodgate-Fabric#7](https://github.com/GeyserMC/Floodgate-Fabric/issues/7) - additionally, Geyser-Fabric's side was fixed already here [dd632ef](https://github.com/GeyserMC/Geyser/commit/dd632ef4b19a52e99107eec77334efe2cac4a9f8)

So if it's been fixed for a while, will it ever get ported to fabric? cause not one of the fixes work, including adding the original config info to Floodgate... The issue stems from Geyser overwriting the config itself, so I don't see how its a duplicate of a 2 year old issue thats apparently been fixed for almost a year...

**Comment by TheUnknownCod3r** [comment] 2023-07-12 13:04
> It's been fixed within Geyser-fabric, not Floodgate-Fabric - the fix is kind of difficult since Floodgate creates it's config differently than Geyser does it.

Ah fair enough, sort of understand that explanation a bit more than just reading that issue. I'd run fabric but several mods we use are quilt only now. Thanks for taking time to respond, even though I worded my response badly.
