### ISSUE TITLE
Chat Crash while typing "/"

### ISSUE THREAD

**Issue by zOIDAdaJulian** [GeyserMC/Geyser#1895] opened 2021-02-03 13:24 UTC
**Describe the bug**
Minecraft PE freezes, when you open the chat and only type "/"

**To Reproduce**
- Download the Geyser-server-inventory Standalone.
- Start the .jar file
- Join the Server via Floodgate
- Open the chat and type "/"
- Freezed

**Expected behavior**
You should be able to type all commands you'd like to.

**Screenshots / Videos**
https://youtu.be/0I-KkIfAbfc

In this Video you can see, when I type "/" it instantly freezes.

**Server Version and Plugins**
Server Version: 1.16.4
Paper (git-Paper-416)

**Geyser Dump**
https://dump.geysermc.org/mrtqYfXacxP8NkM9aIA72KQRVuasNl9c

**Minecraft: Bedrock Edition Version**
PE Version: 1.16.100

**Comment by EasyClifton** [comment] 2021-02-03 13:28
This happens because Minecraft Bedrock client is not able to process all the command suggestions the server sends to it. The client should load all suggestions after some time, but if it doesn't, your only option will be to disable the `command-suggestions` option in the Geyser config. This will remove the command suggestions that cause the client to hang.

**Comment by zOIDAdaJulian** [comment] 2021-02-03 13:30
However, this only happens with the inventory rewrite Version. With the Master Geyser Version everything is working fine.

**Comment by Camotoy** [comment] 2021-02-03 15:32
That's doubtful - unless (technical talk start) having the server authoritative toggle turned on in the StartGamePacket affects how command suggestions are processed (technical talk end), I highly doubt that the server inventory branch would change this. I'll mark this as unconfirmed for now in case other people have something similar to report.

**Comment by Camotoy** [comment] 2021-02-05 16:47
Unable to replicate any difference with the server inventory branch and master branch on 1.16.201. Perhaps try updating your Minecraft version?

**Comment by zOIDAdaJulian** [comment] 2021-02-05 22:27
It's worth a try, I'll attempt it.

**Comment by zOIDAdaJulian** [comment] 2021-02-05 22:44
Unfortunately, still the same as before. MCPE freezed with the Inventory Branch and everything fine on the Master Branch.
But as EasyClifton already said, setting command-suggestions to false fixed this. Still very strange, that this problem only happens on the Inventory Branch.

**Comment by nickg2** [comment] 2021-02-06 14:22
I see this has the unconfirmed tag, I can confirm this has been affecting me as well.

**Comment by nickg2** [comment] 2021-02-06 14:34
Heres something that a player sent to me 
"So had the freezing bug happen many many times yesterday [day server inventory branch was used]. Every time it happened was immediately after bringing up the chat interface or a few seconds after. Sometimes it was just brining up the chat interface and nothing else. The entire interface would freeze for about 20-40 seconds and then everything would go back. The audio that was invoked would finish out and the machine ( Notification Center, etc) was still completely responsive so it isn’t a platform or host issue. But to be clear, it happens after invoking the chat interface sometimes before typing anything so it isn’t related to commands.
Or the autocomplete system"

**Comment by LichLord91** [comment] 2021-02-06 22:46
Im having the same issue, seems to be  related more to command completion , im on the latest inventory branch as well. Ill test turning off command completion and maybe swap out to main branch to see if its isolated to inventory branch, doubtful though.

**Comment by Camotoy** [comment] 2021-02-14 21:58
Caused by https://github.com/CloudburstMC/Protocol/commit/571f0dcf11284b7419ad48aa9fa487a080509bb0.

Master branch:
![image](https://user-images.githubusercontent.com/20743703/107890263-d086e680-6ee5-11eb-8d63-1e8d1d14a1f9.png)

Server inventory branch: 
![image](https://user-images.githubusercontent.com/20743703/107890258-cb299c00-6ee5-11eb-8d52-2bc1ed0df517.png)

**Comment by Camotoy** [comment] 2021-02-18 00:42
Largely fixed with #1936.

**Closed by Camotoy** 2021-02-18 00:42 UTC
Labels: Confirmed Bug

**Comment by LichLord91** [comment] 2021-02-19 22:31
> Im having the same issue, seems to be related more to command completion , im on the latest inventory branch as well. Ill test turning off command completion and maybe swap out to main branch to see if its isolated to inventory branch, doubtful though.

I forgot to reply back but yes looks like this is fixed with the new commit no crashes thusfar , slight lag when first typing / but defenitly useable and no longer crashing.
