### ISSUE TITLE
Console Error Spam: Could not translate the packet: InventoryTransactionPacket

### ISSUE THREAD

**Issue by youwen233** [GeyserMC/Geyser#1049] opened 2020-07-29 06:31 UTC
**Describe the bug**

When a player joined to the server, the console may have a spam:
```
[14:22:32] [Network Listener - #1/WARN]: [Geyser-Spigot] 无法翻译数据包 InventoryTransactionPacket
java.lang.ArrayIndexOutOfBoundsException: 50
	at org.geysermc.connector.inventory.Inventory.getItem(Inventory.java:82) ~[?:?]
	at org.geysermc.connector.network.translators.inventory.action.InventoryActionDataTranslator.translate(InventoryActionDataTranslator.java:70) ~[?:?]
	at org.geysermc.connector.network.translators.inventory.BaseInventoryTranslator.translateActions(BaseInventoryTranslator.java:80) ~[?:?]
	at org.geysermc.connector.network.translators.inventory.CraftingInventoryTranslator.translateActions(CraftingInventoryTranslator.java:84) ~[?:?]
	at org.geysermc.connector.network.translators.bedrock.BedrockInventoryTransactionTranslator.translate(BedrockInventoryTransactionTranslator.java:67) ~[?:?]
	at org.geysermc.connector.network.translators.bedrock.BedrockInventoryTransactionTranslator.translate(BedrockInventoryTransactionTranslator.java:58) ~[?:?]
	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:94) ~[?:?]
	at org.geysermc.connector.network.UpstreamPacketHandler.translateAndDefault(UpstreamPacketHandler.java:45) ~[?:?]
	at org.geysermc.connector.network.UpstreamPacketHandler.defaultHandler(UpstreamPacketHandler.java:139) ~[?:?]
	at org.geysermc.connector.network.LoggingPacketHandler.handle(LoggingPacketHandler.java:167) ~[?:?]
	at com.nukkitx.protocol.bedrock.packet.InventoryTransactionPacket.handle(InventoryTransactionPacket.java:46) ~[?:?]
	at com.nukkitx.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:26) ~[?:?]
	at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:278) ~[?:?]
	at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:32) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:434) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:412) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:405) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:279) ~[?:?]
	at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
[14:22:32] [Network Listener - #1/WARN]: java.lang.ArrayIndexOutOfBoundsException: 50
[14:22:32] [Network Listener - #1/WARN]: 	at org.geysermc.connector.inventory.Inventory.getItem(Inventory.java:82)
[14:22:32] [Network Listener - #1/WARN]: 	at org.geysermc.connector.network.translators.inventory.action.InventoryActionDataTranslator.translate(InventoryActionDataTranslator.java:70)
[14:22:32] [Network Listener - #1/WARN]: 	at org.geysermc.connector.network.translators.inventory.BaseInventoryTranslator.translateActions(BaseInventoryTranslator.java:80)
[14:22:32] [Network Listener - #1/WARN]: 	at org.geysermc.connector.network.translators.inventory.CraftingInventoryTranslator.translateActions(CraftingInventoryTranslator.java:84)
[14:22:32] [Network Listener - #1/WARN]: 	at org.geysermc.connector.network.translators.bedrock.BedrockInventoryTransactionTranslator.translate(BedrockInventoryTransactionTranslator.java:67)
[14:22:32] [Network Listener - #1/WARN]: 	at org.geysermc.connector.network.translators.bedrock.BedrockInventoryTransactionTranslator.translate(BedrockInventoryTransactionTranslator.java:58)
[14:22:32] [Network Listener - #1/WARN]: 	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:94)
[14:22:32] [Network Listener - #1/WARN]: 	at org.geysermc.connector.network.UpstreamPacketHandler.translateAndDefault(UpstreamPacketHandler.java:45)
[14:22:32] [Network Listener - #1/WARN]: 	at org.geysermc.connector.network.UpstreamPacketHandler.defaultHandler(UpstreamPacketHandler.java:139)
[14:22:32] [Network Listener - #1/WARN]: 	at org.geysermc.connector.network.LoggingPacketHandler.handle(LoggingPacketHandler.java:167)
[14:22:32] [Network Listener - #1/WARN]: 	at com.nukkitx.protocol.bedrock.packet.InventoryTransactionPacket.handle(InventoryTransactionPacket.java:46)
[14:22:32] [Network Listener - #1/WARN]: 	at com.nukkitx.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:26)
[14:22:32] [Network Listener - #1/WARN]: 	at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:278)
[14:22:32] [Network Listener - #1/WARN]: 	at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:32)
[14:22:32] [Network Listener - #1/WARN]: 	at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307)
[14:22:32] [Network Listener - #1/WARN]: 	at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:434)
[14:22:32] [Network Listener - #1/WARN]: 	at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:412)
[14:22:32] [Network Listener - #1/WARN]: 	at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:405)
[14:22:32] [Network Listener - #1/WARN]: 	at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:279)
[14:22:32] [Network Listener - #1/WARN]: 	at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288)
[14:22:32] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[14:22:32] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[14:22:32] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
[14:22:32] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
[14:22:32] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[14:22:32] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[14:22:32] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
[14:22:32] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
[14:22:32] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
[14:22:32] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
[14:22:32] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
[14:22:32] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
[14:22:32] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
[14:22:32] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[14:22:32] [Network Listener - #1/WARN]: 	at java.lang.Thread.run(Unknown Source)
[14:22:33] [Network Listener - #1/WARN]: [Geyser-Spigot] 无法翻译数据包 InventoryTransactionPacket
java.lang.ArrayIndexOutOfBoundsException: 50
	at org.geysermc.connector.inventory.Inventory.getItem(Inventory.java:82) ~[?:?]
	at org.geysermc.connector.network.translators.inventory.action.InventoryActionDataTranslator.translate(InventoryActionDataTranslator.java:70) ~[?:?]
	at org.geysermc.connector.network.translators.inventory.BaseInventoryTranslator.translateActions(BaseInventoryTranslator.java:80) ~[?:?]
	at org.geysermc.connector.network.translators.inventory.CraftingInventoryTranslator.translateActions(CraftingInventoryTranslator.java:84) ~[?:?]
	at org.geysermc.connector.network.translators.bedrock.BedrockInventoryTransactionTranslator.translate(BedrockInventoryTransactionTranslator.java:67) ~[?:?]
	at org.geysermc.connector.network.translators.bedrock.BedrockInventoryTransactionTranslator.translate(BedrockInventoryTransactionTranslator.java:58) ~[?:?]
	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:94) ~[?:?]
	at org.geysermc.connector.network.UpstreamPacketHandler.translateAndDefault(UpstreamPacketHandler.java:45) ~[?:?]
	at org.geysermc.connector.network.UpstreamPacketHandler.defaultHandler(UpstreamPacketHandler.java:139) ~[?:?]
	at org.geysermc.connector.network.LoggingPacketHandler.handle(LoggingPacketHandler.java:167) ~[?:?]
	at com.nukkitx.protocol.bedrock.packet.InventoryTransactionPacket.handle(InventoryTransactionPacket.java:46) ~[?:?]
	at com.nukkitx.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:26) ~[?:?]
	at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:278) ~[?:?]
	at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:32) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:434) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:412) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:405) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:279) ~[?:?]
	at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
[14:22:33] [Network Listener - #1/WARN]: java.lang.ArrayIndexOutOfBoundsException: 50
[14:22:33] [Network Listener - #1/WARN]: 	at org.geysermc.connector.inventory.Inventory.getItem(Inventory.java:82)
[14:22:33] [Network Listener - #1/WARN]: 	at org.geysermc.connector.network.translators.inventory.action.InventoryActionDataTranslator.translate(InventoryActionDataTranslator.java:70)
[14:22:33] [Network Listener - #1/WARN]: 	at org.geysermc.connector.network.translators.inventory.BaseInventoryTranslator.translateActions(BaseInventoryTranslator.java:80)
[14:22:33] [Network Listener - #1/WARN]: 	at org.geysermc.connector.network.translators.inventory.CraftingInventoryTranslator.translateActions(CraftingInventoryTranslator.java:84)
[14:22:33] [Network Listener - #1/WARN]: 	at org.geysermc.connector.network.translators.bedrock.BedrockInventoryTransactionTranslator.translate(BedrockInventoryTransactionTranslator.java:67)
[14:22:33] [Network Listener - #1/WARN]: 	at org.geysermc.connector.network.translators.bedrock.BedrockInventoryTransactionTranslator.translate(BedrockInventoryTransactionTranslator.java:58)
[14:22:33] [Network Listener - #1/WARN]: 	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:94)
[14:22:33] [Network Listener - #1/WARN]: 	at org.geysermc.connector.network.UpstreamPacketHandler.translateAndDefault(UpstreamPacketHandler.java:45)
[14:22:33] [Network Listener - #1/WARN]: 	at org.geysermc.connector.network.UpstreamPacketHandler.defaultHandler(UpstreamPacketHandler.java:139)
[14:22:33] [Network Listener - #1/WARN]: 	at org.geysermc.connector.network.LoggingPacketHandler.handle(LoggingPacketHandler.java:167)
[14:22:33] [Network Listener - #1/WARN]: 	at com.nukkitx.protocol.bedrock.packet.InventoryTransactionPacket.handle(InventoryTransactionPacket.java:46)
[14:22:33] [Network Listener - #1/WARN]: 	at com.nukkitx.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:26)
[14:22:33] [Network Listener - #1/WARN]: 	at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:278)
[14:22:33] [Network Listener - #1/WARN]: 	at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:32)
[14:22:33] [Network Listener - #1/WARN]: 	at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307)
[14:22:33] [Network Listener - #1/WARN]: 	at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:434)
[14:22:33] [Network Listener - #1/WARN]: 	at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:412)
[14:22:33] [Network Listener - #1/WARN]: 	at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:405)
[14:22:33] [Network Listener - #1/WARN]: 	at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:279)
[14:22:33] [Network Listener - #1/WARN]: 	at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288)
[14:22:33] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[14:22:33] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[14:22:33] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
[14:22:33] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
[14:22:33] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[14:22:33] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[14:22:33] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
[14:22:33] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
[14:22:33] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
[14:22:33] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
[14:22:33] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
[14:22:33] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
[14:22:33] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
[14:22:33] [Network Listener - #1/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[14:22:33] [Network Listener - #1/WARN]: 	at java.lang.Thread.run(Unknown Source)
```
**To Reproduce**

1.Start my server
2.Let a player in
3.See the error

**Expected behavior**

No console spam

**Screenshots / Videos**

![批注 2020-07-29 142822.png](https://i.loli.net/2020/07/29/goHMNxvBWyQGs2X.png)

**Server Version**

This server is running Paper version git-Paper-123 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Geyser Version**

This server is running Geyser version 1.0.0 (git-master-fe75320) (Java: 1.16.1, Bedrock: 1.16.0)

**Minecraft: Bedrock Edition Version**

0.16.0

**Additional Context**

https://dump.geysermc.org/RwvMlRtTjnHVSSPaKhFcn1Dg0r4U19OZ

**Comment by rtm516** [comment] 2020-07-29 09:44
Duplicate of https://github.com/GeyserMC/Geyser/issues/1049

**Closed by rtm516** 2020-07-29 09:44 UTC
