### ISSUE TITLE
Can't go through nether portal without having to disconnect and reconnect to server

### ISSUE THREAD

**Issue by Meloooche** [GeyserMC/Geyser#3492] opened 2022-12-30 00:47 UTC
Every time I go through a nether portal on my friends java server I get stuck in this weird state where I am inside of blocks and cant move, the only way to fix this is if I disconnect and reconnect from the server. It's only a minor inconvenience but it gets quite annoying having to disconnect and then login again every time I want to go to the nether or the end.

**Comment by Camotoy** [comment] 2023-01-05 22:42
Duplicate of #3482 now. Thanks though!

**Closed by Camotoy** 2023-01-05 22:42 UTC
Labels: Duplicate
