### ISSUE TITLE
Advanced tooltips doesn't work correctly

### ISSUE THREAD

**Issue by AnhNguyenlost13** [GeyserMC/Geyser#2711] opened 2021-12-18 05:00 UTC
### Describe the bug

When enabling the advanced tooltips option on Geyser (/geyser tooltips), the item NBT and durability aren't displayed properly

### To Reproduce

1. Do "/geyser tooltips" on a Bedrock client
2. The item durability + NBT aren't displayed properly
![image](https://user-images.githubusercontent.com/94160753/146629612-aa67cc3e-5ddf-4955-9b93-96419c2a584c.png)

### Expected behaviour

The tooltips display correctly (durability, NBT tags)

### Server Version and Plugins

Server version: git-Paper-79 (1.18.1)
Plugins (7): BedrockPlayerManager, DiscordSRV, floodgate, Geyser-Spigot, SetHome, WEPatch, WorldEdit

### Geyser Dump

https://dump.geysermc.org/bXfbJBSxisrUDhFdupleXaYI5LUjibSy

### Geyser Version

2.0.0-SNAPSHOT (git-master-90442a8)

### Minecraft: Bedrock Edition Version

1.18.2.03

**Comment by Camotoy** [comment] 2021-12-18 05:00
Duplicate of confirmed bug #2706. Thank you for reporting anyway!

**Closed by Camotoy** 2021-12-18 05:00 UTC
