### ISSUE TITLE
`Downstream packet error! Failed to create tag` from ClientboundDisguisedChatPacket

### ISSUE THREAD

**Issue by Vaspei** [GeyserMC/Geyser#4347] opened 2023-12-18 17:46 UTC
### Describe the bug

Currently all bedrock players cannot see other players nor their own messages in chat and bedrock players experiencing extreme lag. None of this has ever happened to my server in the 12+ months of using geyser. Only started happened after updating to latest geyser version to support 1.20.4 versions. 

### To Reproduce

Cannot see your own messages nor other players' messages in chat on all bedrock devices and it's extremely laggy. Looks like failed packet translations

### Expected behaviour

To be able to see your own messages and other players' messages and it have a close to smooth experience with minimal lag or none at all

### Geyser Dump

https://dump.geysermc.org/qnV8ymLFmPQ7sPxm7vgipD4qfXYDh8eU

### Geyser Version

2.2.0-SNAPSHOT (git-master-58ff00d) (Java: 1.20.4, Bedrock 1.20.40/1.20.41-1.20.50/1.20.51

### Minecraft: Bedrock Edition Device/Version

1.20.40/1.20.41-1.20.50/1.20.51

### Additional Context

Debug mode
https://pastebin.com/aEb9xXXb

**Comment by Konicai** [comment] 2023-12-19 08:13
Also reported other people, but the cause is unknown in these cases:
- https://mclo.gs/ziTKnS2 (p.and.u_uriel)
- https://dump.geysermc.org/Xa6FscdrOdC0bWeIG9IHJcE46DhoejvR (foodplayz)

**Comment by onebeastchris** [comment] 2023-12-19 16:26
Please try updating velocity @Vaspei 
https://github.com/PaperMC/Velocity/commit/a54d8c681fe82eaa0e44e29888578597fa968c1b seems like there were some changes regarding tags, i could imagine that this might partially resolve it

**Comment by Vaspei** [comment] 2023-12-19 20:49
> Please try updating velocity @Vaspei [PaperMC/Velocity@a54d8c6](https://github.com/PaperMC/Velocity/commit/a54d8c681fe82eaa0e44e29888578597fa968c1b) seems like there were some changes regarding tags, i could imagine that this might partially resolve it

Okay, I've just done that and issue still persists

**Comment by Konicai** [comment] 2023-12-19 21:06
Yeah its not only velocity - eg the first log i attached above

**Comment by onebeastchris** [comment] 2024-01-30 09:40
@Vaspei are you using ViaVersion in your setup? If yes, try updating it to 4.9.3 (can be downloaded here: https://ci.viaversion.com/job/ViaVersion/)

**Comment by onebeastchris** [comment] 2024-02-17 20:51
Closing due to no further response.

**Closed by onebeastchris** 2024-02-17 20:51 UTC
Labels: Waiting On Response
