### ISSUE TITLE
Bucket of water is not working on mobile version. It works on Win 10.

### ISSUE THREAD

**Issue by Martoxdlol** [GeyserMC/Geyser#958] opened 2020-07-15 17:08 UTC
**Describe the bug**

On Android versión of MCBE water bucket cannot fill or put water.

**To Reproduce**
Use a bucket

**Expected behavior**

**Screenshots / Videos**

[Error water Geyser MCPE.zip](https://github.com/GeyserMC/Geyser/files/4926723/Error.water.Geyser.MCPE.zip)

**Server Version**

git-Spigot-0287a20-7560f5f (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Geyser Version**

Geyser 1.0.0 (git-master-e942d7c)

**Minecraft: Bedrock Edition Version**

1.16.1 02

**Additional Context**

https://dump.geysermc.org/3tUjihoc28PrK4OywHciaexC7BAai94F

**Comment by rtm516** [comment] 2020-07-15 17:10
Thanks for the report, but this is a duplicate of #321 and we have a WIP PR #767

**Closed by rtm516** 2020-07-15 17:10 UTC
