### ISSUE TITLE
Player Weather not changing from Raining to Sunny/Clear

### ISSUE THREAD

**Issue by DuneSciFye** [GeyserMC/Geyser#3686] opened 2023-04-19 19:51 UTC
### Describe the bug

If you set your playerweather to rainy from sunny, it works, but if you try to go to sunny from rainy, it stays rainy.

### To Reproduce

1. Set playerweather to rainy
2. Try to set it back to sunny

### Expected behaviour

It should set it back to sunny

### Geyser Version

Geyser-Velocity (2.1.0-SNAPSHOT (git-master-6ec7326))

**Comment by onebeastchris** [comment] 2023-04-19 21:09
likely duplicate of https://github.com/GeyserMC/Geyser/issues/3679

**Closed** 2023-04-19 22:11 UTC
