### ISSUE TITLE
Black Exlamation Mark Covering Up Screen

### ISSUE THREAD

**Issue by Giggybluf** [GeyserMC/Geyser#2370] opened 2021-07-11 17:05 UTC
### Describe the bug

whenever a bedrock player hits the air or is too far from a block to interact with, a black exclamation mark covers up a large part of the screen, i haven't seen any other issues similar to that one reported so i do not know if i am the only one experiencing this bug.

### To Reproduce

1. Hit the air or the sky 

### Expected behaviour

the apparition of a black exclamation mark that covers up a large part of the screen and then goes away after a few seconds

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/87275837/125203875-3011d400-e283-11eb-8d6e-8beaebbc9045.png)

### Server Version and Plugins

no plugins other than geyser and floodgate
Using paper 1.17.1

### Geyser Version

Geyser-Spigot v1.4.0-SNAPSHOT

**Comment by Konicai** [comment] 2021-07-11 17:11
As far as I know, the only consistent/reliable way to get rid of this is to set GUI opacity to 0% in the client to 0

**Comment by Camotoy** [comment] 2021-07-11 17:13
Duplicate of #1710. Thank you anyway for reporting!

**Closed by Camotoy** 2021-07-11 17:13 UTC
