### ISSUE TITLE
Bedrock unable to enchant with custom enchants.

### ISSUE THREAD

**Issue by L8-Alphine** [GeyserMC/Geyser#4547] opened 2024-04-04 14:02 UTC
### Describe the bug

Normally, before the GeyserMC updated for the latest 1.20 update, custom enchants from EcoEnchants was working via anvil for Bedrock players. Now it shows this when we try to use an anvil.

![image](https://github.com/GeyserMC/Geyser/assets/164806334/66c04be0-082e-460b-ba67-a9e0713378e7)

The follow is the the server status:
The Server is Network connected and the main Survival server is running

- Paper 1.20.1 (git-Paper-194)
- Geyser Bungeecord Version 2.2.2 (git-master-a9467cf)
- Floodgate Spigot 2.2.2 (git-master-7f38765)
- EcoEnchants (10.36.0)
- Eco (6.65.5)

Those the plugins and versions that is running that I believe are related to this bug.

### To Reproduce

1. Install and use 1.20.1 Paper (git-Paper-194)
2. Install Geyser Bungeecord Version 2.2.2 (git-master-a9467cf) on a bungeecord network
3. Install Floodgate Spigot 2.2.2 (git-master-7f38765) on the backend spigot server
4. Install EcoEnchants (10.36.0) on the spigot server
5. Install Eco (6.65.5) on the spigot server
6. Get a custom enchantment from EcoEnchants
7. Open up a bedrock account and log in
8. Use a tool and custom enchantment from EcoEnchants
9. Issue will be a red X telling you the combine is invalid when it's valid in Java

There is also another thing is that bedrock ONLY knows about the basic enchantments from the enchantment list in the creative menu.

### Expected behaviour

The custom enchantment should be able to apply to the item that the bedrock use is trying to enchant, this works from the enchantment table because it's server-side that enchants the item but this anvil issue is causing issues with the custom experience with my players.

### Geyser Dump

https://dump.geysermc.org/dQLmel9eGA34u3ix1Odqgt5PEizalMXE

### Geyser Version

Geyser Bungeecord Version 2.2.2 (git-master-a9467cf)

### Minecraft: Bedrock Edition Device/Version

ALL BEDROCK CLIENTS

**Comment by onebeastchris** [comment] 2024-04-04 14:15
https://github.com/GeyserMC/Geyser/issues/3121
Duplicate of the linked issue - custom enchantments, and anvils are unfortunately client-side on Bedrock.

**Closed by onebeastchris** 2024-04-04 14:15 UTC
