### ISSUE TITLE
Players Teleport Back when Moving Up Blocks

### ISSUE THREAD

**Issue by apieceofbaggage** [GeyserMC/Geyser#444] opened 2020-04-27 20:23 UTC
When changing the y-level while walking/running, Bedrock players get teleported back relatively often. This only occurs when moving up blocks (i.e. stairs, slabs, repeaters, snow layer), not when jumping or swimming. The error does not occur when moving down blocks.

**Steps too Reproduce**
1. Run
2. Change y-level by moving onto a block without jumping/swimming

**Expected behavior**
Not being teleported back

**Server Version**
CraftBukkit version git-Spigot-2040c4c-893ad93 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Geyser Version**
https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/90/
Build #90 (Apr 26, 2020, 7:24:21 AM)

**Minecraft: Bedrock Edition Version**
1.14.60

**Additional Context**
The other plugins installed do not seem to be causing any issues. Console occasionally gets the "player moved wrongly" alert, but not every time.

**Comment by RednedEpic** [comment] 2020-04-27 20:30
Duplicate of #204.

**Closed by RednedEpic** 2020-04-27 20:30 UTC
Labels: Duplicate
