### ISSUE TITLE
Quick crafting on ps4 kicked player to many packages send

### ISSUE THREAD

**Issue by kobenetwork** [GeyserMC/Geyser#1202] opened 2020-08-25 20:22 UTC
A player found this bug on the server and sended me video proof https://youtu.be/sKIOhFZi6dM. Do not have all details but it explains itself.

**Comment by RednedEpic** [comment] 2020-08-25 20:22
Duplicate of #1176. In the future, please follow the issue template and ensure that the bug you are reporting has not been reported yet.

**Closed by RednedEpic** 2020-08-25 20:22 UTC
