### ISSUE TITLE
issue on Velocity, players getting kicked sometimes when a bedrock player joins

### ISSUE THREAD

**Issue by shawn695** [GeyserMC/Geyser#4008] opened 2023-07-22 20:54 UTC
### Describe the bug

sometimes not all the time, when a bedrock player joins everyone in the servers get kicked with this 

"Main: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@63d02a5a
22.07 18:28:14 [Server] INFO com.velocitypowered.proxy.util.except.QuietRuntimeException: A packet did not decode successfully (invalid data). If you are a developer, launch Velocity with -Dvelocity.packet-decode-logging=true to see more."

full log of proxy showing when the geyser player joins and then everyone getting kicked afterwards
https://paste.gg/3f0cca1fb6dd4c7b8cc13884ea6f5f8a

### To Reproduce

happens randomly

### Expected behaviour

players not to get kicked when a geyser player joins

### Geyser Dump

https://dump.geysermc.org/KmnxdUmmmPBdQg2mW78XkcC6qLr1X873

### Geyser Version

b17191b

### Minecraft: Bedrock Edition Device/Version

1.20.11 clients

**Comment by onebeastchris** [comment] 2023-08-24 19:21
Duplicate of https://github.com/GeyserMC/Floodgate/issues/420, closing

**Closed by onebeastchris** 2023-08-24 19:21 UTC
Labels: Duplicate
