### ISSUE TITLE
"Downstream packet error" when entering portals on some server networks.

### ISSUE THREAD

**Issue by TylerJohnson177** [GeyserMC/Geyser#4203] opened 2023-10-09 05:07 UTC
### Describe the bug

I am working on creating a server network using the Waterfall proxy software for both Java and Bedrock players, and I created a lobby server that contains portals that transport players to the other servers on the network. The portals work perfectly for players playing on Java edition, but not for Bedrock edition players. I would say around 50% to 70% of the time a Bedrock player enters a portal, Geyser throws "Downstream packet error! Unregistered serverbound packet class: com.github.steveice10.mc.protocol.packet.ingame.serverbound.player.ServerboundMovePlayerRotPacket" and kicks the player from the network. This happens on both Geyser-Bungeecord (Build 327) and Geyser-Standalone (Build 327), I have not tested it on previous builds nor the Geyser-Spigot version. 

### To Reproduce

1. Join this server: 51.222.144.134:19132 (Pebblehost) with a bedrock client.
2. Attempt to enter the large portal.
3. The bug may not appear right away (Sometimes the portal works).
4. The bug is reproduced when the player gets kicked and an exception is displayed on the player's screen.

### Expected behaviour

When a Bedrock player enters the portal, the player should be transported to the other server on the network without getting kicked.  

### Screenshots / Videos

https://github.com/GeyserMC/Geyser/assets/80006547/10ca95aa-9189-49dc-9d2f-ec2f1990e018

### Server Version and Plugins

-Lobby Server-
PaperMC 1.20.1: Build 196

-Plugins-
Floodgate: Build 75
BungeeGuard: 1.3.3
SimplePortals: 1.7.3
WorldEdit-Bukkit: 7.2.16
ViaVersion: 4.8.1
ViaVersionAutoUpdate: 1.0
WorldGuard-Bukkit: 7.0.9
--------------------------------------
-Proxy-
Waterfall: Build 545

-Plugins-
Geyser-Bungeecord: Build 327
Floodgate: Build 75
GeyserUpdater: 1.6.3
HubMagic: 0.2.6
-------------------------------------
-Server the Portal is Connecting to-
PaperMC 1.20.1: Build 196

-Plugins-
Floodgate: Build 75
BungeeGuard: 1.3.3
ViaVersion: 4.8.1
ViaVersionAutoUpdate: 1.0
Themis: 0.15.1
Discord SRV: 1.26.2
IlegalStack: 2.9.2
ProtocolLib: 5.1.0

### Geyser Dump

https://dump.geysermc.org/4NtmSoj3tqc1i7kzy4u9WUD93KQokcoi

### Geyser Version

Geyser-Bungeecord: Build 327

### Minecraft: Bedrock Edition Device/Version

1.20.32 IOS, 1.20.32 Windows 10

### Additional Context

I am thinking that this issue may be tied to the SimplePortals plugin due to the rapid 180 degree rotation right before a player gets transported. Also, the issue seems to occur more often when the Bedrock player has higher ping, or when connecting via the Geyser-Standalone running on my local machine rather then the instance of Geyser running on the Waterfall proxy at Pebblehost.

**Comment by EpicJosch** [comment] 2023-10-11 17:22
I have the same issue

**Comment by EpicJosch** [comment] 2023-10-11 17:22
https://github.com/SpigotMC/BungeeCord/issues/3550

**Comment by EpicJosch** [comment] 2023-10-11 17:22
https://github.com/PaperMC/Waterfall/issues/822

**Comment by onebeastchris** [comment] 2023-10-11 17:24
Duplicate of https://github.com/GeyserMC/Geyser/issues/4191 - reason for closing that can be found [here](https://github.com/GeyserMC/Geyser/issues/4191#issuecomment-1753469120).

**Closed by onebeastchris** 2023-10-11 17:24 UTC

**Comment by Kas-tle** [comment] 2023-10-12 05:17
Hi, could you please see if the build artifacts from my PR resolve your issue?
https://github.com/GeyserMC/Geyser/actions/runs/6491305641

**Comment by TylerJohnson177** [comment] 2023-10-12 05:34
Yes, this fixed my issue. Thank you very much for getting this resolved.
