### ISSUE TITLE
Connect bedrock server through java editon

### ISSUE THREAD

**Issue by KaptanINO** [GeyserMC/Geyser#2673] opened 2021-12-06 08:51 UTC
### What feature do you want to see added?

Connecting Bedrock Editon servers through java edition.

### Are there any alternatives?

I searched but I found nothing.

**Comment by Jens-Co** [comment] 2021-12-06 09:10
Hello there, This is not something we are planning to create. Do know that there already a project (https://github.com/THEREALWWEFAN231/TunnelMC) which is an non active fabric mod. I will close this issue for now, thanks anyway:)

**Closed** 2021-12-06 09:11 UTC
Labels: Feature Request

**Comment by Chew** [comment] 2021-12-06 18:00
Also a duplicate of #2274
