### ISSUE TITLE
Translate "closeInventory" 

### ISSUE THREAD

**Issue by Grizzly90** [GeyserMC/Geyser#1527] opened 2020-11-11 13:59 UTC
**Describe the bug**
I need to close the Player Inventory via Spigot plugin. On java the Inventory is close properly using this function: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/HumanEntity.html#closeInventory()
But the bedrock client won't close the inventory if in gamemode creative

**To Reproduce**
1. install a plugin which uses closeInventory()
2. be in Gamemode Creative
3. trigger the function
4. Playerinventory stays opend

**Expected behavior**
Inventory gets closed

**Server Version**
CraftBukkit version git-Spigot-37d799b-bc6a175 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Geyser Version**
Geyser Version 1.1.0 (git-master-0e15aa7)

**Minecraft: Bedrock Edition Version**
1.16.40

**Comment by DoctorMacc** [comment] 2020-11-11 15:28
I'm closing this as a duplicate of #326. Thank you for reporting anyway!

**Closed by DoctorMacc** 2020-11-11 15:28 UTC
