### ISSUE TITLE
Falling blocks

### ISSUE THREAD

**Issue by PRO100KatYT** [GeyserMC/Geyser#2106] opened 2021-04-06 07:50 UTC
### Describe the bug

Motion of falling blocks is displayed incorrectly.

### To Reproduce

1. Get a command block
2. Type in the command block the command to summon a falling block (for example summon falling_block ~ ~1 ~ {BlockState:{Name:"minecraft:lapis_block"},Time:1,Motion:[0.0,1.0,0.0]}

### Expected behaviour

I expected the same appearance as on Java Edition.

### Screenshots / Videos

https://youtu.be/Yo0NPI0p01A

### Geyser Dump

https://dump.geysermc.org/Bv5sZLj1Cv7vEq9VlmSDYpxdAQ2dHH14

### Geyser Version

1.2.1-SNAPSHOT (git-master-86b2901)

### Minecraft: Bedrock Edition Version

1.16.210

**Comment by Camotoy** [comment] 2021-04-06 14:35
This is likely a duplicate of #2050; therefore I am closing. Regardless, thank you for the issue report!

**Closed by Camotoy** 2021-04-06 14:35 UTC
