### ISSUE TITLE
Saddled camels unmoveable/unrideable on bedrock

### ISSUE THREAD

**Issue by neeleshpoli** [GeyserMC/Geyser#3952] opened 2023-07-08 02:03 UTC
### Describe the bug

Cemals that have a saddle are not moveable at all when mounted. Works in Java edition on the same server and works in singleplayer on bedrock so it is most likely Geyser Issue.

To be clear, the camel can be saddled and can be mounted, you just can't move it at all.

Note: Server is running Fabric.

### To Reproduce

1. Start Fabric server with fabric-API, Geyser for Fabric, and floodgate.
2. Spawn a camel in creative, equip a saddle on it, mount it, and its unmoveable.

### Expected behaviour

The Camel should be moveable using W, A, S, and D.

### Server Version and Plugins

fabric-server-mc.1.20.1-loader.0.14.21-launcher.0.11.2

Mods:
fabric-API
floodgate
Geyser

### Geyser Dump

https://dump.geysermc.org/mNAZJRGlJzubQeXCJ8k5ebfayLLD69vZ

### Geyser Version

Geyser version 2.1.2-SNAPSHOT (git-master-872d7e3) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.0)

### Minecraft: Bedrock Edition Device/Version

v1.20.1, Windows 11

**Comment by onebeastchris** [comment] 2023-07-08 02:19
https://github.com/GeyserMC/Geyser/issues/3860 Duplicate of this issue, but thanks for reporting.

**Closed** 2023-07-08 02:19 UTC
Labels: Duplicate
