### ISSUE TITLE
Can't login if you logout in End

### ISSUE THREAD

**Issue by ad1tya2** [GeyserMC/Geyser#1569] opened 2020-11-20 08:33 UTC
**Describe the bug**
I have a problem where when bedrock edition players logout specifically in the end, they cant log back in.
I have the latest floodgate and geyser
I have a standalone geyser setup using floodgate which connects to a bungeecord network in which all servers have floodgate installed,
This only happens in the survival server,
In the other servers like skyblock and bedwars the problem is _not there_
This problem also seems to exist in older versions
**The hub and other servers work perfectly**, this seems like an issue related with just _**world_the_end**_
There seem to be no errors whatsoever in bungee or survival or geyser,
Except read timed out if you are patient enough to wait for 5 mins on "building terrain"

**To Reproduce**
1. make a survival server with hub and bungeecord
2. Use floodgate on all servers
3. login into the server and go to the end
4. logout
5. now relogin and try to connect to survival, you wont be able to connect - it will get stuck on the screen mentioned above

**Screenshots / Videos**
this is where the problem occurs the screen gets stuck at : -
![image](https://user-images.githubusercontent.com/74638765/99777191-f5163100-2b37-11eb-9230-5329857bd867.png)

**Server Version**
git-Paper-253 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT) [Survival]

**Geyser Version**
This server is running Geyser version 1.2.0-SNAPSHOT (git-master-4297215) (Java: 1.16.4, Bedrock: 1.16.100.60) [geyser]

**Minecraft: Bedrock Edition Version**
Client version 1.16.100.04 and 1.16.100.40 [tested with both]

**Additional Context**
https://dump.geysermc.org/HxOeWj9eTNz5gBwIdVyW1p4QY29U4Svu

git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:9c078b7:1539 by md_5 [bungeee]

https://mclo.gs/5aeCchd#L4449 [survival logs]

https://mclo.gs/R6Rrfxk [geyser logs]

**Comment by rtm516** [comment] 2020-11-20 10:07
Please follow the issue template. Once you have made these changes we can reopen this issue.

**Comment by Hellohi3654** [comment] 2020-11-24 11:41
Can confirm this bug exists

**Comment by Hellohi3654** [comment] 2020-11-24 11:43
If a player dies in the end 90% of the time they will crash then they are unable to log back in 
The only way I found to fix this issue is to back up the players inventory and echest the delete there player data
You can't tp them back to the overworld because they haven't respawned yet

**Comment by ad1tya2** [comment] 2020-11-24 13:52
Basically @Hellohi3654 You tried to tell your players to not logout in the end, but when they end up dying they have to logout and the aforementioned glitch occurs

**Comment by Hellohi3654** [comment] 2020-11-24 13:56
Well yeah when they die in the end for some reason they crash then they can't join back because their in the end and I can't teleport them back to the overworld because they haven't respawned yet

**Comment by ad1tya2** [comment] 2020-11-24 14:04
Can you test what happens if they logout in the end? (without dying ofc)

**Comment by Hellohi3654** [comment] 2020-11-24 14:05
Well not now but I'm pretty sure they won't be able to log back in

**Comment by DoctorMacc** [comment] 2020-11-28 00:41
Does this issue still persist? I'm unable to reproduce with Paper + BungeeCord, but I'm not using Floodgate.

**Comment by Hellohi3654** [comment] 2020-11-28 02:49
Try using floodgate

**Comment by Hellohi3654** [comment] 2020-11-28 02:49
Also try killing the player in the end then leaving instead of respawning

**Comment by DoctorMacc** [comment] 2020-11-28 03:13
I've done the latter.

**Comment by DoctorMacc** [comment] 2020-11-28 03:39
No change with Floodgate installed just on BungeeCord.

**Comment by ad1tya2** [comment] 2020-11-28 05:19
Wait i will get back to you

**Comment by ad1tya2** [comment] 2020-11-28 06:07
@DoctorMacc I Switched to bungeecord version of Geyser and its working flawlessly now without a hitch, huh
Well Should i close the ticket?

**Comment by Hellohi3654** [comment] 2020-11-30 06:29
why was this closed this is still an issue for me

**Comment by Hellohi3654** [comment] 2020-11-30 06:30
must be caused by something else

**Comment by Hellohi3654** [comment] 2020-11-30 09:42
if you would like to see the issue join my server
IP: hellohi3654.wither.host
Port: 19179
for both java and bedrock
then just ask where the end portal is

**Comment by DoctorMacc** [comment] 2020-11-30 15:47
I know you use your own fork, so you should verify that A: you're up-to-date with master, B: it doesn't happen with a master build.

**Comment by Hellohi3654** [comment] 2020-11-30 21:09
I will test this afternoon
I originally thought it was just an issue with my branch but after I heard that someone using the master branch had the same issue I figured it wasn't my branch

**Comment by Hellohi3654** [comment] 2020-12-01 08:55
I downloaded the standalone version from https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/
and I joined my bungee cord network went into another server then went to the end and logged out
and the glitch occured
https://dump.geysermc.org/lNr2H5C7Yy4xKrxuVYMOnrZtdMQNzHmD

**Comment by Hellohi3654** [comment] 2020-12-01 08:58
I think it's something to do with how the end loading screen comes up when transferring to another server on bungeecord
Because if you left in the overworld or the nether it would show the end loading screen then go to the loading screen of that dimension 
But because the loading screen is just changing to itself again it somehow breaks and doesn't ever load

**Comment by ad1tya2** [comment] 2020-12-01 10:00
@Hellohi3654 easy way to solve this is by using the bungeecord plugin version!
I simply shifted to that.

**Comment by Hellohi3654** [comment] 2020-12-01 10:02
The issue still happens on the plugin version as well

**Comment by ad1tya2** [comment] 2020-12-01 10:33
@Hellohi3654 are you using the updated version?,
now i am beginning to think whoever couldn't play simply left my server

**Comment by Hellohi3654** [comment] 2020-12-01 10:45
yeah I tested today with the latest version

**Comment by Hellohi3654** [comment] 2020-12-13 12:47
I finally think I know how to reproduce this bug
Setup a bungeecord network and install geyser on the bungee server **make sure that build on nether roof is turned on in the config**
Then join the bungeecord network and go to the end
Either leave or die in the end then leave and try and rejoin the server

Not sure but I think this is how to accurately reproduce this bug

**Comment by Hellohi3654** [comment] 2020-12-13 12:53
because the nether is technically the end it glitches and stops the player from actually joining in the real end

**Comment by ad1tya2** [comment] 2020-12-13 15:02
@Hellohi3654 Yes i think thats it!

**Comment by Camotoy** [comment] 2020-12-16 19:07
@Hellohi3654 Perfect, thank you so much!

**Closed** 2021-01-04 00:06 UTC
Labels: Confirmed Bug
