### ISSUE TITLE
Bedrock players have bypass to wg

### ISSUE THREAD

**Issue by Z3r0xh** [GeyserMC/Geyser#5014] opened 2024-09-01 08:27 UTC
### Describe the bug

Some wg checks can be bypassed if you are a bedrock user. For example, in a protected area where users do not have access to open doors or trapdoors, geyser users can open them and go through them. Java users cannot do this, as when they try to open it, it closes automatically and they are taken back to the previous location.

### To Reproduce

Using wg protect an area and place a door.
If you are a java player, you will notice that you cannot open it and go through it.
If you are a bedrock player, you will be able to open it and go through it.

### Expected behaviour

They should not be able to pass through the door in a protected area

### Screenshots / Videos

https://youtu.be/LYtu6GIrH_k

### Server Version and Plugins

server is running UniverseSpigot version 1.21.1-DEV-ver/1.21.1@4a8025b (2024-08-30T06:50:00Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
Universe-1.21.1-DEV-4a8025b (MC: 1.21.1)

### Geyser Version

Geyser version 2.4.2-b661 (git-master-8935b34) (Java: 1.21, Bedrock: 1.20.80/1.20.81 - 1.21.20/1.21.21)

### Minecraft: Bedrock Edition Device/Version

last version

**Comment by onebeastchris** [comment] 2024-09-01 08:37
Duplicate of https://github.com/GeyserMC/Geyser/issues/2819 - Thanks anyways for reporting.

**Closed by onebeastchris** 2024-09-01 08:37 UTC

**Comment by Z3r0xh** [comment] 2024-09-01 08:58
> Duplicate of #2819 - Thanks anyways for reporting.

Is there any possible solution at the moment? Since I see that it is a problem that has existed for quite some time

**Comment by onebeastchris** [comment] 2024-09-01 09:02
there is, look at the comments on that issue

**Comment by Z3r0xh** [comment] 2024-09-01 09:05
> there is, look at the comments on that issue

I just tried the geyser-interaction-fix, it doesn't work well. When you open the door it does send you back for 1 second, but the door stays open.
