### ISSUE TITLE
chunks not rendering

### ISSUE THREAD

**Issue by rorychatt** [GeyserMC/Geyser#4678] opened 2024-05-19 21:22 UTC
### Describe the bug

So over the past few versions, mobile and Windows devices while connected to geyser server experience problems with chunk rendering, for example, when riding a boat

We can see that block wireframes are there, but chunks are not rendering as game thinks player stands in a different spot.

### To Reproduce

1. Join server running latest Geyser plugin
2. Fly for some time, or use a boat as a passenger and swim for some time

### Expected behaviour

We expect the chunks to load properly

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/40919111/716930ed-0089-40c4-b937-63e321de8905)
![image](https://github.com/GeyserMC/Geyser/assets/40919111/15043047-1397-430c-9a7d-60b809ff2653)

### Server Version and Plugins

Paper Version: git-Paper-37 (MC: 1.20.6)

### Geyser Dump

https://dump.geysermc.org/Tvt2pXxuwxejeEwpMCSKA45EtVXxZIZv

### Geyser Version

2.3.1-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.20.81

**Comment by timelord1102** [comment] 2024-05-23 23:42
Having the same issue on fabric

**Comment by LuckserSky34** [comment] 2024-06-19 00:34
+1

**Comment by onebeastchris** [comment] 2024-06-22 21:39
Hello! Can you try the builds here and see if it fixes your issue? https://github.com/GeyserMC/Geyser/actions/runs/9607076730

**Comment by onebeastchris** [comment] 2024-07-04 16:18
Closing - this issue is a duplicate of https://github.com/GeyserMC/Geyser/issues/3809. Thanks for reporting!

**Closed by onebeastchris** 2024-07-04 16:18 UTC

**Comment by UnbeatenPlayzYT** [comment] 2025-01-04 17:22
> Hello! Can you try the builds here and see if it fixes your issue? https://github.com/GeyserMC/Geyser/actions/runs/9607076730

Wdym?
