### ISSUE TITLE
different weather in bedrock and java

### ISSUE THREAD

**Issue by Axel-prog** [GeyserMC/Geyser#4388] opened 2024-01-12 21:27 UTC
### Describe the bug

different weather in bedrock and java

### To Reproduce

wait for a "natural" rain when the weather cycle is off

bug does not appear when using commands

### Expected behaviour

Same weather in both versions

### Screenshots / Videos

![Screenshot (159)](https://github.com/GeyserMC/Geyser/assets/74259444/e964c7c2-afb0-4046-994d-1790d0565256)

### Server Version and Plugins

The server is running Minecraft Java 1.20.4

Plugins:

Viaversion
Viabackwards
Skript
Protocolib
Geyser
Geyserskinmaneger
Changeskin
Display name v2.2

### Geyser Dump

https://dump.geysermc.org/9Xtp1iV3i3bwMoPkR268scSFGpwmbqmL

### Geyser Version

2.2.0-SNAPSHOT (git-master-46bde0c)

### Minecraft: Bedrock Edition Device/Version

1.20.51 Minecraft bedrock Windows edition (Windows: 11)

### Additional Context

It would be useful for lightning traps but if not possible it's ok

**Comment by RinTheWeeb** [comment] 2024-01-15 18:50
I have the same issue. Weather from Java version is not synced to Bedrock users.

**Comment by onebeastchris** [comment] 2024-02-17 20:47
Closing, since this is a duplicate of a confirmed bug (#3679). Thanks anyways for reporting!

**Closed by onebeastchris** 2024-02-17 20:47 UTC
