### ISSUE TITLE
Geyser-Bungeecord error spams at console

### ISSUE THREAD

**Issue by vijaypondini** [GeyserMC/Geyser#2380] opened 2021-07-13 20:17 UTC
### Describe the bug

After updating to the latest geyser, latest waterfall, latest everything, the proxy spams my console with a variety of errors, absolutely unknown to me
https://mclo.gs/wZwscJg

### To Reproduce

1. Get a proxy with geyser-bungeecord as well as floodgate-bungeecord 
2. Setup a backend server as well
3. Connect to it on bedrock
4. You'll notice errors spamming over the console as you're plauing

### Expected behaviour

You shouldn't get errors in the console

### Server Version and Plugins

1.17 Latest waterfall, plugins are shown in geyser dump

### Geyser Dump

https://dump.geysermc.org/cZPfjW4vPXnofY1mnbok9rnQKkH8rqup

### Geyser Version

>....[01:46:42 INFO]: This server is running Geyser version 1.4.1-SNAPSHOT (git-master-f7ef902) (Java: 1.17.1, Bedrock: 1.17.0 

### Minecraft: Bedrock Edition Version

Bedrock 1.17.10

### Additional Context

Just read through the logs files, I hope that should do the most for you https://mclo.gs/wZwscJg

**Comment by Camotoy** [comment] 2021-07-13 22:13
Fixed with b2619fa.

**Closed by Camotoy** 2021-07-13 22:13 UTC

**Comment by vijaypondini** [comment] 2021-07-13 22:36
`[04:04:52 INFO] [floodgate]: Floodgate player logged in as _Phobetor1687 joined (UUID: 00000000-0000-0000-0009-01fbc3122541)
[04:04:52 INFO] [Geyser-BungeeCord]: Registering bedrock skin for _Phobetor1687 (00000000-0000-0000-0009-01fbc3122541)
[04:04:52 WARN]: Error dispatching event PostLoginEvent(player=_Phobetor1687) to listener com.djrapitops.extension.FloodgateBungeeListener@4f4a7083
java.lang.LinkageError: loader constraint violation: when resolving interface method 'org.geysermc.floodgate.util.LinkedPlayer org.geysermc.floodgate.api.player.FloodgatePlayer.getLinkedPlayer()' the class loader net.md_5.bungee.api.plugin.PluginClassloader @78c1372d of the current class, com/djrapitops/extension/FloodgateBungeeListener, and the class loader net.md_5.bungee.api.plugin.PluginClassloader @73ba6fe6 for the method's defining class, org/geysermc/floodgate/api/player/FloodgatePlayer, have different Class objects for the type org/geysermc/floodgate/util/LinkedPlayer used in the signature (com.djrapitops.extension.FloodgateBungeeListener is in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @78c1372d, parent loader 'app'; org.geysermc.floodgate.api.player.FloodgatePlayer is in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @73ba6fe6, parent loader 'app')
        at com.djrapitops.extension.FloodgateBungeeListener.onLogin(FloodgateBungeeListener.java:62) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:48) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:549) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at java.lang.Thread.run(Thread.java:831) [?:?]
`

This is the only remaining error, which I think has to do with player skins. Related to loading custom skins on floodgate ^

**Comment by Camotoy** [comment] 2021-07-13 22:38
That wouldn't have been caused by the 1.17.10 update. Did you shade in the API for Floodgate into your plugin by chance?

**Comment by vijaypondini** [comment] 2021-07-13 22:40
There's no plugin available on the proxy that interacts with floodgate api, however there is a plugin that uses forms api at backend, floodgate-spigot. However it's not anything skin related. I'll be sure to review with the plugin developer of this forms plugin about it too

**Comment by Camotoy** [comment] 2021-07-13 22:40
`com.djrapitops.extension.FloodgateBungeeListener` sure seems like there's a plugin listening to Floodgate on the proxy.
