### ISSUE TITLE
Fire doesn't actually go away

### ISSUE THREAD

**Issue by haloflooder** [GeyserMC/Geyser#1532] opened 2020-11-13 17:04 UTC
**Describe the bug**

When you try to extenguish fires on a bedrock client. The fire is gone from the client but the fire still exists on the java server. So you can just step into fire and die from it even though the fire is not visible on the client.

**To Reproduce**

1. Try to extinguish fire on bedrock client
2. On a java client, you can still see the fire

**Expected behavior**

The fire should be extinguished on the java server.

**Screenshots / Videos**

### Java
![image](https://i.imgur.com/XsLaLa0.png)
![image](https://i.imgur.com/VuPvwbI.png)

### Bedrock
![image](https://i.imgur.com/J7dGaQC.png)
![image](https://i.imgur.com/eWSp1W3.png)

**Server Version**

Tuinity 1.16.3 (88a2c88)

**Geyser Version**

git-master-e00715c

**Minecraft: Bedrock Edition Version**

1.16.40

**Additional Context**

**Comment by DoctorMacc** [comment] 2020-11-13 17:05
Is cache chunks enabled?

**Comment by rtm516** [comment] 2020-11-13 17:05
Can you check you have `chunk-caching` enabled? Also, could you provide a dump?

**Comment by haloflooder** [comment] 2020-11-13 17:06
Cache chunks are not enabled.

And here's the dump.
https://dump.geysermc.org/Tt3eLK0NZR4kKHhiTb41ciRXJ3c4QZY0

**Comment by DoctorMacc** [comment] 2020-11-13 17:07
I believe we have a fix for this but it requires cache chunks enabled. If you're able to, try enabling that and see if the problem is solved.

**Comment by haloflooder** [comment] 2020-11-13 17:17
Works fine after I enabled cache chunks

**Comment by DoctorMacc** [comment] 2020-11-13 17:18
Great. If I am correct, this is the only way to solve the problem, so I'll be closing this as we can't fix it any other way. Let us know how cache chunks performs!

**Closed by DoctorMacc** 2020-11-13 17:18 UTC
