### ISSUE TITLE
geyser and authlib can't work well together

### ISSUE THREAD

**Issue by happyeggchen** [GeyserMC/Geyser#2565] opened 2021-10-04 06:21 UTC
### Describe the bug

Can't login my JE server
JE server is using authlib

### To Reproduce

Enable online mode and authlib,login from be edition

### Expected behaviour

BE login normally

### Server Version and Plugins

server:git-Paper-295
plugins:FarmProtect*, Geyser-Spigot, ViaBackwards, ViaVersion

### Geyser Dump

https://dump.geysermc.org/8ROs0tB3fYfEI7xIQ3qdeLaXQ4fCf4ZO

### Geyser Version

1.4.3-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.17.32.02.apk

### Additional Context

[14:15:55 INFO]: [Geyser-Spigot] bluelakeORG 從 Java 伺服器中斷連線，原因為 java.lang.IllegalStateException: Cannot reply to EncryptionRequestPacket without profile and access token.
[14:15:55 WARN]: java.lang.IllegalStateException: Cannot reply to EncryptionRequestPacket without profile and access token.
[14:15:55 WARN]:  at Geyser-Spigot.jar//com.github.steveice10.mc.protocol.ClientListener.packetReceived(ClientListener.java:55)
[14:15:55 WARN]:  at Geyser-Spigot.jar//com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
[14:15:55 WARN]:  at Geyser-Spigot.jar//com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:146)
[14:15:55 WARN]:  at Geyser-Spigot.jar//com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:332)
[14:15:55 WARN]:  at Geyser-Spigot.jar//com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:36)
[14:15:55 WARN]:  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[14:15:55 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:15:55 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:15:55 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:15:55 WARN]:  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[14:15:55 WARN]:  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[14:15:55 WARN]:  at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[14:15:55 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:15:55 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:15:55 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:15:55 WARN]:  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[14:15:55 WARN]:  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[14:15:55 WARN]:  at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[14:15:55 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:15:55 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:15:55 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:15:55 WARN]:  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[14:15:55 WARN]:  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[14:15:55 WARN]:  at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[14:15:55 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:15:55 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:15:55 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:15:55 WARN]:  at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[14:15:55 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:15:55 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:15:55 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:15:55 WARN]:  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[14:15:55 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:15:55 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:15:55 WARN]:  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[14:15:55 WARN]:  at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
[14:15:55 WARN]:  at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)
[14:15:55 WARN]:  at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)
[14:15:55 WARN]:  at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)
[14:15:55 WARN]:  at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[14:15:55 WARN]:  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[14:15:55 WARN]:  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[14:15:55 WARN]:  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[14:15:55 WARN]:  at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by Chew** [comment] 2021-10-04 06:28
This looks to be a duplicate of #2232. We're still looking into this issue, though. Thank you for reporting!

**Closed by Chew** 2021-10-04 06:28 UTC

**Comment by Chew** [comment] 2021-10-04 06:30
Never mind, I misinterpreted. You set offline mode in your geyser config, while you're server is online. Please switch Geyser's config back to online.
