### ISSUE TITLE
Downstream packet error after updating to new version of Geyser BungeeCord

### ISSUE THREAD

**Issue by DCE-114514** [GeyserMC/Geyser#3718] opened 2023-04-29 03:05 UTC
### Describe the bug

[10:03:08 WARN] [Geyser-BungeeCord]: 下游数据包错误! Cannot invoke "com.github.steveice10.mc.protocol.data.game.level.event.LevelEvent.ordinal()" because "this.event" is null
[10:03:09 WARN] [Geyser-BungeeCord]: 下游数据包错误! Cannot invoke "com.github.steveice10.mc.protocol.data.game.level.event.LevelEvent.ordinal()" because "this.event" is null
[10:03:10 WARN] [Geyser-BungeeCord]: 下游数据包错误! Cannot invoke "com.github.steveice10.mc.protocol.data.game.level.event.LevelEvent.ordinal()" because "this.event" is null
[10:03:11 WARN] [Geyser-BungeeCord]: 下游数据包错误! Cannot invoke "com.github.steveice10.mc.protocol.data.game.level.event.LevelEvent.ordinal()" because "this.event" is null
[10:03:12 WARN] [Geyser-BungeeCord]: 下游数据包错误! Cannot invoke "com.github.steveice10.mc.protocol.data.game.level.event.LevelEvent.ordinal()" because "this.event" is null
[10:03:13 WARN] [Geyser-BungeeCord]: 下游数据包错误! Cannot invoke "com.github.steveice10.mc.protocol.data.game.level.event.LevelEvent.ordinal()" because "this.event" is null
[10:03:14 WARN] [Geyser-BungeeCord]: 下游数据包错误! Cannot invoke "com.github.steveice10.mc.protocol.data.game.level.event.LevelEvent.ordinal()" because "this.event" is null
[10:03:15 WARN] [Geyser-BungeeCord]: 下游数据包错误! Cannot invoke "com.github.steveice10.mc.protocol.data.game.level.event.LevelEvent.ordinal()" because "this.event" is null
[10:03:16 WARN] [Geyser-BungeeCord]: 下游数据包错误! Cannot invoke "com.github.steveice10.mc.protocol.data.game.level.event.LevelEvent.ordinal()" because "this.event" is null
[10:03:17 WARN] [Geyser-BungeeCord]: 下游数据包错误! Cannot invoke "com.github.steveice10.mc.protocol.data.game.level.event.LevelEvent.ordinal()" because "this.event" is null
[10:03:18 WARN] [Geyser-BungeeCord]: 下游数据包错误! Cannot invoke "com.github.steveice10.mc.protocol.data.game.level.event.LevelEvent.ordinal()" because "this.event" is null
[10:03:19 WARN] [Geyser-BungeeCord]: 下游数据包错误! Cannot invoke "com.github.steveice10.mc.protocol.data.game.level.event.LevelEvent.ordinal()" because "this.event" is null

### To Reproduce

Beta version Bedrock Edition players enter

### Expected behaviour

null

### Server Version and Plugins

WaterFall 1.19-526
minimotd
SkinRestorer
AdbancedBan
AllMusic
AuthMeBungee
BungeeOluginManagerPlus
CMIB
FallBackServer
floodgate-bungee
Geyser-BungeeCord
HidePlugins
HuskHomes
JoinMessages-BC
TABv3.3.2
TrChat
Xconomy

### Geyser Dump

https://dump.geysermc.org/N8QzWI1u0rV1K1gifQQfRjBVvc0V9zqL

### Geyser Version

Build #95 2023/4/29

### Minecraft: Bedrock Edition Device/Version

1.19.81

### Additional Context

null

**Comment by ManifestJW** [comment] 2023-05-02 03:38
I'm seeing this error in my console too!

**Comment by onebeastchris** [comment] 2023-05-02 18:26
Duplicate of https://github.com/GeyserMC/Geyser/issues/3714

**Comment by Jens-Co** [comment] 2023-05-02 18:37
Closing due to duplicate Duplicate of #3714

**Closed by Jens-Co** 2023-05-02 18:37 UTC
