### ISSUE TITLE
Cauldrons with water don't render

### ISSUE THREAD

**Issue by AdyaGD** [GeyserMC/Geyser#835] opened 2020-06-28 18:59 UTC
**Describe the bug**
Cauldrons with water stay empty in bedrock edition

**To Reproduce**
1. Place a cauldron
2. Right click with water
3. The cauldron look empty

**Expected behavior**
Cauldron should have water in it

**Server Version**
This server is running CraftBukkit version git-Spigot-758abbe-2b00831 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Geyser Version**
Spigot, 46 Build

**Minecraft: Bedrock Edition Version**
Pocket Edition

**Comment by endevrr** [comment] 2020-06-29 20:24
Duplicate of #865

**Closed** 2020-06-29 20:25 UTC
