### ISSUE TITLE
Unable to upgrade tools properly 

### ISSUE THREAD

**Issue by Jim-m-y** [GeyserMC/Geyser#5137] opened 2024-11-09 14:34 UTC
### Describe the bug

Diamond tools cannot be upgraded to netherine using the smithing table

### To Reproduce

1. Try upgrading diamond armor to netherine 

### Expected behaviour

I shouldn't be able to upgrade armor or tools, but it's very strange since I can upgrade them, but many, if not hundreds, of people reported this error on my server.

### Screenshots / Videos

https://cdn.discordapp.com/attachments/1304263288690835497/1304263288892293262/IMG-20241107-WA00621.jpg?ex=6730bb98&is=672f6a18&hm=5f1419c4202ab9b7285e9ebb7f96254718053e6207dc37917aa23ded43b11224&

### Server Version and Plugins

>....[14:21:10 INFO]: Este servidor está ejecutando la versión Geyser 2.5.0-b711 (git-master-4598ffe) (Versión Java: 1.21.3, Versión Bedrock: 1.20.80/1.20.81 - 1.21.40 - 1.21.44)

### Geyser Dump

https://dump.geysermc.org/Mk9eSbridEZpPgYOF3WXouCvqmHVYKCc

### Geyser Version

2.5.0-b711 (git-master-4598ffe) 

### Minecraft: Bedrock Edition Device/Version

All Device/Version

**Comment by Camotoy** [comment] 2024-11-09 22:01
Duplicate of #5126. Thank you for the report though!

**Closed by Camotoy** 2024-11-09 22:01 UTC
