### ISSUE TITLE
Bedrock plate material

### ISSUE THREAD

**Issue by StarYunmeng** [GeyserMC/Geyser#1101] opened 2020-08-08 15:00 UTC
I want to send different material packages to the computer version and the bedrock version

**Comment by Heath123** [comment] 2020-08-08 15:00
Firstly, please fill in the issue template. Secondly, what does "material packages" mean? Resource packs?

**Comment by StarYunmeng** [comment] 2020-08-08 15:01
Resource packs

**Comment by StarYunmeng** [comment] 2020-08-08 15:02
I want to send resource packs to my mobile phone

**Comment by RednedEpic** [comment] 2020-08-08 15:02
Duplicate of #210. Currently working on this in #1076.

**Comment by Heath123** [comment] 2020-08-08 15:03
(sort of) duplicate of #210, and you can already do this with the resources branch

**Comment by Heath123** [comment] 2020-08-08 15:03
This technically isn't a direct duplicate, because #210 is about passing through the Java resource pack

**Closed by RednedEpic** 2020-08-08 15:02 UTC
