### ISSUE TITLE
The viewing distance of the player, depends on the viewing distance of the server.

### ISSUE THREAD

**Issue by Levakiv** [GeyserMC/Geyser#2609] opened 2021-11-01 16:18 UTC
### Describe the bug

Player view distance depends on the view distance set on the server, not the client's settings.

### To Reproduce

1. chnage "view-distance" in server.properties.
2. Join server with any render distance
3. after login use spigot [Player#getClientViewDistance()](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.html#getClientViewDistance())
4. See that getClientViewDistance returned a value that does not match the player's viewing distance.
5. Change the viewing distance on the client side
6. after login use spigot [Player#getClientViewDistance()]
7. See that getClientViewDistance returned the same value as in step 3
8. Change the value in "view-distance" in server.properties to another
9. Restart server
10. Join server with any render distance
11. after login use spigot [Player#getClientViewDistance()](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.html#getClientViewDistance())
12. See what value to change with the change in viewing distance on the server

### Expected behaviour

The viewing distance depends on the player's viewing distance setting.

### Screenshots / Videos

view-distance=6 in server.properties.

Bedrock with render distance 8: ![Minecraft Screenshot 2021 11 01 - 18 23 04 94](https://user-images.githubusercontent.com/68151306/139696376-8a564198-e211-43f0-a982-e67c9ebae0ac.png)
Bedrock with render distance 64: ![Minecraft Screenshot 2021 11 01 - 18 25 02 35](https://user-images.githubusercontent.com/68151306/139696623-daf2f868-bd41-4fde-9bff-8e8710997031.png)

Java with render distance 8:  ![2021-11-01_18 08 52](https://user-images.githubusercontent.com/68151306/139694425-da81f7ab-40c3-408a-8ec3-56ccbc5b5cad.png)
Java with render distance 64: ![2021-11-01_18 09 44](https://user-images.githubusercontent.com/68151306/139694453-45952a7a-3c95-4604-8c5e-e7a205409a39.png)

### Server Version and Plugins

3272-Spigot-3892929-747a73e
Plugins:
floodgate-spigot  Build #41
Geyser-Spigot Build #921
info-1.0 https://www.dropbox.com/s/9lygod4f2kijk39/info-1.0.jar

### Geyser Dump

https://dump.geysermc.org/lLram8HvH6rxSXLUzT3Z4p1QwCMdxbl2

### Geyser Version

1.4.3-SNAPSHOT (git-master-96cbc54)

### Minecraft: Bedrock Edition Version

1.17.41

### Additional Context

If server.properties viewing distance in view-distance is set to 8, it will be 13. If 7, it will be 12.

**Comment by Camotoy** [comment] 2021-11-01 16:40
Duplicate of #1860. Thanks for reporting anyway!

**Closed by Camotoy** 2021-11-01 16:40 UTC
