### ISSUE TITLE
World Change error

### ISSUE THREAD

**Issue by Crypt97** [GeyserMC/Geyser#576] opened 2020-05-16 09:37 UTC
**Describe the bug**
When you die sometimes you stay in the Nether world dimension, so the sky is red, and then the Bedrock player is shown to the other players that he doesn't move, and that player can only visually see that he's moving, but he can't interact with anything because he's not there originally.

**To Reproduce**

1. /kill
2. If the Nether world is the fault
3. Try to carry away from animals or to take blockage

**Expected behavior**

**Screenshots / Videos**
http://prntscr.com/shu6fk

**Server Version**
This server is running Paper version git-Paper-267 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Geyser Version**
Geyser bukkit 
https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/152/

**Minecraft: Bedrock Edition Version**
1.14.60

**Additional Context**

**Comment by RednedEpic** [comment] 2020-05-17 05:06
> **Describe the bug**
> When you die sometimes you stay in the Nether world dimension, so the sky is red, and then the Bedrock player is shown to the other players that he doesn't move, and that player can only visually see that he's moving, but he can't interact with anything because he's not there originally.
> 
> **To Reproduce**
> 
> 1. /kill
> 2. If the Nether world is the fault
> 3. Try to carry away from animals or to take blockage
> 4. See error
> 
> **Expected behavior**
> 
> **Screenshots / Videos**
> http://prntscr.com/shu6fk
> 
> **Server Version**
> This server is running Paper version git-Paper-267 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
> 
> **Geyser Version**
> Geyser bukkit
> https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/152/
> 
> **Minecraft: Bedrock Edition Version**
> 1.14.60
> 
> **Additional Context**

Unable to reproduce, both with running /kill in the nether and the overworld. Is there any additional context here that may be useful in reproducing this?

**Comment by Crypt97** [comment] 2020-05-17 13:11
More info: https://youtu.be/gKG2oOyPIPQ

**Comment by TheMasterBlaster** [comment] 2020-05-17 14:28
I have noticed this issue when tping to a different world. It seems to happen at random.

**Comment by toinouH** [comment] 2020-07-30 14:11
@Crypt97 @TheMasterBlaster  Does this bug still exist?

**Comment by TheMasterBlaster** [comment] 2020-07-30 17:27
As I have stated before "It seems to happen at random.", but as of recently I have not noticed it.

**Comment by RednedEpic** [comment] 2020-12-12 00:59
Closing as no future reports of the issue have been reported. Additionally, the way we handle respawns has slightly changed in 1.16.x (Bedrock) and on our side of things, so it's likely that fixed the underlying issue here.

**Closed by RednedEpic** 2020-12-12 00:59 UTC
Labels: Confirmed Bug, Priority: Low
