### ISSUE TITLE
Bedrock players can walk through the world border

### ISSUE THREAD

**Issue by cfpwastaken** [GeyserMC/Geyser#2272] opened 2021-06-09 17:59 UTC
### Describe the bug

On servers that have a set border, bedrock players can't see them and even walk through them.

### To Reproduce

1. Set the worldborder center to find it better: `/worldborder center ~ ~`
2. Set the worldborder size down: `/worldborder set 3`
3. See the bug

### Expected behaviour

There should be a world border something preventing the user from going through.

### Screenshots / Videos

https://user-images.githubusercontent.com/44261356/121404842-a6f23f00-c95c-11eb-9926-fed7c875ae27.mp4

If you need more Videos / Screenshots just tell me.

### Server Version and Plugins

- Craftbukkit version 2991-Spigot-018b9a0-f3f3094 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) (39 versions behind)
- PermissionsEx, FAWE, Via*, WorldGuard, Multiverse-Core, BedWars
- I am not sure what version of BungeeCord it is exactly but it is the LaTeSt VeRsIoN (sorry I really don't know)

### Geyser Dump

https://dump.geysermc.org/THYxDoF3wCFbt0IOj1TDuyUrWgHvCGFe

### Geyser Version

1.4.0-SNAPSHOT (Java: 1.17, Bedrock: 1.17.0) (3 versions behind)

### Minecraft: Bedrock Edition Version

Late- 1.17.0

### Additional Context

Sorry about my (potentially) bad English

**Comment by Chew** [comment] 2021-06-09 18:05
Duplicate of #447. Thank you for reporting anyway!

**Closed by Chew** 2021-06-09 18:05 UTC
