### ISSUE TITLE
Moving honey blocks do not pull bedrock players with them

### ISSUE THREAD

**Issue by whakama** [GeyserMC/Geyser#2331] opened 2021-06-27 09:54 UTC
### Describe the bug

When using a honey block flying machine, bedrock players do not get pulled with it. They just slip off the honey blocks and fall to the ground.

### To Reproduce

1. Build a piston flying machine (like in this video: https://www.youtube.com/watch?v=RG6HiwpYeHk)
2. Stand on the honey block
3. The machine flies without you

### Expected behaviour

Bedrock players should get moved with the honey blocks like Java players do.

### Geyser Dump

https://dump.geysermc.org/yvLG7LaKzc809QxkVu3J7UHsEK6DK9Kh

### Geyser Version

1.4.0-SNAPSHOT (git-master-5b1d815) (Java: 1.17, Bedrock: 1.17.0)

### Minecraft: Bedrock Edition Version

1.17.0

**Comment by Camotoy** [comment] 2021-06-27 11:38
Closing as this is a duplicate of #2241. Thank you for reporting anyway!

**Closed by Camotoy** 2021-06-27 11:38 UTC
