### ISSUE TITLE
Buckets can’t be used

### ISSUE THREAD

**Issue by soshimee** [GeyserMC/Geyser#1293] opened 2020-09-15 09:46 UTC
**Describe the bug**

I can’t use buckets of any kind.

**To Reproduce**

Try using a bucket, it doesn’t work.

**Expected behavior**

Buckets working.

**Screenshots / Videos**

**Server Version**

This server is running Paper version git-Paper-191 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Geyser Version**

This server is running Geyser version 1.1.0 (git-master-6638c53) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.100)

**Minecraft: Bedrock Edition Version**

It was up-to-date but I do not know how to check it.

**Additional Context**

https://dump.geysermc.org/4nHrjZFz5VDRImbRnddEd2lG2zLarynW

**Comment by haloflooder** [comment] 2020-09-15 12:01
Can confirm on my side as well. Just noticed the issue when players were trying to farm and they were complaining that buckets weren't working properly.

**Comment by DoctorMacc** [comment] 2020-09-15 14:18
What platform are your players on?

**Comment by haloflooder** [comment] 2020-09-15 15:08
If you're talking to me.

Paper version git-Paper-134 (1.16.1)
Geyser version 1.1.0 (git-7cbfdcf52192479be2eda88cf6c3aae20b72fc05-7cbfdcf) (Java: 1.16.3, Bedrock: 1.16.20) (bungee plugin)

**Comment by DoctorMacc** [comment] 2020-09-15 15:09
I'm talking to everyone. I meant Bedrock client device, not platform, my bad!

**Comment by soshimee** [comment] 2020-09-15 15:19
Windows 10.

**Comment by haloflooder** [comment] 2020-09-15 15:28
Currently have win 10 and mobile users online but both platforms have the issue. Usually have xbox/ps4/switch players as well but none are online atm.

I tested myself on win 10 and mobile. Problem doesn't happen that often in win 10 but happens more often with mobile. So I'm guessing touch controls are making it glitchy because behavior is kinda weird.

**Comment by DoctorMacc** [comment] 2020-09-15 15:29
Yes, mobile players will have a tougher time because the bucket needs to be placed in the center of the screen. Could it only be a range thing? I think there's a window where Bedrock can place a bucket but Java won't accept it.

**Comment by soshimee** [comment] 2020-09-15 15:33
Also happens on iPadOS.

**Comment by soshimee** [comment] 2020-09-15 15:40
“ bucket needs to be placed in the center of the screen” Why? Bedrock players can place other blocks in other angles.

**Comment by DoctorMacc** [comment] 2020-09-15 15:41
Java limitations on how items are "used".

**Comment by soshimee** [comment] 2020-09-15 15:42
Hmm, can it be fixed in Geyser side?

**Comment by haloflooder** [comment] 2020-09-15 15:59
Wonder if geyser could make the player face the correct direction where the cursor wants to do the action.

**Comment by soshimee** [comment] 2020-09-16 08:13
I think they could.

**Comment by Comstepr** [comment] 2020-09-16 08:39
I have confirmed this bug

**Server Version**
This server is running Tuinity version git-Tuinity-"58fef63" (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Geyser Version**
This server is running Geyser version 1.1.0 (git-master-6638c53) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.100)

**Geyser Dump**
https://dump.geysermc.org/lRmvZLLqDEqpllgW5CuQ4RVNE0QSlMuq

**Device**
iOS

Unable to place water buckets anywhere, even by looking at where I want to place it.

**Comment by DoctorMacc** [comment] 2020-09-24 19:12
Should be fixed with #1311. If there's anything that is still broken please let us know!

**Closed by DoctorMacc** 2020-09-24 19:12 UTC
Labels: Confirmed Bug

**Comment by freekvh** [comment] 2020-10-04 08:56
I still have issues with water, since updating everything to latest [https://dump.geysermc.org/LdI4aOAPL82cp9nMvJD2VINKbWRfQQpZ](https://dump.geysermc.org/LdI4aOAPL82cp9nMvJD2VINKbWRfQQpZ) I can now sometimes place water but it just sits there, not flowing (I did this on sand btw), see here:

![schermshot](https://user-images.githubusercontent.com/12241293/95011231-8c2e3480-062f-11eb-8d0b-073ca5d2db3e.png)

**Comment by freekvh** [comment] 2020-10-04 14:21
Update: it does work as expected in survival, but not in creative.

**Comment by KJP12** [comment] 2021-01-03 07:30
This bug appears to still be present for mobile players in the form of the bucket taking from the center of the screen rather than anywhere that's on screen.

Here's the details of both the client and servers:
**Client**: Bedrock version 1.16.201, iPad 7, iOS 14.2

**Proxy**: Velocity 1.1.2 with Geyser 1.2.0-SNAPSHOT (git-master-396d1b6) and Floodgate 1.0-SNAPSHOT from November 16th, 2020 on the CI. *Cannot get more precise details as the command to dump Geyser information is inaccessible from in-game and Velocity's console input is inaccessible due to it being ran as a systemd unit. I can get the dump later if it is needed.*

**Server**: Fabric 1.16.4 server with FabricProxy-1.3.3.jar and crossstitch-0.1.2.jar installed.

**Initial server**: Tuinity 1.16.4 with Velocity support enabled. *This shouldn't matter, just putting this here in case it does.*

Video of the bug in action. https://streamable.com/paf8om

Do note, I'm reporting this on the behalf of someone else who doesn't want to create a Github account.
I don't have Bedrock edition on a mobile or touchscreen device at the ready to verify or help debug the issue. I do however manage the server this issue is occuring on.

**Comment by Camotoy** [comment] 2021-01-03 15:40
Yes, this is known and unfortunately a "can't fix" for the time being. The packet that Java wants for placing the bucket doesn't ask for a position and simply places the contents in the middle of the screen.
