### ISSUE TITLE
no visible bubble water

### ISSUE THREAD

**Issue by Crypt97** [GeyserMC/Geyser#571] opened 2020-05-15 20:18 UTC
**Describe the bug**
Drowning is not visible as no bubble appears or no sound can be heard in case of injury.

**Comment by RednedEpic** [comment] 2020-05-15 20:21
1) Please fill out the template _completely_ in the future
2) Please make sure that there is not already an open issue for this as this is a duplicate of #476.
3) Please make sure that there is not already an open pull request for this, as less than 10 minutes ago one was opened to fix this (see #569).

**Closed by RednedEpic** 2020-05-15 20:21 UTC
Labels: Duplicate, Invalid
