### ISSUE TITLE
Chance of random kicked for flying on join

### ISSUE THREAD

**Issue by Nerdtality** [GeyserMC/Geyser#74] opened 2019-11-04 00:06 UTC
Describe the bug
When joining the server, randomly you will be kicked from the server for flying.

Expected behavior
No kick

Server version
1.14.4

Geyser version
"SNAPSHOT 1"

Bedrock version
1.12.1

**Comment by Kasjuhh** [comment] 2019-11-04 08:30
This is most likely server sided

**Comment by Heath123** [comment] 2019-11-04 15:32
Yes, but Geyser is making the server think that the player is flying so it needs to be fixed in Geyser

**Comment by Nerdtality** [comment] 2019-11-08 05:29
During log and death, player will sometimes float. Also, if a player dies, the player can still be killed without clicking respawn. Guess that should be a second ticket? lol

**Comment by EOT3000** [comment] 2019-11-13 03:07
Redned, Geyser "Anticheat" shouldn't just check for too much movement, but should also floor the Y axis, if the client doesn't do that fast enough, the client isn't creative, and the client doesn't have fly mode enabled. Not at PC so I can't add this rn.

**Comment by EOT3000** [comment] 2020-01-22 19:41
I can confirm this bug!

**Comment by RednedEpic** [comment] 2020-01-24 00:21
> I can confirm this bug!
> 
> Happens randomly tho

This bug can happen due to a variety of things (poor internet, laggy server, laggy client, etc.). It could very well be due to Geyser, but it happens just as regularly for me as it does on a normal Java Edition client, thus why I set this as an unconfirmed bug.

If anyone else has any relevant information narrowing this down to Geyser, please include that in this issue as well as detailed information about what you were doing then (and perhaps a log). I would also recommend before reporting that adequate testing is done with the vanilla Java Edition client as well so it can be narrowed down better.

**Comment by Loganh4005** [comment] 2020-04-07 17:10
is spawn on stairs or slabs or was on spawn block bedrock placed?

**Comment by AnonAlpha** [comment] 2020-05-11 05:37
Think this will be fixed by teleport fix pr and the fix for issue #204

**Comment by DoctorMacc** [comment] 2020-05-11 13:50
We already added the teleport fix PR?

**Comment by carchrae** [comment] 2020-05-20 23:44
this happened to me several times, using minecraft pocket edition.  for some reason i was spawned on a cliff (and not at the setworldspawn point) so there is a good chance i was falling.  i was able to join eventually.

geyser+floodgate versions (git-master-83c7858) were downloaded today (a few hours before this log, PST)  on papermc (git-Paper-260 (MC: 1.15.2))

here is some log in case it is of use.

an aside, but awesome job on geyser.  with this lockdown, so awesome to connect my kids with their friends no matter what version they are running.  so a massive thank you.  

```
[14:29:34] [Network Listener - #1/INFO]: [Geyser-Bukkit] /***.***.***.***:45110 tried to connect!
[14:29:34] [Network Listener - #1/INFO]: [Geyser-Bukkit] Player connected with username username
[14:29:37] [Network Listener - #1/INFO]: [Geyser-Bukkit] Attempting to login using floodgate mode... authentication will be encrypted
[14:29:37] [Thread-20/INFO]: [Geyser-Bukkit] Loaded Floodgate key!
[14:29:37] [nioEventLoopGroup-7-1/INFO]: [Geyser-Bukkit] username (logged in as: username) has connected to remote java server on address 127.0.0.1
[14:29:37] [Netty Epoll Server IO #0/INFO]: [floodgate-bukkit] Added *username 00000000-0000-0000-000*-*************
[14:29:38] [Netty Epoll Server IO #0/INFO]: UUID of player *username is 00000000-0000-0000-000*-*************
[14:29:38] [nioEventLoopGroup-7-1/INFO]: [Geyser-Bukkit] Registering bedrock skin for *username (00000000-0000-0000-000*-*************)
[14:29:38] [nioEventLoopGroup-7-1/INFO]: [Geyser-Bukkit] Unable to load bedrock skin for '*username' as they are likely using a customised skin
[14:29:38] [Server thread/INFO]: *username joined the game
[14:29:38] [Server thread/INFO]: *username[/***.***.***.***:48598] logged in with entity id 2874 at ([world]-163.5, 67.0, -83.5)
[14:29:38] [Thread-21/INFO]: [Geyser-Bukkit] Spawned player at -163.5 67.0 -83.5
[14:29:43] [Server thread/WARN]: *username was kicked for floating too long!
[14:29:43] [Server thread/INFO]: *username lost connection: Flying is not enabled on this server
[14:29:43] [nioEventLoopGroup-7-1/INFO]: [Geyser-Bukkit] username has disconnected from remote java server on address 127.0.0.1 because of Flying is not enabled on this server
[14:29:43] [Server thread/INFO]: *username left the game
[14:29:43] [Server thread/WARN]: handleDisconnection() called twice
[14:30:14] [Network Listener - #1/INFO]: [Geyser-Bukkit] Bedrock user with ip: /***.***.***.*** has disconnected for reason CLOSED_BY_REMOTE_PEER
[14:30:31] [Network Listener - #1/INFO]: [Geyser-Bukkit] /***.***.***.***:45110 tried to connect!
[14:30:32] [Network Listener - #1/INFO]: [Geyser-Bukkit] Player connected with username username
[14:30:35] [Network Listener - #1/INFO]: [Geyser-Bukkit] Attempting to login using floodgate mode... authentication will be encrypted
[14:30:35] [Thread-22/INFO]: [Geyser-Bukkit] Loaded Floodgate key!
[14:30:35] [nioEventLoopGroup-8-1/INFO]: [Geyser-Bukkit] username (logged in as: username) has connected to remote java server on address 127.0.0.1
[14:30:35] [Netty Epoll Server IO #1/INFO]: [floodgate-bukkit] Added *username 00000000-0000-0000-000*-*************
[14:30:35] [Netty Epoll Server IO #1/INFO]: UUID of player *username is 00000000-0000-0000-000*-*************
[14:30:35] [nioEventLoopGroup-8-1/INFO]: [Geyser-Bukkit] Registering bedrock skin for *username (00000000-0000-0000-000*-*************)
[14:30:35] [nioEventLoopGroup-8-1/INFO]: [Geyser-Bukkit] Unable to load bedrock skin for '*username' as they are likely using a customised skin
[14:30:35] [Server thread/INFO]: *username joined the game
[14:30:35] [Thread-23/INFO]: [Geyser-Bukkit] Spawned player at -163.5 67.16559022918649 -83.5
[14:30:35] [Server thread/INFO]: *username[/***.***.***.***:48602] logged in with entity id 3033 at ([world]-163.5, 67.16559022918649, -83.5)
[14:30:41] [Server thread/WARN]: *username was kicked for floating too long!
[14:30:41] [Server thread/INFO]: *username lost connection: Flying is not enabled on this server
[14:30:41] [nioEventLoopGroup-8-1/INFO]: [Geyser-Bukkit] username has disconnected from remote java server on address 127.0.0.1 because of Flying is not enabled on this server
[14:30:41] [Server thread/INFO]: *username left the game
[14:30:41] [Server thread/WARN]: handleDisconnection() called twice
[14:31:22] [Network Listener - #1/INFO]: [Geyser-Bukkit] Bedrock user with ip: /***.***.***.*** has disconnected for reason CLOSED_BY_REMOTE_PEER
[14:32:35] [Network Listener - #1/INFO]: [Geyser-Bukkit] /***.***.***.***:45110 tried to connect!
[14:32:36] [Network Listener - #1/INFO]: [Geyser-Bukkit] Player connected with username username
[14:32:39] [Network Listener - #1/INFO]: [Geyser-Bukkit] Attempting to login using floodgate mode... authentication will be encrypted
[14:32:39] [Thread-24/INFO]: [Geyser-Bukkit] Loaded Floodgate key!
[14:32:39] [nioEventLoopGroup-9-1/INFO]: [Geyser-Bukkit] username (logged in as: username) has connected to remote java server on address 127.0.0.1
[14:32:39] [Netty Epoll Server IO #2/INFO]: [floodgate-bukkit] Added *username 00000000-0000-0000-000*-*************
[14:32:39] [Netty Epoll Server IO #2/INFO]: UUID of player *username is 00000000-0000-0000-000*-*************
[14:32:39] [nioEventLoopGroup-9-1/INFO]: [Geyser-Bukkit] Registering bedrock skin for *username (00000000-0000-0000-000*-*************)
[14:32:39] [nioEventLoopGroup-9-1/INFO]: [Geyser-Bukkit] Unable to load bedrock skin for '*username' as they are likely using a customised skin
[14:32:39] [Server thread/INFO]: *username joined the game
[14:32:39] [Thread-25/INFO]: [Geyser-Bukkit] Spawned player at -163.5 67.74613836357081 -83.5
[14:32:39] [Server thread/INFO]: *username[/***.***.***.***:48608] logged in with entity id 3353 at ([world]-163.5, 67.74613836357081, -83.5)
[14:32:43] [Server thread/WARN]: *username was kicked for floating too long!
[14:32:43] [Server thread/INFO]: *username lost connection: Flying is not enabled on this server
[14:32:43] [nioEventLoopGroup-9-1/INFO]: [Geyser-Bukkit] username has disconnected from remote java server on address 127.0.0.1 because of Flying is not enabled on this server
[14:32:43] [Server thread/INFO]: *username left the game
[14:32:43] [Server thread/WARN]: handleDisconnection() called twice
```

**Comment by DoctorMacc** [comment] 2020-09-22 03:59
Has this happened as of recent?

**Comment by pkcwong** [comment] 2020-09-30 12:00
I still observe this issue with Geyser build 411, logs similar to the one posted above.

**Comment by RednedEpic** [comment] 2021-05-21 23:21
Going to (finally) close this issue as the initial cause of it is no longer a problem. I understand that sometimes this may occur in situations such as Geyser lagging or the client being wonky. Unfortunately this issue here as it stands is too broad and any situation where you're kicked for flying is more likely a side effect of a totally separate issue.

**Closed by RednedEpic** 2021-05-21 23:21 UTC
Labels: More Info Needed, Unconfirmed Bug
