### ISSUE TITLE
Strider won't move when riding it

### ISSUE THREAD

**Issue by MagnoBooter** [GeyserMC/Geyser#1326] opened 2020-09-22 18:19 UTC
**Describe the bug**
You can saddle, mount and control the direction of a strider, but it doesn't move.

**To Reproduce**
1. Find a strider in the nether.
2. Saddle it.
3. Mount it while holding a warped-fungus-on-a-stick.
4. Try to move. Nothing happens.

**Expected behavior**
The strider should move in the direction you are looking.

**Screenshots / Videos**

**Server Version**
Paper version git-Paper-202 (MC: 1.16.3)

**Geyser Version**
1.1.0 (git-master-5fafa07), build #394

**Minecraft: Bedrock Edition Version**
1.16.40

**Additional Context**
[Geyser Dump](https://dump.geysermc.org/kO7WEkimT6XLBq7RTduspBbFC5lAsszF)

**Comment by DoctorMacc** [comment] 2020-09-22 18:20
This is a duplicate of #638. Thank you for reporting anyway!

**Closed by DoctorMacc** 2020-09-22 18:20 UTC
