### ISSUE TITLE
Block breaks much faster than in Java Edition

### ISSUE THREAD

**Issue by DoctaEnkoda** [GeyserMC/Geyser#2386] opened 2021-07-15 18:49 UTC
### Describe the bug

PS4 players (Actualy bug reported) break bedrock blocks much faster than Java Edition players.
Enchant pickaxe : Efficency 5 and beacon haste 2

### To Reproduce

1. Go on any server
2. Enchant pickaxe with efficency 5
3. Add beacon haste 2

### Expected behaviour

Players in Java Edition and Bedrock Edition should snapped at the same speed. 

### Screenshots / Videos

https://www.youtube.com/watch?v=-jdqaj0dNWI

### Server Version and Plugins

Proxy : 
[20:44:33 INFO]: Velocity 1.1.9
[20:44:33 INFO]: Copyright 2018-2021 Velocity Contributors. Velocity is licensed under the terms of the GNU General Public License v3.
=>.... [20:44:33 INFO]: Visit the Velocity website or the Velocity GitHub

Version Server: 
[20:45:17 INFO]: Checking version, please wait...
[20:45:19 INFO]: This server is running Purpur version git-Purpur-"a254471" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Unknown version
Previous version: git-Purpur-"b3b2976" (MC: 1.16.5)
(This branch: https://github.com/DoctaEnkoda/Purpur-SinonMC)

### Geyser Dump

https://dump.geysermc.org/mbZxlhpfIK7ASqjBSbPzUs4OaX6QGoAx

### Geyser Version

1.4.1-SNAPSHOT (git-master-ac9da9a) (Java: 1.17.1, Bedrock: 1.17.0 - 1.17.10)

**Comment by Camotoy** [comment] 2021-07-16 19:44
Looks like the core issue is a duplicate of #1621. Thank you anyway for reporting!

**Closed by Camotoy** 2021-07-16 19:44 UTC
