### ISSUE TITLE
Shields don't retract when attacking

### ISSUE THREAD

**Issue by pinkpig58** [GeyserMC/Geyser#2850] opened 2022-02-18 10:48 UTC
### Describe the bug

Just like on Java (and Bedrock Vanilla) shields should retract when using your weapon (or fist) so you can't block and hit at the same time.

### To Reproduce

1. Get a shield and weapon
2. Start using the weapon (or punch)

### Expected behaviour

The shield should retract when using the weapon, like this:

https://user-images.githubusercontent.com/41856020/154668253-4458bb05-db6a-4795-87af-d6b30cd8beb6.mp4

### Screenshots / Videos

This is what happens when using Geyser:

https://user-images.githubusercontent.com/41856020/154668380-0e3045d0-ada0-4a8b-9bbe-2b740cd2dd6a.mp4

### Geyser Dump

https://dump.geysermc.org/xu10HBInqy1kCnURU1PPPeqcbMleTN8b

### Geyser Version

2.0.1-SNAPSHOT (git-master-31fd57a)

### Minecraft: Bedrock Edition Version

1.18.12

**Comment by Konicai** [comment] 2022-02-18 14:07
duplicate of https://github.com/GeyserMC/Geyser/issues/1453

**Closed by Konicai** 2022-02-18 14:07 UTC
