### ISSUE TITLE
World loading caused by non-full chunks

### ISSUE THREAD

**Issue by SinanGentoo** [GeyserMC/Geyser#743] opened 2020-06-06 15:25 UTC
**Describe the bug**
When using WorldEdit or an explosion, the wrong chunk will appear around the edited block, but in fact it has not really disappeared

**To Reproduce**
1.Use WorldEdit to edit the world
2.Input //undo
3.The world has a loading error

**Expected behavior**
Able to fix this problem

**Screenshots / Videos**
![](https://i.niupic.com/images/2020/06/06/8exE.jpg)

**Server Version**
The latest Paper 1.15.2

**Geyser Version**
Merged non-full-chunk's latest master and original latest master 

**Minecraft: Bedrock Edition Version**
1.14.60

**Additional Context**
In fact, this problem also occurs with explosions, but not 100%. In addition, this problem occurs when the cache-chunk is turned on and off

**Comment by RednedEpic** [comment] 2020-06-09 01:16
Duplicate of #399.

**Closed by RednedEpic** 2020-06-09 01:16 UTC

**Comment by DoctorMacc** [comment] 2020-06-09 01:28
This issue happens with the non-full chunk branch, as stated. So it's still something that will need to fix, and should have been fixed with the non-full-chunk branch.
