### ISSUE TITLE
bedrock players not able to craft banners and are kicked during crafting 

### ISSUE THREAD

**Issue by bajamaster13** [GeyserMC/Geyser#4980] opened 2024-08-22 01:05 UTC
### Describe the bug

when players attempt to craft banners with any of the patterns it kicks them with an exception error of null id 8

### To Reproduce

1 be on a bedrock client connected to server
2 have the pattern, dye and banner of your choosing in loom 
3 go to get finished product from loom 
4 player gets kicked

### Expected behaviour

should be able to craft banner without kicking player 

### Geyser Dump

https://dump.geysermc.org/mZpSWsj5o2rQkYIBzI9JEHo6E3dd0uf

### Geyser Version

build#652

### Minecraft: Bedrock Edition Device/Version

1.21.20

**Comment by Camotoy** [comment] 2024-08-22 01:29
Duplicate of #4972. Thanks anyway!

**Closed by Camotoy** 2024-08-22 01:29 UTC
