### ISSUE TITLE
Action Bar issue even after Bungee fix

### ISSUE THREAD

**Issue by pinkpig58** [GeyserMC/Geyser#3024] opened 2022-06-08 17:56 UTC
### Describe the bug

I'm led to believe that BungeeCord fixed this in Build 1642, however I'm still having this issue using Geyser-Bungeecord and I'm wondering if there's a further issue.

As previously brought up in #3012 , action bars are sent in chat, when they shouldn't.
This **doesn't** happen on Java 1.19 clients, only Bedrock.

Build 1642: https://github.com/SpigotMC/BungeeCord/commit/5972fd23533648161c13b6e81ca769b7af398568

### To Reproduce

1. Create a Geyser-Bungeecord server
2. Add a plugin with the code (or similar) shown below
3. Connect on Bedrock
4. See the action bar be sent in chat

### Expected behaviour

The action bar should not be sent in chat.

### Screenshots / Videos

The code I'm running to create the action bar:

```
@EventHandler
public void onMove(PlayerMoveEvent e) {
      Player p = e.getPlayer();
      p.spigot().sendMessage(ChatMessageType.ACTION_BAR, new ComponentBuilder("test action bar").create());
}
```

### Server Version and Plugins

BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:ff5727c:1644

- ViaVersion-4.3.1
- Build 65 of Floodgate
- Build 1108 of Geyser-Bungeecord
- Small plugin only running the above code (on Spigot server)

### Geyser Dump

https://dump.geysermc.org/pGaHlUb5chf6ISP8WC1MDmh9fGMrjdq6

### Geyser Version

2.0.4-SNAPSHOT (git-master-78bb69b)

### Minecraft: Bedrock Edition Device/Version

1.19 - tested on Windows, iOS and Android

**Comment by RednedEpic** [comment] 2022-06-08 18:08
Duplicate of #3023.

**Closed by RednedEpic** 2022-06-08 18:08 UTC

**Comment by pinkpig58** [comment] 2022-06-08 18:11
Despite this being closed, I'll highlight that their issue wasn't in regards to Bungeecord - making clear that this is impacting both Spigot and Bungeecord versions of Geyser.
