### ISSUE TITLE
The camel bug 

### ISSUE THREAD

**Issue by Frank505Hartmann** [GeyserMC/Geyser#4313] opened 2023-11-26 22:42 UTC
### Describe the bug

Well I was playing with my teammates And we found a camel and when he got on Bedrock he couldn't control it since it was spinning non-stop and he couldn't control it.Since he didn't control it, he couldn't take the camel but I saw that in Java he could do it and it would be good to correct it.

### To Reproduce

Ride a camel from Bedrock with saddle 

### Expected behaviour

That the camel could be controlled from Bedrock 

### Server Version and Plugins

1.20.2

### Geyser Dump

https://dump.geysermc.org/vTc7MkIc6Yz2b9WedeoXlvZGdsGgPICz

### Geyser Version

Latest version currently on  26/11/23

### Minecraft: Bedrock Edition Device/Version

1.20.41.02

### Additional Context

I also saw that the horse jumps on Bedrock while you use it

**Comment by onebeastchris** [comment] 2023-11-26 23:04
Duplicate of https://github.com/GeyserMC/Geyser/issues/3860 - thanks anyways for reporting.

**Closed** 2023-11-26 23:04 UTC
