### ISSUE TITLE
Mapping for slimefun is error in lastet version

### ISSUE THREAD

**Issue by srlss123** [GeyserMC/Geyser#3397] opened 2022-11-13 05:46 UTC
### Describe the bug

Mapping for slimefun is error in lastet version
Mapping items is not Incorrect material in game 

### To Reproduce

1.Use cutsom-mapping
2.start geyser
3.join game use bedrock
4.No incorrect material

### Expected behaviour

correct material

### Screenshots / Videos

![QQ图片20221113134530](https://user-images.githubusercontent.com/78008410/201507799-385e840e-7aff-4bb9-ac39-d0ccf119aea5.jpg)

### Server Version and Plugins

MC version 1.19.2
Slimefun version Slimefun-v33a278c-canary

### Geyser Version

2.1.0-SNAPSHOT(build 1229)

### Minecraft: Bedrock Edition Device/Version

1.14.0 Windows 10

**Comment by SofiaRedmond** [comment] 2022-11-14 00:36
This can be fixed by unnesting the mappings, but it is a very big job and could take time to do. 

Anyway I would like to know if there is a way to fix it on Geyser's side.

**Comment by Camotoy** [comment] 2022-11-14 00:41
I'm confused on what's broken. Can you provide specific replication steps?

**Comment by SofiaRedmond** [comment] 2022-11-14 00:57
> I'm confused on what's broken. Can you provide specific replication steps?

It's about these mappings:
https://github.com/SofiaRedmond/Slimefun-Geyser/tree/main/GeyserCustomMappings/custom_mappings

It seems that Geyser is not able to manipulate correctly when the same item is in two different files, for example:

File A:
stick mapping 1

File B:
Stick mapping2

and mixes both mappings, resulting in the mixing of textures into items that do not correspond to them. I managed to solve this error momentarily by nesting the mappings in a single file.

File A:
Stick mapping 1 & 2

**Comment by Kas-tle** [comment] 2022-11-14 04:19
Geyser mirrors the behavior of java predicates. This means that the order of entires matters. When you spread the mappings for one item out across multiple files, the order in which these files are loaded in will not be consistent. As a result, this is not something that could really be "fixed" without doing something weird like having a config file to specify what order the mappings files should be loaded in... and at that point if your needs are that specific, you should probably be using an extension to register your items anyways... or just put the mappings in one file.

**Comment by srlss123** [comment] 2022-11-14 14:41
But in new version have this bug.....

**Comment by Camotoy** [comment] 2022-11-14 14:58
Yes, we added behavior in a newer version that changes the way this pack operates, and as a result, other things match vanilla Java behavior.

**Comment by SofiaRedmond** [comment] 2022-11-14 15:17
> Geyser mirrors the behavior of java predicates. This means that the order of entires matters. When you spread the mappings for one item out across multiple files, the order in which these files are loaded in will not be consistent. As a result, this is not something that could really be "fixed" without doing something weird like having a config file to specify what order the mappings files should be loaded in... and at that point if your needs are that specific, you should probably be using an extension to register your items anyways... or just put the mappings in one file.

Ok, thx i'll work on it.

**Comment by Camotoy** [comment] 2022-11-14 15:21
While we could definitely codify official behavior of the same mappings in different files, in this case I think this issue can be resolved as "works as intended". I would recommend having separate mappings files per item, which I don't see breaking anytime soon as per Kastle's comment.
Thanks.

**Closed by Camotoy** 2022-11-14 15:21 UTC
