### ISSUE TITLE
ModeEngine4 Support！

### ISSUE THREAD

**Issue by ximuya2** [GeyserMC/Geyser#4385] opened 2024-01-08 16:33 UTC
### Describe the bug

In Model Engine 4, even if you install resource packs on Bedrock players, they will not be able to see the physical mockups of custom monsters

### To Reproduce

Meg4

### Expected behaviour

Meg4

### Screenshots / Videos

none

### Geyser Version

latest

### Minecraft: Bedrock Edition Device/Version

1.20.51

### Additional Context

none

**Comment by onebeastchris** [comment] 2024-01-08 16:38
This boils down to Bedrock not supporting display and item entities - we plan to hack around that, but that requires a lot of work and is not something that's yet ready.
Closing, as it's essentially a duplicate of https://github.com/GeyserMC/Geyser/issues/3810 - thanks anyways for reporting.

**Closed by onebeastchris** 2024-01-08 16:38 UTC

**Comment by ximuya2** [comment] 2024-01-09 05:34
> This boils down to Bedrock not supporting display and item entities - we plan to hack around that, but that requires a lot of work and is not something that's yet ready. Closing, as it's essentially a duplicate of #3810 - thanks anyways for reporting.

Can you implement it before 1.21 is coming?

**Comment by onebeastchris** [comment] 2024-01-09 06:51
We don't provide eta's.
