### ISSUE TITLE
chunk loading error via geyser mc in bedrock!

### ISSUE THREAD

**Issue by Furiousmind** [GeyserMC/Geyser#4937] opened 2024-08-05 12:08 UTC
### Describe the bug

I have 1.21 bedrock minecraft installed in my pc . I used aternos to create my server. I have installed the latest version of minecraft and geyser mc through geyser mc . The version of geyser mc is 2.4.1-b634 , git-master-61ae5de. Everything is latest but I have chunk loading problem in playing my server. 
If there is anything that i can do then plz tell me.  I don't get the chunk problem immediately but after a while playing.
My render distance in game is 5 chunk.

### Expected behaviour

The chunk doesn't load all the 4 sides making shape like a square.

### Geyser Dump

https://dump.geysermc.org/JoXAqI9fRZcvnzZsTSkTzdN0XzIQF1Vk

### Geyser Version

git-master-61ae5de

### Minecraft: Bedrock Edition Device/Version

1.21.2

**Comment by onebeastchris** [comment] 2024-08-06 12:00
Closing - this is a likely duplicate of https://github.com/GeyserMC/Geyser/issues/3809

**Closed by onebeastchris** 2024-08-06 12:00 UTC
