### ISSUE TITLE
Can't ride camels

### ISSUE THREAD

**Issue by Zegery** [GeyserMC/Geyser#4948] opened 2024-08-07 18:15 UTC
### Describe the bug

When you try to ride a camel on Bedrock edition, you cannot move it.

### To Reproduce

1. Find a camel
2. Put a saddle on the camel
3. Try to move around while riding the camel.

### Expected behaviour

You should be able to move around on the camel.

### Screenshots / Videos

https://github.com/user-attachments/assets/e40bf5ae-0d0a-4ecf-9abf-43342c61d5a7

### Server Version and Plugins

Fabric 1.21

### Geyser Dump

https://dump.geysermc.org/GWuQNcix9f8skdsoYFO0mfZAgNdiWBDD

### Geyser Version

2.4.1-b633

### Minecraft: Bedrock Edition Device/Version

1.21.2 Windows

### Additional Context

Consoles also have the issue, it is Bedrock in general

**Comment by onebeastchris** [comment] 2024-08-07 19:52
Duplicate of https://github.com/GeyserMC/Geyser/issues/3860 - will be fixed soon. Join our discord to get a preview build that has the fix!

**Closed by onebeastchris** 2024-08-07 19:52 UTC
