### ISSUE TITLE
Bedwars Freezing

### ISSUE THREAD

**Issue by ilikestohack** [GeyserMC/Geyser#2901] opened 2022-03-22 19:57 UTC
### Describe the bug

When bedrock users are on my BedWars server and they are killed they freeze at the generating world screen. They can still see the world in the background of that generating screen covered with the red overlay like when you haven't respawned yet. The player still loads in on the java players / other players side meaning the java/other players can grab that players bed and kill them without having to fight more than one kill.

### To Reproduce

Create a server with bedwars1058 and Geyser-BungeeCord, connect two clients (one being tested may need to be a phone? Not sure if its only mobile clients or not yet. Try killing the test player once with the other client and then check the client to see if it is stuck (respawn if necessary) then kill the player again to see if they unfreeze.

### Expected behaviour

Player's clients are expected to be automatically spawned back into the game world.

### Server Version and Plugins

1.17.1 Plugin that runs the game is bedwars1058 open source and has other pluguns which do not seem to cause issues in other servers. 

### Geyser Dump

https://dump.geysermc.org/mmtPwdjbS6dhSwH63BGyBxLdxSIwIEg0

### Geyser Version

2.0.1-SNAPSHOT (git-master-559c5d6) (Java:  1.18 - 1.18.1, Bedrock: 1.17.40 - 1.18.10)

### Minecraft: Bedrock Edition Version

Pocket Edition at least

**Comment by seb303** [comment] 2022-04-07 07:30
We have the same problem.  When a bedrock player dies during a bedwars game (Mbedwars in this case), they get stuck and cannot control their player.  Killing their player a 2nd time (either in game or /kill) fixes the problem until they next get killed.

We've seen this sporadically with Xbox users, but every time with Nintendo Switch users.

1.17.1 Paper backend, behind Velocity (3.1.1) with:
ViaVersion 4.2.1
Geyser 2.0.2-SNAPSHOT 2022-04-01T20\:21\:47+0100
Floodgate 2.1.0-SNAPSHOT 2022-03-20T01\:03\:37+0000

**Comment by ruins22** [comment] 2022-05-05 16:39
Same issue occurs in our server using PVP Arena, when a bedrock player dies they are stuck on the generating world screen and are not able to respawn until the game is over. Can reproduce on multiple bedrock platforms. 

![78bc5b44268f8652d3266dbc52d9ee3f-png](https://user-images.githubusercontent.com/105007209/166970323-399d0219-97ef-4cbe-82a5-820b3520d56a.jpg)

1.18.2 Paper 
PVP Arena v1.15.2
Geyser 2.0.3 SNAPSHOT
Floodgate

**Comment by seb303** [comment] 2022-05-06 09:55
Try setting gamerule doImmediateRespawn.  This seemed to fix the problem in bedwars.

**Comment by ruins22** [comment] 2022-05-07 18:04
We already have tried setting the doImmediateRespawn gamerule both to true and to false, the issue occurs regardless of that.

**Comment by SunshroomChan** [comment] 2022-05-29 14:29
i have same problem like you guys and i reported it in the past but the creator of the plugin and some staff on Discord channel said they doesn't support for GeyserMC as Bedrock players

**Comment by SunshroomChan** [comment] 2022-05-29 14:31
But i don't know why ScreamingBedwars and Marcely's Bedwars doesn't have that stuck on loading screen, which is annoying for Bedrock players and maybe because this Bedwars plugin codebase they was used loading screen when being killed or died by void like that

**Comment by SunshroomChan** [comment] 2022-05-29 14:32
Even i tried remove world change loading screen plugin on Spigot just work when you change world but on being killed and died by void, it doesn't make you passed it

**Comment by LimeDev8756** [comment] 2022-06-01 18:25
I have had this issue for a while too, doesn't seem easy to fix too

**Comment by Jens-Co** [comment] 2022-08-10 02:35
Any updates about this issue?

**Comment by 63476-bomber** [comment] 2022-09-12 06:34
I found a solution for Marcely's bedwars but I think it works for other games too.  The fact is that many bedwars skip the death screen, which does not affect the geyser very well, therefore, in the config you can find "skip the death screen" you need to set it to false
![Uploading IMG_20220912_093408.png…]()

**Comment by 63476-bomber** [comment] 2022-09-12 06:37
![Uploading IMG_20220912_093408.png…]()

**Comment by Creeperz653** [comment] 2022-09-13 03:16
They aren’t using Marcely bedwars …

**Comment by SunshroomChan** [comment] 2022-09-13 03:44
> I found a solution for Marcely's bedwars but I think it works for other games too. The fact is that many bedwars skip the death screen, which does not affect the geyser very well, therefore, in the config you can find "death-skipscreen" you need to set it to false https://flic.kr/ps/3ZC973

Truely it was by Bedwars1058's codebase, compare to others doesn't have it

**Comment by SunshroomChan** [comment] 2022-09-13 03:46
> They aren’t using Marcely bedwars …

I used it once it fixed no more loading screen, the most problem is Bedwars1058 itself codebase, mostly how Andrei1058 he code it and i have reported this bug with screenshot https://github.com/andrei1058/BedWars1058/issues/598

**Comment by SunshroomChan** [comment] 2022-09-13 03:48
> I found a solution for Marcely's bedwars but I think it works for other games too. The fact is that many bedwars skip the death screen, which does not affect the geyser very well, therefore, in the config you can find "death-skipscreen" you need to set it to false https://flic.kr/ps/3ZC973

Please remind that on Java it have dirt screen on Bedwars1058 plugin but it fast because it just show for a less second while on Bedrock editionbeing delayed 5 second of it

**Comment by SunshroomChan** [comment] 2022-09-13 03:50
> I found a solution for Marcely's bedwars but I think it works for other games too. The fact is that many bedwars skip the death screen, which does not affect the geyser very well, therefore, in the config you can find "death-skipscreen" you need to set it to false https://flic.kr/ps/3ZC973

Death screen can be easily fixed on this plugin: https://www.spigotmc.org/resources/minimalist-instant-respawn.52321/
For older version you can download what version you want on Version History on that plugin page

**Comment by onebeastchris** [comment] 2023-06-11 00:40
Closing in favor of https://github.com/GeyserMC/Geyser/issues/3048

**Closed by onebeastchris** 2023-06-11 00:40 UTC
