### ISSUE TITLE
Save player credentials to simplify the login process.

### ISSUE THREAD

**Issue by JeriRyu** [GeyserMC/Geyser#1152] opened 2020-08-14 14:17 UTC
**What feature do you want?**
There should be an option of saving the players' login credentials, so they don't need to type the email and password every time. The plugin should be able help them to login automatically.

**Alternatives?**
Currently no alternatives.

**Comment by Heath123** [comment] 2020-08-14 14:19
Duplicate of #558

**Comment by Heath123** [comment] 2020-08-14 14:20
We don't intend to do this for security reasons, sorry

**Comment by DoctorMacc** [comment] 2020-08-14 14:22
There is an option to save logins in the config, however. But as said we won't do it for security reasons; thank you for asking anyway! Closing.

**Closed** 2020-08-14 14:22 UTC
