### ISSUE TITLE
Noisy issue when trying to join, bedrock players are recognized as if they were from Java

### ISSUE THREAD

**Issue by Dxzo** [GeyserMC/Geyser#4428] opened 2024-02-08 16:49 UTC
### Describe the bug

On some random occasions some bedrock players are recognized as if they were from Java. Floodgate does not assign the corresponding UUID.

### To Reproduce

1. Start the server
2. Log in and out of the server repeatedly with a Bedrock account until the error occurs

### Expected behaviour

The Bedrock player should always be recognized as such, as a Bedrock player and not a Java player.

### Screenshots / Videos

Full log here:

[geyserissue.txt](https://github.com/GeyserMC/Geyser/files/14212184/geyserissue.txt)

### Server Version and Plugins

This server is running Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)

### Geyser Dump

https://dump.geysermc.org/Nv1INc5HFvmQwUI0xZjWSEY9tb2zeWAp

### Geyser Version

This server is running Geyser version 2.2.2-SNAPSHOT (git-master-63fd97a) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.60/1.20.61)

### Minecraft: Bedrock Edition Device/Version

Minecraft Bedrock 1.20.51

### Additional Context

I remember that this happened before and it was reported, I assumed that it was solved since that's what you guys said, I still didn't update it because I was afraid of this, only now that many players are complaining about the new version I tried to update it and PUM, I see that this problem is still happening, and we are talking about a quite noisy problem since it confuses players very often and they have to re-enter until it recognizes them as bedrock players

**Comment by Zos-Mahos** [comment] 2024-02-11 03:22
How many times does one have to join and re-enter for the error to occur?

**Comment by Dxzo** [comment] 2024-02-11 04:22
> How many times does one have to join and exit for the error to occur?

When I was doing the tests this occurred between 6 to 11 attempts.

I have to add something else: I made the decision to update in production anyway on 08/02 at night since my players were complaining about the new version, and today 10/02 something strange happened, early on it started to reduce this problem and practically now it is no longer happening, this behavior is quite strange since I have not made any changes on the server that are related. In a few hours I will have the server restart automatically and I will see how it goes.

**Comment by ThisisZeth** [comment] 2024-02-11 09:41
> > How many times does one have to join and exit for the error to occur?
> 
> When I was testing this occurred between 6 to 11 attempts, but in production are more frequent since there are several players connecting and leaving.
> 
> I have to add something else: I made the decision to update in production anyway on 08/02 at night since my players were complaining about the new version, and today 10/02 something strange happened, early on it started to reduce this problem and practically now it is no longer happening, this behavior is quite strange since I have not made any changes on the server that are related. In a few hours I will have the server restart automatically and I will see how it goes.

You only update Geyser to build 429?

**Comment by Dxzo** [comment] 2024-02-11 19:01
> > > How many times does one have to join and exit for the error to occur?
> > 
> > 
> > When I was testing this occurred between 6 to 11 attempts, but in production are more frequent since there are several players connecting and leaving.
> > I have to add something else: I made the decision to update in production anyway on 08/02 at night since my players were complaining about the new version, and today 10/02 something strange happened, early on it started to reduce this problem and practically now it is no longer happening, this behavior is quite strange since I have not made any changes on the server that are related. In a few hours I will have the server restart automatically and I will see how it goes.
> 
> You only update Geyser to build 429?

Yes, but in reality I already noticed this since I updated to geyser 1.20.51 support, from 1.20.50 backwards there are no problems, that is why I had not updated it until recently with this new version thinking that it would no longer happen . Also, testing with the old jars does not happen.

**Comment by Dxzo** [comment] 2024-02-11 19:15
> > How many times does one have to join and exit for the error to occur?
> 
> When I was testing this occurred between 6 to 11 attempts, but in production are more frequent since there are several players connecting and leaving.
> 
> I have to add something else: I made the decision to update in production anyway on 08/02 at night since my players were complaining about the new version, and today 10/02 something strange happened, early on it started to reduce this problem and practically now it is no longer happening, this behavior is quite strange since I have not made any changes on the server that are related. In a few hours I will have the server restart automatically and I will see how it goes.

By the way, after the reboot occurred the issue still occurs

**Comment by Dxzo** [comment] 2024-02-13 23:42
My only "solution" at the moment was to disable the automatic restart of the server, and it still happens sometimes. Any update of the issue?

**Comment by Dxzo** [comment] 2024-02-14 16:35
This issue does not happen with velocity...

**Comment by onebeastchris** [comment] 2024-03-02 17:30
Closing this issue as it's a duplicate of https://github.com/GeyserMC/Geyser/issues/4403 - thanks anyways for reporting.

**Closed by onebeastchris** 2024-03-02 17:30 UTC
