### ISSUE TITLE
Incorrect weather sync

### ISSUE THREAD

**Issue by MishkoFreid** [GeyserMC/Geyser#2704] opened 2021-12-16 01:20 UTC
### Describe the bug

When on java it is a snow weather, on bedrock it is a rainy.
Im using realisticseasons plugin to make different seasons in my world, and for some reason it is not synced on both platforms
And according to the developer of this plugin, this is a bug on your side, not on the plugin side.

### To Reproduce

1.
2.
3.
4.
5.

### Expected behaviour

When on java it is a snow weather, on bedrock it is a rainy.
Im using realisticseasons plugin to make different seasons in my world, and for some reason it is not synced on both platforms
And according to the developer of this plugin, this is a bug on your side, not on the plugin side.

### Screenshots / Videos

![eb0a356a9df269f7](https://user-images.githubusercontent.com/96202762/146289897-9db0a2e3-d5fa-4103-87a9-c1117a0373f3.png)

### Server Version and Plugins

PaperSpigot 1.18.1 build #76
Geysermc 1.18.1 build #967
Floodgate installed: yes

### Geyser Version

Geysermc 1.18.1 build #967

### Minecraft: Bedrock Edition Version

1.18.0.02

**Comment by Chew** [comment] 2021-12-16 02:16
Duplicate of #2499/#2588 (likely one of them). To our knowledge, this is a bedrock issue.

**Comment by Camotoy** [comment] 2021-12-16 02:21
I requested this person open the issue; this may be a biome mapping issue as a result of 1.18.

**Comment by MishkoFreid** [comment] 2021-12-16 02:27
> I requested this person open the issue; this may be a biome mapping issue as a result of 1.18.

When i change the season, all biomes transform to something like "realisticseasons:winter_plains" or "realisticseasons:summer_plains". Maybe this bug happens because Geyser didn't see this changes, and see only vanilla snow biomes?

**Comment by Carbuino** [comment] 2021-12-16 07:35
> I requested this person open the issue; this may be a biome mapping issue as a result of 1.18.

I was poking around at the mappings and from what I can tell, the new 1.18 biomes aren't included in the 'biome_definitions.dat' or the 'biomes.json' in the mappings submodule? Normally, I would change this on my end to test if it fixes the problem but I can't seem to open the biome_definitions.dat in anything more readable than a Hex editor.

**Comment by MishkoFreid** [comment] 2021-12-17 20:27
> > I requested this person open the issue; this may be a biome mapping issue as a result of 1.18.
> 
> I was poking around at the mappings and from what I can tell, the new 1.18 biomes aren't included in the 'biome_definitions.dat' or the 'biomes.json' in the mappings submodule? Normally, I would change this on my end to test if it fixes the problem but I can't seem to open the biome_definitions.dat in anything more readable than a Hex editor.

Can i fix my bug? Or what i can do

**Comment by Carbuino** [comment] 2021-12-18 00:15
> Can i fix my bug? Or what i can do

I have a working fix right now, I just need to file a push request. I still need to test it on 1.17 though.

**Comment by MishkoFreid** [comment] 2021-12-19 11:24
> > Can i fix my bug? Or what i can do
> 
> I have a working fix right now, I just need to file a push request. I still need to test it on 1.17 though.

And how i can install it, what i need to replace

**Comment by Konicai** [comment] 2022-01-21 23:32
I believe this is fixed from the PR listed here that was merged back in December. Let us know if you're still having this issue!

**Closed by Konicai** 2022-01-21 23:32 UTC
