### ISSUE TITLE
nogravity entity flag broken

### ISSUE THREAD

**Issue by Maximillus** [GeyserMC/Geyser#1628] opened 2020-12-05 00:16 UTC
**Describe the bug**
spawn an entity with nogravity flag, in java it will not fall but in the bedrock it falls

Actual behavior
entity falls continuously 
Server Version
paper 1.16.4

Geyser Version
Geyser version 1.2.0-SNAPSHOT

Minecraft: Bedrock Edition Version
1.16.100

**Comment by User2573** [comment] 2020-12-09 22:56
That’s because bedrock doesn’t have any data tag equivalent of java’s “NoGravity”

**Comment by rtm516** [comment] 2020-12-09 23:43
> That’s because bedrock doesn’t have any data tag equivalent of java’s “NoGravity”

Yes there is, there is a `HAS_GRAVITY` flag. I'm unsure what effect this has on most entities but it doesn't work with falling sand entities.

**Comment by RednedEpic** [comment] 2020-12-11 23:19
Unable to reproduce. 
![image](https://user-images.githubusercontent.com/29153871/101963712-fede0200-3bd4-11eb-97cf-47b7e206e083.png)

**Comment by RednedEpic** [comment] 2020-12-12 08:29
Coming back to this again, I've tested with multiple entity types just to be safe, and I am also unable to reproduce. This may have been a result of some client bugs in 1.16.100 due to the fact that it broke some things with entity movement, but using 1.16.200 those have been fixed. Closing.

**Closed by RednedEpic** 2020-12-12 08:29 UTC
Labels: Unconfirmed Bug
