### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by TypicalShavonne** [GeyserMC/Geyser#3982] opened 2023-07-14 14:29 UTC
### Describe the bug

The error spit out in console
```[21:15:07 ERROR] [org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec]: Error encoding packet LevelSoundEvent2Packet(sound=TABLE_USE, position=(2319.5, 78.5, -1174.5), extraData=-1, identifier=:, babySound=false, relativeVolumeDisabled=false)
org.cloudburstmc.protocol.bedrock.codec.PacketSerializeException: Error whilst serializing LevelSoundEvent2Packet(sound=TABLE_USE, position=(2319.5, 78.5, -1174.5), extraData=-1, identifier=:, babySound=false, relativeVolumeDisabled=false)
        at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryEncode(BedrockCodec.java:80) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.encode(BedrockPacketCodec.java:39) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.encode(BedrockPacketCodec.java:19) ~[?:?]
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[velocity-3.2.0-SNAPSHOT-259.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[velocity-3.2.0-SNAPSHOT-259.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[velocity-3.2.0-SNAPSHOT-259.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[velocity-3.2.0-SNAPSHOT-259.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[velocity-3.2.0-SNAPSHOT-259.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[velocity-3.2.0-SNAPSHOT-259.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[velocity-3.2.0-SNAPSHOT-259.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[velocity-3.2.0-SNAPSHOT-259.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[velocity-3.2.0-SNAPSHOT-259.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[velocity-3.2.0-SNAPSHOT-259.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
        at org.cloudburstmc.protocol.bedrock.BedrockPeer.onTick(BedrockPeer.java:91) ~[?:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[velocity-3.2.0-SNAPSHOT-259.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:159) ~[velocity-3.2.0-SNAPSHOT-259.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[velocity-3.2.0-SNAPSHOT-259.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[velocity-3.2.0-SNAPSHOT-259.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity-3.2.0-SNAPSHOT-259.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[velocity-3.2.0-SNAPSHOT-259.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.2.0-SNAPSHOT-259.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.2.0-SNAPSHOT-259.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.2.0-SNAPSHOT-259.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: No id found for TABLE_USE
        at org.cloudburstmc.protocol.common.util.Preconditions.checkArgument(Preconditions.java:207) ~[?:?]
        at org.cloudburstmc.protocol.common.util.TypeMap.getId(TypeMap.java:39) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.v332.serializer.LevelSoundEventSerializer_v332.serialize(LevelSoundEventSerializer_v332.java:18) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.v332.serializer.LevelSoundEventSerializer_v332.serialize(LevelSoundEventSerializer_v332.java:12) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryEncode(BedrockCodec.java:78) ~[?:?]
        ... 23 more```

### To Reproduce

Not sure

### Expected behaviour

No error

### Screenshots / Videos

_No response_

### Server Version and Plugins

_No response_

### Geyser Dump

https://dump.geysermc.org/cDbp3XfjIgtd8bipceHEKHn2OpcUBBJ6

### Geyser Version

2.1.2-SNAPSHOT (git-master-3a0c1b7)

### Minecraft: Bedrock Edition Device/Version

1.20.10

### Additional Context

_No response_

**Comment by onebeastchris** [comment] 2023-07-14 14:33
Duplicate of https://github.com/GeyserMC/Geyser/issues/3969, thanks anyways.

**Closed by onebeastchris** 2023-07-14 14:33 UTC
