### ISSUE TITLE
Transparent player skin issues - second layer transparency

### ISSUE THREAD

**Issue by chenxi050402** [GeyserMC/Geyser#2185] opened 2021-04-30 09:07 UTC
### Describe the bug

On the Java edition transparency is allowed on the second layer of the skin. When I play on Java edition the layer is displayed correctly, but when using Geyser, the transparency value is lost and the glasses are completely black.

### To Reproduce

1. Change skin to one that has a transparent 2nd layer e.g. the one on my username.
2. Log on to a server and open survival inventory to see results.

### Expected behaviour

The transparency is just fine

### Server Version and Plugins

CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Paper version git-Paper-478 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Plugins (11): BungeeTabListPlus, CoreProtect, Essentials, FastAsyncWorldEdit (WorldEdit), ImageOnMap, LuckPerms, OpenInv, PlaceholderAPI, PlugMan, Rotten_Flesh_to_Leather*, SkinsRestorer

### Geyser Version

1.2.1-SNAPSHOT (git-master-7d80dff)

### Additional Context

Not to be confused with issue #1888.

**Comment by Camotoy** [comment] 2021-04-30 14:13
If I am correct, this is a Bedrock limitation, but there has been interest in fixing this via the upcoming GeyserOptionalPack.

**Comment by Kas-tle** [comment] 2021-04-30 22:09
Hello,

On testing I've found that the translucency info seems to be dumped somewhere along the line before the texture is rendered on the player model. I can switch the material of the player model and this indeed does produce a visual changed (confirmed by switching to charged_creeper, which is quite distinct). However, switching to entity_alphablend, which should render with translucency, does nothing. This leads me to believe that there is some funny business going on before the image is actually applied to the player entity.

Creating a clean entity with the same image and specifying alphablend with the same skin file does indeed render how one would expect. As such, I do not believe optionalpack can fix this unless Mojang happens to change this.

This is also tracked by https://bugs.mojang.com/browse/MCPE-31500 and has an ADO, meaning that Mojang is also tracking it internally, so it is possible this will eventually be fixed on the vanilla end. As such, missing client feature is the appropriate tag here for now. Please do up-vote the Jira issue if you have the chance, as it increases the likelihood Mojang will address it.

**Comment by RednedEpic** [comment] 2022-04-23 17:09
Missing client feature which we can't do much about. Please upvote the issue on Jira & comment stating this is still an issue so Mojang is more likely to see it.

**Closed by RednedEpic** 2022-04-23 17:09 UTC
Labels: Missing Client Feature
