### ISSUE TITLE
Support custom skulls in the "minecraft:item_display" command

### ISSUE THREAD

**Issue by SiderealEmu** [GeyserMC/Geyser#5071] opened 2024-10-05 17:25 UTC
### What feature do you want to see added?

Feature:
Allow skulls to be visible when they are attached to an item_display and the item_display itself is a passenger of an entity.

Justification:
There are a good amount of datapacks that create custom mobs, by simply spawning a passive entity, setting the visibility of the entity to null, then attaching a custom player head via an item_display that is a passenger of the entity. If geyser had the ability to support item display (or just a workaround) it would allow for an easy way for bedrock clients to get new custom mobs by simply just registering the skull. I know that bedrock does not natively support item_displays, but nor does it support custom skulls natively. I would think that somehow, geysermc could see the incoming item_display command and instead just use a custom block and then attach it to the non-humanoid mob just like how skulls are done on mobs that have head slots.

### Are there any alternatives?

Skull are visible to bedrock clients if they are attached to anything other than an item_display or block_display. I have not been able to find a successful alternative in a minecraft java command that would yield similar results. Thus allowing for modification in geysermc itself.

**Comment by onebeastchris** [comment] 2024-10-07 18:12
Closing as this is a duplicate of https://github.com/GeyserMC/Geyser/issues/3810 - thanks anyways.

**Closed by onebeastchris** 2024-10-07 18:12 UTC
Labels: Feature Request
