### ISSUE TITLE
Skin Uploading floodgate 2.0 and GSM

### ISSUE THREAD

**Issue by TheBingPlays** [GeyserMC/Geyser#2091] opened 2021-03-31 18:35 UTC
### Describe the bug

Im having an issue with floodgate 2.0. skins are still not uploading and still appear as steve and alex. I though GeyserSkinManager would fix this problem but it is not. Im getting this stacktrace error. GeyserSkinManager is enabled

### To Reproduce

Starting server and joining on bedrock client

### Expected behaviour

Skin uploading to server and java being able to see it

### Screenshots / Videos

[14:04:35] [Netty Server IO #2/INFO]: UUID of player TheBingPlays is fc421d35-3aa1-4311-bd41-be228102341d
[14:04:35] [Server thread/INFO]: [floodgate] Floodgate player logged in as TheBingPlays joined (UUID: fc421d35-3aa1-4311-bd41-be228102341d)
[14:04:35] [WebSocketConnectReadThread-318/INFO]: [Geyser-Spigot] Got disconnected from the skin uploader: invalid geometry: the image width and height doesn't match the geometry data width and height
[14:04:36] [WebSocketConnectReadThread-351/INFO]: [floodgate] Got disconnected from the skin uploader: failed to find the given code in combination with the verify code
[14:04:36] [Server thread/INFO]: TheBingPlays[/192.168.1.1:63048] logged in with entity id 3879 at ([world]56.10616, 69.91944122314453, -52.19224)
[14:04:36] [pool-26-thread-1/WARN]: [GeyserSkinManager] Failed to upload player skin for fc421d35-3aa1-4311-bd41-be228102341d
[14:04:36] [pool-26-thread-1/WARN]: java.util.concurrent.CompletionException: java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
[14:04:36] [pool-26-thread-1/WARN]:     at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
[14:04:36] [pool-26-thread-1/WARN]:     at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
[14:04:36] [pool-26-thread-1/WARN]:     at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
[14:04:36] [pool-26-thread-1/WARN]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:04:36] [pool-26-thread-1/WARN]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:04:36] [pool-26-thread-1/WARN]:     at java.lang.Thread.run(Unknown Source)
[14:04:36] [pool-26-thread-1/WARN]: Caused by: java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
[14:04:36] [pool-26-thread-1/WARN]:     at sun.awt.image.IntegerInterleavedRaster.setDataElements(Unknown Source)
[14:04:36] [pool-26-thread-1/WARN]:     at java.awt.image.BufferedImage.setRGB(Unknown Source)
[14:04:36] [pool-26-thread-1/WARN]:     at com.github.camotoy.geyserskinmanager.common.SkinUtils.toBufferedImage(SkinUtils.java:184)
[14:04:36] [pool-26-thread-1/WARN]:     at com.github.camotoy.geyserskinmanager.common.SkinUploader.uploadSkinInner(SkinUploader.java:57)
[14:04:36] [pool-26-thread-1/WARN]:     at com.github.camotoy.geyserskinmanager.common.SkinUploader.lambda$uploadSkin$0(SkinUploader.java:45)
[14:04:36] [pool-26-thread-1/WARN]:     ... 4 more

### Server Version and Plugins

1.16.1

### Geyser Dump

https://dump.geysermc.org/UGyOgSGPmtCzOPWvislLW1FO7gX7nkNj

### Geyser Version

Build 657

### Minecraft: Bedrock Edition Version

Latest as of 3/31/2021

**Comment by Konicai** [comment] 2021-03-31 19:34
GSM shouldn't be used with floodgate 2.0 and won't fix the issue

**Comment by TheBingPlays** [comment] 2021-03-31 19:47
> GSM shouldn't be used with floodgate 2.0 and won't fix the issue.
> 
> Can you send a link to the skin?

https://minecraftskinstealer.com/profile/TheBingPlays

**Comment by AllThingsBroken** [comment] 2021-03-31 19:57
I'm having this issue as well with all bedrock players because of "Got disconnected from the skin uploader: invalid geometry: the image width and height doesn't match the geometry data width and height"

**Comment by Tim203** [comment] 2021-03-31 20:02
> I'm having this issue as well with all bedrock players because of "Got disconnected from the skin uploader: invalid geometry: the image width and height doesn't match the geometry data width and height"

It'd be nice to get the actual skin and geometry data of those skins. I've introduced it on purpose because it gave errors. I just need to know if it can happen legitimately and how to work around it if it does.

**Comment by AllThingsBroken** [comment] 2021-03-31 20:44
I think I found the problem! "Slim" bedrock skins will cause the geometry problem. I changed my skin to normal and it was fine.

**Comment by TheBingPlays** [comment] 2021-03-31 22:24
> "Slim" bedrock skins will cause the geometry problem. I changed my skin to normal and it was fine.

Setting the skin to slim did not fix the issue for me :(

**Comment by Konicai** [comment] 2021-03-31 22:27
> 
> 
> > "Slim" bedrock skins will cause the geometry problem. I changed my skin to normal and it was fine.
> 
> Setting the skin to slim did not fix the issue for me :(

Neither for me, using TheBingPlay's skin.

**Comment by Tim203** [comment] 2021-03-31 22:33
Alex or steve shouldn't matter for that part.
I concluded that I have to rewrite some parts of the skin converter code, which can take a bit of time.
I'll write another comment here when it's able to be used.

**Comment by adamsarba** [comment] 2021-08-03 14:40
@Tim203 Hi, any news? I'm using floodgate, had problem with wrong skin geometry but changed it to wide version (in Bedrock) and I don't have any errors in console any more. But! After over a week skin is still invisible on our server 😕

**Comment by Tim203** [comment] 2021-08-03 14:49
Not yet, other stuff had higher priority because the skin converter does work even though it isn't perfect.
And about the queue: the queue resets every time the global api restarts, and that happens most of the time at least once a week.
It's just unfortunate for everyone that the skin upload service is so popular and we're actively trying to improve it.
I expect that it's only a matter of time until the queues should lower, because more skins had the time to be uploaded.

**Comment by FranGamer1892** [comment] 2022-03-29 02:17
Any updates on this? I can't believe this functionality is so incomplete...

**Comment by RednedEpic** [comment] 2022-04-23 17:01
We've been working with Mineskin & they've greatly improved the way that skin uploading is done on their end. We've also done a set of changes & to my knowledge have received no further reports on this. Please open a new issue with _detailed_ and updated information on how this bug can be reproduced (please send skin geo + image). Closing.

**Closed by RednedEpic** 2022-04-23 17:01 UTC

**Comment by veetack1** [comment] 2024-06-15 20:14
actually
