### ISSUE TITLE
The client gets stuck when the op enters /

### ISSUE THREAD

**Issue by pbs666** [GeyserMC/Geyser#570] opened 2020-05-15 20:12 UTC
Op gets stuck when entering a new world and typing/in the chat bar. This problem affects the server administrator managing the server because the server administrator often needs to transfer and use commands between the world. You have to wait 3 to 5 minutes for every jam to return to normal, which seriously slows down the efficiency. I hope you can fix it as soon as possible, because this bug has a big impact on the server and has been there for a long time.

**Comment by RednedEpic** [comment] 2020-05-15 20:13
> Op gets stuck when entering a new world and typing/in the chat bar. This problem affects the server administrator managing the server because the server administrator often needs to transfer and use commands between the world. You have to wait 3 to 5 minutes for every jam to return to normal, which seriously slows down the efficiency. I hope you can fix it as soon as possible, because this bug has a big impact on the server and has been there for a long time.

Please follow the issue template.

**Comment by DoctorMacc** [comment] 2020-05-15 20:15
Closing because this is a duplicate of #405. If you feel this is incorrect, please let us know.

**Closed by DoctorMacc** 2020-05-15 20:15 UTC
