### ISSUE TITLE
Increased server resources on connection

### ISSUE THREAD

**Issue by madrig88** [GeyserMC/Geyser#377] opened 2020-04-19 06:43 UTC
**Describe the bug**
I use a vanilla Minecraft server and a standalone Geyser instance. When we have multiple people on the Minecraft server using the Java version, the Resources used increase significantly once the Bedrock version connects. When this happens, the server goes from approx 4-10% CPU, up to about 95-100% CPU usage. This can get bad enough to prevent you from opening chests, opening gates in fences, or even using beds without affecting the Java players at all. When there are only a couple people on the server, it still happens, it just takes a lot longer.

More info in the Additional context

**To Reproduce**
1. Log in to Geyser using Xbox One
2. Notice there are 6+ people on remote vanilla server
3. Try to break blocks, open chests, sleep in beds.

**Expected behavior**
Open Chests, Gates, sleep in beds.

**Server Version**
Vanilla Minecraft Server 1.15.2

**Geyser Version**
Geyser Build #24 Inventory Branch Standalone

**Minecraft: Bedrock Edition Version**
Bedrock Version 1.14.60 Xbox One

**Additional Context**
Xbox One is on the same network as Geyser Standalone and that forwards to the Java server on a different network via domain name. We are trying to keep the server Vanilla and not use plugins hence the use of the standalone version.

**Comment by RednedEpic** [comment] 2020-04-19 06:49
> **Describe the bug**
> I use a vanilla Minecraft server and a standalone Geyser instance. When we have multiple people on the Minecraft server using the Java version, the Resources used increase significantly once the Bedrock version connects. When this happens, the server goes from approx 4-10% CPU, up to about 95-100% CPU usage. This can get bad enough to prevent you from opening chests, opening gates in fences, or even using beds without affecting the Java players at all. When there are only a couple people on the server, it still happens, it just takes a lot longer.
> 
> More info in the Additional context
> 
> **To Reproduce**
> 
> 1. Log in to Geyser using Xbox One
> 2. Notice there are 6+ people on remote vanilla server
> 3. Try to break blocks, open chests, sleep in beds.
> 
> **Expected behavior**
> Open Chests, Gates, sleep in beds.
> 
> **Server Version**
> Vanilla Minecraft Server 1.15.2
> 
> **Geyser Version**
> Geyser Build #24 Inventory Branch Standalone
> 
> **Minecraft: Bedrock Edition Version**
> Bedrock Version 1.14.60 Xbox One
> 
> **Additional Context**
> Xbox One is on the same network as Geyser Standalone and that forwards to the Java server on a different network via domain name. We are trying to keep the server Vanilla and not use plugins hence the use of the standalone version.

Just tested this myself, and Geyser in most cases is using around 1% - 3% of the CPU on average, and no more than 5% during world or server switches. Could you please run a profiler so we can see what exactly is going up?

**Comment by madrig88** [comment] 2020-04-19 06:57
Could you walk me through this? I'm not the one hosting the Minecraft Server. Also, just to make sure we are on the same page, Geyser itself is not using high resources, however, when it connects to the Vanilla server, it causes the server to increase its resource use. we can have 20 Java people on the server and it doesn't use as many resources as 1 Bedrock connection to the server. Not sure if this is known or not.

**Comment by RednedEpic** [comment] 2020-04-19 06:58
> Could you walk me through this? I'm not the one hosting the Minecraft Server. Also, just to make sure we are on the same page, Geyser itself is not using high resources, however, when it connects to the Vanilla server, it causes the server to increase its resource use. we can have 20 Java people on the server and it doesn't use as many resources as 1 Bedrock connection to the server. Not sure if this is known or not.

Ah, so even if Geyser is on a separate machine it causes the Java server to do this?

**Comment by madrig88** [comment] 2020-04-19 06:59
Correct. In fact I even hosted a vanilla server on my local computer and everything seemed to work smoothly, aside from the other issues I've submitted.

**Comment by RednedEpic** [comment] 2020-04-19 07:05
> Correct. In fact I even hosted a vanilla server on my local computer and everything seemed to work smoothly, aside from the other issues I've submitted.

Just gave this a test on Paper and was unable to reproduce. Since you mentioned this was on vanilla, I'm not yet going to close this issue, however the fact that Geyser is causing the server to go up to 95% - 100% from your testing seems like a pretty big deal. If possible, I would recommend swapping over to Paper as it not only opens the door for plugins in the future, but also substantially improves performance just in general compared to vanilla. If this is a decision you decide to make, report back here and let us know if anything changes.

**Comment by DoctorMacc** [comment] 2020-04-19 17:08
I believe this is the same person that was talking to me describing bugs that happened on a vanilla Minecraft server and not Paper. If this is true then we should look into this.

**Comment by madrig88** [comment] 2020-04-19 18:06
Yes, I did reach out to you yesterday, and I spoke with the admin of the Minecraft server, and he is not inclined to use a server outside of vanilla, but finds the capability of allowing Bedrock users somewhat important.

What information do you need from us?

**Comment by Heath123** [comment] 2020-04-19 18:09
> Yes, I did reach out to you yesterday, and I spoke with the admin of the Minecraft server, and he is not inclined to use a server outside of vanilla, but finds the capability of allowing Bedrock users somewhat important.
> 
> What information do you need from us?

The vanilla server has really bad performance and features. There's not really a good reason to use it unless Paper/Spigot isn't out for the version you're using.

**Comment by DoctorMacc** [comment] 2020-04-19 18:10
Correct, but that doesn't mean we shouldn't be supporting the,

@madrig88 What would be helpful is a list of everything different between vanilla Minecraft servers and Paper servers.

**Comment by Heath123** [comment] 2020-04-19 18:11
> Correct, but that doesn't mean we shouldn't be supporting them.
> 
> @madrig88 What would be helpful is a list of everything different between vanilla Minecraft servers and Paper servers.

Of course we should support it. I just mean in general it's not a good idea.

**Comment by ARMmaster17** [comment] 2020-04-21 01:35
I can confirm that this same issue exists for the latest stable build of Spigot as well as vanilla server. Geyser was running on a separate machine and CPU usage shot up and kicked out everyone. This was on a shared-hosting platform. Ran Spigot and Geyser in separate VMs on my own hardware and saw similar trends.

**Comment by RednedEpic** [comment] 2020-04-21 01:37
> I can confirm that this same issue exists for the latest stable build of Spigot as well as vanilla server. Geyser was running on a separate machine and CPU usage on the vanilla server shot up and kicked out everyone. This was on a shared-hosting platform. Ran Spigot and Geyser in separate VMs on my own hardware and saw similar trends.
> 
> Edit: Also I was running the latest Geyser build from Inventory Branch Standalone as of yesterday at noon EST.

Could you test this with Paper too?

**Comment by ARMmaster17** [comment] 2020-04-21 01:56
Issues does not seem to be present on Paper. Tested using Paper build 201. Same Geyser build as above. CPU never goes above 20% (the spike is Ansible doing container setup).
![image](https://user-images.githubusercontent.com/4678601/79816692-d0639c00-8351-11ea-94b5-adcd1d5a43b5.png)

**Comment by DoctorMacc** [comment] 2020-04-21 02:10
If you have time, could you test if there is any difference with vanilla/Spigot and master? We have different bug reports about signs not working on Spigot - I wonder if they are related.

**Comment by ARMmaster17** [comment] 2020-04-23 01:11
Not sure what's going on with my Spigot image, but I just tested with Vanilla (1.15.2) and the latest build of Geyser (master/build 71).

![image](https://user-images.githubusercontent.com/4678601/80048229-932c1500-84dd-11ea-8a46-f6ff74282861.png)

Brand new server, everything left at default. Geyser and Vanilla server are running on the same machine, but Geyser is running in standalone mode.

Some heavy CPU spikes when the bedrock client loaded in, but then it averaged out to ~15% CPU utilization. Problem does not seem to exist on latest master build.

**Comment by DoctorMacc** [comment] 2020-04-23 01:31
@ARMmaster17 so from your wording, is your problem fixed, or am I misunderstanding?

**Comment by ARMmaster17** [comment] 2020-04-23 01:52
@DoctorMacc It appears that from the latest build from the master branch the original issue of the CPU usage shooting up to 100% is not present. So yes, I believe the issue has been fixed on master.

**Comment by DoctorMacc** [comment] 2020-04-23 01:55
Hmm, that's good, although I don't know what would have changed.

@madrig88 can you re-test?

**Comment by DoctorMacc** [comment] 2020-04-29 16:33
Closing unless we get more information.

**Closed by DoctorMacc** 2020-04-29 16:33 UTC
Labels: More Info Needed

**Comment by madrig88** [comment] 2020-04-29 17:23
My apologies, I have been unavailable for the last week, I will test this evening when I have access to the Xbox I am testing with.

Thank you so far for your efforts.
