### ISSUE TITLE
Pre 1.13 server, client crash when trade

### ISSUE THREAD

**Issue by diamond-gold** [GeyserMC/Geyser#1163] opened 2020-08-17 16:52 UTC
**Describe the bug**
Trying to trade with a villager on a server that is pre 1.13 causes client to crash, 1.16.1 java client have no issue

**To Reproduce**
Try to trade with a villager in a pre 1.13 server

**Expected behavior**
It should be able to trade.

**Server Version**
This server is running CraftBukkit version git-Spigot-79a30d7-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Tested in 1.8 server, same issue
ViaVersion 3.1.0

**Geyser Version**
Build 332

**Minecraft: Bedrock Edition Version**
1.16.2

**Additional Context**

**Comment by DoctorMacc** [comment] 2020-08-17 18:01
Thanks for the report! However, this is a duplicate of #747.

**Closed by DoctorMacc** 2020-08-17 18:01 UTC
