### ISSUE TITLE
Chunks stop loading after walking around.

### ISSUE THREAD

**Issue by CrebitKarma** [GeyserMC/Geyser#4772] opened 2024-06-19 06:07 UTC
### Describe the bug

Chunks stop loading in for bedrock players, they generate but cannot be seen.
I use Geyser Standalone.

### To Reproduce

Run a fabric server.
Run Geyser.
Should see after moving around for a bit.

### Expected behaviour

Chunks continue to be seen and generated.

### Screenshots / Videos

![IMG_3877](https://github.com/GeyserMC/Geyser/assets/173233031/0b8547e6-3dca-450b-9044-4e699cb6a26e)

### Server Version and Plugins

1.20.4 Fabric
Chunk mods:
C2ME
Lithium
Other mods of interest:
ViaVersion
I also have other mods but they are all for optimization.

### Geyser Dump

https://dump.geysermc.org/AbiN7BqoCQ2XmNkB3L45g1XW1h55mpVX

### Geyser Version

2.4.0-SNAPSHOT (git-master-63a3da7)

### Minecraft: Bedrock Edition Device/Version

1.21, Windows, MCPE, haven't tried other devices.

### Additional Context

I'm using Geyser Standalone.

**Comment by Camotoy** [comment] 2024-06-22 00:18
Hello! Can you try the builds here and see if it fixes your issue? https://github.com/GeyserMC/Geyser/actions/runs/9607076730

**Comment by rorychatt** [comment] 2024-06-25 08:25
Also mentioned here

https://github.com/GeyserMC/Geyser/issues/4678#issuecomment-2184198768

**Comment by onebeastchris** [comment] 2024-07-04 16:18
Duplicate of https://github.com/GeyserMC/Geyser/issues/3809 - closing this issue. Thanks for reporting it!

**Closed by onebeastchris** 2024-07-04 16:18 UTC
Labels: Waiting On Response
